Update git submodules
* Update platform/build/soong from branch 'master'
  to 2bb2017a30604ede139d0608cea9622797601c0a
  - Merge "Use packagepath and local_repository for mixed builds"
  - Use packagepath and local_repository for mixed builds
    
    This allows mixed builds to continue functioning even given the toplevel
    WORKSPACE file containing toplevel_output_directories with out/.
    
    Test: Manually verified on aosp_flame building libc.
    Change-Id: I80fc4853421317e2d2c7f03d92d58286df1342ce
    

* Update platform/superproject from branch 'master'
  to 29558b9e1c965e7c46fbcfbaeb60a9d87d7c7d07
  - Update git submodules
    
    * Update build/soong from branch 'master'
      to 2bb2017a30604ede139d0608cea9622797601c0a
      - Merge "Use packagepath and local_repository for mixed builds"
      - Merge "rust: Add header library support to rust_bindgen."
      - Merge "add PackagingSpec"
      - Merge "Revert "Always turn on compatible property""
      - Revert "Always turn on compatible property"
        
        This reverts commit f6d606ebea3334bdf00148639edcc8378c3b8861.
        
        Reason for revert: broken targets on the internal branch
        
        Change-Id: I948280e2072789a2ee20e7fe4844c667f58b5182
        
      - Merge "soong_ui finder.go: improve comments/documentation."
      - Merge "Always turn on compatible property"
      - Merge "Document usage, perform minor cleanups."
      - Merge "Integrate bazelenv.sh environment variables into soong_ui environment."
      - Merge "Add unit_test test option in test configs"
      - add PackagingSpec
        
        Currently, installation of a module is defined as an action of copying
        the built artifact of the module to an install path like out/soong/host
        (for host modules) and out/target/product/<device>/<partition> (for
        device modules). After the modules are installed, the installed files
        are further processed to create packages like system.img, vendor.img,
        cvd-host-package.tar.gz, etc.
        
        This notion of installation seems to have originated from the old time
        when system.img is the primary product of the entire build process
        (modulo a few more like root.img). Packaging the installed files as the
        filesystem image was considered as a post-build step then.
        
        However, this model doesn't seem to fit well to the current and future
        environment where we have a lot more filesystem images (system, vendor,
        system_ext, product, ...). The filesystem images themselves are even
        grouped together to form a higher-level filesystem image like super.img.
        Furthermore, things like cvd-host-package.tar.gz requires us to be able
        to group some of the host tools in a format that isn't filesystem image.
        Lastly, we are expected to have more filesystem images that are subsets
        of system.img (and their friends) for the Android-like mini OS that will
        be running on on-device virtual machines. These all imply that the
        packaging (which we call installation today) is not a global post-build
        step, but a part of the build rules for creating the package-like
        modules.
        
        A model better fits to the new sitatuation might be this; a module
        specifies its built artifact and the path where it should be placed. The
        latter path is not rooted at out/. It's a relative path to the root
        directory which will be determined by another module that implements the
        packaging. For example, cc_library will have ./lib (or ./lib64), not
        out/target/product/<device>/<partition>/lib as the path. Then packages
        like system.img, cvd-host-package.tar.gz, etc. are explicitly modeled as
        modules and they have deps to other modules. Then the modules are placed
        at the relative path under the package root, and the entire root
        directory finally is packaged as the output file (be it img, tar.gz, or
        whatever).
        
        PackagingSpec is the first step to implement the new model. It abstracts
        a request to place a built artifact at a certain path in a package. It
        has extra information about whether the path should be a symlink or not,
        and whether the path is for an executable. It currently is created when
        InstallFiles (and its friends) are called, and can be retrieved via
        the new method PackagingSpecs().
        
        In this CL, no one is using PackagingSpec. The installation is still
        done by the existing rules created in InstallFiles, etc. and the
        structs are not used for the filesystem images like system.img.
        
        Bug: 159685774
        Bug: 172414391
        Test: m
        
        Change-Id: Ie1dec72d1ac14382fc3b74e5c850472e9320d6a3
        
      - soong_ui finder.go: improve comments/documentation.
        
        Test: m
        Bug: 173474588
        Change-Id: I947a34b3d9a5b2cd36fba293b55860a20a11d40b
        
      - Merge "soong_ui's bazel.go: document/comment with tiny refactoring."
      - Integrate bazelenv.sh environment variables into soong_ui environment.
        
        This removes the need to source bazelenv.sh for USE_BAZEL_ANALYSIS, and
        unifies mixed builds to use the checked in tools/bazel and bazelrc.
        
        It also unifies all bazel-related output to be in out/bazel.
        
        Without aosp/1502095, this change still requires toplevel_output_directories to be an empty
        list, otherwise there'll be this error:
        
        ERROR: Directories specified with toplevel_output_directories should be
        ignored and can not be used as sources.
        
        Test: With aosp/1441774: rm -rf out/ && lunch aosp_cf_x86_auto && USE_BAZEL_ANALYSIS=1 m libc && prebuilts/build-tools/linux-x86/bin/ninja -f out/combined-aosp_cf_x86_auto.ninja -t commands libc | grep bazel-out | wc -l # 2 results
        Change-Id: I69b217ec88da531415792bb6e04b6a194ca4718d
        
      - Merge "Support for recovery snapshot."
      - Use packagepath and local_repository for mixed builds
        
        This allows mixed builds to continue functioning even given the toplevel
        WORKSPACE file containing toplevel_output_directories with out/.
        
        Test: Manually verified on aosp_flame building libc.
        Change-Id: I80fc4853421317e2d2c7f03d92d58286df1342ce
        
      - rust: Add header library support to rust_bindgen.
        
        Allow rust_bindgen modules to define dependencies that only provide
        headers and may not necessarily need to be linked in.
        
        Bug: 161141999
        Test: Soong tests pass.
        Test: Example module has appropriate include flags when compiling.
        Change-Id: Ic9ce8b1204008ad8dcb18766c914e48bb292d485
        
      - soong_ui's bazel.go: document/comment with tiny refactoring.
        
        This patch adds information behind the Bazel USE_BAZEL=1 execution
        pipeline.
        
        Test: m
        Bug: 173474588
        Change-Id: I54bdd26fb14c8a371de0922d193419112e8c3ece
        
      - Always turn on compatible property
        
        It's mandatory for devices launching with Android P or later.
        
        Bug: 170082975
        Test: m
        Change-Id: I22578c3b77d28abc8a09b88324ef3702d0ccafde
        
      - Document usage, perform minor cleanups.
        
        Test: treehugger
        Bug: 173466220
        Change-Id: I5aa09c2941c0eceb8ae635b9e613ad932d38aebb
        
      - Support for recovery snapshot.
        
        Bug: 171231437
        Test: source build/envsetup.sh
        Test: ALLOW_MISSING_DEPENDENCIES=true m -j nothing
        
        Change-Id: I6b35fbb0b90ffffa941ea108cbd31a454b2dd403
        
      - Add unit_test test option in test configs
        
        This change allows a test (native, java, rust or python) to be included
        in host-unit-tests suite when test option `unit_test` is set to true.
        
        Bug: 172006742
        Test: m host-unit-tests
        Change-Id: I69d3eb5b51198c549e2e6914ceac3a4fc33c3cf2