Update git submodules
* Update platform/frameworks/base from branch 'master'
  to 9f165ca3e1d900d9539a373550725cc5d55b2682
  - Merge "Fix Wbitwise-instead-of-logical introduced by clang-r445002"
  - Fix Wbitwise-instead-of-logical introduced by clang-r445002
    
    Bug: http://b/215753485
    
    frameworks/base/cmds/incidentd/src/WorkDirectory.cpp:283:38: error: use of bitwise '|' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
                report->set_all_sections(report->all_sections() | args.all());
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                ||
    frameworks/base/cmds/incidentd/src/WorkDirectory.cpp:283:38: note: cast
    one or both operands to int to silence this warning
    
    Test: Build with new clang
    Change-Id: I8dc614e274c95f8941bf390cb68c60d0328bb31b