Update git submodules
* Update platform/cts from branch 'master'
  to ee991403a178621a0dcbebce4a647a7f345deeb9
  - Merge "VpnTest: test getConnectionOwnerUid API"
  - VpnTest: test getConnectionOwnerUid API
    
    Test connection->UID resolution for both UDP and TCP connections.
    
    Bug: 9496886
    Bug: 109758967
    Test: atest HostsideVpnTests
    Change-Id: Ic17c64df74f65d788fd3d95a25af3c5b44946881
    

* Update platform/frameworks/base from branch 'master'
  to f8529dc8915f1cc2b03ad851c9b1bbbb8e5089a8
  - Merge "Add ConnectivityManager.getConnectionOwnerUid()"
  - Add ConnectivityManager.getConnectionOwnerUid()
    
    Allow VPN apps to lookup the UID owner of a network connection.
    
    Requires specifying the:
     - IP address and port for both the source and destination of a TCP
       connection.
     - IP address and port for either source and destination or just
       source for a UDP connection.
    Only TCP and UDP protocols are supported. Only connections for UIDs
    that apply to the calling VPN app will be resolved. This is intended
    to replace direct app access to /proc/net/{tcp,tcp6,udp,udp6}.
    
    The implementation uses netlink inet_diag sockets[1] to perform
    the lookup on TCP sockets as well as UDP sockets when supported
    (kernel has CONFIG_INET_UDP_DIAG=y).
    
    [1] http://man7.org/linux/man-pages/man7/sock_diag.7.html
    
    Bug: 9496886
    Bug: 109758967
    Test: atest HostsideVpnTests
    Test: atest InetDiagSocketTest on Taimen with CONFIG_INET_UDP_DIAG
        and on Sailfish without CONFIG_INET_UDP_DIAG.
    Change-Id: I2bbc7072dd091e2e653dadf6dc05024c04180f34
    

* Update platform/frameworks/opt/telephony from branch 'master'
  to 780ae8bde652d256bd9ec5abc21e970cfe3f319e
  - Merge "Stub out getConnectionOwnerUid for telephony tests"
  - Stub out getConnectionOwnerUid for telephony tests
    
    This function is already tested in CTS module HostsideVpnTests and
    unit test module InetDiagSocketTest.
    
    Fix test error:
    frameworks/opt/telephony/tests/telephonytests/src/com/android/internal/telephony/mocks/ConnectivityServiceMock.java:66:
    error: ConnectivityServiceMock is not abstract and does not override
    abstract method getConnectionOwnerUid(ConnectionInfo) in
    IConnectivityManager
    public class ConnectivityServiceMock extends IConnectivityManager.Stub
    
    Bug: 9496886
    Bug: 109758967
    Test: atest frameworks/opt/telephony/tests/telephonytests/src/com/android/internal/telephony/mocks/ConnectivityServiceMock.java
    Change-Id: I1a3275cc3417a8786bd4f09142141c64287bde80
    

* Update platform/libcore from branch 'master'
  to afbc97fd10ea0961369115814e6a8d55961654c9
  - Merge "Add NETLINK_INET_DIAG constant"
  - Add NETLINK_INET_DIAG constant
    
    For use by ConnectivityService in new getConnectionOwnerUid() API.
    
    Only system_server and netd may use this type of socket so mark as
    @hide.
    
    Bug: 9496886
    Bug: 109758967
    Test: atest HostsideVpnTests
    Change-Id: I2237a2cc17f503f287c8edbb739ff7de11f0480b
    

* Update platform/superproject from branch 'master'
  to 335d7ab55edea38e1bd6562b6bb29865bfa2b562
  - Update git submodules
    
    * Update cts from branch 'master'
      to ee991403a178621a0dcbebce4a647a7f345deeb9
      - Merge "VpnTest: test getConnectionOwnerUid API"
      - VpnTest: test getConnectionOwnerUid API
        
        Test connection->UID resolution for both UDP and TCP connections.
        
        Bug: 9496886
        Bug: 109758967
        Test: atest HostsideVpnTests
        Change-Id: Ic17c64df74f65d788fd3d95a25af3c5b44946881
        
    
    * Update frameworks/base from branch 'master'
      to f8529dc8915f1cc2b03ad851c9b1bbbb8e5089a8
      - Merge "Add ConnectivityManager.getConnectionOwnerUid()"
      - Add ConnectivityManager.getConnectionOwnerUid()
        
        Allow VPN apps to lookup the UID owner of a network connection.
        
        Requires specifying the:
         - IP address and port for both the source and destination of a TCP
           connection.
         - IP address and port for either source and destination or just
           source for a UDP connection.
        Only TCP and UDP protocols are supported. Only connections for UIDs
        that apply to the calling VPN app will be resolved. This is intended
        to replace direct app access to /proc/net/{tcp,tcp6,udp,udp6}.
        
        The implementation uses netlink inet_diag sockets[1] to perform
        the lookup on TCP sockets as well as UDP sockets when supported
        (kernel has CONFIG_INET_UDP_DIAG=y).
        
        [1] http://man7.org/linux/man-pages/man7/sock_diag.7.html
        
        Bug: 9496886
        Bug: 109758967
        Test: atest HostsideVpnTests
        Test: atest InetDiagSocketTest on Taimen with CONFIG_INET_UDP_DIAG
            and on Sailfish without CONFIG_INET_UDP_DIAG.
        Change-Id: I2bbc7072dd091e2e653dadf6dc05024c04180f34
        
    
    * Update frameworks/opt/telephony from branch 'master'
      to 780ae8bde652d256bd9ec5abc21e970cfe3f319e
      - Merge "Stub out getConnectionOwnerUid for telephony tests"
      - Stub out getConnectionOwnerUid for telephony tests
        
        This function is already tested in CTS module HostsideVpnTests and
        unit test module InetDiagSocketTest.
        
        Fix test error:
        frameworks/opt/telephony/tests/telephonytests/src/com/android/internal/telephony/mocks/ConnectivityServiceMock.java:66:
        error: ConnectivityServiceMock is not abstract and does not override
        abstract method getConnectionOwnerUid(ConnectionInfo) in
        IConnectivityManager
        public class ConnectivityServiceMock extends IConnectivityManager.Stub
        
        Bug: 9496886
        Bug: 109758967
        Test: atest frameworks/opt/telephony/tests/telephonytests/src/com/android/internal/telephony/mocks/ConnectivityServiceMock.java
        Change-Id: I1a3275cc3417a8786bd4f09142141c64287bde80
        
    
    * Update libcore from branch 'master'
      to afbc97fd10ea0961369115814e6a8d55961654c9
      - Merge "Add NETLINK_INET_DIAG constant"
      - Add NETLINK_INET_DIAG constant
        
        For use by ConnectivityService in new getConnectionOwnerUid() API.
        
        Only system_server and netd may use this type of socket so mark as
        @hide.
        
        Bug: 9496886
        Bug: 109758967
        Test: atest HostsideVpnTests
        Change-Id: I2237a2cc17f503f287c8edbb739ff7de11f0480b
        
    
    * Update system/sepolicy from branch 'master'
      to 7776cc3bc598b384e83ad32a975764654363ee0c
      - Merge "system_server: add policy for getConnectionOwnerUid API"
      - system_server: add policy for getConnectionOwnerUid API
        
        Bug: 9496886
        Bug: 109758967
        Test: atest HostsideVpnTests
        Change-Id: I1716d9c740b374b861e691b31ab271c681cf6bff
        

* Update platform/system/sepolicy from branch 'master'
  to 7776cc3bc598b384e83ad32a975764654363ee0c
  - Merge "system_server: add policy for getConnectionOwnerUid API"
  - system_server: add policy for getConnectionOwnerUid API
    
    Bug: 9496886
    Bug: 109758967
    Test: atest HostsideVpnTests
    Change-Id: I1716d9c740b374b861e691b31ab271c681cf6bff