Update git submodules
* Update platform/external/tensorflow from branch 'master'
  to 2266f3eccb66934b0447176114b8fa97ab10ad4e
  - Specify "nnapi-reference" backend for the buffer handle test
    
    Fixes: 141138444
    Test: mm
    Test: NNAPIDelegate#StatefulDelegateWithBufferHandles
    Change-Id: Iab7643c9284e00db483ae2cafe3091ab04503a43
    
  - Avoid using SSE_OR_PORTABLE
    am: 9e3cbbdd7c
    
    Change-Id: Ic44b13337518fbc7e1762b6d55435aa4eadd4616
    
  - Merge remote-tracking branch 'aosp/upstream-master' into tfl_rebase
    am: e6330c9df6
    
    Change-Id: Ib9a82b1f1885261d38a904a99782d15f1f15f416
    
  - Make sure the buffers in NNAPI delegate shared memory pool are 16 bytes aligned.
    am: 119303cbdd
    
    Change-Id: Ia57604ee6628b54c6bccd16a1007c65186bf6e50
    
  - DO NOT MERGE - Merge qt-dev-plus-aosp-without-vendor (5699924) into stage-aosp-master
    
    Bug: 134405016
    Change-Id: Ia8717eede2f005aa2af987b9da1426b3b84578d0
    
  - Use normal NDK in tensorflow_headers am: e25f94d271
    am: 8182ed13f2
    
    Change-Id: I8a35493777dbc81be6ba7fd7b22d8bb2809e1721
    
  - Use normal NDK in tensorflow_headers
    am: e25f94d271
    
    Change-Id: I6482805d4f4e1d68bde5dd543800f01ea5762256
    
  - [automerger skipped] Add Android specific generated test runner. am: 19df2fb19c
    am: f697f251d4 -s ours
    am skip reason: change_id I09b5d5307b4a402c4fa166434744d7fe2f3b90cb with SHA1 ea303b6c0d is in history
    
    Change-Id: I90435a26b413ea982ed35a550bca77fd8d58aecf
    
  - [automerger skipped] Update libtflite_static to include the reference op resolver am: 8bc8c0fbd1
    am: 9cb4cc04ec -s ours
    am skip reason: change_id I72705f021aa19eb2118abac30c8de8ce50344bf4 with SHA1 39cbbcfb61 is in history
    
    Change-Id: I673eb5df640abd755c08e53a7be12665b3cad5e9
    
  - Add Android specific generated test runner.
    am: 19df2fb19c
    
    Change-Id: I299cb094a650ad7c5542e6e16e9e7566146765ad
    
  - Update libtflite_static to include the reference op resolver
    am: 8bc8c0fbd1
    
    Change-Id: Ibf7feb13115aadf583e74d336a68d699c4f2afdb
    
  - Add Android specific generated test runner.
    am: ea303b6c0d
    
    Change-Id: I6151e78fe43314d80e7cf4e6e4dbefce81bea258
    
  - Update libtflite_static to include the reference op resolver
    am: 39cbbcfb61
    
    Change-Id: I16d095e1c66718f03af0d6744fef567e6350a186
    
  - Add Android specific generated test runner.
    
      - The test runner is a Android specific trimmed down version of
      generated_examples_zip_test.
      - The main difference is the removal of dependencies like absl, re2
      and tensorflow core.
      - The files are forked in to nnapi_tflite_zip_tests/ to avoid problems
      upon rebasing.
      - More models will be added in upcoming CLs when the delegate is updated
      to support these ops
    
    Bug: 130762914
    Test: mm
    Test: atest TfliteGeneratedNnapiTest
    Change-Id: I09b5d5307b4a402c4fa166434744d7fe2f3b90cb
    
  - Update libtflite_static to include the reference op resolver
    
       - MFCC and AUDIO_SPECTROGRAM are disabled because of missing dependencies.
    
    Bug: 130762914
    Test: mm
    Change-Id: I72705f021aa19eb2118abac30c8de8ce50344bf4
    
  - Make sure the buffers in NNAPI delegate shared memory pool are 16 bytes aligned.
    am: 8e31a81e2b
    
    Change-Id: Ic9e81c4c32f2ce6d87785e672ab0e504c559195e
    
  - Make sure the buffers in NNAPI delegate shared memory pool are 16 bytes
    aligned.
    
    Bug: 130687286
    Test: mm
    Test: atest -a CtsTfliteNnapiDelegateTestCases
    Change-Id: I514dc59cf797816d3cd62d81fe5657f6ba135b7f
    
  - [automerger skipped] Merge changes from topic "tflite-nnapi-delegate-cts" am: f6a2179451
    am: 05445ab551 -s ours
    am skip reason: change_id I065e6ec5d312f9efe6ae3e4933fbe9412216f2aa with SHA1 6f26cdf6e3 is in history
    
    Change-Id: I8707677b1f328bfac1a0695db7a6fa25eab647b0
    
  - [automerger skipped] Fix compilation problems when running nnapi_delegate_test as part of CTS am: 8f3a29166b
    am: df293a9e8f -s ours
    am skip reason: change_id I2a3126794de8f30bd80e0a55b075fd21a201a738 with SHA1 010ba16282 is in history
    
    Change-Id: If3982a4d43c2ffbb5ef6f82e7f3cf10c7431ab92
    
  - Merge "Add presubmit tests for the NNAPI delegate" into qt-dev
    am: 1e96bcd117
    
    Change-Id: I78c06ceb2ceb1f0619d29783062f4601594f9670
    
  - Fix compilation problems when running nnapi_delegate_test as part of CTS
    am: 010ba16282
    
    Change-Id: Id45ae2b78d95f8452ed08b74ff19b4ba6358f83d
    
  - Merge "Add presubmit tests for the NNAPI delegate" into qt-dev
  - Add presubmit tests for the NNAPI delegate
    
    Bug: 124643616
    Test: atest
    Change-Id: I065e6ec5d312f9efe6ae3e4933fbe9412216f2aa
    Exempt-From-Owner-Approval: miaowang@ is an owner, and he gave a DrNo approval. He is asleep right now but I'd like to merge the change sooner.
    
  - Fix compilation problems when running nnapi_delegate_test as part of CTS
    
    This fixes the following two problems:
    
    1.
        In file included from external/tensorflow/tensorflow/lite/kernels/test_util.h:30:
        external/tensorflow/tensorflow/lite/testing/util.h:21:10: fatal error: 'tensorflow/lite/string.h' file not found
        #include "tensorflow/lite/string.h"
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
    
    2.
        ld.lld: error: undefined symbol: testing::internal::FormatMatcherDescription(bool, char const*, std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > > > const&)
        >>> referenced by nnapi_delegate_test.cc:34 (external/tensorflow//tensorflow/lite/delegates/nnapi/nnapi_delegate_test.cc:34)
        >>>               nnapi_delegate_test.o:(tflite::(anonymous namespace)::QuantizedNearMatcher::gmock_Impl<std::__ndk1::tuple<unsigned char const&, int const&> >::DescribeTo(std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >*) const) in archive out/target/product/crosshatch/obj_arm/STATIC_LIBRARIES/CtsTfliteNnapiDelegateTests_static_intermediates/CtsTfliteNnapiDelegateTests_static.a
    
    Bug: 130342510
    Bug: 124643616
    Test: mma CtsTfliteNnapiDelegateTests_static (with change I823a3071b4e45c5bf00a84334793347339f1cfa4)
    Change-Id: I2a3126794de8f30bd80e0a55b075fd21a201a738
    
  - [automerger skipped] Allow NNAPI delegate to report compliation failure am: 1aea22052d
    am: c0bf9ddc44 -s ours
    am skip reason: change_id Ib3229e20348eaee2cb968a213ac1f68bfce7418c with SHA1 d739c10163 is in history
    
    Change-Id: Iae6b3f95f86d838a8b5818fa3e729b1323f05818
    
  - [automerger skipped] Refactor NNAPI delegate am: 7ff851a936
    am: d7f101b83b -s ours
    am skip reason: change_id I9146f114a4bf418028e48aed72095dab48286bbb with SHA1 7c8832ce5e is in history
    
    Change-Id: Ia2cd5f29535c963509945ff7f26fd668521108ae
    
  - [automerger skipped] Fix segfault when NnApiDelegate is called without a device name am: 7e09129b27
    am: 63511d73bb -s ours
    am skip reason: change_id Ic613183c46a6684ebf194235926ed43e41eb5ab9 with SHA1 34fde8a1a8 is in history
    
    Change-Id: I6d847f123edb356870b72e83cc29d2bcd8ee2d38
    
  - [automerger skipped] Update the NNAPI delegate to allow user to specify accelerator by name. am: fbaa3b3c9c
    am: 5124d3a726 -s ours
    am skip reason: change_id Ie79d0e581ad269e69f64dd1c9bfaed812940d821 with SHA1 de5ec2294f is in history
    
    Change-Id: Ief5cf6208155558b6512ec69cab989b4f2de8079
    
  - Merge master@5406228 into git_qt-dev-plus-aosp.
    am: ab786c451d
    
    Change-Id: Ie488260c9112cd24ee6a554499092824cb02ca0b
    
  - Merge changes from topic "nnapi-vts-benchmark"
    
    * changes:
      Allow NNAPI delegate to report compliation failure
      Refactor NNAPI delegate
    
  - Allow NNAPI delegate to report compliation failure
    
    Bug: 123041316
    Test: atest VtsHalNeuralnetworksV1_2Benchmark (from change I4a0b83c85775acae2b8e502aae60830ff4f28507)
    Change-Id: Ib3229e20348eaee2cb968a213ac1f68bfce7418c
    
  - Refactor NNAPI delegate
    
    In prepartion for change Ib3229e20348eaee2cb968a213ac1f68bfce7418,
    this change makes the delegate TFLite registration part of NNAPIDelegateKernel
    so that it can access its private fields.
    
    Bug: 123041316
    Test: mma
    Change-Id: I9146f114a4bf418028e48aed72095dab48286bbb
    
  - Merge master@5406228 into git_qt-dev-plus-aosp.
    
    Change-Id: Iafb526d7c880af47c064a93d615b3465fbb037f0
    BUG: 129345239
    
  - Disable deprecated declarations for tensorflow am: 5a8a049b8c am: 39c3436d4d
    am: 6e2f11af3d
    
    Change-Id: Ie990b9c7375b0215fc971c39d816dcd4456eefa1
    
  - Disable deprecated declarations for tensorflow am: 5a8a049b8c
    am: 39c3436d4d
    
    Change-Id: I2851e7ccce202e2fe66c6379fd40dbbf294ae0e5
    
  - Fix segfault when NnApiDelegate is called without a device name
    
    Change-Id: Ic613183c46a6684ebf194235926ed43e41eb5ab9
    Fix: 129242862
    Test: mma
    
  - Update the NNAPI delegate to allow user to specify accelerator by name.
    
      - If an accelerator can be found based on the user provided name, the
      delegate will try to compile and run the model on the selected
      accelerator. An error will occur if the accelerator could not be found..
      - It is the user's responsibility to handle errors from a specific
      accelerator.
    
    Bug: 112661902
    Test: mm
    Test: Run NNAPI benchmark with driver names specified.
    Change-Id: Ie79d0e581ad269e69f64dd1c9bfaed812940d821
    
  - Merge remote-tracking branch 'aosp/upstream-master' into rebase_tf am: e16a4ebead am: 38b281d440
    am: ed6249b630
    
    Change-Id: I92a745020dc0e9b36eaec1f6f6f3916b80fd8045
    
  - Merge remote-tracking branch 'aosp/upstream-master' into rebase_tf am: e16a4ebead
    am: 38b281d440
    
    Change-Id: Ic1f401961b0031f5d510fc2fb7c08f0fbd1c6977
    
  - Disable deprecated declarations for tensorflow am: a5e6662c45 am: 471ac34eb0
    am: 7eba1a82a7
    
    Change-Id: Id0451f4ef273dd393119014ede35121409d37d5d
    
  - Disable deprecated declarations for tensorflow am: a5e6662c45
    am: 471ac34eb0
    
    Change-Id: Id8020d89335d3a04da87845978677d05603f15ed
    
  - Merge stage-aosp-master into pi-dev-plus-aosp
    am: 6c851299f3
    
    Change-Id: Id0c92384b6ce8952a38d8a2e3d45fd23c824ff22
    
  - Merge stage-aosp-master into pi-dev-plus-aosp
    
    Bug: 126125118
    Change-Id: I915a9367d6caf740b9e8fb37e8ef4e7e5d4b75cf
    
  - Merge remote-tracking branch 'aosp/upstream-master' into rebase_tf am: aa0a298258 am: 561aa44c05
    am: 23b4584071
    
    Change-Id: Ie3afec030503cd89f7c54b58f4f9cd4961e721c7
    
  - Merge remote-tracking branch 'aosp/upstream-master' into rebase_tf am: aa0a298258
    am: 561aa44c05
    
    Change-Id: Ib2a5a9f9902f51415d97ce957bbfaf89fd762a1d
    
  - [automerger skipped] Update includes in favor of external/libtextclassifier update am: 89345b1ce9 am: 5a865c6431
    am: f2ec9d7313 -s ours
    am skip reason: change_id Ia565913f0ec2aa1f36110d8b50d6b778b81c674e with SHA1 51cd24c046 is in history
    
    Change-Id: I01ee9d41f4a53359212613027098ef7b51a001b8
    
  - Update includes in favor of external/libtextclassifier update am: 89345b1ce9
    am: 5a865c6431
    
    Change-Id: Id559ce60bfd3040a60a91108430139fd96857bbc
    
  - Add default active developers into OWNERS am: abbf4bc0d1 am: eede1d0740
    am: 1bfe746dfd
    
    Change-Id: I288792e67ca70a3f95907f4c3b70f8274d2a9c9a
    
  - [automerger skipped] Merge pie-platform-release to aosp-master - DO NOT MERGE am: 438240aa67  -s ours am: 069419b92d  -s ours
    am: 859b3cdaf1  -s ours
    
    Change-Id: I8e3cb6c6ff5a249846cdd0a6f6dd5b46071608b4
    
  - [automerger skipped] Merge pi-platform-release to stage-aosp-master - DO NOT MERGE am: 60a31ffae9  -s ours
    am: c4301657ec  -s ours
    
    Change-Id: I197e113b7937393efe1d94fddaaf069a7267854f
    
  - Merge "Drop lib3 to AOSP (update the include statement)"
  - Merge remote-tracking branch 'aosp/upstream-master' into rebase_tf am: 578a2e9abd am: fa4dfc87a0
    am: 38e069128f
    
    Change-Id: Ie31679b29b2e22b6b6d16056f5a56e66096c556d
    
  - Merge remote-tracking branch 'aosp/upstream-master' into rebase_tf am: f3befa9b24 am: 2fd835c7bc
    am: daed6f7720
    
    Change-Id: Ib3ad9b3b423747dd00fbd81f5771b46a646898f2
    
  - Drop lib3 to AOSP (update the include statement)
    
    Test: Build
    
    Change-Id: Ia565913f0ec2aa1f36110d8b50d6b778b81c674e
    
  - Fix METADATA for tensorflow am: a9338bb548 am: d6be2ea306
    am: 63236a7f45
    
    Change-Id: Ie0918c6d6fa1cb60d0613844be4f06c93df1f7b9
    
  - [automerger skipped] Adds the new NNAPI Delegate to libtflite_static so that the NNAPI Benchmark app can use it. am: dfe2ac587a am: 7d23df3f4e
    am: 8e63e2ad9e  -s ours
    
    Change-Id: I9ef99b68f7c4daaca1a245fd1a1d26e4bb8021be
    
  - Adds the new NNAPI Delegate to libtflite_static so that the NNAPI
    Benchmark app can use it.
    
    This app is the sole user of this library.
    
    Bug: 111008127
    Bug: 113562636
    
    Test: Covered by existing test:
    com.example.android.nn.benchmark.NNTest
    
    Change-Id: I902a91ca87d429d7ebeac88e33cb07095b9b7f0f
    
  - Merge remote-tracking branch 'aosp/upstream-master' into rebase_tf am: c2adfe94fb am: 26b20bf954
    am: e1dd5a6877
    
    Change-Id: Ic30f4e119349dc5c69ad759b4582e52b19402ba9
    
  - Merge remote-tracking branch 'aosp/upstream-master' into rebase_tf am: f5815eb13d am: c9920cdb4b
    am: b1daed9f35
    
    Change-Id: I08aa697d68aa5b5a1f6669351567cc560133ad6d
    
  - Merge remote-tracking branch 'aosp/upstream-master' into rebase_tf am: d44ca8d83b am: 33669739e0 am: 45d3f6763a
    am: 3fa5284654
    
    Change-Id: I525a901804461ea81c5da1136adcda8159d49800
    
  - Merge remote-tracking branch 'aosp/upstream-master' into rebase_tf am: 2db2230841 am: 9634dc9f6a
    am: 299f9bfe7e
    
    Change-Id: I80edb86846c82195d672620dbfd92063eb80e286
    
  - Merge remote-tracking branch 'aosp/upstream-master' into mymerge am: fec35b43fc am: a54ed4f710
    am: 6b27318821
    
    Change-Id: Ibc66b3e11281d9fc825c81772e7b8b69220df88e
    
  - Merge remote-tracking branch 'aosp/upstream-master' into rebase_tflite am: a17c23f99c am: 2bcd73bda1
    am: e8220ab4f5
    
    Change-Id: I3523e52bcf49c573747a0f4060b7401aee2c0f9a
    
  - Fix NNAPI delegation: no scratch tensors and scale 0 for floats am: 4e1c5c76c5 am: 40ca7247b8
    am: 24440b0bdd
    
    Change-Id: Id7797621732f461fe4096108c7d5c4f379977ded
    
  - Merge remote-tracking branch 'aosp/upstream-master' into mymerge am: 78bd57f023 am: b8cad611cf
    am: 1657f65e1f
    
    Change-Id: Ia04abb068a56a87e8c05bd2807cf565a127cb0f9
    
  - Fix NNAPI delegation: no scratch tensors and scale 0 for floats
    
      - TFLite has temporary (scratch) tensors needed for its own CPU
      implementation
      - Delegating temporary tensors to NNAPI will cause validation
      failure, as they are not used
      - This CL skips such temporaries for CONV_2D operations - others may
      need to be added later
      - Setting non-zero scale for 32-bit float tensors causes validation
      errors
      - Also added delegation for MUL.
    
    Change-Id: I62dfaa53f4cdffd0d1dcedb28d181b8c92755ca8
    Test: build and run NNAPI benchmarking app
    
  - [automerger skipped] Port in minimal changes to support BroadcastSub and BroadcastDiv am: 55302b513b am: 97595de6bd  -s ours
    am: f659a33237  -s ours
    
    Change-Id: I4a95454d97a5a7a0413e2dedd83cce4a2819ed99
    
  - Port in minimal changes to support BroadcastSub and BroadcastDiv am: 6c79676c3e
    am: 20abae9145
    
    Change-Id: I80ab296ad2556ef72f69f67c793c79d1d5e7e796
    

* Update platform/superproject from branch 'master'
  to affb95a9c17a80ea535adecf8c236ec75e19ced1
  - Update git submodules
    
    * Update external/tensorflow from branch 'master'
      to 2266f3eccb66934b0447176114b8fa97ab10ad4e
      - Specify "nnapi-reference" backend for the buffer handle test
        
        Fixes: 141138444
        Test: mm
        Test: NNAPIDelegate#StatefulDelegateWithBufferHandles
        Change-Id: Iab7643c9284e00db483ae2cafe3091ab04503a43