Update git submodules
* Update platform/superproject from branch 'master'
  to 45c3c70868d2cd0c3187cb450f2257e458a2e7a1
  - Update git submodules
    
    * Update system/tools/aidl from branch 'master'
      to ebc3c5d9c9bcbdd5230d4e94c32f627da4f8357f
      - Generic validation of AidlDefinedType
        
        This treats all defined types the same when parsing, and since it is
        convenient, we also always show generic failures in addition to
        language-specific failures.
        
        Before:
        
            ERROR: a/path/Foo.aidl:1.26-43: The NDK and Rust backend does not
            support ParcelableHolder yet.
        
        After:
        
            ERROR: a/path/Foo.aidl:1.26-43: Arrays of ParcelableHolder are not
            supported.
            ERROR: a/path/Foo.aidl:1.26-43: The NDK and Rust backend does not
            support ParcelableHolder yet.
        
        Bug: 169958329
        Test: aidl_parser_fuzzer tests/corpus/*
        Test: atest aidl_unittests
        Change-Id: I99804f23eb687664b479a58d56b6c03b638a4ce9
        

* Update platform/system/tools/aidl from branch 'master'
  to ebc3c5d9c9bcbdd5230d4e94c32f627da4f8357f
  - Generic validation of AidlDefinedType
    
    This treats all defined types the same when parsing, and since it is
    convenient, we also always show generic failures in addition to
    language-specific failures.
    
    Before:
    
        ERROR: a/path/Foo.aidl:1.26-43: The NDK and Rust backend does not
        support ParcelableHolder yet.
    
    After:
    
        ERROR: a/path/Foo.aidl:1.26-43: Arrays of ParcelableHolder are not
        supported.
        ERROR: a/path/Foo.aidl:1.26-43: The NDK and Rust backend does not
        support ParcelableHolder yet.
    
    Bug: 169958329
    Test: aidl_parser_fuzzer tests/corpus/*
    Test: atest aidl_unittests
    Change-Id: I99804f23eb687664b479a58d56b6c03b638a4ce9