Update git submodules
* Update platform/external/autotest from branch 'master'
  to 403d5bc6cf99f2e74a9b909eb8c172f03375ed9e
  - autotest: Sync disk after installing autotest. am: d64eca55f1
    
    Change-Id: I8f006f5e1b5f8f30303d9e5166da95ea620c89d9
    
  - autotest: Sync disk after installing autotest.
    
    If a test performs a reset immediately after installing autotest,
    some of the python files can become empty afterwards, since they
    weren't really written yet.  This causes failures like the following:
    
      AutotestRunError: execute_section 0 failed to return anything
    
    Syncing the disk fixes this, ensuring that the files aren't empty.
    
    BUG=b:140625492
    TEST=Run platform_ServoPowerStateController_USBPluggedin for multiple iterations.
    
    Change-Id: I629f79cd6d0a3db6aa7554db6de6e1e13e9aa2b1
    Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/2088198
    Commit-Queue: Dana Goyette <dgoyette@chromium.org>
    Tested-by: Dana Goyette <dgoyette@chromium.org>
    Reviewed-by: Shelley Chen <shchen@chromium.org>
    

* Update platform/superproject from branch 'master'
  to d6c3fd8fbff039e58d4e9440af6fc1b5391d526b
  - Update git submodules
    
    * Update external/autotest from branch 'master'
      to 403d5bc6cf99f2e74a9b909eb8c172f03375ed9e
      - autotest: Sync disk after installing autotest. am: d64eca55f1
        
        Change-Id: I8f006f5e1b5f8f30303d9e5166da95ea620c89d9
        
      - autotest: Sync disk after installing autotest.
        
        If a test performs a reset immediately after installing autotest,
        some of the python files can become empty afterwards, since they
        weren't really written yet.  This causes failures like the following:
        
          AutotestRunError: execute_section 0 failed to return anything
        
        Syncing the disk fixes this, ensuring that the files aren't empty.
        
        BUG=b:140625492
        TEST=Run platform_ServoPowerStateController_USBPluggedin for multiple iterations.
        
        Change-Id: I629f79cd6d0a3db6aa7554db6de6e1e13e9aa2b1
        Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/2088198
        Commit-Queue: Dana Goyette <dgoyette@chromium.org>
        Tested-by: Dana Goyette <dgoyette@chromium.org>
        Reviewed-by: Shelley Chen <shchen@chromium.org>