Update git submodules
* Update platform/external/perfetto from branch 'master'
  to 6f366ee0aff6975d45be36e1322b243f72f3a24d
  - Merge "Fix MacOS protobuf build"
  - Fix MacOS protobuf build
    
    Error:
    ../../buildtools/protobuf/src/google/protobuf/stubs/strutil.cc:506:11: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
              sprintf(dest + used, (use_hex ? "\\x%02x" : "\\%03o"),
              ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
    __deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
    ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
            #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
    Change-Id: I4c3bbf1fedf2466ff5693c305e4553002a90ad4c