Update git submodules
* Update platform/external/zopfli from branch 'master'
  to a7aca0225b218bea25168000e960892e6cdc615c
  - Upgrade zopfli to 831773bc28e318b91a3255fa12c9fcde1606058b
    
    Test: make
    Change-Id: I74d0b4845c2f385937969ed58add46099934cfb4
    
  - Merge pull request #180 from enh-google/master
    
    Fix the i686-linux-android build.
  - Fix the i686-linux-android build.
    
    Found while trying to update AOSP's copy of zopfli from circa-2015
    source:
    
    external/zopfli/src/zopfli/cache.c:37:9: error: format specifies type
    'unsigned long' but the argument has type 'unsigned int'
    [-Werror,-Wformat]
            ZOPFLI_CACHE_LENGTH * 3 * blocksize);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
  - [LSC] Add LOCAL_LICENSE_KINDS to external/zopfli am: 462a053a91
    
    Original change: https://android-review.googlesource.com/c/platform/external/zopfli/+/1576047
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I80956215c01874c48c31724b60215a60cfd16743
    
  - Merge pull request #176 from JayXon/lodepng
    
    Update lodepng to 20201017
  - update lodepng to the latest version
    
  - Update lodepng to 20201017
    
  - add optional flag to keep original colortype
    
  - Change to O3 since it's faster than O2 now
  - mark version as 1.0.3
    
  - Merge pull request #155 from JayXon/getPNGHeaderInfo
    
    Use getPNGHeaderInfo() instead of decoding entire image
  - Merge pull request #163 from JayXon/filter
    
    Use lodepng builtin filter strategy for 1,2,3,4.
  - update lodepng to latest version
    
  - Use lodepng builtin filter strategy for 1,2,3,4.
    
  - update lodepng to the latest version
    
  - Use getPNGHeaderInfo() instead of decoding entire image
    
    Only the color type from header is needed here
    
  - Fix issue 162
    
    Fix issue https://github.com/google/zopfli/issues/162
  - Update lodepng to latest version
    
  - update lodepng to the latest version
    
  - Makefile improvements
    
    Add static library targets, support parallel build, overridable flags
  - Merge pull request #158 from davidsansome/cgo
    
    Add a CGO wrapper
  - Add a CGO wrapper
    
  - Merge pull request #151 from jibsen/update-cmake
    
    Update CMake script
  - Add config file package to install
    
    Install config files that allow other CMake based projects to use
    Zopfli with find_package(Zopfli). Also add aliases, so targets are
    available with the same names when built as a subproject.
    
    This allows the "Modern CMake" usage pattern:
    
    find_package(Zopfli REQUIRED) # or add_subdirectory(Zopfli)
    ...
    target_link_libraries(my_target PRIVATE Zopfli::libzopfli)
    
    These are only enabled for CMake 3.0+. While strictly speaking much
    of the functionality is available in earlier versions, the namespace
    support is not.
    
  - Set CMAKE_BUILD_TYPE to Release if empty
    
    Make based single-configuration generators default to an empty build
    type, if that is the case set it to Release instead. Also add an
    option to disable this behavior in case someone needs the default
    empty build type.
    
  - Fix paths to include files in install
    
  - Remove PRIVATE from target_link_libraries
    
    Not supported in CMake 2.8.11.
    
  - Link libzopflipng with libzopfli
    
    Avoids duplicating the zopfli code and simplifies the build a bit.
    Also move source file listings to the respective add_library and
    add_executable calls so we don't have extra variables.
    
  - Make comments more informative
    
  - Do not link with libm on BeOS and Haiku
    
  - Avoid (unlikely) double expansion
    
  - Add workaround for MSVC building DLL
    
    Recent versions of CMake support exporting all symbols when building a
    DLL. Enable this feature as a workaround for not explicitly exporting
    the public symbols, and warn on older version of CMake.
    
  - Add ZOPFLI_BUILD_SHARED option
    
    This replaces BUILD_SHARED_LIBS, which should not be inadvertently set
    by Zopfli if built as a subproject. Instead we use BUILD_SHARED_LIBS
    as the default value, if set.
    
    Also do not add install target for Zopfli by default when built as a
    static library subproject.
    
  - Move MSVC specific define to targets
    
  - Do not force Release build
    
    For Makefile generators, the default build type (CMAKE_BUILD_TYPE
    empty) uses CMAKE_C_FLAGS and by extension CFLAGS. Instead of forcing
    the build type in this case, print a status message letting the user
    know.
    
  - Add include directory to library targets
    
    When using zopfli as a subproject, users can do:
    
    add_subdirectory(zopfli)
    
    target_link_libraries(my_target libzopfli)
    
  - Add variables for library version
    
    Define the library version in one place. If the minimum CMake version
    is ever updated to 3.0, this could be added to the project command.
    
  - Add install target
    
  - Set minimum CMake version to 2.8.11
    
    This is a compromise between getting useful features and supporting
    operating systems still in use.
    
    https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/Life-Cycle-Considerations
    
  - fix warning due to signed integer in malloc size
  - Set cmake library versions to the current 1.0.2
  - Merge pull request #58 from jibsen/cmake-build
    
    Add CMake script
  - Update Makefile to 1.0.2
    
  - Merge pull request #81 from pornel/fwrite
    
    Faster stdout writing
  - Merge pull request #107 from JayXon/min
    
    Avoid min name conflict
  - try both with and without OptimizeHuffmanForRle, for better compression on small files
    
  - standardize code style
    
  - Merge pull request #111 from fhanau/master
    
    Update katajainen.c
  - Update katajainen.c
    
  - Update README.zopflipng
  - Update README
  - Update README.zopflipng
  - Avoid min name conflict
    
    In some weird C implementations (MSVC), min is defined as (((a) < (b)) ?
    (a) : (b))
    
  - Merge branch 'patch-2' of https://github.com/MrKrzYch00/zopfli into MrKrzYch00-patch-2
    
  - make the sort stable, and move some function definitions to header for speedup
    
  - Update squeeze.c
  - Convert a tab to spaces
  - Update CONTRIBUTORS
  - Merge pull request #105 from jthlim/master
    
    Implemented a number of small optimizations. 
  - Implemented a number of small optimizations. Details on http://roartindon.blogspot.sg/2016/04/boosting-zopfli-performance.html
    
  - verify pixels after encoding, and fix colorkey issue
    
  - Fix excessive usage of malloc/free
    
    Split ZopfliInitHash to:
    - ZopfliAllocHash - allocate hash memory,
    - ZopfliResetHash - reset hash values.
    
    Allocate Hash outside of ZopfliLZ77Greedy and ZopfliLZ77OptimalRun that
    pass it further to functions previously allocating them. Do the same for
    costs malloc'd array.
    
    Reason for this change:
    - the size of malloc doesn't change,
    - speed up Zopfli*,
    - fix crash on certain devices**.
    
    * speeds up Zopfli (especially on smaller blocks) by reducing amount of
    sys time from ~7s to 0.1s on x64 Linux for ~5m compression time and from
    ~1m to 0.1s on ARMv7 Linux for 13m compression time.
    ** fixes a large amount of iterations crash on some ARM devices that due
    to architecture or older kernel (not sure which) don't handle too
    aggressive heap allocation and freeing.
    
  - Update lodepng_util.cpp to the latest version
  - Fix unfinished sentence.
  - don't iterate chunks for keeping colortype if no --keepchunks
    
  - fix bug when keeping bKGD chunks from different color type
    
  - Improved zopflipng file handling and user messages
  - Decrease master block size to use less memory
  - Set zlib level bits to 3 to indicate slowest compression.
  - Update build instructions
  - Update build instructions
  - Update build instructions
  - update zopflipng to use latest lodepng and fix png related bugs
    
  - make the CRC code threading compatible with a lookup table
    
  - Faster stdout writing
    
  - Merge pull request #78 from MegaByte/master
    
    Refine __builtin_clz compatibility check
  - Refine __builtin_clz compatibility check
    
  - Merge pull request #77 from khernyo/fix-invalid-read
    
    Fix invalid read outsize allocated memory
  - Fix invalid read outsize allocated memory
    
    The invalid read happens when compressing a 1 byte file.
    
  - fix compiler warning
    
  - block splitting no more distinction between splitting first and last
    
  - zopfli bug and typo fixes
    
  - Merge pull request #67 from rossy/setmode-fix
    
    Fix for _setmode usage
  - Fix _setmode usage for stdout new-line conversion
    
    The previous fix didn't work in all situations. I suspect it's because
    it was changing the state of the fd back to _O_TEXT mode without
    synchronising with fflush(). Changing the mode back to _O_TEXT isn't
    actually needed (see discussion in #56,) so just remove the call.
    
  - Merge pull request #56 from MrKrzYch00/original
    
    Various fixes
  - Merge pull request #60 from scop/master
    
    Adjust usage message to note multiple input file arguments are ok
  - Merge pull request #59 from scop/spelling
    
    Spelling fixes
  - Adjust usage message to note multiple input file arguments are ok
    
  - Spelling fixes
    
  - >2GB file size crash fix
    
    Fix SIGSEGV on files larger than 2GB. If file is larger than that display an error and exit with EXIT_FAILURE.
    
    It's worth noting that fseek64 and ftell64 could be used but due to large memory usage when reading big files, the code should be changed to read files in ZOPFLI_MASTER_BLOCK_SIZE chunks first.
  - Add CMake script
    
  - Fix SIGSEGV when out of memory for cache
    
    This fixes SIGSEGV (Segmentation Fault) when malloc for cache fails due to out of memory condition. This can happen on low memory systems or when Zopfli is compiled with higher ZOPFLI_CACHE_LENGTH preprocessor value than default one.
  - New line separator in iterations error
    
    Add new line separator at the end of iterations error. This fixes command prompt displaying on same line as this error message when zopfli exists - linux terminal.
  - Fix stdout new lines on Windows
    
    This fixes output to stdout on windows to use binary. Tested on Windows 10 Technical Preview.
  - Fix SIGSEGV when can't writer output
    
    This fixes SIGSEGV (Segmentation Fault) when output file can't be opened for writting binary (wb). Instead display error message on what's wrong and exit with failure status (aka. errorlevel). This will make it more clear to user who forgot to "sudo" etc.
  - Fix deflate stream size reporting
    
    Use offset recording of current outsize when calling ZopfliDeflate. Fixes incorrect Deflate stream reporting when zlib or gz container is used.
  - Merge pull request #55 from JayXon/FirstEncounteredTransparentPixel
    
    Fix RGB value of first encountered transparent pixel
  - fix RGB value of first encountered transparent pixel
    
    The comment suggest to use first encountered transparent pixel, which I
    think is the right way, but the code is using last encountered
    transparent pixel.
    
  - Merge pull request #54 from pornel/warnings
    
    Warnings--
  - Merge pull request #51 from JayXon/ColorIndex
    
    Fix ColorIndex
  - Merge pull request #53 from pornel/verbose
    
    Verbose flag
  - Fix misc cppcheck warnings.
    
  - Dead store
    
  - verbose flag
    
  - Fix ColorIndex
    
  - Merge branch 'dwbuiten-fileperms'
    
  - Merge branch 'fileperms' of https://github.com/dwbuiten/zopfli into dwbuiten-fileperms
    
  - Merge pull request #49 from dwbuiten/sharedlib
    
    build: Allow building ZopfliPNG as a shared library
  - Merge pull request #50 from dwbuiten/c_api
    
    ZopfliPNG: Add a C API
  - ZopfliPNG: Add a C API
    
    This allows the library to be used from many more languages,
    and also provides a defined and stable ABI, unlike C++.
    
    Signed-off-by: Derek Buitenhuis <derek.buitenhuis@gmail.com>
    
  - build: Allow building ZopfliPNG as a shared library
    
    Signed-off-by: Derek Buitenhuis <derek.buitenhuis@gmail.com>
    
  - Don't set the executable flag on C++ source files
    
    Signed-off-by: Derek Buitenhuis <derek.buitenhuis@gmail.com>
    
  - Rename CONTRIBUTING to CONTRIBUTING.md
  - Create CONTRIBUTING