Update git submodules
* Update platform/build/soong from branch 'master'
  to b0353ed3b18503636676092685bf17ba713d7526
  - Merge "Use the current java version for -jvm-target"
  - Use the current java version for -jvm-target
    
    This is a partial revert of aosp/541879.
    In that cl, the kotlin jvm version was always
    set to 1.8 because that's what the kotlin
    complier supported at the time, but now
    it supports more versions:
    
    $ ./external/kotlinc/bin/kotlinc -jvm-target foo
    error: unknown JVM target version: foo
    Supported versions: 1.6, 1.8, 9, 10, 11, 12, 13, 14, 15, 16, 17
    
    Bug: 69160377
    Bug: 236431222
    Test: Treehugger
    Change-Id: I273e0b4d1f484013889e17c60bc1b299a3f975a1
    

* Update platform/external/kotlinx.coroutines from branch 'master'
  to 6ee49c7d05e198c91c241a404ca4e99a9016aef4
  - Update sdk_version of kotlinx-coroutines
    
    So that it compiles for Jvm version 11,
    and doesn't hit issues inlining it's code
    into other Jvm 11 code.
    
    Bug: 69160377
    Bug: 236431222
    Test: Treehugger
    Change-Id: Ie15d315a4396c539b5d3f8c903252c990c5274c7
    
  - Add a filegroup to allow exporting the kotlinx-coroutines-play-services src files am: 7687439cf5
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinx.coroutines/+/2064527
    
    Change-Id: Ib4062333fd3d9f32dd803a7541769bb110610c57
    Signed-off-by: Automerger Merge Worker <android-build-automerger-merge-worker@system.gserviceaccount.com>