Update git submodules
* Update platform/art from branch 'master'
  to 5fa267b4eb075c85827afb0379a7a63ab37d6bf7
  - Disable check for false-positive bugprone-use-after-move clang-tidy warning
    
    After clang update, clang-tidy bugprone-use-after-move starts to check
    constructor initialization list. It gives below false-positive warning:
    
    art/libartbase/base/scoped_arena_allocator.cc:122:20: error: 'other' used after it
      was moved [bugprone-use-after-move,-warnings-as-errors]
    arena_stack_(other.arena_stack_),
    ^
    art/libartbase/base/scoped_arena_allocator.cc:119:7: note: move occurred here
    : DebugStackReference(std::move(other)),
    ^
    
    This CL disable the check in the code.
    
    Bug: 286421006
    Test: build with clang-r498229
    Change-Id: Icac433d9bf1600546b5f7cf7bc6c520d61d020c2