Update git submodules
* Update platform/system/teeui from branch 'master'
  to 5653082ecc73e4d42a789fb935bd94d34e595b14
  - [LSC] Add LOCAL_LICENSE_KINDS to system/teeui
    
    Added SPDX-license-identifier-Apache-2.0 to:
      libteeui/Android.bp
      libteeui/example/Android.bp
      libteeui/prebuilt/localization/Android.bp
      libteeui_jni/Android.bp
      test/Android.bp
      tools/framebufferizer/Android.bp
    
    Bug: 68860345
    Bug: 151177513
    Bug: 151953481
    
    Test: m all
    
    Exempt-From-Owner-Approval: janitorial work
    Change-Id: I6005cbde33fe33cbdeda5e65f98ba7029c4bddda
    
  - Change layout to address failing portability tests. am: aa62b6cb40 am: 3a499b7c5e am: fa8ef9a368 am: 80e5b642bb
    
    Original change: https://android-review.googlesource.com/c/platform/system/teeui/+/1329356
    
    Change-Id: I8f8e5ee355b2145a4b91378d180d8d352103b1da
    
  - Change layout to address failing portability tests. am: aa62b6cb40 am: 3a499b7c5e am: fa8ef9a368
    
    Original change: https://android-review.googlesource.com/c/platform/system/teeui/+/1329356
    
    Change-Id: Idb9a9a92beb58811fccd242177d5aef7dcd5ae4e
    
  - Change layout to address failing portability tests. am: aa62b6cb40 am: 3a499b7c5e
    
    Original change: https://android-review.googlesource.com/c/platform/system/teeui/+/1329356
    
    Change-Id: I97b3ecd24150940cc491514ec598a95e761a4f5b
    
  - Change layout to address failing portability tests. am: aa62b6cb40
    
    Original change: https://android-review.googlesource.com/c/platform/system/teeui/+/1329356
    
    Change-Id: I867a099e5558c1fe54303dbe2d7513cbea98cee7
    
  - Merge changes Ie5fdacb1,If9adb952,Idb10efa4,Ifbcf97a0,I8dbfde56 am: 31b74d7fd3 am: f95c6cd89d am: 5b0f100a12 am: 9173b2e80d
    
    Original change: https://android-review.googlesource.com/c/platform/system/teeui/+/1308624
    
    Change-Id: I8b30bb8961c9c383f652d4f418aaad44444fc2f5
    
  - Merge changes Ie5fdacb1,If9adb952,Idb10efa4,Ifbcf97a0,I8dbfde56 am: 31b74d7fd3 am: f95c6cd89d am: 5b0f100a12
    
    Original change: https://android-review.googlesource.com/c/platform/system/teeui/+/1308624
    
    Change-Id: Ie40f2f053d11c1cb59f051c24057427c16bb3cb5
    
  - Merge changes Ie5fdacb1,If9adb952,Idb10efa4,Ifbcf97a0,I8dbfde56 am: 31b74d7fd3 am: f95c6cd89d
    
    Original change: https://android-review.googlesource.com/c/platform/system/teeui/+/1308624
    
    Change-Id: I2bc1a306ee8dd20609663d337ab4d5302e4354be
    
  - Merge changes Ie5fdacb1,If9adb952,Idb10efa4,Ifbcf97a0,I8dbfde56 am: 31b74d7fd3
    
    Original change: https://android-review.googlesource.com/c/platform/system/teeui/+/1308624
    
    Change-Id: I52709b17befaf011f8e70459804a37a9f23b319d
    
  - Remove MODULE_LICENSE_APACHE2 from teeui am: 99191b8209 am: a3d7781bd0 am: 7f30cc8d20 am: 91c5de5991
    
    Change-Id: I7efcbf21d58f1ae8dcef7c9552d045e5eb465298
    
  - Remove MODULE_LICENSE_APACHE2 from teeui am: 99191b8209 am: a3d7781bd0 am: 7f30cc8d20
    
    Change-Id: If5a2e9ab1990c4b5103456b1ac2d03e69847a6b0
    
  - Remove MODULE_LICENSE_APACHE2 from teeui am: 99191b8209 am: a3d7781bd0
    
    Change-Id: I4a0218f4a34639c25d83cb0c395949b9ecf85306
    
  - [automerger skipped] Fix compile error for clang update. am: 38f5f676c7 am: 3f223c1ac1 am: add4ebe799 am: 2d0126b5a9 -s ours
    
    am skip reason: Change-Id I85972a6f042933540a371686e1a1d2bf422519af with SHA-1 38f5f676c7 is in history
    
    Change-Id: Ie246174c3e07d03ca44da646c4cd41cdf5dfd237
    
  - Fix compile error for clang update. am: 38f5f676c7 am: 3f223c1ac1 am: add4ebe799
    
    Change-Id: I5d575b7fee9887cae25c13bb1eb5f7906cf63fdc
    
  - [automerger skipped] Fix compile error for clang update. am: 38f5f676c7 -s ours am: 70d7b3175e -s ours am: e6a15b1b9b -s ours
    
    am skip reason: Change-Id I85972a6f042933540a371686e1a1d2bf422519af with SHA-1 38f5f676c7 is in history
    
    Change-Id: Id382e2f75164690c17f728484fe966837182bc3b
    
  - [automerger skipped] Fix compile error for clang update. am: 38f5f676c7 am: 3f223c1ac1 -s ours am: 0e9d542748 -s ours
    
    am skip reason: Change-Id I85972a6f042933540a371686e1a1d2bf422519af with SHA-1 0d0d97559b is in history
    
    Change-Id: Iaa390ad028a7e76dfe61df3e19e387e75d159ec6
    
  - [automerger skipped] Fix compile error for clang update. am: 38f5f676c7 -s ours am: 70d7b3175e -s ours
    
    am skip reason: Change-Id I85972a6f042933540a371686e1a1d2bf422519af with SHA-1 38f5f676c7 is in history
    
    Change-Id: I0feeb63664183085ab50e2810f02f054102079c2
    
  - Fix compile error for clang update. am: 38f5f676c7 am: 3f223c1ac1
    
    Change-Id: Iba2c738e0a86ac786291b163e49ab81a0ab5d58d
    
  - [automerger skipped] Fix compile error for clang update. am: 38f5f676c7 am: 3f223c1ac1 -s ours
    
    am skip reason: Change-Id I85972a6f042933540a371686e1a1d2bf422519af with SHA-1 0d0d97559b is in history
    
    Change-Id: If6e0fd0f0bb91f67b831e525bfb0b6a850457be2
    
  - [automerger skipped] Fix compile error for clang update. am: 38f5f676c7 -s ours
    
    am skip reason: Change-Id I85972a6f042933540a371686e1a1d2bf422519af with SHA-1 0d0d97559b is in history
    
    Change-Id: If0b2e3b7b4144ab701e48f35c65e36fef9316979
    
  - Fix compile error for clang update. am: 38f5f676c7
    
    Change-Id: I4a5036b178557482b2a9a98c6289c1ffd3150c9d
    
  - Fix compile error for clang update.
    
    system/teeui/libteeui/example/teeui.cpp:130:9: error:
    call to member function 'setParam' is ambiguous
        ctx.setParam<RightEdgeOfScreen>(pxs(sDeviceInfo.width_));
        ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
    system/teeui/libteeui/include/teeui/utils.h:468:10: note: candidate function
    [with MetaParam = teeui::MetaParam<teeui::Param_RightEdgeOfScreen,
     teeui::Coordinate<teeui::UnitT<teeui::Unit::PX>, float> >]
        void setParam(
             ^
    system/teeui/libteeui/include/teeui/utils.h:475:10: note: candidate function
    [with MetaParam = teeui::MetaParam<teeui::Param_RightEdgeOfScreen,
    teeui::Coordinate<teeui::UnitT<teeui::Unit::PX>, float> >,
    Unit = teeui::UnitT<teeui::Unit::PX>, N = float, $3 = void]
        void setParam(const Coordinate<Unit, N>& v) {
             ^
    
    Bug: 149839606
    Test: build.
    Change-Id: I85972a6f042933540a371686e1a1d2bf422519af
    Merged-In: I85972a6f042933540a371686e1a1d2bf422519af
    (cherry picked from commit 0d0d97559b7072c487ff7e8a82fb32587c381672)
    
  - Move utf8range into separate file. am: 2ca8124f0d am: 1ec35188a8 am: 59b8329d02 am: 2cb14f4827
    
    Change-Id: I7d57965dba0d50d28360aff1488394ad92db8001
    
  - Move utf8range into separate file. am: 2ca8124f0d am: 1ec35188a8 am: 59b8329d02
    
    Change-Id: I8d15d61b0c7b18786e6c833b708f2436d938ed72
    
  - Move utf8range into separate file. am: 2ca8124f0d am: 1ec35188a8
    
    Change-Id: I0fab91115013cb5963ede8fbaa09daae209dfacc
    
  - TEEUI cleanup: Make param_ field in Params private am: 006e59f114 am: c308063d4f am: 89262147fb am: 3464d72f30
    
    Change-Id: I558898ccd898b9c586fe7157c80ccbdf5930d32a
    
  - TEEUI cleanup: Make param_ field in Params private am: 006e59f114 am: c308063d4f am: 89262147fb
    
    Change-Id: Iadfb4d1517467d33363858f1967577bca4a16092
    
  - TEEUI cleanup: Make param_ field in Params private am: 006e59f114 am: c308063d4f
    
    Change-Id: I345bbd690e024a9fc2051c69e867a46774eb5a5f
    
  - Merge "Integration of newly generated localization files." am: 6de66326f2 am: 3ed58a125a am: d71c8d72df am: 0ba4a25122
    
    Change-Id: Ib98868e0dcbc7b29f97313012e12356a5eb88201
    
  - Restructure pixelDrawer in order to support generic callback, so that it can be am: b13be7b3cc am: fc6e5b4e51 am: fe8a5a46cb am: d9e108ff07
    
    Change-Id: I8849db8286a5c8bdd33d43e9a5bb833026ebc6b9
    
  - Merge "Integration of newly generated localization files." am: 6de66326f2 am: 3ed58a125a am: d71c8d72df
    
    Change-Id: I8331beac18c2d3db7dd19dcd16cc59514b994037
    
  - Restructure pixelDrawer in order to support generic callback, so that it can be am: b13be7b3cc am: fc6e5b4e51 am: fe8a5a46cb
    
    Change-Id: Ic5b25bc826bb9dead93639436e9664288f99416a
    
  - Merge "Integration of newly generated localization files." am: 6de66326f2 am: 3ed58a125a
    
    Change-Id: I5f83ac9e6bb9f08fbd1492466001e6b254f9ae50
    
  - Restructure pixelDrawer in order to support generic callback, so that it can be am: b13be7b3cc am: fc6e5b4e51
    
    Change-Id: I6fa86f3d0a3228cdde8b46fe053d86b2d45bb783
    
  - Fix compile error for clang update. am: 0d0d97559b am: 5756d1ea52 am: 66f2b406d8 am: 60a5befcb5
    
    Change-Id: I958ca97fcc490d031cebbff7ceacf75b85d31b52
    
  - Fix compile error for clang update. am: 0d0d97559b am: 5756d1ea52 am: 66f2b406d8
    
    Change-Id: Ifec77f35429311ec1f024efa1dee8d282bac9017
    
  - Fix compile error for clang update. am: 0d0d97559b am: 5756d1ea52
    
    Change-Id: I89a98dc47f6aabbb96f711ddf8ab6d1b4e1ca7ab
    
  - Add explicit dependencies on jni_headers am: 9cdb2650cf am: a02a781538 am: feee9701e5 am: 05e2df9e99
    
    Change-Id: I202f29bfea0d2c712583bfb3bbbe76867265a1f3
    
  - Add explicit dependencies on jni_headers am: 9cdb2650cf am: a02a781538 am: feee9701e5
    
    Change-Id: I61ab2c3f9dc7104e9c54020437bd0a239db7eb2e
    
  - Add explicit dependencies on jni_headers am: 9cdb2650cf am: a02a781538
    
    Change-Id: Ib99443e3e96883eb9f11e41e379dae6db2a15cf8
    
  - [automerger skipped] DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp into stag-aosp-master am: 50a92751c9 -s ours am: becc15de0c am: f6d1359e61
    
    Change-Id: I6dea64e4cd726b120a8425d339bc4e96fcd002d8
    
  - [automerger skipped] DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp into stag-aosp-master am: 50a92751c9 -s ours am: becc15de0c
    
    Change-Id: I8ecdc03c29358693a25ccd7b7ababa71c2a41f2c
    
  - [automerger skipped] DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp into stag-aosp-master am: 50a92751c9 -s ours
    
    am skip reason: subject contains skip directive
    
    Change-Id: Iba6d22e75b48bc3b4567ae8a83a7fcb4cf79ea33
    
  - [automerger skipped] DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp@6304901 into stag-aosp-master am: bcbc7c972a -s ours am: 13b81bf303 am: 73ead94d0d
    
    Change-Id: I3b3bcc78ad4fa7b2e1d849787c5463c92717679d
    
  - [automerger skipped] DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp@6304901 into stag-aosp-master am: bcbc7c972a -s ours am: 13b81bf303
    
    Change-Id: I68c4d49775913c5c8a9640be129205cd0c0260c4
    
  - [automerger skipped] DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp@6304901 into stag-aosp-master am: bcbc7c972a -s ours
    
    am skip reason: subject contains skip directive
    
    Change-Id: I28af70c3f41b49157ac6f2dbb5957a6f6a2ab20d
    
  - Store latest settings of TeeuiFramebufferizer in user config file am: 4e1c58ce59 am: dcc05c54e2 am: d7ff776c70 am: fe0008cda6
    
    Change-Id: I329cc408d6ed59e01c0472ad968e236519715d56
    
  - Store latest settings of TeeuiFramebufferizer in user config file am: 4e1c58ce59 am: dcc05c54e2 am: d7ff776c70
    
    Change-Id: I531e7db99e36ec087a409f947bbd347edce22949
    
  - Store latest settings of TeeuiFramebufferizer in user config file am: 4e1c58ce59 am: dcc05c54e2
    
    Change-Id: Ic4f45204e68fc24d6791c33ecbaf0ae6a4fae2ab
    
  - Aligment of label texts to support buttons am: 3fb01037f5 am: 2a488d3c55 am: c793d5350b am: 8878291b2a
    
    Change-Id: I3687beead56e1966c5fa1d655cc80029aa6ae7db
    
  - Aligment of label texts to support buttons am: 3fb01037f5 am: 2a488d3c55 am: c793d5350b
    
    Change-Id: I8f09f880b335600fb37dd593f91a405b75c38094
    
  - Aligment of label texts to support buttons am: 3fb01037f5 am: 2a488d3c55
    
    Change-Id: I6ccdca217342aea168bf27c678b24e8090b61e52
    
  - Teeui renderer test with WWWWW test strings am: aa75510332 am: 2e59097423 am: d4380aba66 am: 5a2ef10811
    
    Change-Id: Icd6912e475f7b94f2da39ab054c963d1a5107bc1
    
  - Teeui renderer test with WWWWW test strings am: aa75510332 am: 2e59097423 am: d4380aba66
    
    Change-Id: I43d851823ea85e4d0174b243befb2642cad9d818
    
  - Teeui renderer test with WWWWW test strings am: aa75510332 am: 2e59097423
    
    Change-Id: I245f743d0fc226670f4fa3cde3d9f57fdd19519f
    
  - [automerger skipped] Separate device config from teeui rendering test am: d8ec1fe1ae am: 9b8d7ce9c2 am: 9da8352bbc -s ours
    am skip reason: Change-Id If57c1bf9e7ea25c81f755b7e6df78ba0e6e52313 with SHA-1 42475294a0 is in history
    
    Change-Id: I6d8eaa2effe51413a06cb13ef19880490756089f
    
  - Separate device config from teeui rendering test
    
    Moved device configuration code away from the teeui rendering test.
    
    Test: N/A
    Change-Id: If57c1bf9e7ea25c81f755b7e6df78ba0e6e52313
    
  - Merge "Edit README file for teeui_localization_rendering_test" am: f0e295991c am: b85dcfbfd1 am: 6571142055
    
    Change-Id: I0d688bd2fa64a82b5e842d337c6b64d574882e4c
    
  - Merge "Add locale testing to teeui" am: 9f8377b975 am: 27f40f8a74 am: 5f522d9fd5
    
    Change-Id: I2c9b8f55a80232cdbb407074dbc2e008f401661b
    
  - Implement the revised layout and color scheme for AOSP. am: e6fc9c26f2 am: 88d9a7b6da am: f391b65c29
    
    Change-Id: Ia7ed13d578a968dc156361e1165ce1608c363822
    
  - Add inverted color mode and Confirmation message to Framebufferizer. am: ada6bfb912 am: 0559ce42a5 am: 0fab098db0
    
    Change-Id: Idcaa59655034138bde5aca9a5854088ab02f9d6f
    
  - Make layout parameters support types other than Coordinates am: 2615fdf181 am: cc28c0b51b am: 033a55fd45
    
    Change-Id: Icc6ac596f6a4bf09f22d7ae7a04783c7c244f34a
    
  - Add translation selection feature in java ui am: 1942e277f8 am: 16337eca4b am: 603ab91a86
    
    Change-Id: I2af38b434443e2010a65ace386090fde38df5af7
    
  - Adding translation rendering am: d179091ba1 am: f64d257c3e am: ca7addcf22
    
    Change-Id: I33042013fb6c21f315ec2e6a5bc3fed167eac45c
    
  - Device Resizing & Pass device parameters and magnified mode down to the renderer am: aea7cab66a am: 6016fa6061 am: 35690980fa
    
    Change-Id: I7978695ca32fb2881ef75fb08537e10179967d5d
    
  - Add generated ConfirmationUITranslation files am: 926fd72cac am: 3b75ec772b am: b0c9df5f90
    
    Change-Id: I1b4ebbdd6d2a16f2e0ce2b0ced3bf68e72649f83
    
  - Moved secure_input protocol and auxiliary code to libteeeui am: 7c4b9e5eb2 am: 70bcf6f045 am: 9202ad71b6
    
    Change-Id: I1dd071e7c400d00b9e51b4e0e9917768446c6975
    
  - Add HAL support library am: c6bdee5cf4 am: 9e7c339f5d am: 69757aa68c
    
    Change-Id: I10dd1cadab7d92e6c1ddf6670620c91aa68a0a46
    
  - Moved confirmationui support library to libteeui am: 9acad3f1ec am: fc18a2b28c am: c572064a85
    
    Change-Id: Ie0f9cf5790514babf01286dfcb75fc964702bbe8
    
  - Teeui tests am: 5caf88f134 am: f2771cd187 am: 8a5c74824a
    
    Change-Id: I5ebbd2a0c460f6630547952c97ef3b747c32c96b
    
  - Teeui example am: bbd062fcd7 am: 561b74cea0 am: 359764eda6
    
    Change-Id: I147de2f8078a1580cb9fd296d577af5cf956a6db
    
  - Teeui layout and rendering am: 5821a43f98 am: 55cbd780bd am: 8e7639b980
    
    Change-Id: If506b63e0e9addbed41f464c221adaaa2f5d086e
    
  - Add teeui jni wrapper. am: c48820ea6f am: 1510a7be9f am: 440da0e314
    
    Change-Id: I849afbadd1bb23e0d4a57bb88268bf7b89708994
    
  - Added TeeuiFramebufferizer am: c3b2e26466 am: d99c9d75c7 am: 7cea10fd30
    
    Change-Id: I1688b84778c4407e09edc8b17feb69c7a164925c
    
  - Merge "Add clang-format, license file, PREUPLOAD.cfg, and OWNERS am: 979bbb0015 am: 3dc2814342 am: dfe4630862"
  - Add clang-format, license file, PREUPLOAD.cfg, and OWNERS am: 979bbb0015 am: 3dc2814342 am: dfe4630862
    
    Change-Id: I6b8f9d6d6e6a7e9dd89b6cfa8d09ceca06ea74be