Update git submodules
* Update platform/build/soong from branch 'master'
  to 679d5308ec27b8c02de7484acae58c93f6cd210b
  - Merge "Switch to clang r416183 12.0.4."
  - Switch to clang r416183 12.0.4.
    
    Bug: http://b/181927912
    
    Test: go/android-llvm-testing-dashboard tag: test_clang_r416183
          go/android-llvm-windows-testing
          go/ab/P20855845 sdk_phone_armv7-sdk_mac build on Forrest
          Forrest run L21700000838126631 for CtsNNAPITestCases
    
    Change-Id: If677b57616348ae52704494f40c7b1ed470bb5f4
    

* Update platform/frameworks/av from branch 'master'
  to 24ba1e48cc65d07e8c08387716dd59e245b3643e
  - Merge "[clang-tidy] Disable bugprone-narrowing-conversions for mediametrics"
  - [clang-tidy] Disable bugprone-narrowing-conversions for mediametrics
    
    Bug: http://b/181927912
    Bug: http://b/182410845
    
    This warning re-appeared:
    
    /mnt/disks/build-disk/src/googleplex-android/master/frameworks/av/services/mediametrics/statsd_drm.cpp:139:33:
    error: narrowing conversion from 'size_t' (aka 'unsigned long') to signed type 'std::__wrap_iter<unsigned char *>::difference_type' (aka'long') is implementation-defined [bugprone-narrowing-conversions,-warnings-as-errors]
            buf.erase(buf.begin() + size, buf.end());
    
    Let's disable this and fix the warning after the compiler update lands.
    
    Test: m statsd_drm.tidy
    Change-Id: Ibabf5b9caaa77d201543308724c8444d98c5dde1