Update git submodules
* Update platform/external/swiftshader from branch 'master'
  to c5685834ed101dc6d0b57ac74404f1d2e9ca23f9
  - Roll SwiftShader from 5d449d4fcb77 to efe254de5d88 (12 revisions)
    
    https://swiftshader.googlesource.com/SwiftShader.git/+log/5d449d4fcb77..efe254de5d88
    
    If this roll has caused a breakage, revert this CL and stop the roller
    using the controls here:
    https://autoroll.skia.org/r/swiftshader-android
    Please CC swiftshader-team@google.com on the revert to ensure that a human
    is aware of the problem.
    
    To report a problem with the AutoRoller itself, please file a bug:
    https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug
    
    Documentation for the AutoRoller is here:
    https://skia.googlesource.com/buildbot/+doc/master/autoroll/README.md
    
    Test: Presubmit checks will test this change.
    Exempt-From-Owner-Approval: The autoroll bot does not require owner approval.
    Bug: b/140302392
    Bug: b/140991626
    Bug: b/152192800
    Bug: b/167582422
    Bug: b/184063472
    Bug: b/187094215
    Bug: b/189334760
    Bug: b/189469951
    Bug: b/189557997
    Bug: b/189588731
    Change-Id: I377ae8b5d2d06f7c4d2fa7901df932cd5788f465
    
  - Remove git submodules before rolling into Android
    
    This change adds a script which is to be called by the SwiftShader into
    Android AutoRoller: https://autoroll.skia.org/r/swiftshader-android
    
    It prepares a checkout for upload into the Android repo. Specifically,
    Android does not allow remote submodules, so this script removes them.
    Note SwiftShader does not require any submodules to build the library;
    they are optional for development purposes.
    
    Bug: b/189557997
    Change-Id: I36b4ae59cd843f1c69146f0f52ce8f323c6bc15a
    Reviewed-on: https://swiftshader-review.googlesource.com/c/SwiftShader/+/54768
    Reviewed-by: Alexis Hétu <sugoi@google.com>
    Kokoro-Result: kokoro <noreply+kokoro@google.com>
    Tested-by: Nicolas Capens <nicolascapens@google.com>
    
  - Value-initialize all vk::GraphicsState members
    
    The vk::GraphicsState constructor does not initialize all members in all
    code paths. We were relying on the zero-initializing done by
    vk::allocate() which is used to allocate vk::GraphicsPipeline which in
    turn contains a GraphicsState member.
    
    We want to change vk::allocate() to no longer zero-initialize all
    memory, to catch more MemorySanitizer errors made by applications. Thus
    we must also not rely on such automatic initialization ourselves.
    
    Note that this change might also hide MemorySantizer violations
    committed by the application side. For example some state is only copied
    from VkGraphicsPipelineCreateInfo into vk::GraphicsState on construction
    when flags indicate they're not dynamic state. If the application
    forgets to makerecord commands that set the dynamic state, their value
    is undefined:
    
    Vulkan 1.2.178 section 6. Command Buffers:
    "When a command buffer begins recording, all state in that command
    buffer is undefined."
    
    Vulkan 1.2.178 section 10.11. Dynamic State:
    "If the state is specified as dynamic in the new pipeline object, then
    that command buffer state is not disturbed. Before any draw or dispatch
    call with this pipeline there must have been at least one call to each
    of the corresponding dynamic state setting commands since the command
    buffer recording was begun, or the last bound pipeline object with that
    state specified as static, whichever was the latter."
    
    Thus once sw::allocate() no longer also zeroes this data, we should
    revert the value-initialization where possible and ensure we don't
    touch the uninitialized data ourselves, unless as a consequence of an
    application bug.
    
    Bug: b/140991626
    Change-Id: I060e8d8a79e93b0676669eed361fab4f86ab1b56
    Reviewed-on: https://swiftshader-review.googlesource.com/c/SwiftShader/+/53089
    Presubmit-Ready: Nicolas Capens <nicolascapens@google.com>
    Kokoro-Result: kokoro <noreply+kokoro@google.com>
    Tested-by: Nicolas Capens <nicolascapens@google.com>
    Reviewed-by: Alexis Hétu <sugoi@google.com>
    
  - Explicitly initialize VkSpecializationInfo fields
    
    vk::allocate() zero-initializes its memory, which was nulling the
    VkSpecializationInfo::pMapEntries field in case the mapEntryCount is 0.
    
    We'll be changing vk::allocate() to not zero-initialize, to catch cases
    where applications might incorrectly be relying on it, with
    MemorySanitizer. So we have to also not be relying on it.
    
    Bug: b/140991626
    Change-Id: I5917c902c0af27985556340dfc1dbae79010a125
    Reviewed-on: https://swiftshader-review.googlesource.com/c/SwiftShader/+/54468
    Presubmit-Ready: Nicolas Capens <nicolascapens@google.com>
    Kokoro-Result: kokoro <noreply+kokoro@google.com>
    Tested-by: Nicolas Capens <nicolascapens@google.com>
    Reviewed-by: Alexis Hétu <sugoi@google.com>
    
  - Make clang-format-all.sh only look at source files
    
    clang-format will modify non source files and has no configuration
    options to ignore bash, python, or extensionless files. This CL is a
    follow up for:
    
    https://swiftshader-review.googlesource.com/c/git-hooks/+/54569
    
    Bug: b/187094215
    Change-Id: I72953bd07e3c16b70aab441a25c27abae31b6a87
    Reviewed-on: https://swiftshader-review.googlesource.com/c/SwiftShader/+/54689
    Kokoro-Result: kokoro <noreply+kokoro@google.com>
    Reviewed-by: Nicolas Capens <nicolascapens@google.com>
    Commit-Queue: Sean Risser <srisser@google.com>
    Tested-by: Sean Risser <srisser@google.com>
    
  - Pass unclamped fragcoord.z to shader
    
    The Vulkan spec is being clarified to explain that the FragCoord passed
    to a shader should use the unclamped depth value and that only the depth
    test and depth write should use clamped values.
    
    Bug: b/184063472
    Change-Id: Ic76c13512745abea2181475eff5147134a1bf147
    Reviewed-on: https://swiftshader-review.googlesource.com/c/SwiftShader/+/54668
    Kokoro-Result: kokoro <noreply+kokoro@google.com>
    Tested-by: Sean Risser <srisser@google.com>
    Reviewed-by: Alexis Hétu <sugoi@google.com>
    Reviewed-by: Nicolas Capens <nicolascapens@google.com>
    Commit-Queue: Sean Risser <srisser@google.com>
    
  - Regres: Roll dEQP to 1.2.6-master revision 8010f59
    
    This update advances dEQP to a revision where the 1.2.6 branch is merged
    into the master branch.
    
    It uses the new 'chunked' testlists.
    
    Notable new tests:
    - Add tests for VK_EXT_provoking_vertex (https://gitlab.khronos.org/Tracker/vk-gl-cts/-/issues/2092)
    - Require geometry shaders for adjacency topologies (https://gitlab.khronos.org/Tracker/vk-gl-cts/-/issues/2906)
    - Add early fragment tests (https://gitlab.khronos.org/Tracker/vk-gl-cts/-/issues/2738)
    
    Tests: dEQP-VK.*
    Bug: b/140302392
    Bug: b/189588731
    Bug: b/167582422
    Fixes: b/189334760
    Fixes: b/185814882
    Change-Id: I278224b3e709c714f1e7e6fb750eeffbfba84578
    Reviewed-on: https://swiftshader-review.googlesource.com/c/SwiftShader/+/54568
    Tested-by: Nicolas Capens <nicolascapens@google.com>
    Kokoro-Result: kokoro <noreply+kokoro@google.com>
    Reviewed-by: Sean Risser <srisser@google.com>
    Reviewed-by: Nicolas Capens <nicolascapens@google.com>
    
  - Regres: Update test lists @ 21f81124
    
    Reactor backend: LLVM
    
    Change-Id: Id3e18f2779facfe3f441f684a40540a86d904643
    Reviewed-on: https://swiftshader-review.googlesource.com/c/SwiftShader/+/54489
    Reviewed-by: Nicolas Capens <nicolascapens@google.com>
    Tested-by: Nicolas Capens <nicolascapens@google.com>
    
  - Regres: Use 'default' dEQP target and skip GLES daily tests
    
    Using -DDEQP_TARGET=x11_egl caused a build error on some systems:
    /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
    (.text+0x20): undefined reference to `main'
    
    Using 'default' instead makes the build succeed, and makes XCB WSI tests
    pass. However, GLES tests crash. Since we no longer need them due to
    SwANGLE, with SwiftShader becoming Vulkan-only, this change removes them
    from the test run. Also, the dEQP build is reduced to just the deqp-vk
    target.
    
    Lastly, code coverage generation on 'daily' test runs is disabled. It
    produced errors such as:
    Failed to process test coverage for test 'dEQP-VK.***'.
    llvm-profdata errored. Cause: exit status 1
    
    It was already disabled locally on the Regres bot to avoid these
    errors.
    
    Bug: b/189469951
    Bug: b/152192800
    Change-Id: I07383e1168cc322bb9247ed39db091f91c054b6d
    Reviewed-on: https://swiftshader-review.googlesource.com/c/SwiftShader/+/54589
    Kokoro-Result: kokoro <noreply+kokoro@google.com>
    Tested-by: Nicolas Capens <nicolascapens@google.com>
    Reviewed-by: Nicolas Capens <nicolascapens@google.com>
    
  - Update git-hooks to latest revision
    
    Bug: b/184063472
    Change-Id: Ife9e8c7d90d43695b712ac6d1d44f9b4ec73a4df
    Reviewed-on: https://swiftshader-review.googlesource.com/c/SwiftShader/+/54669
    Reviewed-by: Nicolas Capens <nicolascapens@google.com>
    Tested-by: Sean Risser <srisser@google.com>
    Commit-Queue: Sean Risser <srisser@google.com>
    
  - Marl: Suppress MemorySanitizer false-positive
    
    Worker::current is a static thread_local which gets intialized to null,
    which gets checked for in Scheduler::Fiber::current(). Unfortunately
    MemorySanitizer does not observe the initialization when Marl is used
    within a shared library, when the Linux dynamic loader is not
    instrumented and its TLS initialization is not otherwise intercepted and
    handled correctly.
    
    This change decorates Scheduler::Fiber::current() with
    __attribute__((no_sanitize_memory)) to suppress instrumenting it with
    use-of-uninitialized-data checks.
    
    Bug: chromium:1211047
    Change-Id: I61b584922d9aba5d67991ce916c69102734f2b61
    Reviewed-on: https://swiftshader-review.googlesource.com/c/SwiftShader/+/54610
    Reviewed-by: Alexis Hétu <sugoi@google.com>
    Kokoro-Result: kokoro <noreply+kokoro@google.com>
    Tested-by: Nicolas Capens <nicolascapens@google.com>
    
  - Bring git-hooks in as a submodule
    
    git-hooks tracks git hook scripts for SwiftShader. Using git config we
    can tell git to use these scripts instead of what's in .git/hooks.
    
    Bug: b/187094215
    Change-Id: I2df090c47ceeb1b352960576a34f259b75946302
    Reviewed-on: https://swiftshader-review.googlesource.com/c/SwiftShader/+/54528
    Kokoro-Result: kokoro <noreply+kokoro@google.com>
    Reviewed-by: Nicolas Capens <nicolascapens@google.com>
    Tested-by: Sean Risser <srisser@google.com>
    Commit-Queue: Sean Risser <srisser@google.com>
    
  - Regres: Recursively load chunked mustpass lists
    
    Bug: b/189334760
    Change-Id: I27d8e54d20a534ffd5f7b0deb8d0c55c05baabdc
    Reviewed-on: https://swiftshader-review.googlesource.com/c/SwiftShader/+/54588
    Kokoro-Result: kokoro <noreply+kokoro@google.com>
    Tested-by: Nicolas Capens <nicolascapens@google.com>
    Reviewed-by: Alexis Hétu <sugoi@google.com>