Update git submodules
* Update platform/external/scudo from branch 'master'
  to c390cfda2fbbd6ae5074b26e3a367a7f2e168da8
  - [scudo] Make the placeholder type specifier be consistent with C/C++
    
    This avoids `-Wformat` complains the placeholder type specifier mismatch
    on `lld`/`llu`(used for `s64`/`u64`) which have slightly different
    interpretation in string_utils.cpp.
    
    Also enable Timer build which was disabled because of the complaining of
    `-Wformat`.
    
    Differential Revision: https://reviews.llvm.org/D147496
    
    GitOrigin-RevId: 1e36156ab1dc70f9f9b94a8d9820c819da4187be
    Change-Id: I35c36329e159e8867b02da2f2855c859279b684d
    
  - [compiler-rt] Fix -Wformat in timing.h (NFC)
    
    /home/jiefu/llvm-project/compiler-rt/lib/scudo/standalone/timing.h:181:41: error: format specifies type 'unsigned long long' but the argument has type 'u64' (aka 'unsigned long') [-Werror,-Wformat]
        Str.append("%14llu.%llu(ns) %-11s", Integral, Fraction, " ");
                    ~~~~~~                  ^~~~~~~~
                    %14lu
    /home/jiefu/llvm-project/compiler-rt/lib/scudo/standalone/timing.h:181:51: error: format specifies type 'unsigned long long' but the argument has type 'u64' (aka 'unsigned long') [-Werror,-Wformat]
        Str.append("%14llu.%llu(ns) %-11s", Integral, Fraction, " ");
                           ~~~~                       ^~~~~~~~
                           %lu
    /home/jiefu/llvm-project/compiler-rt/lib/scudo/standalone/timing.h:185:54: error: format specifies type 'unsigned long long' but the argument has type 'u64' (aka 'unsigned long') [-Werror,-Wformat]
        Str.append("%s (%llu)\n", Timers[HandleId].Name, Occurrence);
                        ~~~~                             ^~~~~~~~~~
                        %lu
    3 errors generated.
    
    GitOrigin-RevId: 99be590cb9b492825dd2cc453efc23d852594d16
    Change-Id: I2fa8a847a634d23daa6958c52a0c89c4a11aeaea