Update git submodules
* Update platform/external/Reactive-Extensions/RxCpp from branch 'master'
  to 671e288a8a2368ef5456d07faa0b7a4aec146802
  - operators: Add ref_count(other) operator overload.
    
    The existing `connectable_observable.ref_count()` operator calls
    connect on the source when it's subscribed to.
    
    Generalize this by allowing an optional parameter `other`, i.e.
    `observable.ref_count(connectable_observable other)` to be used as the
    connect target.
    
    Useful for implementing diamond graphs while retaining composability:
    
    ```
         A
       /   \
      B     C
       \   /
         D
         |
         E
    
    auto A = ... | publish();
    auto B = A | ...;
    auto C = A | ...;
    auto D = B | merge(C) | ref_count(A);
    auto E = D | ...;
    
    E | subscribe(...);
    ```
    
    Resolves: https://github.com/ReactiveX/RxCpp/issues/484
    Pull request: https://github.com/ReactiveX/RxCpp/pull/485
    
    (Need to merge this into AOSP now because it's blocking an android
    change).
    
    (cherry picked from commit 77a5b21ac18d4e42a8402176a9b3baf583b7414e)
    
    Change-Id: I9139dbce2c3b0ba4f4ca59b8300d2b4ceaef4855
    
  - android: Merge branch 'upstream-master' into master
    
    Updates to aac2fc97bc5fe680446afb5ae81bef0a9c0fbf8a in upstream.
    
    Change-Id: Ic56ec9d83b5611e734dfdbebec7c3538388f5c82
    
  - rxcpp: Fix data race in composite_subscription
    
    composite_subscription_inner had missing checks which could lead to add/remove/clear
    racing against unsubscribe.
    
    (See the issue for more details).
    
    Fixes: #475
    
  - cmake: Fix 'make' generator targets
    
    Remove 'RxCpp' library target when it's used outside of
    Visual Studio. This was supposed to be a virtual target,
    not an actual one that builds libRxCpp.so.
    
    The build never worked because it was missing setting the
    compiler/linker flags from shared.cmake
    
    Resolves: #477
    
  - README: fix cmake generation snippet for clang/linux
    
    clang should be told to use libc++, otherwise it will
    try to use libstdc++ which may be missing on some systems.
    
    Resolves: #478
    
  - Fix url to Doxygen binary tarball.
    
    The files hosted on SourceForge are not going to fade away.
    
  - Fix 'Wcatch-value'.
    
    This warning is reported by GCC 9.
    
  - make ci more reliable
    
  - fixes for replay and moved-from container not being empty
    
  - Add support for compiling rxcpp with -fno-exceptions (#456)
    
    * Minor compilation/test fixes for compiling on android
    
    Change-Id: Id623455d32e9323355744a240c2813d0411d1dac
    
    * Rx: Add support for compiling code without exceptions (-fno-exceptions)
    
    std::exception_ptr usage is replaced with rxcpp::util::error_ptr
    which will typedef to std::exception_ptr when exceptions are enabled.
    
    When exceptions are disabled this will typedef to an internal error
    type that can retain the "what" error message.
    
    Additionally std::current_exception() and similar usages are replaced
    with rxu::current_exception which uses error_ptr instead.
    
    Lastly all try/catch/throw keywords are replaced with either
    RXCPP_TRY, RXCPP_CATCH, rxu::throw_exception or similar.
    
    Note that try/catch/throw keywords cause a compilation error with
    -fno-exceptions. Trying to access most of the std::*exception* functions
    will call std::terminate at runtime.
    
    Tests using exceptions must be disabled by passing --nothrow to the
    check2 test runner.
    
    Change-Id: I0b95ae2e323653a17c3b733d165ecf87a014c315
    
    * update to catch2 and add RX_USE_EXCEPTIONS cmake option
    
    * fix bugs in doxygen examples
    
    * replace [[noreturn]] with RXCPP_NORETURN
    
    * removes support for VS 2013
    
  - Update ide build to Visual Studio 2017
  - Fix doc target missing declarations errors
    
    Building the docs (e.g. with `ninja doc`) failed with GCC (e.g. GCC 7.3
    under Fedora 27) with some missing declaration errors.
    
    Example:
    
        ../Rx/v2/examples/doxygen/main.cpp:7:13: error: no previous
        declaration for ‘std::__cxx11::string get_pid()’
        [-Werror=missing-declarations]
    
    Thus, this change adds a shared declaration for `get_pid()` that is
    included by all users/the file where it's defined such that
    accidental deviation in the signature are immediately noticed (as
    compile error).
    
    Similarly, the visibility of the example `less()` is changed to static
    as it's only locally used.
    
    With those changes the doc target succeeds again.
    

* Update platform/superproject from branch 'master'
  to a94771e47444ee3555d98afd98ad916353351f92
  - Update git submodules
    
    * Update external/Reactive-Extensions/RxCpp from branch 'master'
      to 671e288a8a2368ef5456d07faa0b7a4aec146802
      - operators: Add ref_count(other) operator overload.
        
        The existing `connectable_observable.ref_count()` operator calls
        connect on the source when it's subscribed to.
        
        Generalize this by allowing an optional parameter `other`, i.e.
        `observable.ref_count(connectable_observable other)` to be used as the
        connect target.
        
        Useful for implementing diamond graphs while retaining composability:
        
        ```
             A
           /   \
          B     C
           \   /
             D
             |
             E
        
        auto A = ... | publish();
        auto B = A | ...;
        auto C = A | ...;
        auto D = B | merge(C) | ref_count(A);
        auto E = D | ...;
        
        E | subscribe(...);
        ```
        
        Resolves: https://github.com/ReactiveX/RxCpp/issues/484
        Pull request: https://github.com/ReactiveX/RxCpp/pull/485
        
        (Need to merge this into AOSP now because it's blocking an android
        change).
        
        (cherry picked from commit 77a5b21ac18d4e42a8402176a9b3baf583b7414e)
        
        Change-Id: I9139dbce2c3b0ba4f4ca59b8300d2b4ceaef4855
        
      - android: Merge branch 'upstream-master' into master
        
        Updates to aac2fc97bc5fe680446afb5ae81bef0a9c0fbf8a in upstream.
        
        Change-Id: Ic56ec9d83b5611e734dfdbebec7c3538388f5c82
        
      - rxcpp: Fix data race in composite_subscription
        
        composite_subscription_inner had missing checks which could lead to add/remove/clear
        racing against unsubscribe.
        
        (See the issue for more details).
        
        Fixes: #475
        
      - cmake: Fix 'make' generator targets
        
        Remove 'RxCpp' library target when it's used outside of
        Visual Studio. This was supposed to be a virtual target,
        not an actual one that builds libRxCpp.so.
        
        The build never worked because it was missing setting the
        compiler/linker flags from shared.cmake
        
        Resolves: #477
        
      - README: fix cmake generation snippet for clang/linux
        
        clang should be told to use libc++, otherwise it will
        try to use libstdc++ which may be missing on some systems.
        
        Resolves: #478
        
      - Fix url to Doxygen binary tarball.
        
        The files hosted on SourceForge are not going to fade away.
        
      - Fix 'Wcatch-value'.
        
        This warning is reported by GCC 9.
        
      - make ci more reliable
        
      - fixes for replay and moved-from container not being empty
        
      - Add support for compiling rxcpp with -fno-exceptions (#456)
        
        * Minor compilation/test fixes for compiling on android
        
        Change-Id: Id623455d32e9323355744a240c2813d0411d1dac
        
        * Rx: Add support for compiling code without exceptions (-fno-exceptions)
        
        std::exception_ptr usage is replaced with rxcpp::util::error_ptr
        which will typedef to std::exception_ptr when exceptions are enabled.
        
        When exceptions are disabled this will typedef to an internal error
        type that can retain the "what" error message.
        
        Additionally std::current_exception() and similar usages are replaced
        with rxu::current_exception which uses error_ptr instead.
        
        Lastly all try/catch/throw keywords are replaced with either
        RXCPP_TRY, RXCPP_CATCH, rxu::throw_exception or similar.
        
        Note that try/catch/throw keywords cause a compilation error with
        -fno-exceptions. Trying to access most of the std::*exception* functions
        will call std::terminate at runtime.
        
        Tests using exceptions must be disabled by passing --nothrow to the
        check2 test runner.
        
        Change-Id: I0b95ae2e323653a17c3b733d165ecf87a014c315
        
        * update to catch2 and add RX_USE_EXCEPTIONS cmake option
        
        * fix bugs in doxygen examples
        
        * replace [[noreturn]] with RXCPP_NORETURN
        
        * removes support for VS 2013
        
      - Update ide build to Visual Studio 2017
      - Fix doc target missing declarations errors
        
        Building the docs (e.g. with `ninja doc`) failed with GCC (e.g. GCC 7.3
        under Fedora 27) with some missing declaration errors.
        
        Example:
        
            ../Rx/v2/examples/doxygen/main.cpp:7:13: error: no previous
            declaration for ‘std::__cxx11::string get_pid()’
            [-Werror=missing-declarations]
        
        Thus, this change adds a shared declaration for `get_pid()` that is
        included by all users/the file where it's defined such that
        accidental deviation in the signature are immediately noticed (as
        compile error).
        
        Similarly, the visibility of the example `less()` is changed to static
        as it's only locally used.
        
        With those changes the doc target succeeds again.