Update git submodules
* Update platform/external/google-benchmark from branch 'master'
  to bcbecb683674a719ac9ed6795f52a03d7ee6a5ef
  - Upgrade google-benchmark to 97393e5ef820fda0330830d56c774949b4cfbb29
    
    Test: build
    Change-Id: I2afa3a5d723880ba40dd66e87c54cd86801e01fd
    
  - Add -lpthread to pkg-config Libs.private. (#755)
    
    Since pthread is required at least for GCC (according to the
    documentation), this should be reflected by the pkg-config file.
    
    The same is, for instance, also done by the gflags library:
    https://github.com/gflags/gflags/blob/1005485222e8b0feff822c5723ddcaa5abadc01a/cmake/package.pc.in#L13
  - Move Statistics struct to internal namespace (#753)
    
    
  - Fix header lines length (#752)
    
    Commit 17a012d7 added a newline to the str, so the line built from
    str.length() is one character longer than it should be.
  - Add minimal Conan support (#728)
    
    
  - Set CMP0048 policy before project() to silence warnings (#750)
    
    If this policy isn't set, CMake emits a large warning when project() is
    called from a cmake subdirectory.
    
    This came up when the benchmark library was added to the LLVM build, and
    it was reported in https://llvm.org/PR38874. This patch was the fix I
    applied locally to fix the issue, and I wanted to send it upstream.
  - Print at least three significant digits for times. (#701)
    
    Some benchmarks are particularly sensitive and they run in less than
    a nanosecond. In order for the console reporter to provide meaningful
    output for such benchmarks it needs to be able to display the times
    using more resolution than a single nanosecond.
    
    This patch changes the console reporter to print at least three
    significant digits for all results.
    
    Unlike the initial attempt, this patch does not align the decimal point.
  - README.md: document State::{Pause,Resume}Timing()
    
    As pointed out in IRC, these are not documented.
  - Update documentation of benchmark_filter (#744)
    
    It should now match reality.
  - #722 Adding Host Name in Reporting (#733)
    
    * Adding Host Name and test
    
    * Addressing Review Comments
    
    * Adding Test for JSON Reporter
    
    * Adding HOST_NAME_MAX for MacOS systems
    
    * Adding Explaination for MacOS HOST_NAME_MAX Addition
    
    * Addressing Peer Review Comments
    
    * Adding codecvt in windows header guard
    
    * Changing name SystemInfo and adding empty message incase host name fetch fails
    
    * Adding Comment on Struct SystemInfo
    
  - Update reference to complexity calculation (#723)
    
    
  - Fix signed vs unsigned comparisons in string_util unit tests (#742)
    
    Unit-tests fail to build due to the following errors:
    
    /home/cfx/Dev/google-benchmark/benchmark.git/test/string_util_gtest.cc:12:5: required from here
    /home/cfx/Applications/googletest-1.8.1/include/gtest/gtest.h:1444:11: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
       if (lhs == rhs) {
           ~~~~^~~~~~
    
    Fixes #741
  - [tools] Run autopep8 and apply fixes found. (#739)
    
    
  - Remove use of std::tmpnam. (#734)
    
    std::tmpnam is deprecated and its use is discouraged. For our purposes
    in the tests, we really just need a file name which is unlikely to
    exist.
    
    This patch converts the tests to using a dummy random file name
    generator, which should hopefully avoid name conflicts.
  - README.md: complexity lambda takes int64_t arg. Fixes #719
  - StrFormat() is a printf-like function, mark it as such, fix fallout. (#727)
    
    Fixes #714.
  - README.md: BM_Sequential(): the return type is 'void'
    
    Used that example as a snippet, and it took a moment to notice
    what needed to be changed to make it compile..
  - Fix C++17 mode compilation with Apple clang (#721)
    
    
  - Merge branch 'atdt-report_loadavg'
    
  - Merge branch 'report_loadavg' of https://github.com/atdt/benchmark into atdt-report_loadavg
    
  - Ensure all informational cmake messages have STATUS type
    
  - Disable exceptions in Microsoft STL (#715)
    
    This is the copy of patch proposed to LLVM's copy of benchmark via
    https://reviews.llvm.org/D52998.
  - Add Ori Livneh to AUTHORS and CONTRIBUTORS
    
  - Include system load average in console and JSON reports
    
    High system load can skew benchmark results. By including system load averages
    in the library's output, we help users identify a potential issue in the
    quality of their measurements, and thus assist them in producing better (more
    reproducible) results.
    
    I got the idea for this from Brendan Gregg's checklist for benchmark accuracy
    (http://www.brendangregg.com/blog/2018-06-30/benchmarking-checklist.html).
    

* Update platform/superproject from branch 'master'
  to 6daef5b1195fafd95819384faeb5fb32b12c82b2
  - Update git submodules
    
    * Update external/google-benchmark from branch 'master'
      to bcbecb683674a719ac9ed6795f52a03d7ee6a5ef
      - Upgrade google-benchmark to 97393e5ef820fda0330830d56c774949b4cfbb29
        
        Test: build
        Change-Id: I2afa3a5d723880ba40dd66e87c54cd86801e01fd
        
      - Add -lpthread to pkg-config Libs.private. (#755)
        
        Since pthread is required at least for GCC (according to the
        documentation), this should be reflected by the pkg-config file.
        
        The same is, for instance, also done by the gflags library:
        https://github.com/gflags/gflags/blob/1005485222e8b0feff822c5723ddcaa5abadc01a/cmake/package.pc.in#L13
      - Move Statistics struct to internal namespace (#753)
        
        
      - Fix header lines length (#752)
        
        Commit 17a012d7 added a newline to the str, so the line built from
        str.length() is one character longer than it should be.
      - Add minimal Conan support (#728)
        
        
      - Set CMP0048 policy before project() to silence warnings (#750)
        
        If this policy isn't set, CMake emits a large warning when project() is
        called from a cmake subdirectory.
        
        This came up when the benchmark library was added to the LLVM build, and
        it was reported in https://llvm.org/PR38874. This patch was the fix I
        applied locally to fix the issue, and I wanted to send it upstream.
      - Print at least three significant digits for times. (#701)
        
        Some benchmarks are particularly sensitive and they run in less than
        a nanosecond. In order for the console reporter to provide meaningful
        output for such benchmarks it needs to be able to display the times
        using more resolution than a single nanosecond.
        
        This patch changes the console reporter to print at least three
        significant digits for all results.
        
        Unlike the initial attempt, this patch does not align the decimal point.
      - README.md: document State::{Pause,Resume}Timing()
        
        As pointed out in IRC, these are not documented.
      - Update documentation of benchmark_filter (#744)
        
        It should now match reality.
      - #722 Adding Host Name in Reporting (#733)
        
        * Adding Host Name and test
        
        * Addressing Review Comments
        
        * Adding Test for JSON Reporter
        
        * Adding HOST_NAME_MAX for MacOS systems
        
        * Adding Explaination for MacOS HOST_NAME_MAX Addition
        
        * Addressing Peer Review Comments
        
        * Adding codecvt in windows header guard
        
        * Changing name SystemInfo and adding empty message incase host name fetch fails
        
        * Adding Comment on Struct SystemInfo
        
      - Update reference to complexity calculation (#723)
        
        
      - Fix signed vs unsigned comparisons in string_util unit tests (#742)
        
        Unit-tests fail to build due to the following errors:
        
        /home/cfx/Dev/google-benchmark/benchmark.git/test/string_util_gtest.cc:12:5: required from here
        /home/cfx/Applications/googletest-1.8.1/include/gtest/gtest.h:1444:11: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
           if (lhs == rhs) {
               ~~~~^~~~~~
        
        Fixes #741
      - [tools] Run autopep8 and apply fixes found. (#739)
        
        
      - Remove use of std::tmpnam. (#734)
        
        std::tmpnam is deprecated and its use is discouraged. For our purposes
        in the tests, we really just need a file name which is unlikely to
        exist.
        
        This patch converts the tests to using a dummy random file name
        generator, which should hopefully avoid name conflicts.
      - README.md: complexity lambda takes int64_t arg. Fixes #719
      - StrFormat() is a printf-like function, mark it as such, fix fallout. (#727)
        
        Fixes #714.
      - README.md: BM_Sequential(): the return type is 'void'
        
        Used that example as a snippet, and it took a moment to notice
        what needed to be changed to make it compile..
      - Fix C++17 mode compilation with Apple clang (#721)
        
        
      - Merge branch 'atdt-report_loadavg'
        
      - Merge branch 'report_loadavg' of https://github.com/atdt/benchmark into atdt-report_loadavg
        
      - Ensure all informational cmake messages have STATUS type
        
      - Disable exceptions in Microsoft STL (#715)
        
        This is the copy of patch proposed to LLVM's copy of benchmark via
        https://reviews.llvm.org/D52998.
      - Add Ori Livneh to AUTHORS and CONTRIBUTORS
        
      - Include system load average in console and JSON reports
        
        High system load can skew benchmark results. By including system load averages
        in the library's output, we help users identify a potential issue in the
        quality of their measurements, and thus assist them in producing better (more
        reproducible) results.
        
        I got the idea for this from Brendan Gregg's checklist for benchmark accuracy
        (http://www.brendangregg.com/blog/2018-06-30/benchmarking-checklist.html).