Update git submodules
* Update platform/build/kati from branch 'master'
  to d4641a8f4179234bf95f334fac6621edcaf40370
  - Merge remote-tracking branch 'aosp/upstream'
    
    * aosp/upstream:
      Add debug location info into the regen stamp file
      Improve ckati_stamp_dump
      Display include stack when encountering an error.
      func: rewrite a loop to appease -Wunreachable-code-loop-increment
    
    Test: treehugger
    Change-Id: I6b7745ba9f82c352fc29040d744afef1be34f546
    
  - Merge pull request #186 from danw/improve_regen_dump
    
    Improve regen dump
  - Add debug location info into the regen stamp file
    
    This makes it easier to figure out where different shell commands are
    coming from.
    
    Change-Id: I0eef9cd28eb39e5ca2961ee650bd498e34e94ced
    
  - Improve ckati_stamp_dump
    
    Support dumping out globs, shell commands, and emulated find commands to
    improve debugging and analysis of regen stamp files.
    
    Change-Id: I80c09a07d2c468d03d416dfa6b1cebce5d5a3fcd
    
  - Merge pull request #185 from pcc/include-stack
    
    Display include stack when encountering an error.
  - Display include stack when encountering an error.
    
  - Merge pull request #183 from gburgessiv/master
    
    func: rewrite a loop to appease -Wunreachable-code-loop-increment
  - func: rewrite a loop to appease -Wunreachable-code-loop-increment
    
    This warning catches loops that can only execute once. It's unhappy
    about the following code:
    
    ```
    build/kati/func.cc:286:3: error: loop will run at most once (loop
    increment never executed) [-Werror,-Wunreachable-code-loop-increment]
      for (StringPiece tok : WordScanner(text)) {
      ^~~
    ```
    
    Since that behavior seems intended here, just tweak the code to silence
    the warning.
    
    b/150166387
    
    Test: TreeHugger passed at
    https://android-review.googlesource.com/c/platform/build/kati/+/1252837