Update git submodules
* Update platform/external/perfetto from branch 'master'
  to aa9175d6761d7ff7a172d637fda4a17df64453b5
  - Merge "proto: Update prefix of GpuLog's Severity enum again"
  - proto: Update prefix of GpuLog's Severity enum again
    
    Turns out that SEVERITY_ERROR is also taken by winerror.h:
    
    --
    gen/third_party/perfetto\protos/perfetto/trace/gpu/gpu_log.pb.h(204,29): error: expected member name or ';' after declaration specifiers
      static constexpr Severity SEVERITY_ERROR =
      ~~~~~~~~~~~~~~~~~~~~~~~~~ ^
    ..\..\third_party\depot_tools\win_toolchain\vs_files\418b3076791776573a815eb298c8aa590307af63\win_sdk\Include\10.0.18362.0\shared\winerror.h(28780,29): note: expanded from macro 'SEVERITY_ERROR'
                                ^
    --
    
    TBR: primiano@google.com
    Change-Id: I7f02e3694254680e1b95fe3937d85e423a17e429
    

* Update platform/superproject from branch 'master'
  to 24317ecf87bd48997a9bfd0918264f1b2f0eaf0a
  - Update git submodules
    
    * Update external/perfetto from branch 'master'
      to aa9175d6761d7ff7a172d637fda4a17df64453b5
      - Merge "proto: Update prefix of GpuLog's Severity enum again"
      - proto: Update prefix of GpuLog's Severity enum again
        
        Turns out that SEVERITY_ERROR is also taken by winerror.h:
        
        --
        gen/third_party/perfetto\protos/perfetto/trace/gpu/gpu_log.pb.h(204,29): error: expected member name or ';' after declaration specifiers
          static constexpr Severity SEVERITY_ERROR =
          ~~~~~~~~~~~~~~~~~~~~~~~~~ ^
        ..\..\third_party\depot_tools\win_toolchain\vs_files\418b3076791776573a815eb298c8aa590307af63\win_sdk\Include\10.0.18362.0\shared\winerror.h(28780,29): note: expanded from macro 'SEVERITY_ERROR'
                                    ^
        --
        
        TBR: primiano@google.com
        Change-Id: I7f02e3694254680e1b95fe3937d85e423a17e429