Update git submodules
* Update platform/superproject from branch 'master'
  to 987a53240ebd24c2d1a02909b9275aa55c996c99
  - Update git submodules
    
    * Update system/memory/libion from branch 'master'
      to 4f98785e4debdc8090fc0d5bfda2574b60f6ce46
      - Switch to using 0 instead of NULL for a void* -> int cast
        
        system/memory/libion/ion.c:51:32: error: cast to smaller integer type 'ion_user_handle_t' (aka 'int') from 'void *' [-Werror,-Wvoid-pointer-to-int-cast]
                int err = ion_free(fd, (ion_user_handle_t)NULL);
                                       ^~~~~~~~~~~~~~~~~~~~~~~
        
        Bug: http://b/155835175
        Test: m with aosp_blueline
        Change-Id: I0d663ddbc245764b469c4f589831586ea7e55148
        

* Update platform/system/memory/libion from branch 'master'
  to 4f98785e4debdc8090fc0d5bfda2574b60f6ce46
  - Switch to using 0 instead of NULL for a void* -> int cast
    
    system/memory/libion/ion.c:51:32: error: cast to smaller integer type 'ion_user_handle_t' (aka 'int') from 'void *' [-Werror,-Wvoid-pointer-to-int-cast]
            int err = ion_free(fd, (ion_user_handle_t)NULL);
                                   ^~~~~~~~~~~~~~~~~~~~~~~
    
    Bug: http://b/155835175
    Test: m with aosp_blueline
    Change-Id: I0d663ddbc245764b469c4f589831586ea7e55148