Update git submodules
* Update platform/external/kotlinc from branch 'master'
  to 0fae9f9bc0cea3630328a745b346bbcc63dfef47
  - Upgrade to Kotlin 1.6.10
    
    Test: make
    Merged-In: I5756c093886932822e8e3669dba2f82cbe5ac6e0
    Change-Id: I5756c093886932822e8e3669dba2f82cbe5ac6e0
    
  - Update Kotlin compiler to 1.5.30 am: b1bbba3335 am: bff72f0798 am: 29dbedaabd
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1828075
    
    Change-Id: If63c45ef76a27232cd96addfaf194c8587ab3f82
    
  - Update Kotlin compiler to 1.5.30 am: b1bbba3335 am: bff72f0798
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1828075
    
    Change-Id: Ib6443375b116c2287df9dea5744fb5de0320b5ed
    
  - Update Kotlin compiler to 1.5.30 am: b1bbba3335
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1828075
    
    Change-Id: I1af04c234475be6ec85e9a97abea078249212f6c
    
  - Add apex_available to kotlin-stdlib am: de64cc51f5 am: 5fd06fcd9b
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1783938
    
    Change-Id: I711217f5a34b5505d969ed9bb62ecfec36c2defb
    
  - Add apex_available to kotlin-stdlib am: de64cc51f5
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1783938
    
    Change-Id: I6741c6a37b58aafa1fa9abf528a7ab298d22ef1f
    
  - Upgrade to kotlinc 1.5.21 am: d16115e7c7 am: 5efa9c12b9
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1775565
    
    Change-Id: I874c94e8aea956001e6fef990902e9a4377c8400
    
  - Upgrade to kotlinc 1.5.21 am: d16115e7c7
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1775565
    
    Change-Id: I96797d33cfbf11ad191cd67396532fca20b12dcb
    
  - Revert^2 "Upgrade to kotlinc v1.5.0" am: cc8434fb96 am: 0dc360387f
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1709768
    
    Change-Id: I77fbbcd3c57e7be3ccd089884382c2b0b87e293f
    
  - Revert "Upgrade to kotlinc v1.5.0" am: 4d583b8478 am: 3ee194938f am: 5846cd11ce am: a68e3f5c48
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1705748
    
    Change-Id: Ia81d9c0949b7a4c52ab0c9c044edad85bd9bdcff
    
  - Revert "Upgrade to kotlinc v1.5.0" am: 4d583b8478 am: 3ee194938f am: 5846cd11ce
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1705748
    
    Change-Id: I88ba3a84337fb2bcecf58369d2c3bac5153d58b4
    
  - Revert "Upgrade to kotlinc v1.5.0" am: 4d583b8478 am: 3ee194938f
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1705748
    
    Change-Id: I3a9e1703d986a384a0339dc9a9510330bff58e1c
    
  - Upgrade to kotlinc v1.5.0 am: 74359acd4d am: 0483ca6709 am: ab7a24955d am: 08a6e68c36
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1697785
    
    Change-Id: I73dc2270e22ddaedd2081f94e41cb57639bdb540
    
  - Upgrade to kotlinc v1.5.0 am: 74359acd4d am: 0483ca6709 am: ab7a24955d
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1697785
    
    Change-Id: Ibf30aeed662b5599ac8d776cdeecb34726061e9c
    
  - Upgrade to kotlinc v1.5.0 am: 74359acd4d am: 0483ca6709
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1697785
    
    Change-Id: I0e08542a9c82702c070a9e5815da0b3db53c19c9
    
  - [automerger skipped] Mark ab/7061308 as merged in stage. am: 16a27a9391 -s ours am: 2a9ce7eb7a -s ours
    
    am skip reason: Change-Id Ic3d10111dec61600f6ee7c691a7e7be3985776a3 with SHA-1 cc351dda40 is in history
    
    Original change: undetermined
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I00cdf6913b7b1736f5381eb5eb3bccbceee1cc6a
    
  - [automerger skipped] Mark ab/7061308 as merged in stage. am: 16a27a9391 -s ours
    
    am skip reason: Change-Id Ic3d10111dec61600f6ee7c691a7e7be3985776a3 with SHA-1 cc351dda40 is in history
    
    Original change: undetermined
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I162c7050ab0d72d9df99aaeb5cf4be4fc6a6e9c2
    
  - Upgrade kotlinc to v1.4.30 am: 610ce4e685 am: b08245c672 am: cc6b0c1d0b
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1592918
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I731ca785cb8e0083519133cdd373da7fb946cf9d
    
  - Upgrade kotlinc to v1.4.30 am: 610ce4e685 am: b08245c672
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1592918
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I78802886da7a8301c8bc973d9767665f6fa53cbe
    
  - [LSC] Add LOCAL_LICENSE_KINDS to external/kotlinc am: 816a21ed45 am: ea6bb32672 am: 06bf5c80f5
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1588704
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I50d95e8a937b4f3c93b5910d1e3f3539c37d8fea
    
  - [LSC] Add LOCAL_LICENSE_KINDS to external/kotlinc am: 816a21ed45 am: ea6bb32672
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1588704
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Ie1f9990cdd24ac3f7b54409d461bbb1493d1aad8
    
  - Fix license_type. Contains LGPL am: 76ce61d4c5 am: ff1164e0a6 am: 8138c72e3b
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1556488
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I408d81102c59bee336606bd673f4c2a309b6d748
    
  - Fix license_type. Contains LGPL am: 76ce61d4c5 am: ff1164e0a6
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1556488
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Ie90f4599a7cb8ee859ac24a51298319fab15d360
    
  - [automerger skipped] Use Apache license for jars am: 4f32aae332 -s ours
    
    am skip reason: Change-Id Ibf0c549571c2b4ea68243a1e6e185a1dbc9f2325 with SHA-1 071a2ac80c is in history
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/external/kotlinc/+/13163838
    
    Change-Id: Idfb76cfb9d51aafc2400be38c1d5f5013ec35f3b
    
  - Update Kotlin compiler to custom 1.4.20 with IR fixes. am: 64ab879540 am: ba555b31fa am: cc351dda40
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1512507
    
    Change-Id: Ib9ac677c15a68b68f9d9cc409e94eb2a852157fa
    
  - Use Apache license for jars
    
    The individual jars exported as Soong modules are covered by the
    Apache license in license/NOTICE.txt, not by the combined licenses
    in the LICENSE file.
    
    See license/README.md for explanation why this is correct.
    
    Bug: 174167893
    Test: manual
    Change-Id: Ibf0c549571c2b4ea68243a1e6e185a1dbc9f2325
    Merged-In: Ibf0c549571c2b4ea68243a1e6e185a1dbc9f2325
    (cherry picked from commit 071a2ac80cf4d269856bd1ddde6d4432852b5d91)
    
  - Use Apache license for jars am: 071a2ac80c am: 0fcd78ec90 am: ea9eab8da9
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1512506
    
    Change-Id: Id2aaf88658c222f39e2ab5fcf4c2be3f8c9e3668
    
  - Merge "Mark ab/6881855 as merged" into stage-aosp-master am: 36738a119c am: 0343ccf72e
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/external/kotlinc/+/13110684
    
    Change-Id: Ibf808e91026e8bcd7007df2e933a51630c90f83a
    
  - Upgrade kotlinc to v1.4.20 am: 66706209b0 am: 487dccdafa am: 1011edf397
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1505014
    
    Change-Id: I29370d33445f5da5b59159dfa336aadfd351287c
    
  - [automerger skipped] Skip ab/6749736 in stage. am: 549e50fe37 -s ours am: a99bf0ee30 -s ours am: 674a934e2d -s ours
    
    am skip reason: Change-Id Ib452d251f6141fb7a182a8d3646b43d5d147a234 with SHA-1 ca978263af is in history
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/external/kotlinc/+/12797134
    
    Change-Id: I0151a0c76e61be643772b8fe0e633be2851daf8d
    
  - Upgrade kotlinc to v1.4.10 am: a8149698b9 am: 6f805a9f41 am: 5ab0e883ae am: 7afc25b996 am: 449953adfd
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1424408
    
    Change-Id: I2969f4a168d8e3354e9a9132555204f4f6afbfbd
    
  - Exclude META-INF/versions from all kotlin jars am: 39ad356abc am: 897b5c51c9 am: 542e57a378 am: e73f518199 am: ba2cf067e2
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1414373
    
    Change-Id: I8c6cbe76ce80364d1137db063f105b7e2ca3ce02
    
  - Upgrade kotlinc to v1.4.0 am: 445d013533 am: 6535434873 am: 71ff40283e am: 330cd7ed82 am: 1ccf370e01
    
    Original change: https://android-review.googlesource.com/c/platform/external/kotlinc/+/1404227
    
    Change-Id: Ic14c7f15f6e42bb87888c11b5ddf619587a6d1a7
    
  - Upgrade kotlinc to v1.3.72 am: f160735557 am: f301753662 am: d8ab5ad3c0 am: ca978263af am: 4fdf794ef3
    
    Change-Id: I3afc72627f5a3c6bde1022e8ce8e3ff09c529fdc
    
  - [automerger skipped] DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp into stag-aosp-master am: cf955d014f -s ours am: fe8c8d4e14 am: 69e9d5e5b0 am: def6e1d1e8 -s ours
    
    am skip reason: subject contains skip directive
    
    Change-Id: Ia56292694702716cc02fe142269e9ea86a45e7e8
    
  - Remove redundant NOTICE copied from LICENSE. am: c783f66280 am: 60a8a03743 am: 3fe525f4d6 am: 3abdc49fc3 am: e46d4ba6ad
    
    Change-Id: Ifb00e49549d6d8476a0f6114fe4dbda9a203fe15
    
  - Upgrade kotlinc to v1.3.71 am: e498d607e2 am: 08e3ceeb17 am: f4219ad1b8 am: e70f0ffea5 am: cfae158982
    
    Change-Id: If85ba090533abf2656c8cfcf2b81d37966f6b034
    
  - [automerger skipped] DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp@6304901 into stag-aosp-master am: d28aae301b -s ours am: 3bd7c82c29 am: 483975abf2 am: 5109317a1f -s ours
    
    am skip reason: subject contains skip directive
    
    Change-Id: Ic90592b0a24d0740e3d1adc0d904bd5e4cf2700a
    
  - Merge "Upgrade kotlinc to v1.3.70" am: 9961c905f8 am: f890329a52 am: 3630aa209e am: 6476f1a6f1 am: 3305a8acfa
    
    Change-Id: I93d79f482748b32f93e24f404c2b94d7db183644
    

* Update platform/frameworks/base from branch 'master'
  to d1b31d480aa997606a44df635e7fe014df0b68f1
  - Merge "Remove usage of IntegerRes in type usage target"
  - Remove usage of IntegerRes in type usage target
    
    Fixes:
    frameworks/base/packages/SystemUI/src/com/android/systemui/media/RecommendationViewHolder.kt:50:40: error: this annotation is not applicable to target 'type usage'
        val mediaCoverItemsResIds = listOf<@IntegerRes Int>(
                                           ^
    
    Test: make -j
    Merged-In: I55129c609ecc26ee71f234778de379d31c9e9cb6
    Change-Id: I55129c609ecc26ee71f234778de379d31c9e9cb6