Update git submodules
* Update platform/packages/apps/QuickSearchBox from branch 'master'
  to d8e7350656c972d7f362d60f21b82fad6ad3254e
  - Merge "API level 30 upgrade: AOSP/QuickSearchBox"
  - API level 30 upgrade: AOSP/QuickSearchBox
    
    The AndroidManifest.xml files of the AOSP QuickSearchBox
    app has been upgraded so that its targetSDKversion is 30.
    
    Test: manual - after the change, the QuickSearchBox app
    built, initialized, and ran successfully with all of
    the UI features functioning properly. Unit tests for
    calendar were also run and the output can be seen below:
    
    com.android.quicksearchbox.CachingIconLoaderTest:.
    com.android.quicksearchbox.LevenshteinFormatterTest:.........................
    com.android.quicksearchbox.PackageIconLoaderTest:..
    com.android.quicksearchbox.SuggestionUtilsTest:......
    com.android.quicksearchbox.util.CachedLaterTest:
    Error in testClear:
    java.lang.NoSuchMethodError: No virtual method clear()V in class Lcom/android/quicksearchbox/util/CachedLater; or its super classes (declaration of 'com.android.quicksearchbox.util.CachedLater' appears in /data/app/~~AC-UvA9XEuLV32lpA6GUtg==/com.android.quicksearchbox-smIQj4ydi76Wg9zv90-ApA==/base.apk)
    	at com.android.quicksearchbox.util.CachedLaterTest.testClear(CachedLaterTest.java:86)
    	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:195)
    	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:181)
    	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:563)
    	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2230)
    
    Error in testGetLaterAfterClear:
    java.lang.NoSuchMethodError: No virtual method clear()V in class Lcom/android/quicksearchbox/util/CachedLater; or its super classes (declaration of 'com.android.quicksearchbox.util.CachedLater' appears in /data/app/~~AC-UvA9XEuLV32lpA6GUtg==/com.android.quicksearchbox-smIQj4ydi76Wg9zv90-ApA==/base.apk)
    	at com.android.quicksearchbox.util.CachedLaterTest.testGetLaterAfterClear(CachedLaterTest.java:69)
    	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:195)
    	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:181)
    	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:563)
    	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2230)
    ....
    com.android.quicksearchbox.util.LevenshteinDistanceTest:.....
    com.android.quicksearchbox.util.PerNameExecutorTest:
    Error in testCancelPendingTasks:
    java.lang.NoSuchMethodError: No interface method cancelPendingTasks()V in class Lcom/android/quicksearchbox/util/NamedTaskExecutor; or its super classes (declaration of 'com.android.quicksearchbox.util.NamedTaskExecutor' appears in /data/app/~~AC-UvA9XEuLV32lpA6GUtg==/com.android.quicksearchbox-smIQj4ydi76Wg9zv90-ApA==/base.apk)
    	at com.android.quicksearchbox.util.PerNameExecutorTest.testCancelPendingTasks(PerNameExecutorTest.java:70)
    	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:195)
    	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:181)
    	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:563)
    	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2230)
    
    Error in testClose:
    java.lang.NoSuchMethodError: No interface method close()V in class Lcom/android/quicksearchbox/util/NamedTaskExecutor; or its super classes (declaration of 'com.android.quicksearchbox.util.NamedTaskExecutor' appears in /data/app/~~AC-UvA9XEuLV32lpA6GUtg==/com.android.quicksearchbox-smIQj4ydi76Wg9zv90-ApA==/base.apk)
    	at com.android.quicksearchbox.util.PerNameExecutorTest.testClose(PerNameExecutorTest.java:94)
    	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:195)
    	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:181)
    	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:563)
    	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2230)
    .
    com.android.quicksearchbox.util.PriorityThreadFactoryTest:.
    com.android.quicksearchbox.util.SingleThreadNamedTaskExecutorTest:.
    Test results for InstrumentationTestRunner=...................................E.E.....
    .....E.E...
    Time: 0.284
    
    FAILURES!!!
    Tests run: 50,  Failures: 0,  Errors: 4
    
    As seen, although there are no failures, there are 4 errors
    that have remained since the last API upgrade. These will
    be addressed in a later CL.
    
    General CTS tests were run as well and the output is below:
    
    ================= Results ==================
    =============== Consumed Time ==============
        arm64-v8a CtsProviderTestCases: 16m 3s
    Total aggregated tests run time: 16m 3s
    ============== TOP 1 Slow Modules ==============
        arm64-v8a CtsProviderTestCases: 0.39 tests/sec [376 tests / 963984 msec]
    ============== Modules Preparation Times ==============
        arm64-v8a CtsProviderTestCases => prep = 9872 ms || clean = 2292 ms
    Total preparation time: 9s  ||  Total tear down time: 2s
    =======================================================
    =============== Summary ===============
    Total Run time: 17m 45s
    1/1 modules completed
    Total Tests       : 376
    PASSED            : 362
    FAILED            : 0
    IGNORED           : 6
    ASSUMPTION_FAILURE: 8
    ============== End of Results ==============
    
    Change-Id: Ia9dfc3dab994b4e7224f5e26d90a3e7fd0651482
    
  - Merge "Fix issues caught by Android Lint" am: 5d3c19ca7d
    
    Original change: https://android-review.googlesource.com/c/platform/packages/apps/QuickSearchBox/+/1346565
    
    Change-Id: Ifecfa029fd9ed0424c490f225435a5e437f87c67