Update git submodules
* Update platform/external/turbine from branch 'master'
  to 54111aedb4aca0eed4847d5f4fc0e7bc83760566
  - Merge remote-tracking branch 'aosp/upstream-main'
    
    * aosp/upstream-main: (86 commits)
      Handle unicode characters that require two UTF-16 code units
      Sort test inputs
      Update to setup-java v2, and use adopt builds
      Address compile errors that would appear when `ImmutableMap` is annotated for nullness in CL 382342656.
      Remove obsolete parent per https://github.com/sonatype/oss-parents
      Fix handling of repackaged transitive classes in jdeps
      Inline a single-use abstract test class
      Fix javadoc
      Inherit from the sonatype oss parent artifact
      Test invalid annotation element values are weeded out
      Satisfy the nullness checker.
      Use `assertThrows` for expected exception tests
      Don't require an argument for `--compress_jar`
      Satisfy the nullness checker
      Fix NPEs in options parsing
      Remove deprecated builders
      Rename `master` branch to `main`
      Never class-load `TurbineProcessingEnvironment` from the `-processor`
      Update Error Prone and maven versions
      Update turbine CI JDK versions
      ...
    
    Bug: 193141629
    Test: m checkbuild
    Change-Id: If2e91cfa8c0b7d307acceb119b5ac4b195a4a237
    
  - Handle unicode characters that require two UTF-16 code units
    
    PiperOrigin-RevId: 384756101
    
  - Sort test inputs
    
    PiperOrigin-RevId: 384751933
    
  - Update to setup-java v2, and use adopt builds
    
    https://github.com/actions/setup-java/blob/main/docs/switching-to-v2.md
    
    PiperOrigin-RevId: 384750269
    
  - Address compile errors that would appear when `ImmutableMap` is annotated for nullness in CL 382342656.
    
    PiperOrigin-RevId: 382560098
    
  - Remove obsolete parent per https://github.com/sonatype/oss-parents
    
    PiperOrigin-RevId: 380698526
    
  - Fix handling of repackaged transitive classes in jdeps
    
    Turbine supports running with only direct dependencies on the classpath (see
    https://github.com/google/turbine/commit/d1509927c68b994ecb9eb95a8ae8478da9f04ed4).
    In this mode it repackages transitive supertypes of classes referenced in the
    compilation, and saves them in the output jar under `META-INF/TRANSITIVE`.
    
    When turbine records classes that were used in the compilation for `jdeps`
    output, it was reporting the jar that it loaded a repackaged transitive class
    from, instead of the jar where that repackaged transitive class was originally
    found.
    
    This change adds a `TurbineTransitiveJar` class file attribute to the
    repackaged classes that records the path of the jar file they were originally
    seen in, and updates the `jdeps` logic to report that original path instead of
    the jar where the repackaged class was observed.
    
    PiperOrigin-RevId: 380075237
    
  - Inline a single-use abstract test class
    
    PiperOrigin-RevId: 379840987
    
  - Fix javadoc
    
    * fix doclint
    * configure maven javadoc plugin
    * add javadoc to CI
    
    PiperOrigin-RevId: 379626123
    
  - Inherit from the sonatype oss parent artifact
    
    And stop passing `--illegal-access=` to tests since it's going
    away in 17.
    
    PiperOrigin-RevId: 379616951
    
  - Test invalid annotation element values are weeded out
    
    before annotation processing happens.
    
    PiperOrigin-RevId: 378303757
    
  - Satisfy the nullness checker.
    
    PiperOrigin-RevId: 378288869
    
  - Use `assertThrows` for expected exception tests
    
    PiperOrigin-RevId: 375819105
    
  - Don't require an argument for `--compress_jar`
    
    Follow-up to https://github.com/google/turbine/commit/db341bf77802d683f52ffc0fc68f433c6d954446
    
    PiperOrigin-RevId: 375515519
    
  - Satisfy the nullness checker
    
    PiperOrigin-RevId: 375173482
    
  - Fix NPEs in options parsing
    
    PiperOrigin-RevId: 375158538
    
  - Remove deprecated builders
    
    PiperOrigin-RevId: 375150352
    
  - Rename `master` branch to `main`
    
    PiperOrigin-RevId: 375143727
    
  - Never class-load `TurbineProcessingEnvironment` from the `-processor`
    
    since it gives dagger access to an internal API, to avoid skew if turbine
    is on the `-processorpath`.
    
    Continue to only do classloader masking for other APIs if the built-in
    annotation processor features are enabled.
    
    Follow-up to https://github.com/google/turbine/commit/3bbf96736b45e2450d41b4ee1ca355402ef3f46d
    
    PiperOrigin-RevId: 374933572
    
  - Update Error Prone and maven versions
    
    PiperOrigin-RevId: 373889180
    
  - Update turbine CI JDK versions
    
    PiperOrigin-RevId: 373677082
    
  - Improve `--builtin_processors` handling
    
    Load all processor classes from the `--processorpath` when
    `--builtin_processors` is unset, instead of unconditionally loading core
    classes like Guava and the Dagger SPI from the host classloader, to avoid skew
    in integration tests using older versons of Dagger.
    
    Follow-up to: unknown commit
    
    PiperOrigin-RevId: 373597566
    
  - Fix handling of `isDefault()` for symbols loaded from the classpath
    
    PiperOrigin-RevId: 368258927
    
  - Eliminate `core.transform` wrapper.
    
    We no longer need it now that we don't specify `ignore_noop = True`.
    
    (Also, run `buildifier third_party/java_src/turbine/copy.bara.sky`, which turns out to just sort the symbols in a `load()`.)
    
    PiperOrigin-RevId: 363447735
    
  - Fix copybara config
    
    PiperOrigin-RevId: 363281354
    
  - Try out more null-checking
    
    PiperOrigin-RevId: 363057464
    
  - Comply with nullness analysis
    
    Startblock:
      unknown commit is submitted
      unknown commit is submitted
      unknown commit is submitted
    PiperOrigin-RevId: 362735853
    
  - Improve GitHub Actions hygiene
    
    context: unknown commit, https://github.com/google/go-github/pull/1821
    PiperOrigin-RevId: 362600035
    
  - Throw a more specific exception
    
    PiperOrigin-RevId: 361261767
    
  - Fix some potential NPEs
    
    PiperOrigin-RevId: 361261029
    
  - Don't read `<clinit>`s from class files
    
    This was causing an error when checking required annotation elements for
    annotations with `<clinit>`s read from bytecode:
    
    ```
    error: missing required annotation argument: <clinit>
    @Foo
    ```
    
    https://github.com/bazelbuild/bazel/issues/13144
    
    PiperOrigin-RevId: 360553027
    
  - Allow turbine to parse JavaBuilder command lines
    
    Add a couple of aliases, and skip some flags that only apply to JavaBuilder.
    
    PiperOrigin-RevId: 359867369
    
  - [LSC] Add LOCAL_LICENSE_KINDS to external/turbine am: 9b74b95fd8
    
    Original change: https://android-review.googlesource.com/c/platform/external/turbine/+/1588973
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I144ea1d71d7b0eaf319b4cc04a98972fab9b8889
    
  - Weed out non-annotation types appearing as nested annotation values
    
    to avoid a crash during lowering when we try to read the annotation
    metadata.
    
    PiperOrigin-RevId: 357781574
    
  - Don't include type annotations in a turbine diagnostic
    
    this fixes a crash if a diagnostic is reported on a type that has
    an ill-formed annotation (which will be reported as a separate
    diagnostic, but prevents the type from being pretty-printed).
    
    PiperOrigin-RevId: 356406155
    
  - Include all simple names present in source for error types
    
    When creating error types to model invalid elements during annotation processing,
    include all simple names present in source for qualified names, instead of
    just the last one.
    
    This fixes https://github.com/bazelbuild/bazel/issues/12926
    
    PiperOrigin-RevId: 355249091
    
  - Get tests running on latest JDK 16 EA
    
    * set necessary `--add-exports=` and `--add-opens=` flags to allow the
      Error Prone plugin to access internal javac APIs when running on
      JDK 16
    
    * set `--illegal-access=permit` to allow access of internal javac APIs
      by tests
    
    PiperOrigin-RevId: 353304282
    
  - Update to latest ASM API level
    
    PiperOrigin-RevId: 353278492
    
  - Log and continue past more errors
    
    To tolerate inputs were the definition of an annotation is initially
    missing, but is generated by an annotation processor.
    
    Motivated by https://github.com/bazelbuild/bazel/issues/12871
    
    PiperOrigin-RevId: 353140504
    
  - Add private constructors for classes that aren't intended to be instantiated
    
    PiperOrigin-RevId: 352623709
    
  - turbine OSS build cleanups
    
    * update versions of some dependencies
    * enabled Error Prone
    * set version to `HEAD-SNAPSHOT` to keep release versions out of the `main` branch
    
    PiperOrigin-RevId: 352112709
    
  - Refactor turbine external CI
    
    Run 16-ea by default, only test with 15 on windows and macos.
    
    PiperOrigin-RevId: 349364427
    
  - Refactor `ClassLoader` setup in `Processing`
    
    Move `ClassLoader` creation to a helper method, and change the main
    entry point to accept a `ClassLoader` as an argument instead of
    doing the creation itself. This is a no-op pre-factoring.
    
    PiperOrigin-RevId: 347056368
    
  - Remove travis and appveyor CI configuration
    
    PiperOrigin-RevId: 347051432
    
  - Set sourceEncoding in turbine's `pom.xml`
    
    Fixes https://maven.apache.org/general.html#encoding-warning
    
    PiperOrigin-RevId: 346929313
    
  - Fix syntax of `.gitattributes`
    
    PiperOrigin-RevId: 346896852
    
  - Update ASM version
    
    PiperOrigin-RevId: 346894059
    
  - Configure turbine's bootclasspath in integration tests to match javac
    
    currently javac is defaulting to the latest supported bootclasspath in
    the annotation processing API tests, and the skew is breaking tests
    on JDK 15 due to changes in system APIs in that release.
    
    PiperOrigin-RevId: 346863290
    
  - Handle `ct.sym` format for JDK >= 12
    
    The entry paths now include the module name of the class as a prefix,
    regardless of `--release` version.
    
    Before:
    
    ```
    876/java/lang/Object.sig
    ```
    
    After:
    
    ```
    B/java.base/java/lang/Object.sig
    ```
    
    PiperOrigin-RevId: 346846804
    
  - Fix `ct.sym` handling for Java versions >= 10
    
    PiperOrigin-RevId: 346695662
    
  - Refactor an `if`/`else` into an enum switch
    
    PiperOrigin-RevId: 346649737
    
  - Enable end-of-line normalization in `.gitattributes`
    
    See https://github.com/actions/checkout/issues/135, this fixes a test failure
    in GitHub Actions involving the line endings in a test output.
    
    PiperOrigin-RevId: 346590309
    
  - Report a better error if the order of `extends` and `implements` is swapped
    
    ```
    error: 'extends' most come before 'implements'
    class T implements A extends B {}
                         ^
    ```
    PiperOrigin-RevId: 346587630
    
  - Clean up `-source` parsing
    
    use `SourceVersion.valueOf` to support the latest version supported by
    the current runtime, without having to compile turbine against the
    corresponding version (i.e. to support `-source 11` without referencing
    `RELEASE_11` statically.)
    
    PiperOrigin-RevId: 346445262
    
  - Allow `--gensrc_output` and `--resource_output` to be directories
    
    for convenience when using Turbine as an annotation processing library,
    in process with javac.
    
    PiperOrigin-RevId: 346385275
    
  - Add initial GitHub Actions config for turbine
    
    PiperOrigin-RevId: 346339430
    
  - Report more diagnostics for invalid annotations at once
    
    instead of reporting missing annotation values one at a time.
    
    PiperOrigin-RevId: 346139063
    
  - Fix an invalid cast
    
    https://github.com/bazelbuild/bazel/issues/12605
    
    PiperOrigin-RevId: 345742937
    
  - Weed out `final` interface methods
    
    As required by the spec:
    
    > an interface method may not be declared ... with the modifiers final, ...
    
    https://docs.oracle.com/javase/specs/jls/se11/html/jls-9.html#jls-9.4
    
    > Methods of interfaces may have any of the flags in Table 4.6-A set except ACC_PROTECTED, ACC_FINAL, ...
    
    https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-4.html#jvms-4.6
    
    Turbine still assumes valid input and relies on javac for error handling,
    but best-effort handling of this case will make instances of
    https://youtrack.jetbrains.com/issue/KT-35716 easier to debug.
    
    PiperOrigin-RevId: 340267486
    
  - Upgrade junit dependency to 4.13.1
    
    PiperOrigin-RevId: 336966883
    
  - Fix handling of @SupportedAnnotationTypes("*")
    
    The specification requires that processors claiming all annotations should
    process all files, even if those files don't have annotations:
    
    > `"*"` by itself represents the set of all annotation types, including the
    > empty set. Note that a processor should not claim `"*"` unless it is actually
    > processing all files; claiming unnecessary annotations may cause a
    > performance slowdown in some environments.
    
    https://docs.oracle.com/en/java/javase/15/docs/api/java.compiler/javax/annotation/processing/Processor.html#getSupportedAnnotationTypes()
    
    PiperOrigin-RevId: 335964308
    
  - Add a ClassPath binder that adapts a StandardJavaFileManager
    
    PiperOrigin-RevId: 335223650
    
  - Remove some no-op round trip conversions
    
    PiperOrigin-RevId: 333553703
    
  - Micro-optimize TurbineExecutableElement#getKind
    
    retrieving the MethodInfo is more expensive than looking at the symbol.
    
    PiperOrigin-RevId: 333428787
    
  - Report errors for required annotation arguments
    
    PiperOrigin-RevId: 332886383
    
  - Imitate javac's handling of type annotations on derived types
    
    Type annotations get removed from erased class types (but not arrays, for some
    reason), and from the results of directSupertypes. This fixes an issue with an
    annotation processor that was calling TypeMirror#toString and including the
    text in source output in.
    
    PiperOrigin-RevId: 332774092
    
  - Preserve erroneous supertypes during type canonicalization
    
    PiperOrigin-RevId: 322848985
    
  - Fix a crash parsing types
    
    PiperOrigin-RevId: 321269121
    
  - Disable Appveyor CI branch builds to reduce load.
    
    PiperOrigin-RevId: 321092646
    
  - Add missing license headers.
    
    PiperOrigin-RevId: 321069308
    
  - Fix a crash in annotation binding
    
    PiperOrigin-RevId: 320276568
    
  - Weed out uses of primitives in generics
    
    to avoid translating them into class files with invalid signatures,
    which turbine will later reject during class reading.
    
    PiperOrigin-RevId: 319827566
    
  - Fix parsing of -source
    
    It is usually, but not necessarily, the same as -target, and
    ProcessingEnvironment#getSourceVersion should return the former.
    
    PiperOrigin-RevId: 319271555
    
  - Add an explicit nullcheck with a failure message
    
    JAVA_HOME can be null when running on e.g. graalvm/native-image, in which case
    --release is unsupported.
    
    PiperOrigin-RevId: 318532110
    
  - Fix an infinite loop
    
    on unclosed generics in variable initializer parsing.
    
    PiperOrigin-RevId: 316293980
    
  - Fix some redundancies
    
    PiperOrigin-RevId: 316170108
    
  - Don't trim diagnostic text from annotation processors
    
    context: unknown commit
    PiperOrigin-RevId: 310657863
    
  - Fix broken JLS links.
    
    PiperOrigin-RevId: 309319270
    
  - Bump various dependency versions to latest
    
    Fixes #50
    
    COPYBARA_INTEGRATE_REVIEW=https://github.com/google/turbine/pull/50 from google:eaftan-dep-bump 648ed58cdd02c5c2ab2c051fcc05b7dd93e4004a
    PiperOrigin-RevId: 309128521
    
  - Update ASM to 8.0
    
    Fixes #48
    
    COPYBARA_INTEGRATE_REVIEW=https://github.com/google/turbine/pull/48 from google:eaftan-update-asm bcae98bd3b76ce8dba1ed458a5f953a42170b0e2
    PiperOrigin-RevId: 307905591
    
  - Always run the final processing round
    
    even if there were unrecoverable errors. Some processors batch up diagnostics and
    emit them on the final round, so bailing out without running the final round can
    cause the compilation to fail without reporting all relevant diagnostics.
    
    PiperOrigin-RevId: 307548452
    
  - Merge pull request #46 from google:eaftan-update-guava
    
    PiperOrigin-RevId: 307506226
    
  - Automatic code cleanup.
    
    PiperOrigin-RevId: 307137059
    
  - Update Guava to 29.0
  - Javadoc typo fix.
    
    PiperOrigin-RevId: 306475910
    
  - Fix NonCanonicalType warnings.
    
    PiperOrigin-RevId: 306298262
    
  - Stop passing SKIP_DEBUG in javac-turbine
    
    The latest version of ASM skips method parameters attributes when SKIP_DEBUG
    is set, which prevents javac-turbine from including them in its output:
    https://gitlab.ow2.org/asm/asm/-/commit/6623d07425b251b6d2ac14fd6d5582c04936e912
    
    GOOGLE:
    RELNOTES: N/A
    PiperOrigin-RevId: 305809948
    
  - Fix typo in Javadoc.
    
    PiperOrigin-RevId: 305761082
    
  - Project import generated by Copybara.
    
    PiperOrigin-RevId: 305723800