Update git submodules
* Update platform/bionic from branch 'master'
  to 17b2add51452455fa257bb78e92a1c982cf5327a
  - Merge "remove bionic-compile-time-tests-g++"
  - remove bionic-compile-time-tests-g++
    
    make checkbuild gives the following error:
    bionic/tests/fortify_filecheck_diagnostics_test.cpp:1:0: error: unknown value 'cortex-a55' for -mcpu
    
    The error is because we have a clang to support the new architecture,
    but not a corresponding GCC. It is not trivial to filter out an invalid
    CPU, and since there is no platform code built with GCC any more, its
    better to remove bionic-compile-time-tests-g++
    
    Bug: 74404306
    Test: builds
    Change-Id: I6aa181c652abeef782fec6380dfadd066140b8b9
    

* Update platform/superproject from branch 'master'
  to 780567017d7537a49071597acebc767af8e5815a
  - Update git submodules
    
    * Update bionic from branch 'master'
      to 17b2add51452455fa257bb78e92a1c982cf5327a
      - Merge "remove bionic-compile-time-tests-g++"
      - remove bionic-compile-time-tests-g++
        
        make checkbuild gives the following error:
        bionic/tests/fortify_filecheck_diagnostics_test.cpp:1:0: error: unknown value 'cortex-a55' for -mcpu
        
        The error is because we have a clang to support the new architecture,
        but not a corresponding GCC. It is not trivial to filter out an invalid
        CPU, and since there is no platform code built with GCC any more, its
        better to remove bionic-compile-time-tests-g++
        
        Bug: 74404306
        Test: builds
        Change-Id: I6aa181c652abeef782fec6380dfadd066140b8b9