Update git submodules
* Update platform/libnativehelper from branch 'master'
  to 84e576a16b5d21b1cfb875623e03bdff5f96924c
  - Merge "Fix an issue where a pointer was used instead of a char*"
  - Fix an issue where a pointer was used instead of a char*
    
    libnativehelper/JniInvocation.c:164:40: error: format specifies type 'char *' but the argument has type 'DlLibrary' (aka 'void *') [-Werror,-Wformat]
          ALOGE("Failed to dlopen %s: %s", library, DlGetError());
                                  ~~       ^~~~~~~
    
    Bug: http://b/155835175
    Test: m with aosp_blueline
    Change-Id: I2473574822cf819be4fe0b4db49b94b174f34696
    

* Update platform/superproject from branch 'master'
  to 5375273ff35ffc19be9539418ffb17511426bf44
  - Update git submodules
    
    * Update libnativehelper from branch 'master'
      to 84e576a16b5d21b1cfb875623e03bdff5f96924c
      - Merge "Fix an issue where a pointer was used instead of a char*"
      - Fix an issue where a pointer was used instead of a char*
        
        libnativehelper/JniInvocation.c:164:40: error: format specifies type 'char *' but the argument has type 'DlLibrary' (aka 'void *') [-Werror,-Wformat]
              ALOGE("Failed to dlopen %s: %s", library, DlGetError());
                                      ~~       ^~~~~~~
        
        Bug: http://b/155835175
        Test: m with aosp_blueline
        Change-Id: I2473574822cf819be4fe0b4db49b94b174f34696