Update git submodules
* Update platform/superproject from branch 'master'
  to 7368ff842fb9e7b763525eb9982e3ad622702522
  - Update git submodules
    
    * Update system/update_engine from branch 'master'
      to f650fa41940c0792b72f5c7299d952537bf6f3db
      - Regenerate checked-in update_metadata_pb2.py with aprotoc
        
        Fixes this error:
        AttributeError: 'module' object has no attribute '_internal_create_key'
        
        Test: run it
        Change-Id: I2621090c87e614bbc5ba6c9be22e60d7ed066173
        

* Update platform/system/update_engine from branch 'master'
  to f650fa41940c0792b72f5c7299d952537bf6f3db
  - Regenerate checked-in update_metadata_pb2.py with aprotoc
    
    Fixes this error:
    AttributeError: 'module' object has no attribute '_internal_create_key'
    
    Test: run it
    Change-Id: I2621090c87e614bbc5ba6c9be22e60d7ed066173