Update git submodules
* Update platform/external/autotest from branch 'master'
  to ee46241ef3623dc047d6e4c8e4afda8a9a107741
  - video_Video{Decode, Encode}Accelerator: Remove args_dict out of control files
    am: 1ae148f888
    
    Change-Id: Idff57ce9dc26a44f6991fcb307b0e7646fe63bb0
    
  - video_Video{Decode, Encode}Accelerator: Remove args_dict out of control files
    
    When tests are run locally by test_that, tests failed with an error
    "Unhandled TypeError: run_once() got an unexpected keyword argument 'servo_host'".
    This is caused by passing **args_dict in arguments in control files.
    This removes it in order to enable to run the tests locally.
    
    BUG=None
    TEST=video_VideoDecodeAccelerator and video_VideoEncodeAccelerator
    
    Change-Id: Id763176a1c089f23cdb63ff287ee944f71ec3944
    Reviewed-on: https://chromium-review.googlesource.com/1331195
    Commit-Ready: Hirokazu Honda <hiroh@chromium.org>
    Tested-by: Hirokazu Honda <hiroh@chromium.org>
    Reviewed-by: Chih-Yu Huang <akahuang@chromium.org>
    

* Update platform/superproject from branch 'master'
  to 59d5a8cf82a9f8934cc4843209a73c1b743c8d55
  - Update git submodules
    
    * Update external/autotest from branch 'master'
      to ee46241ef3623dc047d6e4c8e4afda8a9a107741
      - video_Video{Decode, Encode}Accelerator: Remove args_dict out of control files
        am: 1ae148f888
        
        Change-Id: Idff57ce9dc26a44f6991fcb307b0e7646fe63bb0
        
      - video_Video{Decode, Encode}Accelerator: Remove args_dict out of control files
        
        When tests are run locally by test_that, tests failed with an error
        "Unhandled TypeError: run_once() got an unexpected keyword argument 'servo_host'".
        This is caused by passing **args_dict in arguments in control files.
        This removes it in order to enable to run the tests locally.
        
        BUG=None
        TEST=video_VideoDecodeAccelerator and video_VideoEncodeAccelerator
        
        Change-Id: Id763176a1c089f23cdb63ff287ee944f71ec3944
        Reviewed-on: https://chromium-review.googlesource.com/1331195
        Commit-Ready: Hirokazu Honda <hiroh@chromium.org>
        Tested-by: Hirokazu Honda <hiroh@chromium.org>
        Reviewed-by: Chih-Yu Huang <akahuang@chromium.org>