Update git submodules
* Update platform/development from branch 'master'
  to 62ce42ad0a15370ac71c411f3803dfcb40125614
  - Merge "Update lint baseline for AutofillKeyboard"
  - Update lint baseline for AutofillKeyboard
    
    The new lint version finds more NewApi errors.
    
    Test: m lint-check
    Change-Id: I190bbf97000312dc4911552594374d36d8782d7b
    

* Update platform/packages/modules/NetworkStack from branch 'master'
  to 618c19b5a17883f216823fbec35f149c77937630
  - Merge "Remove NetworkShimImpl mock in TcpSocketTrackerTest"
  - Remove NetworkShimImpl mock in TcpSocketTrackerTest
    
    Lint flags the usage of NetworkShimImpl in TcpSocketTrackerTest:
    packages/modules/NetworkStack/tests/unit/src/com/android/networkstack/netlink/TcpSocketTrackerTest.java:234: Error: Class requires API level S (current min is 29): NetworkShimImpl [NewApi]
                    .spyStatic(NetworkShimImpl.class)
                               ~~~~~~~~~~~~~~~~~~~~~
    
    Remove the NetworkShimImpl mock that is not used.
    
    Test: atest TcpSocketTrackerTest
    Test: m lint-check
    Change-Id: Ifd8994e36bb024d5ea79c4cdb8a99faa0a1472b7
    

* Update platform/prebuilts/cmdline-tools from branch 'master'
  to 54f85f289c447eff51dfa6a9eaad4af9d256ace5
  - Update Android.bp for new paths
    
    update_prebuilts.sh puts lint-tests.jar in the top of the tree, and
    the latest versions of lint rename some of the jar files.
    
    Test: m lint-check
    Change-Id: Iddfcfed24f3c697bd6ed3a73ad38d2cd7824573d
    
  - Update cmdline-tools to ab/7748865
    
    https://ci.android.com/builds/submitted/7748865/studio-linux/latest
    
    Test: treehugger
    Change-Id: I12a42f831c2184557f06368e71393f0896c10655
    
  - Add script for downloading lint updates
    
    Test: ./uppdate-prebuilts.sh 7486794
    Change-Id: I7a1e6e48e99c7f3d0bfe4ad6e69748b3ca8e539b
    
  - Introduce Android Lint test support in Soong am: 34a182b364 am: 2ad6d20aa6
    
    Original change: https://android-review.googlesource.com/c/platform/prebuilts/cmdline-tools/+/1776367
    
    Change-Id: If960ddcb2eddfa5b036f2ee4a76e964af35033d8
    
  - Introduce Android Lint test support in Soong am: 34a182b364
    
    Original change: https://android-review.googlesource.com/c/platform/prebuilts/cmdline-tools/+/1776367
    
    Change-Id: I7aec8bc1a837b028ee5ea2f5bd31dc92c24ab115
    
  - Update prebuilts/cmdline-tools to 7486794 am: d7db3f7589 am: 2fd35ef578
    
    Original change: https://android-review.googlesource.com/c/platform/prebuilts/cmdline-tools/+/1746780
    
    Change-Id: I5714cfdef0ab37eb233bb3c4aa6d1a77e65cd550
    
  - Update prebuilts/cmdline-tools to 7486794 am: d7db3f7589
    
    Original change: https://android-review.googlesource.com/c/platform/prebuilts/cmdline-tools/+/1746780
    
    Change-Id: I89c0266737b4bbea0892422c7d7fce17b932e902
    
  - [automerger skipped] Update prebuilts/cmdline-tools to the latest version am: c1f3cdfcf7 -s ours
    
    am skip reason: skip tag Change-Id Ia6a0ca5df6a5d1843bc57ec0fef3193478c350cb with SHA-1 8420704427 is already in history
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/prebuilts/cmdline-tools/+/14126035
    
    Change-Id: If99367f273b0147e2dec53b376abe70a49f5eeca
    
  - [automerger skipped] Repackage lint into a standalone jar am: 9cee107972 -s ours
    
    am skip reason: skip tag Change-Id Iea1272200b3578b0f7bd3ad8c985e7a38fc4cf09 with SHA-1 bda50ab053 is already in history
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/prebuilts/cmdline-tools/+/14126034
    
    Change-Id: Iaa798a3187cb312d777655af8fff3f64072f2c56
    
  - Update prebuilts/cmdline-tools to the latest version
    
    Test: m lint-check droid
    Merged-In: Ia6a0ca5df6a5d1843bc57ec0fef3193478c350cb
    Change-Id: Ia6a0ca5df6a5d1843bc57ec0fef3193478c350cb
    
  - Repackage lint into a standalone jar
    
    The lint shell script in tools/bin/lint uses tools/lib/lint-classpath.jar
    as its classpath.  That jar contains a list of other jars that java adds
    to the classpath.  This makes it impossible for the build system to track
    dependencies.
    
    Use a genrule to read the jars from tools/lib/lint-classpath.jar and then
    merge them all together into a single jar.  The result is then embedded
    into a self-contained java_binary.
    
    Bug: 181681346
    Test: m lint && lint --help
    Merged-In: Iea1272200b3578b0f7bd3ad8c985e7a38fc4cf09
    Change-Id: Iea1272200b3578b0f7bd3ad8c985e7a38fc4cf09
    
  - Update prebuilts/cmdline-tools to the latest version am: 8420704427 am: 1d85538aaf am: 946c1177a7
    
    Original change: https://android-review.googlesource.com/c/platform/prebuilts/cmdline-tools/+/1664906
    
    Change-Id: I42410b1aa15269dbda5c8309ba1a6a26dcd038a8
    
  - Update prebuilts/cmdline-tools to the latest version am: 8420704427 am: 1d85538aaf
    
    Original change: https://android-review.googlesource.com/c/platform/prebuilts/cmdline-tools/+/1664906
    
    Change-Id: Ibdd00df8089e310b105560d4c0cfe95e0e786d7c
    
  - Repackage lint into a standalone jar am: bda50ab053 am: 0f03d555d5 am: b181eba1f2
    
    Original change: https://android-review.googlesource.com/c/platform/prebuilts/cmdline-tools/+/1619830
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Ibe11ef4e26be73e7777d776b9d8573427f18391b
    
  - Repackage lint into a standalone jar am: bda50ab053 am: 0f03d555d5
    
    Original change: https://android-review.googlesource.com/c/platform/prebuilts/cmdline-tools/+/1619830
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I16dd6a32f5d69352754b967b25beb0fa16036fed
    
  - [LSC] Add LOCAL_LICENSE_KINDS to prebuilts/cmdline-tools am: 7d3caa2227 am: 25264b28c1 am: cce9cd3867
    
    Original change: https://android-review.googlesource.com/c/platform/prebuilts/cmdline-tools/+/1587742
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Icc6a87bd855c16da60eff775256efa55fcd38198
    
  - [LSC] Add LOCAL_LICENSE_KINDS to prebuilts/cmdline-tools am: 7d3caa2227 am: 25264b28c1
    
    Original change: https://android-review.googlesource.com/c/platform/prebuilts/cmdline-tools/+/1587742
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I0bbd6122102c04ea2e99eed55751d7608bf4a625
    
  - [automerger skipped] Export jars needed to compile new lint checkers am: 3e865a8272 am: 4237c162a1 -s ours
    
    am skip reason: Change-Id I969779f4fa3b63f77f9da27d73130e50a7219634 with SHA-1 3e865a8272 is in history
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/prebuilts/cmdline-tools/+/12273579
    
    Change-Id: I92d942d29351a45090cbb2622710e81966a602ff
    
  - [automerger skipped] Add SDK cmdline-tools version 2.0 am: b9e97b6969 am: f179dfb3ce -s ours
    
    am skip reason: Change-Id I62b7c6dab5e99419928243de825b5d0da21b6466 with SHA-1 b9e97b6969 is in history
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/prebuilts/cmdline-tools/+/11917801
    
    Change-Id: I42ebdfbab9bbaabc1d702a1876a42315b701ebd0
    
  - [automerger skipped] Export jars needed to compile new lint checkers am: 3e865a8272 am: 9dd8cf43e4 am: 6c5a91fb37 -s ours am: 73343c6ff9 -s ours
    
    am skip reason: Change-Id I969779f4fa3b63f77f9da27d73130e50a7219634 with SHA-1 3e865a8272 is in history
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/prebuilts/cmdline-tools/+/12273579
    
    Change-Id: Iad5aeaa1e4d479b4e410948343e91b21a5da625e
    
  - [automerger skipped] Export jars needed to compile new lint checkers am: 3e865a8272 -s ours am: 626d92d721 -s ours am: 36db650c62 -s ours am: 7feb1a4fc0 -s ours
    
    am skip reason: Change-Id I969779f4fa3b63f77f9da27d73130e50a7219634 with SHA-1 3e865a8272 is in history
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/prebuilts/cmdline-tools/+/12273579
    
    Change-Id: I2e1e5187d3116399b55b68fc2c333a6df3775f0f
    
  - [automerger skipped] Export jars needed to compile new lint checkers am: 3e865a8272 am: 9dd8cf43e4 -s ours am: 8c8e6c3c3e -s ours am: 4c39bdcee7 -s ours
    
    am skip reason: Change-Id I969779f4fa3b63f77f9da27d73130e50a7219634 with SHA-1 1b7d724e36 is in history
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/prebuilts/cmdline-tools/+/12273579
    
    Change-Id: I81d355c74651558294243d4bbd08fff3813b8515
    
  - Export jars needed to compile new lint checkers am: 3e865a8272
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/prebuilts/cmdline-tools/+/12273579
    
    Change-Id: I8334dfe46e38c22d5e8b5933431ae34ab253a0b0
    
  - Export jars needed to compile new lint checkers am: 1b7d724e36 am: a7bb537bef am: 2ea589336b am: c4e78357f3 am: 026c746bc9
    
    Original change: https://android-review.googlesource.com/c/platform/prebuilts/cmdline-tools/+/1351002
    
    Change-Id: I873ad8a79ee2c5e8cf1de0b7a5351e8ce6dec650
    
  - [automerger skipped] Add SDK cmdline-tools version 2.0 am: b9e97b6969 -s ours am: 87e55e7521 -s ours am: 3d80eee03e -s ours am: a7b9004657 -s ours
    
    am skip reason: Change-Id I62b7c6dab5e99419928243de825b5d0da21b6466 with SHA-1 b9e97b6969 is in history
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/prebuilts/cmdline-tools/+/11917801
    
    Change-Id: Ic02499c4fa2d382cd2e6cbb9f88678364d2d8f3b
    
  - [automerger skipped] Add SDK cmdline-tools version 2.0 am: b9e97b6969 am: a59e47d163 am: f02b6b7892 -s ours am: de2a2d34d5 -s ours
    
    am skip reason: Change-Id I62b7c6dab5e99419928243de825b5d0da21b6466 with SHA-1 b9e97b6969 is in history
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/prebuilts/cmdline-tools/+/11917801
    
    Change-Id: I2262cb590830474cfa59a9e9470ec633d1ce9490
    
  - [automerger skipped] Add SDK cmdline-tools version 2.0 am: b9e97b6969 am: a59e47d163 -s ours am: f22110a2c0 -s ours am: 26ed3d2b83 -s ours
    
    am skip reason: Change-Id I62b7c6dab5e99419928243de825b5d0da21b6466 with SHA-1 ce0be67699 is in history
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/prebuilts/cmdline-tools/+/11917801
    
    Change-Id: I6c3a24bbd73121f05a92edb5d50046e1f58c6ac2
    
  - Add SDK cmdline-tools version 2.0 am: b9e97b6969
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/prebuilts/cmdline-tools/+/11917801
    
    Change-Id: I06c51f1884bec465f0405a317dec4528c22eea43
    
  - Add SDK cmdline-tools version 2.0 am: ce0be67699 am: cc1928fc8b am: 68a92b9e38 am: 91f1030eba am: a3be090aab
    
    Original change: https://android-review.googlesource.com/c/platform/prebuilts/cmdline-tools/+/1324474
    
    Change-Id: Ib58a26168ac9b4033e902ecbd0c20943b5da96b8