Update git submodules
* Update platform/external/jemalloc_new from branch 'master'
  to 6412c821280e850ea070e6da2f9378c4c277abda
  - Disable je_* renaming for integration tests
    
    The integration tests fail to build with musl because the je_*
    declarations use __attribute__(nothrow), which doesn't match the
    declarations in musl.  When the je_* declarations are renamed
    to remove the je_ suffix, they collide with the musl declarations
    and fail with:
    external/jemalloc_new/include/jemalloc/jemalloc.h:197:28: error: exception specification in declaration does not match previous declaration
        void JEMALLOC_NOTHROW       *je_malloc(size_t size)
                                     ^
    external/jemalloc_new/include/jemalloc/jemalloc_rename.h:38:21: note: expanded from macro 'je_malloc'
                        ^
    external/musl/include/stdlib.h:42:7: note: previous declaration is here
    void *malloc (size_t);
          ^
    
    Set JEMALLOC_NO_RENAME for the integration tests so they use the
    je_* names.  This will also avoid the tests accidentally calling the
    libc methods.
    
    Bug: 190084016
    Test: m USE_HOST_MUSL=true jemalloc_integrationtests_basic
    Test: out/host/linux-x86/nativetest/jemalloc5_integrationtests/basic
    Change-Id: Iddc7e0f9ecb688487484ed413ad8c81ce548cc5f
    
  - Support compiling libjemalloc5 against musl am: 7326a7c470 am: 727713db35
    
    Original change: https://android-review.googlesource.com/c/platform/external/jemalloc_new/+/1776846
    
    Change-Id: I2d551e55038906c2005fb5596e7b70fc9997dd78
    
  - Support compiling libjemalloc5 against musl am: 7326a7c470
    
    Original change: https://android-review.googlesource.com/c/platform/external/jemalloc_new/+/1776846
    
    Change-Id: I2697e627273c1073073cce8634bb13ca7c3195fd
    
  - [automerger skipped] Mark ab/7061308 as merged in stage. am: 8b28ac89b2 -s ours am: 13cbf156c1 -s ours
    
    am skip reason: Change-Id I35e35d979fb8aea7926cfa2ea8f5fa084287b7bd with SHA-1 ad8f39c73d is in history
    
    Original change: undetermined
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Ibdea17b1d4a38a96fc0b93d5f06d9415044567d6
    
  - [automerger skipped] Mark ab/7061308 as merged in stage. am: 8b28ac89b2 -s ours
    
    am skip reason: Change-Id I35e35d979fb8aea7926cfa2ea8f5fa084287b7bd with SHA-1 ad8f39c73d is in history
    
    Original change: undetermined
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I3feb1543663d3ed32237c0c58e686859fb637397
    
  - [LSC] Add LOCAL_LICENSE_KINDS to external/jemalloc_new am: 33d62c57c1 am: 0c24e096eb am: 289a9908c1
    
    Original change: https://android-review.googlesource.com/c/platform/external/jemalloc_new/+/1588856
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I7ff4c068610d84777a9864ffbca957de609f1793
    
  - [LSC] Add LOCAL_LICENSE_KINDS to external/jemalloc_new am: 33d62c57c1 am: 0c24e096eb
    
    Original change: https://android-review.googlesource.com/c/platform/external/jemalloc_new/+/1588856
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Ie8b2b72402f9fca570ae02ad3b84255a62109a5f
    
  - Mark ab/6881855 as merged am: d21b7bb14a am: ad8f39c73d
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/external/jemalloc_new/+/13110682
    
    Change-Id: I78809f036f29f27c78e7719bf4661db7c414b63c
    
  - Merge "Make vendor_ramdisk_available." am: 4a13357c76 am: 8565f18203 am: 19b86d9b44 am: 6e6a931704
    
    Original change: https://android-review.googlesource.com/c/platform/external/jemalloc_new/+/1469669
    
    Change-Id: Ia5b5209fe7fae90eb635d7c14b3b490b7519b96a
    
  - Bionic and kernel system include paths are no longer implicit. am: 838a8c58b2 am: b32ec89beb am: 69c835d562 am: 8d41b14439 am: 48b2f6625e
    
    Change-Id: I14d7bbdb38e436f55946a7d7abe9f09b93fbd5dc
    
  - Add METADATA to jemalloc_new: BSD+Apache2+MIT=NOTICE am: 5b79d5eb49 am: e1ae8c6d19 am: 2c69f2c796 am: 79aac14c11 am: 10b196c21e
    
    Change-Id: I634f7d6227689a292ab372a43b75034e8337dbd2
    
  - [automerger skipped] Only retain for 64 bit. am: d3a7616aa2 am: ae06453fb8 am: 45117afe65 am: 21acbb987d -s ours am: 863cc44626 -s ours
    
    am skip reason: Change-Id Iaec8276582f880145a1ca5ebbaa65789f46d2bf2 with SHA-1 d3a7616aa2 is in history
    
    Change-Id: I3e1f37723e8d551c6ce70a735039832644fda2d3
    
  - [automerger skipped] Only retain for 64 bit. am: d3a7616aa2 -s ours am: 1e79f023e8 -s ours am: 002ab15677 -s ours am: 2413e29bc4 -s ours
    
    am skip reason: Change-Id Iaec8276582f880145a1ca5ebbaa65789f46d2bf2 with SHA-1 d3a7616aa2 is in history
    
    Change-Id: I2df4e5c6e8d5436d5d42cbb282c316561a6e2d07
    
  - [automerger skipped] Only retain for 64 bit. am: d3a7616aa2 am: ae06453fb8 -s ours am: 90c8527246 -s ours am: 708060b034 -s ours
    
    am skip reason: Change-Id Iaec8276582f880145a1ca5ebbaa65789f46d2bf2 with SHA-1 42ee32379d is in history
    
    Change-Id: I25aaf519d8349b2b9048690e46acc2454d5e5a96
    
  - [automerger skipped] DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp into stag-aosp-master am: 8c0dca2b8c -s ours am: 8fc781e931 am: 379a15b146 am: 9d7ed87c42 -s ours
    
    am skip reason: subject contains skip directive
    
    Change-Id: I7d15c255d7c01d5c9062b6ae0fc92c970338c02e
    
  - Only retain for 64 bit. am: 42ee32379d am: d137d703f1 am: 2890fd07de am: e6a1fb2c87 am: 443236a516
    
    Change-Id: Ibea4d7849633cd0f50cfeef63c1f72032d7c0ae9
    
  - [automerger skipped] DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp@6304901 into stag-aosp-master am: d4ae8e1cd5 -s ours am: 08a8407a05 am: 3c23223d37 am: 87394dbae1 -s ours
    
    am skip reason: subject contains skip directive
    
    Change-Id: I6b53d6be34ff5f0edf85e8c88483b4651a45a57e