Update git submodules
* Update platform/external/drm_hwcomposer from branch 'master'
  to 97b4f2559eb0a7059ac41a8cb257b03ed880a1cd
  - Merge remote-tracking branch 'aosp/upstream-main' into HEAD
    
    Update AOSP to the latest upstream-main branch.
    
    This includes fixes for multiplane formats like NV12,
    as well as lots of cleanups from Roman.
    
    * aosp/upstream-main: (26 commits)
      drm_hwcomposer: Rework UserPropertyBlob to use RAII
      drm_hwcomposer: Move GetPlaneProperty into DrmPlane class
      drm_hwcomposer: Remove unused DrmDisplayCompositor class fields
      drm_hwcomposer: Remove unused {DrmComposition,DrmCompositor}::Dump()
      drm_hwcomposer: Move client flattening closer to the frontend
      drm_hwcomposer: Allow pre-multi layer to always pass DrmPlane validation
      drm_hwcomposer: Improve Mapper@4 metadata API fds index guessing logic
      drm_hwcomposer: Add support for VSYNC_2_4 callback
      drm_hwcomposer: Handle all HWC2 callbacks in DrmHwcTwo.{h,cpp}
      drm_hwcomposer: Move rotation enum querying into DrmPlane initialization
      drm_hwcomposer: Cleanup DrmPlane::Init()
      drm_hwcomposer: DrmPlane: More atomic commit cleanup
      drm_hwcomposer: Remove unused cursor_{x,y}_ and layer_color_ variables
      drm_hwcomposer: Convert transform value at HWC hook call
      drm_hwcomposer: Improve handling of blending mode
      drm_hwcomposer: Query color_encoding and color_range enums during init
      drm_hwcomposer: Create intermediate enum for colorspace and samplerange
      drm_hwcomposer: Move plane-related atomic commit logic to DrmPlane class
      drm_hwcomposer: Move IsKMSDev to DrmDevice
      drm_hwcomposer: Remove unused AvailableWritebackConnector()
      ...
    
    Signed-off-by: John Stultz <john.stultz@linaro.org>
    Change-Id: I6fe0c6887e1927a44cc3cb7c2c32e2195da148d3
    
  - drm_hwcomposer: Rework UserPropertyBlob to use RAII
    
    Makes code simpler and leak-free.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Move GetPlaneProperty into DrmPlane class
    
    In addition move logging to GetPlaneProperty(), which allow to reduce
    number of LoC by ~50 LoC and increase readability.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Remove unused DrmDisplayCompositor class fields
    
    Test: mmma external/drm_hwcomposer
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Remove unused {DrmComposition,DrmCompositor}::Dump()
    
    Both DrmCompositor and DrmComposition have to be reworked to account
    for shared DRM planes, asynchronous atomic commit, dynamic modechange and
    composition reusing between Validate/Present steps.
    
    Current dump logic will be obsolate anyway and keeping/supporting it will
    slow-down reworking process. It make sense to remove it now and create
    from scrach if needed.
    
    Test: mmma external/drm_hwcomposer
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Move client flattening closer to the frontend
    
    Remove unnecessary code from DrmCompositor.
    Drops ~100 LoC.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Allow pre-multi layer to always pass DrmPlane validation
    
    This logic was removed accidentaly during cleanup. Restore it.
    Enables hardware-accelerated composition on raspberry-pi 4.
    
    Fixes: 5063d53ddf7d ("drm_hwcomposer: Improve handling of blending mode")
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Improve Mapper@4 metadata API fds index guessing logic
    
    Unfortunately Mapper@4.0 metadata API doesn't allow to query fd index or
    getting fd another way for every layout plane, therefore users have to
    provide their custom additional metadata API.
    
    We are doing all our best to minimize custom per-platform logic in
    drm_hwcomposer. So it was decided to implement primitive guessing logic,
    allowing users to extend it with out-of-tree code if necessary.
    
    As was reported by John Stultz in [1] our primitive logic has some flaws.
    
    New guessing logic are using inputs from layout data (offsets, sizes),
    and should be more precise.
    
    [1]: https://gitlab.freedesktop.org/drm-hwcomposer/drm-hwcomposer/-/merge_requests/159
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Add support for VSYNC_2_4 callback
    
    Increase composer@2.4 implemented API coverage.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Handle all HWC2 callbacks in DrmHwcTwo.{h,cpp}
    
    Part of frontend isolation activities.
    1. Use HWC2 HAL types only inside DrmHwcTwo.{h,cpp}.
    2. Use single lock for all callbacks.
    3. Communicate with other drm_dwc components using std::function
       without any locking.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Move rotation enum querying into DrmPlane initialization
    
    Benefits:
    1. Improve readability.
    2. Less logic in runtime slightly reduces overhead on CPU.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Cleanup DrmPlane::Init()
    
    Adding enum value into map looks ugly.
    Create a wrapper in order to fix it.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: DrmPlane: More atomic commit cleanup
    
    A few rearrangements to reduce LoC and increase readability.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Remove unused cursor_{x,y}_ and layer_color_ variables
    
    Make it clear that drm_hwcomposer doesn't handle these values.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Convert transform value at HWC hook call
    
    One more step towards "frontend" isolation.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Improve handling of blending mode
    
    1. Convert to DrmHwcBlending inside HWC hook.
    2. Use map for enum_values for cleaner atomic commit preparation.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Query color_encoding and color_range enums during init
    
    Should slightly reduce CPU load at runtime + improve
    atomic commit readability.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Create intermediate enum for colorspace and samplerange
    
    Part of "frontend" isolation activities.
    Also allows to additionally simplify atomic commit.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Move plane-related atomic commit logic to DrmPlane class
    
    Remove unnecessary property getter/setters from DrmPlane class.
    
    As result: Removed ~50 unnecessary LoC. Improved readability.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Move IsKMSDev to DrmDevice
    
    IsKMSDev() is a DRM device helper, therefore DrmDevice class
    is better home for it.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Remove unused AvailableWritebackConnector()
    
    ResourceManager::AvailableWritebackConnector is not used anymore.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Remove unused ResourceManager::gralloc_ field
    
    It was added with initial ResourceManager implementation and was
    never used.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Cleanup DRM atomic commit
    
    Create and use DrmPlane::AtomicSet() wrapper.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Wrap libdrm drmMode*{Get|Free}* into RAII
    
    This should elliminate chance of any leaks in the future.
    Fix drmModePropertyBlobPtr leak in DrmHwcTwo.cpp.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Merge remote-tracking branch 'aosp/upstream-main' into HEAD am: 38163fdedc
    
    Original change: https://android-review.googlesource.com/c/platform/external/drm_hwcomposer/+/1809159
    
    Change-Id: I97b4652389ac4dd30b56e7992431a1cf831e73c7
    
  - drm_hwcomposer: Fix property_get() linux impl.
    
    Bad implementation was found during code surfing.
    At this moment function is used only as a stub for CI.
    
    Signed-off-by: Roman Stratiienko <r.stratiienko@gmail.com>
    
  - drm_hwcomposer: CI: Tune the readability-identifier-naming settings
    
    Copy rules from [1], which is based on Google cpp code-style guide [2]
    
    [1]: https://gist.github.com/airglow923/1fa3bda42f2b193920d7f46ee8345e04
    [2]: https://google.github.io/styleguide/cppguide.html
    
    Signed-off-by: Roman Stratiienko <r.stratiienko@gmail.com>
    
  - drm_hwcomposer: CI: Upgrade clang-* to v12
    
    - Enabling readability-ientifier-naming tidy check does require to specify
    MacroDefinitionIgnoredRegexp key, which is available only in clang-tidy-12.
    
    - Clang-12 isn't available on ubuntu 20.10, therefore upgrade to 21.04.
    
    - "DEBIAN_FRONTEND: noninteractive" is required to prevent ubuntu 21.04
    from hanging, presumably due to waiting for the user input.
    
    - A positive side effect of upgrading to clang-12 is new clang-tidy-12,
    which exposed new issues in the code which is also fixed by this commit,
    e.g:
    
        Failed cppcoreguidelines-narrowing-conversions check with error:
        error: narrowing conversion from 'uint32_t' (aka 'unsigned int') to 'float'
    
    require explicit casting to pass the check, while some of such fails are caused
    by incorrect variable type and fixed by changing the type to correct one.
    
    Signed-off-by: Roman Stratiienko <r.stratiienko@gmail.com>
    
  - Merge remote-tracking branch 'gitlab/main' into HEAD am: 84fa73c0d4 am: 82288efb3a
    
    Original change: https://android-review.googlesource.com/c/platform/external/drm_hwcomposer/+/1714669
    
    Change-Id: If18723bda10941e12869cd0d586bfc7f6acaa69a
    
  - [automerger skipped] Mark ab/7061308 as merged in stage. am: aaaaca8aaa -s ours am: 1b4a72f29e -s ours
    
    am skip reason: Change-Id Ia13ce2304a0527f626ceeb9fee3331b0b3178661 with SHA-1 d92b471251 is in history
    
    Original change: undetermined
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I454fb72e5d01ee217c012f7ba803f89c88fd299b
    
  - [automerger skipped] Mark ab/7061308 as merged in stage. am: aaaaca8aaa -s ours
    
    am skip reason: Change-Id Ia13ce2304a0527f626ceeb9fee3331b0b3178661 with SHA-1 d92b471251 is in history
    
    Original change: undetermined
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I534bef112deb4e48b33a8c22fdc25ddebf0dd92e
    
  - [LSC] Add LOCAL_LICENSE_KINDS to external/drm_hwcomposer am: 86bdae7316 am: c0b3c58483 am: 3eb07de446
    
    Original change: https://android-review.googlesource.com/c/platform/external/drm_hwcomposer/+/1588980
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Ib3c0ed9fe2be3ad979fc95b572100fbaf0ec664b
    
  - [LSC] Add LOCAL_LICENSE_KINDS to external/drm_hwcomposer am: 86bdae7316 am: c0b3c58483
    
    Original change: https://android-review.googlesource.com/c/platform/external/drm_hwcomposer/+/1588980
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I5fbcee7adf7d2cca7c0f2e931d3f12f2f10da748
    
  - Mark ab/6881855 as merged am: b7cd811394 am: d92b471251
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/external/drm_hwcomposer/+/13112091
    
    Change-Id: I5d1ae65684e91de0d6d8050fcee3df7bbcfead47
    
  - Merge remote-tracking branch 'aosp/upstream-main' into HEAD am: c707da598c am: 713247a272 am: b13b51996b am: 42ac17f8bf
    
    Original change: https://android-review.googlesource.com/c/platform/external/drm_hwcomposer/+/1485140
    
    Change-Id: Id8cc6673022e9a990dd6aa46d4117ab7032f93a9
    
  - Merge remote-tracking branch 'aosp/upstream-main' into HEAD am: 8e7afb9d2e am: 30a066b586 am: 709de7f5f7 am: 69da7879e9
    
    Original change: https://android-review.googlesource.com/c/platform/external/drm_hwcomposer/+/1443444
    
    Change-Id: I739296a922f2fba873d833fa9fb3dc59bc53db3b
    
  - [automerger skipped] Skip ab/6749736 in stage. am: e3d29b6be5 -s ours am: 9f1115d2f6 -s ours am: 5435cde9c4 -s ours
    
    am skip reason: Change-Id Id01b079cef39ede789f1f8931a699af8940055da with SHA-1 c7ecb443d4 is in history
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/external/drm_hwcomposer/+/12796944
    
    Change-Id: I20bab95c39226e50b4b58ab962080edc6da48f7d
    
  - Merge remote-tracking branch 'aosp/upstream-main' into HEAD am: 42de64e56d am: 58a4d1f46b am: 2b534bc255 am: 3598c2e2a2 am: 9d9a3bf320
    
    Original change: https://android-review.googlesource.com/c/platform/external/drm_hwcomposer/+/1419031
    
    Change-Id: I4e5f81bad63c6fd6e9a355f316192f8e927af10a
    
  - Merge remote-tracking branch 'aosp/upstream-master' into HEAD am: 37b57553a1 am: 2c43892b3f am: f170f9360c am: c7ecb443d4 am: 48eaaa4813
    
    Original change: https://android-review.googlesource.com/c/platform/external/drm_hwcomposer/+/1355362
    
    Change-Id: I97a0c9229e6600ed5dcf6e9827a9cf709e783926
    
  - Add METADATA to drm_hwcomposer: Apache2=NOTICE am: 21defd5396 am: 696cb269cb am: daac92756b am: 0fb985f9c8 am: 6113fdb381
    
    Change-Id: I2b219456cb25c5ca0edbd325464ad47ac5f50cd9
    
  - [automerger skipped] DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp into stag-aosp-master am: 4248301614 -s ours am: df63680eb1 am: 9f7c222112 am: 35126bfe9c -s ours
    
    am skip reason: subject contains skip directive
    
    Change-Id: Ie3bd51bcaf59f824cf3ee385026ca5339fc03ab8
    
  - [automerger skipped] DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp@6304901 into stag-aosp-master am: 1463cdb95f -s ours am: a5cd8c47d6 am: f55a0b4212 am: b8c29b2bc3 -s ours
    
    am skip reason: subject contains skip directive
    
    Change-Id: Ib5aa59d79a3fc011f9db53475e64097536eb4050
    
  - Merge remote-tracking branch 'aosp/upstream-master' into HEAD am: b4854a24d3 am: dedb1edb34 am: 627ac7265a am: 95d88f7de9 am: 774785749a
    
    Change-Id: Ia0d97574b198d6e1d009ce2a64b5062713465edc
    
  - Update OWNERS am: 39931c49ec am: 9cd565e90e am: 96d368d99b am: 0dbd91e2b7 am: cec91c298c
    
    Change-Id: I682d49e196d15e087386cec99a637c2b502a6e2b