Update git submodules
* Update platform/cts from branch 'master'
  to f37ebcc24374afc6a6f95647462c09914c7cdfa3
  - Merge "SecurityFeaturesTest: stop using undocumented APIs"
  - SecurityFeaturesTest: stop using undocumented APIs
    
    The property ro.debuggable is explicitly not exposed as an API.
    https://android.googlesource.com/platform/frameworks/base/+/50269bef43a2004274abb2b623502cbd85f12525/core/java/android/os/Build.java#1086
    
    The closest approximation to a supported API is the Build.TYPE API, so
    use it instead.
    
    Fixes a bug where android.os.cts.SecurityFeaturesTest#testPrctlDumpable
    fails in instant app mode, because instant apps aren't allowed to
    execute the getprop command. getprop is not a supported Android API.
    
    05-06 12:04:19 I/ModuleListener: [1/1] android.os.cts.SecurityFeaturesTest#testPrctlDumpable fail:
    java.io.IOException: Cannot run program "getprop": error=13, Permission denied
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
        at android.os.cts.BuildTest.getProperty(BuildTest.java:140)
        at android.os.cts.SecurityFeaturesTest.testPrctlDumpable(SecurityFeaturesTest.java:72)
        at java.lang.reflect.Method.invoke(Native Method)
        at junit.framework.TestCase.runTest(TestCase.java:168)
        at junit.framework.TestCase.runBare(TestCase.java:134)
        at junit.framework.TestResult$1.protect(TestResult.java:115)
        at androidx.test.internal.runner.junit3.AndroidTestResult.runProtected(AndroidTestResult.java:73)
        at junit.framework.TestResult.run(TestResult.java:118)
        at androidx.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:51)
        at junit.framework.TestCase.run(TestCase.java:124)
        at androidx.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:62)
        at androidx.test.internal.runner.junit3.AndroidTestSuite$2.run(AndroidTestSuite.java:101)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
    Caused by: java.io.IOException: error=13, Permission denied
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
        at java.lang.ProcessImpl.start(ProcessImpl.java:141)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 17 more
    
    (cherrypicked from commit 38b43c2562c691651df08e68a834a269250423ac)
    
    Bug: 131559495
    Test: cts-tradefed run cts-dev --enable-parameterized-modules --module-parameter INSTANT_APP -m CtsOsTestCases -t android.os.cts.SecurityFeaturesTest#testPrctlDumpable
    Change-Id: I3ed73457d3495bcb94c4ae4a2e6297e0e22618f6
    

* Update platform/superproject from branch 'master'
  to 575903877b818dafcbcf0f042658ac83435bdf61
  - Update git submodules
    
    * Update cts from branch 'master'
      to f37ebcc24374afc6a6f95647462c09914c7cdfa3
      - Merge "SecurityFeaturesTest: stop using undocumented APIs"
      - SecurityFeaturesTest: stop using undocumented APIs
        
        The property ro.debuggable is explicitly not exposed as an API.
        https://android.googlesource.com/platform/frameworks/base/+/50269bef43a2004274abb2b623502cbd85f12525/core/java/android/os/Build.java#1086
        
        The closest approximation to a supported API is the Build.TYPE API, so
        use it instead.
        
        Fixes a bug where android.os.cts.SecurityFeaturesTest#testPrctlDumpable
        fails in instant app mode, because instant apps aren't allowed to
        execute the getprop command. getprop is not a supported Android API.
        
        05-06 12:04:19 I/ModuleListener: [1/1] android.os.cts.SecurityFeaturesTest#testPrctlDumpable fail:
        java.io.IOException: Cannot run program "getprop": error=13, Permission denied
            at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
            at android.os.cts.BuildTest.getProperty(BuildTest.java:140)
            at android.os.cts.SecurityFeaturesTest.testPrctlDumpable(SecurityFeaturesTest.java:72)
            at java.lang.reflect.Method.invoke(Native Method)
            at junit.framework.TestCase.runTest(TestCase.java:168)
            at junit.framework.TestCase.runBare(TestCase.java:134)
            at junit.framework.TestResult$1.protect(TestResult.java:115)
            at androidx.test.internal.runner.junit3.AndroidTestResult.runProtected(AndroidTestResult.java:73)
            at junit.framework.TestResult.run(TestResult.java:118)
            at androidx.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:51)
            at junit.framework.TestCase.run(TestCase.java:124)
            at androidx.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:62)
            at androidx.test.internal.runner.junit3.AndroidTestSuite$2.run(AndroidTestSuite.java:101)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
            at java.lang.Thread.run(Thread.java:919)
        Caused by: java.io.IOException: error=13, Permission denied
            at java.lang.UNIXProcess.forkAndExec(Native Method)
            at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
            at java.lang.ProcessImpl.start(ProcessImpl.java:141)
            at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
            ... 17 more
        
        (cherrypicked from commit 38b43c2562c691651df08e68a834a269250423ac)
        
        Bug: 131559495
        Test: cts-tradefed run cts-dev --enable-parameterized-modules --module-parameter INSTANT_APP -m CtsOsTestCases -t android.os.cts.SecurityFeaturesTest#testPrctlDumpable
        Change-Id: I3ed73457d3495bcb94c4ae4a2e6297e0e22618f6