Update git submodules
* Update platform/external/autotest from branch 'master'
  to 330f1e914d66b3ac6f7f5f0a24b206cb9f729224
  - Revert "deployment: Change deploy workflow to install test image and then install firmware."
    am: 7ccc1bbd8f
    
    Change-Id: I1be2857134f9d0d9f4ec302af86ccc60958c45e0
    
  - Revert "deployment: Change deploy workflow to install test image and then install firmware."
    
    This reverts commit cb6524d9492e592ba0ef6df5472dc5286cbc1c43.
    
    Reason for revert: Breaks autotest_lib.site_utils.deployment.cmdparse_unittest:
    
    FAIL: test_repair_defaults (autotest_lib.site_utils.deployment.cmdparse_unittest._CommandParserTestCase)
    Test argument defaults for `deploy repair`.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/mnt/host/source/src/third_party/autotest/files/site_utils/deployment/cmdparse_unittest.py", line 220, in test_repair_defaults
        self.assertTrue(arguments.install_test_image)
    AssertionError: False is not true
    
    Which breaks all bots in the CQ.
    
    Original change's description:
    > deployment: Change deploy workflow to install test image and then install firmware.
    >
    > BUG=chromium:995451
    > TEST=run deploy locally
    >
    > Change-Id: I94977fa06c6b53f094a435521a801c236efdbed8
    > Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/1841840
    > Reviewed-by: Xixuan Wu <xixuan@chromium.org>
    > Tested-by: Garry Wang <xianuowang@chromium.org>
    > Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
    
    Bug: chromium:995451
    Exempt-From-Owner-Approval: it's the weekend and everything is red!
    Change-Id: I71a82e06d8a30fb929b132ca87c537df5e7e703d
    Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/1869821
    Tested-by: Mike Frysinger <vapier@chromium.org>
    Reviewed-by: Mike Frysinger <vapier@chromium.org>
    

* Update platform/superproject from branch 'master'
  to ca1ad7093b619cde2df351651de3b27eee0b82fd
  - Update git submodules
    
    * Update external/autotest from branch 'master'
      to 330f1e914d66b3ac6f7f5f0a24b206cb9f729224
      - Revert "deployment: Change deploy workflow to install test image and then install firmware."
        am: 7ccc1bbd8f
        
        Change-Id: I1be2857134f9d0d9f4ec302af86ccc60958c45e0
        
      - Revert "deployment: Change deploy workflow to install test image and then install firmware."
        
        This reverts commit cb6524d9492e592ba0ef6df5472dc5286cbc1c43.
        
        Reason for revert: Breaks autotest_lib.site_utils.deployment.cmdparse_unittest:
        
        FAIL: test_repair_defaults (autotest_lib.site_utils.deployment.cmdparse_unittest._CommandParserTestCase)
        Test argument defaults for `deploy repair`.
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "/mnt/host/source/src/third_party/autotest/files/site_utils/deployment/cmdparse_unittest.py", line 220, in test_repair_defaults
            self.assertTrue(arguments.install_test_image)
        AssertionError: False is not true
        
        Which breaks all bots in the CQ.
        
        Original change's description:
        > deployment: Change deploy workflow to install test image and then install firmware.
        >
        > BUG=chromium:995451
        > TEST=run deploy locally
        >
        > Change-Id: I94977fa06c6b53f094a435521a801c236efdbed8
        > Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/1841840
        > Reviewed-by: Xixuan Wu <xixuan@chromium.org>
        > Tested-by: Garry Wang <xianuowang@chromium.org>
        > Legacy-Commit-Queue: Commit Bot <commit-bot@chromium.org>
        
        Bug: chromium:995451
        Exempt-From-Owner-Approval: it's the weekend and everything is red!
        Change-Id: I71a82e06d8a30fb929b132ca87c537df5e7e703d
        Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/1869821
        Tested-by: Mike Frysinger <vapier@chromium.org>
        Reviewed-by: Mike Frysinger <vapier@chromium.org>