Update git submodules
* Update device/google/cuttlefish from branch 'master'
  to f4d16ad599669a5c249c8e0c9659f18138508531
  - Merge changes I2ad89bee,I26e3b310,I5062230f,I0a169826,I13e2f74a
    
    * changes:
      Fake out KeymasterContext::GenerateAttestation.
      Implement KeymasterContext::UpgradeKeyBlob with a TPM.
      Set a hardware property to convince Android 3DES is present
      Attach the key origin to the hw_enforced property set.
      Fix bug with hmac calculations on long strings.
    
  - Fake out KeymasterContext::GenerateAttestation.
    
    Implementation that signs the certificate with a TPM-resident key is
    still TODO.
    
    Still fails a CTS test with:
    STACKTRACE:
    java.lang.Exception: Failed on curve 0 challenge 0 purpose 0 includeValidityDates true and devicePropertiesAttestation true
            at android.keystore.cts.KeyAttestationTest.testEcAttestation(KeyAttestationTest.java:181)
    ...
    Caused by: java.lang.AssertionError: Attestations must not contain any extra data
    Expected: is an empty collection
         but: <[2.5.29.35, 2.5.29.15]>
            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
            at android.keystore.cts.KeyAttestationTest.checkUnexpectedOids(KeyAttestationTest.java:711)
    
    This looks like it is another instance of b/158212234 and b/149746301.
    
    Bug: 155695501
    Test: Treehugger
    Change-Id: I2ad89beeae8ede46d31b3591d22bef4e5a732def
    
  - Implement KeymasterContext::UpgradeKeyBlob with a TPM.
    
    Bug: 155695501
    Test: Treehugger
    Change-Id: I26e3b310e798296773823de90e461c404042d5af
    
  - Set a hardware property to convince Android 3DES is present
    
    https://cs.android.com/android/platform/superproject/+/master:frameworks/base/keystore/java/android/security/keystore/AndroidKeyStoreProvider.java;l=74;drc=master
    
    Bug: 155695501
    Test: atest CtsKeystoreTestCases
    Change-Id: I5062230f7288ddee7380e15bdb547a3ea188ab9f
    
  - Attach the key origin to the hw_enforced property set.
    
    Bug: 155695501
    Test: atest CtsKeystoreTestCases
    Change-Id: I0a169826fe7d8b4a0ffc39b1de78609825cced87
    
  - Fix bug with hmac calculations on long strings.
    
    Bug: 155695501
    Test: atest CtsKeystoreTestCases
    Change-Id: I13e2f74a27d486f9353c15aa6c7ae6b2e1766e36
    

* Update platform/superproject from branch 'master'
  to 0d7beaccc452e355ee108e61ff3460f38051d896
  - Update git submodules
    
    * Update device/google/cuttlefish from branch 'master'
      to f4d16ad599669a5c249c8e0c9659f18138508531
      - Merge changes I2ad89bee,I26e3b310,I5062230f,I0a169826,I13e2f74a
        
        * changes:
          Fake out KeymasterContext::GenerateAttestation.
          Implement KeymasterContext::UpgradeKeyBlob with a TPM.
          Set a hardware property to convince Android 3DES is present
          Attach the key origin to the hw_enforced property set.
          Fix bug with hmac calculations on long strings.
        
      - Fake out KeymasterContext::GenerateAttestation.
        
        Implementation that signs the certificate with a TPM-resident key is
        still TODO.
        
        Still fails a CTS test with:
        STACKTRACE:
        java.lang.Exception: Failed on curve 0 challenge 0 purpose 0 includeValidityDates true and devicePropertiesAttestation true
                at android.keystore.cts.KeyAttestationTest.testEcAttestation(KeyAttestationTest.java:181)
        ...
        Caused by: java.lang.AssertionError: Attestations must not contain any extra data
        Expected: is an empty collection
             but: <[2.5.29.35, 2.5.29.15]>
                at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
                at android.keystore.cts.KeyAttestationTest.checkUnexpectedOids(KeyAttestationTest.java:711)
        
        This looks like it is another instance of b/158212234 and b/149746301.
        
        Bug: 155695501
        Test: Treehugger
        Change-Id: I2ad89beeae8ede46d31b3591d22bef4e5a732def
        
      - Implement KeymasterContext::UpgradeKeyBlob with a TPM.
        
        Bug: 155695501
        Test: Treehugger
        Change-Id: I26e3b310e798296773823de90e461c404042d5af
        
      - Set a hardware property to convince Android 3DES is present
        
        https://cs.android.com/android/platform/superproject/+/master:frameworks/base/keystore/java/android/security/keystore/AndroidKeyStoreProvider.java;l=74;drc=master
        
        Bug: 155695501
        Test: atest CtsKeystoreTestCases
        Change-Id: I5062230f7288ddee7380e15bdb547a3ea188ab9f
        
      - Attach the key origin to the hw_enforced property set.
        
        Bug: 155695501
        Test: atest CtsKeystoreTestCases
        Change-Id: I0a169826fe7d8b4a0ffc39b1de78609825cced87
        
      - Fix bug with hmac calculations on long strings.
        
        Bug: 155695501
        Test: atest CtsKeystoreTestCases
        Change-Id: I13e2f74a27d486f9353c15aa6c7ae6b2e1766e36