Update git submodules
* Update platform/packages/apps/Bluetooth from branch 'master'
  to 94dd6410f9b16640bf87b7331bb5d51163558015
  - Merge "A2dp: Check the value of mConnectionState in isConnected"
  - A2dp: Check the value of mConnectionState in isConnected
    
    * There could be potential critical timing to cause
    java.lang.ArrayIndexOutOfBoundsException: index=-1, when a2dp state machine
    exit one state to enter another state. at this timing, the mStateStackTopIndex
    value of mStateStack be set to -1.
    * Checking mConnectionState value which maintained in A2dpStateMachine to avoid
    this AndroidRuntime exception.
    
    Bug: 142217033
    Test: Enable Bluetooth -> Connect Bluetooth headset -> Disconnect
    Bluetooth headset -> Disable Bluetooth then check a2dp state machine log.
    Change-Id: Ifdd3e96b84496cef04a70d95b5b64eca81e5db9c
    

* Update platform/superproject from branch 'master'
  to acc3a7a461f4b819e5dcd75460a73671bd07ff89
  - Update git submodules
    
    * Update packages/apps/Bluetooth from branch 'master'
      to 94dd6410f9b16640bf87b7331bb5d51163558015
      - Merge "A2dp: Check the value of mConnectionState in isConnected"
      - A2dp: Check the value of mConnectionState in isConnected
        
        * There could be potential critical timing to cause
        java.lang.ArrayIndexOutOfBoundsException: index=-1, when a2dp state machine
        exit one state to enter another state. at this timing, the mStateStackTopIndex
        value of mStateStack be set to -1.
        * Checking mConnectionState value which maintained in A2dpStateMachine to avoid
        this AndroidRuntime exception.
        
        Bug: 142217033
        Test: Enable Bluetooth -> Connect Bluetooth headset -> Disconnect
        Bluetooth headset -> Disable Bluetooth then check a2dp state machine log.
        Change-Id: Ifdd3e96b84496cef04a70d95b5b64eca81e5db9c