Update git submodules
* Update platform/superproject from branch 'master'
  to ec641274777837d0d66a9955bdfdc4655dbc15a1
  - Update git submodules
    
    * Update system/tools/hidl from branch 'master'
      to 277c270d2b779729d1da0f7764059943a5514c4d
      - Add 'while importing X at Y' error chains.
        
        So that you can see where exactly things go wrong during an import
        chain. This is especially useful when something complicated goes wrong
        inside of an import.
        
        For instance:
        ERROR: must import type, but importing value: test.import_identifier@1.0::types:Foo
        while importing test.import_identifier@1.0::types:Foo at system/tools/hidl/test/error_test/import_identifier/1.0/IFoo.hal:19.8-44.
        
        Bug: N/A
        Test: manual
        Change-Id: Ifd1baa7a7405e74c2ba6c4b65944110a77069bda
        

* Update platform/system/tools/hidl from branch 'master'
  to 277c270d2b779729d1da0f7764059943a5514c4d
  - Add 'while importing X at Y' error chains.
    
    So that you can see where exactly things go wrong during an import
    chain. This is especially useful when something complicated goes wrong
    inside of an import.
    
    For instance:
    ERROR: must import type, but importing value: test.import_identifier@1.0::types:Foo
    while importing test.import_identifier@1.0::types:Foo at system/tools/hidl/test/error_test/import_identifier/1.0/IFoo.hal:19.8-44.
    
    Bug: N/A
    Test: manual
    Change-Id: Ifd1baa7a7405e74c2ba6c4b65944110a77069bda