Update git submodules
* Update platform/packages/services/Telecomm from branch 'master'
  to 6cca360b192c8da3b8d8ff064c50d6528ad48c1a
  - Merge changes I81d13f2c,Ic2773277
    
    * changes:
      BluetoothLeAudio: Fix missing group id for device.
      BluetoothLeAudio: Return early from getLeAudioConnectedDevices
    
  - BluetoothLeAudio: Fix missing group id for device.
    
    Telecom has registered callbacks for BluetoothLeAudio and in this way it
    tracs devices being added/removed to/from group.
    However, it could happen that callback is registered after device has
    been added to the group. In such a case, Telecom will not be aware about
    the group for the device. This patch fixes it.
    
    Issue was visible when LeAudio device is already bonded and Bluetooth is
    enabled.
    
    Bug: 150670922
    Bug: 227562754
    Test: atest TelecomUnitTests
    
    Change-Id: I81d13f2c629eb774cc277692da9e9f1bb31a0779
    
  - BluetoothLeAudio: Return early from getLeAudioConnectedDevices
    
    If LeAudio is not supported or there is no known groups, function can
    return early.
    
    It also fixes flake testLeAudioServiceDisconnect() test:
    
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.bluetooth.BluetoothDevice android.bluetooth.BluetoothLeAudio.getConnectedGroupLeadDevice(int)' on a null object reference
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.bluetooth.BluetoothDevice android.bluetooth.BluetoothLeAudio.getConnectedGroupLeadDevice(int)' on a null object reference
    	at com.android.server.telecom.bluetooth.BluetoothDeviceManager.getLeAudioConnectedDevices(BluetoothDeviceManager.java:219)
    	at com.android.server.telecom.bluetooth.BluetoothDeviceManager.getNumConnectedDevices(BluetoothDeviceManager.java:232)
    	at com.android.server.telecom.tests.BluetoothDeviceManagerTest.testLeAudioServiceDisconnect(BluetoothDeviceManagerTest.java:299)
    
    Bug: 150670922
    Test: atest TelecomUnitTest
    Change-Id: Ic27732771a7e87d5b5a87584f50996cf3fd97b48