Update git submodules
* Update platform/superproject from branch 'master'
  to dde1a5ef97edf91b9bc6812700b549edbd22dad3
  - Update git submodules
    
    * Update system/core from branch 'master'
      to 37b0d41faf5380e045a4c08acb94a498aac8e453
      - Merge "Fix an issue with C-compatibility due to a missing tag name"
      - Fix an issue with C-compatibility due to a missing tag name
        
        system/core/libpixelflinger/include/pixelflinger/format.h:85:15: error: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Werror,-Wnon-c-typedef-for-linkage]
        typedef struct {
                      ^
                      GGLFormat
        system/core/libpixelflinger/include/pixelflinger/format.h:98:5: note: type is not C-compatible due to this member declaration
             inline uint32_t mask(int i) const {
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        system/core/libpixelflinger/include/pixelflinger/format.h:124:3: note: type is given name 'GGLFormat' for linkage purposes by this typedef declaration
        } GGLFormat;
          ^
        
        Bug: http://b/155835175
        Test: m with aosp_blueline
        Change-Id: I2819427e2c9e885f7b66527d5268987e8cc73f31
        Merged-In: I73b95ff1d6d17af512ce2226b6324e5da0343c39
        

* Update platform/system/core from branch 'master'
  to 37b0d41faf5380e045a4c08acb94a498aac8e453
  - Merge "Fix an issue with C-compatibility due to a missing tag name"
  - Fix an issue with C-compatibility due to a missing tag name
    
    system/core/libpixelflinger/include/pixelflinger/format.h:85:15: error: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Werror,-Wnon-c-typedef-for-linkage]
    typedef struct {
                  ^
                  GGLFormat
    system/core/libpixelflinger/include/pixelflinger/format.h:98:5: note: type is not C-compatible due to this member declaration
         inline uint32_t mask(int i) const {
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    system/core/libpixelflinger/include/pixelflinger/format.h:124:3: note: type is given name 'GGLFormat' for linkage purposes by this typedef declaration
    } GGLFormat;
      ^
    
    Bug: http://b/155835175
    Test: m with aosp_blueline
    Change-Id: I2819427e2c9e885f7b66527d5268987e8cc73f31
    Merged-In: I73b95ff1d6d17af512ce2226b6324e5da0343c39