Update git submodules
* Update platform/packages/modules/DnsResolver from branch 'master'
  to bc7d6c0a2030ec19db7f7a8b98e8ee0c65c7ecb5
  - Sanitize buffer alignment macros
    
    The ancient ALIGN() macros caused clang-tidy to complain:
    
    packages/modules/DnsResolver/gethnamaddr.cpp:367:10: error: integer to
    pointer cast pessimizes optimization opportunities
    [performance-no-int-to-ptr,-warnings-as-errors]
        bp = (char*) ALIGN(bp);
    
    The new inline template align_ptr() sidesteps this issue as recommended
    by the clang-tidy documentation:
      https://clang.llvm.org/extra/clang-tidy/checks/performance-no-int-to-ptr.html
    
    Furthermore, align_ptr() is used to replace this... surprising
    piece of code:
    
        bp += sizeof(align) - (size_t)((uintptr_t)bp % sizeof(align));
    
    See the bug there? When bp is already aligned to a multiple of
    sizeof(align), it will overalign! Also, 'align' was a union of a
    uint32_t and a char, which is obviously the same alignment of a plain
    uint32_t on any architecture ever created!
    
    Bug: 182416023
    Change-Id: Id39c3030025e4510feeb55723760a2950067cece
    
  - Merge changes Id2a5945b,I4ef63f3f am: 119280eedf
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1737422
    
    Change-Id: I8a14689ac6b8cda9f2f63d8f5a8d740956bd1d50
    
  - Merge "Rename nssocks to udpsocks" am: 57ff72e8ce
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1737419
    
    Change-Id: Iacc3a6b5ae3dc5220420b8cce7ec4928a2f5991f
    
  - Fix a bug in DoT probe am: 91be321dc9
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1737424
    
    Change-Id: Id5e2450cb16801e05a39eb1dcba60a902fb12775
    
  - Fix TlsServerRevalidation flaky am: c16f2545af
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1737639
    
    Change-Id: I4cf705e4d05022398677d22e02dd540cd4e693a9
    
  - Revert "Revert "Implement DNS probe in DoT validation"" am: bb22c7cace
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1737638
    
    Change-Id: I6b5d2aa8117ac32718061226b6aa568e9dab2140
    
  - Revert "Implement DNS probe in DoT validation" am: d65a6bda85
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1737048
    
    Change-Id: Ifbbe48afc0a16f58c67fc460592247939755dd6b
    
  - Implement DNS probe in DoT validation am: c47e5d7084
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1733919
    
    Change-Id: I6efd992da5f1522b48f84b273a15ff145c9b91a1
    
  - Merge "Revert "Support evaluating private DNS by latency"" am: d1b3b80399
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1733918
    
    Change-Id: Id614b62cd65078a6f549a7fc590a60f00e35f6cc
    
  - DO NOT MERGE - Merge ab/7272582 am: 9d08a4f762
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1736136
    
    Change-Id: I18351a55d9603fa586556a2a3547049f5dfd1111
    
  - Revert "Set maximum attempt for opportunistic mode private DNS validation" am: 7135fbfcbd
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1733917
    
    Change-Id: I6097f69cc60b39a3c03ab250e99d48af14e04974
    
  - Clean up DnsTlsDispatcher when a network is disconnected am: e0086c0fee
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1722073
    
    Change-Id: I696bcfdcc893769c322f3ef48430a16061c17f1e
    
  - Merge "Set maximum attempt for opportunistic mode private DNS validation" am: b977d1ac2f
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1723079
    
    Change-Id: I092180462b730893ce0677600266156f43432a84
    
  - Merge "Support evaluating private DNS by latency" am: b8b2793943
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1708172
    
    Change-Id: Ie40665102ca0bd0e91d080ec33bb931d5f5da96c
    
  - Add tethering to resolver AIDL apex_available am: fb492079b3
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1657882
    
    Change-Id: I8e8ccb439bcd6054b0a6ea0735eab7ec7de4c5ac
    
  - Merge "Add one more Revalidation unit test" am: 8d636aebd5
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1708171
    
    Change-Id: Icecce98381bc620c1ad51574fe0191b8d920be89
    
  - Merge "Add getAverageLatencyMs in DnsStats" am: 830589a0fc
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1708170
    
    Change-Id: Ia8cd77d6ecb5549ba47acc554fcba7ba215af250
    
  - Merge "Exclude the latency in DnsStats if it is relevant to EPERM" am: 0a61733e87
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1708169
    
    Change-Id: I159b3c9663a15fe7d43f84ed6ec283c8928aed2d
    
  - Make doh_unit_test and doh_ffi_test can be run on the R platfrom am: 5e60de17c4
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1711569
    
    Change-Id: Id47395305c8bb19a62d510bc5e9d6647eb9fd0a6
    
  - Merge "Add min_sdk_version to DnsResolver tests" am: f6526c49cb
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1711570
    
    Change-Id: Idba26f435739a4163f459f5f9856f35d163e8b95
    
  - Fix doh flaky test am: 6ac664e70e
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1711568
    
    Change-Id: Ic7c7c68d2336357381bedf259804cdc5c31a8b4a
    
  - Apply IPrivateDnsServer to PrivateDnsConfiguration am: cf56d23d1f
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1690509
    
    Change-Id: I65f3d636e04ecdbb0ebfbba3edc07dfc975bd5b4
    
  - Introduce IPrivateDnsServer am: 690b19fad9
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1600841
    
    Change-Id: Ic625b84481a8b8e7af31ed5d80f76b73ee4fac4b
    
  - Change most of PrivateDnsConfiguration methods to use ServerIdentity am: ad96ef83d3
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1600840
    
    Change-Id: I7eb1044c7e0271ed8facbe530f80c4569f8dfb75
    
  - Merge "Add PRODO_DOH in enum Protocol." am: 05bf348e44
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1696986
    
    Change-Id: Id218241d08dc9f4c7849dde8348e7cf53c5345f2
    
  - Remove dead code in PrivateDnsConfiguration am: 1f663fc281
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1600838
    
    Change-Id: I72fc845a5fd6276a6e60c37185842189107f749e
    
  - Change ServerIdentity to store IPSockAddr instead of IPAddress am: 453b5e4ef4
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1600837
    
    Change-Id: I62f2505f13be2b796cbe3cdc913c5d556fdffb51
    
  - Support DoT query timeout am: 08b2f2b72e
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1533160
    
    Change-Id: I4ac5e3f5f367fae0aa443f918779e8a836d6e2c3
    
  - Merge "Use libgtest_prod_headers." am: 58544e2472
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1687091
    
    Change-Id: I1192ac96d3fab6c2b5868582ba58b9a8d1ab55e2
    
  - Retry binding sockets in DNSResponder if errno is EADDRNOTAVAIL am: db04a2bd0a
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1688185
    
    Change-Id: Icdbbe469015773dece7cee40be5f80ecbc74ed99
    
  - Implement DoT revalidation am: 82ae84b949
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1516273
    
    Change-Id: Ie9ccf4cfbeffcfd69ec08af9ea8d106e4ecd1deb
    
  - Merge "Add more unit test for doh" am: 9310ca2278
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1676245
    
    Change-Id: Idf0a7f695c877bc5818ab5fc81133d35a38925dc
    
  - Update the default sampling flag of DNS resolver metrics events am: 1289a07cf9
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1669637
    
    Change-Id: Id53cc457bf80bac00f405d4870b2fde28eebbfa8
    
  - Merge "Fix the unexpected getaddrinfo error code changing due to parallel lookup" am: 8f58a580d8
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1673193
    
    Change-Id: I917d50414c4f0dc8102160dbc8931ea07740c01a
    
  - Add doh_unit_test target am: d587028223
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1669634
    
    Change-Id: Ic6b6c1d55ef7747cc7fb6fcfd24caba165de1e87