Update git submodules
* Update platform/external/drm_hwcomposer from branch 'master'
  to bc74646e908624b7a4029102dd950cbbb0e9c058
  - Merge "drm_hwcomposer: Merge remote-tracking branch 'aosp/upstream-main' into HEAD"
  - drm_hwcomposer: Merge remote-tracking branch 'aosp/upstream-main' into HEAD
    
    Sync AOSP's drm_hwcomposer branch to the upstream main branch.
    
    This includes a number of fixes and cleanups from
    Roman Stratiienko as well as fixes from Mauro Rossi.
    
    * aosp/upstream-main:
      drm_hwcomposer: Rework HwcDisplay disposal to avoid races
      drm_hwcomposer: Add test utility to listen for uevents
      drm_hwcomposer: Define DRM_FORMAT_XYUV8888 if missing
      drm_hwcomposer: fix sign-compare building error in uevent listener
      drm_hwcomposer: build with -std=c++17 cppflag
      drm_hwcomposer: Rename DrmDisplayCompositor->DrmAtomicStateManager
      drm_hwcomposer: Remove AtomicCommitArgs::clear_active_composition field
      drm_hwcomposer: Remove RCAR-DU specific code.
      drm_hwcomposer: Rework KMS composition planner + plane sharing support
      drm_hwcomposer: Implement SetActiveConfigWithConstraints
      drm_hwcomposer: Use single VSyncWorker per display
      drm_hwcomposer: Dynamic DrmDisplayPipeline to HwcDisplay bindings
      drm_hwcomposer: Initialize HwcDisplay using DrmDisplayPIpeline
      drm_hwcomposer: Fix PipelineBindable::BindPipeline
      drm_hwcomposer: Introduce DrmDisplayPipeline class
      drm_hwcomposer: Tidy-up DrmDevice class
      drm_hwcomposer: Tidy-up DrmConnector class
      drm_hwcomposer: Tidy-up DrmEncoder class
      drm_hwcomposer: Tidy-up DrmCrtc class
      drm_hwcomposer: Remove ability to prioritize primary display
      drm_hwcomposer: Handle primary display in GetDisplayConnectionType()
      drm_hwcomposer: Tidy-up DrmPlane class
      drm_hwcomposer: Simplify DrmHwcTwo::GetDisplay()
      drm_hwcomposer: Fix build_deploy.sh script
    
    Signed-off-by: John Stultz <john.stultz@linaro.org>
    Change-Id: Iba91e67371f4f1fc0a8cccf2ee97373898a5d195
    
  - drm_hwcomposer: Rework HwcDisplay disposal to avoid races
    
    The code prior to this commit has a flaw:
    
        HwcDisplay::~HwcDisplay() {
          ...
          auto &main_lock = hwc2_->GetResMan().GetMainLock();
          /* Unlock to allow pending vsync callbacks to finish */
          main_lock.unlock();
    
    At this point display is no longer in displays_[] list. After
    lock is released, hwc2 API thread starts to process transactions
    which may fail with BAD_SIAPLAY responce and cause SF to crash.
    
          vsync_worker_.VSyncControl(false);
          vsync_worker_.Exit();
          main_lock.lock();
        }
    
    1. Rework the logic in order to avoid such scenariuos:
    1.a. Temporary switch non-primary unplugged displays to headless state
         allowing remaining transactions to succeed without impacting the
         pipeline.
    1.b. Give 100mSec delay before destroying / removing display from the
         displays_[] list to allow all pending hwc2 transactions to complete.
    
    2. Support hotswap of the DrmDisplayPipeline, which makes primary display
       reattaching process smoother.
       Now SF should be able to gracefully remove all layers.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Add test utility to listen for uevents
    
    Dumping uevents is useful for debugging purposes.
    
    1. Extract logic related to uevent socket into utils/UEvent.h class.
    2. Use it by both UEventListener.cpp and tests/uevent_print.cpp.
    
    Bump clang-tidy level of UEventListener.cpp to normal.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Define DRM_FORMAT_XYUV8888 if missing
    
    Fixes drm_hwcomposer build for Android-9.
    
    Signed-off-by: Roman Stratiienko <r.stratiienko@gmail.com>
    Change-Id: I14e931c37c3d09284dfd338e6482a27cf21e0e10
    
  - drm_hwcomposer: fix sign-compare building error in uevent listener
    
    d26619b5 ("drm_hwcomposer: CI: Upgrade clang-* to v12") declared 'ret' as ssize_t
    but after commit 1e053b4e ("drm_hwcomposer: Make uevent listener standalone")
    drm/UEventListener.cpp is affected by the following builing error:
    
    external/drm_hwcomposer/drm/UEventListener.cpp:82:28:
    error: comparison of integers of different signs: 'uint32_t' (aka 'unsigned int') and 'ssize_t' (aka 'int') [-Werror,-Wsign-compare]
        for (uint32_t i = 0; i < ret;) {
                             ~ ^ ~~~
    1 error generated.
    
    Fixes: 1e053b4e ("drm_hwcomposer: Make uevent listener standalone")
    Signed-off-by: Mauro Rossi <issor.oruam@gmail.com>
    [RomanS: Fixed CI nitpicks]
    Signed-off-by: Roman Stratiienko <r.stratiienko@gmail.com>
    Change-Id: Ia97d9019c21ac68be386a627cb101f6e423bbfc7
    
  - drm_hwcomposer: build with -std=c++17 cppflag
    
    Fixes the following building error:
    
    external/drm_hwcomposer/DrmHwcTwo.cpp:985:14: error: decomposition declarations are a C++17 extension [-Werror,-Wc++17-extensions]
      for (auto &[handle, layer] : layers_) {
                 ^~~~~~~~~~~~~~~
    1 error generated.
    
    Signed-off-by: Mauro Rossi <issor.oruam@gmail.com>
    Signed-off-by: Roman Stratiienko <r.stratiienko@gmail.com>
    Change-Id: I236f16969e4500ff2efb79c06500bc4d3a3d810c
    
  - Empty merge of sc-v2-dev-plus-aosp-without-vendor@8084891
    
    Bug: 214455710
    Merged-In: I95601c680ca1af0dc9d3b3f102f79f77af081b75
    Change-Id: I96baa183ce57edeab2e627dbe9bfe061db37eb77
    
  - drm_hwcomposer: Rename DrmDisplayCompositor->DrmAtomicStateManager
    
    Primary responsibilities of this class are:
    
    1. Send composition/mode/active state over DRM atomic commit IOCTL
       to the kernel
    2. Track commit state and keep planes owned by the Pipeline while they
       are either displayed or staged for displaying.
    3. Keep framebuffers alive while they are in use or staged.
    
    Not much related to composition itself, therefore rename it to
    DrmAtomicStateManager and move it to drm folder.
    
    Bump clang-tidy level of DrmAtomicStateManager.c to normal by fixing
    minor clang-tidy findings.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Remove AtomicCommitArgs::clear_active_composition field
    
    Now we can use empty DrmKmsPlan to achieve the same goal.
    
    + Remove unused HwcDisplay::ClearDisplay()
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Remove RCAR-DU specific code.
    
    We are not testing it for more than year, therefore it's better
    to use generic logic for 'rcar-du' instead.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Rework KMS composition planner + plane sharing support
    
    Rewrite Layer-to-Plane planner. Get rid of ~200 redundant lines of code
    + added plane sharing functionality.
    
    Closes: https://gitlab.freedesktop.org/drm-hwcomposer/drm-hwcomposer/-/issues/11
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Implement SetActiveConfigWithConstraints
    
    Enough to get 100% passes in Composer 2.4 VTS.
    Some SOCs require a VTS fix to pass [1]
    
    [1]: https://android-review.googlesource.com/c/platform/hardware/interfaces/+/1954544
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Use single VSyncWorker per display
    
    Composer 2.4 will require another vsyncworker callback to send
    VsyncPeriodTimingChanged event. It makes sence to use single
    VSyncWorker and flags to indicate which actions are required
    to perform. This should also save some runtime resources.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Dynamic DrmDisplayPipeline to HwcDisplay bindings
    
    The following use scenarios are now possible:
    
    1. When no display connected, primary HwcDisplay is created in headless
       mode.
    
    2. When user connects first display, it binds to primary slot, replacing
       headless HwcDisplay.
    
    3. When user connects another display it binds to the new HwcDisplay
       slot, creating new display for the framework.
    
    4. When user disconnects first (Primary) display, drm_hwc detaches
       second display and attaches it to the Primary slot. In this case
       framework is notified as Primary display resolution updated
       (Plugged->Plugged transition). And second display is disconnected
       (Plugged->Unplugged transition).
    
    DrmDisplayPipeline is now created on demand (after hotplug event).
    
    HwcDisplay class is now destructed on connector unplug, which will give
    us ability to destroy any resource caches (will be required for FB
    caching logic).
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Initialize HwcDisplay using DrmDisplayPIpeline
    
    HwcDisplay can now take all necessary objects from DrmDisplayPipeline.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Fix PipelineBindable::BindPipeline
    
    We should assign weak pointer object to really take ownership.
    
    Fixes: cad8e0ca57c2 ("drm_hwcomposer: Introduce DrmDisplayPipeline class")
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Introduce DrmDisplayPipeline class
    
    Create systematic way of binding DRM objects (Crtc,Encoder,Planes...)
    to the pipeline using RAII. Use it to create the pipeline.
    
    + Allow pipeline creation to fail.
    
    Closes: https://gitlab.freedesktop.org/drm-hwcomposer/drm-hwcomposer/-/issues/14
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Tidy-up DrmDevice class
    
    1. Move drm/DrmConnector.h to Normal clang-tidy checks list by fixing
       clang-tidy findings.
    
    2. Remove DrmDevice self-reference.
    
    3. Replace shared_ptr reference to DrmDevice in DrmFbImporter with a
       pointer, making ResourceManager only owner of DrmDevice and its
       chilren.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Tidy-up DrmConnector class
    
    Implement DrmConnector instantiation through CreateInstance() static method,
    which helps to reduce complexity of DrmDevice::Init() function.
    
    Move Connector-to-CRTC binding information to the DrmDevice class.
    
    Move drm/DrmConnector.h to Normal clang-tidy checks list by fixing
    clang-tidy findings.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Tidy-up DrmEncoder class
    
    Implement DrmEncoder instantiation through CreateInstance() static method,
    which helps to reduce complexity of DrmDevice::Init() function.
    
    Move Encoder-to-CRTC binding information to the DrmDevice class.
    
    Move drm/DrmEncoder.h to Normal clang-tidy checks list by fixing
    clang-tidy findings.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Tidy-up DrmCrtc class
    
    Implement DrmCrtc instantiation through CreateInstance() static method,
    which helps to reduce complexity of DrmDevice::Init() function.
    
    Move CRTC-to-Display binding information to the DrmDevice class.
    
    Move drm/DrmCrtc.h to Normal clang-tidy checks list by fixing
    clang-tidy findings.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Remove ability to prioritize primary display
    
    This feature isn't correctly fits hwc2 and SF requirements.
    
    Primary display prioritization shall be done by introducing ability to
    override internal/external connector type for any connector.
    
    'vendor.hwc.drm.primary_display_order' property is no longer relevant.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Handle primary display in GetDisplayConnectionType()
    
    Primary display should always be internal.
    
    Closes: https://gitlab.freedesktop.org/drm-hwcomposer/drm-hwcomposer/-/issues/58
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Tidy-up DrmPlane class
    
    This allow to throw away few lines from DrmDevice::Init() making it less
    complicated.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Simplify DrmHwcTwo::GetDisplay()
    
    Cosmetic change: make GetDisplay() non-static class method + use
    deduced return type.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - drm_hwcomposer: Fix build_deploy.sh script
    
    Composer service has to be started again.
    
    Signed-off-by: Roman Stratiienko <roman.o.stratiienko@globallogic.com>
    
  - Merge remote-tracking branch 'aosp/upstream-main' into 'aosp/master' am: e6295d18ec
    
    Original change: https://android-review.googlesource.com/c/platform/external/drm_hwcomposer/+/1960322
    
    Change-Id: I0e856981f1fcd3068af68015c9cd20350f011166
    
  - Merge "drm_hwcomposer: Merge remote-tracking branch 'aosp/upstream-main' into HEAD" am: 6ca311696d
    
    Original change: https://android-review.googlesource.com/c/platform/external/drm_hwcomposer/+/1949446
    
    Change-Id: I312356facb8fac168d1af22615c3c56877470fa9
    
  - Update OWNERS am: 6635fd594d
    
    Original change: https://android-review.googlesource.com/c/platform/external/drm_hwcomposer/+/1956416
    
    Change-Id: I81ac59cb0b4ea550583ea2eb36ba7143b38173c3
    
  - drm_hwcomposer: Merge remote-tracking branch 'aosp/upstream-main' into HEAD am: 774e5e3432 am: 24ccb88ece am: 42f5da5192
    
    Original change: https://android-review.googlesource.com/c/platform/external/drm_hwcomposer/+/1921343
    
    Change-Id: Iae3684f162cd9e86a0feca58480a2dbcf3f450fe
    
  - drm_hwcomposer: Merge remote-tracking branch 'aosp/upstream-main' into HEAD am: 774e5e3432 am: 24ccb88ece
    
    Original change: https://android-review.googlesource.com/c/platform/external/drm_hwcomposer/+/1921343
    
    Change-Id: Ie06bd7b625f697ffea49621c3c41109b04cf36ad
    
  - drm_hwcomposer: Merge remote-tracking branch 'aosp/upstream-main' into HEAD am: 774e5e3432
    
    Original change: https://android-review.googlesource.com/c/platform/external/drm_hwcomposer/+/1921343
    
    Change-Id: I8167d2b1b7c43605a7fd313faa140fdb45a4e451
    
  - [automerger skipped] Merge sc-qpr1-dev-plus-aosp-without-vendor@7810918 am: ac850066c3 -s ours am: 163d99edee -s ours
    
    am skip reason: Merged-In I302491d47346aa48eebcac6498991fda95f62b58 with SHA-1 a976c15a02 is already in history
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/external/drm_hwcomposer/+/16277420
    
    Change-Id: I4a4122441b474e2f8afd3d117eb1fe1541879559
    
  - [automerger skipped] Merge sc-qpr1-dev-plus-aosp-without-vendor@7810918 am: ac850066c3 -s ours
    
    am skip reason: Merged-In I302491d47346aa48eebcac6498991fda95f62b58 with SHA-1 a976c15a02 is already in history
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/external/drm_hwcomposer/+/16277420
    
    Change-Id: Ia865f24177898cfaffaff1d22fb4185f465c6fba
    
  - Merge remote-tracking branch 'aosp/upstream-main' into HEAD am: 97b4f2559e am: 6e792d7aa5 am: fc030f53a5 am: b038ca0b70
    
    Original change: https://android-review.googlesource.com/c/platform/external/drm_hwcomposer/+/1883310
    
    Change-Id: I158aeece6bbfc33e681f5b8f1fa7df05d11e4c1a
    
  - Merge remote-tracking branch 'aosp/upstream-main' into HEAD am: 97b4f2559e am: 6e792d7aa5 am: fc030f53a5
    
    Original change: https://android-review.googlesource.com/c/platform/external/drm_hwcomposer/+/1883310
    
    Change-Id: I74fbf209afc31b56a35380946c6c27142e3b194d
    
  - Merge remote-tracking branch 'aosp/upstream-main' into HEAD am: 97b4f2559e am: 6e792d7aa5
    
    Original change: https://android-review.googlesource.com/c/platform/external/drm_hwcomposer/+/1883310
    
    Change-Id: I3861fb091fb45c0cd3b00a7267cc43c57f4b9a2c
    
  - Merge remote-tracking branch 'goog/mirror-aosp-master' into merge am: 4c333dd763
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/external/drm_hwcomposer/+/16042371
    
    Change-Id: I0068287e2500f1789fc809213726380077158c57
    
  - Merge remote-tracking branch 'goog/mirror-aosp-master' into merge
    
    The trout virtual device was broken by the recent move to HWC 2.4
    as it was not able to execute the new calls in HWC 2.4; bring in
    AOSP drm_hwc in order to support HWC 2.4 on trout
    
    Bug: 202850907
    Test: build and boot trout
    Change-Id: I418234d51a8674ed348774a02f7b28ed6495e7ac
    
  - drm_hwcomposer: Merge remote-tracking branch 'aosp/upstream-main' into HEAD am: 38163fdedc am: ecb41b1fdc am: 197ccc9866 am: a976c15a02
    
    Original change: https://android-review.googlesource.com/c/platform/external/drm_hwcomposer/+/1809159
    
    Change-Id: Ic7f2914fcc77abcca6707975905f17c7121b95b0
    
  - Merge remote-tracking branch 'gitlab/main' into HEAD am: 84fa73c0d4 am: 82288efb3a am: 469d0d5452
    
    Original change: https://android-review.googlesource.com/c/platform/external/drm_hwcomposer/+/1714669
    
    Change-Id: Ib711a939454ada9dfce6daa3ae7db451888e7be7