Update git submodules
* Update platform/external/autotest from branch 'master'
  to 476666867025e3d7fce3e7481aa2bebb54bdbef8
  - servo: Consolidate xmlrpc and socket error wrapping. am: 0d92eaf99f
    
    Original change: undetermined
    
    Change-Id: Icbb0302b4a5ac1319221f49ba29335966b073c1e
    
  - servo: Consolidate xmlrpc and socket error wrapping.
    
    Instead of having two different wrapper functions, now multiple types
    of control exceptions are wrapped by the same context manager.  It's
    also now a class, for separation between __enter__ and __exit__.
    
    Since set_get_all was created back in 2013, this commit simplifies
    the code by removing some compatibility code for servod lacking it.
    
    One other minor change is a rename of ServodBadStatusLine, to make it
    easier to search for instances of the error that *aren't* servod.
    
    Example:
    
    ServodConnectionError: has_control->doc(usb_mux_oe1) -- [Errno 104] Connection reset by peer: "<Servo 'labstation.test:9999'>"
    ServodBadResponse: initialize_dut->hwinit() -- StatusLine=''
    
    BUG=b:161371008
    TEST=Run a test that uses Servo, terminate servod during the test
    
    Change-Id: Ic8a68fb38a2556ef9a670ed29f6658e6751edd5c
    Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/2365593
    Tested-by: Dana Goyette <dgoyette@chromium.org>
    Commit-Queue: Dana Goyette <dgoyette@chromium.org>
    Reviewed-by: Gregory Nisbet <gregorynisbet@google.com>
    Reviewed-by: Ruben Rodriguez Buchillon <coconutruben@chromium.org>
    

* Update platform/superproject from branch 'master'
  to 96da37db24cd89c3930f6ab69ae22dc47bafb83d
  - Update git submodules
    
    * Update external/autotest from branch 'master'
      to 476666867025e3d7fce3e7481aa2bebb54bdbef8
      - servo: Consolidate xmlrpc and socket error wrapping. am: 0d92eaf99f
        
        Original change: undetermined
        
        Change-Id: Icbb0302b4a5ac1319221f49ba29335966b073c1e
        
      - servo: Consolidate xmlrpc and socket error wrapping.
        
        Instead of having two different wrapper functions, now multiple types
        of control exceptions are wrapped by the same context manager.  It's
        also now a class, for separation between __enter__ and __exit__.
        
        Since set_get_all was created back in 2013, this commit simplifies
        the code by removing some compatibility code for servod lacking it.
        
        One other minor change is a rename of ServodBadStatusLine, to make it
        easier to search for instances of the error that *aren't* servod.
        
        Example:
        
        ServodConnectionError: has_control->doc(usb_mux_oe1) -- [Errno 104] Connection reset by peer: "<Servo 'labstation.test:9999'>"
        ServodBadResponse: initialize_dut->hwinit() -- StatusLine=''
        
        BUG=b:161371008
        TEST=Run a test that uses Servo, terminate servod during the test
        
        Change-Id: Ic8a68fb38a2556ef9a670ed29f6658e6751edd5c
        Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/2365593
        Tested-by: Dana Goyette <dgoyette@chromium.org>
        Commit-Queue: Dana Goyette <dgoyette@chromium.org>
        Reviewed-by: Gregory Nisbet <gregorynisbet@google.com>
        Reviewed-by: Ruben Rodriguez Buchillon <coconutruben@chromium.org>