Update git submodules
* Update platform/external/mesa3d from branch 'master'
  to 5e0303ace001baac2e3c3265a37029db55b50bc0
  - Merge "Add xmlpool/options.h back in the list of intermediate prebuilt source files"
  - Add xmlpool/options.h back in the list of intermediate prebuilt source files
    
    commit 092675ffa035 ("mesa3d: dragonboards: add format_srgb.c
    to prebuilts") overrides the list of locally generated source
    files(LOCAL_GENERATED_SOURCES) and we run into following build
    error:
    
    external/mesa3d/src/util/xmlpool.h:103:10: fatal error: 'xmlpool/options.h' file not found
    
    Currently in src/util/Android.mk, LOCAL_GENERATED_SOURCES list
    is populated as -->
    LOCAL_GENERATED_SOURCES := $(UTIL_GENERATED_SOURCES)
    LOCAL_GENERATED_SOURCES += $(MESA_DRI_OPTIONS_H)
    LOCAL_GENERATED_SOURCES := $(MESA_FORMAT_SRGB_C)
    
    The last assignment ":=" effectively overrides the existing
    LOCAL_GENERATED_SOURCES list including MESA_DRI_OPTIONS_H,
    hence causing xmlpool/options.h file not found build error.
    
    We fix the build by populating the LOCAL_GENERATED_SOURCES as:
    LOCAL_GENERATED_SOURCES := $(UTIL_GENERATED_SOURCES)
    LOCAL_GENERATED_SOURCES := $(MESA_DRI_OPTIONS_H)
    LOCAL_GENERATED_SOURCES += $(MESA_FORMAT_SRGB_C)
    
    As for UTIL_GENERATED_SOURCES, since AOSP master build system
    has started to police the use of non-hermetic tools from the
    system PATH, see commit 5e0738226596 ("Add prebuilt-intermediates
    for xmlpool) for reference, it is highly unlikely that we are
    going to use UTIL_GENERATED_SOURCES ever agin. So it is safe to
    assume and keep overriding the list of those util generated
    source files, at least for now.
    
    Change-Id: I173037f9303c849533037ac0abd09faf9544ce80
    Signed-off-by: Amit Pundir <amit.pundir@linaro.org>
    

* Update platform/superproject from branch 'master'
  to a3929c3e5c48a03990d47672b46d05a52989c145
  - Update git submodules
    
    * Update external/mesa3d from branch 'master'
      to 5e0303ace001baac2e3c3265a37029db55b50bc0
      - Merge "Add xmlpool/options.h back in the list of intermediate prebuilt source files"
      - Add xmlpool/options.h back in the list of intermediate prebuilt source files
        
        commit 092675ffa035 ("mesa3d: dragonboards: add format_srgb.c
        to prebuilts") overrides the list of locally generated source
        files(LOCAL_GENERATED_SOURCES) and we run into following build
        error:
        
        external/mesa3d/src/util/xmlpool.h:103:10: fatal error: 'xmlpool/options.h' file not found
        
        Currently in src/util/Android.mk, LOCAL_GENERATED_SOURCES list
        is populated as -->
        LOCAL_GENERATED_SOURCES := $(UTIL_GENERATED_SOURCES)
        LOCAL_GENERATED_SOURCES += $(MESA_DRI_OPTIONS_H)
        LOCAL_GENERATED_SOURCES := $(MESA_FORMAT_SRGB_C)
        
        The last assignment ":=" effectively overrides the existing
        LOCAL_GENERATED_SOURCES list including MESA_DRI_OPTIONS_H,
        hence causing xmlpool/options.h file not found build error.
        
        We fix the build by populating the LOCAL_GENERATED_SOURCES as:
        LOCAL_GENERATED_SOURCES := $(UTIL_GENERATED_SOURCES)
        LOCAL_GENERATED_SOURCES := $(MESA_DRI_OPTIONS_H)
        LOCAL_GENERATED_SOURCES += $(MESA_FORMAT_SRGB_C)
        
        As for UTIL_GENERATED_SOURCES, since AOSP master build system
        has started to police the use of non-hermetic tools from the
        system PATH, see commit 5e0738226596 ("Add prebuilt-intermediates
        for xmlpool) for reference, it is highly unlikely that we are
        going to use UTIL_GENERATED_SOURCES ever agin. So it is safe to
        assume and keep overriding the list of those util generated
        source files, at least for now.
        
        Change-Id: I173037f9303c849533037ac0abd09faf9544ce80
        Signed-off-by: Amit Pundir <amit.pundir@linaro.org>