Update git submodules
* Update platform/external/minijail from branch 'master'
  to f65da3a91d350345a3b2a4e365314c5efdb13851
  - minijail0: implement --env-reset and --env-add
    
    The default behavior of minijail0 is to transmit its own environment
    to the program it launches.
    These two options enable modification of this standard behavior, by
    setting up a specific environment for the target program.
    
    * --env-reset prevents minijail0 to pass its own environment to the
    program. Note that if this option is used without any --env-add option,
    the program starts with a completely empty environment.
    
    * --env-add allows setting any number of environment variables to be
    added to the environment set up for the program. Note that the special
    environment variable LD_PRELOAD can also be set this way, without
    impacting minijail0's own invocation.
    
    Test: `make tests`
    
    Test: `valgrind ./minijail0 --env-add A=X /usr/bin/env`
    Test: `valgrind ./minijail0 --env-add A=X --env-add A=Y /usr/bin/env`
    Test: `valgrind ./minijail0 --env-reset /usr/bin/env`
    Test: `valgrind ./minijail0 --env-reset --env-reset /usr/bin/env`
    Test: `valgrind ./minijail0 --env-reset --env-add A=X /usr/bin/env`
    Test: `valgrind ./minijail0 --env-add A=X --env-reset --env-add A=Y /usr/bin/env`
    Test: `valgrind ./minijail0 --env-add A=X --env-reset --env-add A=Y --env-reset /usr/bin/env`
    
    Test: `minijail0 --env-reset --env-add LD_PRELOAD="a b" --env-add FOO=bar /usr/bin/env`
    """
    ERROR: ld.so: object 'a' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
    ERROR: ld.so: object 'b' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
    LD_PRELOAD=a b
    FOO=bar
    """
    
    Change-Id: I2e106003824ff6707b80b6653141657e4ec40f47