Update git submodules
* Update platform/art from branch 'master'
  to bd0f277e83ee8ad5faae3813512e780319dc885f
  - Add missing assert.h and functional includes
    
    Bug: http://b/175635923
    Test: treehugger
    Change-Id: I0520133c1d21e93609edf77f078afaccd7017aa5
    
  - Remove unneeded art::Unit member functions
    
    Remove ~Unit to avoid a build failure after libc++ upgrade:
    
    art/cmdline/unit.h:29:3: error: definition of implicit copy assignment operator for 'Unit' is deprecated because it has a user-provided destructor [-Werror,-Wdeprecated-copy-with-user-provided-dtor]
    
    (Perhaps std::vector changed to use assignment instead of a copy ctor.)
    
    Also remove the Unit() default ctor, because it's unnecessary, and
    Valgrind support has been deprecated for years now. Similarly, remove
    the explicitly-defaulted copy ctor. It can be defined implicitly (i.e.
    following the C++ "rule of zero").
    
    Bug: http://b/175635923
    Test: treehugger
    Change-Id: Iefd41dad5b88361104ab159549058daa3b895612