Update git submodules
* Update platform/external/scudo from branch 'master'
  to b35c52a7fd0fec818d77809d60562a7a302a82b2
  - Revert "[Scudo] enabling anonymous named pages on Linux 5.17 and onwards."
    
    This reverts commit 619499252307c520fd840a5f3c79ffa00eaf2264.
    
    GitOrigin-RevId: 016e59bf2cbf3e550a1fca5c4de204d84565ab03
    Change-Id: I7336d756d107280e6fcdd8f3c02d42665c473fcc
    
  - [Scudo] enabling anonymous named pages on Linux 5.17 and onwards.
    
    Reviewers: vitalybuka
    
    Reviewed-By: vitalybuka
    
    Differential Revision: https://reviews.llvm.org/D122962
    
    GitOrigin-RevId: 619499252307c520fd840a5f3c79ffa00eaf2264
    Change-Id: I484285595f33e2daef776050a99fbfc30a58a7c8
    
  - [compiler-rt] [scudo] Use -mcrc32 on x86 when available
    
    Update the hardware CRC32 logic in scudo to support using `-mcrc32`
    instead of `-msse4.2`.  The CRC32 intrinsics use the former flag
    in the newer compiler versions, e.g. in clang since 12fa608af44a.
    With these versions of clang, passing `-msse4.2` is insufficient
    to enable the instructions and causes build failures when `-march` does
    not enable CRC32 implicitly:
    
        /var/tmp/portage/sys-libs/compiler-rt-sanitizers-14.0.0/work/compiler-rt/lib/scudo/scudo_crc32.cpp:20:10: error: always_inline function '_mm_crc32_u32' requires target feature 'crc32', but would be inlined into function 'computeHardwareCRC32' that is compiled without support for 'crc32'
          return CRC32_INTRINSIC(Crc, Data);
                 ^
        /var/tmp/portage/sys-libs/compiler-rt-sanitizers-14.0.0/work/compiler-rt/lib/scudo/scudo_crc32.h:27:27: note: expanded from macro 'CRC32_INTRINSIC'
        #  define CRC32_INTRINSIC FIRST_32_SECOND_64(_mm_crc32_u32, _mm_crc32_u64)
                                  ^
        /var/tmp/portage/sys-libs/compiler-rt-sanitizers-14.0.0/work/compiler-rt/lib/scudo/../sanitizer_common/sanitizer_platform.h:132:36: note: expanded from macro 'FIRST_32_SECOND_64'
        #  define FIRST_32_SECOND_64(a, b) (a)
                                           ^
        1 error generated.
    
    For backwards compatibility, use `-mcrc32` when available and fall back
    to `-msse4.2`.  The `<smmintrin.h>` header remains in use as it still
    works and is compatible with GCC, while clang's `<crc32intrin.h>`
    is not.
    
    Use __builtin_ia32*() rather than _mm_crc32*() when using `-mcrc32`
    to preserve compatibility with GCC.  _mm_crc32*() are aliases
    to __builtin_ia32*() in both compilers but GCC requires `-msse4.2`
    for the former, while both use `-mcrc32` for the latter.
    
    Originally reported in https://bugs.gentoo.org/835870.
    
    Differential Revision: https://reviews.llvm.org/D122789
    
    GitOrigin-RevId: fd1da784ac644492f8ca40064baf3ef360352f55
    Change-Id: I0f43b4130bdf02d558ab71e302696e0d9664b26b
    
  - Revert "[compiler-rt] [scudo] Use -mcrc32 on x86 when available"
    
    This reverts commit 09b53121c323f260ab97cecd067d4e7b3be1bf7c.
    
    Breaks the build with GCC 11.2 on x86_64:
    
    In file included from /home/npopov/repos/llvm-project/compiler-rt/lib/scudo/scudo_crc32.h:27,
                     from /home/npopov/repos/llvm-project/compiler-rt/lib/scudo/scudo_crc32.cpp:14:
    /usr/lib/gcc/x86_64-redhat-linux/11/include/smmintrin.h: In function ‘__sanitizer::u32 __scudo::computeHardwareCRC32(__sanitizer::u32, __sanitizer::uptr)’:
    /usr/lib/gcc/x86_64-redhat-linux/11/include/smmintrin.h:846:1: error: inlining failed in call to ‘always_inline’ ‘long long unsigned int _mm_crc32_u64(long long unsigned int, long long unsigned int)’: target specific option mismatch
      846 | _mm_crc32_u64 (unsigned long long __C, unsigned long long __V)
    
    GitOrigin-RevId: 985c717cdbffd5da7cb188ba8b81f4fd662a81e0
    Change-Id: Iee437853bc5665cc4d79fb5a019269a08ca7bb4a
    
  - [compiler-rt] [scudo] Use -mcrc32 on x86 when available
    
    Update the hardware CRC32 logic in scudo to support using `-mcrc32`
    instead of `-msse4.2`.  The CRC32 intrinsics use the former flag
    in the newer compiler versions, e.g. in clang since 12fa608af44a.
    With these compilers, passing `-msse4.2` is insufficient to enable
    the instructions and causes build failures when `-march` does not enable
    CRC32:
    
        /var/tmp/portage/sys-libs/compiler-rt-sanitizers-14.0.0/work/compiler-rt/lib/scudo/scudo_crc32.cpp:20:10: error: always_inline function '_mm_crc32_u32' requires target feature 'crc32', but would be inlined into function 'computeHardwareCRC32' that is compiled without support for 'crc32'
          return CRC32_INTRINSIC(Crc, Data);
                 ^
        /var/tmp/portage/sys-libs/compiler-rt-sanitizers-14.0.0/work/compiler-rt/lib/scudo/scudo_crc32.h:27:27: note: expanded from macro 'CRC32_INTRINSIC'
        #  define CRC32_INTRINSIC FIRST_32_SECOND_64(_mm_crc32_u32, _mm_crc32_u64)
                                  ^
        /var/tmp/portage/sys-libs/compiler-rt-sanitizers-14.0.0/work/compiler-rt/lib/scudo/../sanitizer_common/sanitizer_platform.h:132:36: note: expanded from macro 'FIRST_32_SECOND_64'
        #  define FIRST_32_SECOND_64(a, b) (a)
                                           ^
        1 error generated.
    
    For backwards compatibility, use `-mcrc32` when available and fall back
    to `-msse4.2`.  The `<smmintrin.h>` header remains in use as it still
    works and is compatible with GCC, while clang's `<crc32intrin.h>`
    is not.
    
    Originally reported in https://bugs.gentoo.org/835870.
    
    Differential Revision: https://reviews.llvm.org/D122789
    
    GitOrigin-RevId: 09b53121c323f260ab97cecd067d4e7b3be1bf7c
    Change-Id: Ic41da7c0ddb05b1a26b4624e05fc26a24b21be35
    
  - [scudo] Reland: Add noreturn/pragma to suppress compiler warnings
    
    Differential Revision: https://reviews.llvm.org/D121853
    
    GitOrigin-RevId: 5fd0925bc98e9e42a08634063be3e81cd546f46d
    Change-Id: If0d04d400552d6492ef67567c7bfe3ec66f7832b
    
  - Revert "[scudo] Wrap clang pragma to avoid GCC error"
    Revert "[scudo] Add noreturn/pragma to suppress compiler warnings"
    
    This reverts commit 686dcbe8b018759b5443c05bfeeb7abf4d9cf09c.
    This reverts commit 030d8262a6e8055660ae74bdb7e4f22c741a1e17.
    
    GitOrigin-RevId: 22a95dd3e6c911c2854dd75f42ba32d34840a61a
    Change-Id: Ic7ac0531d99b43e4bbc5f708650c453c8ccff152
    
  - [scudo] Provide allocator declaration
    
    Ensure that extern allocator declaration is visible before definition
    
    Differential Revision: https://reviews.llvm.org/D121848
    
    GitOrigin-RevId: 6ba8c8abe982722f5e4383553d03c1c77f9dfbb0
    Change-Id: If795a9d560c390e3116bc6276e42309883a17c8b
    
  - [scudo] Wrap clang pragma to avoid GCC error
    
    Fixes: [scudo] Add noreturn/pragma to suppress compiler warnings
    
    Differential Revision: https://reviews.llvm.org/D121853
    
    GitOrigin-RevId: 030d8262a6e8055660ae74bdb7e4f22c741a1e17
    Change-Id: I1adb57c8641b74f98cfac3a00cf61e025df37211
    
  - [scudo] Add noreturn/pragma to suppress compiler warnings
    
    Differential Revision: https://reviews.llvm.org/D121853
    
    GitOrigin-RevId: 686dcbe8b018759b5443c05bfeeb7abf4d9cf09c
    Change-Id: I73b66b04ab311c0ac7736e6cadd1265e57365010
    
  - [scudo] Add missing include for extern variable declaration
    
    Add include to resolve compiler warning about no previous extern declaration for non-static HashAlgorithm
    
    Differential Revision: https://reviews.llvm.org/D122630
    
    GitOrigin-RevId: db13f5a1b01e323ac1954bc239d47516d3227c47
    Change-Id: I118306bfc26a64a532adf6e214dc6f1f7c9d5023
    
  - [scudo] Fix definition of canCache() function
    
    The called member function has boolean type, change this function to match
    
    Differential Revision: https://reviews.llvm.org/D122631
    
    GitOrigin-RevId: d0eeb0fba09f2eeebb2d71f70c8b491dc3c4f316
    Change-Id: I6cf4a9c04cea4496320fad0537118c6cff672070
    
  - [scudo] Initialize local variable to avoid compiler warning
    
    Compiler warns about HeaderPos possibly being uninitialized which should not be possible, but just initialize it anyway
    
    Differential Revision: https://reviews.llvm.org/D122632
    
    GitOrigin-RevId: 92897217fa1483e437e1716ebcb3b747f2e22dcb
    Change-Id: I384a048b5eacca59052149833ef89dd6ec5b6308
    
  - [scudo] Use template specialization on Quarantine to avoid zero-length array
    
    Use a separate templated QuarantineBlocks class to avoid a zero-length array
    
    Differential Revision: https://reviews.llvm.org/D122518
    
    GitOrigin-RevId: 0e1d2007aa3c63597c6965dd265055da78bf7c51
    Change-Id: I2b8a70e0382c0ea408d6ccf89cbc9d526d64bdbb
    
  - Revert "[scudo] Use template specialization on Quarantine to avoid zero-length array"
    
    This reverts commit 7dda44c189d74ec0a1bbe7dfff7c4d5f6b0e96d4.
    
    GitOrigin-RevId: a52868a55c45b9f67b8efb54e18a6275aff2b39e
    Change-Id: Ia5a6bb37a559ac311c736a8223d0ccbc71dc064c
    
  - [scudo] Use cast on calls to __builtin_umul_overflow/__builtin_umull_overflow
    
    Platforms may define uintptr_t differently, so perform an explicit cast
    
    Differential Revision: https://reviews.llvm.org/D121852
    
    GitOrigin-RevId: 9343fc76133bfdd0e4003e58403a79b140ec1b25
    Change-Id: Ia586cba305a28128b2ed9aa16b96dbb1f8f18b5c
    
  - [scudo] Use template specialization on Quarantine to avoid zero-length array
    
    Use a separate templated QuarantineBlocks class to avoid a zero-length array
    
    Differential Revision: https://reviews.llvm.org/D122518
    
    GitOrigin-RevId: 7dda44c189d74ec0a1bbe7dfff7c4d5f6b0e96d4
    Change-Id: Ie3eb863d387b4437dc0c571b1681b9ea1ac2268c