Update git submodules
* Update platform/superproject from branch 'master'
  to 00ec4c99814059da4cef9cc59c1ff292c90a4c8c
  - Update git submodules
    
    * Update tools/acloud from branch 'master'
      to 27d72c398038c4d063570172646425d26fa54731
      - Merge "acloud: fix py3 compatible issue: "AttributeError" of 'filter' object has no attribute 'append'"
      - acloud: fix py3 compatible issue: "AttributeError" of 'filter' object has no attribute 'append'
        
        Wrap with list(filter..)) since filter return list in py2 but
        return type of 'filter' in py3.
        Although gcompute_client didn't call 'append', it also should wrap with
        list.
        
        BUG: 137195528
        Test: acloud-dev create --local-image
        Change-Id: I87af280fe4a41e014c0352d0bfb2db45b0796132
        

* Update platform/tools/acloud from branch 'master'
  to 27d72c398038c4d063570172646425d26fa54731
  - Merge "acloud: fix py3 compatible issue: "AttributeError" of 'filter' object has no attribute 'append'"
  - acloud: fix py3 compatible issue: "AttributeError" of 'filter' object has no attribute 'append'
    
    Wrap with list(filter..)) since filter return list in py2 but
    return type of 'filter' in py3.
    Although gcompute_client didn't call 'append', it also should wrap with
    list.
    
    BUG: 137195528
    Test: acloud-dev create --local-image
    Change-Id: I87af280fe4a41e014c0352d0bfb2db45b0796132