Update git submodules
* Update platform/external/mdnsresponder from branch 'master'
  to bade252173f8fbc5a0675c09e44dce5073456785
  - Merge "Increase keyword buffer size to 11 since we read up to 10 bytes."
  - Increase keyword buffer size to 11 since we read up to 10 bytes.
    
    external/mdnsresponder/mDNSPosix/mDNSPosix.c:516:32: error: 'sscanf' may overflow; destination buffer in argument 3 has size 10, but the corresponding specifier may require size 11 [-Werror,-Wfortify-source]
                    if (sscanf(line,"%10s %15s", keyword, nameserver) != 2) continue;       // it will skip whitespaces
    
    This was found as part of testing
    https://android-review.googlesource.com/c/toolchain/llvm_android/+/1940575.
    
    Test: builds with latest fortify-source checks
    Change-Id: Id6910c32875b82e44020f6138e8e89b6a8bff4a4