Update git submodules
* Update device/linaro/dragonboard from branch 'master'
  to 845c78e2bb6325671d7d9ea2846325774ce450f6
  - db845c: Fix android.graphics.cts.OpenGlEsDeqpLevelTest#testOpenGlEsDeqpLevel
    
    When running CtsGraphicsTestCases, I was seeing failures from
    android.graphics.cts.OpenGlEsDeqpLevelTest#testOpenGlEsDeqpLevel:
    
    [1/1] android.graphics.cts.OpenGlEsDeqpLevelTest#testOpenGlEsDeqpLevel: FAILED (138ms)
    
    STACKTRACE:
    java.lang.AssertionError: Feature android.software.opengles.deqp.level must be present and have at least version 132383489
            at org.junit.Assert.fail(Assert.java:89)
            at org.junit.Assert.assertTrue(Assert.java:42)
            at android.graphics.cts.OpenGlEsDeqpLevelTest.testOpenGlEsDeqpLevel(OpenGlEsDeqpLevelTest.java:64)
    
    So this patch adds the file to set android.software.opengles.deqp.level.
    
    Signed-off-by: John Stultz <john.stultz@linaro.org>
    Change-Id: I1cf4592e14eae9c73b2c81b36e28213c3fb1cd60