Update git submodules
* Update platform/external/elfutils from branch 'master'
  to 325ecbcd3c4a49f26f46c139c9543ddd09ca3007
  - Merge "dwfl: fix potential overflow when reporting on kernel modules"
  - dwfl: fix potential overflow when reporting on kernel modules
    
    dwfl_linux_kernel_report_modules_ has an outstanding ancient bug when
    reading kernel module information from a modules list file. The target
    buffer for the module name was sized too small to hold potential values.
    Fix that by increasing the value to account for the null termination.
    
    In practice, this unlikely ever happened, but it now got diagnosed by
    LLVM as part of a stricter -Wfortify-source implementation [1]:
    
    libdwfl/linux-kernel-modules.c:1019:7: error: 'sscanf' may overflow; destination buffer in argument 3 has size 128, but the corresponding specifier may require size 129 [-Werror,-Wfortify-source]
                        modname, &modsz, &modaddr) == 3)
    
    [1] https://github.com/llvm/llvm-project/commit/2db66f8d48beeea835cb9a6940e25bc04ab5d941
    
    Suggested-by: Paul Pluzhnikov <ppluzhnikov@google.com>
    Signed-off-by: Matthias Maennich <maennich@google.com>
    
    Test: Builds with new clang without warnings
    (cherry picked from commit 2e3bc18672f0cede0332ae3194eb2e33d4cc5fd7)
    Change-Id: I19342bb64ff5b973aa3f4c65abed8123eab8367d
    
  - Merge changes Ie8f964b5,I644650d7 am: be508084da
    
    Original change: https://android-review.googlesource.com/c/platform/external/elfutils/+/1895360
    
    Change-Id: Ieef9602118d5afa007831783893f296de1cd0e7f
    
  - Merge "Extend visibility to //external/stg" am: eed13d52bc
    
    Original change: https://android-review.googlesource.com/c/platform/external/elfutils/+/1892422
    
    Change-Id: I1fb62b9b5eb3e1132912406388ac0997ce4a0118
    
  - Merge "Support building elfutils against musl" am: 462e61fb7e am: 214f750dc9 am: 5adfcd8adb
    
    Original change: https://android-review.googlesource.com/c/platform/external/elfutils/+/1819989
    
    Change-Id: I2f64b3c66a7411a688e49b5e7acad451a7086b23
    
  - Merge "lib: Make error.c more like error(3)" am: 7134827f42 am: 5a845dbd8d am: aff7b07ee1
    
    Original change: https://android-review.googlesource.com/c/platform/external/elfutils/+/1819988
    
    Change-Id: Idaa79dd0deea2e6ea6d0566a83ecdccdaffe823d
    
  - Merge "Support building elfutils against musl" am: 462e61fb7e am: 214f750dc9
    
    Original change: https://android-review.googlesource.com/c/platform/external/elfutils/+/1819989
    
    Change-Id: I63535e7d75919472a2b1ce687fd10228c9993fad
    
  - Merge "lib: Make error.c more like error(3)" am: 7134827f42 am: 5a845dbd8d
    
    Original change: https://android-review.googlesource.com/c/platform/external/elfutils/+/1819988
    
    Change-Id: Ia441dd9cb551d449c609f1f2c248a96f6ee6c485
    
  - Merge "Add patch for manual config.h changes" am: 54e9c47ac3 am: 377347e7d7 am: c71044154f
    
    Original change: https://android-review.googlesource.com/c/platform/external/elfutils/+/1822514
    
    Change-Id: I0cd716c29db8214091dc84e7d14f74a7428d978b
    
  - Merge "Add patch for manual config.h changes" am: 54e9c47ac3 am: 377347e7d7
    
    Original change: https://android-review.googlesource.com/c/platform/external/elfutils/+/1822514
    
    Change-Id: I81772b15221ed5cc34d599608e0ef566d5ea7a6e
    
  - Merge changes I9001f472,I324bee2b,I1a634839,I0663d474,I320ee9c2, ... am: 820f86f790 am: 21d650df05 am: df5daa1498
    
    Original change: https://android-review.googlesource.com/c/platform/external/elfutils/+/1819987
    
    Change-Id: Ica3d1ffb6cd374626575f0e91b157390fc4d9eeb
    
  - Merge changes I9001f472,I324bee2b,I1a634839,I0663d474,I320ee9c2, ... am: 820f86f790 am: 21d650df05
    
    Original change: https://android-review.googlesource.com/c/platform/external/elfutils/+/1819987
    
    Change-Id: I1ebe60a3be578303868f3d8c8fc0421ffe258c91