Update git submodules
* Update platform/external/swiftshader from branch 'master'
  to abf48850bebdc1544d2fd875b440f0b954c39060
  - Roll SwiftShader from b89ed2f23a03 to 9ebfb6b54814 (2 revisions)
    
    https://swiftshader.googlesource.com/SwiftShader.git/+log/b89ed2f23a03..9ebfb6b54814
    
    Please enable autosubmit on changes if possible when approving them.
    
    If this roll has caused a breakage, revert this CL and stop the roller
    using the controls here:
    https://autoroll.skia.org/r/swiftshader-android
    Please CC natsu@google.com,nicolascapens@google.com,swiftshader-eng@google.com on the revert to ensure that a human
    is aware of the problem.
    
    To file a bug in SwiftShader: https://bugs.chromium.org/p/swiftshader/issues/entry
    
    To report a problem with the AutoRoller itself, please file a bug:
    https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug
    
    Documentation for the AutoRoller is here:
    https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md
    
    Test: Presubmit checks will test this change.
    Exempt-From-Owner-Approval: The autoroll bot does not require owner approval.
    Bug: b/242184599
    Change-Id: I00895ad4e61d24744855f7cdadb7d20cb7a7dc6e
    
  - Align allocations to 4096 on Android hosts
    
    ... as allocations which may be mapped into KVM virtual machines
    need to be page aligned.
    
    Bug: b/242184599
    Test: cvd start --gpu_mode=gfxstream_guest_angle_host_swiftshader
    Change-Id: I5e6b7a765e254dbd965b69cd94dc49671d740db3
    Reviewed-on: https://swiftshader-review.googlesource.com/c/SwiftShader/+/71628
    Presubmit-Ready: Jason Macnak <natsu@google.com>
    Kokoro-Result: kokoro <noreply+kokoro@google.com>
    Commit-Queue: Jason Macnak <natsu@google.com>
    Reviewed-by: Geoff Lang <geofflang@google.com>
    Tested-by: Jason Macnak <natsu@google.com>
    
  - IWYU: add cstdint for uintptr_t in llvm-10.0 Signals.h
    
    Upstream commit:
    
      From ff1681ddb303223973653f7f5f3f3435b48a1983 Mon Sep 17 00:00:00 2001
      From: Sergei Trofimovich <slyich@gmail.com>
      Date: Mon, 23 May 2022 08:03:23 +0100
      Subject: [PATCH] [Support] Add missing <cstdint> header to Signals.h
    
      Without the change llvm build fails on this week's gcc-13 snapshot as:
    
        [  0%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/Signals.cpp.o
        In file included from llvm/lib/Support/Signals.cpp:14:
        llvm/include/llvm/Support/Signals.h:119:8: error: variable or field 'CleanupOnSignal' declared void
          119 |   void CleanupOnSignal(uintptr_t Context);
              |        ^~~~~~~~~~~~~~~
    
    Change-Id: Iabe0256d86012e7887e295815aa6cfd50694459a
    Reviewed-on: https://swiftshader-review.googlesource.com/c/SwiftShader/+/71608
    Reviewed-by: Shahbaz Youssefi <syoussefi@google.com>
    Kokoro-Result: kokoro <noreply+kokoro@google.com>
    Tested-by: Shahbaz Youssefi <syoussefi@google.com>
    Commit-Queue: Shahbaz Youssefi <syoussefi@google.com>