Update git submodules
* Update platform/external/scudo from branch 'master'
  to e1509e34983c9a759bbeaa98b6aab23bc216eb25
  - Merge "Don't report unused parameter on riscv64"
  - Don't report unused parameter on riscv64
    
    Ignore the following warning to allow compilation on riscv64.
    external/scudo/standalone/common.h:103:31: error: unused parameter 'Count' [-Werror,-Wunused-parameter]
    inline void yieldProcessor(u8 Count) {
    
    Test: Builds
    Signed-off-by: CHEN GUOYIN <chenguoyin.cgy@linux.alibaba.com>
    Signed-off-by: Mao Han <han_mao@linux.alibaba.com>
    Change-Id: I6a20f3271550399853254aefec04fe2d4e3ec5c0