Update git submodules
* Update platform/external/vixl from branch 'master'
  to 0055695302d9c837f7184999383c91a35994a770
  - Fix Wbitwise-instead-of-logical
    
    Bug: http://b/217563632
    Bug: http://b/215753485
    
    This was found by upcoming clang-r445002 update.
    
    external/vixl/src/aarch64/assembler-aarch64.cc:2738:17: error: use of
    bitwise '|' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
        VIXL_ASSERT(vd.Is2S() | vd.Is4S());
    
    external/vixl/src/aarch64/assembler-aarch64.cc:2755:17: error: use of
    bitwise '|' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
        VIXL_ASSERT(vd.Is4H() | vd.Is8H());
    
    external/vixl/src/aarch32/operands-aarch32.h:296:35: warning: use of
    bitwise '|' with boolean operands [-Wbitwise-instead-of-logical]
    
      bool IsInteger() const { return IsInteger32() | IsInteger64(); }
    
    Test: Build with new clang
    Change-Id: I5b77e90881a0cc7ff0266c69f035abc2d3266a7e
    
  - Change libvixl symbol visibility. am: 07f3653da4 am: 6d0be08f95 am: 4632b10c27 am: 0da09680b5
    
    Original change: https://android-review.googlesource.com/c/platform/external/vixl/+/1697237
    
    Change-Id: If97d079809651f445a2d768828147bedf02cd082
    
  - Change libvixl symbol visibility. am: 07f3653da4 am: 6d0be08f95 am: 4632b10c27
    
    Original change: https://android-review.googlesource.com/c/platform/external/vixl/+/1697237
    
    Change-Id: I593c20dde4d5893a17e13f42a3f432d54ffcd909
    
  - Change libvixl symbol visibility. am: 07f3653da4 am: 6d0be08f95
    
    Original change: https://android-review.googlesource.com/c/platform/external/vixl/+/1697237
    
    Change-Id: I7b24126254439bc0eb4c9a1ec638f43e5506f90d
    
  - Change libvixl symbol visibility. am: 07f3653da4
    
    Original change: https://android-review.googlesource.com/c/platform/external/vixl/+/1697237
    
    Change-Id: I4d484e8b250979800b66b729762ade28df4a76d0
    
  - Merge "[sve] Fix while simulation corner case" am: 32d1887005 am: 24645f8955 am: d7bea93e0e
    
    Original change: https://android-review.googlesource.com/c/platform/external/vixl/+/1596671
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Ia6ab5af0658d05628fc268b6d9c631bcb7b8196c
    
  - Merge "[sve] Fix while simulation corner case" am: 32d1887005 am: 24645f8955
    
    Original change: https://android-review.googlesource.com/c/platform/external/vixl/+/1596671
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Id224d69bd799903989be8e30cbb23881d770bf31
    
  - Merge "[sve] Fix while simulation corner case" am: 32d1887005
    
    Original change: https://android-review.googlesource.com/c/platform/external/vixl/+/1596671
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Icecd39efbd5de9815a4e9b340fea642ab64d5881
    
  - Merge "Add min_sdk_version for ART module." am: 01322e9232 am: 742f86daa4 am: 6a0f1af6df
    
    Original change: https://android-review.googlesource.com/c/platform/external/vixl/+/1614808
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Ib8f2461608bd3d8088be8826390fa539fcbf89c0
    
  - Merge "Add min_sdk_version for ART module." am: 01322e9232 am: 742f86daa4
    
    Original change: https://android-review.googlesource.com/c/platform/external/vixl/+/1614808
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Ib687fe3a689fd0d00a46383b81f0f8074401ff16
    
  - Merge "Add min_sdk_version for ART module." am: 01322e9232
    
    Original change: https://android-review.googlesource.com/c/platform/external/vixl/+/1614808
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: If2260d6cbaaa8b193092067da5ef1334af25be3e
    
  - [automerger skipped] Mark ab/7061308 as merged in stage. am: b7589d4f78 -s ours am: 09ce70af08 -s ours
    
    am skip reason: Change-Id I31171581ec2868c21eb0793da8db7618691d4556 with SHA-1 d1a32350b3 is in history
    
    Original change: undetermined
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I7ee6f4150636fb62bf1ead039d887e84f38ee1e0
    
  - [automerger skipped] Mark ab/7061308 as merged in stage. am: b7589d4f78 -s ours
    
    am skip reason: Change-Id I31171581ec2868c21eb0793da8db7618691d4556 with SHA-1 d1a32350b3 is in history
    
    Original change: undetermined
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I87d031a69896378b481d63305e35c28c2676ba43
    
  - [LSC] Add LOCAL_LICENSE_KINDS to external/vixl am: cd42a2b85f am: b4b8f0eff4 am: f5cdcbe54b
    
    Original change: https://android-review.googlesource.com/c/platform/external/vixl/+/1588925
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: If4a6e7cf0886c0c94f5b7148df8a42d708f94e8d
    
  - [LSC] Add LOCAL_LICENSE_KINDS to external/vixl am: cd42a2b85f am: b4b8f0eff4
    
    Original change: https://android-review.googlesource.com/c/platform/external/vixl/+/1588925
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Ic2d27acb9db5eb2ff4441fe2d15601bc33f67ab6
    
  - Mark ab/6881855 as merged am: c36e159efc am: d1a32350b3
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/external/vixl/+/13111010
    
    Change-Id: If50de56029abb4dd642a25279cc8d85420b8c464
    
  - Merge changes from topic "VIXL_UPDATE_11_20" am: c4b1310f4f am: 232c365e75 am: 8654da69be am: 3b80d11845
    
    Original change: https://android-review.googlesource.com/c/platform/external/vixl/+/1492919
    
    Change-Id: I3815defd1f90efea845fc40c186ee463b05b379a
    
  - Add Ulyana Trafimovich to VIXL's `OWNERS` file. am: 35fce03ba5 am: 2b6b2b94db am: d141826069 am: 59273a40b4
    
    Original change: https://android-review.googlesource.com/c/platform/external/vixl/+/1499365
    
    Change-Id: I74ae6c0003f545f3da1b9a4e7c2df7a21bc71954
    
  - Merge "Revert "Merge remote-tracking branch 'aosp/upstream-master' into..."" am: aa1d76b182 am: 5b80cc0fda am: c08be28ad3 am: fac053ea9a
    
    Original change: https://android-review.googlesource.com/c/platform/external/vixl/+/1478659
    
    Change-Id: I4a9ffb4cbeb14ab585deed871b5f9c2440640bfb
    
  - Merge "Merge remote-tracking branch 'aosp/upstream-master' into master" am: 85a645d23e am: 9198f01852 am: 744d3aa646 am: d404edd169
    
    Original change: https://android-review.googlesource.com/c/platform/external/vixl/+/1371191
    
    Change-Id: Ia89b39c221a4673541969326d6b0442f0c43b298
    
  - [automerger skipped] Rename ART release APEX to com.android.art. am: 6032882b11 am: e54127800d am: 22ccdef692 am: 8e70319377 -s ours
    
    am skip reason: Change-Id I8f3000a4f5274316ddcc86f97d12a6afb97e50b6 with SHA-1 c978f1e65f is in history
    
    Original change: https://android-review.googlesource.com/c/platform/external/vixl/+/1454873
    
    Change-Id: I4dc4d8a5724a3d61fc05931c0510ade5431d967f
    
  - Rename ART release APEX to com.android.art.
    
    Test: See https://r.android.com/1457217
    Bug: 169639321
    Change-Id: I8f3000a4f5274316ddcc86f97d12a6afb97e50b6
    Merged-In: I8f3000a4f5274316ddcc86f97d12a6afb97e50b6
    
  - Set apex_available property am: 5c997a052f am: 27853fcf3c
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/external/vixl/+/11297989
    
    Change-Id: Ib85550fc90fe167f667a7e30869150a853ec7654
    
  - [automerger skipped] Set apex_available property am: 8eb15daf6b am: 54f58fb13d -s ours am: c88d8206e8 -s ours am: bd66280e6a -s ours am: 30cdf64f89 -s ours
    
    am skip reason: Change-Id I1889653812a980f6a2e3b6b25e7647f7c5919606 with SHA-1 5c997a052f is in history
    
    Change-Id: Id2fa9aa3c5e620261805dcee26aa0ba47a6bb47a
    
  - Merge "Set apex_available property am: 5c997a052f am: eb12cb84ad am: c150fd7455" into rvc-qpr-dev-plus-aosp am: a5697b8055
    
    Change-Id: Ie22a4375a21dc5e3b389d832297c183937945a85
    
  - Set apex_available property am: 5c997a052f am: 869b63d85c am: d85eea8993 am: e85430a9c0
    
    Change-Id: I78270cc8ea47d6fccc77e94d4ad63695e489d9dd
    
  - Set apex_available property am: 5c997a052f am: eb12cb84ad am: f66fe0dfee am: ee68d3539f
    
    Change-Id: I26cf6e7071724fa22caa9e47c99c108a229c7751
    
  - Set apex_available property am: 5c997a052f
    
    Change-Id: Ifd46978ddf16be4a79c7f065dc492378f5a6bb22
    
  - Add METADATA to vixl: BSD=NOTICE am: ad8e2af956 am: c3e950ef4c am: 297d308d44 am: db69e6613b am: 24be0c71ec
    
    Change-Id: Id06b553c42c19fab558978ad9bc6fe431d9b667a
    
  - [automerger skipped] DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp into stag-aosp-master am: 653c202dc6 -s ours am: c26ecfaea1 am: ee5b9e0246 am: 38c8269d99 -s ours
    
    am skip reason: subject contains skip directive
    
    Change-Id: I4ade5cc126f560f0420bb7a98ba4cf0fc6b34371
    
  - [automerger skipped] DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp@6304901 into stag-aosp-master am: 5c1b118487 -s ours am: c72a49769b am: ee30163070 am: 25bb926e30 -s ours
    
    am skip reason: subject contains skip directive
    
    Change-Id: Ibc92f60005d3d1fd1eeeecd20c56eef5e9f532e8