Update git submodules
* Update platform/frameworks/base from branch 'master'
  to f617f30ee068dbef72e82572e0cab245c17581d0
  - Merge "UWB: Remove Unused RTSU Constants"
  - Merge "Move ACTION_CLEAR_DNS_CACHE to ConnectivityManager"
  - Move ACTION_CLEAR_DNS_CACHE to ConnectivityManager
    
    - As API review feedback, move ACTION_CLEAR_DNS_CACHE form Intent
      to ConnectivityManager.
    
    - Rename to "android.net.action.CLEAR_DNS_CACHE" because of lint
      suggestion.
    frameworks/base/packages/Connectivity/framework/src/android/net/
    ConnectivityManager.java:449: error: Inconsistent action value;
    expected `android.net.action.CLEAR_DNS_CACHE`, was
    `android.intent.action.CLEAR_DNS_CACHE` [ActionValue]
    
    Bug: 183937999
    Test: atest FrameworksNetTests
    Test: atest ActivityTaskManagerServiceTests
    Test: atest android.permission2.cts.PermissionPolicyTest
    Test: atest CtsNetTestCases
    Change-Id: Iae8aa0ba10dfc7581f0cfaab82643edbee789e2f
    
  - UWB: Remove Unused RTSU Constants
    
    Bug: 184691885
    Test: Build
    Signed-off-by: Harpreet Eli Sangha <eliptus@google.com>
    Change-Id: I92a3b5ec96bd152544b9b46dfacfdd970e5b7d1f