Update git submodules
* Update platform/external/oss-fuzz from branch 'master'
  to b002bcd93920a7e2e9f8545043357a394202650d
  - Merge "Upgrade oss-fuzz to 0ca53f3c94f36276fa53fb0cdd62ec87677ae6be"
  - Upgrade oss-fuzz to 0ca53f3c94f36276fa53fb0cdd62ec87677ae6be
    
    Test: None
    Change-Id: I7216d4f3fa5d16e198fd08be95770c365f4ed25d
    
  - [infra] Update binaries in the base-runner image (#3065). (#3066)
    
    
  - wireshark: fix build by adding ares dependency (#3064)
    
    Since wireshark commit v3.3.0rc0-15-g451a241e50, c-ares became a
    required dependency.
    
    Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=19095
  - Enable UBSan builtin, null, returns-nonnull-attribute, and unreachable checks. (#3062)
    
    
  - Revert "Enable UBSan's builtin, null, and unreachable checks. (#3057)" (#3061)
    
    This reverts commit 146316b7055186bdb91a2ed6ef37d445364cd770.
  - Install clang using git (#3060)
    
    
    
  - [cras] fix build (#3055)
    
    We now use some rust code in CRAS, fix the fuzzer build so that code is
    compiled as well.
  - Enable UBSan's builtin, null, and unreachable checks. (#3057)
    
    
  - [proxygen] Fix build by importing `fmt` in Dockerfile (#3056)
    
    * [proxygen] Fix build by importing `fmt` in Dockerfile
    
    I have not yet tested this locally as my current laptop doesn't have a set up environment. Putting this up to see if Travis finds a green build, otherwise I'll set this up tomorrow.
    
    * [proxygen] Fix path to fmt tarball
    
  - expat: Use upstream fuzzer build (retain dictionaries) (#3041)
    
    
  - Integration of Racket (#3054)
    
    * Integration of Racket
    
    * Remove experimental flags
    
  - [njs] Reverting --debug=YES introduced in c16cf5a2. (#3053)
    
    As it changed reproducibility of existing issues.
  - Fix fuzz targets in mysql (#3052)
    
    
  - solidity: Upgrade evmone to v0.3.0 to fix build failure (#3048)
    
    
  - [njs] Expanded auto_ccs. (#3051)
    
    
  - fix link failure with libtiff (#3050)
    
    * fix link failure with libtiff
    
    The fuzz targets were failing to link with:
    
    ```
    Step #4: /work/lib/libtiff.a(tif_lzma.o): In function `TIFFInitLZMA':
    Step #4: /src/libtiff/libtiff/tif_lzma.c:465: undefined reference to
    `lzma_lzma_preset'
    ```
    
    It looks like it's become necessary to explicitly link -llzma, see:
    
    https://gitlab.com/libtiff/libtiff/commit/4159bda6db2f8cf8e848d8095b5d37d49ba67a10
    
    oss-fuzz issue:
    
    https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=18928#c4
    
    Thanks to @lovell.
    
    * pin libtiff to 4.1.0
    
    It seems there's an issue with git master libtiff -- it fails to link on
    systems without lzma installed.
    
    For now, pin to 4.1.0, the current stable version.
    
    * explicitly disable lzma
    
    lzma detection in libtiff seems to be broken as of 20 nov. Disable
    explicitly.
    
  - Pre-compile honggfuzz (#3045)
    
    
    
  - [njs] Moving fuzzing target upstream. (#3047)
    
    
  - mysql fuzz targets use custom rm and cp (#3046)
    
    
  - Update WABT primary contact (#3044)
    
    The previous address was an alias for a mailing list, not an actual account. Changing the contact to @dschuff as requested in https://github.com/WebAssembly/wabt/issues/1212#issuecomment-555117572.
  - [libheif] Also run fuzzers on i386 (#3042)
    
    * Explicitly link against "$LIB_FUZZING_ENGINE" in libFuzzer mode.
    
    Previously was linking against "-lFuzzingEngine" which doesn't work
    on i386 builds.
    
    * Also run libheif fuzzers on i386.
    
  - [postgis] fix build (#3038)
    
    Upstream enables link time optimization that breaks fuzzers build. Link time optimization is automatically disabled in --enable-debug mode.
  - [njs] Fix broken build. (#3036)
    
    
  - Fixes ecc-diff-fuzzer build (#3029)
    
    
  - Update Osquery Contacts (#3016)
    
    * Update Osquery Contacts
    
  - [wabt] Add project (#3035)
    
    
  - Update project.yaml
  - [bignum-fuzzer] Add Richard of OpenSSL (#3034)
    
    
  - adjust wolfSSL emails listed in cryptofuzz project (#3032)
    
    
  - remove libunwind and libblocksruntime from base-runner. (#3031)
    
    Fixes #2947.
  - Add optimization flags to honggfuzz compilation. (#3030)
    
    
  - [bignum-fuzzer] Disable Rust (#3028)
    
    
  - Add libcacard project (#3019)
    
    
  - Add additional build deps for honggfuzz. (#3026)
    
    These will be statically linked into the hongfuzz binary.
    
  - Add myself to envoy project autoccs. (#3024)
    
    
  - [simdjson] repoint to upstream repository (#3022)
    
    
  - [json-iterator] Adds golang project json-iterator (#2989)
    
    
  - [cryptofuzz] ARM mbed crypto (#3021)
    
    
  - [libssh] Fix building libssh as a static library (#3020)
    
    
  - do not analyze too long inpus for gnupg list fuzz target (#3007)
    
    
  - Add wavpack to oss-fuzz (#3017)
    
    
  - honggfuzz: Include libhfcommon in $LIB_FUZZING_ENGINE. (#3011)
    
    
  - Debugs mysql server fuzz targets (#3012)
    
    
  - [simdjson] move the build script into the simdjson repo (#3013)
    
    this means it can be maintained and bugfixed upstream
  - Remove unused aosp project. (#3009)
    
    
  - [cryptofuzz] Enable wolfCrypt 32 bit builds (#3008)
    
    
  - Get run_minijail working for i386 (#2997)
    
    
  - Speculative fix for ndpi broken build
  - [LibRawSpeed] Pull in newer cmake to fix the build (#3003)
    
    As per https://apt.kitware.com/
  - [cryptofuzz] wolfCrypt (#3004)
    
    
    
  - Update Dockerfile (#3005)
    
    gogs is the old url that redirects to new gitea url
  - [simdjson] initial integration (#2999)
    
    * [simdjson] initial attempt
    
    * fix name mismatch
    
    * fix bad path
    
    * add corpus build script
    
    * drop setting the c++ standard
    
  - mruby: Move LPM build to dockerfile (#3000)
    
    
  - [osquery][lz4][zstd] Add more fb auto_ccs (#2998)
    
    Cc: mhl@fb.com
  - Adds gonids project (#2995)
    
    
  - [ndpi] Integrate NDPI with pcap (#2994)
    
    
  - Add a new fuzz target to osquery for sql queries, and add dictionaries and seed corpuses for both targets. (#2992)
    
    
  - iroha: vcpkg script migration step 1 (#2986)
    
    
  - Limits input size for gnupg list fuzz target (#2987)
    
    
  - [libxls] Build requires autoconf-archive (#2988)
    
    Fixes oss-fuzz/18609
  - [ffmpeg] Drop mesa/drm, it does not build due to changes to its build system (#2983)
    
    Fixes issue 18386
    
    Signed-off-by: Michael Niedermayer <michaelni@gmx.at>
  - [cjson] Add Alanscut to auto_ccs (#2981)
    
    

* Update platform/superproject from branch 'master'
  to f3e81ca94807c47ad8c206c61be0c840bbab7c7b
  - Update git submodules
    
    * Update external/oss-fuzz from branch 'master'
      to b002bcd93920a7e2e9f8545043357a394202650d
      - Merge "Upgrade oss-fuzz to 0ca53f3c94f36276fa53fb0cdd62ec87677ae6be"
      - Upgrade oss-fuzz to 0ca53f3c94f36276fa53fb0cdd62ec87677ae6be
        
        Test: None
        Change-Id: I7216d4f3fa5d16e198fd08be95770c365f4ed25d
        
      - [infra] Update binaries in the base-runner image (#3065). (#3066)
        
        
      - wireshark: fix build by adding ares dependency (#3064)
        
        Since wireshark commit v3.3.0rc0-15-g451a241e50, c-ares became a
        required dependency.
        
        Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=19095
      - Enable UBSan builtin, null, returns-nonnull-attribute, and unreachable checks. (#3062)
        
        
      - Revert "Enable UBSan's builtin, null, and unreachable checks. (#3057)" (#3061)
        
        This reverts commit 146316b7055186bdb91a2ed6ef37d445364cd770.
      - Install clang using git (#3060)
        
        
        
      - [cras] fix build (#3055)
        
        We now use some rust code in CRAS, fix the fuzzer build so that code is
        compiled as well.
      - Enable UBSan's builtin, null, and unreachable checks. (#3057)
        
        
      - [proxygen] Fix build by importing `fmt` in Dockerfile (#3056)
        
        * [proxygen] Fix build by importing `fmt` in Dockerfile
        
        I have not yet tested this locally as my current laptop doesn't have a set up environment. Putting this up to see if Travis finds a green build, otherwise I'll set this up tomorrow.
        
        * [proxygen] Fix path to fmt tarball
        
      - expat: Use upstream fuzzer build (retain dictionaries) (#3041)
        
        
      - Integration of Racket (#3054)
        
        * Integration of Racket
        
        * Remove experimental flags
        
      - [njs] Reverting --debug=YES introduced in c16cf5a2. (#3053)
        
        As it changed reproducibility of existing issues.
      - Fix fuzz targets in mysql (#3052)
        
        
      - solidity: Upgrade evmone to v0.3.0 to fix build failure (#3048)
        
        
      - [njs] Expanded auto_ccs. (#3051)
        
        
      - fix link failure with libtiff (#3050)
        
        * fix link failure with libtiff
        
        The fuzz targets were failing to link with:
        
        ```
        Step #4: /work/lib/libtiff.a(tif_lzma.o): In function `TIFFInitLZMA':
        Step #4: /src/libtiff/libtiff/tif_lzma.c:465: undefined reference to
        `lzma_lzma_preset'
        ```
        
        It looks like it's become necessary to explicitly link -llzma, see:
        
        https://gitlab.com/libtiff/libtiff/commit/4159bda6db2f8cf8e848d8095b5d37d49ba67a10
        
        oss-fuzz issue:
        
        https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=18928#c4
        
        Thanks to @lovell.
        
        * pin libtiff to 4.1.0
        
        It seems there's an issue with git master libtiff -- it fails to link on
        systems without lzma installed.
        
        For now, pin to 4.1.0, the current stable version.
        
        * explicitly disable lzma
        
        lzma detection in libtiff seems to be broken as of 20 nov. Disable
        explicitly.
        
      - Pre-compile honggfuzz (#3045)
        
        
        
      - [njs] Moving fuzzing target upstream. (#3047)
        
        
      - mysql fuzz targets use custom rm and cp (#3046)
        
        
      - Update WABT primary contact (#3044)
        
        The previous address was an alias for a mailing list, not an actual account. Changing the contact to @dschuff as requested in https://github.com/WebAssembly/wabt/issues/1212#issuecomment-555117572.
      - [libheif] Also run fuzzers on i386 (#3042)
        
        * Explicitly link against "$LIB_FUZZING_ENGINE" in libFuzzer mode.
        
        Previously was linking against "-lFuzzingEngine" which doesn't work
        on i386 builds.
        
        * Also run libheif fuzzers on i386.
        
      - [postgis] fix build (#3038)
        
        Upstream enables link time optimization that breaks fuzzers build. Link time optimization is automatically disabled in --enable-debug mode.
      - [njs] Fix broken build. (#3036)
        
        
      - Fixes ecc-diff-fuzzer build (#3029)
        
        
      - Update Osquery Contacts (#3016)
        
        * Update Osquery Contacts
        
      - [wabt] Add project (#3035)
        
        
      - Update project.yaml
      - [bignum-fuzzer] Add Richard of OpenSSL (#3034)
        
        
      - adjust wolfSSL emails listed in cryptofuzz project (#3032)
        
        
      - remove libunwind and libblocksruntime from base-runner. (#3031)
        
        Fixes #2947.
      - Add optimization flags to honggfuzz compilation. (#3030)
        
        
      - [bignum-fuzzer] Disable Rust (#3028)
        
        
      - Add libcacard project (#3019)
        
        
      - Add additional build deps for honggfuzz. (#3026)
        
        These will be statically linked into the hongfuzz binary.
        
      - Add myself to envoy project autoccs. (#3024)
        
        
      - [simdjson] repoint to upstream repository (#3022)
        
        
      - [json-iterator] Adds golang project json-iterator (#2989)
        
        
      - [cryptofuzz] ARM mbed crypto (#3021)
        
        
      - [libssh] Fix building libssh as a static library (#3020)
        
        
      - do not analyze too long inpus for gnupg list fuzz target (#3007)
        
        
      - Add wavpack to oss-fuzz (#3017)
        
        
      - honggfuzz: Include libhfcommon in $LIB_FUZZING_ENGINE. (#3011)
        
        
      - Debugs mysql server fuzz targets (#3012)
        
        
      - [simdjson] move the build script into the simdjson repo (#3013)
        
        this means it can be maintained and bugfixed upstream
      - Remove unused aosp project. (#3009)
        
        
      - [cryptofuzz] Enable wolfCrypt 32 bit builds (#3008)
        
        
      - Get run_minijail working for i386 (#2997)
        
        
      - Speculative fix for ndpi broken build
      - [LibRawSpeed] Pull in newer cmake to fix the build (#3003)
        
        As per https://apt.kitware.com/
      - [cryptofuzz] wolfCrypt (#3004)
        
        
        
      - Update Dockerfile (#3005)
        
        gogs is the old url that redirects to new gitea url
      - [simdjson] initial integration (#2999)
        
        * [simdjson] initial attempt
        
        * fix name mismatch
        
        * fix bad path
        
        * add corpus build script
        
        * drop setting the c++ standard
        
      - mruby: Move LPM build to dockerfile (#3000)
        
        
      - [osquery][lz4][zstd] Add more fb auto_ccs (#2998)
        
        Cc: mhl@fb.com
      - Adds gonids project (#2995)
        
        
      - [ndpi] Integrate NDPI with pcap (#2994)
        
        
      - Add a new fuzz target to osquery for sql queries, and add dictionaries and seed corpuses for both targets. (#2992)
        
        
      - iroha: vcpkg script migration step 1 (#2986)
        
        
      - Limits input size for gnupg list fuzz target (#2987)
        
        
      - [libxls] Build requires autoconf-archive (#2988)
        
        Fixes oss-fuzz/18609
      - [ffmpeg] Drop mesa/drm, it does not build due to changes to its build system (#2983)
        
        Fixes issue 18386
        
        Signed-off-by: Michael Niedermayer <michaelni@gmx.at>
      - [cjson] Add Alanscut to auto_ccs (#2981)