Update git submodules
* Update platform/external/autotest from branch 'master'
  to 52906b22fdd2604b19f9eeaf91d3890a67cb522e
  - network_WiFi_MalformedProbeResp: fix an unhandled exception
    am: 900aaff6d5
    
    Change-Id: Ibea373626e86376b26d408168fe67d304679acce
    
  - network_WiFi_MalformedProbeResp: fix an unhandled exception
    
    The following failure message, triggered by an unhandled exception,
    isn't very helpful:
    
      File "/usr/local/autotest/server/site_tests/network_WiFi_MalformedProbeResp/network_WiFi_MalformedProbeResp.py", line 63, in run_once
          for bss in bss_list:
      TypeError: 'NoneType' object is not iterable
    
    This CL updates network_WiFi_MalformedProbeResp to handle the absence of
    scan result more gracefully, so that a better error message like "Client
    failed to receive probe responses" can be reported instead.
    
    BUG=chromium:868503
    TEST=Run network_WiFi_MalformedProbeResp.
    
    Change-Id: If2364d3d5417fcb5900abfd85593777a61b594e7
    Reviewed-on: https://chromium-review.googlesource.com/1357250
    Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
    Tested-by: Ben Chan <benchan@chromium.org>
    Reviewed-by: Brian Norris <briannorris@chromium.org>
    

* Update platform/superproject from branch 'master'
  to 0b188baf71bcbae235fc3d3fbed764db8da4a4b1
  - Update git submodules
    
    * Update external/autotest from branch 'master'
      to 52906b22fdd2604b19f9eeaf91d3890a67cb522e
      - network_WiFi_MalformedProbeResp: fix an unhandled exception
        am: 900aaff6d5
        
        Change-Id: Ibea373626e86376b26d408168fe67d304679acce
        
      - network_WiFi_MalformedProbeResp: fix an unhandled exception
        
        The following failure message, triggered by an unhandled exception,
        isn't very helpful:
        
          File "/usr/local/autotest/server/site_tests/network_WiFi_MalformedProbeResp/network_WiFi_MalformedProbeResp.py", line 63, in run_once
              for bss in bss_list:
          TypeError: 'NoneType' object is not iterable
        
        This CL updates network_WiFi_MalformedProbeResp to handle the absence of
        scan result more gracefully, so that a better error message like "Client
        failed to receive probe responses" can be reported instead.
        
        BUG=chromium:868503
        TEST=Run network_WiFi_MalformedProbeResp.
        
        Change-Id: If2364d3d5417fcb5900abfd85593777a61b594e7
        Reviewed-on: https://chromium-review.googlesource.com/1357250
        Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
        Tested-by: Ben Chan <benchan@chromium.org>
        Reviewed-by: Brian Norris <briannorris@chromium.org>