Update git submodules
* Update platform/prebuilts/asuite from branch 'master'
  to 5acfa0202cb1bc86503d0fc4afd9310c7cdaadac
  - Merge "Revert "Atest: prebuilt from aosp_cf_x86_phone-userdebug.""
  - Revert "Atest: prebuilt from aosp_cf_x86_phone-userdebug."
    
    This reverts commit a766481a2ca7eb09b3909ca62e9ae8a31b5578bd.
    
    Reason for revert: Due to some user's environment will get
                       ImportError: No module named protobuf,
                       roll back it first.
    
    Change-Id: Ic72088fcfadbfa2ce2a1055cb080576d9fd6f3b9
    

* Update platform/superproject from branch 'master'
  to 5daa9dacc91b5466a06291cdd66465825d9eb6e0
  - Update git submodules
    
    * Update prebuilts/asuite from branch 'master'
      to 5acfa0202cb1bc86503d0fc4afd9310c7cdaadac
      - Merge "Revert "Atest: prebuilt from aosp_cf_x86_phone-userdebug.""
      - Revert "Atest: prebuilt from aosp_cf_x86_phone-userdebug."
        
        This reverts commit a766481a2ca7eb09b3909ca62e9ae8a31b5578bd.
        
        Reason for revert: Due to some user's environment will get
                           ImportError: No module named protobuf,
                           roll back it first.
        
        Change-Id: Ic72088fcfadbfa2ce2a1055cb080576d9fd6f3b9