Update git submodules
* Update platform/external/kmod from branch 'master'
  to 83d182a671df25de32b815f1f0461af6e86d215c
  - Upgrade kmod to v28
    
    Test: make
    Change-Id: Ib72ea77e13d0d8621347a240715db48d918481d8
    
  - kmod 28
    
  - build: add comment with rules for libtool version update
    
  - build: fix distcheck due to missing zstd
    
    Enable zstd since it's used in the testsuite.
    
  - testsuite: add test for empty modules.builtin.aliases.bin
    
  - shared: fix UNIQ definition
    
    We need a macro indirection for UNIQ to work. Otherwise it won't be
    unique at all since it will just append "UNIQ" to the name:
    
    In file included from testsuite/test-init.c:30:
    
    testsuite/testsuite.h:142:27: error: redefinition of ‘stest_load_resourcesUNIQ’
    
  - depmod: unconditionally write builtin.alias.bin
    
    The file is always created and unless we return an error, the temporary
    file is renamed to its final destination. All other places write the
    index without checking if the index is empty, so just do the same.
    
    Reported-by: Joe Buehler <aspam@cox.net>
    
  - ci: remove semaphoreci
    
    It's currently failing and we are already covered by travis-ci.
    
  - ci: update travis distro
    
    Don't bother with gcc 4.8 vs 4.9, just use the latest one for the
    distro. Update travis to ubuntu 20.04 so we can get current
    dependencies.
    
  - NEWS: fix typo
    
  - libkmod: kmod_log_null: qualify ctx argument as const
    
    kmod_log_null() does not change ctx (does nothing).
    
    Fix warnings
    
    In file included from libkmod/libkmod-index.c:33:
    libkmod/libkmod-index.c: In function ‘index_mm_open’:
    libkmod/libkmod-index.c:757:6: warning: passing argument 1 of ‘kmod_log_null’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
      757 |  DBG(ctx, "file=%s\n", filename);
    
    Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
    
  - depmod: output_builtin_alias_bin: free idx on error path
    
    idx is allocated in the beginning but it's not freed if there is
    a failure after the allocation.
    
    Change the error path: return immediately if idx allocation fails
    and then free it in both success and error path at the end.
    
    Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
    
  - libkmod: kmod_builtin_get_modinfo: free modinfo on error
    
    The function allocates array but on building it if get_string()
    fails it returns the error leaving the array allocated. The caller
    does not care about it in error case either.
    
    Free it to fix memory leak.
    
    Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
    
  - Mark ab/6881855 as merged
    
    Bug: 172690556
    Change-Id: I09532d6bfe66fdd21aa6b9d4120352e2083982b2
    
  - Upgrade kmod to v27 am: f9d235a152
    
    Original change: https://android-review.googlesource.com/c/platform/external/kmod/+/1479351
    
    Change-Id: I6ea209409fd6714a34de01d9b49cf44be22b7fdb
    
  - man: fix typo
    
  - testsuite: add test for zstd-compressed module
    
    I took away one module from the gzip-compressed modules for this purpose.
    
    Signed-off-by: Torge Matthies <openglfreak@googlemail.com>
    
  - add Zstandard compression support
    
    I changed the style of the hackargs variable in autogen.sh to multiline
    because said line was becoming a bit long with the new --with-zstd arg
    added.
    
    A previous version of this patch has been running on my two Arch Linux
    installations (with an accompanying mkinitcpio patch) for several months
    over many kernel updates without any issues.
    Any additional testing and/or patch review would of course be appreciated.
    
    Signed-off-by: Torge Matthies <openglfreak@googlemail.com>
    
  - Add license type: GPL+LGPL are RESTRICTED licenses am: 5e3bde0f8e am: e62d44322d am: 07b5cdfc6f am: 3045ec0d51
    
    Change-Id: I08d4eccab1feee54b774047102b44dba8f011ffb
    
  - testsuite: add check for kmod_load_resources
    
    Make sure we can call kmod_load_resources when we do have all the
    mandatory indexes in place.
    
  - libkmod: allow modules.alias.builtin to be optional
    
  - libkmod: fix return error when opening index
    
    When calling kmod_load_resources() we could end up getting a bogus
    return value -ENOMEM due to several other reasons, like the index not
    existing. Change index_mm_open() to propagate the failure reason so we
    can take actions on it or return to the caller.
    
  - libkmod: simplify lookup when builtin.modinfo.bin file is missing
    
    When we try to lookup a module and builtin.modinfo.bin is missing, we
    would do the right thing because the caller was replacing the return
    code with 0 (and the list was not modified).
    
    Make it simpler by allowing the caller to check and differentiate the
    errors between module not found and index not found.
    
  - depmod: do not output .bin to stdout
    
    index_write() relies on fseek/ftell to manage the position to which we
    are write and thus needs the file stream to support it.
    
    Right now when trying to write the index to stdout we fail with:
    
    	depmod: tools/depmod.c:416: index_write: Assertion `initial_offset >= 0' failed.
    	Aborted (core dumped)
    
    We have no interest in outputting our index to stdout, so just skip it
    like is done with other indexes.
    
    While at it, add/remove some newlines to improve readability.
    
    Reported-by: Yanko Kaneti <yaneti@declera.com>
    Fix: b866b2165ae6 ("Lookup aliases in the modules.builtin.modinfo")
    
  - testsuite: check for ill-formed kcmdline
    
    Commit ca3bf5d47cec ("iommu/amd: Introduces ivrs_acpihid kernel parameter")
    in the kernel introduced an ill-formed kernel parameter, ivrs_acpihid.
    The problem is that it may have a dot on the key side:
    "ivrs_acpihid[00:14.5]=AMD0020:0". This could potentially trip our
    parser of module options, but right now it's working as intended: the
    only thing that happens is that after deciding "ivrs_acpihid[00:14" is a
    module name, it will fail the underscores() routine and the option will
    be ignored from the kmod pov (not kernel's pov since that driver parsers
    the kernel command line by itself).
    
  - libkmod: ignore kcmdline option if we fail to parse modname
    
    The error message is saying we are ignoring the option on the kernel
    command line, so just do it.
    
  - gitignore: ignore .cache.mk when building modules
    
  - gitignore: ignore release files
    

* Update platform/superproject from branch 'master'
  to cb0f1c0fa998f01934b67689a954c1ac00cf84e1
  - Update git submodules
    
    * Update external/kmod from branch 'master'
      to 83d182a671df25de32b815f1f0461af6e86d215c
      - Upgrade kmod to v28
        
        Test: make
        Change-Id: Ib72ea77e13d0d8621347a240715db48d918481d8
        
      - kmod 28
        
      - build: add comment with rules for libtool version update
        
      - build: fix distcheck due to missing zstd
        
        Enable zstd since it's used in the testsuite.
        
      - testsuite: add test for empty modules.builtin.aliases.bin
        
      - shared: fix UNIQ definition
        
        We need a macro indirection for UNIQ to work. Otherwise it won't be
        unique at all since it will just append "UNIQ" to the name:
        
        In file included from testsuite/test-init.c:30:
        
        testsuite/testsuite.h:142:27: error: redefinition of ‘stest_load_resourcesUNIQ’
        
      - depmod: unconditionally write builtin.alias.bin
        
        The file is always created and unless we return an error, the temporary
        file is renamed to its final destination. All other places write the
        index without checking if the index is empty, so just do the same.
        
        Reported-by: Joe Buehler <aspam@cox.net>
        
      - ci: remove semaphoreci
        
        It's currently failing and we are already covered by travis-ci.
        
      - ci: update travis distro
        
        Don't bother with gcc 4.8 vs 4.9, just use the latest one for the
        distro. Update travis to ubuntu 20.04 so we can get current
        dependencies.
        
      - NEWS: fix typo
        
      - libkmod: kmod_log_null: qualify ctx argument as const
        
        kmod_log_null() does not change ctx (does nothing).
        
        Fix warnings
        
        In file included from libkmod/libkmod-index.c:33:
        libkmod/libkmod-index.c: In function ‘index_mm_open’:
        libkmod/libkmod-index.c:757:6: warning: passing argument 1 of ‘kmod_log_null’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
          757 |  DBG(ctx, "file=%s\n", filename);
        
        Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
        
      - depmod: output_builtin_alias_bin: free idx on error path
        
        idx is allocated in the beginning but it's not freed if there is
        a failure after the allocation.
        
        Change the error path: return immediately if idx allocation fails
        and then free it in both success and error path at the end.
        
        Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
        
      - libkmod: kmod_builtin_get_modinfo: free modinfo on error
        
        The function allocates array but on building it if get_string()
        fails it returns the error leaving the array allocated. The caller
        does not care about it in error case either.
        
        Free it to fix memory leak.
        
        Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
        
      - man: fix typo
        
      - testsuite: add test for zstd-compressed module
        
        I took away one module from the gzip-compressed modules for this purpose.
        
        Signed-off-by: Torge Matthies <openglfreak@googlemail.com>
        
      - add Zstandard compression support
        
        I changed the style of the hackargs variable in autogen.sh to multiline
        because said line was becoming a bit long with the new --with-zstd arg
        added.
        
        A previous version of this patch has been running on my two Arch Linux
        installations (with an accompanying mkinitcpio patch) for several months
        over many kernel updates without any issues.
        Any additional testing and/or patch review would of course be appreciated.
        
        Signed-off-by: Torge Matthies <openglfreak@googlemail.com>
        
      - testsuite: add check for kmod_load_resources
        
        Make sure we can call kmod_load_resources when we do have all the
        mandatory indexes in place.
        
      - libkmod: allow modules.alias.builtin to be optional
        
      - libkmod: fix return error when opening index
        
        When calling kmod_load_resources() we could end up getting a bogus
        return value -ENOMEM due to several other reasons, like the index not
        existing. Change index_mm_open() to propagate the failure reason so we
        can take actions on it or return to the caller.
        
      - libkmod: simplify lookup when builtin.modinfo.bin file is missing
        
        When we try to lookup a module and builtin.modinfo.bin is missing, we
        would do the right thing because the caller was replacing the return
        code with 0 (and the list was not modified).
        
        Make it simpler by allowing the caller to check and differentiate the
        errors between module not found and index not found.
        
      - depmod: do not output .bin to stdout
        
        index_write() relies on fseek/ftell to manage the position to which we
        are write and thus needs the file stream to support it.
        
        Right now when trying to write the index to stdout we fail with:
        
        	depmod: tools/depmod.c:416: index_write: Assertion `initial_offset >= 0' failed.
        	Aborted (core dumped)
        
        We have no interest in outputting our index to stdout, so just skip it
        like is done with other indexes.
        
        While at it, add/remove some newlines to improve readability.
        
        Reported-by: Yanko Kaneti <yaneti@declera.com>
        Fix: b866b2165ae6 ("Lookup aliases in the modules.builtin.modinfo")
        
      - testsuite: check for ill-formed kcmdline
        
        Commit ca3bf5d47cec ("iommu/amd: Introduces ivrs_acpihid kernel parameter")
        in the kernel introduced an ill-formed kernel parameter, ivrs_acpihid.
        The problem is that it may have a dot on the key side:
        "ivrs_acpihid[00:14.5]=AMD0020:0". This could potentially trip our
        parser of module options, but right now it's working as intended: the
        only thing that happens is that after deciding "ivrs_acpihid[00:14" is a
        module name, it will fail the underscores() routine and the option will
        be ignored from the kmod pov (not kernel's pov since that driver parsers
        the kernel command line by itself).
        
      - libkmod: ignore kcmdline option if we fail to parse modname
        
        The error message is saying we are ignoring the option on the kernel
        command line, so just do it.
        
      - gitignore: ignore .cache.mk when building modules
        
      - gitignore: ignore release files