Update git submodules
* Update device/google/cuttlefish from branch 'master'
  to a333d3af92180b85a8ecd1c8a4d3b7933fdd55ab
  - Reland: assemble_cvd: Use toybox cpio to unpack vendor ramdisk
    
    Since GNU cpio could break the
    "while cpio -idu; do :;done <cpio.concatenated" loop due to its buffered
    IO reading too much of the input.
    
    Use "mkbootfs" to pack ramdisk as it yields more stable output than
    "find | cpio". The archive generated by "mkbootfs" has its entry sorted,
    assigned stable inode number, cleared mtime, uid and gid.
    
    Also format some lines of code to make clang-format happy.
    
    Bug: 185883642
    Bug: 173134558
    Test: launch_cvd -kernel_path kernel && check ~/cuttlefish_assembly
    Test: Run launch_cvd again and check that the repacked
      stripped_ramdisk.cpio is deterministic.
    Test: adb reboot recovery
    Change-Id: Ie9f17787017e4e6a73038c98688a5eb0a1fdbf56
    

* Update platform/external/toybox from branch 'master'
  to 2d03a5e677e528459785a1d8273a63f0fe00837c
  - Fix linux_bionic build
    
    After adding "toybox" to cvd-host_package.tar.gz,
    aosp_cf_arm64_phone-userdebug failed to build with error:
    
      In file included from external/toybox/lib/args.c:10:
      external/toybox/toys.h:8:10: fatal error: 'generated/config.h' file
      not found
      #include "generated/config.h"
               ^~~~~~~~~~~~~~~~~~~~
      1 error generated.
    
    This is because toybox is not configured to be built on linux_bionic
    host, and aosp_cf_arm64_phone is trying to build the HOST_CROSS variant
    of toybox, which is arm64 linux_bionic.
    
    Bug: 185883642
    Test: lunch aosp_cf_arm64_phone-userdebug && m
    Change-Id: I64418fb5f88f8a8b8b7e6905b58cc1f7e68ab2e8