Update git submodules
* Update platform/superproject from branch 'master'
  to 1334f61a81bb0018d6a4f50387f7de9bf5dc8975
  - Update git submodules
    
    * Update tools/asuite from branch 'master'
      to d9b5d49a41d2478d6701b18afa34fd42516e007c
      - AIDEGen: Fix 'cannot find module_bp_java_deps.json' issue.
        
        build/make/core/main.mk:13: Calling make directly is no longer
        supported. Because build system no longer supports make directly,
        we change to use atest build method to generate the
        module_bp_java_deps.json.
        
        Bug: 138129456
        Test: 1. m clean && m aidegen
                 cd ./tools/tradefederation/core/
                 aidegen-dev
                 IntelliJ will be launched to open core project.
              2. aidegen-dev -a
                 IntelliJ will be launched to open the whole tree
                 as a project.
        
        Change-Id: I2887886aefb97b9611b6654a978e061746859439
        

* Update platform/tools/asuite from branch 'master'
  to d9b5d49a41d2478d6701b18afa34fd42516e007c
  - AIDEGen: Fix 'cannot find module_bp_java_deps.json' issue.
    
    build/make/core/main.mk:13: Calling make directly is no longer
    supported. Because build system no longer supports make directly,
    we change to use atest build method to generate the
    module_bp_java_deps.json.
    
    Bug: 138129456
    Test: 1. m clean && m aidegen
             cd ./tools/tradefederation/core/
             aidegen-dev
             IntelliJ will be launched to open core project.
          2. aidegen-dev -a
             IntelliJ will be launched to open the whole tree
             as a project.
    
    Change-Id: I2887886aefb97b9611b6654a978e061746859439