Update git submodules
* Update platform/cts from branch 'master'
  to e8fc1139cb4879052aeb4d9511b90f5c07defdbb
  - Merge "pass an empty file_contexts file to secilc"
  - pass an empty file_contexts file to secilc
    
    The host executable secilc will create it's own file_contexts file
    if one is not passed to it. For some reason, this has started to fail
    our test infra. Since I am unable to reproduce the failure
    locally, see if first creating the temp file and passing it to
    secilc fixes the following test error:
    
    junit.framework.AssertionFailedError: Failed to open file_contexts file
    
    	at junit.framework.Assert.fail(Assert.java:57)
    	at junit.framework.Assert.assertTrue(Assert.java:22)
    	at junit.framework.TestCase.assertTrue(TestCase.java:192)
    	at android.security.cts.SELinuxHostTest.buildSystemPolicy(SELinuxHostTest.java:261)
    
    Bug: 182008549
    Test: Have Treehugger run these tests since I am unable to reproduce the
    failure locally.
    
    Change-Id: Ibc68175701e882e9dbfc16d36ad587b62127dc71