Update git submodules
* Update platform/packages/apps/Gallery2 from branch 'master'
  to 6b26017b7291ab2077acadf8807056870992bc09
  - Merge "Revert "SYSTEM/app/Gallery2/Gallery2.apk app - update the version to target P (28) or higher.""
  - Revert "SYSTEM/app/Gallery2/Gallery2.apk app - update the version to target P (28) or higher."
    
    This reverts commit 7ff2227efdca7c79eafbb2713dffa2e0ac06bab4.
    
    Reason for revert: b/122473906 
      java.lang.AssertionError: Error details:
      java.lang.RuntimeException: Unable to start receiver com.android.gallery3d.app.PackagesMonitor: java.lang.IllegalStateException: Not allowed to start service Intent { act=android.intent.action.PACKAGE_CHANGED dat=package:com.android.nfc flg=0x5000010 cmp=com.android.gallery3d/.app.PackagesMonitor$AsyncService (has extras) }: app is in background uid UidRecord{bf15789 u0a43 RCVR idle change:uncached procs:1 seq(0,0,0)}
    	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3520)system_app_crash: Process: com.android.gallery3d
    
    Change-Id: Ib396fb544eb85d91dbc75ef4a71c4e99d6f19998
    

* Update platform/superproject from branch 'master'
  to b9a342570668714aec621ea6f9f15af719bf16d8
  - Update git submodules
    
    * Update packages/apps/Gallery2 from branch 'master'
      to 6b26017b7291ab2077acadf8807056870992bc09
      - Merge "Revert "SYSTEM/app/Gallery2/Gallery2.apk app - update the version to target P (28) or higher.""
      - Revert "SYSTEM/app/Gallery2/Gallery2.apk app - update the version to target P (28) or higher."
        
        This reverts commit 7ff2227efdca7c79eafbb2713dffa2e0ac06bab4.
        
        Reason for revert: b/122473906 
          java.lang.AssertionError: Error details:
          java.lang.RuntimeException: Unable to start receiver com.android.gallery3d.app.PackagesMonitor: java.lang.IllegalStateException: Not allowed to start service Intent { act=android.intent.action.PACKAGE_CHANGED dat=package:com.android.nfc flg=0x5000010 cmp=com.android.gallery3d/.app.PackagesMonitor$AsyncService (has extras) }: app is in background uid UidRecord{bf15789 u0a43 RCVR idle change:uncached procs:1 seq(0,0,0)}
        	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3520)system_app_crash: Process: com.android.gallery3d
        
        Change-Id: Ib396fb544eb85d91dbc75ef4a71c4e99d6f19998