Update git submodules
* Update platform/external/f2fs-tools from branch 'master'
  to c5e1fc00dddcca3be816d170a1020048af354ff4
  - Merge remote-tracking branch 'aosp/upstream-master' into aosp
    
    * aosp/upstream-master:
      fsck.f2fs: allow fsck to fix issues with online resize due to SPO
      fsck.f2fs: account COMPRESS_ADDR as reserved blocks correctly
      f2fs_io: support compress blocks ioctls
      fsck.f2fs: report real wall time
      Include private/fs_config.h directly when needed
      f2fs-tools: Casefolded Encryption support
      fsck.f2fs: allow --dry-run to check readonly mounted fs
    
    Signed-off-by: Jaegeuk Kim <jaegeuk@google.com>
    Change-Id: Id0c5f82cdd29ca8f3684d65cbfa3e4e853785590
    
  - fsck.f2fs: allow fsck to fix issues with online resize due to SPO
    
    Add support for new CP flag CP_RESIZEFS_FLAG set during online
    resize FS. If SPO happens after SB is updated but CP isn't, then
    allow fsck to fix it.
    
    The fsck errors without this fix -
        Info: CKPT version = 6ed7bccb
                Wrong user_block_count(2233856)
        [f2fs_do_mount:3365] Checkpoint is polluted
    
    The subsequent mount failure without this fix -
    [   11.294650] F2FS-fs (sda8): Wrong user_block_count: 2233856
    [   11.300272] F2FS-fs (sda8): Failed to get valid F2FS checkpoint
    
    Signed-off-by: Sahitya Tummala <stummala@codeaurora.org>
    Reviewed-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - fsck.f2fs: account COMPRESS_ADDR as reserved blocks correctly
    
    We should not account COMPRESS_ADDR as reserved block once we
    released compress block on compress inode.
    
    Signed-off-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - f2fs_io: support compress blocks ioctls
    
    Adds to support below three commands to operate reserved blocks
    in compressed inode.
    - get_cblocks
    - release_cblocks
    - reserve_cblocks
    
    Signed-off-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - fsck.f2fs: report real wall time
    
    clock_t time is per-process time, which is not wall time. For example,
    if the CPU is shared by other processes, clock_t time may advance slower
    than wall clock. On the other hand, if the current process is
    multithreaded and more than one execution core is available, clock_t
    time may advance faster than wall clock.
    
    this CL changes it to use CLOCK_BOOTTIME (Linux-specific)
    
    Signed-off-by: Wei Wang <wvw@google.com>
    Reviewed-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - Include private/fs_config.h directly when needed
    
    This is no longer a transitive include of android_filesystem_config.h
    
    Signed-off-by: Tom Cherry <tomcherry@google.com>
    Reviewed-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - f2fs-tools: Casefolded Encryption support
    
    This adds support for casefolded and encrypted directories.
    Fsck cannot check the hashes of such directories because it would
    require access to the encryption key to generate the siphash
    
    Signed-off-by: Daniel Rosenberg <drosen@google.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - fsck.f2fs: allow --dry-run to check readonly mounted fs
    
    As Ondřej Jirman <megi@xff.cz> reported:
    
    I was trying to run: fsck.f2fs --dry-run /dev/mmcblk0p2 on a RO mounted device,
    and fsck refuses to run. Strace shows that it tries to open the block device
    with O_EXCL even in RO mode, which will always fail if the block device
    is mounted.
    
    fsck.f2fs --dry-run /dev/mmcblk0p2
    Info: Dry run
    Info: Mounted device!
    Info: Check FS only on RO mounted device
    	Error: Failed to open the device!
    
    I suggest not using O_EXCL for --dry-run check.
    
    Let's change to allow --dry-run to check readonly mounted fs.
    
    Reported-by: Ondřej Jirman <megi@xff.cz>
    Signed-off-by: Chao Yu <yuchao0@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    

* Update platform/superproject from branch 'master'
  to 77108a3ef0be2fff0d316fb5f6707db30c65c86f
  - Update git submodules
    
    * Update external/f2fs-tools from branch 'master'
      to c5e1fc00dddcca3be816d170a1020048af354ff4
      - Merge remote-tracking branch 'aosp/upstream-master' into aosp
        
        * aosp/upstream-master:
          fsck.f2fs: allow fsck to fix issues with online resize due to SPO
          fsck.f2fs: account COMPRESS_ADDR as reserved blocks correctly
          f2fs_io: support compress blocks ioctls
          fsck.f2fs: report real wall time
          Include private/fs_config.h directly when needed
          f2fs-tools: Casefolded Encryption support
          fsck.f2fs: allow --dry-run to check readonly mounted fs
        
        Signed-off-by: Jaegeuk Kim <jaegeuk@google.com>
        Change-Id: Id0c5f82cdd29ca8f3684d65cbfa3e4e853785590
        
      - fsck.f2fs: allow fsck to fix issues with online resize due to SPO
        
        Add support for new CP flag CP_RESIZEFS_FLAG set during online
        resize FS. If SPO happens after SB is updated but CP isn't, then
        allow fsck to fix it.
        
        The fsck errors without this fix -
            Info: CKPT version = 6ed7bccb
                    Wrong user_block_count(2233856)
            [f2fs_do_mount:3365] Checkpoint is polluted
        
        The subsequent mount failure without this fix -
        [   11.294650] F2FS-fs (sda8): Wrong user_block_count: 2233856
        [   11.300272] F2FS-fs (sda8): Failed to get valid F2FS checkpoint
        
        Signed-off-by: Sahitya Tummala <stummala@codeaurora.org>
        Reviewed-by: Chao Yu <yuchao0@huawei.com>
        Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
        
      - fsck.f2fs: account COMPRESS_ADDR as reserved blocks correctly
        
        We should not account COMPRESS_ADDR as reserved block once we
        released compress block on compress inode.
        
        Signed-off-by: Chao Yu <yuchao0@huawei.com>
        Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
        
      - f2fs_io: support compress blocks ioctls
        
        Adds to support below three commands to operate reserved blocks
        in compressed inode.
        - get_cblocks
        - release_cblocks
        - reserve_cblocks
        
        Signed-off-by: Chao Yu <yuchao0@huawei.com>
        Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
        
      - fsck.f2fs: report real wall time
        
        clock_t time is per-process time, which is not wall time. For example,
        if the CPU is shared by other processes, clock_t time may advance slower
        than wall clock. On the other hand, if the current process is
        multithreaded and more than one execution core is available, clock_t
        time may advance faster than wall clock.
        
        this CL changes it to use CLOCK_BOOTTIME (Linux-specific)
        
        Signed-off-by: Wei Wang <wvw@google.com>
        Reviewed-by: Chao Yu <yuchao0@huawei.com>
        Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
        
      - Include private/fs_config.h directly when needed
        
        This is no longer a transitive include of android_filesystem_config.h
        
        Signed-off-by: Tom Cherry <tomcherry@google.com>
        Reviewed-by: Chao Yu <yuchao0@huawei.com>
        Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
        
      - f2fs-tools: Casefolded Encryption support
        
        This adds support for casefolded and encrypted directories.
        Fsck cannot check the hashes of such directories because it would
        require access to the encryption key to generate the siphash
        
        Signed-off-by: Daniel Rosenberg <drosen@google.com>
        Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
        
      - fsck.f2fs: allow --dry-run to check readonly mounted fs
        
        As Ondřej Jirman <megi@xff.cz> reported:
        
        I was trying to run: fsck.f2fs --dry-run /dev/mmcblk0p2 on a RO mounted device,
        and fsck refuses to run. Strace shows that it tries to open the block device
        with O_EXCL even in RO mode, which will always fail if the block device
        is mounted.
        
        fsck.f2fs --dry-run /dev/mmcblk0p2
        Info: Dry run
        Info: Mounted device!
        Info: Check FS only on RO mounted device
        	Error: Failed to open the device!
        
        I suggest not using O_EXCL for --dry-run check.
        
        Let's change to allow --dry-run to check readonly mounted fs.
        
        Reported-by: Ondřej Jirman <megi@xff.cz>
        Signed-off-by: Chao Yu <yuchao0@huawei.com>
        Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>