Update git submodules
* Update platform/cts from branch 'master'
  to 2447865c2142022d8d729973a08bba62223c1200
  - Merge "Add net-utils-framework-common to cts-net"
  - Add net-utils-framework-common to cts-net
    
    In order to avoid class package missing problem, add
    net-utils-framework-common in cts net test build. Also jarjar
    the package name to prevent conflict.
    
    Test: build
    Test: atest DnsResolverTest
    Bug: 150952393
    (clean cherry-pick from internal branch)
    Merged-In: I40e2d4c4945a0579f6e1923e4722b09354ff050c
    Change-Id: I40e2d4c4945a0579f6e1923e4722b09354ff050c
    

* Update platform/frameworks/libs/net from branch 'master'
  to deb4f9440df94bee2bb5113a5b37697815b05ca8
  - Add the visibility of net-utils-framework-common for cts-net
    
    DnsResolverTest required DnsPacket to parse DNS answer, and the
    DnsPacket class is provided by system previously.
    However, DnsPacket was moved to here with changed package,
    which has no backward-compatibility and might cause
    NoClassDefFoundError. To solve this problem, build the DnsResolverTest with
    DnsPacket directly.
    
    Test: build
    Test: atest DnsResolverTest
    Bug: 150952393
    (clean cherry-pick from internal branch)
    Merged-In: I463fd58173cee55a210fa6c6b8c9b0d5a74b7906
    Change-Id: I463fd58173cee55a210fa6c6b8c9b0d5a74b7906
    

* Update platform/superproject from branch 'master'
  to 4736d608a726fe1a8cdc15aa797ff1ab2c692038
  - Update git submodules
    
    * Update cts from branch 'master'
      to 2447865c2142022d8d729973a08bba62223c1200
      - Merge "Add net-utils-framework-common to cts-net"
      - Add net-utils-framework-common to cts-net
        
        In order to avoid class package missing problem, add
        net-utils-framework-common in cts net test build. Also jarjar
        the package name to prevent conflict.
        
        Test: build
        Test: atest DnsResolverTest
        Bug: 150952393
        (clean cherry-pick from internal branch)
        Merged-In: I40e2d4c4945a0579f6e1923e4722b09354ff050c
        Change-Id: I40e2d4c4945a0579f6e1923e4722b09354ff050c
        
    
    * Update frameworks/libs/net from branch 'master'
      to deb4f9440df94bee2bb5113a5b37697815b05ca8
      - Add the visibility of net-utils-framework-common for cts-net
        
        DnsResolverTest required DnsPacket to parse DNS answer, and the
        DnsPacket class is provided by system previously.
        However, DnsPacket was moved to here with changed package,
        which has no backward-compatibility and might cause
        NoClassDefFoundError. To solve this problem, build the DnsResolverTest with
        DnsPacket directly.
        
        Test: build
        Test: atest DnsResolverTest
        Bug: 150952393
        (clean cherry-pick from internal branch)
        Merged-In: I463fd58173cee55a210fa6c6b8c9b0d5a74b7906
        Change-Id: I463fd58173cee55a210fa6c6b8c9b0d5a74b7906