Update git submodules
* Update platform/superproject from branch 'master'
  to ce58a8734bc472b5dfc5574c377f941c02f0ac97
  - Update git submodules
    
    * Update build/soong from branch 'master'
      to 98975c301e6be189e505c4c16b0fbde94f577f76
      - Merge "Move -Wno-null-dereference to external only"
      - Move -Wno-null-dereference to external only
        
        Test: m checkbuild
        Bug: 29823425
        Change-Id: Icd675e451b2a2a8e3f489706e533f92d991de9c0
        
    
    * Update hardware/google/av from branch 'master'
      to 10c8642c2abc6bf02d64ff605d3a42ed567265c8
      - Suppress null-dereference warning temporarily
        
        There's one more occurance of this warning.
        
        In file included from hardware/google/av/codec2/tests/C2SampleComponent_test.cpp:23:
        In file included from frameworks/av/media/codec2/core/include/C2Component.h:29:
        In file included from frameworks/av/media/codec2/core/include/C2Enum.h:20:
        frameworks/av/media/codec2/core/include/C2Param.h:1612:92: error: binding dereferenced null pointer to reference has undefined behavior [-Werror,-Wnull-dereference]
        C2FieldDescriptor::NamedValuesType named = C2FieldDescriptor::namedValuesFor(*(T*)0);
        ^~~~~~
        
        Also modernised the code to use nullptr instead of 0.
        
        Bug: 122154294
        Test: m checkbuild
        Exempt-From-Owner-Approval: No functionality change, similar CL already reviewed by owner
        Change-Id: I8020b1891d4636b68c997671eb9972f385014801