Update git submodules
* Update platform/external/zlib from branch 'master'
  to 457c92b855a561252861559abc6bbc5fa08d4f4b
  - Merge "Upgrade zlib to 814da1f383b625955149c3845db62af3f29a4ffe"
  - Upgrade zlib to 814da1f383b625955149c3845db62af3f29a4ffe
    
    Test: None
    Change-Id: I96acd457d55ed8fbce25f328a7dc43e7cd83a8d4
    
  - Revert "Unify CPU features detection code"
    
    This reverts commit 6f7e5e79cefe982ad84a88927565a88db2e592be.
    
    Reason for revert: This broke the build, e.g.
    https://ci.chromium.org/p/chromium/builders/ci/ios-device/144512
    
    ../../third_party/zlib/cpu_features.c:75:13: error: unused function '_cpu_check_features' [-Werror,-Wunused-function]
    static void _cpu_check_features(void)
                ^
    
    Original change's description:
    > Unify CPU features detection code
    > 
    > This will allow to remove some duplicated code (i.e. thread synchronization)
    > while at same time removing unnecessary use of inline ASM for Intel features
    > detection.
    > 
    > A few other advantages:
    >  - remove some extra logic (e.g. no need to test the platform to include the
    >    correct CPU detection header).
    >  - simplifies the buildsystem (i.e. we always include cpu_features.c)
    >  - get rid of the simd_stub file.
    > 
    > Bug: 1032721
    > Change-Id: Ic93472d3337bc2cbe092d4cf8fbe4b31b1ceca6d
    > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1976820
    > Reviewed-by: Chris Blume <cblume@chromium.org>
    > Reviewed-by: Adenilson Cavalcanti <cavalcantii@chromium.org>
    > Commit-Queue: Adenilson Cavalcanti <cavalcantii@chromium.org>
    > Cr-Commit-Position: refs/heads/master@{#727038}
    
    TBR=cavalcantii@chromium.org,cblume@chromium.org,mtklein@chromium.org,adenilson.cavalcanti@arm.com
    
    Change-Id: I20c5dedb98ba8b5d304ff1339042bcf243505e88
    No-Presubmit: true
    No-Tree-Checks: true
    No-Try: true
    Bug: 1032721
    Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1979790
    Reviewed-by: Hans Wennborg <hans@chromium.org>
    Commit-Queue: Hans Wennborg <hans@chromium.org>
    Cr-Original-Commit-Position: refs/heads/master@{#727039}
    Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
    Cr-Mirrored-Commit: 9d8f976414a7608c3361718462253104a761c6bb
    
  - Unify CPU features detection code
    
    This will allow to remove some duplicated code (i.e. thread synchronization)
    while at same time removing unnecessary use of inline ASM for Intel features
    detection.
    
    A few other advantages:
     - remove some extra logic (e.g. no need to test the platform to include the
       correct CPU detection header).
     - simplifies the buildsystem (i.e. we always include cpu_features.c)
     - get rid of the simd_stub file.
    
    Bug: 1032721
    Change-Id: Ic93472d3337bc2cbe092d4cf8fbe4b31b1ceca6d
    Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1976820
    Reviewed-by: Chris Blume <cblume@chromium.org>
    Reviewed-by: Adenilson Cavalcanti <cavalcantii@chromium.org>
    Commit-Queue: Adenilson Cavalcanti <cavalcantii@chromium.org>
    Cr-Original-Commit-Position: refs/heads/master@{#727038}
    Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
    Cr-Mirrored-Commit: 6f7e5e79cefe982ad84a88927565a88db2e592be
    
  - Unify optimized insert_string implementations
    
    This change will unify the x86 and Arm optimized implementations
    for insert_string (used for compression).
    
    The objective here is two-fold:
    a) Remove duplicated code.
    b) Better insulate deflate.c divergence when compared to
    vanilla zlib.
    
    Bug: 1032721
    Change-Id: Id2f65398aeb5a6384708493f0f6ae1fcd14022c2
    Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1960893
    Reviewed-by: Chris Blume <cblume@chromium.org>
    Commit-Queue: Adenilson Cavalcanti <cavalcantii@chromium.org>
    Cr-Original-Commit-Position: refs/heads/master@{#724325}
    Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
    Cr-Mirrored-Commit: 9d4ec9349a1bf609eedb917c44c69eb0df9ff6bb
    

* Update platform/superproject from branch 'master'
  to 950d03a48c41016622881ce5588af1f92bba0382
  - Update git submodules
    
    * Update external/zlib from branch 'master'
      to 457c92b855a561252861559abc6bbc5fa08d4f4b
      - Merge "Upgrade zlib to 814da1f383b625955149c3845db62af3f29a4ffe"
      - Upgrade zlib to 814da1f383b625955149c3845db62af3f29a4ffe
        
        Test: None
        Change-Id: I96acd457d55ed8fbce25f328a7dc43e7cd83a8d4
        
      - Revert "Unify CPU features detection code"
        
        This reverts commit 6f7e5e79cefe982ad84a88927565a88db2e592be.
        
        Reason for revert: This broke the build, e.g.
        https://ci.chromium.org/p/chromium/builders/ci/ios-device/144512
        
        ../../third_party/zlib/cpu_features.c:75:13: error: unused function '_cpu_check_features' [-Werror,-Wunused-function]
        static void _cpu_check_features(void)
                    ^
        
        Original change's description:
        > Unify CPU features detection code
        > 
        > This will allow to remove some duplicated code (i.e. thread synchronization)
        > while at same time removing unnecessary use of inline ASM for Intel features
        > detection.
        > 
        > A few other advantages:
        >  - remove some extra logic (e.g. no need to test the platform to include the
        >    correct CPU detection header).
        >  - simplifies the buildsystem (i.e. we always include cpu_features.c)
        >  - get rid of the simd_stub file.
        > 
        > Bug: 1032721
        > Change-Id: Ic93472d3337bc2cbe092d4cf8fbe4b31b1ceca6d
        > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1976820
        > Reviewed-by: Chris Blume <cblume@chromium.org>
        > Reviewed-by: Adenilson Cavalcanti <cavalcantii@chromium.org>
        > Commit-Queue: Adenilson Cavalcanti <cavalcantii@chromium.org>
        > Cr-Commit-Position: refs/heads/master@{#727038}
        
        TBR=cavalcantii@chromium.org,cblume@chromium.org,mtklein@chromium.org,adenilson.cavalcanti@arm.com
        
        Change-Id: I20c5dedb98ba8b5d304ff1339042bcf243505e88
        No-Presubmit: true
        No-Tree-Checks: true
        No-Try: true
        Bug: 1032721
        Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1979790
        Reviewed-by: Hans Wennborg <hans@chromium.org>
        Commit-Queue: Hans Wennborg <hans@chromium.org>
        Cr-Original-Commit-Position: refs/heads/master@{#727039}
        Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
        Cr-Mirrored-Commit: 9d8f976414a7608c3361718462253104a761c6bb
        
      - Unify CPU features detection code
        
        This will allow to remove some duplicated code (i.e. thread synchronization)
        while at same time removing unnecessary use of inline ASM for Intel features
        detection.
        
        A few other advantages:
         - remove some extra logic (e.g. no need to test the platform to include the
           correct CPU detection header).
         - simplifies the buildsystem (i.e. we always include cpu_features.c)
         - get rid of the simd_stub file.
        
        Bug: 1032721
        Change-Id: Ic93472d3337bc2cbe092d4cf8fbe4b31b1ceca6d
        Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1976820
        Reviewed-by: Chris Blume <cblume@chromium.org>
        Reviewed-by: Adenilson Cavalcanti <cavalcantii@chromium.org>
        Commit-Queue: Adenilson Cavalcanti <cavalcantii@chromium.org>
        Cr-Original-Commit-Position: refs/heads/master@{#727038}
        Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
        Cr-Mirrored-Commit: 6f7e5e79cefe982ad84a88927565a88db2e592be
        
      - Unify optimized insert_string implementations
        
        This change will unify the x86 and Arm optimized implementations
        for insert_string (used for compression).
        
        The objective here is two-fold:
        a) Remove duplicated code.
        b) Better insulate deflate.c divergence when compared to
        vanilla zlib.
        
        Bug: 1032721
        Change-Id: Id2f65398aeb5a6384708493f0f6ae1fcd14022c2
        Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1960893
        Reviewed-by: Chris Blume <cblume@chromium.org>
        Commit-Queue: Adenilson Cavalcanti <cavalcantii@chromium.org>
        Cr-Original-Commit-Position: refs/heads/master@{#724325}
        Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
        Cr-Mirrored-Commit: 9d4ec9349a1bf609eedb917c44c69eb0df9ff6bb