Update git submodules
* Update platform/development from branch 'master'
  to 445a4c4e196d2f23a9939dd523b81549420d695d
  - Merge "Use input instead of raw_input in gdbclient.py"
  - Use input instead of raw_input in gdbclient.py
    
    Following suggestions in b/194659728, update the python script to work
    under python3.
    
    Previous failure:
    
    Traceback (most recent call last):
      File "/android3/android/master/development/scripts/lldbclient.py", line 413, in <module>
        main()
      File "/android3/android/master/development/scripts/lldbclient.py", line 405, in main
        do_main()
      File "/android3/android/master/development/scripts/lldbclient.py", line 400, in do_main
        raw_input("Press enter to shut down lldb-server")
    NameError: name 'raw_input' is not defined
    
    Bug: none
    Test: "lldbclient.py --setup-forwarding vscode-lldb -r
    /data/nativetest64/inputflinger_tests/inputflinger_tests
    --gtest_filter=PalmRejectorTest.GenericAxisValue_IsNotSet"
    
    Change-Id: I21d977cbc580894d6e2eb2f2f56dec04c65b0416