Update git submodules
* Update kernel/build from branch 'master'
  to 1b6f17959fadcdc686abb67fd8b6ad57da52c882
  - kleaf: kernel_config_option_test sets kernel_build.arch properly.
    
    Needed to fix errors like:
      ERROR: @//build/kernel/kleaf/tests/kernel_config_test:kernel_config_option_test_suite_kernel_x86_64_trim_env must specify arch = x86_64.
    
    Bug: 272164611
    Test: TH
    Change-Id: Ia1a2940249233ae94ad835750a5d36970ffa0325