Update git submodules
* Update platform/external/rust/cxx from branch 'master'
  to d80a29bb561477e37aeab2eff14f3b4e7fcc889d
  - Upgrade rust/cxx to 251cf910ebb5cc6eb628a1e48cacbea6cfdf05c3
    
    Test: Build this and system/bt/gd/rust.
    Change-Id: I81ca4e339af94638bdcffb6b5f6b301aa354220f
    
  - Revert "Suppress unknown clippy lints"
    
    This reverts commit 05e7ae87b8c44a194735aae9f9331a54424913b2.
    
    Test: Build with following CL.
    Change-Id: I460aeb68294046d56c02391604125852489a8e39
    
  - Merge pull request 882 from trondhe/master
    
  - add additional cmake example
    
  - Avoid asserting to llvm that C++ ptr type bits are fully occupied
    
    For example if hypothetically any of std::unique_ptr or std::shared_ptr
    or std::weak_ptr contained any padding bits in their representation,
    manipulating any of them by value in Rust as if they were fully
    initialized pointers would be UB.
    
  - Release 1.0.49
    
  - Lockfile update
    
  - Merge pull request #859 from dtolnay/vectorrepr
    
    Fix "not FFI-safe" on CxxVector containing struct containing Rust string
  - Update CxxVector autotrait diagnostic
    
  - Eliminate raw pointer to element type from CxxVector impl
    
  - Adjust CxxVector repr to be ffi independent of T
    
  - Add regression test of issue 857
    
    This currently fails to compile.
    
        error: `extern` block uses type `String`, which is not FFI-safe
           --> tests/ffi/lib.rs:329:34
            |
        329 |     impl CxxVector<SharedString> {}
            |                                  ^^ not FFI-safe
            |
        note: the lint level is defined here
           --> tests/ffi/lib.rs:23:1
            |
        23  | #[cxx::bridge(namespace = "tests")]
            | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            = help: consider adding a `#[repr(C)]` or `#[repr(transparent)]` attribute to this struct
            = note: this struct has unspecified layout
            = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
    
  - Merge pull request #858 from dtolnay/stdvectorautotrait
    
    Add ui test of CxxVector autotrait impls
  - Add ui test of CxxVector autotrait impls
    
  - Tweak opaque type repr for slightly more evocative errors
    
  - Add a CxxVector size assertion
    
  - Release 1.0.48
    
  - Lockfile update
    
  - Prune null fields from serialized clang tree
    
  - Expose Serialize impls on cxxbridge_macro::clang::Node
    
    This allows external tooling to round-trip through this data structure
    to discard information that cxxbridge-macro is not interested in.
    
    https://github.com/dtolnay/clang-ast/pull/8
    
  - Adopt Box<str> for some AST size shrinking
    
  - Track size of AST node structure
    
  - Merge pull request #854 from dtolnay/empty
    
    Add `bool empty() const noexcept` to Str, String
  - Split clang AST data structures out to module
    
  - Document empty() member function in book
    
  - Add 'bool empty() const noexcept' to Str, String
    
  - Release 1.0.47
    
  - Lockfile update
    
  - Merge pull request #852 from dtolnay/gz
    
    Support gz compressed AST input
  - Handle gz decoder errors
    
  - Support gz compressed AST input
    
  - Merge pull request #851 from dtolnay/mmap
    
    Memory-map AST file instead of reading to memory
  - Memory-map AST file instead of reading to memory
    
  - Merge pull request #847 from dtolnay/clang-ast
    
    Experimental support for enum variant names and discriminant values retrieved from C++
  - Ignore whether variants_from_header attr is outer or inner
    
  - Parse enum underlying repr type from clang AST
    
  - Support enum repr types from std::os::raw
    
  - Factor out enum qualified name formatter
    
  - Raise error on repeated definitions of same enum
    
  - Move empty enum check to before filling in variants
    
  - Parse discriminant values from clang AST
    
  - Adopt default variant name on name parse error
    
  - Check whether variants have been found for every enum
    
  - Extract variant info from ast dump
    
  - JSON deserialization based on CXX_CLANG_AST env var
    
  - Store original Attribute of the variants_from_header for spans
    
  - Determine whether AST dump loading is necessary
    
  - Set up clang ast loading in macro expand codepath
    
  - Skip enum static assertions if loading from header
    
  - Implicltly extern type for enums sourced from header
    
  - Preserve item inner attrs
    
  - Implement variants_from_header checking
    
  - Parse #![variants_from_header] inner attribute
    
  - Pull in syn 1.0.70 for inner attribute support
    
  - Update lockfile to reflect clang-ast dependency
    
  - Add experimental feature with optional dependency on clang-ast
    
  - Release 1.0.46
    
  - Lockfile update
    
  - Merge pull request #845 from dtolnay/clippy
    
    Work around redundant_closure lint in old clippys
  - Work around redundant_closure lint in old clippys
    
  - Merge pull request #844 from dtolnay/unknownlint
    
    Avoid warning on unknown upper_case_acronyms lint on old clippys
  - Avoid warning on unknown upper_case_acronyms lint on old clippys
    
  - Merge pull request #842 from dtolnay/weakptrtarget
    
    Expose WeakPtrTarget trait bound under cxx::memory
  - Expose WeakPtrTarget trait bound under cxx::memory
    
  - Merge pull request #841 from dtolnay/missingdocs
    
    deny(missing_docs) at crate root
  - deny(missing_docs) at crate root
    
    To help flag missing documentation on publicly accessible APIs.
    
  - Fill in vector pop method comment
    
  - Release 1.0.45
    
  - Disable bazel/buck CI jobs on pull requests
    
    These are somewhat annoying to set up for local development, and
    iterating a PR via GitHub Actions remote builds is painful. Anything
    that would break these is always easy enough to fix up afterward.
    
  - Merge pull request #840 from dtolnay/pop
    
    Add CxxVector::pop in Rust
  - Add CxxVector::pop in Rust
    
  - Merge pull request #839 from dtolnay/push
    
    Add CxxVector::push in Rust
  - Add CxxVector::push in Rust
    
  - Factor out helper for identifying maybe trivial types
    
  - Merge pull request #837 from dtolnay/fncvoid
    
    Make FatFunction private contents into proper ctype
  - Make FatFunction contents into proper ctype
    
    Without this, it's possible for the macro-expanded code to trigger
    improper_ctypes lints.
    
        error: `extern` block uses type `()`, which is not FFI-safe
            --> tests/ffi/lib.rs:2577:44
             |
        2577 |             fn __c_take_callback(callback: ::cxx::private::FatFunction);
             |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not FFI-safe
             |
        note: the lint level is defined here
            --> tests/ffi/lib.rs:1439:8
             |
        1439 | #[deny(improper_ctypes, improper_ctypes_definitions)]
             |        ^^^^^^^^^^^^^^^
             = help: consider using a struct instead
             = note: tuples have unspecified layout
    
  - Clean up unneeded Debug derive macro import
    
    Presumably this used to be a handwritten Debug impl which needed the
    import, later replaced by #[derive(Debug)] which is present in the
    prelude but masks the unused_imports warning.
    
  - Merge pull request #836 from dtolnay/dropwrapper
    
    Add impls for dropping RustString/RustVec ffi wrappers
  - Add impls for dropping RustString/RustVec ffi wrappers
    
  - Release 1.0.44
    
  - Merge pull request #834 from dtolnay/innerattr
    
    Support inner attributes inside bridge
  - Support inner attributes inside bridge
    
    Example:
    
        #[cxx::bridge]
        mod ffi {
            #![deny(missing_docs)]
    
            unsafe extern "C++" {
                include!("example/include/header.h");
    
                /// wow
                fn f();
            }
        }
    
        pub use self::ffi::*;
    
  - Merge pull request #832 from dtolnay/docmethod
    
    Fix placement of C++ comments on member function decls
  - Add padding around member functions that have documentation
    
  - Document member functions just once in impl file
    
  - Fix placement of C++ comments on member function decls
    
  - Release 1.0.43
    
  - Lockfile update
    
  - Update Bazel Rust rules version
    
  - Update Bazel build to rustc 1.51.0
    
  - Merge pull request #828 from dtolnay/fn
    
    Fix undeclared lifetime when fn ptr arg contains outer lifetime
  - Fix undeclared lifetime when fn ptr arg contains outer lifetime
    
  - Add regression test for issue 739
    
    Currently fails to build.
    
        error[E0261]: use of undeclared lifetime name `'a`
           --> tests/ffi/lib.rs:162:59
            |
        23  | #[cxx::bridge(namespace = "tests")]
            |                                    - lifetime `'a` is missing in item created through this procedural macro
        ...
        162 |         fn c_take_callback_ref_lifetime<'a>(callback: fn(&'a String));
            |                                                           ^^ undeclared lifetime
            |
            = note: for more information on higher-ranked polymorphism, visit https://doc.rust-lang.org/nomicon/hrtb.html
            = help: if you want to experiment with in-band lifetime bindings, add `#![feature(in_band_lifetimes)]` to the crate attributes
        help: consider making the type lifetime-generic with a new `'a` lifetime
            |
        162 |         fn c_take_callback_ref_lifetime<'a>(callback: for<'a> fn(&'a String));
            |                                                       ^^^^^^^
    
  - Merge pull request #827 from dtolnay/spans
    
    Preserve token spans everywhere possible in expand_extern_type
  - Preserve token spans everywhere possible in expand_extern_type
    
  - Merge pull request #826 from dtolnay/ctypes
    
    Insert void ptr casts for invalid Box and UniquePtr ctypes
  - Insert void ptr casts for invalid Box and UniquePtr ctypes
    
  - Merge pull request #825 from dtolnay/span
    
    Improve spans inside generated function bodies
  - Span all C++ function shim bodies with appropriate span
    
  - Span all Rust function shim bodies with appropriate span
    
  - Merge pull request #824 from dtolnay/colon
    
    Preserve span of function argument colon tokens
  - Touch up BareFn type parsing
    
  - Propagate span of method receiver colon tokens
    
  - Store span of method receiver colon tokens
    
  - Propagate span of function argument colon tokens
    
  - Store span of function argument colon tokens
    
  - Merge pull request #823 from dtolnay/span
    
    Span all argument manipulations using the arg's ident span
  - Span all argument manipulations using the arg's ident span
    
  - Merge pull request #822 from dtolnay/var
    
    Consistently use 'var' for fn argument variable ident
  - Consistently use 'var' for fn argument variable ident
    
  - Merge pull request #821 from dtolnay/abi
    
    Revamp RustString and RustVec ABI to match cxx.h
  - Resolve improper ctype lint affecting RustVec
    
  - Resolve improper ctype lint affecting RustString
    
  - Merge pull request #820 from dtolnay/vecrepr
    
    Encapsulate RustVec repr to single module
  - Encapsulate RustVec repr to single module
    
  - Merge pull request #819 from dtolnay/abi
    
    Revamp RustStr and RustSlice ABI to match cxx.h
  - Restore compatibility with rustc pre 1.53
    
    The signature of NonNull::as_ref is more restrictive on lifetimes in
    older standard libraries.
    
        error[E0515]: cannot return value referencing local variable `repr`
          --> src/rust_str.rs:19:9
           |
        19 |         repr.as_ref()
           |         ----^^^^^^^^^
           |         |
           |         returns a value referencing data owned by the current function
           |         `repr` is borrowed here
    
  - Resolve improper ctype lint affecting RustSlice
    
  - Resolve improper ctype lint affecting RustStr
    
  - Merge pull request #818 from dtolnay/slice
    
    Encapsulate RustSlice repr to single module
  - Encapsulate RustSlice repr to single module
    
  - Merge pull request #816 from dtolnay/definitions
    
    Deny improper_ctypes_definitions in generated code
  - Deny improper_ctypes_definitions
    
    This warning is mostly equivalent to improper_ctypes but applies to
    function definitions as opposed to declarations.
    
        extern "C" {
            // improper_ctypes
            pub fn c(_s: &str);
        }
    
        // improper_ctypes_definitions
        pub extern "C" fn r(_s: &str) {}
    
    Warnings:
    
        warning: `extern` block uses type `str`, which is not FFI-safe
         --> src/lib.rs:3:18
          |
        3 |     pub fn c(_s: &str);
          |                  ^^^^ not FFI-safe
          |
          = note: `#[warn(improper_ctypes)]` on by default
          = help: consider using `*const u8` and a length instead
          = note: string slices have no C equivalent
    
        warning: `extern` fn uses type `str`, which is not FFI-safe
         --> src/lib.rs:7:25
          |
        7 | pub extern "C" fn r(_s: &str) {}
          |                         ^^^^ not FFI-safe
          |
          = note: `#[warn(improper_ctypes_definitions)]` on by default
          = help: consider using `*const u8` and a length instead
          = note: string slices have no C equivalent
    
  - Merge pull request #814 from dtolnay/fnrefarg
    
    Fix rust::Fn call with non-const reference argument
  - Suppress ptr_arg clippy lint in test suite
    
        warning: writing `&String` instead of `&str` involves a new object where a slice will do
           --> tests/test.rs:207:24
            |
        207 |     fn callback_ref(s: &String) {
            |                        ^^^^^^^ help: change this to: `&str`
            |
            = note: `#[warn(clippy::ptr_arg)]` on by default
            = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg
    
  - Fix rust::Fn call with non-const reference argument
    
  - Add regression test for issue 738
    
    Currently fails to build.
    
        In file included from cxx-test-suite-32b8d00ca9482f5f/out/cxxbridge/crate/tests/ffi/tests.h:2,
                         from tests.cc:1:
        cxx-test-suite-32b8d00ca9482f5f/out/cxxbridge/include/rust/cxx.h: In instantiation of ‘Ret rust::cxxbridge1::Fn<Ret(Args ...)>::operator()(Args ...) const [with Ret = void; Args = {rust::cxxbridge1::String&}]’:
        tests.cc:504:18:   required from here
        cxx-test-suite-32b8d00ca9482f5f/out/cxxbridge/include/rust/cxx.h:478:29: error: cannot bind non-const lvalue reference of type ‘rust::cxxbridge1::String&’ to an rvalue of type ‘std::remove_reference<rust::cxxbridge1::String&>::type’ {aka ‘rust::cxxbridge1::String’}
          478 |   return (*this->trampoline)(std::move(args)..., this->fn);
              |          ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        cxx-test-suite-32b8d00ca9482f5f/out/cxxbridge/include/rust/cxx.h:478:58: error: return-statement with a value, in function returning ‘void’ [-fpermissive]
          478 |   return (*this->trampoline)(std::move(args)..., this->fn);
              |                                                          ^
    
  - Merge pull request #813 from dtolnay/static
    
    Diagnostic for invalid use of 'static as a lifetime parameter name
  - Make errors rustc already catches specific to C++ generator
    
  - Diagnostic for invalid lifetime param 'static
    
  - Add ui test of invalid use of 'static as lifetime param name
    
  - Update ui test suite to nightly-2021-04-09
    
  - Suppress unknown clippy lints am: 05e7ae87b8
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1668767
    
    Change-Id: I11d757ae1be3c91dd0c7ae96dc68845268dd7c12
    
  - Update CXX to 1.0.42 am: b4406114c9
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1668766
    
    Change-Id: I1266f286b324ab76f88adf5828c7e43b04393b7c
    
  - Use whole_static_library for cxx bridge library am: 6e7104cc54
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1654112
    
    Change-Id: I4d864a76ad230d5f10cb30507fea5363e0f0be5a