Update git submodules
* Update toolchain/llvm_android from branch 'master'
  to b4d698aa746c462a93cf8ed769c4b0bbfa971ce5
  - Enables -Werror=unguarded-availability for Darwin
    
    This will fail the build if any API newer than MAC_MIN_VERSION is used.
    
    And it did fail the build. The following fixes are applied:
    
    1. Bump MAC_MIN_VERSION to 10.10, because at least one error occured:
    /Volumes/Android/hhb/llvm-toolchain/out/llvm-project/libcxx/src/filesystem/operations.cpp:1088:7:
    error: 'fchmodat' is only available on macOS 10.10 or newer
    [-Werror,-Wunguarded-availability]
      if (::fchmodat(AT_FDCWD, p.c_str(), real_perms, flags) == -1) {
            ^~~~~~~~~~
    
    2. Disable libcompression. It is new in 10.11.
    
    3. Disable debugserver for lldb. It is just for testing.
    
    Change-Id: I8a2ed3011b4e5c16794672fef6c25d343b7e1fec