Update git submodules
* Update platform/art from branch 'master'
  to 34b00fbeb8d3924f04bccad016d6d0fe898b3938
  - Remove libdexfile_support shared library.
    
    It's a tiny library that doesn't justify the DSO overhead - only
    provide it as a static library.
    
    Also clean up a few remaining references to libdexfile_external.so.
    
    Test: Boot
    Bug: 143978909
    Change-Id: I3d2be11e7b01dcfeafffab518833ca7425e95f4c
    

* Update platform/prebuilts/module_sdk/art from branch 'master'
  to 4289d8266a5d09e9438ee603daf5f3ec43ccbaab
  - Disable shared libdexfile_support prebuilt.
    
    This manual change is necessary to work around Soong problem where the
    dropped source shared lib in https://r.android.com/1708390 causes a
    failing dependency here:
    
      error: prebuilts/module_sdk/art/current/sdk/Android.bp:1293:1: reverse dependency "libdexfile_support" of "art-module-sdk_libdexfile_support@current" missing variant:
        os:android,image:,arch:x86_64_silvermont,sdk:
      available variants:
        /.../
        os:android,image:,arch:x86_64_silvermont (alias to os:android,image:,arch:x86_64_silvermont,sdk:,link:static)
        os:android,image:,arch:x86_64_silvermont,sdk: (alias to os:android,image:,arch:x86_64_silvermont,sdk:,link:static)
        os:android,image:,arch:x86_64_silvermont,sdk:,link:static
        /.../
    
    The next prebuilt drop after that CL has been submitted will avoid that
    dependency.
    
    Test: m nothing
    Bug: 143978909
    Change-Id: Idd19d7b879b8780831bc275df67bc0f2127c21ff