Update git submodules
* Update platform/tools/tradefederation.git from branch 'master'
  to 7f9e82575eb16ad963dd39b6e8aa87052b600d3d
  - Capture additional exception path in getUsbHelper
    
    ... and auto disable if such exceptions happen.
    It seems that exception signature has changed across
    JDK versions from UnsatisfiedLinkError to NoClassDefFoundError
    so using the super class LinkageError instead.
    
    Also added the auto-disable approach which was originally
    suggested during review of aosp/1849495
    
    Bug: 202400161
    Change-Id: I709b1777a65d9f0d348d97a968145e698cb8ee8e
    Test: existing unit tests