Update git submodules
* Update platform/external/python/asn1crypto from branch 'master'
  to 2b20719855546eec025b0433f144d8780850ebd1
  - Upgrade python/asn1crypto to 1.4.0
    
    Test: make
    Change-Id: I91c1d9e084d4804e09aa5d686816dba41512357e
    
  - Version 1.4.0
    
  - Fix keys.PublicKeyInfo.bit_size tests on Python 2.6
    
  - Ensure keys.PublicKeyInfo.bit_size returns an int
    
  - Tweak error messages on invalid OIDs
    
  - Merge pull request #174 from joernheissler/oid-arc-2
    
    Fix parsing of ObjectIdentifier's first octet.
  - Fix PyPy on CircleCI
    
  - Merge pull request #188 from daxtens/travis-ppc64le
    
    Add ppc64le jobs to Travis CI
  - Add ppc64le jobs to Travis CI
    
    As with ARM64, Travis CI supports ppc64le ("Power") now.
    
    I've just mimicked the job that ARM64 does, I think that provides
    decent coverage without bloating the test matrix too much. (We could
    also test pypy on Power, but I don't think it gets us too much extra
    value.)
    
  - Disable uploading coverage reports to codecov since it is a constant thorn in my side
    
  - Fix an issue with asn1crypto_tests when running egg_info from sdist
    
  - Merge pull request #181 from hroncok/patch-1
    
    Fix a syntax typo
  - Fix a syntax typo
    
    
    This worked for now, but is SyntaxError in Python 3.9.0a6:
    
      File "/usr/lib/python3.9/site-packages/asn1crypto/x509.py", line 1139
        return', '.join(
             ^
    SyntaxError: invalid string prefix
    
    (The Python change might actually be reverted before 3.9 final, but this can be fixed anyway.)
  - [automerger skipped] DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp into stag-aosp-master am: e601bdffcf -s ours am: d1a106cb67
    
    Change-Id: I14df755a99bb97c940ade44583384d1e47b40db0
    
  - [automerger skipped] DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp into stag-aosp-master am: e601bdffcf -s ours
    
    am skip reason: subject contains skip directive
    
    Change-Id: I124a3fd0579b628566cb5d9339ee87883e6c08bc
    
  - Remove redundant NOTICE symbolic link. am: 39d4669413 am: 9d6b0848b4 am: 2993ae972d
    
    Change-Id: I9bb9ab295bd5a2ff464e236edeb66a98df803e10
    
  - Remove redundant NOTICE symbolic link. am: 39d4669413 am: 9d6b0848b4
    
    Change-Id: If9a41a8c81ad30179b0f05d6ac1d6ff2f5951977
    
  - Run GitHub actions on pull requests
    
  - Update deps task to filter by python_version and requires_python
    
  - Upgrade python/asn1crypto to 1.3.0 am: 4918382e86 am: a9a4b88828 am: 67a55d70b5
    
    Change-Id: I755be65c30a23d78d712b75efcac32c11f8d9524
    
  - Fix parsing of ObjectIdentifier's first octet.
    
    X.660 §7.6 specifies that the first arc of an OID must be 0 to 2 and
    the second arc below arcs 0 and 1 must be 0 to 39. Arc 2 is not
    restricted in that way.
    
    The algorithm for parsing ObjectIdentifiers did not work for
    OID 2.X with X >= 40.
    
    This change also enforces above restrictions when setting an
    ObjectIdentifier.
    
  - [automerger skipped] DO NOT MERGE - qt-qpr1-dev-plus-aosp-without-vendor@5915889 into stage-aosp-master am: 0fb45b7e85
    am: 1fbb019a9b -s ours
    am skip reason: subject contains skip directive
    
    Change-Id: I22f141892f47952231b2052b5921f59c41f2ea18
    
  - Upgrade python/asn1crypto to 1.0.0 am: bbe5f36e27 am: 9f54e18bda am: f4b1d844bc
    am: 09b30c4fd8
    
    Change-Id: I9cd0710bd5601152d8c30dfe5a16d1e282523bdb
    
  - Add in TEST_MAPPING for acloud unittests. am: 18a97e91fe am: 9d1650023f am: 489460043e am: dcce760325
    am: ca8975ab36
    
    Change-Id: I5db41ea58d9e1844f65fed28c336524585e791c3
    
  - Merge commit '6060d29' into import am: b80da1501c am: 0d2b31c24f
    am: d314b9f425
    
    Change-Id: I13790b448aede2ee03336d09c8a5f652e3abea1a
    

* Update platform/superproject from branch 'master'
  to 77f624111a1e7a4a39eb13240c627bf608a9c254
  - Update git submodules
    
    * Update external/python/asn1crypto from branch 'master'
      to 2b20719855546eec025b0433f144d8780850ebd1
      - Upgrade python/asn1crypto to 1.4.0
        
        Test: make
        Change-Id: I91c1d9e084d4804e09aa5d686816dba41512357e
        
      - Version 1.4.0
        
      - Fix keys.PublicKeyInfo.bit_size tests on Python 2.6
        
      - Ensure keys.PublicKeyInfo.bit_size returns an int
        
      - Tweak error messages on invalid OIDs
        
      - Merge pull request #174 from joernheissler/oid-arc-2
        
        Fix parsing of ObjectIdentifier's first octet.
      - Fix PyPy on CircleCI
        
      - Merge pull request #188 from daxtens/travis-ppc64le
        
        Add ppc64le jobs to Travis CI
      - Add ppc64le jobs to Travis CI
        
        As with ARM64, Travis CI supports ppc64le ("Power") now.
        
        I've just mimicked the job that ARM64 does, I think that provides
        decent coverage without bloating the test matrix too much. (We could
        also test pypy on Power, but I don't think it gets us too much extra
        value.)
        
      - Disable uploading coverage reports to codecov since it is a constant thorn in my side
        
      - Fix an issue with asn1crypto_tests when running egg_info from sdist
        
      - Merge pull request #181 from hroncok/patch-1
        
        Fix a syntax typo
      - Fix a syntax typo
        
        
        This worked for now, but is SyntaxError in Python 3.9.0a6:
        
          File "/usr/lib/python3.9/site-packages/asn1crypto/x509.py", line 1139
            return', '.join(
                 ^
        SyntaxError: invalid string prefix
        
        (The Python change might actually be reverted before 3.9 final, but this can be fixed anyway.)
      - Run GitHub actions on pull requests
        
      - Update deps task to filter by python_version and requires_python
        
      - Fix parsing of ObjectIdentifier's first octet.
        
        X.660 §7.6 specifies that the first arc of an OID must be 0 to 2 and
        the second arc below arcs 0 and 1 must be 0 to 39. Arc 2 is not
        restricted in that way.
        
        The algorithm for parsing ObjectIdentifiers did not work for
        OID 2.X with X >= 40.
        
        This change also enforces above restrictions when setting an
        ObjectIdentifier.