Update git submodules
* Update platform/external/libcxxabi from branch 'master'
  to 45ad00158cee28182b7338b963e38b97747d7924
  - cxa_guard: avoid sys/syscall.h and SYS_gettid
    
    Avoid including sys/syscall.h on Android Trusty, because sys/syscall.h
    tries to include bits/syscall.h, which doesn't exist. Detect this
    situation using _LIBCXXABI_HAS_NO_THREADS, which Trust seems to define,
    and if there are no threads, then SYS_gettid isn't needed.
    
    Disable the SYS_gettid call for Bionic, because some Android processes
    have a seccomp filter blocking gettid.
    
    Bug: http://b/189279320
    Test: treehugger
    Change-Id: I542d649d11f10f07ce702521f9d18736e67602c1
    
  - Add Apache 2.0 to license_kinds
    
    The __cxa_guard rewrite added some files with the new LLVM Apache
    license.
    
    Bug: http://b/189279320
    Test: treehugger
    Change-Id: Ibe1d5b2a367bb859eb41336050f6a8d85ac14a5e
    
  - [libcxxabi] __cxa_guard_require: test guard byte with != 0 instead of == 1
    
    git-svn-id: https://llvm.org/svn/llvm-project/libcxxabi/trunk@369109 91177308-0d34-0410-b5e6-96231b3b80d8
    (cherry picked from commit ab4302de162a1de64cdd8d51351858834cc926be)
    
    Bug: http://b/189279320
    Test: treehugger
    Change-Id: Ia47ad2f2f95d343adb30eb46c0043c76f5885195
    
  - Fix compilation error with -DLIBCXXABI_ENABLE_THREADS=OFF
    
    The error is:
    
    libcxxabi/src/cxa_guard_impl.h: In instantiation of ‘__cxxabiv1::{anonymous}::LibcppMutex __cxxabiv1::{anonymous}::GlobalStatic<__cxxabiv1::{anonymous}::LibcppMutex>::instance’:
    libcxxabi/src/cxa_guard_impl.h:529:62:   required from here
    libcxxabi/src/cxa_guard_impl.h:510:23: error: ‘__cxxabiv1::{anonymous}::LibcppMutex __cxxabiv1::{anonymous}::GlobalStatic<__cxxabiv1::{anonymous}::LibcppMutex>::instance’ has incomplete type
     _LIBCPP_SAFE_STATIC T GlobalStatic<T>::instance = {};
                           ^
    
    git-svn-id: https://llvm.org/svn/llvm-project/libcxxabi/trunk@359175 91177308-0d34-0410-b5e6-96231b3b80d8
    (cherry picked from commit f98261d3290e2b05e7714ba125d9315d87e9d62e)
    
    Bug: http://b/189279320
    Test: treehugger
    Change-Id: Idf967a477590de8baf88541aff3aff08ff15e187
    
  - Cleanup new cxa guard implementation.
    
    * Add TSAN annotations around the futex syscalls.
    * Test that the futex syscall wrappers actually work.
    * Fix bad names.
    
    git-svn-id: https://llvm.org/svn/llvm-project/libcxxabi/trunk@359069 91177308-0d34-0410-b5e6-96231b3b80d8
    (cherry picked from commit 11fe87d836527d01c0df6f8ad25d575c9baba7cc)
    
    Bug: http://b/189279320
    Test: treehugger
    Change-Id: I73ce984b425d40addd9b951370ec7d36fccfe010
    
  - Rewrite cxa guard implementation.
    
    This patch does three main things:
      (1) It re-writes the cxa guard implementation to make it testable.
      (2) Adds support for recursive init detection on non-apple platforms.
      (3) It adds a futex based implementation.
    
    The futex based implementation locks and notifies on a per-object basis, unlike the
    current implementation which uses a global lock for all objects. Once this patch settles
    I'll turn it on by default when supported.
    
    git-svn-id: https://llvm.org/svn/llvm-project/libcxxabi/trunk@359060 91177308-0d34-0410-b5e6-96231b3b80d8
    (cherry picked from commit 57e82af58dd4515ab4885f32273268f34f757101)
    
    Bug: http://b/189279320
    Test: treehugger
    Change-Id: Id518751bb508319b8491929092ddac1d0ccb73ad
    
  - [libc++abi] Create a macro for the 32 bit guard setting on ARM platforms
    
    Summary:
    The goal is to use a descriptive name for this feature, instead of just
    using __arm__.
    
    Reviewers: EricWF
    
    Subscribers: javed.absar, kristof.beyls, christof, jkorous, dexonsmith, libcxx-commits
    
    Tags: #libc
    
    Differential Revision: https://reviews.llvm.org/D60520
    
    git-svn-id: https://llvm.org/svn/llvm-project/libcxxabi/trunk@358106 91177308-0d34-0410-b5e6-96231b3b80d8
    (cherry picked from commit 1dc2c61c2a77bf864c7c627af72f1130a3e318ec)
    
    Bug: http://b/189279320
    Test: treehugger
    Change-Id: I0360c4a2cd4f9f6e90dd176c4fa37fdfb817832b
    
  - Fix incorrect change during refactoring.
    
    cxa_guard_abort should still broadcast on exit.
    
    git-svn-id: https://llvm.org/svn/llvm-project/libcxxabi/trunk@357956 91177308-0d34-0410-b5e6-96231b3b80d8
    (cherry picked from commit cb31f3d9f6ff64c044921996d2bb2efc4c028765)
    
    Bug: http://b/189279320
    Test: treehugger
    Change-Id: Ie916355d58cb03da1f0d006b3da2a284f93becf3
    
  - Further refactor cxa_guard.cpp
    
    This patch is a part of a series of patches to cleanup
    our implementation of __cxa_acquire et al. No functionality
    change was intended.
    
    This patch does two primary things.
    
    It introduces the GuardObject class to abstract the reading
    and writing to the guard object. In future, it will be used
    to ensure atomic accesses are used when needed.
    
    It also introduces the GuardValue class used to represent
    values of the guard object. It is an abstraction to access
    and write to the various different bits of a guard.
    
    git-svn-id: https://llvm.org/svn/llvm-project/libcxxabi/trunk@357804 91177308-0d34-0410-b5e6-96231b3b80d8
    (cherry picked from commit 45dccfe519d6ff73a41212f4f673ebafb196d688)
    
    Bug: http://b/189279320
    Test: treehugger
    Change-Id: Ida958365f627587e353ab74dd0c8d74c8f36deaf
    
  - Create RAII lock guard for global initialization lock.
    
    This patch is a part of a series of cleanups to cxa_guard.cpp.
    It should introduce no functionality change.
    
    This patch refactors the use of the global mutex and condvar into
    a RAII lock guard class. This improves correctness (since unlocks can't
    be forgotten). It also allows the unification of the non-threading and
    threading implementations.
    
    git-svn-id: https://llvm.org/svn/llvm-project/libcxxabi/trunk@357669 91177308-0d34-0410-b5e6-96231b3b80d8
    (cherry picked from commit 43cb674684655c8ca907f814e90c65b3ea5b9106)
    
    Bug: http://b/189279320
    Test: treehugger
    Change-Id: Ied307fc69e1ba563e5cb76e454084f9c5827e2d3
    
  - Always use is_initialized and set_initialized in cxa_guard.cpp
    
    This patch is part of a series of cleanups to cxa_guard.cpp.
    It should have no functionality change.
    
    git-svn-id: https://llvm.org/svn/llvm-project/libcxxabi/trunk@357668 91177308-0d34-0410-b5e6-96231b3b80d8
    (cherry picked from commit 40b41ca3d8fb69f5bec2ce65f0cb7490c3b048a6)
    
    Bug: http://b/189279320
    Test: treehugger
    Change-Id: I7b0d0db251a3ac960349321daca3fbc97f673b5b