Update git submodules
* Update platform/hardware/ril from branch 'master'
  to 5c1f34d91896e98616278ff2f3599604c74f6b66
  - Merge "Fix mismatched allocation/deallocation"
  - Fix mismatched allocation/deallocation
    
    When we use "new[]", we need to use "delete[]", not "delete".
    
    Test: TreeHugger
    Change-Id: Ie1caad9ffcd8ac9e2544b627ad85966178dc00a1
    
  - Merge "Merge Android 12"
  - Merge Android 12
    
    Bug: 202323961
    Merged-In: I6f522d6d244351a294cfa10defa2744cf5f16564
    Change-Id: I4b7101bc5f107cb39a290672951b7c36cbc41840
    
  - Merge sc-dev-plus-aosp-without-vendor@7634622
    
    Merged-In: I914766c7f155468a250afe5b8f42a16c57b1ea35
    Change-Id: I6f522d6d244351a294cfa10defa2744cf5f16564
    
  - [Telephony] Remove IOem in ril am: 899ef068c6
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/hardware/ril/+/14759714
    
    Change-Id: I914766c7f155468a250afe5b8f42a16c57b1ea35
    
  - [Telephony] Remove IOem in ril
    
    Bug: 171260715
    Test: make, atest com.android.internal.telephony.RILTest
    Change-Id: I9089ac911bbd5063b560d37dbc100fb9d60f21e0
    
  - Merge "Replace `ro.kernel.` with `ro.boot.`" am: 415413a355 am: 619e7f9672 am: 50e386b635
    
    Original change: https://android-review.googlesource.com/c/platform/hardware/ril/+/1676389
    
    Change-Id: If7984faac253709c522e847a616acb9ef252e1fd
    
  - Merge "Replace `ro.kernel.` with `ro.boot.`" am: 415413a355 am: 619e7f9672
    
    Original change: https://android-review.googlesource.com/c/platform/hardware/ril/+/1676389
    
    Change-Id: I1fa1a2c2013ece9bb8971629cd8e603c615be0bc
    
  - Merge "Replace `ro.kernel.` with `ro.boot.`" am: 415413a355
    
    Original change: https://android-review.googlesource.com/c/platform/hardware/ril/+/1676389
    
    Change-Id: Iba8d52a1d985d6bcb9c8e1b393a77749f30468c0
    
  - Merge "Remove local dynamic array" am: 33dda50e8a am: ff7fde0faf am: 7ecc69ca36
    
    Original change: https://android-review.googlesource.com/c/platform/hardware/ril/+/1666339
    
    Change-Id: I5e54e21bcd411b93f9190bd74a017ff72f114eea
    
  - Merge "Remove local dynamic array" am: 33dda50e8a am: ff7fde0faf
    
    Original change: https://android-review.googlesource.com/c/platform/hardware/ril/+/1666339
    
    Change-Id: I26829677d160cfccee2b30d58ccce6e36e6d1743
    
  - Merge "Remove local dynamic array" am: 33dda50e8a
    
    Original change: https://android-review.googlesource.com/c/platform/hardware/ril/+/1666339
    
    Change-Id: Ic7d1dbbae3855ea762eefcf2047036c0b99ac7f5
    
  - [automerger skipped] Mark ab/7061308 as merged in stage. am: 3b85c7fef5 -s ours am: 7376cf648c -s ours
    
    am skip reason: Change-Id I4fef14ff40117a98869e946351cc0ae672a99853 with SHA-1 14f36fec42 is in history
    
    Original change: undetermined
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: If47f1911201eefe533b0f148d6b965c15e1a3631
    
  - Merge "[LSC] Add LOCAL_LICENSE_KINDS to hardware/ril" am: a586a9c2d5 am: f5ed50edda am: 7fb343d5bb
    
    Original change: https://android-review.googlesource.com/c/platform/hardware/ril/+/1588039
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I52e23ec8943c69a13e6055cbc09726d07e47b960
    
  - [automerger skipped] Mark ab/7061308 as merged in stage. am: 3b85c7fef5 -s ours
    
    am skip reason: Change-Id I4fef14ff40117a98869e946351cc0ae672a99853 with SHA-1 14f36fec42 is in history
    
    Original change: undetermined
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I9e295e81a74325ae3d5a994a04187e62548bc52e
    
  - Merge "[LSC] Add LOCAL_LICENSE_KINDS to hardware/ril" am: a586a9c2d5 am: f5ed50edda
    
    Original change: https://android-review.googlesource.com/c/platform/hardware/ril/+/1588039
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I6d56dd50c58876b1315f01d77610ebef53ec13b4
    
  - Merge "Retire libqemu_pipe from libreference-ril" am: 3438d03c30 am: debcd7526f am: 3936861a84
    
    Original change: https://android-review.googlesource.com/c/platform/hardware/ril/+/1554914
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I8ea47c7628241fae5b93769914f8eff5fe4d869d
    
  - Merge "Retire libqemu_pipe from libreference-ril" am: 3438d03c30 am: debcd7526f
    
    Original change: https://android-review.googlesource.com/c/platform/hardware/ril/+/1554914
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Ic4e11dd39fbd97d6023071c73f87a8fc33b91554
    
  - Mark ab/6881855 as merged am: 503a11b0d8 am: 14f36fec42
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/hardware/ril/+/13111234
    
    Change-Id: Ibf314553e174e5ca27bf0fb881343178d5e7d95f
    
  - Merge "Map RIL_RadioTechnologyFamily to RadioTechnologyFamily correctly" am: 4729b84992 am: 33f79bed54 am: be43386d15 am: 4c09d5b971
    
    Original change: https://android-review.googlesource.com/c/platform/hardware/ril/+/1471647
    
    Change-Id: I79aaf694eff56ca6b83d4fc179f95539ce8d93f3
    
  - [automerger skipped] Skip ab/6749736 in stage. am: 93b625c199 -s ours am: 823eab4c05 -s ours am: 1b9a4091c5 -s ours
    
    am skip reason: Change-Id I271e6fb0abeae2cd4e3f9083dd48607d60a8c4ad with SHA-1 e9d0552de8 is in history
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/hardware/ril/+/12797313
    
    Change-Id: If67b62777698a4679c9821b02b5cbea3ec5882fe
    
  - [automerger skipped] Mark Android R (rvc-dev-plus-aosp-without-vendor@6692709) as merged am: 850741d2cb -s ours am: b675417913 -s ours am: 098fd136f5 -s ours am: 63aafded11 -s ours
    
    am skip reason: Change-Id I890e1b9395ebe8f17d5739fb3169f9a9b80282b0 with SHA-1 948e8c1a66 is in history
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/hardware/ril/+/12469984
    
    Change-Id: Ib5a09518c5583179bda43267006ddaeaa6ce87f6
    
  - Merge "Fix -Wformat error with explicit void* -> char* cast." am: 180d9e2e04 am: 2cc8c73b82 am: c0b71d31b0 am: e92568023f am: 986ec65138
    
    Original change: https://android-review.googlesource.com/c/platform/hardware/ril/+/1407077
    
    Change-Id: I66291cf285a2831a9a1126ac2b449e0ec6e1c76e
    
  - Fix -Wformat error with explicit void* -> char* cast.
    
    hardware/ril/reference-ril/reference-ril.c:1841:46: error: format specifies type 'char *' but the argument has type 'void *' [-Werror,-Wformat]
        snprintf(cmd, sizeof(cmd), "AT+CCHO=%s", data);
                                            ~~   ^~~~
    
    Bug: http://b/155835175
    Test: m
    Change-Id: I7fd819c6c452b56aae15429344320c4cdaed702c
    
  - [automerger skipped] Merge "Map the RAT included in ImsSmsMessage to RIL value correctly." am: d0412127b7 am: 16aff6bb6b am: bb7727bfa0 am: e9d0552de8 am: b380d7c867 -s ours
    
    am skip reason: Change-Id I34f377b7d41365a327de220cd4bd0f456514495e with SHA-1 03bccca295 is in history
    
    Original change: https://android-review.googlesource.com/c/platform/hardware/ril/+/1378659
    
    Change-Id: Ia05a49680a8f416273bce9489d87a763cdebae62
    
  - Merge "Update language to comply with Android's inclusive language guidance" am: a0d65e2267 am: 04bff7f6c8 am: cb3ef0078b am: bec1491f5b am: 44ccdd3fbc
    
    Original change: https://android-review.googlesource.com/c/platform/hardware/ril/+/1375725
    
    Change-Id: I201b64d5e8e82b85b5c5033fad4a0b2150deaabc
    
  - Map the RAT included in ImsSmsMessage to RIL value correctly.
    
    Test: TH
    Bug: 160646256
    Bug: 161405820
    Change-Id: I34f377b7d41365a327de220cd4bd0f456514495e
    
  - Merge "change parameter type for 32bit platform" am: f1575d44a9 am: ca26310e0c am: 948e8c1a66 am: 290349c559 am: 12c193e8f0
    
    Original change: https://android-review.googlesource.com/c/platform/hardware/ril/+/1353378
    
    Change-Id: I756ab18e054227d9ad4aa493928e404fd8329937
    
  - Merge "Add METADATA to ril: Apache2=NOTICE" am: 8e413723a6 am: 662ce93413 am: a92f99d12d am: fb46cd356c am: 4fa2cc451b
    
    Change-Id: I5f2c74033b35076aa602c313e41ff0822cd7414c
    
  - [automerger skipped] DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp into stag-aosp-master am: 569b5cec61 -s ours am: c22541211c am: fe36eda1e1 am: 063aec5450 -s ours
    
    am skip reason: subject contains skip directive
    
    Change-Id: Ib5ebc153a249ddd9eebfc3eb99303884599bbb18
    
  - [automerger skipped] DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp@6304901 into stag-aosp-master am: 4c514e82b1 -s ours am: a568c67f9f am: fe41cf3d74 am: ba397c38a6 -s ours
    
    am skip reason: subject contains skip directive
    
    Change-Id: I7313df0c2cb02192416b595691b114e3de6fe4a5