Update git submodules
* Update platform/frameworks/base from branch 'master'
  to 9e7ac57a6c8be0854d775b0e8dde3c11ac4136e3
  - Merge "Cancel NotificationTimeout alarms when canceling notification"
  - Cancel NotificationTimeout alarms when canceling notification
    
    If alarms with long timeouts are created, there is a risk of a
    crash in system_server because of alarm creation limit is reached:
    
    java.lang.IllegalStateException: Maximum limit of concurrent alarms 500
    reached for uid: 1000, callingPackage: android
    
    To avoid this cancel alarms if Notifications are canceled.
    
    Suggested-by: Snild Dolkow <snild@sony.com>
    
    Bug: 186456631
    Change-Id: I63343b9450fc817ec6a2f46329de346320463c46