Update git submodules
* Update platform/hardware/qcom/sm8150/display from branch 'master'
  to 7f2aafbff147ec2a30ca4243385ebb0b7aec1cfc
  - hwc_session: move a break
    
    As written, this loop only runs once, which makes clang's new warning
    unhappy:
    
    hardware/qcom/sm8150/display/sdm/libs/hwc2/hwc_session.cpp:934:51:
    error: loop will run at most once (loop increment never executed)
    [-Werror,-Wunreachable-code-loop-increment]
    
    Chatting with qcom, this appears to be a bug, and the best fix is to
    move the `break` into the `if`.
    
    Bug: 150166387
    Test: TreeHugger
    Change-Id: Icb64eed5b894b9188f5265094587dd802207ba66
    

* Update platform/superproject from branch 'master'
  to 38f05ff846752b3cac0237d9769df90067f58bd7
  - Update git submodules
    
    * Update hardware/qcom/sm8150/display from branch 'master'
      to 7f2aafbff147ec2a30ca4243385ebb0b7aec1cfc
      - hwc_session: move a break
        
        As written, this loop only runs once, which makes clang's new warning
        unhappy:
        
        hardware/qcom/sm8150/display/sdm/libs/hwc2/hwc_session.cpp:934:51:
        error: loop will run at most once (loop increment never executed)
        [-Werror,-Wunreachable-code-loop-increment]
        
        Chatting with qcom, this appears to be a bug, and the best fix is to
        move the `break` into the `if`.
        
        Bug: 150166387
        Test: TreeHugger
        Change-Id: Icb64eed5b894b9188f5265094587dd802207ba66