Update git submodules
* Update platform/build/soong from branch 'master'
  to 27a8719b0f7ae6a079d921ec2f515cb06a1340ba
  - Merge "Integrate bazelenv.sh environment variables into soong_ui environment."
  - Integrate bazelenv.sh environment variables into soong_ui environment.
    
    This removes the need to source bazelenv.sh for USE_BAZEL_ANALYSIS, and
    unifies mixed builds to use the checked in tools/bazel and bazelrc.
    
    It also unifies all bazel-related output to be in out/bazel.
    
    Without aosp/1502095, this change still requires toplevel_output_directories to be an empty
    list, otherwise there'll be this error:
    
    ERROR: Directories specified with toplevel_output_directories should be
    ignored and can not be used as sources.
    
    Test: With aosp/1441774: rm -rf out/ && lunch aosp_cf_x86_auto && USE_BAZEL_ANALYSIS=1 m libc && prebuilts/build-tools/linux-x86/bin/ninja -f out/combined-aosp_cf_x86_auto.ninja -t commands libc | grep bazel-out | wc -l # 2 results
    Change-Id: I69b217ec88da531415792bb6e04b6a194ca4718d
    

* Update platform/superproject from branch 'master'
  to 2355ac90029e27f5f9c4858f109629cc4d94f61c
  - Update git submodules
    
    * Update build/soong from branch 'master'
      to 27a8719b0f7ae6a079d921ec2f515cb06a1340ba
      - Merge "Integrate bazelenv.sh environment variables into soong_ui environment."
      - Integrate bazelenv.sh environment variables into soong_ui environment.
        
        This removes the need to source bazelenv.sh for USE_BAZEL_ANALYSIS, and
        unifies mixed builds to use the checked in tools/bazel and bazelrc.
        
        It also unifies all bazel-related output to be in out/bazel.
        
        Without aosp/1502095, this change still requires toplevel_output_directories to be an empty
        list, otherwise there'll be this error:
        
        ERROR: Directories specified with toplevel_output_directories should be
        ignored and can not be used as sources.
        
        Test: With aosp/1441774: rm -rf out/ && lunch aosp_cf_x86_auto && USE_BAZEL_ANALYSIS=1 m libc && prebuilts/build-tools/linux-x86/bin/ninja -f out/combined-aosp_cf_x86_auto.ninja -t commands libc | grep bazel-out | wc -l # 2 results
        Change-Id: I69b217ec88da531415792bb6e04b6a194ca4718d
        
  - Added repo manifest.