Update git submodules
* Update platform/build.git from branch 'master'
  to f14e8caca799d443f9634a544ec79bfa9688f08c
  - Merge "Fix build break for vendor freeze"
  - Fix build break for vendor freeze
    
    1. Fix build break when rebuilding vendor images in
    sign_target_files_apks, because of missing SYSTEM/build.prop:
      File ".../add_img_to_target_files.py", line 999, in <module>
      File ".../add_img_to_target_files.py", line 993, in main
      File ".../add_img_to_target_files.py", line 854, in AddImagesToTargetFiles
      File ".../add_img_to_target_files.py", line 229, in AddVendor
      File ".../add_img_to_target_files.py", line 391, in CreateImage
      File "add_img_to_target_files/common.py", line 394, in __init__
        self._fingerprint = self.CalculateFingerprint()
      File "add_img_to_target_files/common.py", line 537, in CalculateFingerprint
        self.GetBuildProp("ro.build.version.release"),
      File "add_img_to_target_files/common.py", line 457, in GetBuildProp
        raise ExternalError("couldn't find %s in build.prop" % (prop,))
    ExternalError: couldn't find ro.build.version.release in build.prop
    
    2. Support more scenarios (non-AB, RADIO...)
    
    Bug: 192422274
    Change-Id: I792b0a2c2354ed9312730e322ce28df49b3c2f7f