Update git submodules
* Update platform/external/selinux from branch 'master'
  to 74de00c1080b3568bb3b0b65f1c5c6a35b46de04
  - label_file.c: Fix MAC build
    
    On Android, the label_file.c file is compiled for all platforms,
    including OSX. OSX has a slightly different prototype for the
    getxattr function.
    
    ssize_t getxattr(const char *path, const char *name, void *value, size_t size, u_int32_t position, int options);
    
    which causes a compile error when compiling libselinux on OSX.
    
      ```
      external/selinux/libselinux/src/label_file.c:1038:37: error: too few arguments to function call, expected 6, have 4
                                           read_digest, SHA1_HASH_SIZE);
                                                                    ^
      /Applications/Xcode9.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/sys/xattr.h:61:1: note: 'getxattr' declared here
      ssize_t getxattr(const char *path, const char *name, void *value, size_t size, u_int32_t position, int options);
      ^
      1 error generated.
      ```
    
    On OSX builds, add the additional arguments so that the code compiles.
    
    As both SELinux labels and the restorecon partial digest are stored in
    extended attributes, it's theoretically possible that someone
    could assign SELinux labels and hash digests on OSX filesystems.
    Doing so would be extremely weird and completely untested, but
    theoretically possible.
    
    Fixes: 149060079
    Test: compiles on both Linux and OSX
    Change-Id: Ib80057ab09e48cc90dd37c2cc3c7046d0bdfdc9b
    

* Update platform/superproject from branch 'master'
  to a18294508b33d86044009c455492ae882b809864
  - Update git submodules
    
    * Update external/selinux from branch 'master'
      to 74de00c1080b3568bb3b0b65f1c5c6a35b46de04
      - label_file.c: Fix MAC build
        
        On Android, the label_file.c file is compiled for all platforms,
        including OSX. OSX has a slightly different prototype for the
        getxattr function.
        
        ssize_t getxattr(const char *path, const char *name, void *value, size_t size, u_int32_t position, int options);
        
        which causes a compile error when compiling libselinux on OSX.
        
          ```
          external/selinux/libselinux/src/label_file.c:1038:37: error: too few arguments to function call, expected 6, have 4
                                               read_digest, SHA1_HASH_SIZE);
                                                                        ^
          /Applications/Xcode9.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/sys/xattr.h:61:1: note: 'getxattr' declared here
          ssize_t getxattr(const char *path, const char *name, void *value, size_t size, u_int32_t position, int options);
          ^
          1 error generated.
          ```
        
        On OSX builds, add the additional arguments so that the code compiles.
        
        As both SELinux labels and the restorecon partial digest are stored in
        extended attributes, it's theoretically possible that someone
        could assign SELinux labels and hash digests on OSX filesystems.
        Doing so would be extremely weird and completely untested, but
        theoretically possible.
        
        Fixes: 149060079
        Test: compiles on both Linux and OSX
        Change-Id: Ib80057ab09e48cc90dd37c2cc3c7046d0bdfdc9b