Update git submodules
* Update platform/build/soong from branch 'master'
  to 4a349ab66ba23df988e18956bdeb08c158926516
  - Merge "Friendly error message on apex_available and min_sdk_version checks"
  - Friendly error message on apex_available and min_sdk_version checks
    
    1) suggest a fix at the end of the message
    2) add new lines around the dependency path so that they are visually
    separated from rest of the error message
    
    Bug: N/A
    Test: m with an intentional break
    error: bionic/apex/Android.bp:32:1: module "com.android.runtime" variant "android_common_com.android.runtime_image": "libutils_headers" requires "libsystem_headers" that doesn't list the APEX under 'apex_available'.
    
    Dependency path:
               via tag apex.dependencyTag: { name:executable payload:true}
        -> crash_dump{os:android,image:,arch:arm_armv8-a,sdk:,apex:apex10000}
               via tag cc.libraryDependencyTag: { Kind:staticLibraryDependency Order:normalLibraryDependency wholeStatic:false reexportFlags:false explicitlyVersioned:false dataLib:false ndk:false staticUnwinder:false makeSuffix: skipApexAllowedDependenciesCheck:false excludeInApex:false}
        -> libtombstoned_client_static{os:android,image:,arch:arm_armv8-a,sdk:,link:static,apex:apex10000}
               via tag cc.libraryDependencyTag: { Kind:staticLibraryDependency Order:normalLibraryDependency wholeStatic:true reexportFlags:true explicitlyVersioned:false dataLib:false ndk:false staticUnwinder:false makeSuffix: skipApexAllowedDependenciesCheck:false excludeInApex:false}
        -> libcutils{os:android,image:,arch:arm_armv8-a,sdk:,link:static,asan:,apex:apex10000}
               via tag cc.libraryDependencyTag: { Kind:headerLibraryDependency Order:normalLibraryDependency wholeStatic:false reexportFlags:false explicitlyVersioned:false dataLib:false ndk:false staticUnwinder:false makeSuffix: skipApexAllowedDependenciesCheck:false excludeInApex:false}
        -> libutils_headers{os:android,image:,arch:arm_armv8-a,sdk:,asan:,apex:apex10000}
               via tag cc.libraryDependencyTag: { Kind:headerLibraryDependency Order:normalLibraryDependency wholeStatic:false reexportFlags:true explicitlyVersioned:false dataLib:false ndk:false staticUnwinder:false makeSuffix: skipApexAllowedDependenciesCheck:false excludeInApex:false}
        -> libsystem_headers{os:android,image:,arch:arm_armv8-a,sdk:,asan:,apex:apex10000}
    
    Consider adding "com.android.runtime" to 'apex_available' property of "libsystem_headers"
    
    Change-Id: I09f92c3086ea433780133a33ba0ad73baee6dc41