Update git submodules
* Update device/google/cuttlefish from branch 'master'
  to b7ea536abc755c37b11a4c78c438295aa2c4eae7
  - Merge "Mark android.hardware.audio.core AIDL as missing"
  - Mark android.hardware.audio.core AIDL as missing
    
    android.hardware.audio.core is the new AIDL audio HAL
    which is being implemented. Due to large size of the
    interface, it is being implemented in an incremental
    fashion. The current state of the implementation does
    not allow for providing all the functionality used
    by Cuttlefish and the emulator.
    
    Bug: 205884982
    Test: m
    Merged-In: I44fbb56c2937f580a09d0e58912ed1fedfb4bc5c
    Change-Id: I44fbb56c2937f580a09d0e58912ed1fedfb4bc5c
    (cherry picked from commit edbd5206d5bc72b0b799251478ed2981abaa9acc)
    

* Update platform/frameworks/av from branch 'master'
  to 04a0dc5ad3e284721da71b2150b9522c4274a538
  - Merge "Add AIDL HAL server to audioserver.rc"
  - Add AIDL HAL server to audioserver.rc
    
    Also remove names of legacy "2.0" implementations
    
    Bug: 205884982
    Test: atest VtsHalAudioCoreTargetTest
    Merged-In: I8c8e4042b23a3ba94801d4bc9c0fb98192ea0fc8
    Change-Id: I8c8e4042b23a3ba94801d4bc9c0fb98192ea0fc8
    (cherry picked from commit 6aaffb464a74f3d1a62c475f3efd75c60a5b7e7c)
    

* Update platform/frameworks/base from branch 'master'
  to 58e6e6d4484ab3184166d32fb7fd35145b2eae5d
  - Merge "audio: Clarify comments on AudioPortMixExt fields"
  - audio: Clarify comments on AudioPortMixExt fields
    
    Specify that '0' means 'unlimited' for
    AudioPortMixExt.maxOpenStreamCount, and 'all opened streams'
    for maxActiveStreamCount.
    
    Bug: 205884982
    Test: N/A
    Merged-In: Ia212fef049778a85046e3333faa0ddf8fe167c1f
    Change-Id: Ia212fef049778a85046e3333faa0ddf8fe167c1f
    (cherry picked from commit 52ca76ed07d48f1d9b884a7082dd7481e35eb5c8)
    

* Update platform/hardware/interfaces from branch 'master'
  to 2468ff5608843bdae8acd938cf6f4979d6e6964b
  - Merge changes from topic "upstream-audio-aidl-hal"
    
    * changes:
      Explicitly depend on V1 of android.media.audio.common.types
      Explicitly depend on audio.common-V1
      audio HAL: initial VTS tests
      audio HAL: Minimal example implementation
      audio HAL: Initial AIDL interfaces
    
  - Explicitly depend on V1 of android.media.audio.common.types
    
    ... for the same reason as cc489264afe295ffe9e01cf97d9bf43e690f7d84
    
    Bug: 225941299
    Test: m
    Merged-In: I269d61c8c441b3db0832f5450f5e5a84a5989a99
    Change-Id: I269d61c8c441b3db0832f5450f5e5a84a5989a99
    (cherry picked from commit 446519a3707c71b71c4f3148779f76a7b97d01cb)
    
  - Explicitly depend on audio.common-V1
    
    Background:
    
    android.hardware.audio.common was frozen in the upstream tm-dev.
    Previously, the interface had only V1 (as the in-development version)
    and it was in the VNDK. However, after the freeze, it will have V1 and
    V2, and only V1 will remain in the VNDK, because we can't have multiple
    versions of the same AIDL interface in VNDK (it's just waste of memory).
    
    android.hardware.audio.core is a new AIDL interface that doesn't exist
    in TM. It is also a member of VNDK and imports the audio.common
    interface. So far, the import has been done without an explicit version
    number (i.e. `imports: ["android.hardware.audio.common"]`). As a result,
    V1 was imported before the freeze, and V2 (the latest) will be imported
    after the freeze.
    
    Problem:
    
    audio.core depending on audio.common-V2 is NOT allowed since the former
    is a member of VNDK, but the latter isn't. VNDK should form a closure.
    We are actually hitting this:
    
    ```
    > error: hardware/interfaces/audio/aidl/Android.bp:71:1: module
    "android.hardware.audio.core-V1-ndk" variant
    "android_vendor.Tiramisu_arm64_armv8-a_static" (created by module
    "android.hardware.audio.core-V1-ndk-generator" (created by module
    "android.hardware.audio.core_interface")): (native:vendor:vndk) should
    not link to "android.hardware.audio.common-V2-ndk" (native:vendor):
    VNDK-core must only depend on VNDK-core or VNDK-SP
    ```
    
    To fix this, make the dependency to audio.common to be explicit about
    the version. This change can't be uploaded to tm-dev as audio.core
    doesn't exist there, and must be submitted before the AIDL APIs are
    frozen there.
    
    Bug: 225941299
    Test: m
    
    Merged-In: Iadc96d558d5c7431b0a2b0cbd28b99319a24ee44
    Change-Id: Iadc96d558d5c7431b0a2b0cbd28b99319a24ee44
    (cherry picked from commit cc489264afe295ffe9e01cf97d9bf43e690f7d84)
    
  - audio HAL: initial VTS tests
    
    Tests basic functionality for enumerating
    capabilities of an audio module, audio patches
    creation, and opening of I/O streams.
    
    Bug: 205884982
    Test: atest VtsHalAudioCoreTargetTest
    Merged-In: I7c7c3c7008f2fc43db1542455c74444a08e55534
    Change-Id: I7c7c3c7008f2fc43db1542455c74444a08e55534
    (cherry picked from commit 7abc70f9085e56aac85c97b30c8c4c1a3b97b63f)
    
  - audio HAL: Minimal example implementation
    
    Implements basic functionality for enumerating
    capabilities of an audio module, audio patches
    creation, and opening of I/O streams.
    
    Bug: 205884982
    Test: atest VtsHalAudioCoreTargetTest
    Merged-In: Ie5d67e9192a598260e762ae9368f99592c8ad97e
    Change-Id: Ie5d67e9192a598260e762ae9368f99592c8ad97e
    (cherry picked from commit ecdc6ca8e872a0478fae7d76b1ad4d805b024eed)
    
  - audio HAL: Initial AIDL interfaces
    
    This adds basic support for enumerating capabilities
    of an audio module, creation of patches, and opening of
    I/O streams.
    
    Bug: 205884982
    Test: atest VtsHalAudioCoreTargetTest
    Merged-In: Ib1ef13c95d338b6ef1bde7d87dcd675fc1d35e85
    Change-Id: Ib1ef13c95d338b6ef1bde7d87dcd675fc1d35e85
    (cherry picked from commit ee2747826449824e29a464a7c94943cc181511af)