Update git submodules
* Update platform/external/rust/cxx from branch 'master'
  to 8624dbf1095c20f36ab9d79805ff2ea500a0f12f
  - Upgrade rust/cxx to 971082d9dc57e581e046b1b10596a97c41287374
    
    Test: make
    Change-Id: I6190988d7ba10024d89c2aed497fad42462fcdca
    
  - Add rust::String utf-16 constructors to website
    
  - Release 1.0.51
    
  - Lockfile update
    
  - Merge pull request #906 from Gerharddc/master
    
    Add UTF-16 rust::String initialization
  - Added UTF-16 rust::String initialization
    
    This patch exposes String::from_utf16 to the C++ interface
    for rust::String.
    
  - Avoid inheriting formatter flags in some Display impls
    
    The previous implementation would produce wrong unintentional output
    when formatting with alignment or padding, such as {:<15}.
    
  - Release 1.0.50
    
  - Lockfile update
    
  - Merge pull request #904 from dtolnay/sliceofalias
    
    Support slice of trivial extern type alias
  - Support slice of trivial extern type alias
    
  - Update ui test suite to nightly-2021-07-21
    
  - Delete derive_nonclone ui test
    
    Starting with nightly-2021-07-20, this test annoyingly produces
    different diagnostics depending on whether the `rust-src` Rustup
    component is installed, which is annoying for contributors running the
    ui test suite locally. It is not super high value to have this test.
    
  - Update ui test suite to nightly-2021-07-20
    
  - Disable clippy CI due to clippy crash
    
    Clippy crash: https://github.com/rust-lang/rust-clippy/issues/7423
    
        thread 'rustc' panicked at '`LateContext::typeck_results` called outside of body', src/tools/clippy/clippy_lints/src/use_self.rs:213:20
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    
        error: internal compiler error: unexpected panic
    
        note: the compiler unexpectedly panicked. this is a bug.
    
        query stack during panic:
        #0 [analysis] running analysis passes on this crate
        end of query stack
    
  - Merge pull request #893 from ccontavalli/hermetic-cargo
    
    bazel: don't use cargo in $PATH, make the build hermetic.
  - bazel: don't use cargo in $PATH, make the build hermetic.
    
    Background:
    tools/bazel/vendor is just running 'cargo', hoping to find it somewhere
    in $PATH.
    
    Problem:
    rules_rust try to be hermetic, and not use the cargo of the system, but
    the cargo of the toolchain installed.
    This means that if the cargo on the system is different from the cargo
    used by cxx.rs, or the system does not have a cargo at all, bad things
    will happen when using cxx.rs.
    
    In this change:
    use the recommended way to find/install the tool. Thanks to Andre in the
    bazel rust slack channel for pointers and help.