Update git submodules
* Update kernel/build from branch 'master'
  to dc2eab43a9522c583d613c499548adb54ee65dde
  - kleaf: Delete unused trim_nonlisted_kmi_setting. (2nd attempt)
    
    This reverts commit b17ad4ec7f5ac61fea316dffa4d7b87428895cd6.
    
    It is replaced by force_disable_trim now. The setting is not
    used or set anywhere, so delete the setting and all transitions
    associated with it.
    
    The revert is rebased on top of the latest changes where
    force_disable_trim is set to True for kasan builds.
    
    Reason for revert: build breakage
    Bug: 270670362
    Bug: 269674780
    
    Change-Id: Ie9cc2ce7f1a4f4c815cc7e06c50935c29e593580
    
  - kleaf: Add tests for trimming.
    
    Add tests that trim_nonlisted_kmi of a device build
    does not affect the base_kernel.
    
    Add tests for notrim_transition that checks that
    trimming is indeed disabled.
    
    Test: TH
    Bug: 269674780
    
    Change-Id: I56f1fa948d2f68b849918178dd9de3baca7b7c4f
    
  - Kleaf: Add --notrim flag.
    
    Exposes //build/kernel/kleaf/impl:force_disable_trim
    as the `--notrim` flag that disables TRIM_NONLISTED_KMI
    globally during device bringup.
    
    This is a temporary measure for devices which does not
    have a symbol list added, yet trimming has enabled on
    the base kernel.
    
    Test: TH
    Bug: 270670362
    Bug: 269674780
    
    Change-Id: If7ac13ac4225a33a34fe968fd568e8757d15a19f
    
  - Reland "kleaf: Fix progress_message and config_tags."
    
    This reverts commit 57f507b130ab495f3aa65c4dab1a9306131f0f0b.
    
    Reason for revert: build breakage
    Bug: 270670362
    Bug: 269674780
    
    Change-Id: Ie6f26dc0132fe5611b4f76158426c4cc6d7447f5
    
  - kleaf: kasan: Disable trimming for kasan builds.
    
    * This is currently causing build breakages due
    to the missing symbol `kcov_common_handle`.
    
    * Similarly to ABI extraction, disable symbol
    list trimming when `--kasan` flag is provided.
    
    Bug: 270670362
    Bug: 269674780
    Change-Id: I8452908e15ea3b7eb8b9b81d4c9da08baee43828
    Signed-off-by: Ulises Mendez Martinez <umendez@google.com>
    Signed-off-by: Yifan Hong <elsk@google.com>
    
  - Reland "kleaf: Add back force_disable_trim bool_setting."
    
    This reverts commit 1c1edcada4ba76575ed5b72807b6e34c46ab6d04.
    
    Instead of relying reading trim configuration from
    a string_setting trim_nonlisted_kmi_setting,
    read from ctx.attr.trim_nonlisted_kmi directly.
    The attribute is always select()'ed based on
    force_disable_trim, so that it is affected by
    notrim_transition.
    
    With this change, because the scope of ctx.attr.trim_nonlisted_kmi
    only affects the current target, for regular builds (that
    doesn't have notrim_transition enabled), the base_kernel is not
    affected by the trim_nonlisted_kmi setting of the device kernel.
    
    Implementation details: _trim_nonlisted_kmi_transition_impl is cleared
    because of the following error:
    
      Error: No attribute 'trim_nonlisted_kmi'. Either this attribute
      does not exist for this rule or is set by a select. Starlark rule
      transitions currently cannot read attributes behind selects.
    
    The setting is already unused and is pending removal,
    so just set the function to no-op for now to silence this error.
    
    Reason of revert: relanding change
    Bug: 270670362
    Bug: 269674780
    
    Change-Id: I6a1f7a9ca26c034b19c41453fc55eedf74628407
    
  - kleaf: rework kernel_config_option_test combined_test
    
    Instead of symlinking the actual config to the expected config
    names (e.g. .config -> notrim_config, etc.), do the other way around:
    
    - Get the list of expected configs
    - merge them to a single list
    - Compare the full expected list against the actual config.
    
    This prepares for the follow up CL where kasan disables trimming.
    
    Test: TH
    Bug: 270670362
    Bug: 269674780
    
    Change-Id: Ia4ef059116579e9d4356f855463b2bf723a71b4a