Update git submodules
* Update platform/packages/apps/Messaging from branch 'master'
  to 919cb6afdd4b543bcf16b24ce1638dd7a2602b3d
  - Merge "Fix NoSuchMethodError for getTypeInfo()"
  - Fix NoSuchMethodError for getTypeInfo()
    
    Load an icon image for audio files from app resources instead because
    ContentResolver#getTypeInfo() is for API level >= 29.
    And it includes size-fit ic_photo_library_light images also.
    
    Bug: 159987488
    Test: Manual
    
    Change-Id: Ie8f766f148a30e105e598e4b7e6b1b22bccda6ae
    Signed-off-by: Taesu Lee <taesu82.lee@samsung.com>
    

* Update platform/superproject from branch 'master'
  to c965b1e13693e4f7b2aed3c66167123e7e952c8b
  - Update git submodules
    
    * Update packages/apps/Messaging from branch 'master'
      to 919cb6afdd4b543bcf16b24ce1638dd7a2602b3d
      - Merge "Fix NoSuchMethodError for getTypeInfo()"
      - Fix NoSuchMethodError for getTypeInfo()
        
        Load an icon image for audio files from app resources instead because
        ContentResolver#getTypeInfo() is for API level >= 29.
        And it includes size-fit ic_photo_library_light images also.
        
        Bug: 159987488
        Test: Manual
        
        Change-Id: Ie8f766f148a30e105e598e4b7e6b1b22bccda6ae
        Signed-off-by: Taesu Lee <taesu82.lee@samsung.com>