Update git submodules
* Update platform/superproject from branch 'master'
  to 0807dfb3bbd031675ff4a0777d5fd293d6ce008a
  - Update git submodules
    
    * Update build/soong from branch 'master'
      to 724c5fd8138d46193adf6de74aba79a37627f897
      - Merge "Revert "Support libraries (not just boot jars) that have hiddenapi""
      - Revert "Support libraries (not just boot jars) that have hiddenapi"
        
        This reverts commit e5b5657f875be27cc8f8fcf3a1e6fa814d794c95.
        
        The reverted change was added in order to gather the information about
        the hiddenapi that is needed for the runtime to enforce the hiddenapi
        accessibility rules. Without it the build broke with the following
        error when the android.test.base library was not in the
        PRODUCT_BOOT_JARS list:
        
        AssertionError: Error processing: frameworks/base/config/hiddenapi-greylist.txt
        The following entries were unexpected:
          Ljunit/framework/TestSuite;->isPublicTestMethod(Ljava/lang/reflect/Method;)Z
          Landroid/test/AndroidTestCase;->setTestContext(Landroid/content/Context;)V
          Landroid/test/InstrumentationTestCase;->runMethod(Ljava/lang/reflect/Method;I)V
          Landroid/test/AndroidTestCase;->getTestContext()Landroid/content/Context;
          Ljunit/framework/TestCase;->fName:Ljava/lang/String;
          Ljunit/framework/TestSuite;->isTestMethod(Ljava/lang/reflect/Method;)Z
          Please visit go/hiddenapi for more information.
        
        However, it turns out that the runtime does not currently enforce
        access to the hiddenapi of libraries that are not on the
        PRODUCT_BOOT_JARS list. Gathering hiddenapi information for a library
        not on the PRODUCT_BOOT_JARS list breaks the
        CtsHiddenApiBlacklistApi27TestCases and
        CtsHiddenApiBlacklistApi28TestCases test modules which use that
        information to ensure that correct runtime behavior.
        
        This change is being reverted simply because it does not work.
        
        Bug: 126519737
        Bug: 73711752
        Test: make REMOVE_ATB_FROM_BCP=true droid and make droid
        Change-Id: I1b4a7786b1061effa0e2d37832afa8570953a06e