Update git submodules
* Update platform/external/selinux from branch 'master'
  to 28cf7ea80d067f070453d47a9a1881517f14d433
  - perfcrastination: Merge remote-tracking branch 'aosp/upstream-master' into mymerge
    
    Followed the following steps:
      # In repo client
      cd external/selinux
      repo sync .
      repo start mymerge .
      git merge aosp/upstream-master --no-ff # resolve any conflicts
      repo upload .
    
    Test: device compiles and boots
    Change-Id: I2b5b1a201d43ee94fc909dd8bca5595bc7f0e522
    
  - libselinux: fix selinux_restorecon() on non-SELinux hosts
    
    The kernel only supports seclabel if it is >= 2.6.30 _and_
    SELinux is enabled, since seclabel is generated by SELinux
    based partly on policy (e.g. is the filesystem type configured in policy
    with a labeling behavior that supports userspace labeling). For some
    reason, when this logic was moved from setfiles to libselinux,
    the test of whether SELinux was enabled was dropped.  Restore it.
    
    This is necessary to enable use of setfiles on non-SELinux hosts
    without requiring explicit use of the -m option.
    
    Fixes: 602347c7422e971a5674fe2767267a96e3b4f61c ("policycoreutils: setfiles - Modify to use selinux_restorecon")
    Reported-by: sajjad ahmed <sajjad_ahmed782@yahoo.com>
    Signed-off-by: Stephen Smalley <sds@tycho.nsa.gov>
    Cc: Richard Haines <richard_c_haines@btinternet.com>
    Reported-by: sajjad ahmed &lt;<a href="mailto:sajjad_ahmed782@yahoo.com" target="_blank">sajjad_ahmed782@yahoo.com</a>&gt;<br>
    Signed-off-by: Stephen Smalley &lt;<a href="mailto:sds@tycho.nsa.gov" target="_blank">sds@tycho.nsa.gov</a>&gt;<br>
    
  - python/semanage module: Fix handling of -a/-e/-d/-r options
    
    Previous code traceback-ed when one of the mentioned option was used without
    any argument as this state was not handled by the argument parser.
    
    action='store' stores arguments as a list while the original
    action='store_const' used str therefore it's needed to convert list to str
    before it's sent to moduleRecords class.
    
    Fixes:
    ^_^ semanage module -a
    Traceback (most recent call last):
      File "/usr/sbin/semanage", line 963, in <module>
        do_parser()
      File "/usr/sbin/semanage", line 942, in do_parser
        args.func(args)
      File "/usr/sbin/semanage", line 608, in handleModule
        OBJECT.add(args.module_name, args.priority)
      File "/usr/lib/python3.7/site-packages/seobject.py", line 402, in add
        if not os.path.exists(file):
      File "/usr/lib64/python3.7/genericpath.py", line 19, in exists
        os.stat(path)
    TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
    
  - python/semanage: Update semanage to use python3
    
    semanage uses seobject which uses setools which is python 3 only.
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
    
  - python/semanage: Drop python shebang from seobject.py
    
    seobject.py is not supposed to be used as entrypoint therefore the shebang is
    unnecessary. It also doesn't need execute bits.
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
    
  - python: always use python3 in the shebang of programs using setools
    
    setools 4.2.0 dropped support for Python 2. On systems where
    /usr/bin/python is Python 2, several tools are now broken because of
    this. Update the shebang of these tools to /usr/bin/python3.
    
    For future reference, as semanage/seobject.py, sepolicy and sepolgen
    import setools, every program that uses one of these modules need to be
    run with Python 3. The following programs do not use any of these
    modules so their shebangs have not been modified:
    
        dbus/selinux_server.py
        libsemanage/utils/semanage_migrate_store
        mcstrans/share/util/mlscolor-test
        mcstrans/share/util/mlstrans-test
        sandbox/start
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - python/sepolicy: drop python shebang from the module
    
    The files in sepolicy's module directory are not supposed to used as
    executable files. The shebang line is therefore not needed.
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - libsemanage: genhomedircon - improve handling large groups
    
    getgrnam_r() uses a preallocated buffer to store a structure containing
    the broken-out fields of the record in the group database. The size of
    this buffer is usually sysconf(_SC_GETGR_R_SIZE_MAX) == 1024 and it is
    not enough for groups with a large number of users.  In these cases,
    getgrnam_r() returns -1 and sets errno to ERANGE and the caller can
    retry with a larger buffer.
    
    Fixes:
    $ semanage login -a -s user_u -r s0-s0:c1.c2 '%largegroup'
    libsemanage.semanage_direct_commit: semanage_genhomedircon returned error code -1. (Numerical result out of range).
    OSError: Numerical result out of range
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
    

* Update platform/superproject from branch 'master'
  to a9203ccef78f855715339388f74abc6a7939c1c5
  - Update git submodules
    
    * Update external/selinux from branch 'master'
      to 28cf7ea80d067f070453d47a9a1881517f14d433
      - perfcrastination: Merge remote-tracking branch 'aosp/upstream-master' into mymerge
        
        Followed the following steps:
          # In repo client
          cd external/selinux
          repo sync .
          repo start mymerge .
          git merge aosp/upstream-master --no-ff # resolve any conflicts
          repo upload .
        
        Test: device compiles and boots
        Change-Id: I2b5b1a201d43ee94fc909dd8bca5595bc7f0e522
        
      - libselinux: fix selinux_restorecon() on non-SELinux hosts
        
        The kernel only supports seclabel if it is >= 2.6.30 _and_
        SELinux is enabled, since seclabel is generated by SELinux
        based partly on policy (e.g. is the filesystem type configured in policy
        with a labeling behavior that supports userspace labeling). For some
        reason, when this logic was moved from setfiles to libselinux,
        the test of whether SELinux was enabled was dropped.  Restore it.
        
        This is necessary to enable use of setfiles on non-SELinux hosts
        without requiring explicit use of the -m option.
        
        Fixes: 602347c7422e971a5674fe2767267a96e3b4f61c ("policycoreutils: setfiles - Modify to use selinux_restorecon")
        Reported-by: sajjad ahmed <sajjad_ahmed782@yahoo.com>
        Signed-off-by: Stephen Smalley <sds@tycho.nsa.gov>
        Cc: Richard Haines <richard_c_haines@btinternet.com>
        Reported-by: sajjad ahmed &lt;<a href="mailto:sajjad_ahmed782@yahoo.com" target="_blank">sajjad_ahmed782@yahoo.com</a>&gt;<br>
        Signed-off-by: Stephen Smalley &lt;<a href="mailto:sds@tycho.nsa.gov" target="_blank">sds@tycho.nsa.gov</a>&gt;<br>
        
      - python/semanage module: Fix handling of -a/-e/-d/-r options
        
        Previous code traceback-ed when one of the mentioned option was used without
        any argument as this state was not handled by the argument parser.
        
        action='store' stores arguments as a list while the original
        action='store_const' used str therefore it's needed to convert list to str
        before it's sent to moduleRecords class.
        
        Fixes:
        ^_^ semanage module -a
        Traceback (most recent call last):
          File "/usr/sbin/semanage", line 963, in <module>
            do_parser()
          File "/usr/sbin/semanage", line 942, in do_parser
            args.func(args)
          File "/usr/sbin/semanage", line 608, in handleModule
            OBJECT.add(args.module_name, args.priority)
          File "/usr/lib/python3.7/site-packages/seobject.py", line 402, in add
            if not os.path.exists(file):
          File "/usr/lib64/python3.7/genericpath.py", line 19, in exists
            os.stat(path)
        TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
        
        Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
        
      - python/semanage: Update semanage to use python3
        
        semanage uses seobject which uses setools which is python 3 only.
        
        Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
        
      - python/semanage: Drop python shebang from seobject.py
        
        seobject.py is not supposed to be used as entrypoint therefore the shebang is
        unnecessary. It also doesn't need execute bits.
        
        Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
        
      - python: always use python3 in the shebang of programs using setools
        
        setools 4.2.0 dropped support for Python 2. On systems where
        /usr/bin/python is Python 2, several tools are now broken because of
        this. Update the shebang of these tools to /usr/bin/python3.
        
        For future reference, as semanage/seobject.py, sepolicy and sepolgen
        import setools, every program that uses one of these modules need to be
        run with Python 3. The following programs do not use any of these
        modules so their shebangs have not been modified:
        
            dbus/selinux_server.py
            libsemanage/utils/semanage_migrate_store
            mcstrans/share/util/mlscolor-test
            mcstrans/share/util/mlstrans-test
            sandbox/start
        
        Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
        
      - python/sepolicy: drop python shebang from the module
        
        The files in sepolicy's module directory are not supposed to used as
        executable files. The shebang line is therefore not needed.
        
        Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
        
      - libsemanage: genhomedircon - improve handling large groups
        
        getgrnam_r() uses a preallocated buffer to store a structure containing
        the broken-out fields of the record in the group database. The size of
        this buffer is usually sysconf(_SC_GETGR_R_SIZE_MAX) == 1024 and it is
        not enough for groups with a large number of users.  In these cases,
        getgrnam_r() returns -1 and sets errno to ERANGE and the caller can
        retry with a larger buffer.
        
        Fixes:
        $ semanage login -a -s user_u -r s0-s0:c1.c2 '%largegroup'
        libsemanage.semanage_direct_commit: semanage_genhomedircon returned error code -1. (Numerical result out of range).
        OSError: Numerical result out of range
        
        Signed-off-by: Petr Lautrbach <plautrba@redhat.com>