Update git submodules
* Update platform/external/selinux from branch 'master'
  to b744f16fd2626c87778927566297be51e6a3b329
  - Merge remote-tracking branch 'aosp/upstream-master' into mymerge
    
    Followed the following steps:
      # In repo client
      cd external/selinux
      repo sync .
      repo start mymerge .
      git merge aosp/upstream-master --no-ff # resolve any conflicts
      repo upload .
    
    Test: android compiles and boots and no observed problems.
    Change-Id: Ibdc3617c75af6ba0d93756cec1ad5ae229e3d5e2
    
  - libselinux: selinux_restorecon: fix printf format string specifier for uint64_t
    
    fc_count is defined as uint64_t, which needs to be printed with PRIu64
    (it is "llu" on x86 and "lu" on x86-64). Otherwise, building with
    'CC="gcc -m32"' fails with:
    
        selinux_restorecon.c: In function ‘restorecon_sb’:
        selinux_restorecon.c:633:26: error: format ‘%lu’ expects argument of
        type ‘long unsigned int’, but argument 3 has type ‘uint64_t’ {aka
        ‘long long unsigned int’} [-Werror=format=]
             fprintf(stdout, "\r%luk", fc_count / STAR_COUNT);
                                ~~^
                                %llu
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - python: replace aliases with corresponding type names
    
    Aliases are not used in the selinux database. When user enters a type
    alias as a parameter it should be converted to the corresponding type
    in order to be processed correctly further in the userspace logic.
    
    Fixes e.g.:
    
    \#sepolicy transition -s phpfpm_t
    /* where phpfpm_t is a type alias of httpd_t */
    
    Traceback (most recent call last):
      File "/usr/bin/sepolicy", line 691, in <module>
        args.func(args)
      File "/usr/bin/sepolicy", line 458, in transition
        mytrans = setrans(args.source, args.target)
      File "/usr/lib/python3.6/site-packages/sepolicy/transition.py", line 48, in __init__
        self._process(self.source)
      File "/usr/lib/python3.6/site-packages/sepolicy/transition.py", line 54, in _process
        trans = _get_trans(source)
      File "/usr/lib/python3.6/site-packages/sepolicy/transition.py", line 36, in _get_trans
        src_list = [src] + list(filter(lambda x: x['name'] == src, sepolicy.get_all_types_info()))[0]['attributes']
    IndexError: list index out of range
    
  - libsepol: mark permissive types when loading a binary policy
    
    Nicolas Iooss reports:
    When using checkpolicy to read a binary policy, permissive types are not
    written in the output file. In order to reproduce this issue, a test
    policy can be written from minimal.cil with the following commands:
    
        $ cd secilc/test/
        $ cp minimum.cil my_policy.cil
        $ echo '(typepermissive TYPE)' >> my_policy.cil
        $ secilc my_policy.cil
        $ checkpolicy -bC -o /dev/stdout policy.31
    
        # There is no "(typepermissive TYPE)" in checkpolicy output.
    
    This is because TYPE_FLAGS_PERMISSIVE is added to typdatum->flags only
    when loading a module, which uses the permissive flag in the type
    properties. A kernel policy defines permissive types in a dedicated
    bitmap, which gets loaded as p->permissive_map before the types are
    loaded.
    
    The solution is to use the permissive_map bitmap instead of relying on
    the flags field of the struct type_datum when writing out CIL or
    policy.conf policy from a binary.
    
    Reported-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    Signed-off-by: James Carter <jwcart2@tycho.nsa.gov>
    

* Update platform/superproject from branch 'master'
  to 4e004f80736e4308e1f88b06b289c692ef75b1fe
  - Update git submodules
    
    * Update external/selinux from branch 'master'
      to b744f16fd2626c87778927566297be51e6a3b329
      - Merge remote-tracking branch 'aosp/upstream-master' into mymerge
        
        Followed the following steps:
          # In repo client
          cd external/selinux
          repo sync .
          repo start mymerge .
          git merge aosp/upstream-master --no-ff # resolve any conflicts
          repo upload .
        
        Test: android compiles and boots and no observed problems.
        Change-Id: Ibdc3617c75af6ba0d93756cec1ad5ae229e3d5e2
        
      - libselinux: selinux_restorecon: fix printf format string specifier for uint64_t
        
        fc_count is defined as uint64_t, which needs to be printed with PRIu64
        (it is "llu" on x86 and "lu" on x86-64). Otherwise, building with
        'CC="gcc -m32"' fails with:
        
            selinux_restorecon.c: In function ‘restorecon_sb’:
            selinux_restorecon.c:633:26: error: format ‘%lu’ expects argument of
            type ‘long unsigned int’, but argument 3 has type ‘uint64_t’ {aka
            ‘long long unsigned int’} [-Werror=format=]
                 fprintf(stdout, "\r%luk", fc_count / STAR_COUNT);
                                    ~~^
                                    %llu
        
        Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
        
      - python: replace aliases with corresponding type names
        
        Aliases are not used in the selinux database. When user enters a type
        alias as a parameter it should be converted to the corresponding type
        in order to be processed correctly further in the userspace logic.
        
        Fixes e.g.:
        
        \#sepolicy transition -s phpfpm_t
        /* where phpfpm_t is a type alias of httpd_t */
        
        Traceback (most recent call last):
          File "/usr/bin/sepolicy", line 691, in <module>
            args.func(args)
          File "/usr/bin/sepolicy", line 458, in transition
            mytrans = setrans(args.source, args.target)
          File "/usr/lib/python3.6/site-packages/sepolicy/transition.py", line 48, in __init__
            self._process(self.source)
          File "/usr/lib/python3.6/site-packages/sepolicy/transition.py", line 54, in _process
            trans = _get_trans(source)
          File "/usr/lib/python3.6/site-packages/sepolicy/transition.py", line 36, in _get_trans
            src_list = [src] + list(filter(lambda x: x['name'] == src, sepolicy.get_all_types_info()))[0]['attributes']
        IndexError: list index out of range
        
      - libsepol: mark permissive types when loading a binary policy
        
        Nicolas Iooss reports:
        When using checkpolicy to read a binary policy, permissive types are not
        written in the output file. In order to reproduce this issue, a test
        policy can be written from minimal.cil with the following commands:
        
            $ cd secilc/test/
            $ cp minimum.cil my_policy.cil
            $ echo '(typepermissive TYPE)' >> my_policy.cil
            $ secilc my_policy.cil
            $ checkpolicy -bC -o /dev/stdout policy.31
        
            # There is no "(typepermissive TYPE)" in checkpolicy output.
        
        This is because TYPE_FLAGS_PERMISSIVE is added to typdatum->flags only
        when loading a module, which uses the permissive flag in the type
        properties. A kernel policy defines permissive types in a dedicated
        bitmap, which gets loaded as p->permissive_map before the types are
        loaded.
        
        The solution is to use the permissive_map bitmap instead of relying on
        the flags field of the struct type_datum when writing out CIL or
        policy.conf policy from a binary.
        
        Reported-by: Nicolas Iooss <nicolas.iooss@m4x.org>
        Signed-off-by: James Carter <jwcart2@tycho.nsa.gov>