Update git submodules
* Update platform/packages/apps/Nfc from branch 'master'
  to fe4149b340b24298ee3be87f8ac141f4ff3f193c
  - Merge "Replace .equals(null) with == null"
  - Replace .equals(null) with == null
    
    .equals(null) always returns false or throws
    a NullPointerException.
    
    Bug: 190944875
    Test: Presubmits
    Change-Id: Id719018fa41a5652bc6b3044046b8a37d8c5d8fb
    
  - Merge "Fix Wbitwise-instead-of-logical introduced by clang-r445002"
  - Fix Wbitwise-instead-of-logical introduced by clang-r445002
    
    Bug: http://b/215753485
    
    packages/apps/Nfc/nci/jni/NativeNfcTag.cpp:1466:22: error: use of
    bitwise '|' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
        isFormattable = (NfcTag::getInstance().isMifareUltralight() |
                        ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    packages/apps/Nfc/nci/jni/NativeNfcTag.cpp:1466:22: note: cast one or
    both operands to int to silence this warning
    
    Test: Build with new clang
    Change-Id: Iaafa695751ef8626486836bf5d78899459dd152f