Update git submodules
* Update platform/external/perfetto from branch 'master'
  to 9bd95112525ed931667cee48a7ccdc2e5c06570e
  - Merge "Tracing: add explicit dtor to TracingMuxerFake"
  - Tracing: add explicit dtor to TracingMuxerFake
    
    Some SDK users hit linking errors when building perfetto.cc
    The cause is uknown (esepcially given they were building the
    same perfetto.cc in 3 targets with the same compiler and only
    one failed).
    
    The linking error was:
    'perfetto::internal::TracingMuxerFake::~TracingMuxerFake()'
    buck-out/gen/arvr/third-party/perfetto/perfetto_sdk#android-arm64,static/libperfetto_sdk.a(out.o):perfetto.cc:vtable for perfetto::internal::TracingMuxerFake: error: undefined reference to 'perfetto::internal::TracingMuxerFake::~TracingMuxerFake()'
    clang++: error: linker command failed with exit code 1 (use -v to see invocation)
    
    Change-Id: I20d3889470777edc18c0871271b735a522e3708b
    Bug: discord chat of 2021-07-20