Update git submodules
* Update platform/cts from branch 'master'
  to 3e04f0899cb39d981ea6b3ce5778f5f12216053b
  - Merge "Merge "Fix com.google.android.gts.devicepolicy.DeviceOwnerTest#testDevicePolicyManager failure on automotive devices." into android12L-tests-dev am: dd1e71d232"
  - Merge "Fix com.google.android.gts.devicepolicy.DeviceOwnerTest#testDevicePolicyManager failure on automotive devices." into android12L-tests-dev am: dd1e71d232
    
    Original change: https://android-review.googlesource.com/c/platform/cts/+/2089185
    
    Change-Id: Ifc8c131ac3f44aaa2158f629220af35bab37e4fa
    Signed-off-by: Automerger Merge Worker <android-build-automerger-merge-worker@system.gserviceaccount.com>
    
  - Merge "Fix com.google.android.gts.devicepolicy.DeviceOwnerTest#testDevicePolicyManager failure on automotive devices." into android12L-tests-dev
  - Fix
    com.google.android.gts.devicepolicy.DeviceOwnerTest#testDevicePolicyManager
    failure on automotive devices.
    
    The call to Context.getUser() was throwing a NoSuchMethodError exception because ContextWrapper overrides that method without marking it as @TestApi.
    Changed mUser as String and added try/catch to avoid FATAL error.
    Removed final keyword to avoid compile error.
    
    Bug: 219868141
    Test: atest -b -t com.google.android.gts.devicepolicy.DeviceOwnerTest#testDevicePolicyManager
    Change-Id: I3371649a73bf075c2164aed0d76ec5ffe4014fac