Update git submodules
* Update platform/art from branch 'master'
  to 6d30df970f1ad209a87708fa03e8f746102fa42d
  - Fix bugprone-use-after-move clang-tidy warning
    
    After clang update, clang-tidy bugprone-use-after-move starts to check
    constructor initialization list. It gives below false-positive warning:
    
    art/compiler/utils/riscv64/assembler_riscv64.h:70:48: error: 'src' used
    after it was moved [bugprone-use-after-move,-warnings-as-errors]
    : Label(std::move(src)), prev_branch_id_(src.prev_branch_id_) {}
    ^
    art/compiler/utils/riscv64/assembler_riscv64.h:70:9: note: move occurred here
    : Label(std::move(src)), prev_branch_id_(src.prev_branch_id_) {}
    ^
    
    Bug: 286421006
    Test: build with clang-r498229
    Change-Id: I437e92095b60b3ef4baaabb4aeb667fe4375a471