Update git submodules
* Update platform/superproject from branch 'master'
  to 4aa57d5d0c813067486d9264b6f2f622c1df4a07
  - Update git submodules
    
    * Update system/libhwbinder from branch 'master'
      to 1f2cf04ff1fba707770ac992f6fd57119812c945
      - Add missing noexcept to declaration
        
        system/libhwbinder/vts/performance/PerfTest.cpp:66:7: error: exception specification in declaration does not match previous declaration
        Pipe::Pipe(Pipe&& rval) noexcept {
              ^
        system/libhwbinder/vts/performance/PerfTest.h:37:5: note: previous declaration is here
            Pipe(Pipe&& rval);
            ^
        1 error generated.
        
        Bug: http://b/111067277
        Test: Builds with C++17.
        Change-Id: I6ff366835aa7328462c7f493754b01417109feee
        

* Update platform/system/libhwbinder from branch 'master'
  to 1f2cf04ff1fba707770ac992f6fd57119812c945
  - Add missing noexcept to declaration
    
    system/libhwbinder/vts/performance/PerfTest.cpp:66:7: error: exception specification in declaration does not match previous declaration
    Pipe::Pipe(Pipe&& rval) noexcept {
          ^
    system/libhwbinder/vts/performance/PerfTest.h:37:5: note: previous declaration is here
        Pipe(Pipe&& rval);
        ^
    1 error generated.
    
    Bug: http://b/111067277
    Test: Builds with C++17.
    Change-Id: I6ff366835aa7328462c7f493754b01417109feee