Update git submodules
* Update platform/external/autotest from branch 'master'
  to 981e16cfa1e5557e22a74529d65d33fbc2549b5f
  - [autotest] network_WiFi_ChannelScanDwellTime: correct list checks
    am: 2c06c1e0c2
    
    Change-Id: I5c3fb85c19be181eb7bb61be6bcede8abe17ce5a
    
  - [autotest] network_WiFi_ChannelScanDwellTime: correct list checks
    
    CL:1097984 incorrectly refactored our list-collation logic. Today, it's
    not possible to hit the 'Failed to find any BSS' code, since the only
    TimeoutError is when _bss_list is None (which is different than []).
    
    Instead, we get this, when the empty list makes its way into logic that
    didn't expect it:
    
      File "/usr/local/autotest/server/site_tests/network_WiFi_ChannelScanDwellTime/network_WiFi_ChannelScanDwellTime.py", line 82, in _get_dwell_time
        index_diff = ssid_index[-1] - ssid_index[0]
    IndexError: list index out of range
    
    I picked a semi-related BUG=, because we're not seeing that symptom any
    more, and are instead seeing this Error. We still should probably figure
    out why we fail the test.
    
    BUG=chromium:628784
    TEST=network_WiFi_ChannelScanDwellTime
    
    Change-Id: Ie458ffb609ebdf8940ec793f782befd293d2c4a2
    Signed-off-by: Brian Norris <briannorris@chromium.org>
    Reviewed-on: https://chromium-review.googlesource.com/1357253
    Commit-Ready: Kirtika Ruchandani <kirtika@chromium.org>
    Reviewed-by: Alex Khouderchah <akhouderchah@chromium.org>
    

* Update platform/superproject from branch 'master'
  to cb00ad1c125247b45172965f5d66ac768940d890
  - Update git submodules
    
    * Update external/autotest from branch 'master'
      to 981e16cfa1e5557e22a74529d65d33fbc2549b5f
      - [autotest] network_WiFi_ChannelScanDwellTime: correct list checks
        am: 2c06c1e0c2
        
        Change-Id: I5c3fb85c19be181eb7bb61be6bcede8abe17ce5a
        
      - [autotest] network_WiFi_ChannelScanDwellTime: correct list checks
        
        CL:1097984 incorrectly refactored our list-collation logic. Today, it's
        not possible to hit the 'Failed to find any BSS' code, since the only
        TimeoutError is when _bss_list is None (which is different than []).
        
        Instead, we get this, when the empty list makes its way into logic that
        didn't expect it:
        
          File "/usr/local/autotest/server/site_tests/network_WiFi_ChannelScanDwellTime/network_WiFi_ChannelScanDwellTime.py", line 82, in _get_dwell_time
            index_diff = ssid_index[-1] - ssid_index[0]
        IndexError: list index out of range
        
        I picked a semi-related BUG=, because we're not seeing that symptom any
        more, and are instead seeing this Error. We still should probably figure
        out why we fail the test.
        
        BUG=chromium:628784
        TEST=network_WiFi_ChannelScanDwellTime
        
        Change-Id: Ie458ffb609ebdf8940ec793f782befd293d2c4a2
        Signed-off-by: Brian Norris <briannorris@chromium.org>
        Reviewed-on: https://chromium-review.googlesource.com/1357253
        Commit-Ready: Kirtika Ruchandani <kirtika@chromium.org>
        Reviewed-by: Alex Khouderchah <akhouderchah@chromium.org>