Update git submodules
* Update platform/art from branch 'master'
  to e58624f221b967553d7b71f14d8677ceaa000553
  - Various renames following the name change from "Runtime APEX" to "ART APEX".
    
    In particular ANDROID_RUNTIME_ROOT is now ANDROID_ART_ROOT.
    
    Test: Build & boot
    Test: art/tools/run-gtests.sh in chroot
    Test: art/test/testrunner/testrunner.py --target --64 in chroot
    Test: art/tools/run-libcore-tests.sh --mode=device --variant=X64 in chroot
    Test: art/tools/run-jdwp-tests.sh --mode=device --variant=X64 in chroot
    Test: m test-art-host-gtest
    Test: art/test/testrunner/testrunner.py --host --64
    Test: art/tools/run-jdwp-tests.sh --mode=host
    Bug: 135753770
    Change-Id: Ia74da964e54cf396d66e9e12ea56da4e9483662a
    

* Update platform/external/vogar from branch 'master'
  to e29e8a57f3e0bb2f7cc2f194606ca205f9d8a6cb
  - Rename ANDROID_RUNTIME_ROOT to ANDROID_ART_ROOT following APEX module name change.
    
    Test: Build & boot
    Test: art/tools/run-libcore-tests.sh --mode=device --variant=X64 in ART chroot test environment
    Test: art/tools/run-libcore-tests.sh --mode=host
      (fails on org.apache.harmony.tests.java.lang.MathTest#test_cbrt_D, but seems unrelated:
      junit.framework.AssertionFailedError: expected:<3.0> but was:<3.0000000000000004>)
    Bug: 135753770
    Change-Id: Icfd23c0dc0a3d868dc519d8c28c9413ce37cfdb0
    
  - Update path to the new ART APEX.
    am: 469ea8377b
    
    Change-Id: I38175385ec7b420c541e3c665dae66f0d4d91528
    
  - Fix vogar-tests
    am: cd0af4ae56
    
    Change-Id: I0b37c367119faa758c6815db3f09a73fe77b80d7
    
  - Add core-icu4j into the list of boot jars
    am: bd5378ace7
    
    Change-Id: Ic09352702211f20a98faa4b1852dab6cb66a014b
    
  - Add ANDROID_I18N_ROOT pointing to i18n APEX
    am: 46947f60ea
    
    Change-Id: I3c77c763b6045c0e471000def3e5463ac7c9a665
    
  - Minimal fix for merging jars with dir entries am: b7120f2b23 am: 752450080f
    am: f1f3f02131
    
    Change-Id: Ic9fbe1fed744031b97f6826c2750524c6e787bf6
    
  - Minimal fix for merging jars with dir entries am: b7120f2b23
    am: 752450080f
    
    Change-Id: Ia7d1fdb5766262b53a6d47193d2f73d6d1a7613a
    
  - Re-order boot classpath list to match base_system.mk am: 76c664f0d6 am: 325f18f1f9
    am: c610b8fe45
    
    Change-Id: I48c23081da8ef9a029b0549eb726e276c5d9c9a1
    
  - Re-order boot classpath list to match base_system.mk am: 76c664f0d6
    am: 325f18f1f9
    
    Change-Id: I3265635e09d3ee27a8128abfc743d6def142ac2e
    
  - Add support for the ANDROID_TZDATA_ROOT env var am: 64fb91e721 am: 67b2175a71
    am: a8d76b152f
    
    Change-Id: I1415a98769ca757d0423bdd89166f04e3f18379a
    
  - Add support for the ANDROID_TZDATA_ROOT env var am: 64fb91e721
    am: 67b2175a71
    
    Change-Id: I0c39c44b1200649bd172d558f33e77ad710ce223
    
  - Merge stage-aosp-master into pi-dev-plus-aosp
    am: 507c42a8e9
    
    Change-Id: I80c0891062f2f48aab8dc8d99853d4cd90831c3e
    
  - Merge stage-aosp-master into pi-dev-plus-aosp
    
    Bug: 126125118
    Change-Id: I4235996d8ca8cd160e0314786643fb46eab78260
    
  - Remove reference to framework-oahl-backward-compatibility am: 3cf71c152d am: 60e8e780c6
    am: 9bbb099a7d
    
    Change-Id: Ia4014dfa001aeb7b72d4e0c8f0613189d692db7a
    
  - Remove reference to framework-oahl-backward-compatibility am: 3cf71c152d
    am: 60e8e780c6
    
    Change-Id: If097118dc5d75b8c6719374587b56f649e2bd1d3
    
  - [automerger skipped] Change the impl lib name of java_sdk_library am: a028dd69aa am: 19a74dc032 -s ours
    am: 138ea1133e -s ours
    am skip reason: change_id I60a7890a037968788074ca1c3642d515169cd08a with SHA1 addf228ec0 is in history
    
    Change-Id: I4bbb008143211a759b0be63582886f0e741f7313
    
  - [automerger skipped] Change the impl lib name of java_sdk_library am: a028dd69aa
    am: 19a74dc032 -s ours
    am skip reason: change_id I60a7890a037968788074ca1c3642d515169cd08a with SHA1 addf228ec0 is in history
    
    Change-Id: I590f2920ecf8e275baf3dae6204687b1ff19de31
    
  - [automerger skipped] Change the impl lib name of java_sdk_library
    am: addf228ec0 -s ours
    am skip reason: change_id I60a7890a037968788074ca1c3642d515169cd08a with SHA1 ec65c980a1 is in history
    
    Change-Id: I1100b7e48504f528975219c13940628cfb97d868
    
  - Merge "Change the impl lib name of java_sdk_library"
  - Change the impl lib name of java_sdk_library
    
    The impl lib name of java_sdk_library is changed to {module_name}.jar
    instead of {module_name}.impl.jar
    
    Bug: 110404779
    Test: m -j
    Change-Id: I60a7890a037968788074ca1c3642d515169cd08a
    Merged-In: I60a7890a037968788074ca1c3642d515169cd08a
    (cherry picked from commit ec65c980a13b3e6eb0bd78662f330c1de9988420)
    
  - Revert "Track addition of core-simple" am: 7057548c48 am: 11cab6c843
    am: d824c6568f
    
    Change-Id: I766089f3b932138c48e22bea3e170071a95b9cbf
    
  - Change the impl lib name of java_sdk_library
    
    The impl lib name of java_sdk_library is changed to {module_name}.jar
    instead of {module_name}.impl.jar
    
    Bug: 110404779
    Test: m -j
    Change-Id: I60a7890a037968788074ca1c3642d515169cd08a
    
  - Fix --variant and add --mode device_testdex am: 6555c78bfb am: 69c1f8861f
    am: 8e90a0f2c2
    
    Change-Id: I5c21a62f0fcd3f69f9845546063aec103673f065
    
  - Fix --mode app_process am: 7b5603bef0 am: 31a5c8db98
    am: 404ab07ad5
    
    Change-Id: I56b5001fdaf4e0af529881d8821c2f0036e6d720
    
  - Add apache-xml for all modes for consistency am: 0352fed514 am: f6929094a9
    am: af7e7c945c
    
    Change-Id: Ife294b331196d97f8781c8b3f75655c4d4fca56f
    
  - Remove use of -testdex jars am: df56643f3b am: 076c092efd
    am: cd2c9f20d3
    
    Change-Id: I44f5fa7dd9c167b78cab8bbeca920daa441d53ac
    
  - Revert "Pass -Xbootclasspath to device tests." am: 58af7f508e am: a5c18cf7e2
    am: 7b216759dc
    
    Change-Id: Ife120b5f02bf2f503c184e211446391d30c13b70
    
  - Pass -Xbootclasspath to device tests. am: 69f7f13374 am: 92d85c8bbd
    am: 9dbe0f37e5
    
    Change-Id: I8e3c2601871310d59289a8915264f7c00e75e73b
    
  - Reduce core image to 6 jars. am: 6c94aec7d4 am: 712d07f919
    am: c3dbc376d1
    
    Change-Id: I1dada7e45f2dec4183d0c148f1b3b5460d93331f
    
  - Add support for ANDROID_RUNTIME_ROOT variable am: ba2701d1b3 am: a280d52417
    am: bfa5e7cb40
    
    Change-Id: I94c8b8a2244addd6cb7520a3560d5a14c245ecee
    
  - [automerger skipped] Merge pie-platform-release to aosp-master - DO NOT MERGE am: d38213eae5  -s ours am: 0a7c297539  -s ours
    am: 992f113cab  -s ours
    
    Change-Id: Iab9daadecfe8818d8b08954c9cb35101595d9d10
    
  - [automerger skipped] Merge pi-platform-release to stage-aosp-master - DO NOT MERGE am: 7f736a1401  -s ours
    am: d4668c45c9  -s ours
    
    Change-Id: I484c60320e6dbce0afcca8f0acda668725107665
    
  - Follow renames of host libraries am: e628c32aaf am: 731ecebfe5
    am: 71bd5bcad0
    
    Change-Id: I3570812c50d466a6f0903e3006419642b95efe56
    
  - Don't add an artifical adb dependency on vogar. am: da5121d6f5 am: 6863f78099
    am: 7f6f73fad8
    
    Change-Id: I9477e29a8e91410c00bcc8b0645577bdcd978c27
    
  - Track addition of core-simple am: d5d5894f91 am: 3782cc43d7
    am: c333e0e647
    
    Change-Id: I154a7e9076d0fb84a1abc97f2a1dc97f4fb9fe4c
    
  - Merge "Replace non-existing http legacy in vogar" am: 50283fa3a0 am: 49f5d51454
    am: bc0f578fed
    
    Change-Id: I364f8a2edfd85ea6cf51d4d142a50ca11b9ac3fd
    
  - Add an ADB-with-chroot device target to Vogar. am: 1409075203 am: 9538f84ee2
    am: 2a875cf229
    
    Change-Id: I26b7584b9f28ef3d189319562160424710b62623
    
  - Merge "Have vogar.android.DeviceFilesystem.ls handle more "file not found" cases." am: fcaae69a94 am: 459e34a869
    am: fde0711b8e
    
    Change-Id: I09582a8d6246881427635f4abf4781d76ef72e40
    
  - Merge "Materialize the action of running Vogar tests as a Makefile rule." am: 13df05216e am: bc64c71fe7
    am: f278ad987f
    
    Change-Id: I87d83e034300905c3cbbcee3a18eb0c92794fe53
    
  - Fix vogar.tasks.RetrieveFilesTask.retrieveFiles' Javadoc comment. am: 194385a285 am: f464039ed2
    am: 1377334122
    
    Change-Id: I1ffa6cfc1be419ed5a1ea5be33bfbe68ada8ebcc
    
  - vogar: Update android.jar paths. am: c551402524 am: 0f6a209e68
    am: c29107baad
    
    Change-Id: Icd80e8f647a49bc90d5b24e29dc2bc1cd792fe56
    
  - Move vogar to "current" prebuilt. am: 8833c43ac9 am: fce190359f
    am: 9c4d97a919
    
    Change-Id: I51272a69d1cffc0ee4e959c2d7e2b64760faacf6
    
  - Some aesthetic changes in Vogar. am: aa4decc90c am: 54227e43f5
    am: bcc206990b
    
    Change-Id: Ic1311f24f8cfe1a83dbdf8699e8035acd9bbac59
    

* Update platform/frameworks/base from branch 'master'
  to 80fd44500cb4c72b504512b45cac8742ccff7db5
  - Merge "Rename ANDROID_RUNTIME_ROOT to ANDROID_ART_ROOT following APEX module name change."
  - Rename ANDROID_RUNTIME_ROOT to ANDROID_ART_ROOT following APEX module name change.
    
    Test: Boot
    Bug: 135753770
    Change-Id: I930027fb0ad18d9d06165bbfbfe54d88bc28530d
    

* Update platform/superproject from branch 'master'
  to b4493b42aa26d80f045045c765473336eeb19ca0
  - Update git submodules
    
    * Update art from branch 'master'
      to e58624f221b967553d7b71f14d8677ceaa000553
      - Various renames following the name change from "Runtime APEX" to "ART APEX".
        
        In particular ANDROID_RUNTIME_ROOT is now ANDROID_ART_ROOT.
        
        Test: Build & boot
        Test: art/tools/run-gtests.sh in chroot
        Test: art/test/testrunner/testrunner.py --target --64 in chroot
        Test: art/tools/run-libcore-tests.sh --mode=device --variant=X64 in chroot
        Test: art/tools/run-jdwp-tests.sh --mode=device --variant=X64 in chroot
        Test: m test-art-host-gtest
        Test: art/test/testrunner/testrunner.py --host --64
        Test: art/tools/run-jdwp-tests.sh --mode=host
        Bug: 135753770
        Change-Id: Ia74da964e54cf396d66e9e12ea56da4e9483662a
        
    
    * Update external/vogar from branch 'master'
      to e29e8a57f3e0bb2f7cc2f194606ca205f9d8a6cb
      - Rename ANDROID_RUNTIME_ROOT to ANDROID_ART_ROOT following APEX module name change.
        
        Test: Build & boot
        Test: art/tools/run-libcore-tests.sh --mode=device --variant=X64 in ART chroot test environment
        Test: art/tools/run-libcore-tests.sh --mode=host
          (fails on org.apache.harmony.tests.java.lang.MathTest#test_cbrt_D, but seems unrelated:
          junit.framework.AssertionFailedError: expected:<3.0> but was:<3.0000000000000004>)
        Bug: 135753770
        Change-Id: Icfd23c0dc0a3d868dc519d8c28c9413ce37cfdb0
        
    
    * Update frameworks/base from branch 'master'
      to 80fd44500cb4c72b504512b45cac8742ccff7db5
      - Merge "Rename ANDROID_RUNTIME_ROOT to ANDROID_ART_ROOT following APEX module name change."
      - Rename ANDROID_RUNTIME_ROOT to ANDROID_ART_ROOT following APEX module name change.
        
        Test: Boot
        Bug: 135753770
        Change-Id: I930027fb0ad18d9d06165bbfbfe54d88bc28530d
        
    
    * Update system/core from branch 'master'
      to 0560d0ef6f80da76298057b6cf06d1766a1266e9
      - Merge "Rename ANDROID_RUNTIME_ROOT to ANDROID_ART_ROOT following APEX module name change."
      - Rename ANDROID_RUNTIME_ROOT to ANDROID_ART_ROOT following APEX module name change.
        
        Test: Boot
        Bug: 135753770
        Change-Id: Ie9a8043ee350164c01a66f1a7ab1b3205076a5c4
        

* Update platform/system/core from branch 'master'
  to 0560d0ef6f80da76298057b6cf06d1766a1266e9
  - Merge "Rename ANDROID_RUNTIME_ROOT to ANDROID_ART_ROOT following APEX module name change."
  - Rename ANDROID_RUNTIME_ROOT to ANDROID_ART_ROOT following APEX module name change.
    
    Test: Boot
    Bug: 135753770
    Change-Id: Ie9a8043ee350164c01a66f1a7ab1b3205076a5c4