Update git submodules
* Update platform/system/apex from branch 'master'
  to eda1433721011ea6f0c8587f0f98756cdd2b5bdc
  - Fix string-compare warning
    
    system/apex/tools/host_apex_verifier.cc:217:45: error: result of comparison against a string literal is unspecified (use an explicit string comparison function instead) [-Werror,-Wstring-compare]
            if (long_options[option_index].name == "deapexer") {
                                                ^  ~~~~~~~~~~
    system/apex/tools/host_apex_verifier.cc:220:45: error: result of comparison against a string literal is unspecified (use an explicit string comparison function instead) [-Werror,-Wstring-compare]
            if (long_options[option_index].name == "debugfs") {
                                                ^  ~~~~~~~~~
    system/apex/tools/host_apex_verifier.cc:223:45: error: result of comparison against a string literal is unspecified (use an explicit string comparison function instead) [-Werror,-Wstring-compare]
            if (long_options[option_index].name == "sdk_version") {
                                                ^  ~~~~~~~~~~~~~
    
    Test: presubmit
    Bug: 153764102
    Change-Id: Ic9f583e91f7b8c3af71aa16371ba2b979344e526
    
  - Merge "Update the allow list inside apex_shim.cpp"
  - Update the allow list inside apex_shim.cpp
    
    Build system for APEXes recently changed and now it appends the version
    of the APEX to the apk paths. This chang updates the corresponding allow
    list of entries that can be present in the shim APEXes, so that we can
    drop the new shim prebuilts for T.
    
    Test: presubmit
    Bug: 230724040
    Change-Id: I67ef3c6d2d10dd03eb24fddc87bd544fa0fb7e19
    Merged-In: I67ef3c6d2d10dd03eb24fddc87bd544fa0fb7e19
    (cherry picked from commit 5f90e159eb510e837074644857cfdeb52f6dba3f)