Update git submodules
* Update platform/external/libepoxy from branch 'master'
  to a01a87cee932840ac49e585937e588a3d6422f52
  - Upgrade libepoxy to 1.5.10
    
    This project was upgraded with external_updater.
    Usage: tools/external_updater/updater.sh update libepoxy
    For more info, check https://cs.android.com/android/platform/superproject/+/master:tools/external_updater/README.md
    
    Test: TreeHugger
    Change-Id: I5e4444163a45546704f817a6ee8a43ecdc4a6917
    
  - Merge pull request #262 from seungha-yang/win-non-eng-locale
    
    meson: Fix for building on non-English locale
  - Merge pull request #261 from arichardson/custom-prefix-build-fix
    
    Fix build if EGL/X11 headers are in a custom prefix
  - Add the right include paths for EGL and X11 headers
    
    Libepoxy currently depends on all headers living under the same prefix.
    This is not necessarily true: X11 headers can live in a separate prefix,
    for instance under /opt/X11. This is also the case when cross-compiling to
    a platform that sets up the build environment in non-standard ways.
    
    We could add `x11_dep` and `egl_dep` to the libepoxy target dependencies,
    but that could potentially add spurious linker flags and cause libepoxy to
    depend on libraries it will dlopen() during normal operations.
    
    To avoid that case, we use a partial_dep() object from Meson, and we limit
    the dependency to compiler flags and inclusion paths.
    
  - Merge pull request #263 from caolanm/fix_libreoffice_android_build
    
    fix error: use of undeclared identifier 'OPENGL_LIB'
  - fix error: use of undeclared identifier 'OPENGL_LIB'
    
    at epoxy/src/dispatch_common.c:690 in LibreOffice android build with
    libepoxy-1.5.9
    
  - meson: Fix for building on non-English locale
    
    Specify utf-8 encoding to fix building on non-English locale
    
  - Post-release version bump to 1.5.10
    
  - Merge pull request #257 from batesj/allow_libopengl
    
    Allow libopengl.so to be used when GLX_LIB is missing
  - Allow libopengl.so to be used when GLX_LIB is missing
    
    This maintains compatibility with previous behavior of
    always using GLX_LIB if it is found. The only change is
    when there is no GLX_LIB.
    
    Previous behavior when no GLX_LIB:
    - abort.
    
    New behavior when no GLX_LIB:
    - Try to load libOpenGL.so as gl_handle (glx_handle remains NULL).
    - Else, abort.
    
    Reviewed-by: Emil Velikov <emil.velikov@collabora.com>
    
  - Merge sc-mainline-prod
    
    Bug: 189946434
    Change-Id: Id18e08ce60fc70b8c02b2ea5277a88cbf9f7bf1c
    
  - Post-release version bump to 1.5.9
    
  - Merge pull request #254 from anholt/issue-252
    
    Revert OpenGL/GLX loading changes
  - Revert "If glvnd library found, do not use libGL.so in epoxy_load_gl"
    
    Commit dbfa4b20 has introduced a string of regressions in the X server
    and KWin.
    
    This reverts commit dbfa4b209c0712b67dfeb8366c2ebe8503063b52.
    
    See: #252
    
  - Revert "Do not overwrite glx_handle in epoxy_load_gl if GLX library is loaded already"
    
    This reverts commit 4994c48172e94ca81c000597e0abc0ea0e682b3c.
    
  - Post-release version bump to 1.5.8
    
  - Merge pull request #250 from anholt/ebassi/issues-249
    
    Remove redeclaration of khronos_uintptr_t
  - Remove redeclaration of khronos_uintptr_t
    
    The type is being redeclared because I didn't see the original
    declaration when I wrote 144cbc9325250081f2eb584ca5deb13aaf1c2433.
    
    Fixes: #249
    
  - Post-release version bump to 1.5.7
    
  - Merge pull request #247 from anholt/win64-khr-types
    
    Support Win64 pointer-sized types
  - Merge pull request #243 from amezin/master
    
    gen_dispatch.py: close output files
  - Support Win64 pointer-sized types
    
    Since we're generating stub types from khrplatform.h because we can't
    include it reliably, we'll have to deal with some of the fallout of the
    Win64 types.
    
    Fixes: #246
    
  - gen_dispatch.py: close output files
    
    Fixes https://github.com/anholt/libepoxy/issues/242
    
  - [automerger skipped] Mark ab/7061308 as merged in stage. am: 93c71b4f52 -s ours am: f982739ffc -s ours am: f377eeac6e -s ours
    
    am skip reason: Change-Id I574a9b5a6e2aec6a2c6314eb22d3d395246e4f51 with SHA-1 1c4e8768d1 is in history
    
    Original change: undetermined
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I4ba50cd6cbcbc60518935bca07f3e5a256117cb3
    
  - [automerger skipped] Mark ab/7061308 as merged in stage. am: 93c71b4f52 -s ours am: f982739ffc -s ours am: f377eeac6e -s ours
    
    am skip reason: Change-Id I574a9b5a6e2aec6a2c6314eb22d3d395246e4f51 with SHA-1 1c4e8768d1 is in history
    
    Original change: undetermined
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I3132783e4edd5b265d23b27d43470d6e47e135c3
    
  - [automerger skipped] Mark ab/7061308 as merged in stage. am: 93c71b4f52 -s ours am: f982739ffc -s ours
    
    am skip reason: Change-Id I574a9b5a6e2aec6a2c6314eb22d3d395246e4f51 with SHA-1 1c4e8768d1 is in history
    
    Original change: undetermined
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I0449500e54fc65974cb46b77656562ea45597b95
    
  - [automerger skipped] Mark ab/7061308 as merged in stage. am: 93c71b4f52 -s ours
    
    am skip reason: Change-Id I574a9b5a6e2aec6a2c6314eb22d3d395246e4f51 with SHA-1 1c4e8768d1 is in history
    
    Original change: undetermined
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I4105983678f21f26cc108e5d4f9e006b4e98c40d
    
  - Mark ab/7061308 as merged in stage.
    
    Bug: 180401296
    Merged-In: I574a9b5a6e2aec6a2c6314eb22d3d395246e4f51
    Change-Id: I76733a21c3bb44167641f80ad5b0bba5aeb85b5b
    
  - [LSC] Add LOCAL_LICENSE_KINDS to external/libepoxy am: f777564138 am: ab4fab6d9f am: a3222c0eb2 am: cf4126ebe8
    
    Original change: https://android-review.googlesource.com/c/platform/external/libepoxy/+/1588917
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Ic482122a0826bda27f9e43c1e930c9ff9d0a02e8
    
  - [LSC] Add LOCAL_LICENSE_KINDS to external/libepoxy am: f777564138 am: ab4fab6d9f am: a3222c0eb2 am: cf4126ebe8
    
    Original change: https://android-review.googlesource.com/c/platform/external/libepoxy/+/1588917
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: If91ac9d5633912f9e69b419b8393bc5db0d56f38
    
  - [LSC] Add LOCAL_LICENSE_KINDS to external/libepoxy am: f777564138 am: ab4fab6d9f am: a3222c0eb2
    
    Original change: https://android-review.googlesource.com/c/platform/external/libepoxy/+/1588917
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Iae3173e9875fb2e7852c6fb8bf53042b852c885e
    
  - [LSC] Add LOCAL_LICENSE_KINDS to external/libepoxy am: f777564138 am: ab4fab6d9f
    
    Original change: https://android-review.googlesource.com/c/platform/external/libepoxy/+/1588917
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I3a04fc879b801ed0933e165a5391df1d595b52fe
    
  - [LSC] Add LOCAL_LICENSE_KINDS to external/libepoxy am: f777564138
    
    Original change: https://android-review.googlesource.com/c/platform/external/libepoxy/+/1588917
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I36a55d247705eeca4a3efe40735885102fe00d0e
    
  - Merge pull request #238 from anholt/pull-229-alt
    
    Fix some bugs in loading OpenGL/GLX/EGL libraries
  - Merge pull request #231 from xclaesse/meson-vars
    
    meson: Set same variables in declare_dependency() as in pkgconfig
  - meson: Set same variables in declare_dependency() as in pkgconfig
    
    GTK currently fails to detect if epoxy has been built with EGL on
    Windows when epoxy is a subproject. To fix that it needs to get that
    information from the dependency variables.
    
    This requires Meson >=0.54.0 for setting variables in
    declare_dependency().
    
  - Do not overwrite glx_handle in epoxy_load_gl if GLX library is loaded already
    
    Reviewed-by: Adam Jackson <ajax@redhat.com>
    
    Signed-off-by: Emmanuele Bassi <ebassi@gnome.org>
    
  - If glvnd library found, do not use libGL.so in epoxy_load_gl
    
    Without additional check, even if libOpenGL was loaded, libGL.so will
    be loaded as well, and used both in gl_handle and glx_handle, so
    libglvnd libraries will not be used.
    
    Reviewed-by: Adam Jackson <ajax@redhat.com>
    
    Signed-off-by: Emmanuele Bassi <ebassi@gnome.org>
    
  - Merge pull request #236 from anholt/ebassi/ci-split
    
    ci: Split Linux and macOS pipelines
  - Add a badge for the project license
    
  - Update the CI status badges
    
    Use the badges from GitHub Actions.
    
  - ci: Split Linux and macOS pipelines
    
    Don't use a single pipeline for everything.
    
  - Merge pull request #235 from anholt/github-ci
    
    Move CI to GitHub
  - ci: Drop tests from MSYS2 pipeline
    
    The WGL tests are failing, likely because of some set up issue; for the
    time being, we care more about building Epoxy, rather than testing it.
    
  - ci: Remove AppVeyor pipeline
    
    We have MSYS2 and MSVC pipelines on GitHub Actions.
    
  - ci: Remove Travis
    
    The GitHub Actions pipeline replaces Travis in any way it matters.
    
  - ci: Use scripts for GitHub Actions
    
    Do not share them with the Travis pipelines.
    
  - ci: Add MSVC workflow on GitHub Actions
    
  - ci: Add MSYS2 workflow on GitHub Actions
    
  - Post-release version bump to 1.5.6
    
  - add crosvm to com.android.virt am: 891be28da6 am: 006e3bcf38 am: 1c4e8768d1
    
    Original change: https://android-review.googlesource.com/c/platform/external/libepoxy/+/1527780
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I951996d6526b3d76d14c5b359367a909edd937ae
    
  - add crosvm to com.android.virt am: 891be28da6 am: 006e3bcf38
    
    Original change: https://android-review.googlesource.com/c/platform/external/libepoxy/+/1527780
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I574a9b5a6e2aec6a2c6314eb22d3d395246e4f51
    
  - add crosvm to com.android.virt am: 891be28da6
    
    Original change: https://android-review.googlesource.com/c/platform/external/libepoxy/+/1527780
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Ie83e6e60eb7b5a4d5263bc456898d9f4576110b7
    
  - Mark ab/6881855 as merged am: 1caece3f9f am: 3e9fd8de95
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/external/libepoxy/+/13110947
    
    Change-Id: I0af2bd1a28352220ecab002c0385fa0a62304de2
    
  - Mark ab/6881855 as merged am: 1caece3f9f
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/external/libepoxy/+/13110947
    
    Change-Id: I2211e6f4383efc703ba139b5f1cf1bf118128e9c
    
  - [automerger skipped] Skip ab/6749736 in stage. am: b56c7afa10 -s ours am: 57c502756c -s ours am: 78821f5ce6 -s ours
    
    am skip reason: Change-Id Ie54bb05e9e5513065fe731ffccedb0bbcf602d91 with SHA-1 c48a6e9f8f is in history
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/external/libepoxy/+/12797162
    
    Change-Id: Ibfca1bc148159b56c270c8c6e3765fca99ac2d07
    
  - [automerger skipped] Skip ab/6749736 in stage. am: b56c7afa10 -s ours am: 57c502756c -s ours
    
    am skip reason: Change-Id Ie54bb05e9e5513065fe731ffccedb0bbcf602d91 with SHA-1 c48a6e9f8f is in history
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/external/libepoxy/+/12797162
    
    Change-Id: I742c8e0ee57694432e7512e4bb887e667d2b6905
    
  - [automerger skipped] Skip ab/6749736 in stage. am: b56c7afa10 -s ours
    
    am skip reason: Change-Id Ie54bb05e9e5513065fe731ffccedb0bbcf602d91 with SHA-1 c48a6e9f8f is in history
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/external/libepoxy/+/12797162
    
    Change-Id: I2c61c088482a889791926175c57ce7d479e712ca
    
  - ANDROID: Add target/device support am: 3189a094b2 am: 826b368df6 am: e8248eb7f7 am: f9494e30af am: 4bec3ff108
    
    Original change: https://android-review.googlesource.com/c/platform/external/libepoxy/+/1414889
    
    Change-Id: I657c773cbbc22857e848a34caa7b900c58ba948e
    
  - [automerger skipped] Mark Android R (rvc-dev-plus-aosp-without-vendor@6692709) as merged am: 92d49d13fd -s ours am: ada6547d20 -s ours am: f25de6fb26 -s ours am: 7fd998dbcd -s ours
    
    am skip reason: Change-Id If8f89ebea88d06db85aac49600fdadad6ad1be49 with SHA-1 1c524efcbe is in history
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/external/libepoxy/+/12469351
    
    Change-Id: I7e847a20687f6909c638179d07ee1b9fb1e3d6a0
    
  - Add Android host build for libepoxy am: a428139a81 am: 97d96203c4 am: a5b7500dae am: c48a6e9f8f am: b076aa0321
    
    Original change: https://android-review.googlesource.com/c/platform/external/libepoxy/+/1368776
    
    Change-Id: I13884068a39c81187122b1bfefed0221569056b7
    
  - Merge pull request #228 from eyelash/github-ci
    
    GitHub CI
  - Merge pull request #225 from anholt/darwin_versions
    
    Use the darwin_versions argument
  - GitHub CI
    
  - Use Meson's darwin_versions argument
    
    Instead of tweaking the linker flags ourselves. This allows Meson to do
    the right thing, and pass the arguments only where needed.
    
  - Require Meson >= 0.48
    
  - Merge pull request #223 from anholt/glsles
    
    Fix return value of shading language for GLES2.
  - Fix return value of shading language for GLES2.
    
    Throughout the mesa project we've been using 100 for GLES2's shading
    language.  It was pretty clearly the intent here, but the clever
    inline detection of "am I parsing a GLSL version or a GL version
    string" forgot about GLSL 1.0.x, and thus returned 10.
    
  - Upgrade libepoxy to 1.5.4 am: 4679a806bd am: 4b204d7bfe am: 1c524efcbe am: 3d8ec97cb8 am: b7733bc78d
    
    Change-Id: I79a597b9ffd18a355f1ce07b5aaeb630e631661e
    
  - [automerger skipped] DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp into stag-aosp-master am: f26ced13c0 -s ours am: d6ac20f29f am: f50958452d am: 4b1ab4b475 -s ours
    
    am skip reason: subject contains skip directive
    
    Change-Id: Ic36acba38d876651fada8e8c387af13e7fbce92d
    
  - Remove redundant NOTICE symbolic link. am: 3df6589272 am: 7a890801db am: d7e67e078c am: 9513e8b2ee am: 8910d2a5a9
    
    Change-Id: Idff2b5f178167d2e494cdbb4ea005efd4c3fdc73
    
  - Merge pull request #220 from crziter/master
    
    Add call convention to mock function
  - Add call convention to mock function
  - Merge pull request #215 from anholt/issue-214
    
    Use EGL_NO_X11 to disable X11 headers
  - Use EGL_NO_X11 to disable X11 headers
    
    MESA_EGL_NO_X11_HEADERS has been deprecated, and libglvnd only supports
    EGL_NO_X11.
    
    Fixes: #214
    
  - Merge pull request #216 from anholt/gen-find-program
    
    build: Use find_program()
  - ci: Unlink python2 on macOS
    
    Otherwise installing Python3 will break horribly.
    
  - build: Use find_program()
    
    Do not rely on the shebang line and the executable bit; we should use
    find_program(), instead, which lets Meson run a script in the
    appropriate environment, portably.
    
  - Merge pull request #212 from anholt/no-autotools
    
    Remove the autotools build system.
  - Lower the minimum required version of Meson
    
    Makes it easier to build Epoxy on older operating systems.
    
  - Remove the autotools build system.
    
    Meson has been out for a long time, is faster, and is simpler.
    
  - Merge pull request #213 from anholt/no-python2
    
    Remove Python 2 support
  - Post-release version bump to 1.5.5
    
  - Remove Python 2 support
    
    Python 2 is going to reach EOL in January 2020, and most platforms have
    already moved to Python 3.