Update git submodules
* Update platform/system/tools/aidl from branch 'master'
  to 481f5933b0b075d1cfc9cde2c0dd956256c504ee
  - remove unused Task::UNSPECIFIED
    
    Fixes: 195987773
    Test: aidl_unittests
    Change-Id: I73ad85484efe311904e11b9ede44b03b7a1854fc
    
  - aidl_parser_fuzzer: fuzz everything
    
    Fuzz the CLI - we're not playing games anymore.
    
    Leaving corpus for now, because the contents at least are known to be
    useful to fuzz, even though the fuzzer requires a new format now. We
    could remove them later.
    
    Bug: 195473218
    Test: aidl_parser_fuzzer locally, and it was able to make some progress,
    for instance, I can see we get here, we know we at least shouldn't be
    regressing on coverage.
        ERROR: :1.1-3: 'j' is not a recognized annotation. It must be one
        of: nullable utf8InCpp SensitiveData VintfStability
        UnsupportedAppUsage JavaOnlyStableParcelable Hide Backing
        JavaPassthrough JavaDerive JavaOnlyImmutable FixedSize Descriptor
        RustDerive SuppressWarnings.
    
    Change-Id: I8b72b8b057ce9dceb178e5b9bf8e34e27d48d2b3
    
  - aidl: Options - avoid calling exit(3)
    
    The fuzzer considers this a fatal error.
    
    Bug: 195473218
    Test: aidl_unittests + the following commands:
        # in a directory without a file named
        # 'alskdjflsakdjflkasjdflkajdslfkajsdf', this command fails:
        aidl alskdjflsakdjflkasjdflkajdslfkajsdf
    
        # this command returns a successful result, and nothing else is done
        aidl --help
    
    Change-Id: I9c0509dae8c4516d8ca57b7a203b51acb5848725
    
  - options: avoid OOR when called w/ no args
    
    This would mean essentially a broken environment, but for fuzzer
    coverage handling this case.
    
    Bug: 195473218
    Test: aidl_parser_fuzzer
    Change-Id: If8101d232b614f2df072393be3f4ba1b017af2cf