Update git submodules
* Update platform/external/toybox from branch 'master'
  to a065dbe6c5d6eb6b723cf04c08a7beeccf1026c9
  - Merge remote-tracking branch 'toybox/master' into HEAD
    
    Change-Id: Ib387b8d25ff1d36bff7a017fd59ef47fbc4e1adf
    
  - Fix sigjmp_buf/jmp_buf mismatches.
    
    Broke the bionic build:
    
      external/toybox/toys/net/netcat.c:188:37: error: incompatible pointer types assigning to 'sigjmp_buf *' (aka 'long (*)[33]') from 'jmp_buf *' (aka 'long (*)[32]') [-Werror,-Wincompatible-pointer-types]
              if (toys.optflags&FLAG_L) NOEXIT(child = XVFORK());
                                        ^~~~~~~~~~~~~~~~~~~~~~~~
      external/toybox/lib/lib.h:375:19: note: expanded from macro 'NOEXIT'
      #define NOEXIT(x) WOULD_EXIT(_noexit_res, x)
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
      external/toybox/lib/lib.h:367:16: note: expanded from macro 'WOULD_EXIT'
        toys.rebound = &_noexit; \
                     ^ ~~~~~~~~
      1 error generated.
    
  - Actually calculating/displaying a reasonable time.
    
    Not yet setting, no server/multicast, should validate source address...
    
  - Add more comments to ps.c and replace hardcoded value with a macro.
    
    If table grows >64 entries XX needs to change, but it can't be 128 yet
    because the slot value is a signed char. Currently 59 entries in table...
    
  - Have test.sh use portability.sh too.
    
  - Factor out scripts/portability.sh and have genconfig.sh use it to find sed/gsed.
    
  - Fix various warnings building on FreeBSD.
    
  - hostname: fix behavior when in jail.
    
    Only -d and -f should cause a DNS lookup. The rest should just act
    directly on the result of gethostname(3). Encountered with the AOSP
    buildbots' use of nsjail, but tested with both the Debian hostname and
    toybox hostname thus:
    
    ```
    unshare -Uunr sh
    hostname android-build
    hostname
    hostname -s
    hostname -d
    hostname -f
    ```
    
    (Not sure how to add that to the tests.)
    
    Also fix a SEGV with -s if the hostname doesn't contain a '.'.
    
    Also switch to the FLAG() macro.
    
    Also add the missing -s to the synopsis.
    
    Bug: http://b/123123255
    
  - xargs: make --help match reality.
    
    Implement -p, -t, and -r.
    
    Add some missing tests.
    
    Move -L and -x back to TODO since they're not implemented and I haven't
    yet even understood what they're supposed to do.
    

* Update platform/superproject from branch 'master'
  to a2e693b0bd416faa39648c67ebc82d47c29009a0
  - Update git submodules
    
    * Update external/toybox from branch 'master'
      to a065dbe6c5d6eb6b723cf04c08a7beeccf1026c9
      - Merge remote-tracking branch 'toybox/master' into HEAD
        
        Change-Id: Ib387b8d25ff1d36bff7a017fd59ef47fbc4e1adf
        
      - Fix sigjmp_buf/jmp_buf mismatches.
        
        Broke the bionic build:
        
          external/toybox/toys/net/netcat.c:188:37: error: incompatible pointer types assigning to 'sigjmp_buf *' (aka 'long (*)[33]') from 'jmp_buf *' (aka 'long (*)[32]') [-Werror,-Wincompatible-pointer-types]
                  if (toys.optflags&FLAG_L) NOEXIT(child = XVFORK());
                                            ^~~~~~~~~~~~~~~~~~~~~~~~
          external/toybox/lib/lib.h:375:19: note: expanded from macro 'NOEXIT'
          #define NOEXIT(x) WOULD_EXIT(_noexit_res, x)
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~
          external/toybox/lib/lib.h:367:16: note: expanded from macro 'WOULD_EXIT'
            toys.rebound = &_noexit; \
                         ^ ~~~~~~~~
          1 error generated.
        
      - Actually calculating/displaying a reasonable time.
        
        Not yet setting, no server/multicast, should validate source address...
        
      - Add more comments to ps.c and replace hardcoded value with a macro.
        
        If table grows >64 entries XX needs to change, but it can't be 128 yet
        because the slot value is a signed char. Currently 59 entries in table...
        
      - Have test.sh use portability.sh too.
        
      - Factor out scripts/portability.sh and have genconfig.sh use it to find sed/gsed.
        
      - Fix various warnings building on FreeBSD.
        
      - hostname: fix behavior when in jail.
        
        Only -d and -f should cause a DNS lookup. The rest should just act
        directly on the result of gethostname(3). Encountered with the AOSP
        buildbots' use of nsjail, but tested with both the Debian hostname and
        toybox hostname thus:
        
        ```
        unshare -Uunr sh
        hostname android-build
        hostname
        hostname -s
        hostname -d
        hostname -f
        ```
        
        (Not sure how to add that to the tests.)
        
        Also fix a SEGV with -s if the hostname doesn't contain a '.'.
        
        Also switch to the FLAG() macro.
        
        Also add the missing -s to the synopsis.
        
        Bug: http://b/123123255
        
      - xargs: make --help match reality.
        
        Implement -p, -t, and -r.
        
        Add some missing tests.
        
        Move -L and -x back to TODO since they're not implemented and I haven't
        yet even understood what they're supposed to do.