Update git submodules
* Update platform/superproject from branch 'master'
  to a9205fd816e683a3ba372785137a47d2ffcce1d2
  - Update git submodules
    
    * Update build/soong from branch 'master'
      to 0f6aa7b56fb9edd508d3c84cf1219c5491aa9ba8
      - Merge "Fail gracefully when apek_key is not found"
      - Fail gracefully when apek_key is not found
        
        When the private key file can not be obtained, e.g., due to missing git
        project where the apex_key module is defined, fail gracefully with an
        error message instead of panicing.
        
        Bug: 119256776
        Test: modify the key property in /systme/apex/Android.bp to
        apex.test.key2 and run `ALLOW_MISSING_DEPENDENCIES=true m apex.test`
        The build fails with
        
        error: system/apex/Android.bp:32:8: module "apex.test" variant "android_common_apex.test": key: private_key for "apex.test.key2" could not be found
        
        Change-Id: I2cd5fed0f046de1f0b380fbdac5f8b82816b0e24