Update git submodules
* Update platform/external/robolectric from branch 'master'
  to d51cb97e9934f408a401b6f945d8bb12b0c3d281
  - Merge "Merge branch 'upstream-google' into rng7 Bug: 263483214 Test: atest -c MyRoboTests"
  - Merge branch 'upstream-google' into rng7
    Bug: 263483214
    Test: atest -c MyRoboTests
    
    Change-Id: Idf85ceeb3e0b4b18dfc2eb36e10f22b254fca400
    
  - Override setInterface and provide outgoing data stream in ShadowUsbDeviceConnection.
    
    Make UsbDeviceConnection easier to use in Robolectric tests by:
    
    - making sure setInterface does not return "false", since the systems under test may always expect a "true" result
    - providing access to the outgoing data via an InputStream, so that callers may decide how many bytes to fetch at a time and also know how many bytes have been read/written.
    
    PiperOrigin-RevId: 498004133
    
  - Add shadow implementation for UserManager#isHeadlessSystemUserMode()
    
    PiperOrigin-RevId: 497655145
    
  - Add ShadowUIModeManager#setCurrentModeType
    
    PiperOrigin-RevId: 497233920
    
  - Update DefaultNativeRuntimeLoader to work in RNG
    
    With Robolectric Native Graphics (RNG), the structure of the JAR file(s)
    containing data will now include a `fonts` directory that contains system
    fonts, as well as a separate ICU dat file. Previously the dat file was built
    into the shared objects, but a separate dat files is equivalent.
    
      fonts
        fonts.xml
        *.ttf
      icu
        icudt68l.dat
      native
        linux
          x86_64
            librobolectric-nativeruntime.so
    
    Update DefaultNativeRuntimeLoader to support this new format. There will
    be forthcoming commits to actually bring these resources to the Robolectric
    build process.
    
    PiperOrigin-RevId: 497012102
    
  - Add ShadowStorageStatsManager implementation of queryStatsForUser()
    
    This can be used to query StorageStats with matching storage UUID and user handle.
    
    PiperOrigin-RevId: 496812921
    
  - Update README.md to point to 4.9.1
    
  - Fix API signature of SpeechRecognizer#createSpeechRecognizer in doc
    
    Signed-off-by: utzcoz <utzcoz@outlook.com>
    
  - Ensure ShadowSpeechRecognizer can work with SDK 28
    
    Use looseSignature and Object to replace RecognitionSupportCallback and
    RecognitionSupport to avoid NoClassDefFoundError.
    
    Signed-off-by: utzcoz <utzcoz@outlook.com>
    
  - Use binary resources for the 'nativeruntime' project
    
    Previously nativeruntime tests would not execute in SDK > 28 in Gradle
    as they were not configured to run in binary resources.
    
    To use binary resources for a project, a test_config.properties file has
    to be added to the test resources, and a resources.ap_ file has to be
    generated using the scripts/build-resources.sh script.
    
  - Disable auto-correct for EspressoTest's EditText
    
    Signed-off-by: utzcoz <utzcoz@outlook.com>
    
  - Fix format of androidx_test's layout xml files
    
    Signed-off-by: utzcoz <utzcoz@outlook.com>
    
  - Add junit4 Enclosed runner compatibility tests
    
    Signed-off-by: utzcoz <utzcoz@outlook.com>
    
  - Merge branch 'google' into 'master'
    
  - Remove unused code for ReflectionHelperTest
    
    Signed-off-by: utzcoz <utzcoz@outlook.com>
    
  - Use \R as regex's linebreak matcher for ExpectedLogMessagesRuleTest
    
    From JDK 8, there is a new line break matcher \R that can be used to
    match linebreak on most common using OSes, for example Linux's \n and
    Windows' \r\n. ExpectedLogMessagesRuleTest uses \n as linebreak matcher
    and it will fail on Windows platform. This CL uses \R to replace \n to
    gain better supporting of ExpectedLogMessagesRuleTest on common OSes.
    With this CL, we can run ExpectedLogMessagesRuleTest without failures on
    Windows now.
    
    Signed-off-by: utzcoz <utzcoz@outlook.com>
    
  - Add test-services for instrumentation-test modules
    
    It can be used to generate screenshot when found test failure.
    
    Signed-off-by: utzcoz <utzcoz@outlook.com>
    
  - Fix package name in AndroidManifest.xml of compat-target28
    
    Signed-off-by: utzcoz <utzcoz@outlook.com>
    
  - Merge branch 'google' into 'master'
    
  - Remove lifecycle-common dependency
    
    lifeycle-common is a transitive dependency of androidx.test:core, and we
    don't need to declare it explicitly.
    
    We can see this relationship with
    `./gradlew :integration_tests:androidx:dependencies`:
    
    +--- androidx.test:core:1.5.0
    |    +--- androidx.annotation:annotation:1.2.0 -> 1.3.0
    |    +--- androidx.test:monitor:1.6.0 (*)
    |    +--- androidx.test.services:storage:1.4.2
    |    |    +--- androidx.annotation:annotation:1.2.0 -> 1.3.0
    |    |    +--- androidx.test:monitor:1.6.0 (*)
    |    |    +--- com.google.code.findbugs:jsr305:2.0.2 -> 3.0.2
    |    |    \--- androidx.test:annotation:1.0.1 (*)
    |    +--- androidx.lifecycle:lifecycle-common:2.3.1 -> 2.4.0
    |    |    \--- androidx.annotation:annotation:1.1.0 -> 1.3.0
    |    +--- androidx.tracing:tracing:1.0.0 (*)
    |    +--- com.google.guava:listenablefuture:1.0 -> 9999.0-empty-to-avoid-conflict-with-guava
    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.7.10 (*)
    |    \--- androidx.concurrent:concurrent-futures:1.1.0
    |         +--- androidx.annotation:annotation:1.1.0 -> 1.3.0
    |         \--- com.google.guava:listenablefuture:1.0 -> 9999.0-empty-to-avoid-conflict-with-guava
    
    Signed-off-by: utzcoz <utzcoz@outlook.com>
    
  - Add shadow for LocaleManager#getSystemLocales
    
    Signed-off-by: utzcoz <utzcoz@outlook.com>
    
  - Enable openRawResourceFd for ResourcesTest
    
    Signed-off-by: utzcoz <utzcoz@outlook.com>
    
  - CI: Keep dependency the same as robolectric.org for Windows building
    
    See https://robolectric.org/building-robolectric/ for details.
    
    Signed-off-by: utzcoz <utzcoz@outlook.com>
    
  - Bump ASM to 9.4
    
    Signed-off-by: utzcoz <utzcoz@outlook.com>
    
  - Update to androidx.test 11.04.2022 stable release
    
    Signed-off-by: utzcoz <utzcoz@outlook.com>
    
  - Use uninterruptibly acquire for ResTable's lock
    
    In complex CI environment, the thread that parsing resource
    might be interrupted with unknown reason, and old interruptable
    acquire method throws InterruptException and causes a
    RuntimeException in ResTable#lock(). That might cause flaky
    tests. This CL selects to use un-interruptable acquire method
    to avoid this occasion.
    
    Signed-off-by: utzcoz <utzcoz@outlook.com>
    
  - Add CI job to validate :preinstrumented:instrumentAll
    
    Signed-off-by: utzcoz <utzcoz@outlook.com>
    
  - Only filter sdk when PREINSTRUMENTED_SDK_VERSIONS is not empty
    
    This CL can fix building error when PREINSTRUMENTED_SDK_VERSIONS is
    empty/not set when running command
    `./gradlew :preinstrumented:instrumentAll`.
    
    I tested it locally with following two commands:
    
    ./gradlew :preinstrumented:instrumentAll
    PREINSTRUMENTED_SDK_VERSIONS=33 ./gradlew :preinstrumented:instrumentAll
    
    Signed-off-by: utzcoz <utzcoz@outlook.com>
    
  - Migrate shadows/playservices to AndroidX
    
  - Add missed override for LocalActivityInvoker#startActivityForResult
    
    Signed-off-by: utzcoz <utzcoz@outlook.com>
    
  - Enable Implements validation on Gradle again
    
    Signed-off-by: utzcoz <utzcoz@outlook.com>
    
  - Bump AGP to 7.3.1
    
    Signed-off-by: utzcoz <utzcoz@outlook.com>
    
  - fix: Avoid referring to Android S's TelephonyCallback
    
  - Enclose The Robolectric.buildActivity() call with in try
    
  - Remove unused looseSignatures from ShadowConextHubClient
    
    Signed-off-by: utzcoz <utzcoz@outlook.com>
    
  - Update to androidx.test 10.26.2022 RC release
    
    Signed-off-by: utzcoz <utzcoz@outlook.com>
    
  - Fix android-9.0.0_r12 ResourceTypes.h link for ResTable
    
    Signed-off-by: utzcoz <utzcoz@outlook.com>
    
  - Update snapshot version to 4.10 in README.md
    
    Signed-off-by: utzcoz <utzcoz@outlook.com>