Update git submodules
* Update platform/prebuilts/asuite from branch 'master'
  to 4bd35c19b8c517a690994b937a4b3646d4f22f78
  - Merge "ASuite: update prebuilt acloud by uploader.(6058269)."
  - ASuite: update prebuilt acloud by uploader.(6058269).
    
    The prebuilt acloud was downloaded from:
        aosp-master/aosp_cf_x86_phone-userdebug:6058269.
    SHA256:a818f9191d501d78d8ad3be1f663d526d7818692ac60dc5777b572fdeaf5448e
    
    2019-12-08 6058269 6014702
    aosp/1181804 4807543: Write device information when instance fail during ssh process.
    aosp/1169225 00fe101: Acloud: Support remote image on the arm64 platform.
    aosp/1152896 7479ce3: acloud: fix py3 compatible issue: NameError:  of name 'raw_input' is not defined
    aosp/1178556 e119a2e: Add unittest for pull.py
    aosp/1177285 53efe26: Add in test cases for list.py
    aosp/1151778 35556da: acloud: fix py3 compatible issue: AttributeError of object has no attribute 'iteritems'.
    aosp/1180043 c98ae06: acloud: create_test.py failed cause by create not exist find_executable
    aosp/1179862 f7ec252: Support mb size format for memory property
    aosp/1177282 487873d: acloud create with local-image on the remote arm64 host.
    aosp/1156449 1debbc3: acloud: fix py3 compatible issue: AttributeError: 'BuildInfo' object has no attribute '__dict__'
    aosp/1157963 6e30cc5: acloud: fix py3 compatible issue: ModuleNotFoundError: No module named 'distutils.spawn'
    aosp/1178544 1e2be8a: Exclude __repr__ line in coverage report
    aosp/1177284 67645b4: Add in test cases for create.py
    aosp/1178545 f5e0373: Add in test cases for gcompute_client_test.py.
    aosp/1178542 c18944d: Apply --boot-timeout to local goldfish instance
    aosp/1177286 85f89da: Pass --gpu to local goldfish instance
    aosp/1175284 d43f293: Add the args to support the remote arm64 host.
    aosp/1175024 0f29ab9: Support creating local goldfish instance with no window
    aosp/1174069 28f5163: Fix setup.py
    aosp/1171769 c1df99d: Add build_target to metadata for cheeps
    aosp/1173794 2c9b852: Fix the wrong instance name for remote image.
    aosp/1157044 3d9000d: List instances to show zone information.
    aosp/989386 a6a953a: Deprecate the bucket settings during acloud setup process.
    aosp/1171988 31d01ca: Add unittest for remote_instance_cf_device_factory.py
    aosp/1171995 a3752b1: Support listing only local instances
    aosp/1158603 9037ee4: Support deleting local goldfish instances
    aosp/1171984 755ad48: Args --num should not be used for local instance.
    aosp/1151738 b65b94d: acloud: fix py3 compatible issue: 'dict' object has no attribute 'iterkeys'
    
    Test: source build/envsetup.sh && lunch
          acloud create
          acloud create --local-image
          acloud create --local-image --local-instance -y
          acloud create --local-instance -y
          acloud list
          acloud reconnect
          acloud delete
          acloud delete --instance_names ins-c232b324-6064066-aosp-cf-x86-phone-userdebug
          acloud create_cf then delete
              acloud create_cf --multi-stage-launch --branch aosp-master --build-target aosp_cf_x86_phone-userdebug --build-id 5818763
              acloud delete --instance_names ins-bdd06773-5818763-aosp-cf-x86-phone-userdebug
          acloud delete --adb-port {port}
          acloud delete --all
    
    Change-Id: I46965c4e059fb7d0b77706537a4806748d84456f
    

* Update platform/superproject from branch 'master'
  to f219499a57d058b93c0b3655b206b87f45eefe9a
  - Update git submodules
    
    * Update prebuilts/asuite from branch 'master'
      to 4bd35c19b8c517a690994b937a4b3646d4f22f78
      - Merge "ASuite: update prebuilt acloud by uploader.(6058269)."
      - ASuite: update prebuilt acloud by uploader.(6058269).
        
        The prebuilt acloud was downloaded from:
            aosp-master/aosp_cf_x86_phone-userdebug:6058269.
        SHA256:a818f9191d501d78d8ad3be1f663d526d7818692ac60dc5777b572fdeaf5448e
        
        2019-12-08 6058269 6014702
        aosp/1181804 4807543: Write device information when instance fail during ssh process.
        aosp/1169225 00fe101: Acloud: Support remote image on the arm64 platform.
        aosp/1152896 7479ce3: acloud: fix py3 compatible issue: NameError:  of name 'raw_input' is not defined
        aosp/1178556 e119a2e: Add unittest for pull.py
        aosp/1177285 53efe26: Add in test cases for list.py
        aosp/1151778 35556da: acloud: fix py3 compatible issue: AttributeError of object has no attribute 'iteritems'.
        aosp/1180043 c98ae06: acloud: create_test.py failed cause by create not exist find_executable
        aosp/1179862 f7ec252: Support mb size format for memory property
        aosp/1177282 487873d: acloud create with local-image on the remote arm64 host.
        aosp/1156449 1debbc3: acloud: fix py3 compatible issue: AttributeError: 'BuildInfo' object has no attribute '__dict__'
        aosp/1157963 6e30cc5: acloud: fix py3 compatible issue: ModuleNotFoundError: No module named 'distutils.spawn'
        aosp/1178544 1e2be8a: Exclude __repr__ line in coverage report
        aosp/1177284 67645b4: Add in test cases for create.py
        aosp/1178545 f5e0373: Add in test cases for gcompute_client_test.py.
        aosp/1178542 c18944d: Apply --boot-timeout to local goldfish instance
        aosp/1177286 85f89da: Pass --gpu to local goldfish instance
        aosp/1175284 d43f293: Add the args to support the remote arm64 host.
        aosp/1175024 0f29ab9: Support creating local goldfish instance with no window
        aosp/1174069 28f5163: Fix setup.py
        aosp/1171769 c1df99d: Add build_target to metadata for cheeps
        aosp/1173794 2c9b852: Fix the wrong instance name for remote image.
        aosp/1157044 3d9000d: List instances to show zone information.
        aosp/989386 a6a953a: Deprecate the bucket settings during acloud setup process.
        aosp/1171988 31d01ca: Add unittest for remote_instance_cf_device_factory.py
        aosp/1171995 a3752b1: Support listing only local instances
        aosp/1158603 9037ee4: Support deleting local goldfish instances
        aosp/1171984 755ad48: Args --num should not be used for local instance.
        aosp/1151738 b65b94d: acloud: fix py3 compatible issue: 'dict' object has no attribute 'iterkeys'
        
        Test: source build/envsetup.sh && lunch
              acloud create
              acloud create --local-image
              acloud create --local-image --local-instance -y
              acloud create --local-instance -y
              acloud list
              acloud reconnect
              acloud delete
              acloud delete --instance_names ins-c232b324-6064066-aosp-cf-x86-phone-userdebug
              acloud create_cf then delete
                  acloud create_cf --multi-stage-launch --branch aosp-master --build-target aosp_cf_x86_phone-userdebug --build-id 5818763
                  acloud delete --instance_names ins-bdd06773-5818763-aosp-cf-x86-phone-userdebug
              acloud delete --adb-port {port}
              acloud delete --all
        
        Change-Id: I46965c4e059fb7d0b77706537a4806748d84456f