Update git submodules
* Update kernel/configs from branch 'master'
  to 71c8608ebdbae9cd106e8de83125c4625cc0055a
  - Revert "GKI: android-6.1: Require uid_sys_stats"
    
    Revert submission 2480476-uid_sys_stats-b219790626
    
    Reason for revert: Causes the following build failure on aosp-master-with-phones with aosp_cf_x86_64_phone-userdebug:
    
    ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No compatible kernel requirement found (kernel FCM version = 8).
    For kernel requirements at matrix level 8, Missing config CONFIG_UID_SYS_STATS
    : Success
    INCOMPATIBLE
    
    Reverted changes: /q/submissionid:2480476-uid_sys_stats-b219790626
    
    Change-Id: Ib593f1e1d4702eec299108dd5df1f34b8c9e69b3