Update git submodules
* Update platform/external/rust/cxx from branch 'master'
  to 68dff21abcb03d090b465afcc125ab0c0c1875d0
  - Merge "Upgrade rust/cxx to 36d9ac1fab726e14305ce1919ebf8a3d64949d30"
  - Grant visibility to the CompOS APEX. am: 149626b05c
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1840154
    
    Change-Id: I94f030e3f3640bd7a99739e085955fef0c08eae8
    
  - Upgrade rust/cxx to 36d9ac1fab726e14305ce1919ebf8a3d64949d30
    
    Test: make
    Change-Id: I45372b36cbe5c64d556df5e0b7ef9451e6c65ea5
    
  - Update ui test suite to nightly-2021-09-14
    
  - Merge pull request #932 from dtolnay/clippy
    
    Re-enable clippy after upstream crash fix
  - Remove ignore of deleted filter_map clippy lint
    
        warning: lint `clippy::filter_map` has been removed: this lint has been replaced by `manual_filter_map`, a more specific lint
         --> macro/src/lib.rs:6:5
          |
        6 |     clippy::filter_map,
          |     ^^^^^^^^^^^^^^^^^^
          |
          = note: `#[warn(renamed_and_removed_lints)]` on by default
    
  - Ignore derivable_impls lint in generated code
    
  - Ignore if_same_then_else clippy lint
    
        error: this `if` has identical blocks
           --> gen/build/src/gen/write.rs:704:33
            |
        704 |           if arg.ty == RustString {
            |  _________________________________^
        705 | |             write!(out, "const ");
        706 | |         } else if let Type::RustVec(_) = arg.ty {
            | |_________^
            |
            = note: `-D clippy::if-same-then-else` implied by `-D clippy::all`
        note: same as this
           --> gen/build/src/gen/write.rs:706:49
            |
        706 |           } else if let Type::RustVec(_) = arg.ty {
            |  _________________________________________________^
        707 | |             write!(out, "const ");
        708 | |         }
            | |_________^
            = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#if_same_then_else
    
        error: this `if` has identical blocks
           --> macro/src/expand.rs:430:33
            |
        430 |           if arg.ty == RustString {
            |  _________________________________^
        431 | |             quote!(#var #colon *const #ty)
        432 | |         } else if let Type::RustVec(_) = arg.ty {
            | |_________^
            |
            = note: `-D clippy::if-same-then-else` implied by `-D clippy::all`
        note: same as this
           --> macro/src/expand.rs:432:49
            |
        432 |           } else if let Type::RustVec(_) = arg.ty {
            |  _________________________________________________^
        433 | |             quote!(#var #colon *const #ty)
        434 | |         } else if let Type::Fn(_) = arg.ty {
            | |_________^
            = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#if_same_then_else
    
  - Re-enable clippy after upstream crash fix
    
  - Delete unused span field from ForeignName
    
        warning: field is never read: `span`
          --> macro/src/syntax/names.rs:12:5
           |
        12 |     span: Span,
           |     ^^^^^^^^^^
           |
           = note: `#[warn(dead_code)]` on by default
    
  - Release 1.0.54
    
  - Merge pull request #925 from dtolnay/cxxstringreserve
    
    Expose reserve on CxxString
  - Expose reserve on CxxString
    
  - Merge pull request #924 from dtolnay/ruststringcap
    
    Expose capacity and reserve on rust::String
  - Expose capacity and reserve on rust::String
    
  - Merge pull request #923 from dtolnay/unsafeop
    
    Adopt unsafe_op_in_unsafe_fn style
  - Adopt unsafe_op_in_unsafe_fn style
    
  - Update Bazel build to rustc 1.54.0
    
  - Rename slice nonnull ptr accessor to match std NonNull<[T]>::as_non_null_ptr
    
    https://doc.rust-lang.org/1.54.0/std/ptr/struct.NonNull.html#method.as_non_null_ptr
    
  - Skip Vec::reserve call more often in reserve_total
    
  - Merge pull request #922 from dtolnay/new_cap
    
    Consistently use new_cap in signatures of reserve_total
  - Consistently use new_cap in signatures of reserve_total
    
  - Merge pull request #921 from dtolnay/cstr-reserve
    
    Fix over-reserve in rust::String::c_str
  - Fix over-reserve in rust::String::c_str
    
  - Build and run syn build script in Buck and Bazel rules
    
  - Release 1.0.53
    
  - Lockfile update
    
  - Merge pull request #919 from isg/no-shadow
    
    Don't shadow `pos` in C++ rust::Slice implementation
  - Switch from 'index' to 'ptr'
    
  - Don't shadow `pos`
    
  - Update ui test suite to nightly-2021-08-20
    
  - Update ui test suite to nightly-2021-08-18
    
  - Merge pull request #916 from dtolnay/bazeledition
    
    Remove rules that override rules_rust's default edition
  - Format Bazel bzl files with buildifier
    
  - Remove rules that override rules_rust's default edition
    
  - Merge pull request #915 from dtolnay/buildscript
    
    Buck: build and execute proc-macro2 build script
  - Buck: build and execute proc-macro2 build script
    
  - Merge pull request #914 from dtolnay/buildscript
    
    Bazel: build and execute proc-macro2 build script
  - Format BUCK files with buildifier
    
  - Bazel: build and execute proc-macro2 build script
    
  - Release 1.0.52
    
  - Lockfile update
    
  - Merge pull request #912 from dtolnay/stringclear
    
    Add CxxString::clear method
  - Add CxxString::clear method
    
  - Merge pull request #911 from dtolnay/resultui
    
    Update ui test suite to nightly-2021-08-12
  - Tweak extern Rust Result spans to work with nightly-2021-08-12
    
  - Update ui test suite to nightly-2021-08-12
    
  - Upgrade rust/cxx to 971082d9dc57e581e046b1b10596a97c41287374 am: 8624dbf109 am: 91082d2c57
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1791076
    
    Change-Id: I64835dd70a41c5e05b886147ab09a7ad68565116
    
  - Upgrade rust/cxx to 971082d9dc57e581e046b1b10596a97c41287374 am: 8624dbf109
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1791076
    
    Change-Id: Ib746380f58aa732bfc4f59347f41c6fc39aff56b
    
  - Upgrade rust/cxx to 251cf910ebb5cc6eb628a1e48cacbea6cfdf05c3 am: d80a29bb56 am: 06ea7cdd21
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1744696
    
    Change-Id: I5ed5929faf0db16282096581e8d85f892c644809
    
  - Revert "Suppress unknown clippy lints" am: d5da53acde am: 2c07afe4b0
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1744695
    
    Change-Id: I624c35ba643c92d2258933ff29d3e3f2cc53e7db
    
  - Upgrade rust/cxx to 251cf910ebb5cc6eb628a1e48cacbea6cfdf05c3 am: d80a29bb56
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1744696
    
    Change-Id: I8d0f5a54ca5fb0b25a23fd16fb75e4a00ab3f76e
    
  - Revert "Suppress unknown clippy lints" am: d5da53acde
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1744695
    
    Change-Id: Ib34641f9c2fa06d33f15deea71dc8ade310ab1ee
    
  - Suppress unknown clippy lints am: 05e7ae87b8 am: 1b1fa6ea3f am: fbed154c91
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1668767
    
    Change-Id: I99d46b6af14e79124cb92050ea0862ba8b19feea
    
  - Update CXX to 1.0.42 am: b4406114c9 am: f1e51d9d13 am: 104a118ace
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1668766
    
    Change-Id: Iddfc0021ba8e2621691a0c3310f3f5215821ed70
    
  - Suppress unknown clippy lints am: 05e7ae87b8 am: 1b1fa6ea3f
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1668767
    
    Change-Id: Id5a89e6480aec0c74f21eb3ecb089418f1760551
    
  - Update CXX to 1.0.42 am: b4406114c9 am: f1e51d9d13
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1668766
    
    Change-Id: I8f1a321a090a956de6f427229b3ec888531cb091
    
  - Use whole_static_library for cxx bridge library am: 6e7104cc54 am: 99dd1ee8ca am: 49d18c7b8c
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1654112
    
    Change-Id: I6e4a95b723d1e3c52d5b163c92cd4d0fa78b354f
    
  - Use whole_static_library for cxx bridge library am: 6e7104cc54 am: 99dd1ee8ca
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1654112
    
    Change-Id: Ic9dccee02b369637a36a676bc871b406090604f9
    
  - [automerger skipped] Mark ab/7061308 as merged in stage. am: 519988c15d -s ours am: beb4979281 -s ours
    
    am skip reason: Change-Id Ie5f48d580aea441a055d5c6ba488e72c28078c23 with SHA-1 440eb71f1a is in history
    
    Original change: undetermined
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Idd9eb5ef3c2357686d434c441c9fd087faf61b80
    
  - [automerger skipped] Mark ab/7061308 as merged in stage. am: 519988c15d -s ours
    
    am skip reason: Change-Id Ie5f48d580aea441a055d5c6ba488e72c28078c23 with SHA-1 440eb71f1a is in history
    
    Original change: undetermined
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Ieecc38a64a540c06f3702752d6ac00312dc503ab
    
  - Add METADATA and OWNERS am: 3cd49d1b4b am: 768afab48d am: 3b4616fa13
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1592774
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Ieee886aba9d18266c1c504634b47db2778980269
    
  - Add METADATA and OWNERS am: 3cd49d1b4b am: 768afab48d
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1592774
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I3303c20e0602d60efbe47b6e2dcb0919a4939f67
    
  - Add METADATA to cxx: Apache2+MIT=NOTICE am: b280fa8234 am: f8bab4279d am: 3ad746382d
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1593631
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I6f6d4ca66aa950360175b613a5effcfa472255b5
    
  - Add METADATA to cxx: Apache2+MIT=NOTICE am: b280fa8234 am: f8bab4279d
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1593631
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Ia174806938aac003a79ec588c772399ef33b794b
    
  - [LSC] Add LOCAL_LICENSE_KINDS to external/rust/cxx am: 28353e514c am: da88a3d3c7 am: ecdeea8a64
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1588706
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I14c196a6f582760fc02f61602a277129e6e534cb
    
  - [LSC] Add LOCAL_LICENSE_KINDS to external/rust/cxx am: 28353e514c am: da88a3d3c7
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1588706
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I4ffa63eb8c7b86ae35a3f774b2e2033b448005b7
    
  - cxx: update libcxxbridge version number & make apex availible am: 0d15d493c3 am: 91a59a6c42 am: 440eb71f1a
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1513255
    
    Change-Id: I03bc69d1cccb827f1b8487439ddb30c690519267
    
  - Merge "Mark ab/6881855 as merged" into stage-aosp-master am: 01fe6d9f39 am: a85821f14b
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/external/rust/cxx/+/13112884
    
    Change-Id: I04a9ef35c9fc6fcea151d2c2278fdd83a6e801bb
    
  - Update to 0.5.9 am: 03f5160b1d am: 711393d7f5 am: 0fb4aeed22
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1508603
    
    Change-Id: I3404631e28485ca0680e1c0a285b8a4051e0903c
    
  - allow libcxx to be used from host builds am: c95654cb0e am: c3174538a4 am: 6b3cc117af am: 4d05a60731
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1503951
    
    Change-Id: I48adf9e40c01b88fa6ffec55b6a486629913555c
    
  - [automerger skipped] Skip ab/6749736 in stage. am: 93dc6fced3 -s ours am: e9c210e824 -s ours am: 56084ee9aa -s ours
    
    am skip reason: Change-Id Ifbe1373f463dd3e18f41869c3e595d452306585f with SHA-1 bde5261051 is in history
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/external/rust/cxx/+/12796088
    
    Change-Id: I38f0c570dc688434df1261ae5246d50d8b0dd445
    
  - [automerger skipped] Mark Android R (rvc-dev-plus-aosp-without-vendor@6692709) as merged am: 2a38800248 -s ours am: 42d8ff24b4 -s ours am: 961aff386f -s ours am: 10fc1fac8a -s ours
    
    am skip reason: Change-Id I4727c8b4cfcb7561b7c63525fcffbc2837650dbe with SHA-1 bb817b3aed is in history
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/external/rust/cxx/+/12469357
    
    Change-Id: Ic8d6ed29d91438c7dccd2e71d3f025a836a1820b
    
  - Update to latest cxx am: 073210719e am: cff6327c2a am: aa2211ba6f am: bde5261051 am: 097ee542df
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1384260
    
    Change-Id: I9846566cbcd32ee21841e2a43fb5c0385711e4aa
    
  - Add cxx build and demo am: 5a12fc8a22 am: 6fbc7cb7e0 am: f83cb942b4 am: bb02e48f3b am: 676e45257a
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1330215
    
    Change-Id: Ie6367613387d1025a5a338eef31714159084791f
    
  - Add METADATA to cxx: Apache2+MIT=NOTICE
    
    Bug: 68860345
    Bug: 69058154
    Bug: 151953481
    
    Test: no code changes
    
    Exempt-From-Owner-Approval: janitorial work
    Change-Id: I63513e4d7ba444e9bf0e946b8a9224d6e2d8cede
    
  - Merge remote-tracking branch 'origin/upstream-master' am: c46c875e90 am: 773720ab13 am: bb817b3aed am: 957ec24422 am: 3e800af7dc
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/cxx/+/1322178
    
    Change-Id: I96c7f1f9db64b7e4c3066da9ab5d2c29d83e5825