Update git submodules
* Update platform/packages/apps/Dialer from branch 'master'
  to a5ba47346d865c8dc515f87f03de7cb75236310a
  - Merge "Use platform error_prone_annotations, add it to dialer-rootcomponentprocessor"
  - Use platform error_prone_annotations, add it to dialer-rootcomponentprocessor
    
    The jdk-11.0.13 update triggers an error in the errorprone build:
    error: cannot access CompatibleWith
      class file for com.google.errorprone.annotations.CompatibleWith not found
    
    Add error_prone_annotations to the dialer-rootcomponentprocessor
    dependencies, and replace the other usages of dialer-error-prone-target
    in the file to match.
    
    Bug: 205944740
    Test: m RUN_ERROR_PRONE=true out/host/common/obj/JAVA_LIBRARIES/dialer-rootcomponentprocessor_intermediates/classes-full-debug.jar
    Change-Id: Ic6cf6614e522919b793744313adfd4c8763b4b61
    
  - Merge "Merge Android 12"
  - Merge Android 12
    
    Bug: 202323961
    Merged-In: I269ea522ba7356dca0bfa43e8a8ee8acdba7b7a2
    Change-Id: Id163159e965a5325ff9f2f51d43ab3214fb55779
    
  - Merge sc-dev-plus-aosp-without-vendor@7634622
    
    Merged-In: I975ce2e612e979884c82ef9da6e70b70dce076aa
    Change-Id: I269ea522ba7356dca0bfa43e8a8ee8acdba7b7a2
    
  - Merge "Use Option.ofNullable instead of Optional.of" am: a85c99c791
    
    Original change: https://android-review.googlesource.com/c/platform/packages/apps/Dialer/+/1792941
    
    Change-Id: I2bd64336f007caf8fc46b2ce3f03b5a0de45eb72
    
  - Merge "API level 30 upgrade: AOSP Dialer" am: e98287809e am: c5af967504
    
    Original change: https://android-review.googlesource.com/c/platform/packages/apps/Dialer/+/1782168
    
    Change-Id: I975ce2e612e979884c82ef9da6e70b70dce076aa
    
  - Merge "API level 30 upgrade: AOSP Dialer" am: e98287809e
    
    Original change: https://android-review.googlesource.com/c/platform/packages/apps/Dialer/+/1782168
    
    Change-Id: I92d5e86d7aca49249ef93884566d11b4e24438fd
    
  - Merge "Wait for IPv4 before sending VVM requests." am: 787c53e1a1 am: f82b164366
    
    Original change: https://android-review.googlesource.com/c/platform/packages/apps/Dialer/+/1724610
    
    Change-Id: I0accb088c4ca7d9d9b19bde7d00ab4b5806ac41a
    
  - Merge "Wait for IPv4 before sending VVM requests." am: 787c53e1a1
    
    Original change: https://android-review.googlesource.com/c/platform/packages/apps/Dialer/+/1724610
    
    Change-Id: I678654bfa7e16fe3a28119bf2a8b6e13b5f683c1
    
  - Merge "Dialer: correct the expanded search bar height" am: 36af0d9694 am: 382167042a
    
    Original change: https://android-review.googlesource.com/c/platform/packages/apps/Dialer/+/1760705
    
    Change-Id: I1c92b6d2a78415603fcfe45dc63332016a14929c
    
  - Merge "Dialer: correct the expanded search bar height" am: 36af0d9694
    
    Original change: https://android-review.googlesource.com/c/platform/packages/apps/Dialer/+/1760705
    
    Change-Id: I90b26025de14c24bfd8abf8ecf42dbbcb6f6c926
    
  - Merge "[LSC] Add LOCAL_LICENSE_KINDS to packages/apps/Dialer" am: 0db4c01541 am: 49e5a04b18 am: 5e0cce0470
    
    Original change: https://android-review.googlesource.com/c/platform/packages/apps/Dialer/+/1684469
    
    Change-Id: I3ad361075dc84399f53fd7783681a87f3ba56aa3
    
  - Merge "[LSC] Add LOCAL_LICENSE_KINDS to packages/apps/Dialer" am: 0db4c01541 am: 49e5a04b18
    
    Original change: https://android-review.googlesource.com/c/platform/packages/apps/Dialer/+/1684469
    
    Change-Id: I4f026b130763836dfc1c8ebef0251259d1f215cb
    
  - Merge "Fix NPE in DialerCall that cause it crash and failed to show disconnection error message." am: 5d01ebb84a am: e2eb24bd29 am: a31d71bd34
    
    Original change: https://android-review.googlesource.com/c/platform/packages/apps/Dialer/+/1671906
    
    Change-Id: Ic6cbd99e9daf9d0c34ab01da72b185571db36cbd
    
  - Merge "Fix NPE in DialerCall that cause it crash and failed to show disconnection error message." am: 5d01ebb84a am: e2eb24bd29
    
    Original change: https://android-review.googlesource.com/c/platform/packages/apps/Dialer/+/1671906
    
    Change-Id: I9c4c827c492b5ad148e0fe99b812bca2be053613
    
  - Merge "Dialer: Move assertion to top of method" am: 59e8aa3503 am: 546caf3c46 am: 871c1a4993
    
    Original change: https://android-review.googlesource.com/c/platform/packages/apps/Dialer/+/1634862
    
    Change-Id: I494efe983e044e8edfd4b7f08da3bb458a287ef4
    
  - Merge "Dialer: Move assertion to top of method" am: 59e8aa3503 am: 546caf3c46
    
    Original change: https://android-review.googlesource.com/c/platform/packages/apps/Dialer/+/1634862
    
    Change-Id: I34f6ab8e0b9a57c5747b7f0023df31a380061311
    
  - Merge "Add <uses-library> information." am: 989a10d131 am: 5e73662247 am: 8417eaa2e8
    
    Original change: https://android-review.googlesource.com/c/platform/packages/apps/Dialer/+/1628699
    
    Change-Id: I8744834e9c7e7c51db962c78bd814f704b816256
    
  - Merge "Add <uses-library> information." am: 989a10d131 am: 5e73662247
    
    Original change: https://android-review.googlesource.com/c/platform/packages/apps/Dialer/+/1628699
    
    Change-Id: I085500ec1ebf1c1334bff6d558e42c0b9048372a
    
  - [automerger skipped] Mark ab/7061308 as merged in stage. am: ff3f9e7f9f -s ours am: fe7008b6af -s ours
    
    am skip reason: Change-Id Ie83e55f1dfa33a110ac7054384a8aa78e4bbdcac with SHA-1 5e7b15bc95 is in history
    
    Original change: undetermined
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I545b2d3c7d4e47baba377e0c8d6934714aef0f52
    
  - Merge "[LSC] Add LOCAL_LICENSE_KINDS to packages/apps/Dialer" am: 6cc3d6e3cf am: 539e344311 am: 0a7baa70ec
    
    Original change: https://android-review.googlesource.com/c/platform/packages/apps/Dialer/+/1588532
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Iedd7f3b08ac4549e0c9a4afbd43551cb9a59e869
    
  - [automerger skipped] Mark ab/7061308 as merged in stage. am: ff3f9e7f9f -s ours
    
    am skip reason: Change-Id Ie83e55f1dfa33a110ac7054384a8aa78e4bbdcac with SHA-1 5e7b15bc95 is in history
    
    Original change: undetermined
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Ic2513d6ea42e269b1815cf2d60f9cae61e6dfad7
    
  - Merge "[LSC] Add LOCAL_LICENSE_KINDS to packages/apps/Dialer" am: 6cc3d6e3cf am: 539e344311
    
    Original change: https://android-review.googlesource.com/c/platform/packages/apps/Dialer/+/1588532
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I73f7a97e069f186371073901dedec90e7833f11f
    
  - Mark ab/6881855 as merged am: c81a999ca4 am: 5e7b15bc95
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/packages/apps/Dialer/+/13112987
    
    Change-Id: Ie85ff7c0e51296f4a4c0ea83c2645aaf89894040
    
  - [automerger skipped] Skip ab/6749736 in stage. am: 74fd529ae2 -s ours am: ced55f9702 -s ours am: c3c39f8c40 -s ours
    
    am skip reason: Change-Id Ic7d60bf2531edb57089955191d597ec7667c9e11 with SHA-1 67f41e0c8b is in history
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/packages/apps/Dialer/+/12797267
    
    Change-Id: I2708e748adcc57ec52ff2d6e54ee0ae88d7d2fd9
    
  - Merge "Fix selecting phone account dialog show error." am: 12095062b3 am: 603f062f7a am: b0406b16af am: ba8225eef4 am: 9a29981143
    
    Original change: https://android-review.googlesource.com/c/platform/packages/apps/Dialer/+/1428938
    
    Change-Id: I5caddcc27100708a9cb30c921645485bf5d2e7f4
    
  - [automerger skipped] Merge "Merge Android R" am: 816ad2b6a2 -s ours am: 2ec4698a1b -s ours am: c18c96890c -s ours am: efaf780e35 -s ours am: 04902d14bf -s ours
    
    am skip reason: Change-Id Ib83cd87683ae896de789cdf6cd0c801562a191d5 with SHA-1 62fe343bc4 is in history
    
    Original change: https://android-review.googlesource.com/c/platform/packages/apps/Dialer/+/1422454
    
    Change-Id: I7beb8c80fcf5fdaf74e2d423a42b6cd511b9aa7b
    
  - [automerger skipped] Merge Android R (rvc-dev-plus-aosp-without-vendor@6692709) am: 62fe343bc4 -s ours am: 998d78971c -s ours am: 6b3b3ff2f5 -s ours am: c439bf2afd -s ours
    
    am skip reason: Change-Id Ic08b97c9660daee8bd69db381ea55234d37a0106 with SHA-1 3b09f24d1d is in history
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/packages/apps/Dialer/+/12470219
    
    Change-Id: I72f40cfb8bb2272408f66924f0bdc81b238190fa
    
  - Merge "Update language to comply with Android's inclusive language guidance" am: 237d9b014c am: 45595d4753 am: 6b570f82d5 am: 67f41e0c8b am: 05e824b3e2
    
    Original change: https://android-review.googlesource.com/c/platform/packages/apps/Dialer/+/1378558
    
    Change-Id: Iac5cc419e476d7b037618dfa92803966b27bbbf8
    
  - Merge "Use AutoValue from external/auto" am: 434cfb8a4f am: 0199744c25 am: 3b09f24d1d am: 2f62dcca3c am: 56241ab4ec
    
    Original change: https://android-review.googlesource.com/c/platform/packages/apps/Dialer/+/1344937
    
    Change-Id: I8061901bf4af7d9784001418961abe71e2a4f339
    
  - Merge "Fix theme for PostCallActivity" am: e4e997f9fa am: 53884bc530 am: 6a594da485 am: f65f932be8 am: f4b8dc6652
    
    Change-Id: I19a92c9e8cd5ff31dbbc089b846473d8ebe68509
    
  - Add an exported flag in manifest
    
    With b/150232615, we will need an explicit value set for the exported
    flag when intent filters are present, as the default behavior is
    changing for future versions. This change adds the value reflecting the previous
    default to the manifest.
    
    These changes were made using an automated tool, the xml file may be
    reformatted slightly creating a larger diff. The only "real" change is
    the addition of "android:exported" to activities, services, and
    receivers that have one or more intent-filters.
    
    Bug: 150232615
    Test: TH
    Exempt-From-Owner-Approval: mechanical refactoring
    Change-Id: Ie488088abaa55ff7f83bc93bb126323ad3885ab3
    
  - Merge "Updated target SDK from 28 to 29." am: 8f1aba6733 am: e4893a40a1 am: 0ab5f8e230 am: 1538024ac6 am: 8872fc4102
    
    Change-Id: Id4f2b57e1791f611de155b066e3e983c121229aa
    
  - Merge "Dialer: Fix proto warning with optmize for lite" am: c251a5b0e9 am: 33e47c33df am: 6295a8e3c5 am: df82c1c210 am: 1e1d86716e
    
    Change-Id: I4395e7dc9c871ec909658ff7b8e67afafbab7b5e
    
  - [automerger skipped] DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp into stag-aosp-master am: 962bc9d662 -s ours am: a37ff821d8 am: 8f23e79b2a am: c6fd169654 -s ours
    
    am skip reason: subject contains skip directive
    
    Change-Id: I8e6fbb7ac77fdd2695454bf7a5afbf5a25ec3777
    
  - Merge " Failed to show hold call when user click swap and merge simultaneously" am: 017fa0a742 am: fe0fb0e663 am: 307fdf3941 am: 92d0181edb am: 4a7630811f
    
    Change-Id: Id260b2a83f2dfaed792177207f52105231347ead
    
  - [automerger skipped] DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp@6304901 into stag-aosp-master am: ec33062995 -s ours am: 43f86045f6 am: 810b45bf50 am: 1af827d1cf -s ours
    
    am skip reason: subject contains skip directive
    
    Change-Id: I59e225a6b097fb406b558fc168dc99a88db26809
    
  - [automerger skipped] Merge "Merge stage-aosp-master to aosp-master - DO NOT MERGE" am: 9cbdb82e0d am: f244f93c19 -s ours am: 27079a8bc1 am: 1acdf988ef am: c41c427491 -s ours
    am skip reason: subject contains skip directive
    
    Change-Id: I771951b6fe8f80ab43c6a96d09403e1a87747488
    
  - [automerger skipped] Merge stage-aosp-master to aosp-master - DO NOT MERGE am: cd3459f07b am: f581c5cbad -s ours am: d2d9f9e087 am: b62fa5884b am: ffb5cf77d8 -s ours
    am skip reason: subject contains skip directive
    
    Change-Id: I8190218a167952a0903f86af582263a42e22df6a