Update git submodules
* Update device/generic/goldfish-opengl from branch 'master'
  to 3aa4d080bb8c104b47c4ab16702fd3f9b28104c1
  - Merge changes I330881b7,I17bfa869,I985dc080,I76b16e1b,Id2cfbbdb, ...
    
    * changes:
      goldfish-opengl: use cpp_std=gnu++17 for Meson build
      goldfish-opengl: nuke unused code path in unregister_VkDeviceMemory
      goldfish-opengl: nuke SubAlloc::memoryTypeIndex
      goldfish-opengl: nuke SubAlloc::isDeviceAddressMemoryAllocation
      goldfish-opengl: nuke virtualHostVisibleBacking
      goldfish-opengl: nuke aligned_buf_{alloc, free}
      goldfish-opengl: nuke VirtioGpuHostmemResourceInfo
    
  - goldfish-opengl: use cpp_std=gnu++17 for Meson build
    
    Otherwise, this is observed sometimes depending on build
    machine:
    
    ../system/OpenglSystemCommon/HostConnection.h:146:18: error: ‘optional’ in namespace ‘std’ does not name a template type
    146 |     virtual std::optional<uint32_t> getFormatDrmFourcc(native_handle_t const* /*handle*/) {
              |                  ^~~~~~~~
    ../system/OpenglSystemCommon/HostConnection.h:146:13: note: ‘std::optional’ is only available from C++17 onwards
    146 |     virtual std::optional<uint32_t> getFormatDrmFourcc(native_handle_t const* /*handle*/) {
    
    BUG=202552093
    TEST=meson amd64-build/
         ninja -C amd64-build/
    
    Change-Id: I330881b78f8ab4ad4f85aeaf7f7296aafa832a25
    
  - goldfish-opengl: nuke unused code path in unregister_VkDeviceMemory
    
    The "direct mapped memory never goes to unregister!" seems to be
    correct and this seems like dead code.
    
    BUG=233803018
    TEST=run ./deqp-vk.memory.*
    
    Change-Id: I17bfa869fca401a350c8b5252b2ee417826ad100
    
  - goldfish-opengl: nuke SubAlloc::memoryTypeIndex
    
    Code examination reveals this value is exactly equal
    to info_VkDeviceMemory::memory.
    
    BUG=233803018
    TEST=run ./deqp-vk.memory*
    
    Change-Id: I985dc080aedff3912e8a3a77f22f1a697a19e488
    
  - goldfish-opengl: nuke SubAlloc::isDeviceAddressMemoryAllocation
    
    Not used.
    
    BUG=233803018
    TEST=run ./deqp-vk.memory*
    
    Change-Id: I76b16e1b62203113bd559ee5fc3d33e3e7d2e72d
    
  - goldfish-opengl: nuke virtualHostVisibleBacking
    
    Not used.
    
    BUG=233803018
    TEST=run ./deqp-vk.memory*
    
    Change-Id: Id2cfbbdb0207f399a2e5269598c8c95a0c9ceb8a
    
  - goldfish-opengl: nuke aligned_buf_{alloc, free}
    
    Never used in the Vulkan part of the code.
    
    BUG=233803018
    TEST=run ./deqp-vk.memory*
    
    Change-Id: I30a7a6cc8d2812e1dda7ab1e59dc29d250f5c13d
    
  - goldfish-opengl: nuke VirtioGpuHostmemResourceInfo
    
    Not used.
    
    BUG=233803018
    TEST=compile
    
    Change-Id: If4814eb6dc6831ec9160acaaa64fe4e5c1df206c