Update git submodules
* Update device/generic/goldfish-opengl from branch 'master'
  to 99e281754e6c5ab81d58158f88b64c9f4d8e4691
  - [build] Suppress -Wunused-but-set-parameter/variable
    
    This patch suppresses -Wunused-but-set-parameter and
    -Wunused-but-set-variable warnings that goldfish code
    does not comply with.
    The code that causes the issues is as the following:
    1) third_party/android/device/generic/goldfish-opengl/system/vulkan_enc/ResourceTracker.cpp:5191:33:
    error: parameter 'input_result' set but not used
    2) third_party/android/device/generic/goldfish-opengl/system/OpenglSystemCommon/ProcessPipe.cpp:223:10:
    error: variable 'isPipe' set but not used
    3) third_party/android/device/generic/goldfish-opengl/system/vulkan_enc/goldfish_vk_marshaling_guest.cpp:3270:51:
    error: variable 'check_pInputAssemblyState' set but not used
    4) third_party/android/device/generic/goldfish-opengl/system/vulkan_enc/goldfish_vk_marshaling_guest.cpp:3316:51:
    error: variable 'check_pRasterizationState' set but not used
    5) third_party/android/device/generic/goldfish-opengl/system/vulkan_enc/goldfish_vk_marshaling_guest.cpp:3260:49:
    error: variable 'check_pVertexInputState' set but not used)
    
    Change-Id: Icfec328a1dc239b046a1650e10aebc5a54be78c9