Update git submodules
* Update platform/external/perfetto from branch 'master'
  to 4557eae87e7cbdffed035438c474d2bed838db71
  - Merge "docs: fix typo in top 5 processes metrics example"
  - docs: fix typo in top 5 processes metrics example
    
    Bug: N/A
    
    In following example from https://perfetto.dev/docs/analysis/metrics,
    it turned out that by default trace_processor uses the SQL file name
    as the name for the metric, hence if we have
    
      - top_five_processes.sql
      - top_five_processes.proto
    
    In top_five_processes.proto, the metric has to be aligned.
    
    So instead of
    
      extend TraceMetrics {
        optional TopProcesses top_processes = 450;
      }
    
    It seems that it needs to be:
    
      extend TraceMetrics {
        optional TopProcesses top_five_processes = 450;
      }
    
    The original complaint from trace_processor is like below:
    
      $ trace_processor --run-metric ./top_five_processes.sql <perfetto trace>
    
    [090.720] processor_shell.cc:1070 Trace loaded: 16.21 MB (39.6 MB/s)
    [090.726] processor_shell.cc:1137 Error when computing metrics: Unknown metric top_five_processes
    
    Change-Id: Iffcd698dd1672b8739a652c1b5e8eab981ac01fc