Update git submodules
* Update platform/external/u-boot from branch 'master'
  to c3eb0fd9cb76f9f6f52c7e74d47d558a510b834e
  - Merge changes I7fc639b0,Ibc675456,I6dfb4a4d,Ibd1c4c20,I7a4e7adc, ...
    
    * changes:
      ANDROID: Add build.config for beagle_x15
      ANDROID: Support building with build.sh
      ANDROID: Fix nested C-style comment
      ANDROID: Fix 32-bit warning
      ANDROID: account for environment changes in raw_disk
      ANDROID: examples/standalone clang build fix
      ANDROID: Suppress a clang warning
      ANDROID: Fix SWIG generated compile warnings
    
  - ANDROID: Add build.config for beagle_x15
    
    Some features don't work with clang (EFI_LOADER), but we don't need
    them. Land this to unblock CI; we can revisit when there is a fix in
    the code or in clang.
    
    Bug: 162801433
    Change-Id: I7fc639b0f2bcee1015ae4f1dcb427489c3b611e1
    
  - ANDROID: Support building with build.sh
    
    Add a build config to build U-Boot for crosvm. Use it like this:
    
    $ BUILD_CONFIG=u-boot/build.config.crosvm.x86_64 build/build.sh
    
    Bug: 162801433
    Change-Id: Ibc67545659b32d1dcc5920ef08cfca2abe27c0eb
    
  - ANDROID: Fix nested C-style comment
    
    Comment blocks must not be nested in C. One of the blocks in
    chromebook_coral.dts is not correctly closed.
    
    Noticed by CC=clang.
    
    Bug: 162801433
    Change-Id: I6dfb4a4d9605c3c12bc7c2c1ffcb09ad0dc9c222
    
  - ANDROID: Fix 32-bit warning
    
    lbaint_t is really a uint64_t, so on 32-bit architectures an %lu won't
    cut it. Cast to unsigned long long and use an %llu instead.
    
    Warning noticed by CC=clang
    
    Bug: 162801433
    Change-Id: Ibd1c4c20362d857bfce53f85525ee6326e9e40be
    
  - ANDROID: account for environment changes in raw_disk
    
    f3998fdc4d0 and 0ac7d722ede changed environment.h
    Account for those changes in raw_disk.c
    
    Change-Id: I7a4e7adc8b12dfad395b8286646599e47258f9a5
    
  - ANDROID: examples/standalone clang build fix
    
    When building the standalone example with clang, the link step fails:
    
    examples/standalone/libstubs.o: In function `dummy':
    /home/adelva/android/kernel/u-boot/include/_exports.h:10: undefined reference to `jt'
    /home/adelva/android/kernel/u-boot/include/_exports.h:11: undefined reference to `jt'
    /home/adelva/android/kernel/u-boot/include/_exports.h:12: undefined reference to `jt'
    /home/adelva/android/kernel/u-boot/include/_exports.h:13: undefined reference to `jt'
    /home/adelva/android/kernel/u-boot/include/_exports.h:14: undefined reference to `jt'
    examples/standalone/libstubs.o:/home/adelva/android/kernel/u-boot/include/_exports.h:15: more undefined references to `jt' follow
    
    Indeed, the standalone libstubs.o does use the jt symbol, but it was
    marked 'static' in stubs.c. It's strange how gcc builds are working.
    
    Bug: 162801433
    Change-Id: I1b2d2cf7d18ccb5b032c92be4e22de816ff4ceb4
    
  - ANDROID: Suppress a clang warning
    
    Clang suggested this warning suppression, but it might still be better
    to fix the original code, which is a bit strange.
    
    Bug: 162801433
    Change-Id: Ifdb17c7879ff203ea9749898d210cc127a0190cb
    
  - ANDROID: Fix SWIG generated compile warnings
    
    Noticed by CC=clang.
    
    Bug: 162801433
    Change-Id: I63f96d619f447f7d11453b9fa0aa84b3dd0b0ac0
    

* Update platform/superproject from branch 'master'
  to c6ecf572d68855d5c2ba0a9011201edc0fa854b0
  - Update git submodules
    
    * Update external/u-boot from branch 'master'
      to c3eb0fd9cb76f9f6f52c7e74d47d558a510b834e
      - Merge changes I7fc639b0,Ibc675456,I6dfb4a4d,Ibd1c4c20,I7a4e7adc, ...
        
        * changes:
          ANDROID: Add build.config for beagle_x15
          ANDROID: Support building with build.sh
          ANDROID: Fix nested C-style comment
          ANDROID: Fix 32-bit warning
          ANDROID: account for environment changes in raw_disk
          ANDROID: examples/standalone clang build fix
          ANDROID: Suppress a clang warning
          ANDROID: Fix SWIG generated compile warnings
        
      - ANDROID: Add build.config for beagle_x15
        
        Some features don't work with clang (EFI_LOADER), but we don't need
        them. Land this to unblock CI; we can revisit when there is a fix in
        the code or in clang.
        
        Bug: 162801433
        Change-Id: I7fc639b0f2bcee1015ae4f1dcb427489c3b611e1
        
      - ANDROID: Support building with build.sh
        
        Add a build config to build U-Boot for crosvm. Use it like this:
        
        $ BUILD_CONFIG=u-boot/build.config.crosvm.x86_64 build/build.sh
        
        Bug: 162801433
        Change-Id: Ibc67545659b32d1dcc5920ef08cfca2abe27c0eb
        
      - ANDROID: Fix nested C-style comment
        
        Comment blocks must not be nested in C. One of the blocks in
        chromebook_coral.dts is not correctly closed.
        
        Noticed by CC=clang.
        
        Bug: 162801433
        Change-Id: I6dfb4a4d9605c3c12bc7c2c1ffcb09ad0dc9c222
        
      - ANDROID: Fix 32-bit warning
        
        lbaint_t is really a uint64_t, so on 32-bit architectures an %lu won't
        cut it. Cast to unsigned long long and use an %llu instead.
        
        Warning noticed by CC=clang
        
        Bug: 162801433
        Change-Id: Ibd1c4c20362d857bfce53f85525ee6326e9e40be
        
      - ANDROID: account for environment changes in raw_disk
        
        f3998fdc4d0 and 0ac7d722ede changed environment.h
        Account for those changes in raw_disk.c
        
        Change-Id: I7a4e7adc8b12dfad395b8286646599e47258f9a5
        
      - ANDROID: examples/standalone clang build fix
        
        When building the standalone example with clang, the link step fails:
        
        examples/standalone/libstubs.o: In function `dummy':
        /home/adelva/android/kernel/u-boot/include/_exports.h:10: undefined reference to `jt'
        /home/adelva/android/kernel/u-boot/include/_exports.h:11: undefined reference to `jt'
        /home/adelva/android/kernel/u-boot/include/_exports.h:12: undefined reference to `jt'
        /home/adelva/android/kernel/u-boot/include/_exports.h:13: undefined reference to `jt'
        /home/adelva/android/kernel/u-boot/include/_exports.h:14: undefined reference to `jt'
        examples/standalone/libstubs.o:/home/adelva/android/kernel/u-boot/include/_exports.h:15: more undefined references to `jt' follow
        
        Indeed, the standalone libstubs.o does use the jt symbol, but it was
        marked 'static' in stubs.c. It's strange how gcc builds are working.
        
        Bug: 162801433
        Change-Id: I1b2d2cf7d18ccb5b032c92be4e22de816ff4ceb4
        
      - ANDROID: Suppress a clang warning
        
        Clang suggested this warning suppression, but it might still be better
        to fix the original code, which is a bit strange.
        
        Bug: 162801433
        Change-Id: Ifdb17c7879ff203ea9749898d210cc127a0190cb
        
      - ANDROID: Fix SWIG generated compile warnings
        
        Noticed by CC=clang.
        
        Bug: 162801433
        Change-Id: I63f96d619f447f7d11453b9fa0aa84b3dd0b0ac0