Update git submodules
* Update trusty/lib from branch 'master'
  to 9c3bba824a5f183e645257a3a4513e970acf5ac1
  - Fix scudo_test.c for clang update
    
    After clang update, we get below error:
    
    trusty/user/base/lib/scudo/test/scudo_test.c:108:20: error:
    a function declaration without a prototype is deprecated in
    all versions of C [-Werror,-Wstrict-prototypes]
    static bool has_mte() {
                       ^
                        void
    
    Bug: 251888886
    Test: run trusty/vendor/google/aosp/scripts/build.py
    Change-Id: I099f9da8677328d77f74ded935e7038070373d4e
    

* Update trusty/lk/common from branch 'master'
  to d655cbc82a07b69605f18a98003cb0e4bd7d473e
  - Fix memtag.c for clang udpate
    
    After clang update, we get below errors:
    
    external/lk/arch/arm64/memtag.c:107:26: error: a function declaration without
    a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
    bool arch_tagging_enabled()
                             ^
                              void
    external/lk/arch/arm64/memtag.c:112:29: error: a function declaration without
    a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
    bool arm64_tagging_supported()
                                ^
                                 void
    
    Bug: 269521171
    Test: run trusty/vendor/google/aosp/scripts/build.py
    Change-Id: I59da50be6c97c750099c41704ac51c51f1f3045f
    

* Update trusty/lk/trusty from branch 'master'
  to 303feeeb07b5d882d96246bbe55074626f92a0c5
  - Update location of libc++.so for clang update
    
    Bug: 269521171
    Test: run trusty/vendor/google/aosp/scripts/build.py
    Change-Id: I460a8f34787c8a4e1167cd6df99a32a032fc1c66
    

* Update trusty/vendor/google/aosp from branch 'master'
  to 47a5d8b88c941679aaa7bd6afd8b0ebb540e3346
  - Update clang to r475365b
    
    Bug: 269521171
    Test: run trusty/vendor/google/aosp/scripts/build.py
    Change-Id: I63c6fec80afdff68f356dfd3b098f575dcec0565