Update git submodules
* Update platform/ndk from branch 'master'
  to c058c0a659101568b27db32cdb5c2c1353f61143
  - Merge changes I5cce7b53,Id6a05798,I126f4a25,Ie7180040,I332126f4, ...
    
    * changes:
      Replace distutils copy_tree, exclude tmp files
      Factor out bash code for host detection and python3 finding
      ndk-gdb.cmd: switch to python3 prebuilt
      ndk-build.cmd: setlocal and avoid dup \\ in NDK_ROOT
      ScriptShortcutModule: remove dup \\ in cmd script
      Fix ScriptShortcutModule shell script quoting
    
  - Replace distutils copy_tree, exclude tmp files
    
    distutils is deprecated and may be removed in an upcoming Python
    release.
    
    The function currently copies the LLVM toolchain's Python 3
    installation, which may contain temporary files in __pycache__ if its
    Python modules have been loaded. There is currently a race condition in
    checkbuild.py where loading a Python module briefly creates a temp file
    that breaks a concurrent copy_tree invocation:
    
    distutils.errors.DistutilsFileError: can't copy
      '/buildbot/src/android/master-ndk/out/linux/android-ndk-r24-canary/
      toolchains/llvm/prebuilt/linux-x86_64/python3/lib/python3.9/
      __pycache__/selectors.cpython-39.pyc.139731628119184':
      doesn't exist or not a regular file
    
    Fix the race by skipping __pycache__ using shutil.copytree's ignore
    parameter. Multiple source dirs are merged, so also pass
    dirs_exist_ok=True, which was added in Python 3.8. Change the shebang
    to python3.
    
    Bug: none
    Test: checkbuild.py, manual
    Change-Id: I5cce7b53359672eb6acd9d9bf48cc87f3dccfae6
    
  - Factor out bash code for host detection and python3 finding
    
    Share this code among ndk-gdb and ndk-build, and use this code to run
    make_standalone_toolchain.py with the prebuilt python3.
    
    Bug: none
    Test: checkbuild.py && run_tests.py
    Test: run ndk-gdb, ndk-build, make_standalone_toolchain.sh manually
    Change-Id: Id6a05798d502b2e29b01b82de927dd61c97b787e
    
  - ndk-gdb.cmd: switch to python3 prebuilt
    
    Bug: none
    Test: manual
    Change-Id: I126f4a256e98810feea945e07722438a4445284a
    
  - ndk-build.cmd: setlocal and avoid dup \\ in NDK_ROOT
    
    Bug: none
    Test: checkbuild.py && run_tests.py
    Change-Id: Ie71800402850febe7b8735f853aabbf2cf65c39f
    
  - ScriptShortcutModule: remove dup \\ in cmd script
    
    %~dp0 already ends in a backslash.
    
    Bug: none
    Test: manual
    Change-Id: I332126f4c85a5bb1fb3d6a554b98fa7bd46040e9
    
  - Fix ScriptShortcutModule shell script quoting
    
    These quotes are unneeded: DIR="$(...)"
    These quotes are needed: "$DIR" ...
    
    Bug: none
    Test: checkbuild.py && run_tests.py
    Change-Id: Ibbf9e84aa98aeaf3e183fc57aba071e1d279cbb1