Update git submodules
* Update platform/system/core from branch 'master'
  to dfdcc31d0330a4ee699d06f7d70868ded7331f12
  - Merge "libutils: Fix missing definition of shared_ptr and unique_ptr"
  - libutils: Fix missing definition of shared_ptr and unique_ptr
    
    This includes memory header for shared_ptr and unique_ptr templates.
    Fixes the following errors:
    
    RefBase.h:803:1: error: ‘shared_ptr’ does not name a type
    RefBase.h:810:1: error: ‘unique_ptr’ does not name a type
    
    Change-Id: I6a7a67333c9ef05250c5a3c6199d7fac288f946b