Update git submodules
* Update platform/frameworks/opt/telephony from branch 'master'
  to d0a964b30a0aa53349e861769c52912e4dec8bda
  - Merge "PhoneSwitcher: Fix ArrayIndexOutOfBoundsException in isPhoneActive()"
  - PhoneSwitcher: Fix ArrayIndexOutOfBoundsException in isPhoneActive()
    
    On HiKey960 (and likely also on other devboards w/o a modem),
    we are seeing a lot of the following crashes since commit
    f544a5ec7d0e ("Remove unecessary member variables of
    PhoneSwitcher."):
    
     FATAL EXCEPTION: main
     Process: com.android.phone, PID: 11848
     java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
            at com.android.internal.telephony.PhoneSwitcher.isPhoneActive(PhoneSwitcher.java:1113)
            at com.android.internal.telephony.PhoneSwitcher.shouldApplyNetworkRequest(PhoneSwitcher.java:1096)
            at com.android.internal.telephony.dataconnection.TelephonyNetworkFactory.onNeedNetworkFor(TelephonyNetworkFactory.java:290)
    ...
    
    While I suspect there is a more optimal fix, adding a test
    to ensure the phoneId isn't greater or equal to the
    mActiveModemCount seems to avoid the problem
    
    Fixes: f544a5ec7d0e ("Remove unecessary member variables of PhoneSwitcher.")
    Change-Id: I586f56e3571de173939f5a87ecfaf44339e8d591
    Signed-off-by: John Stultz <john.stultz@linaro.org>
    

* Update platform/superproject from branch 'master'
  to ecf394af2fbbbd7fe0008b3b23b959fbe83db8c4
  - Update git submodules
    
    * Update frameworks/opt/telephony from branch 'master'
      to d0a964b30a0aa53349e861769c52912e4dec8bda
      - Merge "PhoneSwitcher: Fix ArrayIndexOutOfBoundsException in isPhoneActive()"
      - PhoneSwitcher: Fix ArrayIndexOutOfBoundsException in isPhoneActive()
        
        On HiKey960 (and likely also on other devboards w/o a modem),
        we are seeing a lot of the following crashes since commit
        f544a5ec7d0e ("Remove unecessary member variables of
        PhoneSwitcher."):
        
         FATAL EXCEPTION: main
         Process: com.android.phone, PID: 11848
         java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
                at com.android.internal.telephony.PhoneSwitcher.isPhoneActive(PhoneSwitcher.java:1113)
                at com.android.internal.telephony.PhoneSwitcher.shouldApplyNetworkRequest(PhoneSwitcher.java:1096)
                at com.android.internal.telephony.dataconnection.TelephonyNetworkFactory.onNeedNetworkFor(TelephonyNetworkFactory.java:290)
        ...
        
        While I suspect there is a more optimal fix, adding a test
        to ensure the phoneId isn't greater or equal to the
        mActiveModemCount seems to avoid the problem
        
        Fixes: f544a5ec7d0e ("Remove unecessary member variables of PhoneSwitcher.")
        Change-Id: I586f56e3571de173939f5a87ecfaf44339e8d591
        Signed-off-by: John Stultz <john.stultz@linaro.org>