Update git submodules
* Update platform/art from branch 'master'
  to 50f89ba3237da01adfdbc65abc330d1c8d5af07e
  - Calling @IntraCoreApi from core-icu4j should not cause "Core platform API violation"
    
    Treat I18n APEX as the same domain as ART and Conscrypt APEX.
    
    Remove unused varaiable isJavaDebuggable because it causes the
    NoSuchMethodError for an unknown reason:
    java.lang.NoSuchMethodError: No virtual method isJavaDebuggable()Z in class Ldalvik/system/VMRuntime; or its super classes (declaration of 'dalvik.system.VMRuntime' appears in /apex/com.android.art/javalib/core-libart.jar)
    
    Bug: 138994281
    Test: art/test/run-test --chroot $ART_TEST_CHROOT 674-hiddenapi
    Change-Id: Icb7e98b5cd7143c06c05dd4377af0c96ba75bca7
    
  - Move ICU from ART APEX to i18n APEX
    
    It involves a change of boot class path to use core-icu4j
    from i18n APEX.
    
    Bug: 138994281
    Test: device boots
    Test: m build-art-target-tests
    Test: CtsJniTestCases
    Test: atest libnativeloader_test
    Test: ./art/test/testrunner/run_build_test_target.py -j80 art-test
    Test: art/build/apex/runtests.sh
    Change-Id: I30fc3735be760cba48856cd102852d2a6c796374
    

* Update platform/build.git from branch 'master'
  to 879d654515e43f7575115ab6bdbf08db5a1b0fdb
  - Merge "Move core-icu4j into i18n APEX"
  - Move core-icu4j into i18n APEX
    
    Bug: 138994281
    Test: core-icu4j observed in i18n APEX
    Change-Id: I10e6d49485305f84b31d62f858c3c032aba4d3df
    

* Update platform/external/chromium-libpac from branch 'master'
  to 4b2116471540356754f3b5fee471dbf9f598ba32
  - Merge "Move libpac into i18n APEX"
  - Move libpac into i18n APEX
    
    Bug: 138994281
    Test: libpac observed in com.android.i18n APEX
    Change-Id: I7d97a10ba3fcce7db746a93e6989f1d7642faa80
    

* Update platform/external/icu from branch 'master'
  to 70089941aaf6d7635b7dbef272855fe2805900d8
  - Move ICU from ART APEX into i18n APEX
    
    libpac and v8 depends on ICU4C C++ API. Since ICU is moved into
    i18n APEX, libpac.so needs to be moved too.
    
    Bug: 153648261
    Test: device boots
    Change-Id: I8d989cad7914a30076f0434bc0f3b535784af15f
    

* Update platform/external/v8 from branch 'master'
  to 07a39fb357abeb6e8b03d9c10df05e4851b5d812
  - Merge "Move v8 and libpac into i18n APEX"
  - Move v8 and libpac into i18n APEX
    
    Bug: 138994281
    Test: manually check that libpac shows up in com.android.i18n APEX
    Change-Id: Ia4c83bc15f000820003298b174cba5a230ad0301
    

* Update platform/external/vogar from branch 'master'
  to df698216217ecd00d26279fae771a6505d084d69
  - Merge "Move core-icu4j into I18n APEX"
  - Move core-icu4j into I18n APEX
    
    Bug: 138994281
    Test: art/tools/run-libcore-tests.sh --mode=device
    Test: art/tools/run-libcore-tests.sh --mode=host
    Change-Id: Ic7de63fe3b1279ccc42b160a4c6bda1dc28611bc
    

* Update platform/frameworks/base from branch 'master'
  to cda251009868c4152e999650e52584180a524b3c
  - Merge "Move ICU into i18n APEX"
  - Move ICU into i18n APEX
    
    Bug: 138994281
    Test: device boots
    Change-Id: I72216ca12c895c9bed05849d6b1a4163d24c0457
    

* Update platform/libcore from branch 'master'
  to 187f1ef62b983d2511e52909c34866c454516392
  - Merge "Move ICU from ART APEX into i18n APEX"
  - Move ICU from ART APEX into i18n APEX
    
    Bug: 153648261
    Test: CtsJniTestCases
    Change-Id: I90fff9c55f560495ecd898e7da5617de00349fa6
    

* Update platform/superproject from branch 'master'
  to dac7b36531b094c2a51608459d1b44d69c7175c5
  - Update git submodules
    
    * Update art from branch 'master'
      to 50f89ba3237da01adfdbc65abc330d1c8d5af07e
      - Calling @IntraCoreApi from core-icu4j should not cause "Core platform API violation"
        
        Treat I18n APEX as the same domain as ART and Conscrypt APEX.
        
        Remove unused varaiable isJavaDebuggable because it causes the
        NoSuchMethodError for an unknown reason:
        java.lang.NoSuchMethodError: No virtual method isJavaDebuggable()Z in class Ldalvik/system/VMRuntime; or its super classes (declaration of 'dalvik.system.VMRuntime' appears in /apex/com.android.art/javalib/core-libart.jar)
        
        Bug: 138994281
        Test: art/test/run-test --chroot $ART_TEST_CHROOT 674-hiddenapi
        Change-Id: Icb7e98b5cd7143c06c05dd4377af0c96ba75bca7
        
      - Move ICU from ART APEX to i18n APEX
        
        It involves a change of boot class path to use core-icu4j
        from i18n APEX.
        
        Bug: 138994281
        Test: device boots
        Test: m build-art-target-tests
        Test: CtsJniTestCases
        Test: atest libnativeloader_test
        Test: ./art/test/testrunner/run_build_test_target.py -j80 art-test
        Test: art/build/apex/runtests.sh
        Change-Id: I30fc3735be760cba48856cd102852d2a6c796374
        
    
    * Update build/make from branch 'master'
      to 879d654515e43f7575115ab6bdbf08db5a1b0fdb
      - Merge "Move core-icu4j into i18n APEX"
      - Move core-icu4j into i18n APEX
        
        Bug: 138994281
        Test: core-icu4j observed in i18n APEX
        Change-Id: I10e6d49485305f84b31d62f858c3c032aba4d3df
        
    
    * Update external/chromium-libpac from branch 'master'
      to 4b2116471540356754f3b5fee471dbf9f598ba32
      - Merge "Move libpac into i18n APEX"
      - Move libpac into i18n APEX
        
        Bug: 138994281
        Test: libpac observed in com.android.i18n APEX
        Change-Id: I7d97a10ba3fcce7db746a93e6989f1d7642faa80
        
    
    * Update external/icu from branch 'master'
      to 70089941aaf6d7635b7dbef272855fe2805900d8
      - Move ICU from ART APEX into i18n APEX
        
        libpac and v8 depends on ICU4C C++ API. Since ICU is moved into
        i18n APEX, libpac.so needs to be moved too.
        
        Bug: 153648261
        Test: device boots
        Change-Id: I8d989cad7914a30076f0434bc0f3b535784af15f
        
    
    * Update external/v8 from branch 'master'
      to 07a39fb357abeb6e8b03d9c10df05e4851b5d812
      - Merge "Move v8 and libpac into i18n APEX"
      - Move v8 and libpac into i18n APEX
        
        Bug: 138994281
        Test: manually check that libpac shows up in com.android.i18n APEX
        Change-Id: Ia4c83bc15f000820003298b174cba5a230ad0301
        
    
    * Update external/vogar from branch 'master'
      to df698216217ecd00d26279fae771a6505d084d69
      - Merge "Move core-icu4j into I18n APEX"
      - Move core-icu4j into I18n APEX
        
        Bug: 138994281
        Test: art/tools/run-libcore-tests.sh --mode=device
        Test: art/tools/run-libcore-tests.sh --mode=host
        Change-Id: Ic7de63fe3b1279ccc42b160a4c6bda1dc28611bc
        
    
    * Update frameworks/base from branch 'master'
      to cda251009868c4152e999650e52584180a524b3c
      - Merge "Move ICU into i18n APEX"
      - Move ICU into i18n APEX
        
        Bug: 138994281
        Test: device boots
        Change-Id: I72216ca12c895c9bed05849d6b1a4163d24c0457
        
    
    * Update libcore from branch 'master'
      to 187f1ef62b983d2511e52909c34866c454516392
      - Merge "Move ICU from ART APEX into i18n APEX"
      - Move ICU from ART APEX into i18n APEX
        
        Bug: 153648261
        Test: CtsJniTestCases
        Change-Id: I90fff9c55f560495ecd898e7da5617de00349fa6
        
    
    * Update system/linkerconfig from branch 'master'
      to 84d3247b545945342fab2b9e35e7b9be60f19c61
      - Make com_android_i18n namespace visible
        
        libnativeloader calls android_get_exported_namespace to link
        this namepsace to classloader namespace.
        
        Bug: 138994281
        Test: CtsJniTestCases
        Change-Id: I65b97bdba462a11d7389b84d873c4daa9c08b45d
        
    
    * Update system/sepolicy from branch 'master'
      to c18f8052e92eb97ca2b2f4df9a1bd3cdc94afde5
      - Merge "Add shared library into i18n APEX and add the required sepolicy"
      - Add shared library into i18n APEX and add the required sepolicy
        
        Bug: 138994281
        Test: device boots
        Change-Id: Ief9dace8557c1d0e5a32222b2c7d1effc50f2847
        

* Update platform/system/linkerconfig from branch 'master'
  to 84d3247b545945342fab2b9e35e7b9be60f19c61
  - Make com_android_i18n namespace visible
    
    libnativeloader calls android_get_exported_namespace to link
    this namepsace to classloader namespace.
    
    Bug: 138994281
    Test: CtsJniTestCases
    Change-Id: I65b97bdba462a11d7389b84d873c4daa9c08b45d
    

* Update platform/system/sepolicy from branch 'master'
  to c18f8052e92eb97ca2b2f4df9a1bd3cdc94afde5
  - Merge "Add shared library into i18n APEX and add the required sepolicy"
  - Add shared library into i18n APEX and add the required sepolicy
    
    Bug: 138994281
    Test: device boots
    Change-Id: Ief9dace8557c1d0e5a32222b2c7d1effc50f2847