Update git submodules
* Update platform/build.git from branch 'master'
  to 790214a4c9eafdd0054c116af3f6865138e336cf
  - Merge "Fix the signing error on no-system-image targets"
  - Fix the signing error on no-system-image targets
    
    Currently when running sign_target_files_apks on a no-system-image
    target, it will raise the following error:
    
      ValueError: max() arg is an empty sequence
    
    This is because there is no APK files in the target_files.zip.
    Fixing this by setting maxsize to zero in this case.
    
    Bug: 213028932
    Test: lunch gki_arm64-userdebug; make dist
    Test: sign_target_files_apks \
            --gki_signing_key=external/avb/test/data/testkey_rsa4096.pem \
            --gki_signing_algorithm=SHA256_RSA4096 \
            --gki_signing_extra_args="--prop gki:prop1 --prop gki:prop2" \
            ./out/dist/*-target_files-eng.*.zip signed.zip
    Change-Id: I40daecbc2ff3f89d3e635d1a4a1c1dea31ba9a27