Update git submodules
* Update platform/external/selinux from branch 'master'
  to 18205ff9d71717029af075d82e0e25906901af97
  - Merge remote-tracking branch 'aosp/upstream-master' into mymerge
    
    Followed the following steps:
      # In repo client
      cd external/selinux
      repo sync .
      repo start mymerge .
      git merge aosp/upstream-master --no-ff # resolve any conflicts
      lunch && make -j
      repo upload .
    
    Test: compiles and boots
    Change-Id: I45fd32fb9bfe2291ef32afcc86f26eb2b24e03e8
    
  - libsepol/cil: remove unnecessary hash tables
    
    The filename_- and range_trans_table ancillary hash tables in
    cil_binary.c just duplicate the final policydb content and can be simply
    removed.
    
    Signed-off-by: Ondrej Mosnacek <omosnace@redhat.com>
    
  - label_file.c: Fix MAC build
    
    On Android, the label_file.c file is compiled for all platforms,
    including OSX. OSX has a slightly different prototype for the
    getxattr function.
    
    ssize_t getxattr(const char *path, const char *name, void *value, size_t size, u_int32_t position, int options);
    
    which causes a compile error when compiling libselinux on OSX.
    
      ```
      external/selinux/libselinux/src/label_file.c:1038:37: error: too few arguments to function call, expected 6, have 4
                                           read_digest, SHA1_HASH_SIZE);
                                                                    ^
      /Applications/Xcode9.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/sys/xattr.h:61:1: note: 'getxattr' declared here
      ssize_t getxattr(const char *path, const char *name, void *value, size_t size, u_int32_t position, int options);
      ^
      1 error generated.
      ```
    
    On OSX builds, add the additional arguments so that the code compiles.
    
    As both SELinux labels and the restorecon partial digest are stored in
    extended attributes, it's theoretically possible that someone
    could assign SELinux labels and hash digests on OSX filesystems.
    Doing so would be extremely weird and completely untested, but
    theoretically possible.
    
    Signed-off-by: Nick Kralevich <nnk@google.com>
    
  - Travis-CI: test that DEBUG build works
    
    Signed-off-by: Ondrej Mosnacek <omosnace@redhat.com>
    
  - libsemanage: preserve parent Makefile's flags in debug mode
    
    Do not override CFLAGS and LDFLAGS in libsemange Makefile under DEBUG=1,
    to make it possible to build the whole tree using the root Makefile with
    DEBUG=1.
    
    Signed-off-by: Ondrej Mosnacek <omosnace@redhat.com>
    
  - libsepol/cil: Rewrite verification of map classes and classpermissionsets
    
    The classperms associated with each map class permission and with each
    classpermissionset are verified in __cil_verify_classperms() which had
    multiple problems with how it did the verification.
    
    1) Verification was short-circuited when the first normal class is found.
      The second classpermissionset statement below would not have been
      verified.
        (classpermission cp1)
        (classpermissionset cp1 (CLASS (PERM)))
        (classpermissionset cp1 cp2)
    
    2) The classperms of a map class permission and classpermissionset were
    not checked for being NULL before the function recursively called itself.
    This would result in a segfault if the missing map or set was referred to
    before the classmap or classpermission occured. This error was reported by
    Dominick Grift (dominick.grift@defensec.nl).
      These rules would cause a segfault.
        (classmap cm1 (mp1))
        (classmapping cm1 mp1 (cm2 (mp2)))
        (classmap cm2 (mp2))
      But an error would be produced for these rules.
        (classmap cm1 (mp1))
        (classmap cm2 (mp2))
        (classmapping cm2 mp2 (cm1 (mp1)))
    
    3) The loop detection logic was incomplete and could only detect a loop
    with a certain statement ordering.
      These rules would cause a stack overflow.
        (classmap cm1 (mp1))
        (classmapping cm1 mp1 (cm2 (mp2)))
        (classmap cm2 (mp2))
        (classmapping cm2 mp2 (cm3 (mp3)))
        (classmap cm3 (mp3))
        (classmapping cm3 mp3 (cm2 (mp2)))
    
    Rewrote __cil_verify_classperms() to fix these errors.
    
    Signed-off-by: James Carter <jwcart2@tycho.nsa.gov>
    
  - libsepol: add support for new polcap genfs_seclabel_symlinks
    
    Add support for new SELinux policy capability genfs_seclabel_symlinks.
    With this capability enabled symlinks on kernel filesystems will receive
    contexts based on genfscon statements, like directories and files,
    and not be restricted to the respective filesystem root sid.
    
    Signed-off-by: Christian Göttsche <cgzones@googlemail.com>
    
  - libsepol,checkpolicy: support omitting unused initial sid contexts
    
    Remove restrictions in libsepol and checkpolicy that required all
    declared initial SIDs to be assigned a context.  With this patch,
    it is possible to build and load a policy that drops the sid <sidname>
    <context> declarations for the unused initial SIDs.  It is still
    required to retain the sid <sidname> declarations (in the flask
    definitions) in order to preserve the initial SID ordering/values.
    The unused initial SIDs can be renamed, e.g. to add an unused_
    prefix or similar, if desired, since the names used in the policy
    are not stored in the kernel binary policy.
    
    In CIL policies, the (sid ...) and (sidorder (...)) statements
    must be left intact for compatibility but the (sidcontext ...)
    statements for the unused initial SIDs can be omitted after this change.
    
    With current kernels, if one removes an unused initial SID context
    from policy, builds policy with this change applied and loads the
    policy into the kernel, cat /sys/fs/selinux/initial_contexts/<sidname>
    will show the unlabeled context.  With the kernel patch to remove unused
    initial SIDs, the /sys/fs/selinux/initial_contexts/<sidname>
    file will not be created for unused initial SIDs in the first place.
    
    NB If an unused initial SID was assigned a context different from
    the unlabeled context in existing policy, then it is not safe to
    remove that initial SID context from policy and reload policy on
    the running kernel that was booted with the original policy.  This
    is because that kernel may have assigned that SID to various kernel
    objects already and those objects will then be treated as having
    the unlabeled context after the removal.  In refpolicy, examples
    of such initial SIDs are the "fs" SID and the "sysctl" SID.  Even
    though these initial SIDs are not directly used (in code) by the current
    kernel, their contexts are being applied to filesystems and sysctl files by
    policy and therefore the SIDs are being assigned to objects.
    
    NB The "sysctl" SID was in use by the kernel up until
    commit 8e6c96935fcc1ed3dbebc96fddfef3f2f2395afc ("security/selinux:
    fix /proc/sys/ labeling) circa v2.6.39.  Removing its context from
    policy will cause sysctl(2) or /proc/sys accesses to end up
    performing permission checks against the unlabeled context and
    likely encounter denials for kernels < 2.6.39.
    
    Signed-off-by: Stephen Smalley <sds@tycho.nsa.gov>
    

* Update platform/superproject from branch 'master'
  to 3a9788c9c36f09f8c4441a5eabaebb7a46530a32
  - Update git submodules
    
    * Update external/selinux from branch 'master'
      to 18205ff9d71717029af075d82e0e25906901af97
      - Merge remote-tracking branch 'aosp/upstream-master' into mymerge
        
        Followed the following steps:
          # In repo client
          cd external/selinux
          repo sync .
          repo start mymerge .
          git merge aosp/upstream-master --no-ff # resolve any conflicts
          lunch && make -j
          repo upload .
        
        Test: compiles and boots
        Change-Id: I45fd32fb9bfe2291ef32afcc86f26eb2b24e03e8
        
      - libsepol/cil: remove unnecessary hash tables
        
        The filename_- and range_trans_table ancillary hash tables in
        cil_binary.c just duplicate the final policydb content and can be simply
        removed.
        
        Signed-off-by: Ondrej Mosnacek <omosnace@redhat.com>
        
      - label_file.c: Fix MAC build
        
        On Android, the label_file.c file is compiled for all platforms,
        including OSX. OSX has a slightly different prototype for the
        getxattr function.
        
        ssize_t getxattr(const char *path, const char *name, void *value, size_t size, u_int32_t position, int options);
        
        which causes a compile error when compiling libselinux on OSX.
        
          ```
          external/selinux/libselinux/src/label_file.c:1038:37: error: too few arguments to function call, expected 6, have 4
                                               read_digest, SHA1_HASH_SIZE);
                                                                        ^
          /Applications/Xcode9.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/sys/xattr.h:61:1: note: 'getxattr' declared here
          ssize_t getxattr(const char *path, const char *name, void *value, size_t size, u_int32_t position, int options);
          ^
          1 error generated.
          ```
        
        On OSX builds, add the additional arguments so that the code compiles.
        
        As both SELinux labels and the restorecon partial digest are stored in
        extended attributes, it's theoretically possible that someone
        could assign SELinux labels and hash digests on OSX filesystems.
        Doing so would be extremely weird and completely untested, but
        theoretically possible.
        
        Signed-off-by: Nick Kralevich <nnk@google.com>
        
      - Travis-CI: test that DEBUG build works
        
        Signed-off-by: Ondrej Mosnacek <omosnace@redhat.com>
        
      - libsemanage: preserve parent Makefile's flags in debug mode
        
        Do not override CFLAGS and LDFLAGS in libsemange Makefile under DEBUG=1,
        to make it possible to build the whole tree using the root Makefile with
        DEBUG=1.
        
        Signed-off-by: Ondrej Mosnacek <omosnace@redhat.com>
        
      - libsepol/cil: Rewrite verification of map classes and classpermissionsets
        
        The classperms associated with each map class permission and with each
        classpermissionset are verified in __cil_verify_classperms() which had
        multiple problems with how it did the verification.
        
        1) Verification was short-circuited when the first normal class is found.
          The second classpermissionset statement below would not have been
          verified.
            (classpermission cp1)
            (classpermissionset cp1 (CLASS (PERM)))
            (classpermissionset cp1 cp2)
        
        2) The classperms of a map class permission and classpermissionset were
        not checked for being NULL before the function recursively called itself.
        This would result in a segfault if the missing map or set was referred to
        before the classmap or classpermission occured. This error was reported by
        Dominick Grift (dominick.grift@defensec.nl).
          These rules would cause a segfault.
            (classmap cm1 (mp1))
            (classmapping cm1 mp1 (cm2 (mp2)))
            (classmap cm2 (mp2))
          But an error would be produced for these rules.
            (classmap cm1 (mp1))
            (classmap cm2 (mp2))
            (classmapping cm2 mp2 (cm1 (mp1)))
        
        3) The loop detection logic was incomplete and could only detect a loop
        with a certain statement ordering.
          These rules would cause a stack overflow.
            (classmap cm1 (mp1))
            (classmapping cm1 mp1 (cm2 (mp2)))
            (classmap cm2 (mp2))
            (classmapping cm2 mp2 (cm3 (mp3)))
            (classmap cm3 (mp3))
            (classmapping cm3 mp3 (cm2 (mp2)))
        
        Rewrote __cil_verify_classperms() to fix these errors.
        
        Signed-off-by: James Carter <jwcart2@tycho.nsa.gov>
        
      - libsepol: add support for new polcap genfs_seclabel_symlinks
        
        Add support for new SELinux policy capability genfs_seclabel_symlinks.
        With this capability enabled symlinks on kernel filesystems will receive
        contexts based on genfscon statements, like directories and files,
        and not be restricted to the respective filesystem root sid.
        
        Signed-off-by: Christian Göttsche <cgzones@googlemail.com>
        
      - libsepol,checkpolicy: support omitting unused initial sid contexts
        
        Remove restrictions in libsepol and checkpolicy that required all
        declared initial SIDs to be assigned a context.  With this patch,
        it is possible to build and load a policy that drops the sid <sidname>
        <context> declarations for the unused initial SIDs.  It is still
        required to retain the sid <sidname> declarations (in the flask
        definitions) in order to preserve the initial SID ordering/values.
        The unused initial SIDs can be renamed, e.g. to add an unused_
        prefix or similar, if desired, since the names used in the policy
        are not stored in the kernel binary policy.
        
        In CIL policies, the (sid ...) and (sidorder (...)) statements
        must be left intact for compatibility but the (sidcontext ...)
        statements for the unused initial SIDs can be omitted after this change.
        
        With current kernels, if one removes an unused initial SID context
        from policy, builds policy with this change applied and loads the
        policy into the kernel, cat /sys/fs/selinux/initial_contexts/<sidname>
        will show the unlabeled context.  With the kernel patch to remove unused
        initial SIDs, the /sys/fs/selinux/initial_contexts/<sidname>
        file will not be created for unused initial SIDs in the first place.
        
        NB If an unused initial SID was assigned a context different from
        the unlabeled context in existing policy, then it is not safe to
        remove that initial SID context from policy and reload policy on
        the running kernel that was booted with the original policy.  This
        is because that kernel may have assigned that SID to various kernel
        objects already and those objects will then be treated as having
        the unlabeled context after the removal.  In refpolicy, examples
        of such initial SIDs are the "fs" SID and the "sysctl" SID.  Even
        though these initial SIDs are not directly used (in code) by the current
        kernel, their contexts are being applied to filesystems and sysctl files by
        policy and therefore the SIDs are being assigned to objects.
        
        NB The "sysctl" SID was in use by the kernel up until
        commit 8e6c96935fcc1ed3dbebc96fddfef3f2f2395afc ("security/selinux:
        fix /proc/sys/ labeling) circa v2.6.39.  Removing its context from
        policy will cause sysctl(2) or /proc/sys accesses to end up
        performing permission checks against the unlabeled context and
        likely encounter denials for kernels < 2.6.39.
        
        Signed-off-by: Stephen Smalley <sds@tycho.nsa.gov>