Update git submodules
* Update platform/build from branch 'master'
  to c21c709f0b2929bc3e52c890d975572ac9a9e84e
  - Merge "Revert "build: Split out mkfs in BuildImageMkfs""
  - Revert "build: Split out mkfs in BuildImageMkfs"
    
    This reverts commit 2b72b7f01e446c2f270f24b840f484bd7c339165.
    
    out/target/product/generic_x86/installed-files.txt \${DIST_DIR}/installed-files-rescued.txt; exit 1 ) )" 
    2018-11-08 19:12:28 - build_image.py - ERROR : Failed to build out/target/product/generic_x86/obj/PACKAGING/systemimage_intermediates/system.img from out/target/product/generic_x86/system 
    Traceback (most recent call last): 
    File "build/make/tools/releasetools/build_image.py", line 767, in <module> 
    main(sys.argv[1:]) 
    File "build/make/tools/releasetools/build_image.py", line 755, in main 
    BuildImage(in_dir, image_properties, out_file, target_out) 
    File "build/make/tools/releasetools/build_image.py", line 449, in BuildImage 
    CheckHeadroom(mkfs_output, prop_dict) 
    NameError: global name 'mkfs_output' is not defined 
    
    
    Bug: 111302946
    Reason for revert: Build problem
    
    Change-Id: I786f232e07af653a7207509055df5a07a6d8bb9e
    

* Update platform/superproject from branch 'master'
  to 8c0efd14e4f6c5862b0e22cedcf64ea116ac32d3
  - Update git submodules
    
    * Update build/make from branch 'master'
      to c21c709f0b2929bc3e52c890d975572ac9a9e84e
      - Merge "Revert "build: Split out mkfs in BuildImageMkfs""
      - Revert "build: Split out mkfs in BuildImageMkfs"
        
        This reverts commit 2b72b7f01e446c2f270f24b840f484bd7c339165.
        
        out/target/product/generic_x86/installed-files.txt \${DIST_DIR}/installed-files-rescued.txt; exit 1 ) )" 
        2018-11-08 19:12:28 - build_image.py - ERROR : Failed to build out/target/product/generic_x86/obj/PACKAGING/systemimage_intermediates/system.img from out/target/product/generic_x86/system 
        Traceback (most recent call last): 
        File "build/make/tools/releasetools/build_image.py", line 767, in <module> 
        main(sys.argv[1:]) 
        File "build/make/tools/releasetools/build_image.py", line 755, in main 
        BuildImage(in_dir, image_properties, out_file, target_out) 
        File "build/make/tools/releasetools/build_image.py", line 449, in BuildImage 
        CheckHeadroom(mkfs_output, prop_dict) 
        NameError: global name 'mkfs_output' is not defined 
        
        
        Bug: 111302946
        Reason for revert: Build problem
        
        Change-Id: I786f232e07af653a7207509055df5a07a6d8bb9e