Update git submodules
* Update platform/external/cpu_features from branch 'master'
  to 47bd1869cd965df9bf5540a54bc6ca8ee29d6f4a
  - Merge v0.7.0 into master.
    
    Adjust Android build system rules for recent changes in upstream
    cpu_features.
    
    Test: Run `atest -a --test-mapping external/cpu_features:all` (on
          x86-64 and Arm64 devices)
    Change-Id: Idd78a3a4f29247b2c83117bde98cca45f94908f2
    
  - Add cpu_features to hwasan-postsubmit am: 7783526676 am: 39430949fb
    
    Original change: https://android-review.googlesource.com/c/platform/external/cpu_features/+/2034603
    
    Change-Id: I65892f813e8be43e8b4c0d50cdc151febca43e4e
    
  - Add cpu_features to hwasan-postsubmit am: 7783526676
    
    Original change: https://android-review.googlesource.com/c/platform/external/cpu_features/+/2034603
    
    Change-Id: Ic9bace9a16d2c06960abe62a9aca38a19fb354d0
    
  - Release v0.7.0
    
  - Fix release script
    
  - replace sse3 detection with pni when reading /proc/cpuinfo (#225)
    
    
  - Fix include paths in BUILD (#226)
    
    Include paths should be specified through includes
    rather than copts, so that they are handled correctly when
    cpu_features is included in another project as an external repository.
  - Add support for ZHAOXIN CPU (#218)
    
    
  - Fix windows amd64 ci
    
    
  - [NFC] Add bazel support to cpu_features (#222)
    
    
  - Fix a getauxval comment and expand the Krait idiv workaround (#206)
    
    * Fix getauxval comment (API 18 not 20)
    
    getauxval is available in Android starting with API 18, not 20.
    
    The comment about __ANDROID_API__ appears to have been copied from the
    NDK's cpufeatures, which always uses dlopen/dlsym and doesn't assume it
    can directly call getauxval, even if __ANDROID_API__ is new enough.
    With this project, though, when __ANDROID_API__ is 18 or up, the
    CMakeLists.txt file would detect that getauxval is available and define
    HAVE_STRONG_GETAUXVAL.
    
    * Broaden Qualcomm Krait idiv workaround
    
    Some Qualcomm Krait CPUs have IDIV support but the kernel doesn't
    report it. Previously, this code looked for two CPUs:
     - 0x510006F2 (0x51/'Q', variant 0, part 0x06f, rev 2)
     - 0x510006F3 (0x51/'Q', variant 0, part 0x06f, rev 3)
    
    This check misses my 2013 Nexus 7 device, which has this CPU ID:
     - 0x511006f0 (0x51/'Q', variant 1, part 0x06f, rev 0)
    
    My Nexus 7 device doesn't report idiv through AT_HWCAP or through
    /proc/cpuinfo (AT_HWCAP is 0x1b0d7).
    
    Expand the check to anything with:
     - implementer 0x51
     - architecture 7
     - part 0x4d or 0x6f
    
    Part 0x4d appears to be a dual-core Krait (e.g. see
    https://crbug.com/341598#c43).
    
    This new matching behavior is a subset of what the upstream kernel
    does (patch[1] contributed by CodeAurora), and also closely matches the
    behavior of pytorch/cpuinfo.
    
    [1] https://github.com/torvalds/linux/commit/120ecfafabec382c4feb79ff159ef42a39b6d33b
  - Fix list_cpu_features.exe does not detect SSE42 on Xeon X5650 (Windows) (#220)
    
    
  - Rename 'master' branch into 'main' (#219)
    
    
  - [x86] Embed brand_string and mark FillX86BrandString as deprecated (#214)
    
    
  - [NFC] Avoid polluting global scope
    
  - [NFC][x86] Read all cpuid leaves at once (#213)
    
    This patch reads the most important cpuid leaves and stores the data in
    a struct. A followup patch will inline micro architecture detection and
    brand string inside X86Info so we don't have to call `ReadLeaves` multiple
    times. This wil allow further simplification of `HasSecondFMA` and help
    fix https://github.com/google/cpu_features/issues/200.
  - Fix arm64 detection precedence in CMakeLists.txt (#209)
    
    Fixes #179
  - Fix #205
    Since buffers are a few tens of bytes there is no need for optimized memfunctions. For compile time sizes, the compiler will generate optimal code already.
    
  - fix googletest download
    
    
  - Fix missing header
    
  - make copy and equals inline headers
    
  - Silence unsused parameters
    
  - Make getter/setter static so they don't leak
    
  - Fix CpuFeatures_memchr to actually use the provided size argument
    
  - Update uarch detection for Intel processors (#184)
    
    
  - Update README.md
  - ci: Update Linux jobs to run inside a docker container.
    
  - ci: Add docker based test framework
    
    * Add documentation
    * Add .dockerignore: minimize docker context size to improve speed
    * Add Makefile: to easily run various docker stages
    * Add a CMake sample project to check CMake install rules
    
  - scripts: Fixup for run_integration.sh
    
  - NFC remove reference to libc memory functions
    
  - New code layout - breaking change in cpu_features_macros.h (#194)
    
    This commit helps with platform code separation (fixes #3). It should also help with the build as we can simply include all `impl_*.c` files regardless of OS / arch.
    
    Note: this patch contains breaking changes in `include/cpu_features_macros.h`
     - `CPU_FEATURES_OS_LINUX_OR_ANDROID` does not exist anymore
     - `CPU_FEATURES_OS_FREEBSD`, `CPU_FEATURES_OS_ANDROID` and `CPU_FEATURES_OS_LINUX` are now mutually exclusive (i.e. `CPU_FEATURES_OS_ANDROID` does not imply `CPU_FEATURES_OS_LINUX`)
     - `CPU_FEATURES_OS_DARWIN` has been renamed into `CPU_FEATURES_OS_MACOS` to be able to target non-Mac Apple products (IOS, TV, WATCH). They are now targetable with `CPU_FEATURES_OS_IPHONE`. This matches Apple naming convention described in [this stackoverflow](https://stackoverflow.com/a/49560690).
  - Update README.md (#193)
    
    Change `Quickstart` section to match new default value for testing.
  - Update README.md
    
  - ci: Fix windows workflow filename
    
  - ci: Drop use of Travis-CI and Appveyor
    
  - cmake: Fix enabling ndk_compat
    
  - Override CacheInfo only if new data is available via Deterministic Cache Parameters Leaf
    #190
    
  - ci: Migrate FreeBSD to macos-10.15 virtual env (#191)
    
    note: In preparation to https://github.com/actions/virtual-environments/issues/4060
    which will drop Vagrant/VirtualBox
    
    ref: https://github.com/actions/virtual-environments/pull/4010
  - Fix memory overflow
    Duplicate of #190
    
  - Set CTest output on failure (#189)
    
    
  - ci(github): Add workflows
    
  - ci(travis): adapt it to the new run_integration.sh
    
  - tools: Rework cross compilation scripts
    
    - Use stderr for issues
    - Add usage to run_integration.sh (-h or --help)
    - deduce toolchain and qemu config from TARGET
    - Bump QEMU from 2.11.1 to 5.2.0
      - fix qemu build on Archlinux
    - Bump Linaro:
        toolchain 7.2-2017.11 -> 7.5-2019.12
        sysroot 2.25-2017.11 -> 2.25-2019.12
    - Bump codescape from 2017.10-08 to 2020.06-01
      - migrate from mips-r2-hard to mips-r6-hard
    
  - ci(appveyor): Add VS 2019 job
    
  - .gitignore: Add build_cross/
    
    note: Used by scripts/*.sh
    
  - cmake: Use of CMAKE_POSITION_INDEPENDENT_CODE instead of BUILD_PIC (Fix #143)
    
  - Fixes #185 (#187)
    
    Missing `string_view` header and invalid `_Static_assert` statement
  - [NFC] Change implementation of FillX86BrandString (#181)
    
    
  - Fixes wrong cache detection of old processors (#183)
    
    
  - [NFC] encapsulate fake cpu instance in x86 test
    
  - Showcase community bindings (#180)
    
    
  - Add cache info for new AMD CPUs (0x8000001D) (#171)
    
    
  - add BUNDLE DESTINATION (#177)
    
    required for installation of executable target if cross-build to iOS/tvOS/watchOS
    see https://cmake.org/cmake/help/latest/policy/CMP0006.html
  - Add separator to CpuFeatures_StringView_HasWord (#174)
    
    
  - Update README.md (#176)
    
    
  - Update gitignore (#173)
    
    
  - Fix broken table in README.md
  - Add support for FreeBSD on x86 (#163)
    
    
  - cmake: Use CTest default (Fix #169) (#170)
    
    note: this is the default behaviour when using include(CTest)
  - ci: Add FreeBSD GitHub workflows (#167)
    
    First step to fixing #158 : add a CI for FreeBSD.
  - CPU features for AMD (#165)
    
    
  - Avoid leaking internal headers for ppc (#164)
    
    
  - fix: Return default value from ‘GetCacheTypeString’ (#162)
    
    The build fails with following message when -Werror
    and -Werror=return-type are enabled.
    
    In function ‘GetCacheTypeString’:
    	error: control reaches end of non-void function [-Werror=return-type]
    
    Simple fix is to return explicitly communicate to
    the compiler that certain block is not reachable.
  - [NFC] refactor the code so it's easier to understand the execution flow (#161)
    
    
  - Remove leftover WORKSPACE file
    
  - Fix #140 Atom processor detected as X86_UNKNOWN (#160)
    
    
  - Detect AVX512 on Darwin use GetDarwinSysCtlByName("hw.optional.avx512f") (#153)
    
    
  - Detect Intel's Multi-Precision Add-Carry Instruction Extensions (#157)
    
    
  - Fix C++ namespace in README
    
    The correct namespace is `cpu_features` as defined in https://github.com/google/cpu_features/blob/3cc8f310d950b44cc6d2ead8057cf43330a726fd/include/cpu_features_macros.h#L108.
  - github/workflows: fix install clang-format to use clang-extra-tools pkg
    
  - Detect Zen 3 (K19) cpus (#152)
    
    Co-authored-by: natanbc <natanbc@users.noreply.github.com>
  - Update AArch64 features to Linux 5.10 (#149)
    
    Added feature: MTE.
  - Provides a release script (#142)
    
    Fixes #141