Update git submodules
* Update platform/bionic from branch 'master'
  to 0771b752f1b955e7ded6ccbbf825b0ae93439eb5
  - Merge "Workaround string-plus-int warning"
  - Workaround string-plus-int warning
    
    The upcoming compiler warns against adding string and int:
    In file included from bionic/libc/bionic/strsignal.cpp:41:
      bionic/libc/private/bionic_sigdefs.h:58:1: error: adding 'int' to a string does not append to the string [-Werror,-Wstring-plus-int]
      __BIONIC_SIGDEF(SIGWINCH,  "Window size changed")
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      bionic/libc/bionic/strsignal.cpp:40:83: note: expanded from macro '__BIONIC_SIGDEF'
      #define __BIONIC_SIGDEF(signal_number, unused) [ signal_number ] = #signal_number + 3,
                                                                         ~~~~~~~~~~~~~~~^~~
    
    Use array indexing index to avoid this warning.
    
    Test: m checkbuild
    Change-Id: Ib5e20edbf5bac76352df0484dd233d0621beb4e9
    

* Update platform/superproject from branch 'master'
  to 020c9958c41c496e22ffb966c266dd6fc1f94943
  - Update git submodules
    
    * Update bionic from branch 'master'
      to 0771b752f1b955e7ded6ccbbf825b0ae93439eb5
      - Merge "Workaround string-plus-int warning"
      - Workaround string-plus-int warning
        
        The upcoming compiler warns against adding string and int:
        In file included from bionic/libc/bionic/strsignal.cpp:41:
          bionic/libc/private/bionic_sigdefs.h:58:1: error: adding 'int' to a string does not append to the string [-Werror,-Wstring-plus-int]
          __BIONIC_SIGDEF(SIGWINCH,  "Window size changed")
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          bionic/libc/bionic/strsignal.cpp:40:83: note: expanded from macro '__BIONIC_SIGDEF'
          #define __BIONIC_SIGDEF(signal_number, unused) [ signal_number ] = #signal_number + 3,
                                                                             ~~~~~~~~~~~~~~~^~~
        
        Use array indexing index to avoid this warning.
        
        Test: m checkbuild
        Change-Id: Ib5e20edbf5bac76352df0484dd233d0621beb4e9