Update git submodules
* Update platform/external/selinux from branch 'master'
  to df5204a030cc8c2edda4c789b508abdb41adf80a
  - Merge remote-tracking branch 'aosp/upstream-master' into mymerge
    
    Followed the following steps:
      # In repo client
      cd external/selinux
      repo sync .
      repo start mymerge .
      git merge aosp/upstream-master --no-ff # resolve any conflicts
      repo upload .
    
    Test: device compiles and boots
    Change-Id: If92a0b5e99e69ac0434197fa848b736b9cf0bf77
    
  - libsepol/cil: silence static analyser's use-after-free warning
    
    clang's static analyze reports a use-after-free in
    __cil_expr_to_string(), when __cil_expr_to_string_helper() does not
    modify its third parameter (variable s1 here) in this loop:
    
        for (curr = curr->next; curr; curr = curr->next) {
            __cil_expr_to_string_helper(curr, flavor, &s1);
            cil_asprintf(&c2, "%s %s", c1, s1);
            free(c1);
            free(s1);
            c1 = c2;
        }
    
    Silence this warning by making sure s1 is always NULL at the beginning
    of every iteration of the loop.
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - libselinux: Fix RESOURCE_LEAK defects reported by coverity scan
    
    Fixes:
    
    libselinux/src/checkAccess.c:93: leaked_storage: Variable "user_context" going out of scope leaks the storage it points to.
    libselinux/src/label_db.c:286: leaked_storage: Variable "filp" going out of scope leaks the storage it points to.
    libselinux/src/label_db.c:291: leaked_storage: Variable "filp" going out of scope leaks the storage it points to.
    libselinux/src/label_file.c:405: leaked_storage: Variable "str_buf" going out of scope leaks the storage it points to.
    libselinux/src/load_policy.c:266: leaked_storage: Variable "names" going out of scope leaks the storage it points to.
    libselinux/src/selinux_config.c:183: leaked_storage: Variable "end" going out of scope leaks the storage it points to.
    libselinux/src/selinux_config.c:184: overwrite_var: Overwriting "end" in "end = type + strlen(type) - 1" leaks the storage that "end" points to.
    libselinux/src/selinux_restorecon.c:376: leaked_storage: Variable "new_entry" going out of scope leaks the storage it points to.
    libselinux/src/selinux_restorecon.c:855: leaked_storage: Variable "xattr_value" going out of scope leaks the storage it points to.
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
    
  - python/semanage: Use standard argparse.error() method in handlePermissive
    
    This method prints a usage message including the message to the standard error
    and terminates the program with a status code of 2.
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
    
  - libselinux/selinux_restorecon: Skip customized files also without -v
    
    In the original code, customizable file contexts were not changed only if -v was
    used. It lead to different behavior when selinux_restorecon was run with -v and
    without it.
    
    Based on an initial patch by Jan Zarsky <jzarsky@redhat.com>
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
    
  - gui: Make all polgen button labels translatable
    
    Signed-off-by: Vit Mojzis <vmojzis@redhat.com>
    
  - dbus: Fix name of polkit function
    
    Add missing action org.selinux.change_default_mode for change_default_mode() and
    remove unused action org.selinux.change_policy_type.
    
    Fixes: e8718ef51463 ("Make sure we do the polkit check on all dbus interfaces.")
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
    
  - checkpolicy: Update manpage
    
    - Add description of -S option
    - Sort the option descriptions based on the synopsis
    - Add missing options to synopsis
    
    Signed-off-by: Vit Mojzis <vmojzis@redhat.com>
    
  - python/semanage/seobject: Fix listing boolean values
    
    Fix gathering boolean values by fixing always False if condition
    (determining whether the values are listed from local store).
    
    Fix listing boolean values by printing the correct values and not
    forcing the use of security_get_boolean_active (which causes
    crash when listing booleans that are not present in active policy).
    
    Fixes:
        # dnf install selinux-policy-mls
        # cat > mypolicy.cil
        (boolean xyz false)
    
        # semodule -i mypolicy.cil -s mls
    
        # semanage boolean -l -S mls
        ...
        irssi_use_full_network         (off  ,  off)  Allow the Irssi IRC Client to connect to any port, and to bind to any unreserved port.
        mozilla_plugin_use_bluejeans   (off  ,  off)  Allow mozilla plugin to use Bluejeans.
        OSError: No such file or directory
    
    Signed-off-by: Vit Mojzis <vmojzis@redhat.com>
    
  - libsepol: do not use uninitialized value for low_value
    
    clang's static analyzer reports a warning when low_bit is used without
    having been initialized in statements such as:
    
        low_value = low_bit << 8;
    
    The warning is: "Result of operation is garbage or undefined".
    
    This is caused by low_bit being only initialized when in_range is true.
    This issue is not critical because low_value is only used in an
    "if (in_range)" block. Silence this warning by moving low_value's
    assignment inside this block.
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - libsepol: Fix RESOURCE_LEAK defects reported by coverity scan
    
    These were reported by Petr Lautrbach (plautrba@redhat.com) and this
    patch was based on his patch with only a few changes.
    
    Signed-off-by: James Carter <jwcart2@tycho.nsa.gov>
    
  - scripts/release: Update links to use release assets instead of wiki links
    
    - new release files are created in release/$RELEASE_TAG
    - download links refers to new release assets
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
    
  - python/semanage: Examples are no longer in the main semanage man page
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
    
  - libselinux: Change matchpathcon usage to match with matchpathcon manpage
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
    
  - libselinux: set an appropriate errno in booleans.c
    
    Fixes:
    $ mkdir booleans
    $ sudo mount --bind ./booleans /sys/fs/selinux/booleans
    $ sudo getsebool -a
    getsebool:  Unable to get boolean names:  Success
    
    Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
    
  - python/restorecon: add force option
    
    This adds 'force' keyword argument to selinux.restorecon() function
    using SELINUX_RESTORECON_SET_SPECFILE_CTX flag.
    
    Signed-off-by: Viktor Ashirov <vashirov@redhat.com>
    
  - python/sepolicy: fix variable name
    
    modify_button_clicked() used variable "type" in a comparison instead of
    "ftype". This is a bug, which has been found with flake8 3.7.0. This
    linter reported:
    
        python/sepolicy/sepolicy/gui.py:1548:20: F823 local variable 'type'
        {0} referenced before assignment
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - python: use == or != when comparing a variable with a string or a integer
    
    Flake8 3.7.0 added a new fatal error message when parsing Python files:
    
        python/semanage/semanage:112:16: F632 use ==/!= to compare str, bytes, and int literals
        python/semanage/semanage:124:23: F632 use ==/!= to compare str, bytes, and int literals
        ...
        python/sepolgen/src/sepolgen/output.py:77:8: F632 use ==/!= to compare str, bytes, and int literals
        python/sepolgen/src/sepolgen/output.py:80:8: F632 use ==/!= to compare str, bytes, and int literals
        python/sepolgen/src/sepolgen/output.py:83:8: F632 use ==/!= to compare str, bytes, and int literals
        python/sepolicy/sepolicy/generate.py:646:16: F632 use ==/!= to compare str, bytes, and int literals
        python/sepolicy/sepolicy/generate.py:1349:16: F632 use ==/!= to compare str, bytes, and int literals
    
    Fix all these warnings.
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - python: reindent lines that were over-indented
    
    Flake8 3.7.0 warns about lines that are over-indented, i.e. lines that
    are indented with more than 4 spaces:
    
        python/sepolgen/src/sepolgen/refparser.py:1047:26: E117 over-indented
        python/sepolgen/src/sepolgen/yacc.py:2569:21: E117 over-indented
        python/sepolicy/sepolicy/interface.py:196:13: E117 over-indented
        python/sepolicy/sepolicy/interface.py:198:13: E117 over-indented
        python/sepolicy/sepolicy/interface.py:215:13: E117 over-indented
        python/sepolicy/sepolicy/interface.py:217:13: E117 over-indented
        python/sepolicy/sepolicy/manpage.py:172:13: E117 over-indented
        python/sepolicy/sepolicy/manpage.py:174:13: E117 over-indented
    
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    
  - Allow installing translated man pages
    
    Signed-off-by: Aleksei Nikiforov <darktemplar@basealt.ru>
    
  - Add man pages translation by Olesya Gerasimenko
    
    Signed-off-by: Olesya Gerasimenko <gammaray@basealt.ru>
    Signed-off-by: Aleksei Nikiforov <darktemplar@basealt.ru>
    

* Update platform/superproject from branch 'master'
  to b6606d5e88cde40ee4dac04201e9063bf480d94c
  - Update git submodules
    
    * Update external/selinux from branch 'master'
      to df5204a030cc8c2edda4c789b508abdb41adf80a
      - Merge remote-tracking branch 'aosp/upstream-master' into mymerge
        
        Followed the following steps:
          # In repo client
          cd external/selinux
          repo sync .
          repo start mymerge .
          git merge aosp/upstream-master --no-ff # resolve any conflicts
          repo upload .
        
        Test: device compiles and boots
        Change-Id: If92a0b5e99e69ac0434197fa848b736b9cf0bf77
        
      - libsepol/cil: silence static analyser's use-after-free warning
        
        clang's static analyze reports a use-after-free in
        __cil_expr_to_string(), when __cil_expr_to_string_helper() does not
        modify its third parameter (variable s1 here) in this loop:
        
            for (curr = curr->next; curr; curr = curr->next) {
                __cil_expr_to_string_helper(curr, flavor, &s1);
                cil_asprintf(&c2, "%s %s", c1, s1);
                free(c1);
                free(s1);
                c1 = c2;
            }
        
        Silence this warning by making sure s1 is always NULL at the beginning
        of every iteration of the loop.
        
        Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
        
      - libselinux: Fix RESOURCE_LEAK defects reported by coverity scan
        
        Fixes:
        
        libselinux/src/checkAccess.c:93: leaked_storage: Variable "user_context" going out of scope leaks the storage it points to.
        libselinux/src/label_db.c:286: leaked_storage: Variable "filp" going out of scope leaks the storage it points to.
        libselinux/src/label_db.c:291: leaked_storage: Variable "filp" going out of scope leaks the storage it points to.
        libselinux/src/label_file.c:405: leaked_storage: Variable "str_buf" going out of scope leaks the storage it points to.
        libselinux/src/load_policy.c:266: leaked_storage: Variable "names" going out of scope leaks the storage it points to.
        libselinux/src/selinux_config.c:183: leaked_storage: Variable "end" going out of scope leaks the storage it points to.
        libselinux/src/selinux_config.c:184: overwrite_var: Overwriting "end" in "end = type + strlen(type) - 1" leaks the storage that "end" points to.
        libselinux/src/selinux_restorecon.c:376: leaked_storage: Variable "new_entry" going out of scope leaks the storage it points to.
        libselinux/src/selinux_restorecon.c:855: leaked_storage: Variable "xattr_value" going out of scope leaks the storage it points to.
        
        Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
        
      - python/semanage: Use standard argparse.error() method in handlePermissive
        
        This method prints a usage message including the message to the standard error
        and terminates the program with a status code of 2.
        
        Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
        
      - libselinux/selinux_restorecon: Skip customized files also without -v
        
        In the original code, customizable file contexts were not changed only if -v was
        used. It lead to different behavior when selinux_restorecon was run with -v and
        without it.
        
        Based on an initial patch by Jan Zarsky <jzarsky@redhat.com>
        
        Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
        
      - gui: Make all polgen button labels translatable
        
        Signed-off-by: Vit Mojzis <vmojzis@redhat.com>
        
      - dbus: Fix name of polkit function
        
        Add missing action org.selinux.change_default_mode for change_default_mode() and
        remove unused action org.selinux.change_policy_type.
        
        Fixes: e8718ef51463 ("Make sure we do the polkit check on all dbus interfaces.")
        
        Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
        
      - checkpolicy: Update manpage
        
        - Add description of -S option
        - Sort the option descriptions based on the synopsis
        - Add missing options to synopsis
        
        Signed-off-by: Vit Mojzis <vmojzis@redhat.com>
        
      - python/semanage/seobject: Fix listing boolean values
        
        Fix gathering boolean values by fixing always False if condition
        (determining whether the values are listed from local store).
        
        Fix listing boolean values by printing the correct values and not
        forcing the use of security_get_boolean_active (which causes
        crash when listing booleans that are not present in active policy).
        
        Fixes:
            # dnf install selinux-policy-mls
            # cat > mypolicy.cil
            (boolean xyz false)
        
            # semodule -i mypolicy.cil -s mls
        
            # semanage boolean -l -S mls
            ...
            irssi_use_full_network         (off  ,  off)  Allow the Irssi IRC Client to connect to any port, and to bind to any unreserved port.
            mozilla_plugin_use_bluejeans   (off  ,  off)  Allow mozilla plugin to use Bluejeans.
            OSError: No such file or directory
        
        Signed-off-by: Vit Mojzis <vmojzis@redhat.com>
        
      - libsepol: do not use uninitialized value for low_value
        
        clang's static analyzer reports a warning when low_bit is used without
        having been initialized in statements such as:
        
            low_value = low_bit << 8;
        
        The warning is: "Result of operation is garbage or undefined".
        
        This is caused by low_bit being only initialized when in_range is true.
        This issue is not critical because low_value is only used in an
        "if (in_range)" block. Silence this warning by moving low_value's
        assignment inside this block.
        
        Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
        
      - libsepol: Fix RESOURCE_LEAK defects reported by coverity scan
        
        These were reported by Petr Lautrbach (plautrba@redhat.com) and this
        patch was based on his patch with only a few changes.
        
        Signed-off-by: James Carter <jwcart2@tycho.nsa.gov>
        
      - scripts/release: Update links to use release assets instead of wiki links
        
        - new release files are created in release/$RELEASE_TAG
        - download links refers to new release assets
        
        Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
        
      - python/semanage: Examples are no longer in the main semanage man page
        
        Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
        
      - libselinux: Change matchpathcon usage to match with matchpathcon manpage
        
        Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
        
      - libselinux: set an appropriate errno in booleans.c
        
        Fixes:
        $ mkdir booleans
        $ sudo mount --bind ./booleans /sys/fs/selinux/booleans
        $ sudo getsebool -a
        getsebool:  Unable to get boolean names:  Success
        
        Signed-off-by: Petr Lautrbach <plautrba@redhat.com>
        
      - python/restorecon: add force option
        
        This adds 'force' keyword argument to selinux.restorecon() function
        using SELINUX_RESTORECON_SET_SPECFILE_CTX flag.
        
        Signed-off-by: Viktor Ashirov <vashirov@redhat.com>
        
      - python/sepolicy: fix variable name
        
        modify_button_clicked() used variable "type" in a comparison instead of
        "ftype". This is a bug, which has been found with flake8 3.7.0. This
        linter reported:
        
            python/sepolicy/sepolicy/gui.py:1548:20: F823 local variable 'type'
            {0} referenced before assignment
        
        Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
        
      - python: use == or != when comparing a variable with a string or a integer
        
        Flake8 3.7.0 added a new fatal error message when parsing Python files:
        
            python/semanage/semanage:112:16: F632 use ==/!= to compare str, bytes, and int literals
            python/semanage/semanage:124:23: F632 use ==/!= to compare str, bytes, and int literals
            ...
            python/sepolgen/src/sepolgen/output.py:77:8: F632 use ==/!= to compare str, bytes, and int literals
            python/sepolgen/src/sepolgen/output.py:80:8: F632 use ==/!= to compare str, bytes, and int literals
            python/sepolgen/src/sepolgen/output.py:83:8: F632 use ==/!= to compare str, bytes, and int literals
            python/sepolicy/sepolicy/generate.py:646:16: F632 use ==/!= to compare str, bytes, and int literals
            python/sepolicy/sepolicy/generate.py:1349:16: F632 use ==/!= to compare str, bytes, and int literals
        
        Fix all these warnings.
        
        Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
        
      - python: reindent lines that were over-indented
        
        Flake8 3.7.0 warns about lines that are over-indented, i.e. lines that
        are indented with more than 4 spaces:
        
            python/sepolgen/src/sepolgen/refparser.py:1047:26: E117 over-indented
            python/sepolgen/src/sepolgen/yacc.py:2569:21: E117 over-indented
            python/sepolicy/sepolicy/interface.py:196:13: E117 over-indented
            python/sepolicy/sepolicy/interface.py:198:13: E117 over-indented
            python/sepolicy/sepolicy/interface.py:215:13: E117 over-indented
            python/sepolicy/sepolicy/interface.py:217:13: E117 over-indented
            python/sepolicy/sepolicy/manpage.py:172:13: E117 over-indented
            python/sepolicy/sepolicy/manpage.py:174:13: E117 over-indented
        
        Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
        
      - Allow installing translated man pages
        
        Signed-off-by: Aleksei Nikiforov <darktemplar@basealt.ru>
        
      - Add man pages translation by Olesya Gerasimenko
        
        Signed-off-by: Olesya Gerasimenko <gammaray@basealt.ru>
        Signed-off-by: Aleksei Nikiforov <darktemplar@basealt.ru>