Update git submodules
* Update platform/system/bt from branch 'master'
  to 76b4ccafa4048e2ca917ba42b69f0d6e10a233b4
  - Merge changes I389b26d7,I0a668115,I75ef0b5c
    
    * changes:
      Alias iterator in packet-gen
      Use generic type for JsonParser
      Change dynamic_cast to static_cast
    
  - Alias iterator in packet-gen
    
    The msvc compiler is unable to translate some of the generated code:
    
    error: no viable conversion from 'std::array<uint8_t, 248>::iterator'
    (aka '_Array_iterator<unsigned char, 248ULL>') to 'uint8_t *' (aka
    'unsigned char *')
    
    Instead of assigning the value to a ptr, we alias the iterator instead.
    
    Test: atest bluetooth_test_gd
    Tag: #gd-refactor
    Bug: 182505215
    Change-Id: I389b26d71ef5bd8f96ae819d34ce11590f14a5e6
    
  - Use generic type for JsonParser
    
    The android emulator team uses a newer libchrome library. The json read
    method now returns an Optional type, vs. a unique_ptr.
    
    We now let the compiler infer the type and rely on the operators to do
    the right thing.
    
    Change-Id: I0a668115659d6508344190783b7dc55d84374f15
    Test: System compiles.
    Bug: 182487647
    
  - Change dynamic_cast to static_cast
    
    dynamic_cast requires type information at run time to throw exceptions.
    This is not available in the emulator build system, where execeptions
    are explicitly disabled.
    
    Instead we use static_cast to downcast.
    
    Change-Id: I75ef0b5c694320fc1e9fe648e8087e4def8cdf94
    Test: Build succeeds.