Update git submodules
* Update platform/external/jetbrains/JetBrainsRuntime from branch 'master'
  to 153020320d4d47c541ede29f60b2c25fecbf804a
  - JBR-1415 CLion with jdk11, frame around Exit button
    
    In addition fallback to normal painting for sub-components of non-opaque
    dialogs and frames
    
  - JBR-1528 backport rendering performance microbenchmarks from openjdk-metal branch
    
    Backport test/jdk/jbu/quality/metal/MetalRenderTest.java
    
  - JBR-1311 [JBR 11] Double quote adding special character on macOS with "English, U.S. International - PC" layout
    
  - JBR-1521 Update quality tests to Java 11
    
    Updated RenderUtil to Java 11
    
  - JBR-1520 [fwp to JBR11] JRE-722 LCD text rendering performance on OSX 25X slower than grayscale
    
    Fixed LCD text performance by using bulk rendering via vertex arrays and
    reducing glTextureBarrierNV usages
    Added native logging of accelerated text rendering
    Replaced glClientActiveTextureARB with glClientActiveTexture
    (it is now part of OpenGL 1.3 standard)
    
  - Updated .gitignore
    
  - JBR-1517 Update font layout speedup code to match the variant submitted to OpenJDK (JDK-8220231)
    
    apply corresponding change from OpenJDK 13
    
  - JBR-1517 Update font layout speedup code to match the variant submitted to OpenJDK (JDK-8220231)
    
    revert original implementation of font layout speedup
    
  - JBR-1435 Various problems with emojis
    
    add piece of code that was missed during migration from JBR 8
    
  - updated JTreg exclude list
    
  - JBR-1427 pycharm jupyter preview stuck  and no response when click on preview.
    
  - JBR-1509 Client area size is wrong in Borderless mode
    
    Fix client area size
    
  - JBR-1255 [JDK 11] java.lang.IllegalArgumentException: Wrong parent window
    
  - JBR-1434 "New file dialog" popup remains above all windows on switching application
    
  - JBR-1417 JBR 11 does not support chain of popups
    
    Adopted version of "JRE-864  Multiple child windows opened and closed in sequence"
    
  - updated JTreg exclude list
    
  - Revert: JBR-1311 [JBR 11] Double quote adding special character on macOS with "English, U.S. International - PC" layout
    
    JBR-1421 resolves the issue
    
  - JBR-1421 Cannot type opening square bracket or brace with a Spanish-ISO keyboard macOS
    
  - updated JTreg exclude list
    
  - JBR-1414 DnD on linux  (XToolkit) does not honor HIDPI scale
    
  - 8211810: X11 Time stamp data should be unsigned
    Reviewed-by: serb
    
  - fixed JBR-1135
    
    don't skip KeyEvents with character A (with keycode == 0) in AWTView::performKeyEquivalent
    
    this condition was added in fix "JBR-184 Mac OS: Delete action deletes twice if Edit menu has be opened before",
    it seems that this condition is unnecessary and JBR-184 doesn't reproduce without it.
    
  - JBR-1412 [fwp to JBR11] JBR-1393 RubyMine is hanging after log in (macOS)
    
    Modified version of JBR8 fix
    
  - updated JTreg exclude list
    
  - updated JTreg exclude list
    
  - updated JTreg exclude list
    
  - JBR-1394 JBR11 does not support LCD text on Mac
    
    Enable LCD rendering for transparent destinations
    
  - Merge pull request #4 from bell-sw/update_8u212
    
    jdk-11.0.3 update
  - Added tag jdk-11.0.3-ga for changeset 175eb80c253a
    
  - updated JTreg exclude list
    
  - Modal dialogs (Messages) shouldn't popup IDEA when another application is active
    
    Investigation is closed
    
  - updated JTreg exclude list
    
  - 8205432: Replace the placeholder Japanese era name
    Reviewed-by: rriggs, chegar
    
  - 8219890: Calendar.getDisplayName() returns empty string for new Japanese Era on some locales
    Reviewed-by: lancea
    
  - 8210633: Cannot parse JapaneseDate string with DateTimeFormatterBuilder Mapped-values
    Reviewed-by: scolebourne, rriggs
    
  - 8208656: Move java/util/Calendar/CalendarTestScripts tests into OpenJDK
    Reviewed-by: naoto
    
  - 8218453: More dynamic RMI interactions
    Reviewed-by: aph
    
  - 8214809: CDS storage improvements
    Reviewed-by: aph
    
  - 8211936: Better String parsing
    Reviewed-by: aph
    
  - 8221769: Revert JDK-8221767 mistakenly pushed to jdk11u 11.0.3
    Reviewed-by: clanger
    
  - 8207760: SAXException: Invalid UTF-16 surrogate detected: d83c ?
    Summary: Properly handle unicode16 characters split across buffer chunks.
    Reviewed-by: lancea, dfuchs
    
  - 8211100: hotspot C1 issue with comparing long numbers on x86 32-bit
    Reviewed-by: iveresov, thartmann
    
  - 8172695: (scanner) java/util/Scanner/ScanTest.java fails
    Reviewed-by: smarks, bpb
    
  - 8211698: Crash in C2 compiled code during execution of double array heavy processing code
    Summary: Correctly registered new Opaque4Node in add_range_check_predicate
    Reviewed-by: roland, thartmann
    
  - 8211064: [AArch64] Interpreter and c1 don't correctly handle jboolean results in native calls
    Reviewed-by: aph
    Contributed-by: andrey.petushkov@gmail.com
    
  - 8215951: AArch64: jtreg test vmTestbase/nsk/jvmti/PopFrame/popframe005 segfaults
    Reviewed-by: aph
    Contributed-by: nick.gasson@arm.com
    
  - 8216350: AArch64: monitor unlock fast path not called
    Reviewed-by: aph, drwhite, fyang
    
  - 8211320: Aarch64: unsafe.compareAndSetByte() and unsafe.compareAndSetShort() c2 intrinsics broken with negative expected value
    Reviewed-by: adinn, aph
    
  - 8220294: ZGC fails to build on GCC 4.4.7: Type parameter issue
    Summary: Specify explicit type in the constructor
    Reviewed-by: shade, pliden
    
  - 8220283: ZGC fails to build on GCC 4.4.7: ATTRIBUTE_ALIGNED compatibility issue
    Reviewed-by: shade, kbarrett
    
  - 8219650: [Testbug] Fix potential crashes in new test hotspot gtest "test_print_hex_dump"
    Reviewed-by: clanger, shade
    
  - 8219651: compiler/ciReplay/TestServerVM.java is failing on windows
    Reviewed-by: thartmann, kvn
    
  - 8219789: [TESTBUG] TestOptionsWithRanges.java produces hs_err_pidXXXXX.log file for VMThreadStackSize=9007199254740991
    Summary: Excluded test of mac range for VMThreadStackSize
    Reviewed-by: coleenp, mseledtsov
    
  - 8219714: [testbug] com/sun/jdi/RedefineNestmateAttr/TestNestmateAttr.java must pass classpath to subprocess
    Reviewed-by: dholmes, dcubed
    
  - 8217609: New era placeholder not recognized by java.text.SimpleDateFormat
    Reviewed-by: nishjain, rriggs
    
  - 8210192: Hsperf counter ParNew::CMS should be ParNew:CMS
    Summary: Rename the counter back to ParNew:CMS and added a test
    Reviewed-by: sjohanss, tschatzl
    Contributed-by: manc@google.com
    
  - 8214122: JDWP is broken on 32 bit Windows: transport library missing onLoad entry
    Reviewed-by: ihse, dcubed
    
  - 8206120: Add test cases for lenient Japanese era parsing
    8211398: Square character support for the Japanese new era
    8218915: Change isJavaIdentifierStart and isJavaIdentifierPart to handle new code points
    Reviewed-by: coffeys, naoto
    Contributed-by: deepak.kejriwal@oracle.com
    
  - 8210989: RSASSA-PSS certificate cannot be selected for client auth on TLSv1.2
    Reviewed-by: xuelei
    
  - 8214118: HeapRegions marked as archive even if CDS mapping fails
    Reviewed-by: tschatzl, jiangli
    
  - 8214189: test/hotspot/jtreg/compiler/intrinsics/mathexact/MulExactLConstantTest.java fails on Windows x64 when run with -XX:-TieredCompilation
    Reviewed-by: kvn
    
  - 8219461: Bump update version for OpenJDK jdk11.0.3
    Reviewed-by: clanger
    
  - 8218192: Remove copy constructor for MemRegion
    Summary: Remove copy constructor in memRegion.hpp
    Reviewed-by: tschatzl, kbarrett
    
  - 8215362: JFR GTest JfrTestNetworkUtilization fails
    Reviewed-by: mgronlun
    
  - 8215175: Inconsistencies in JFR event metadata
    Reviewed-by: mgronlun
    
  - 8213966: The ZGC JFR events should be marked as experimental
    Reviewed-by: pliden
    
  - 8165675: Trace event for thread park has incorrect unit for timeout
    Reviewed-by: mgronlun
    
  - 8215100: AArch64: fix compareTo intrinsic with four-character Latin/Unicode
    Reviewed-by: aph, dpochepk
    Contributed-by: nick.gasson@arm.com
    
  - 8215202: AArch64: jtreg test test/jdk/sun/nio/cs/FindEncoderBugs.java fails
    Reviewed-by: aph
    Contributed-by: nick.gasson@arm.com
    
  - 8216049: stringTable::intern creates redundant String when looking up existing one
    Reviewed-by: redestad, gziemski, rehn, zgu, jiangli
    
  - 8211267: StackOverflowError happened by TextField.setFont(...)
    Reviewed-by: serb, prr
    
  - 8213183: InputMethod cannot be used after its restarting
    Summary: Retains masks at XSelectInput and deletes all IM data at DestroyXIMCallback
    Reviewed-by: naoto
    
  - 8212233: javadoc fails on jdk12 with "The code being documented uses modules but the packages defined in $URL are in the unnamed module."
    Reviewed-by: hannesw, pmuthuswamy
    
  - 8201818: [macosx] Printing attributes break page size set via "java.awt.print.Book" object
    Reviewed-by: prr, psadhukhan
    
  - 8213983: [macosx] Keyboard shortcut ?cmd +`? stops working properly if popup window is displayed
    Reviewed-by: kaddepalli, serb
    
  - 8210394: (zipfs) jdk/nio/zipfs/ZFSTests.java rootdir.zip: The process cannot access the file because it is being used by another process
    Reviewed-by: alanb, jlaskey
    
  - 8216280: Allow later Symantec Policy distrust date for two Apple SubCAs
    Reviewed-by: coffeys
    
  - 8207258: Distrust TLS server certificates anchored by Symantec Root CAs
    Reviewed-by: weijun
    
  - 8219260: Default number of test jobs needs to be consistently calculated
    Reviewed-by: aph, clanger, erikj
    
  - 8214513: A PKCS12 keystore from Java 8 using custom PBE parameters cannot be read in Java 11
    Reviewed-by: mullan
    
  - 8214100: use of keystore probing results in unnecessary exception thrown
    Reviewed-by: mullan
    
  - 8197398: (zipfs) Files.walkFileTree walk indefinitelly while processing JAR file with "/" as a directory inside.
    Reviewed-by: alanb
    
  - 8214339: SSLSocketImpl erroneously wraps SocketException
    Reviewed-by: ascarpino, jnimeh
    
  - 8214827: Incorrect call ClassLoaders.toFileURL("jrt:/java.compiler")
    Summary: Use URL constructor for jrt URL in SystemDictionaryShared::get_shared_protection_domain().
    Reviewed-by: ccheung, iklam, dholmes, coleenp
    
  - 8216578: Remove unused/obsolete method in JFR code
    Reviewed-by: mgronlun, mikael
    
  - 8213782: NullPointerException in sun.security.ssl.OutputRecord.changeWriteCiphers
    Reviewed-by: ascarpino
    
  - 8213583: Error while opening the JFileChooser when desktop contains shortcuts pointing to deleted files
    Reviewed-by: kaddepalli, aivanov, serb
    
  - 8211787: javax/net/ssl/TLSCommon/TLSTest.java throws java.net.SocketTimeoutException: Read timed out
    Summary: java.net.SocketTimeoutException: Read timed out
    Reviewed-by: xuelei
    
  - 8219251: Langtools tests default memory size needs to be 768m
    Reviewed-by: aph, clanger
    
  - 8217597: [TESTBUG] old version docker does not support --cpus
    Summary: "--cpus" is only available in Docker 1.13 and higher, and is the equivalent of setting both --cpu-period and --cpu-quota.
    Reviewed-by: bobv, dholmes
    Contributed-by: aoqi@loongson.cn
    
  - 8211382: ISO2022JP and GB18030 NIO converter issues
    Reviewed-by: sherman, rriggs
    
  - 8211163: UNIX version of Java_java_io_Console_echo does not return a clean boolean
    Reviewed-by: shade, alanb
    
  - 8211295: DriverManager.getConnection fails when called from com.sun.rowset.JdbcRowSetImpl
    Reviewed-by: mchung, alanb
    
  - 8215727: Restore JFR thread sampler loop to old / previous behavior
    Reviewed-by: egahlin, mgronlun
    Contributed-by: milan.mimica@gmail.com
    
  - 8217315: Proper units should print more significant digits
    Reviewed-by: stuefe, tschatzl
    
  - 8217994: os::print_hex_dump should be more resilient against unreadable memory
    Reviewed-by: zgu, stuefe, lucy
    
  - 8212232: Wrong metadata for the configuration of the cutoff for old object sample events
    Reviewed-by: mgronlun
    
  - 8213952: Relax DNSName restriction as per RFC 1123
    Reviewed-by: weijun, mullan, chegar
    
  - 8211765: JarFile constructor throws undocumented exception
    Reviewed-by: lancea, sherman, alanb, chegar
    Contributed-by: Jaikiran Pai <jai.forums2013@gmail.com>
    
  - 8209960: -Xlog:jfr* doesn't work with the JFR
    Reviewed-by: mgronlun
    
  - 8207829: FlightRecorderMXBeanImpl is leaking the first classloader which calls it
    Reviewed-by: mgronlun
    
  - 8211049: Second parameter of "initialize" method is not used
    Summary: Use the specified random object instead of system default
    Reviewed-by: weijun
    
  - 8215330: javax.xml.catalog.CatalogResolverImpl: GroupEntry.matchURI fails to match
    Reviewed-by: lancea
    
  - 8215947: JVM crash with -XX:+DumpSharedSpaces
    Summary: disable JIT compilation if -XX:+DumpSharedSpaces is specified by the user
    Reviewed-by: lfoltan, jiangli
    
  - 8215397: jsig.c missing classpath exception
    Reviewed-by: dholmes
    
  - 8213421: Line number information for execution samples always 0
    Reviewed-by: mgronlun
    
  - 8211821: PrintStringTableStatistics crashes JVM
    Summary: During JVM exit, print the Symbol and String tables before current thread gets deleted.
    Reviewed-by: iklam, dholmes
    
  - 8210874: Test for JDK-8209615
    Reviewed-by: lancea
    
  - 8209615: ParseError in XMLEventReader on a valid input
    Reviewed-by: lancea
    
  - 8209758: 2 classes with same name G1PrintCollectionSetClosure cause crash when logging is enabled
    Reviewed-by: tschatzl, kbarrett
    
  - 8208275: C2 crash in Node::add_req(Node*)
    Summary: Split-if optimization should not process (dead) counted loops.
    Reviewed-by: roland
    
  - 8217342: Build failed with excluding JFR
    Reviewed-by: shade, pliden
    
  - 8214129: SSL session resumption/SNI with TLS1.2 causes StackOverflowError
    Reviewed-by: xuelei, jjiang
    
  - 8213829: Remove circular dependency between g1CollectedHeap and g1ConcurrentMark
    Summary: Improve include statements related to g1CollectedHeap.inline.hpp
    Reviewed-by: kbarrett, tschatzl
    
  - 8200109: NMT: diff_malloc_site assert(early->flags() == current->flags(), "Must be the same memory type")
    Reviewed-by: shade, coleenp
    
  - 8217471: [TESTBUG] gc/epsilon/TestClasses.java fails on some platforms - OOME Metaspace
    Reviewed-by: dholmes, tschatzl
    
  - 8217014: Epsilon should not ignore Metadata GC causes
    Reviewed-by: stuefe, zgu
    
  - 8216308: StackTraceElement::fill_in can use injected Class source-file
    Reviewed-by: coleenp, dholmes
    
  - 8216302: StackTraceElement::fill_in can use cached Class.name
    Reviewed-by: coleenp, dholmes, mchung
    
  - 8217378: UseCriticalCMSThreadPriority is broken
    Reviewed-by: rkennke, dcubed
    
  - 8204142: AWT hang occurs when sequenced events arrive out of sequence in multiple AppContexts
    Summary: Improvements on the synchronization of SequencedEvent events from different AppContexts
    Reviewed-by: serb
    
  - 8217321: [TESTBUG] utilities/test_globalDefinitions.cpp should use _LP64, not LP64
    Reviewed-by: tschatzl, coleenp
    
  - 8218156: "jcmd VM.metaspace basic" misreports free chunk space
    Reviewed-by: zgu
    
  - 8214206: Fix for JDK-8213419 is broken on 32-bit
    Reviewed-by: mdoerr, shade
    
  - 8213419: C2 may hang in MulLNode::Ideal()/MulINode::Ideal() with gcc 8.2.1
    Reviewed-by: kvn, dlong, aph
    
  - Merge conflict in WWindowPeer.displayChanged()
    JRE-660 fix vs JDK-8207070 (commits 8649992 and https://hg.openjdk.java.net/jdk-updates/jdk11u/rev/09456a6d05fb)
    fix: combine two changes to start both updateGC and adjustBoundsOnDPIChange on EventHanderThread.
    DisplayChangesException.java test passed
    
  - 8207070: Webstart app popup on wrong screen in a one-screen setup changing to multi-monitor
    Reviewed-by: prr
    
  - 8187364: Unable to enter zero width non-joiner (ZWNJ) symbol in Swing text component
    Reviewed-by: serb, dmarkov
    (empty commmit for backport robot; the fix is actually backported already)
    
  - Merge conflict in Java_sun_font_FreetypeFontScaler_getGlyphImageNative
    IDEA-57233 fix vs JDK-8216965 (commits 0456745 vs https://hg.openjdk.java.net/jdk-updates/jdk11u/rev/a363f160b05a)
    fix: combine two changes to include both error check and renderFlag.
    FontSize1Test test passed
    
  - 8216965: crash in freetypeScaler.c CopyBW2Grey8
    Reviewed-by: serb, mbaesken
    
  - updated JTreg exclude list
    
  - JBR-1380: Regression test java/awt/Graphics2D/DrawString/LCDTextSrcEa.java works incorrectly
    
  - JBR-1311 [JBR 11] Double quote adding special character on macOS with "English, U.S. International - PC" layout
    
  - updated JTreg exclude list
    
  - JBR-1314 Font difference in pycharm 2019.1 on Ubuntu
    
    Removed disabling hints on MAX_FCSIZE_LTL_DISABLED font size
    
  - JBR-1372: JDialog1054.java, MoveFocusShortcutTest.java regression tests need update
    
  - updated JTreg exclude list
    
  - [JDK 11] Font Rendering on MacOS
    
    Fixed regression caused by JBR-1076 by limiting fallback painting
    only to undecorated non-opaque frames and dialogs
    
  - IDEA-210154 Borderless UI: Top frame of IDEA window is blue
    
  - updated JTreg exclude list
    
  - [followup] JBR-1365 force IDE-managed HiDPI on Linux for fractional scales
    
  - JBR-1365 force IDE-managed HiDPI on Linux for fractional scales
    
  - Revert "JRE-1199: added the list of files required for stripped JBR bundle"
    
    This reverts commit a1fcf9fc
    
  - Revert "JRE-1199: added the list of files required for stripped JBR bundle (follow up)"
    
    This reverts commit 9820ecb7
    
  - Revert "JRE-1199: added the list of files required for stripped JBR bundle (follow up)"
    
    This reverts commit e5dd1ec9
    
  - Revert "JRE-1199: corrected the list of files required for stripped JBR bundle on Windows"
    
    This reverts commit 6f4be20e
    
  - Revert "JRE-1199: added the list of files required for stripped JBR bundle - removed leading ./"
    
    This reverts commit 13fbc2be
    
  - Revert "JRE-1199: added JFX files"
    
    This reverts commit ec0d6d6b
    
  - Revert "JRE-1199: added the list of files required for stripped JBR bundle (follow up)"
    
    This reverts commit a4e7fdb6
    
  - Revert "JRE-1238: NoClassDefFoundError: Could not initialize class sun.tools.attach.VirtualMachineImpl"
    
    This reverts commit 366ceeb8
    
  - updated JTreg exclude list
    
  - JBR-1362 Multiple child windows opened and closed in sequence result in a focus loss
    
  - JBR-1351 Borderless UI: Bold frame around IDEA window appears on non-HiDPI display
    
  - JBR-1354 com/sun/tools/attach/PermissionTest.java: access denied ("java.util.PropertyPermission" "sun.tools.attach.tmp.only" "read")
    
  - JBR-1061 .attach_pid files in the working dir - flag to put .attach file in tmp dir only
    
  - updated JTreg exclude list
    
  - updated JTreg exclude list
    
  - updated JTreg exclude list