Update git submodules
* Update platform/frameworks/opt/gamesdk from branch 'master'
  to 626be67d857c111cb722312fd3c9e040d7dacc4f
  - Fix swappy compilation when using android studio
    
    This fixes the following compilation error:
    linux-x86_64/bin/arm-linux-androideabi-ld: error: unrecognized emulation
    armelf_linux_eabi
    
    Depending on which ndk toolchain we're using we do/don't need to add an
    "-m" parameter to specify the emulation
    
    Bug: n/a
    Test: tested manually
    Change-Id: I797188fa2a908578c883a2da28d0985bd5acb5f3