Update git submodules
* Update platform/cts from branch 'master'
  to 80849a4d70fe760f70d9b5a092eb4dfa47af7ebb
  - Merge "CtsNdkBinderTestCases: fix sync ordering"
  - CtsNdkBinderTestCases: fix sync ordering
    
    One of our test farms hit this error:
    06-28 14:51:43.707 16438 16457 E TestRunner: failed: testCallingInfo[class android.binder.cts.JavaService$Remote](android.binder.cts.JavaClientTest)
    06-28 14:51:43.707 16438 16457 E TestRunner: ----- begin exception -----
    06-28 14:51:43.708 16438 16457 E TestRunner: java.lang.AssertionError: expected:<0> but was:<-1>
    06-28 14:51:43.708 16438 16457 E TestRunner: 	at org.junit.Assert.fail(Assert.java:88)
    ...
    
    I suspect this is the cause, but cannot prove it (have run this tests
    thousands of times and never hit this).
    
    Fixes: 136271878
    Test: CtsNdkBinderTestCases (although unable to repro reported flake)
    Change-Id: Id611effd0b93eb7fc644bccedda139198fd37c8a
    

* Update platform/superproject from branch 'master'
  to 0a3873ae77f7e70d4c3086feecc58a9bdd8e1ed6
  - Update git submodules
    
    * Update cts from branch 'master'
      to 80849a4d70fe760f70d9b5a092eb4dfa47af7ebb
      - Merge "CtsNdkBinderTestCases: fix sync ordering"
      - CtsNdkBinderTestCases: fix sync ordering
        
        One of our test farms hit this error:
        06-28 14:51:43.707 16438 16457 E TestRunner: failed: testCallingInfo[class android.binder.cts.JavaService$Remote](android.binder.cts.JavaClientTest)
        06-28 14:51:43.707 16438 16457 E TestRunner: ----- begin exception -----
        06-28 14:51:43.708 16438 16457 E TestRunner: java.lang.AssertionError: expected:<0> but was:<-1>
        06-28 14:51:43.708 16438 16457 E TestRunner: 	at org.junit.Assert.fail(Assert.java:88)
        ...
        
        I suspect this is the cause, but cannot prove it (have run this tests
        thousands of times and never hit this).
        
        Fixes: 136271878
        Test: CtsNdkBinderTestCases (although unable to repro reported flake)
        Change-Id: Id611effd0b93eb7fc644bccedda139198fd37c8a