Update git submodules
* Update platform/system/extras from branch 'master'
  to bc726fdd18e7cdf77d646568b74836f9dedbc3e6
  - Merge "profcollectd: Provide clearer messaging when daemon is not running"
  - profcollectd: Provide clearer messaging when daemon is not running
    
    Instead of crashing, now outputs:
      $ profcollectctl once
      Trace once
      Error: Failed to trace.
    
      Caused by:
          0: Failed to get profcollectd binder service, is profcollectd running?
          1: StatusCode::NAME_NOT_FOUND
    
    Test: manual
    Change-Id: Id46c8504e1a4ab2537b37c8d927d1abd9a997443