Update git submodules
* Update platform/external/rust/crates/libc from branch 'master'
  to f00ddafb90c13557028ad452f9ec9dc5795fbc0a
  - Fix compile error for riscv64-linux-android
    
    Fixes:
    error[E0369]: cannot subtract `char` from `char`
      --> prebuilts/rust/linux-x86/1.64.0/src/stdlibs/vendor/libc/src/unix/linux_like/android/b64/riscv64/mod.rs:63:53
       |
    63 | pub const COMPAT_HWCAP_ISA_I: ::c_ulong = 1 << ('I' - 'A');
       |                                                 --- ^ --- char
       |                                                 |
       |                                                 char
    
    (cherry picked from commit a7f9d0a7f8b49b27f4668b5e84b926376989bcff)
    Test: lunch aosp_riscv64-userdebug && m -k
    Change-Id: I78484cd43c52c3acd30cbf6a536237a66f9671e7