Update git submodules
* Update platform/external/cpu_features from branch 'master'
  to 50b79af61d87d88428cba29b436e7109b95f35db
  - Merge v0.8.0 into master.
    
    Test: Run `atest -a --test-mapping external/cpu_features:all` (on
          x86-64 and Arm64 devices)
    Change-Id: Ia6cbc61e844a10e3dc76d3ee92bf214da89651a2
    
  - Release v0.8.0
    
  - Add Mendocino ZEN2 detection (#305)
    
    
  - Add RISCV vector extension (#289)
    
    Co-authored-by: Michael Roe <michael-roe@users.noreply.github.com>
  - Add Raptor Lake-P and Raptor Lake-HX/S detection (#300)
    
    
  - Add cpu-features-jni Java bindings to README (#297)
    
    * Add cpu-features-jni Java bindings
    
    * Update Java bindings URL
  - Add Windows Arm64 support (#291)
    
    * Add Windows Arm64 support
    
    To add Windows Arm64 support was added detection of features via Windows API function IsProcessorFeaturePresent. Added _M_ARM64 to detect CPU_FEATURES_AARCH64 macro on Windows. Added initial code for Windows Arm64 testing and provided test for Raspberry PI 4. We can't use "define_introspection_and_hwcaps.inl" as a common file for all operating systems due to msvc compiler error C2099: initializer is not a constant, so as a workaround for Windows I used separate "define_introspection.inl"
    
    See also: #268, #284, #186
    
    * [CMake] Add  windows_utils.h to PROCESSOR_IS_AARCH64
    
    * Add detection of armv8.1 atomic instructions
    
    * Update note on win-arm64 implementation and move to cpuinfo_aarch64.h
    
    * Remove redundant #ifdef CPU_FEATURES_OS_WINDOWS
    
    * Add note on FP/SIMD and Cryptographic Extension for win-arm64
    
    * Add comments to Aarch64Info fields
    
    Added comments to specify that implementer, part and variant we set 0 for Windows, since Win API does not provide a way to get information. For revision added comment that we use GetNativeSystemInfo
  - Update C++ standard for tests from C++11 to C++14 (#293)
    
    Since 1.13.0, gtest requires at least C++14. When it is automatically
    downloaded and compiled, gtest’s CMake scripts override the C++
    standard, so the tests are compiled in C++14 mode already. Changing the
    C++ standard in cpu_features will make it easier for users such as Linux
    distribution packagers who are linking against an external or
    system-wide copy of gtest 1.13.0 or later.
  - Add documentation on current behavior for X86 (#212)
    
    * Add documentation for X86 OS support
    
    * Update X86 documentation
    
    * Remove outdated cache info comment
    
    * Update x86 documentation according to comments
    
    * Update Internal structures documentation
  - Fix badges in README.md
    
  - Support risc-v (#287)
    
    Co-authored-by: DaniAffCH <danieleaffinita2000@gmail.com>
    Co-authored-by: Corentin Le Molgat <corentinl@google.com>
  - Include tests when using QEMU (#288)
    
    * Include tests when using QEMU
    * Also add `set -e` so we fail when tests fail
  - script: rename few variables in expand_bootlin
    
  - Add Intel Raptor Lake uarch detection (#283)
    
    
  - Update README.md to report support of POWER and s390x (#284)
    
    
  - Improve CI (Aarch64, Power) (#285)
    
    * scripts: Fix shellcheck
    
    * script: Bump qemu 5.2.0 -> 7.1.0
    
    * scripts: add bootlin aarch64 toolchains
    
    * scripts: Add PowerPC bootlin toolchain
    
    * scripts: cleanup linaro toolchains
    
    * scripts: cleanup codespace
    
    * cmake(ci): Add aarch64 bootlin support
    
    * cmake(ci): Add PowerPC bootlin support
    
    * ci: Add aarch64 bootlin jobs
    
    * ci: Add PowerPC bootlin jobs
    
    * Remove conflict with compiler generated preprocessor
    
    Co-authored-by: Guillaume Chatelet <gchatelet@google.com>
  - S390X Support (#274)
    
    * support for s390x
    
    * added z15 T01, T02 model checking
    
    * removed z15 checking
    
    * removed empty strings
    
    * added s390x unit tests
    
    * added reference url for hwcaps
    
    * moved documentation to S390XFeatures struct, updated copyright date, removed unused include statement
    
    * changed num_processors to int
    
    * removed newlines from test inputs
    
    * scripts: Add bootlin s390x support
    
    * cmake(ci): Add s390x support
    
    * ci: Add s390x workflow
    
    Co-authored-by: Marcos <marcos.araque.fiallos@ibm.com>
    Co-authored-by: Corentin Le Molgat <corentinl@google.com>
  - Add REP instructions detection (#282)
    
    
  - Add X86 movdir detection (#281)
    
    
  - Add X86 GFNI detection
    
    
  - add x86/avx512_fp16 detection (#279)
    
    fixes #278
  - Add AMD ZEN4 Raphael detection (#277)
    
    
  - add mobile core flavor (#266)
    
    
  - Use textual_hdrs for bazel instead of hdrs (#276)
    
    
  - Replace hardcoded cache type value to enum type for X86 tests (#270)
    
    Replaced hardcoded integer values of cache type to `CacheType` values for X86 tests and added declaration `CacheType` for `P4_CacheInfo` test
  - Add support for detecting Intel CascadeLake CPUs (#271)
    
    Should close
    https://github.com/google/cpu_features/issues/260
  - Add cache detection for old AMD processors (#199)
    
    * Add cache detection for of old AMD processors
    
    
    
    
    update links
    
    * Add documentation link for cache_size * 512
    
    * Update legacy amd cache detection
  - add amd cato (#267)
    
    * add AMD RX-8125, RX-8120, and A9-9820 detection
  - Get rid repeated branch (#269)
    
    * Get rid repeated branch
    * Update cache type field comment
  - add intel goldmont plus (#256)
    
    * add intel goldmont plus (INTEL_ATOM_GMT_PLUS)
  - add amd piledriver 0x10 model (#255)
    
    * add amd piledriver 0x10 model
  - add CometLake model 166
    
  - Replace hardcode values to constants
    
    
  - Added some missing amd k12 uarch (#259)
    
    * Add comment about AMD_K12 LLANO.
    * Add family 0x12 model 0x00 to it.
  - Add AVX_VNNI
    
    
  - add Lakefield
    
  - add intel Tremont microarch
    
  - [NFC] Remove unused variable
    
  - [NFC] Restrict windows inclusion to windows platforms
    
  - test enum macro consistency (#257)
    
    
  - Add detection LZCNT (#254)
    
    Fixes #253 
  - remove internal FillX86BrandString usage (#258)
    
    
  - Add macros for RISCV hwcaps (#246)
    
    Co-authored-by: Michael Roe <michael-roe@users.noreply.github.com>
  - add comet lake unit test #248 (#250)
    
    
  - add windows ssse3,sse4_1,sse4_2 detection for non avx path (#251)
    
    * add windows ssse3,sse4_1,sse4_2 detection for non avx path
    
    * remove special WESTMERE case
    
    * move windows conditional redefinition to separate header
    
    * fix minor issues
  - Merge v0.7.0 into master. am: 47bd1869cd am: 5febe36e4e am: 4e0d6a4041 am: ea9bafd934
    
    Original change: https://android-review.googlesource.com/c/platform/external/cpu_features/+/2158718
    
    Change-Id: I0be6ba6b0e8c42accdfeec6c1a7f9b4407322599
    Signed-off-by: Automerger Merge Worker <android-build-automerger-merge-worker@system.gserviceaccount.com>
    
  - Merge v0.7.0 into master. am: 47bd1869cd am: 5febe36e4e am: 4e0d6a4041
    
    Original change: https://android-review.googlesource.com/c/platform/external/cpu_features/+/2158718
    
    Change-Id: I985cbc87033a5081138966d5720df9b4bc7ab783
    Signed-off-by: Automerger Merge Worker <android-build-automerger-merge-worker@system.gserviceaccount.com>
    
  - Merge v0.7.0 into master. am: 47bd1869cd am: 5febe36e4e
    
    Original change: https://android-review.googlesource.com/c/platform/external/cpu_features/+/2158718
    
    Change-Id: I12596ddd0aa8af946afbd7865849677891d81519
    Signed-off-by: Automerger Merge Worker <android-build-automerger-merge-worker@system.gserviceaccount.com>
    
  - Merge v0.7.0 into master. am: 47bd1869cd
    
    Original change: https://android-review.googlesource.com/c/platform/external/cpu_features/+/2158718
    
    Change-Id: Ie2cd87a7f5a5ad0cdfd5c416b530e1ac661545c3
    Signed-off-by: Automerger Merge Worker <android-build-automerger-merge-worker@system.gserviceaccount.com>
    
  - add comet lake support #248 (#249)
    
    
  - Add not about avx512_4vbmi2 being an alias of avx512_4fmaps
    
  - Add macros for RISCV features (#244)
    
    Co-authored-by: Michael Roe <michael-roe@users.noreply.github.com>
  - Add AMD ZEN 4 uarch and update detection (#243)
    
    * Add AMD ZEN 4 uarch and update detection
    
    * Add tests via cpuid dump
  - Added some MIPS features. (#241)
    
    Co-authored-by: Michael Roe <michael-roe@users.noreply.github.com>
  - Added CPU_FEATURES_COMPILED_MIPS_MIPS3D. (#240)
    
    Co-authored-by: Michael Roe <michael-roe@users.noreply.github.com>
  - Add install doc (Fix #238) (#239)
    
    
  - Update AArch64 features to Linux 5.17. (#237)
    
    
  - Comply with -Wstrict-prototypes
  - Comply with -Wstrict-prototypes
  - Add cpu_features to hwasan-postsubmit am: 7783526676 am: 39430949fb am: 99ce48d49f
    
    Original change: https://android-review.googlesource.com/c/platform/external/cpu_features/+/2034603
    
    Change-Id: I8ee0ecc2edfdb84bcc28d160f69274a6d38c9d69
    
  - Add bazel ci README, update main README (#235)
    
    
  - Move ci folder and make naming more consistent (#233)
    
    
  - Add script to generate markdown CI badges
    
  - Update CI status table
  - ci: Add bazel jobs (#232)
    
    
  - Bump google test commit
    
  - Remove trailing whitespace in .grenrc.yml
  - Improve the release process (#231)
    
    
  - Merge sc-mainline-prod
    
    Bug: 189946434
    Change-Id: I2913d729c623bb6190d9d65491a9903e8778e781
    
  - Merge "Add min_sdk_version for ART module." am: 99eb6aeb11 am: 7189f0f11c am: 1b802d5e41 am: fc822b57d5
    
    Original change: https://android-review.googlesource.com/c/platform/external/cpu_features/+/1614812
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I610474e04d98d3f58b8f849d04d10710cec2e8ec
    
  - Merge "Add min_sdk_version for ART module." am: 99eb6aeb11 am: 7189f0f11c am: 1b802d5e41 am: fc822b57d5
    
    Original change: https://android-review.googlesource.com/c/platform/external/cpu_features/+/1614812
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I081116ac36cf332f35a11bc6b52321679af6df0f
    
  - [automerger skipped] Mark ab/7061308 as merged in stage. am: 107ea1cb3b -s ours am: ba9f097184 -s ours am: 05b68d05e2 -s ours
    
    am skip reason: Change-Id Id3801f60a8d3d7c495aa9cf1b37260b93875d8d4 with SHA-1 ee2401247f is in history
    
    Original change: undetermined
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I13220d206594f816ba47021f1644695a920dee44
    
  - [automerger skipped] Mark ab/7061308 as merged in stage. am: 107ea1cb3b -s ours am: ba9f097184 -s ours am: 05b68d05e2 -s ours
    
    am skip reason: Change-Id Id3801f60a8d3d7c495aa9cf1b37260b93875d8d4 with SHA-1 ee2401247f is in history
    
    Original change: undetermined
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I226afbbfe03b9d702b8ab98dbc169ffc39888cd7
    
  - Clean up cc_test TEST_MAPPING after default update am: 79725d88db am: 457281ab2a am: 9708bdc7ad am: 0400a02dbd
    
    Original change: https://android-review.googlesource.com/c/platform/external/cpu_features/+/1596917
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Iad4684fce841f5c48f9d85c01a3ca22556754558
    
  - Clean up cc_test TEST_MAPPING after default update am: 79725d88db am: 457281ab2a am: 9708bdc7ad am: 0400a02dbd
    
    Original change: https://android-review.googlesource.com/c/platform/external/cpu_features/+/1596917
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Ib76cc91b71480953abe45855bb91d6afec41cda3
    
  - [LSC] Add LOCAL_LICENSE_KINDS to external/cpu_features am: a4f534609a am: 96786250fa am: af574af6f3 am: 64c6baae8a
    
    Original change: https://android-review.googlesource.com/c/platform/external/cpu_features/+/1588874
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Ic67f8edb573b1e07350c7a3a5338d54f8498274c
    
  - [LSC] Add LOCAL_LICENSE_KINDS to external/cpu_features am: a4f534609a am: 96786250fa am: af574af6f3 am: 64c6baae8a
    
    Original change: https://android-review.googlesource.com/c/platform/external/cpu_features/+/1588874
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I969d5d6af65ca95d728c8304e1d20cbfeebe4a68