Update git submodules
* Update platform/external/autotest from branch 'master'
  to 7a335b8a01114da40b91aa98a16f58005bbbde51
  - servo: remove old code-logic on usb port am: 11daf2cae4
    
    Change-Id: Ie75348ed3913cc832f9b8bd905d59e908fe5ef81
    
  - servo: remove old code-logic on usb port
    
    Due to autotest and hdctools not being in sync, and v3, guado, fizz not
    always being on the same version, the logic on how to switch usb muxes
    and power is duplicated in autotest and hdctools. This change mitigates
    that issue by leveragin the full support on the hdctools side, by
    calling thoes abstractions directly, cleaning up the autotest-side, and
    leaving only one code-path.
    
    Exempt-From-Owner-Approval: owner had given cr before, only documentation change since then
    
    BUG=chromium:1017308, chromium:869335
    
    TEST=test_that --autotest_dir . 100.90.26.19
    platform_InstallTestImage.local --args "servo_host=100.90.28.161"
    
    // observe test passing
    
    TEST=test_that --autotest_dir . $DIP power_USBHotplugInSuspend
    --args "servo_host=$LIP"
    
    /tmp/test_that_results_4y3rgf/results-1-power_USBHotplugInSuspend
    [  FAILED  ]
    /tmp/test_that_results_4y3rgf/results-1-power_USBHotplugInSuspend
    ERROR: Client failed to suspend.
    
    // this is the same failure as before, as the test is currently broken.
    Though the usb logic seems fine.
    
    Change-Id: I40328c557790855a5a8a00fdbd8b374d48042bcb
    Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/2073517
    Tested-by: Ruben Rodriguez Buchillon <coconutruben@chromium.org>
    Reviewed-by: Dana Goyette <dgoyette@chromium.org>
    Reviewed-by: Garry Wang <xianuowang@chromium.org>
    Commit-Queue: Ruben Rodriguez Buchillon <coconutruben@chromium.org>
    

* Update platform/superproject from branch 'master'
  to 0de77f3d1cddd1466e9ac99acd73d50017b8c501
  - Update git submodules
    
    * Update external/autotest from branch 'master'
      to 7a335b8a01114da40b91aa98a16f58005bbbde51
      - servo: remove old code-logic on usb port am: 11daf2cae4
        
        Change-Id: Ie75348ed3913cc832f9b8bd905d59e908fe5ef81
        
      - servo: remove old code-logic on usb port
        
        Due to autotest and hdctools not being in sync, and v3, guado, fizz not
        always being on the same version, the logic on how to switch usb muxes
        and power is duplicated in autotest and hdctools. This change mitigates
        that issue by leveragin the full support on the hdctools side, by
        calling thoes abstractions directly, cleaning up the autotest-side, and
        leaving only one code-path.
        
        Exempt-From-Owner-Approval: owner had given cr before, only documentation change since then
        
        BUG=chromium:1017308, chromium:869335
        
        TEST=test_that --autotest_dir . 100.90.26.19
        platform_InstallTestImage.local --args "servo_host=100.90.28.161"
        
        // observe test passing
        
        TEST=test_that --autotest_dir . $DIP power_USBHotplugInSuspend
        --args "servo_host=$LIP"
        
        /tmp/test_that_results_4y3rgf/results-1-power_USBHotplugInSuspend
        [  FAILED  ]
        /tmp/test_that_results_4y3rgf/results-1-power_USBHotplugInSuspend
        ERROR: Client failed to suspend.
        
        // this is the same failure as before, as the test is currently broken.
        Though the usb logic seems fine.
        
        Change-Id: I40328c557790855a5a8a00fdbd8b374d48042bcb
        Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/autotest/+/2073517
        Tested-by: Ruben Rodriguez Buchillon <coconutruben@chromium.org>
        Reviewed-by: Dana Goyette <dgoyette@chromium.org>
        Reviewed-by: Garry Wang <xianuowang@chromium.org>
        Commit-Queue: Ruben Rodriguez Buchillon <coconutruben@chromium.org>