Update git submodules
* Update platform/external/googletest from branch 'master'
  to 4f6f24cbf624e07caca25a593c2cb6f812b10d80
  - Merge "Upgrade googletest to 3f5b5b8f8493a03fa25f1e4a7eae7678514a431d"
  - Upgrade googletest to 3f5b5b8f8493a03fa25f1e4a7eae7678514a431d
    
    Test: None
    Change-Id: I763e78fa0bdd9487977004fa95d281ccf77d698b
    
  - Googletest export
    
    Remove special case for protocol buffers. It is no longer needed.
    
    PiperOrigin-RevId: 246550795
    
  - Merge pull request #2245 from daquexian:fix_wsign_conversion
    
    PiperOrigin-RevId: 246550729
    
  - Googletest export
    
    Clarify build system support - CMake and automake community supported
    
    PiperOrigin-RevId: 245821927
    
  - Fix -Wsign-conversion error by adding static_cast
    
  - Merge pull request #2242 from SylvestreG:master
    
    PiperOrigin-RevId: 245798478
    
  - Removing  obsolete msvc 2005 and 2010
    
  - Removing  obsolete codegear and msvc 2010
    
  - Googletest export
    
    Internal Change
    
    PiperOrigin-RevId: 245788057
    
  - Merge pull request #2241 from ngie-eign:fix-wsign-conversion-fallout
    
    PiperOrigin-RevId: 245430295
    
  - Fix compilation on CentOS 7
    
  - Address fallout from -Wsign-conversion work on Windows
    
    Some Windows users builds were broken after a0d60be. This change
    addresses the lingering -Wsign-conversion issues with those platforms
    by adding some missing `static_cast` calls as needed.
    
    Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>
    
  - Googletest export
    
    Add GTEST_FAIL_AT, an equivalent to ADD_FAILURE_AT but that
    spawns a fatal failure rather than a non-fatal, eg. the equivalent
    of an ASSERT* failure rather than an EXPECT* failure.
    
    PiperOrigin-RevId: 244746609
    
  - Update README.md
  - Googletest export
    
    Fixes https://github.com/google/googletest/issues/2232
    
    PiperOrigin-RevId: 244237560
    
  - Googletest export
    
    Remove GMock Doctor.
    It has not been actively supported for a while.
    We also now have better techniques to improve compiler errors where needed
    instead of requiring a separate tool to diagnose them.
    
    PiperOrigin-RevId: 244196068
    
  - Googletest export
    
    Expose more information in SuiteApiResolver diagnostic output
    
    PiperOrigin-RevId: 244179347
    
  - Merge pull request #2170 from ngie-eign:issue-2146-ver2
    
    PiperOrigin-RevId: 244069956
    
  - Googletest export
    
    [googletest] Fix death test condition.
    
    PiperOrigin-RevId: 243742424
    
  - Googletest export
    
    Migrate ZX_WAIT_ASYNC_REPEATING to ZX_WAIT_ASYNC_ONCE
    
    ZX_WAIT_ASYNC_REPEATING is deprecated so convert code to use
    ZX_WAIT_ASYNC_ONCE instead.
    
    PiperOrigin-RevId: 243707147
    
  - Merge pull request #2230 from return:style-issue
    
    PiperOrigin-RevId: 243313653
    
  - Sort Haiku platform definition alphabetically.
    
    Fixes a minor ordering issue when defining the platform macro.
    Also fixes a minor typo: 'Max OS X' -> 'Mac OS X'.
    
  - Merge pull request #2226 from davidben:msvc-5046
    
    PiperOrigin-RevId: 243121568
    
  - Merge pull request #2229 from return:haiku-support
    
    PiperOrigin-RevId: 243104604
    
  - Merge pull request #2228 from rongou/patch-2
    
    replace test case with test suite in the primer
  - Add Haiku platform support.
    
    This allows googletest to recognize the Haiku operating system when
    running tests in other projects.
    
  - replace test case with test suite in the primer
  - Merge pull request #2225 from rongou/patch-1
    
    add missing period
  - MSVC C5046 warning is unavailable in MSVC 2015.
    
    Per the MSVC documentation the warning is new as of Visual Studio 2017,
    version 15.8.
    https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c5046?view=vs-2019
    
    GTest users building on MSVC 2015 or older versions of 2017 will, when
    C4616 is enabled, see a warning like:
    
    [...]gtest-matchers.h(53): error C2220: warning treated as error - no 'object' file generated
    [...]gtest-matchers.h(53): warning C4619: #pragma warning: there is no warning number '5046'
    
    Guard the mention of 5046 by an _MSC_VER check. VS2017 15.8 corresponds
    to an _MSC_VER of 1915.
    https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019
    
  - add missing period
  - Update README.md
  - Merge pull request #2222 from Ivaylo-Kirov/patch-1
    
    Update ForDummies.md
  - Update ForDummies.md
  - clang: fix `-Wsign-conversion` errors
    
    Cast some values as their unsigned equivalents or `size_t` to match the
    parameter type used for the template object under test. Also, provide
    UInt32 equivalent delegate methods for some callers (with
    int-equivalents for backwards compatibility).
    
    This closes #2146.
    
    Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>
    
  - Merge pull request #2148 from ngie-eign:clang-add-explicit-c++11-rtti-flag
    
    PiperOrigin-RevId: 242038269
    
  - Googletest export
    
    [fdio] Improve fdio_pipe_half signature, step 3.
    
    The return value on fdio_pipe_half conflated two things: the error code
    on failure (as a zx_status_t) or a file descriptor on success. This
    technically worked, because they're both ints, the error code was always
    negative, and the file descriptor always positive. However, the stated
    return type of zx_status_t was misleading. This changes the signature
    such that it always returns an actual zx_status_t, and the file
    descriptor is returned through a pointer argument.
    
    Also remove the last argument, since it was always given the same value.
    
    This needs to be done as a soft transition because it's called from the
    Dart runtime, from googletest, and from Crashpad, and Crashpad and
    Chromium both depend on googletest on Fuchsia. The steps are as follows:
    1) Add fdio_pipe_half2.
    2) Update Dart to use fdio_pipe_half2.
    3) Update googletest to use fdio_pipe_half2.
    4) Roll updated googletest into Chronium.
    5) Update Crashpad to use fdio_pipe_half2 and roll updated googletest into it.
    6) Update fdio_pipe_half to match fdio_pipe_half2.
    7) Update Dart to use fdio_pipe_half again.
    8) Update googletest to use fdio_pipe_half again.
    9) Roll updated googletest into Chronium.
    10) Update Crashpad to use fdio_pipe_half again and roll updated googletest into it.
    11) Remove fdio_pipe_half2.
    
    This is step 3.
    
    PiperOrigin-RevId: 241957137
    
  - clang: explicitly enable/disable RTTI support with the compiler
    
    Add `-frtti` to the compiler with the base flags case so that RTTI is
    enabled by default with clang. Add its inverse analog,
    `cxx_no_rtti_flags` in order to test the case with RTTI off, similar to
    gcc.
    
    This reduces the amount of testing/support overhead needed in the
    non-RTTI case with clang, as the tests currently fail when these two
    features are off with version 1.8.1. This something I used in when
    investigating test failures on FreeBSD, as the tests that rely on
    RTTI were failing with googletest 1.8.1 on the OS platform.
    
    More investigation is being done to determine how this should be fixed
    on FreeBSD 11.2-RELEASE with ports, as the package doesn't currently
    compile the tests, and when enabled (based on my WIP diff), the tests
    fail in similar ways.
    
    Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>
    

* Update platform/superproject from branch 'master'
  to 39e3664c11071e81282ce2f101ed839aa80ec398
  - Update git submodules
    
    * Update external/googletest from branch 'master'
      to 4f6f24cbf624e07caca25a593c2cb6f812b10d80
      - Merge "Upgrade googletest to 3f5b5b8f8493a03fa25f1e4a7eae7678514a431d"
      - Upgrade googletest to 3f5b5b8f8493a03fa25f1e4a7eae7678514a431d
        
        Test: None
        Change-Id: I763e78fa0bdd9487977004fa95d281ccf77d698b
        
      - Googletest export
        
        Remove special case for protocol buffers. It is no longer needed.
        
        PiperOrigin-RevId: 246550795
        
      - Merge pull request #2245 from daquexian:fix_wsign_conversion
        
        PiperOrigin-RevId: 246550729
        
      - Googletest export
        
        Clarify build system support - CMake and automake community supported
        
        PiperOrigin-RevId: 245821927
        
      - Fix -Wsign-conversion error by adding static_cast
        
      - Merge pull request #2242 from SylvestreG:master
        
        PiperOrigin-RevId: 245798478
        
      - Removing  obsolete msvc 2005 and 2010
        
      - Removing  obsolete codegear and msvc 2010
        
      - Googletest export
        
        Internal Change
        
        PiperOrigin-RevId: 245788057
        
      - Merge pull request #2241 from ngie-eign:fix-wsign-conversion-fallout
        
        PiperOrigin-RevId: 245430295
        
      - Fix compilation on CentOS 7
        
      - Address fallout from -Wsign-conversion work on Windows
        
        Some Windows users builds were broken after a0d60be. This change
        addresses the lingering -Wsign-conversion issues with those platforms
        by adding some missing `static_cast` calls as needed.
        
        Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>
        
      - Googletest export
        
        Add GTEST_FAIL_AT, an equivalent to ADD_FAILURE_AT but that
        spawns a fatal failure rather than a non-fatal, eg. the equivalent
        of an ASSERT* failure rather than an EXPECT* failure.
        
        PiperOrigin-RevId: 244746609
        
      - Update README.md
      - Googletest export
        
        Fixes https://github.com/google/googletest/issues/2232
        
        PiperOrigin-RevId: 244237560
        
      - Googletest export
        
        Remove GMock Doctor.
        It has not been actively supported for a while.
        We also now have better techniques to improve compiler errors where needed
        instead of requiring a separate tool to diagnose them.
        
        PiperOrigin-RevId: 244196068
        
      - Googletest export
        
        Expose more information in SuiteApiResolver diagnostic output
        
        PiperOrigin-RevId: 244179347
        
      - Merge pull request #2170 from ngie-eign:issue-2146-ver2
        
        PiperOrigin-RevId: 244069956
        
      - Googletest export
        
        [googletest] Fix death test condition.
        
        PiperOrigin-RevId: 243742424
        
      - Googletest export
        
        Migrate ZX_WAIT_ASYNC_REPEATING to ZX_WAIT_ASYNC_ONCE
        
        ZX_WAIT_ASYNC_REPEATING is deprecated so convert code to use
        ZX_WAIT_ASYNC_ONCE instead.
        
        PiperOrigin-RevId: 243707147
        
      - Merge pull request #2230 from return:style-issue
        
        PiperOrigin-RevId: 243313653
        
      - Sort Haiku platform definition alphabetically.
        
        Fixes a minor ordering issue when defining the platform macro.
        Also fixes a minor typo: 'Max OS X' -> 'Mac OS X'.
        
      - Merge pull request #2226 from davidben:msvc-5046
        
        PiperOrigin-RevId: 243121568
        
      - Merge pull request #2229 from return:haiku-support
        
        PiperOrigin-RevId: 243104604
        
      - Merge pull request #2228 from rongou/patch-2
        
        replace test case with test suite in the primer
      - Add Haiku platform support.
        
        This allows googletest to recognize the Haiku operating system when
        running tests in other projects.
        
      - replace test case with test suite in the primer
      - Merge pull request #2225 from rongou/patch-1
        
        add missing period
      - MSVC C5046 warning is unavailable in MSVC 2015.
        
        Per the MSVC documentation the warning is new as of Visual Studio 2017,
        version 15.8.
        https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c5046?view=vs-2019
        
        GTest users building on MSVC 2015 or older versions of 2017 will, when
        C4616 is enabled, see a warning like:
        
        [...]gtest-matchers.h(53): error C2220: warning treated as error - no 'object' file generated
        [...]gtest-matchers.h(53): warning C4619: #pragma warning: there is no warning number '5046'
        
        Guard the mention of 5046 by an _MSC_VER check. VS2017 15.8 corresponds
        to an _MSC_VER of 1915.
        https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019
        
      - add missing period
      - Update README.md
      - Merge pull request #2222 from Ivaylo-Kirov/patch-1
        
        Update ForDummies.md
      - Update ForDummies.md
      - clang: fix `-Wsign-conversion` errors
        
        Cast some values as their unsigned equivalents or `size_t` to match the
        parameter type used for the template object under test. Also, provide
        UInt32 equivalent delegate methods for some callers (with
        int-equivalents for backwards compatibility).
        
        This closes #2146.
        
        Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>
        
      - Merge pull request #2148 from ngie-eign:clang-add-explicit-c++11-rtti-flag
        
        PiperOrigin-RevId: 242038269
        
      - Googletest export
        
        [fdio] Improve fdio_pipe_half signature, step 3.
        
        The return value on fdio_pipe_half conflated two things: the error code
        on failure (as a zx_status_t) or a file descriptor on success. This
        technically worked, because they're both ints, the error code was always
        negative, and the file descriptor always positive. However, the stated
        return type of zx_status_t was misleading. This changes the signature
        such that it always returns an actual zx_status_t, and the file
        descriptor is returned through a pointer argument.
        
        Also remove the last argument, since it was always given the same value.
        
        This needs to be done as a soft transition because it's called from the
        Dart runtime, from googletest, and from Crashpad, and Crashpad and
        Chromium both depend on googletest on Fuchsia. The steps are as follows:
        1) Add fdio_pipe_half2.
        2) Update Dart to use fdio_pipe_half2.
        3) Update googletest to use fdio_pipe_half2.
        4) Roll updated googletest into Chronium.
        5) Update Crashpad to use fdio_pipe_half2 and roll updated googletest into it.
        6) Update fdio_pipe_half to match fdio_pipe_half2.
        7) Update Dart to use fdio_pipe_half again.
        8) Update googletest to use fdio_pipe_half again.
        9) Roll updated googletest into Chronium.
        10) Update Crashpad to use fdio_pipe_half again and roll updated googletest into it.
        11) Remove fdio_pipe_half2.
        
        This is step 3.
        
        PiperOrigin-RevId: 241957137
        
      - clang: explicitly enable/disable RTTI support with the compiler
        
        Add `-frtti` to the compiler with the base flags case so that RTTI is
        enabled by default with clang. Add its inverse analog,
        `cxx_no_rtti_flags` in order to test the case with RTTI off, similar to
        gcc.
        
        This reduces the amount of testing/support overhead needed in the
        non-RTTI case with clang, as the tests currently fail when these two
        features are off with version 1.8.1. This something I used in when
        investigating test failures on FreeBSD, as the tests that rely on
        RTTI were failing with googletest 1.8.1 on the OS platform.
        
        More investigation is being done to determine how this should be fixed
        on FreeBSD 11.2-RELEASE with ports, as the package doesn't currently
        compile the tests, and when enabled (based on my WIP diff), the tests
        fail in similar ways.
        
        Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>