Update git submodules
* Update platform/superproject from branch 'master'
  to 71be6f8cccaf585ff77ab10e4fb69e3c99fa3de1
  - Update git submodules
    
    * Update system/core from branch 'master'
      to 605eab93c64754ed9e0650ecf20e658d6f7cf023
      - Merge "fs_mgr: overlay: test is alarming on legacy eng builds."
      - fs_mgr: overlay: test is alarming on legacy eng builds.
        
        On taimen-eng build, the test reports:
        
          [  WARNING ] user fastboot missing required to invalidate, ignoring a failure
          ERROR: expected "cat: /vendor/hello: No such file or directory"
                 got "Hello World! Fri Mar 22 08:56:32 PDT 2019"
          [  FAILED  ] vendor content after flash vendor
        
        Which is a result of a corner case problem on devices that need to
        use overlayfs to support adb remount, but do not have fastbootd as
        required by Dynamic Android Partitions (DAP).  These legacy non-DAP
        devices we consider this a Known Issue.
        
        The message however is too alarming when reporting this Known Issue
        that the test has notified you it accepts.  Use standard notification
        output format, and change the result to a series of WARNING instead.
        
        The output would then look like:
        
          [  WARNING ] user fastboot missing required to invalidate, ignoring a failure
          [  WARNING ] expected "cat: /vendor/hello: No such file or directory"
          [  WARNING ] got "Hello World! Fri Mar 22 08:56:32 PDT 2019"
          [  WARNING ] vendor content after flash vendor
        
        Which still tells us there is an issue, but does not cause a state
        of extreme alarm when looking at the test output.
        
        Test: adb-remount-test.sh
        Bug: 120448575
        Bug: 128876541
        Bug: 123079041
        Change-Id: I1d8d60f23f7670ade7eae1be629264f7507e0cfd
        

* Update platform/system/core from branch 'master'
  to 605eab93c64754ed9e0650ecf20e658d6f7cf023
  - Merge "fs_mgr: overlay: test is alarming on legacy eng builds."
  - fs_mgr: overlay: test is alarming on legacy eng builds.
    
    On taimen-eng build, the test reports:
    
      [  WARNING ] user fastboot missing required to invalidate, ignoring a failure
      ERROR: expected "cat: /vendor/hello: No such file or directory"
             got "Hello World! Fri Mar 22 08:56:32 PDT 2019"
      [  FAILED  ] vendor content after flash vendor
    
    Which is a result of a corner case problem on devices that need to
    use overlayfs to support adb remount, but do not have fastbootd as
    required by Dynamic Android Partitions (DAP).  These legacy non-DAP
    devices we consider this a Known Issue.
    
    The message however is too alarming when reporting this Known Issue
    that the test has notified you it accepts.  Use standard notification
    output format, and change the result to a series of WARNING instead.
    
    The output would then look like:
    
      [  WARNING ] user fastboot missing required to invalidate, ignoring a failure
      [  WARNING ] expected "cat: /vendor/hello: No such file or directory"
      [  WARNING ] got "Hello World! Fri Mar 22 08:56:32 PDT 2019"
      [  WARNING ] vendor content after flash vendor
    
    Which still tells us there is an issue, but does not cause a state
    of extreme alarm when looking at the test output.
    
    Test: adb-remount-test.sh
    Bug: 120448575
    Bug: 128876541
    Bug: 123079041
    Change-Id: I1d8d60f23f7670ade7eae1be629264f7507e0cfd