Update git submodules
* Update platform/bionic from branch 'master'
  to b2ced4ca7d6cda9be6d689e0be70e62eb1a3efbc
  - Merge "Modify path for python clang support package"
  - Modify path for python clang support package
    
    Due to commit 594844244237091347b62e8fbbc8a2851258db50 (update
    stable to r468909b) the path for python3-clang support was moved from
       prebuilts/clang/host/linux-x86/clang-stable/lib64/python3/site-packages
    to:
       prebuilts/clang/host/linux-x86/clang-stable/lib/python3/site-packages
    
    Change the imports to point to the correct place.
    
    Without the change:
      Traceback (most recent call last):
        File "bionic/libc/kernel/tools/./clean_header.py", line 72, in <module>
          import sys, cpp, kernel, glob, os, re, getopt
        File "bionic/libc/kernel/tools/cpp.py", line 19, in <module>
          import clang.cindex
      ModuleNotFoundError: No module named 'clang'
    
    Bug: 254401594
    Test: execute clean_headers.py
    Signed-off-by: Pat Tjin <pattjin@google.com>
    Change-Id: Ibf1423fbe78ee009366e26905c4a09e68ac8ff9b