Update git submodules
* Update platform/external/perfetto from branch 'master'
  to 514135fb1a37ba15cf7daad4918e17cfc1724de4
  - Speculative fix of Windows build (take 2)
    
    Remove PERFETTO_EXPORT from ScopedResource as the class
    is fully defined inline and has no symbols.
    This seems to create problems when instantiating it in an
    anonymous namespace on Windows:
    
    From https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket/8828353581767219057/+/u/compile__with_patch_/stdout
    ../../third_party/perfetto/include\perfetto/ext/base/scoped_file.h(54,23): error: 'perfetto::base::ScopedResource<void *, &perfetto::base::ListFilesRecursive(const std::string &, std::vector<std::string> &)::(anonymous class)::__invoke, nullptr, false, perfetto::base::PlatformHandleChecker>' must have external linkage when declared 'dllexport'
    class PERFETTO_EXPORT ScopedResource {
                          ^
    
    Change-Id: I264973225637b60de52fe0d963c1dc1bc7741b75