Update git submodules
* Update platform/cts from branch 'master'
  to de2c2886c6815efeee54bca437b46e8d98834dcd
  - Merge changes I4d86445e,I1890fc23,Iada3a7d3
    
    * changes:
      Allow MethodHandle.invoke/invokeExact to be used in tests
      Reformat cts/tests/signature .bp files
      Explicitly specify test class to run in CtsIntentSignatureTestCases
    
  - Allow MethodHandle.invoke/invokeExact to be used in tests
    
    If LOCAL_MIN_SDK_VERSION is set to less than 26 then attempting to use
    MethodHandle.invoke/invokeExact results in a build error:
    
    Error: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)
    
    That is blocking refactoring of this code.
    
    Also, this ensures that if the minSdkVersion attribute is set in an
    AndroidManifest.xml then the LOCAL_MIN_SDK_VERSION is set to the same
    value in the corresponding build module. See change
    I3883c56394bf9b2b47e97518b57af2d1cb79cb79 for more information.
    
    Test: atest -p cts/tests/signature
    Change-Id: I4d86445ed6d4e89a91c0ca1e0159e49b40808c17
    
  - Reformat cts/tests/signature .bp files
    
    Bug: 131312181
    Test: atest -p cts/tests/signature
    Change-Id: I1890fc23525df603f349e12d7e4c9ffabc9caaa4
    
  - Explicitly specify test class to run in CtsIntentSignatureTestCases
    
    If a test class is not explicitly specified then the test runner will
    scan the classes on the classpath to find the tests. That takes time
    and can lead to spurious warnings and even complete failure of the test
    runner depending on the errors it encounters when processing the
    classes.
    
    Test: atest CtsIntentSignatureTestCases
    Change-Id: Iada3a7d32d9d835ed8882737af88c7ae89179302
    

* Update platform/superproject from branch 'master'
  to 0e7a0aa28de7cfe82ade0cb66bf526b7492a3b1b
  - Update git submodules
    
    * Update cts from branch 'master'
      to de2c2886c6815efeee54bca437b46e8d98834dcd
      - Merge changes I4d86445e,I1890fc23,Iada3a7d3
        
        * changes:
          Allow MethodHandle.invoke/invokeExact to be used in tests
          Reformat cts/tests/signature .bp files
          Explicitly specify test class to run in CtsIntentSignatureTestCases
        
      - Allow MethodHandle.invoke/invokeExact to be used in tests
        
        If LOCAL_MIN_SDK_VERSION is set to less than 26 then attempting to use
        MethodHandle.invoke/invokeExact results in a build error:
        
        Error: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)
        
        That is blocking refactoring of this code.
        
        Also, this ensures that if the minSdkVersion attribute is set in an
        AndroidManifest.xml then the LOCAL_MIN_SDK_VERSION is set to the same
        value in the corresponding build module. See change
        I3883c56394bf9b2b47e97518b57af2d1cb79cb79 for more information.
        
        Test: atest -p cts/tests/signature
        Change-Id: I4d86445ed6d4e89a91c0ca1e0159e49b40808c17
        
      - Reformat cts/tests/signature .bp files
        
        Bug: 131312181
        Test: atest -p cts/tests/signature
        Change-Id: I1890fc23525df603f349e12d7e4c9ffabc9caaa4
        
      - Explicitly specify test class to run in CtsIntentSignatureTestCases
        
        If a test class is not explicitly specified then the test runner will
        scan the classes on the classpath to find the tests. That takes time
        and can lead to spurious warnings and even complete failure of the test
        runner depending on the errors it encounters when processing the
        classes.
        
        Test: atest CtsIntentSignatureTestCases
        Change-Id: Iada3a7d32d9d835ed8882737af88c7ae89179302