Update git submodules
* Update device/generic/vulkan-cereal from branch 'master'
  to 1a777161e9d2ec4281444add4e5c59f406ca34d7
  - Merge "fix gcc8 build error"
  - fix gcc8 build error
    
    error: could not convert ‘{...ommited...}’
    from ‘<brace-enclosed initializer list>’
    to ‘VkSwapchainCreateInfoKHR’
    
    gcc8 failed to convert initializer list
    if any of the fields were missing
    
    Test: compiled:
    export CC=gcc-8 && export CXX=g++-8 && cmake . ../ && make
    
    Change-Id: I606abc065335a882cfbb41543dabd2c1d027d332