Update git submodules
* Update platform/external/gwp_asan from branch 'master'
  to eebf1b5dc4d74f36673f888e032af6050a036728
  - [GWP-ASan] Fix typos.
    
    Summary:
    Fix two spelling typos and de-indent a guarded #define so that it's
    consistent with clang-format.
    
    Reviewers: vitalybuka
    
    Reviewed By: vitalybuka
    
    Subscribers: #sanitizers, llvm-commits
    
    Tags: #sanitizers, #llvm
    
    Differential Revision: https://reviews.llvm.org/D66311
    
    llvm-svn: 369433
    GitOrigin-RevId: 8f5e1755ca385566c0352a9bd292218cebfd3d0b
    Change-Id: I462924f85a40a42cd7507c1c4b16e02e686cda68
    
  - [GWP-ASan] Implement stack frame compression.
    
    Summary:
    This patch introduces stack frame compression to GWP-ASan. Each stack frame is
    variable-length integer encoded as the difference between frame[i] and
    frame[i - 1]. Furthermore, we use zig-zag encoding on the difference to ensure
    that negative differences are also encoded into a relatively small number of
    bytes.
    
    Examples of what the compression looks like can be seen in
    `gwp_asan/tests/compression.cpp`.
    
    This compression can reduce the memory consumption cost of stack traces by
    ~50%.
    
    Reviewers: vlad.tsyrklevich
    
    Reviewed By: vlad.tsyrklevich
    
    Subscribers: mgorny, #sanitizers, llvm-commits, eugenis, morehouse
    
    Tags: #sanitizers, #llvm
    
    Differential Revision: https://reviews.llvm.org/D66189
    
    llvm-svn: 369048
    GitOrigin-RevId: be8a2f75657b27ea113517c3279f0489a7f4018c
    Change-Id: Ie1a070a1ac5f760bb049c3afa29959a1f4e4afa8
    
  - [GWP-ASan] Update backtrace function signature.
    
    Summary:
    Updates the function signature and comments for backtracing (and printing
    backtraces). This update brings GWP-ASan in line with future requirements for
    stack frame compression, wherein the length of the trace is provided
    explicitly, rather than relying on nullptr-termination.
    
    Reviewers: vlad.tsyrklevich
    
    Reviewed By: vlad.tsyrklevich
    
    Subscribers: #sanitizers, llvm-commits, morehouse
    
    Tags: #sanitizers, #llvm
    
    Differential Revision: https://reviews.llvm.org/D66099
    
    llvm-svn: 368619
    GitOrigin-RevId: 352d1b59c0c892f4d642a7355e0dee664bb19479
    Change-Id: I33753753f2cac61fa5c9653a39041e8ab6b1ea90
    
  - Remove a few straggler ".cc"s in compiler-rt/lib
    
    llvm-svn: 367589
    GitOrigin-RevId: 4a1a113a99082914734b78e434a2ffea78a57dc4
    Change-Id: I5f4e2841712073e5d548b1c48656219d68880514
    
  - [GWP-ASan] Add thread ID to PRNG seed.
    
    Summary:
    Adds thread ID to PRNG seed for increased entropy. In particular, this allows
    multiple runs in quick succession that will have different PRNG seeds, allowing
    for better demos/testing.
    
    Reviewers: kcc
    
    Reviewed By: kcc
    
    Subscribers: kubamracek, #sanitizers, llvm-commits
    
    Tags: #sanitizers, #llvm
    
    Differential Revision: https://reviews.llvm.org/D64453
    
    llvm-svn: 366253
    GitOrigin-RevId: b157dcacb5b96fd64900906911832a8ac3bb189e
    Change-Id: I3ec12b36b75c35dd70074f8d6af01ec507ed09ef
    
  - Explicitly define __STDC_FORMAT_MACROS for PRIu64
    
    Summary:
    Builds are failing on RHEL machines because of PRIu64.
    
    lvm/projects/compiler-rt/lib/gwp_asan/guarded_pool_allocator.cpp:420:50: error: expected ')'
    
    `snprintf(ThreadBuffer, kThreadBufferLen, "%" PRIu64, ThreadID);`
    inttypes.h in RHEL uses PRIu64 macros only when __STDC_FORMAT_MACROS is defined.
    
    Author: DTharun
    
    Reviewers: hctim
    
    Reviewed By: hctim
    
    Differential Revision: https://reviews.llvm.org/D64388
    
    llvm-svn: 365801
    GitOrigin-RevId: af3dc759e786324c8a38fa7849da0791b99e67b0
    Change-Id: I13fe1971202c47656cf01a1df71ad4c8d16784df
    
  - [GWP-ASan] Add generic unwinders and structure backtrace output.
    
    Summary:
    Adds two flavours of generic unwinder and all the supporting cruft. If the
    supporting allocator is okay with bringing in sanitizer_common, they can use
    the fast frame-pointer based unwinder from sanitizer_common. Otherwise, we also
    provide the backtrace() libc-based unwinder as well. Of course, the allocator
    can always specify its own unwinder and unwinder-symbolizer.
    
    The slightly changed output format is exemplified in the first comment on this
    patch. It now better incorporates backtrace information, and displays
    allocation details on the second line.
    
    Reviewers: eugenis, vlad.tsyrklevich
    
    Reviewed By: eugenis, vlad.tsyrklevich
    
    Subscribers: srhines, kubamracek, mgorny, cryptoad, #sanitizers, llvm-commits, morehouse
    
    Tags: #sanitizers, #llvm
    
    Differential Revision: https://reviews.llvm.org/D63841
    
    llvm-svn: 364941
    GitOrigin-RevId: 7339ca278c3fdb1d932b776005b2687ec11eadae
    Change-Id: I3fc3255cf5bf6d57a986d18c32080165f975a8a7
    
  - [GWP-ASan] Guard against recursive allocs. Pack TLS for perf.
    
    Summary:
    Add a recursivity guard for GPA::allocate(). This means that any
    recursive allocations will fall back to the supporting allocator. In future
    patches, we will introduce stack trace collection support. The unwinder will be
    provided by the supporting allocator, and we can't guarantee they don't call
    malloc() (e.g. backtrace() on posix may call dlopen(), which may call malloc().
    
    Furthermore, this patch packs the new TLS recursivity guard into a thread local
    struct, so that TLS variables should be hopefully not fall across cache lines.
    
    Reviewers: vlad.tsyrklevich, morehouse, eugenis
    
    Reviewed By: eugenis
    
    Subscribers: kubamracek, #sanitizers, llvm-commits, eugenis
    
    Tags: #sanitizers, #llvm
    
    Differential Revision: https://reviews.llvm.org/D63736
    
    llvm-svn: 364356
    GitOrigin-RevId: 05d1a2bd1bf3c0172334bbdf21cdf97135ab2797
    Change-Id: Icf228a1613e3bb85ad3cabb008a7273e2d0d7270
    
  - Fixup files added in r362636 to build with gcc 5.4. NFCI
    
    llvm-svn: 362682
    GitOrigin-RevId: dbceb9b2203b58f829e911c8d1610b95d9abf192
    Change-Id: I0df203de341f16c39903d8411e7cbd78c1509744
    
  - [GWP-ASan] Core Guarded Pool Allocator [4].
    
    Summary:
    See D60593 for further information.
    
    This patch introduces the core of GWP-ASan, being the guarded pool allocator. This class contains the logic for creating and maintaining allocations in the guarded pool. Its public interface is to be utilised by supporting allocators in order to provide sampled guarded allocation behaviour.
    
    This patch also contains basic functionality tests of the allocator as unittests. The error-catching behaviour will be tested in upcoming patches that use Scudo as an implementing allocator.
    
    Reviewers: vlad.tsyrklevich, eugenis, jfb
    
    Reviewed By: vlad.tsyrklevich
    
    Subscribers: dexonsmith, kubamracek, mgorny, cryptoad, jfb, #sanitizers, llvm-commits, morehouse
    
    Tags: #sanitizers, #llvm
    
    Differential Revision: https://reviews.llvm.org/D62872
    
    llvm-svn: 362636
    GitOrigin-RevId: a95edb9dc1ddaf70761e8c90be175f144a28f757
    Change-Id: I1853eaf86da8fb14bbd2bcfac5e64aa16ff5f06f
    
  - [GWP-ASan] Configuration options [3].
    
    Summary:
    See D60593 for further information.
    
    This patch introduces the configuration options for GWP-ASan. In general, we expect the supporting allocator to populate the options struct, and give that to GWP-ASan during initialisation. For allocators that are okay with pulling in sanitizer_common, we also provide an optional parser that populates the gwp_asan::Options struct with values provided in the GWP_ASAN_OPTIONS environment variable.
    
    This patch contains very little logic, and all of the testable components (i.e. the optional parser's internal logic) is tested as part of the sanitizer_common testbed.
    
    Reviewers: vlad.tsyrklevich, morehouse, jfb
    
    Reviewed By: morehouse
    
    Subscribers: dexonsmith, kubamracek, mgorny, #sanitizers, llvm-commits, vitalybuka
    
    Tags: #sanitizers, #llvm
    
    Differential Revision: https://reviews.llvm.org/D62698
    
    llvm-svn: 362527
    GitOrigin-RevId: 2133daf232c5ee8f9cee5662e5b31f584992d3a6
    Change-Id: I9e33b14f3d11c702d5e1b99ca79e1ee0ba67d2cc
    
  - Attempt to fix test failure for armv8.
    
    Looks like armv8 can't handle a thousand threads, which GWP-ASan
    requests when running a synchronised mutex test. Limiting this to 100 to
    attempt to fix the build issue.
    
    llvm-svn: 362163
    GitOrigin-RevId: 365e59248056e8ba24848a5857117b01a066ef68
    Change-Id: Id6374d3fea1d6f711c0c5b5154bacabe04f3e043
    
  - Attempt to fix 'mutex.h' not found when building mutex_posix.
    
    llvm-svn: 362149
    GitOrigin-RevId: 9bd9a03ad04cc2377e5443c834b1af3f42617a39
    Change-Id: Ib217fdf7f97ac8eb43a2264124eb8e54630b8fbc
    
  - [GWP-ASan] Mutex implementation [2].
    
    Summary:
    See D60593 for further information.
    This patch pulls out the mutex implementation and the required definitions file.
    
    We implement our own mutex for GWP-ASan currently, because:
    
    1. We must be compatible with the sum of the most restrictive elements of the supporting allocator's build system. Current targets for GWP-ASan include Scudo (on Linux and Fuchsia), and bionic (on Android).
    2. Scudo specifies `-nostdlib++ -nonodefaultlibs`, meaning we can't use `std::mutex` or `mtx_t`.
    3. We can't use `sanitizer_common`'s mutex, as the supporting allocators cannot afford the extra maintenance (Android, Fuchsia) and code size (Fuchsia) overheads that this would incur.
    
    In future, we would like to implement a shared base mutex for GWP-ASan, Scudo and sanitizer_common. This will likely happen when both GWP-ASan and Scudo standalone are not in the development phase, at which point they will have stable requirements.
    
    Reviewers: vlad.tsyrklevich, morehouse, jfb
    
    Reviewed By: morehouse
    
    Subscribers: dexonsmith, srhines, cfe-commits, kubamracek, mgorny, cryptoad, jfb, #sanitizers, llvm-commits, vitalybuka, eugenis
    
    Tags: #sanitizers, #llvm, #clang
    
    Differential Revision: https://reviews.llvm.org/D61923
    
    llvm-svn: 362138
    GitOrigin-RevId: 5f0f4e3ae03afa84034c01ddaac559e0b5cb6532
    Change-Id: Ic069ffb69d84da1b9aa020a161f0224f78aab6f0
    
  - [GWP-ASan] Fixed issue with c++ standard library dependency.
    
    Summary:
    Removed dependency on c++ standard library. Some supporting allocators (namely Scudo on Fuchsia, and shortly, scudo standalone) has a hard requirement of no c++stdlib.
    
    This patch updates the build system so that we don't have any c++ stdlib dependencies. It also will conveniently fix a racy build-order bug discrepency between GWP-ASan and libc++.
    
    Reviewers: phosek, morehouse
    
    Reviewed By: phosek, morehouse
    
    Subscribers: kubamracek, mgorny, cryptoad, #sanitizers, llvm-commits, beanz, smeenai, vitalybuka
    
    Tags: #sanitizers, #llvm
    
    Differential Revision: https://reviews.llvm.org/D62048
    
    llvm-svn: 360982
    GitOrigin-RevId: 364f662fa3f31d262ce5b28065490bc4dceebaac
    Change-Id: I58a84b457614902f8747e64cc278140bc00ab5b5
    
  - [GWP-ASan] Initial build files, implementation of PRNG [1].
    
    Summary:
    See D60593 for further information.
    This patch slices off the PRNG implementation and the initial build files for GWP-ASan.
    
    Reviewers: vlad.tsyrklevich, morehouse, vitalybuka
    
    Reviewed By: morehouse
    
    Subscribers: srhines, kubamracek, mgorny, #sanitizers, llvm-commits, cryptoad, eugenis
    
    Tags: #sanitizers, #llvm
    
    Differential Revision: https://reviews.llvm.org/D61867
    
    llvm-svn: 360710
    GitOrigin-RevId: c9dd299736add73d576b5f005116cc470bf02977
    Change-Id: I3ebee445c016a530c3816a5c4b815f5b2ef339ea
    
  - Fix typos throughout the license files that somehow I and my reviewers
    all missed!
    
    Thanks to Alex Bradbury for pointing this out, and the fact that I never
    added the intended `legacy` anchor to the developer policy. Add that
    anchor too. With hope, this will cause the links to all resolve
    successfully.
    
    llvm-svn: 351731
    GitOrigin-RevId: 4a1b95bda0c444798a5240fe924dd127b776d12d
    Change-Id: I771d5c087359296aa6d9fdb3439ab604e65c4c1d
    
  - Install new LLVM license structure and new developer policy.
    
    This installs the new developer policy and moves all of the license
    files across all LLVM projects in the monorepo to the new license
    structure. The remaining projects will be moved independently.
    
    Note that I've left odd formatting and other idiosyncracies of the
    legacy license structure text alone to make the diff easier to read.
    Critically, note that we do not in any case *remove* the old license
    notice or terms, as that remains necessary until we finish the
    relicensing process.
    
    I've updated a few license files that refer to the LLVM license to
    instead simply refer generically to whatever license the LLVM project is
    under, basically trying to minimize confusion.
    
    This is really the culmination of so many people. Chris led the
    community discussions, drafted the policy update and organized the
    multi-year string of meeting between lawyers across the community to
    figure out the strategy. Numerous lawyers at companies in the community
    spent their time figuring out initial answers, and then the Foundation's
    lawyer Heather Meeker has done *so* much to help refine and get us ready
    here. I could keep going on, but I just want to make sure everyone
    realizes what a huge community effort this has been from the begining.
    
    Differential Revision: https://reviews.llvm.org/D56897
    
    llvm-svn: 351631
    GitOrigin-RevId: 469bdefd448b76c5adcdd67256e9a44fabf7e027
    Change-Id: If73a9bbb7f3118f161385c5bf9e92edddafd9add
    
  - Update year in license files
    
    In last year's update (D48219) it was suggested that the release manager
    might want to do this, so here we go.
    
    llvm-svn: 351194
    GitOrigin-RevId: eb60fbfdb43cb8583eda1e338b3489ddef332f10
    Change-Id: Icb9ded2860a380524f627f0f3f872f7b145e2e57
    
  - Update copyright year to 2018.
    
    llvm-svn: 334936
    GitOrigin-RevId: 7555c589af006c9c4d171794200753d0e92ef946
    Change-Id: Ib32362be171719188734d196c4d3d13df25eb5a4
    
  - Update copyright year to 2016.
    
    llvm-svn: 264948
    GitOrigin-RevId: d993522d289e73808984a06abaf725eefae5defa
    Change-Id: I44943980f9ef0c865e9930077895dd14b2cebe58
    
  - Update copyright year to 2015.
    
    llvm-svn: 232089
    GitOrigin-RevId: 59c57cd89b617d06d6d7bae9f3964c972470c1a1
    Change-Id: I0cf01f45f8a6f27610abced6018c3f623e61d154
    
  - Move Android ucontext.h out of third_party.
    
    Google is re-licensing this code under the standard dual license of
    compiler-rt.
    
    llvm-svn: 204128
    GitOrigin-RevId: 0b5b3295e521e266ded60099c1e067120cd2ffaa
    Change-Id: Ie531cab1fa49d51d5de316ca7ea8fa1c96f94959
    
  - Update license.txt to point to the new code in third_party/android.
    
    Also remove a reference to mach_override code that is long gone.
    
    llvm-svn: 201510
    GitOrigin-RevId: fba430d2997536da822f6ee83501577a04d2e036
    Change-Id: I29db5b99b23afecac5c76ef76229a6cdec50d6a5
    
  - Update the copyright credits -- Happy new year 2014!
    
    FIXME: Dragonegg may be updated at non-trivial changes.
    llvm-svn: 198274
    GitOrigin-RevId: d40d387fb11b5ae1a82296fcca6b9798b96a0c1a
    Change-Id: I13732971826a251716902ef0a288301693361df9
    
  - Update the copyright coredits -- Happy new year 2013!
    
    llvm-svn: 171342
    GitOrigin-RevId: 43632a26a5da8568525193ee80e544cb57efa675
    Change-Id: I9c8774cf52950d7a398df1d40492585c62dfbfe0
    
  - [asan] move lib/asan/interception to lib/interception so that other tools (e.g. tsan) can use it
    
    llvm-svn: 156816
    GitOrigin-RevId: 1dd4c606ed055bccc1fd94004cc20074b16592de
    Change-Id: I92161ecb737cd0ad7762c6eb9ff5d18a9a6a0a2e
    
  - Update source code links in LICENSE.TXT.
    
    mach_override has been moved to a different path.
    sysinfo is gone.
    
    llvm-svn: 151148
    GitOrigin-RevId: d179ec614eebb0cb57108e9c01fd456ed82cbad6
    Change-Id: I3f5b8e4249ebc9d4f85f64f29bff983b4907cdef
    
  - Happy new year 2012!
    
    llvm-svn: 147395
    GitOrigin-RevId: e9d3d21988603592864d76dab5e4ccb09f355ec9
    Change-Id: Ic3872e573a398894087fc30e243011c018942e14