Update git submodules
* Update platform/external/googletest from branch 'master'
  to b1a925fc62f985f610476bafd127eda4599b7746
  - Merge commit 'f5e592d8ee5ffb1d9af5be7f715ce3576b8bf9c4' into update
    
    Change-Id: I6568c7bcb74e84fe3753ecea2e791439dccb12f3
    
  - Googletest export
    
    Revert https://github.com/google/googletest/commit/ac3c2a8d0496893787015014a5abd397b766cce2 -- it seems to break some gcc users (#3384)
    
    PiperOrigin-RevId: 370834917
    
  - Googletest export
    
    Clean up links to Matchers Reference
    
    PiperOrigin-RevId: 370821457
    
  - Googletest export
    
    Move matchers reference from cheat sheet into its own document
    
    PiperOrigin-RevId: 370749693
    
  - Googletest export
    
    Update the `DescribeTo` signature in the code example at the Writing New Polymorphic Matchers section in gmock_cook_book.
    
    `os` should be a pointer to be consistent with the implementation, which dereference it as `*os`.
    
    PiperOrigin-RevId: 370693387
    
  - Googletest export
    
    internal change
    
    PiperOrigin-RevId: 370503556
    
  - Googletest export
    
    Fix iOS logging issues in tests
    
    PiperOrigin-RevId: 370484087
    
  - Merge pull request #3174 from sebkraemer:issue-15644
    
    PiperOrigin-RevId: 369696657
    
  - Merge pull request #3314 from Vollstrecker:master
    
    PiperOrigin-RevId: 369550590
    
  - Googletest export
    
    This callsite was previously updated to use ZX_INFO_PROCESS_V2 as a part of a soft transition. It is now time to revert back to `ZX_INFO_PROCESS` (which is now an alias of the former). See fxbug.dev/30751 for more details.
    
    PiperOrigin-RevId: 369370855
    
  - Googletest export
    
    This callsite was previously updated to use ZX_INFO_PROCESS_V2 as a part of a soft transition. It is now time to revert back to `ZX_INFO_PROCESS` (which is now an alias of the former). See fxbug.dev/30751 for more details.
    
    PiperOrigin-RevId: 369349579
    
  - Merge pull request #3364 from jbampton:fix-spelling
    
    PiperOrigin-RevId: 369217358
    
  - Use URL instead of git-repo
  - Googletest export
    
    Use the time_point from steady_clock instead of the template
    This fixes the build on some embedded compilers
    
    PiperOrigin-RevId: 368879480
    
  - Googletest export
    
    Fix -Wconversion issues on Fuchsia
    
    PiperOrigin-RevId: 368520510
    
  - Apply missing suggestions from code review for GTEST_SKIP
    
    Co-authored-by: Eric Schmidt <shibumi@google.com>
  - Apply suggestions from code review for GTEST_SKIP documentation
    
    Extended example and some rewording by @ericschmidtatwork, thank you.
    
    Co-authored-by: Eric Schmidt <shibumi@google.com>
  - Add subsection for GTEST_SKIP documentation
    
    A subsection "Skipping test execution" was added to document GTEST_SKIP
    and where it can be used.
    
    relates issue #1544
    
  - chore: fix spelling
    
  - Mention to explicitely set the option to it's default.
  - Googletest export
    
    Remove AppVeyor configuration.
    Windows is now tested on Kokoro.
    
    PiperOrigin-RevId: 368471950
    
  - Changes like Requested.
  - Googletest export
    
    Add support to run gtest on Xtensa platform.
    
    This add support to run GTest base test suits on Xtensa
    (https://ip.cadence.com/ipportfolio/tensilica-ip) base simulator.
    Xtensa only provides libc and some basic operations and does not run an
    operating system by default.
    
    PiperOrigin-RevId: 368162205
    
  - Googletest export
    
    Adds a warning about anonymous namespaces in relation to private testing.
    
    PiperOrigin-RevId: 367730808
    
  - Googletest export
    
    Update docs to point to the github.io pages.
    
    PiperOrigin-RevId: 367711335
    
  - Merge pull request #3158 from GauthamBanasandra:patch-1
    
    PiperOrigin-RevId: 367681693
    
  - Googletest export
    
    Generalize root directory in CI scripts
    
    PiperOrigin-RevId: 367628939
    
  - Merge pull request #3319 from a-sully:patch-1
    
    PiperOrigin-RevId: 367509099
    
  - Googletest export
    
    Update the example for Notify to use a lambda.
    It is much less boilerplate and easier to remember.
    
    PiperOrigin-RevId: 367284222
    
  - Googletest export
    
    Docs: Add examples for `FieldsAre` matcher
    PiperOrigin-RevId: 367263024
    
  - Googletest export
    
    Migrate away from deprecated --heap_check=strict
    
    PiperOrigin-RevId: 367226846
    
  - Googletest export
    
    This is part of a soft transition over to having ZX_INFO_PROCESS
    populate a new struct. See fxbug.dev/30751 for more details.
    
    PiperOrigin-RevId: 367083068
    
  - Googletest export
    
    Docs: Clarifying matcher in `Pointwise` and `UnorderedPointwise`
    PiperOrigin-RevId: 367059198
    
  - Googletest export
    
    Disable blank issue template, delete question template
    
    PiperOrigin-RevId: 366874747
    
  - Googletest export
    
    Add macros to omit {EXPECT,ASSERT}_{TRUE,FALSE}
    
    PiperOrigin-RevId: 366455905
    
  - Merge pull request #3155 from ZedThree:cmake-alias-libraries
    
    PiperOrigin-RevId: 365572439
    
  - Googletest export
    
    Delete extra whitespace in gtest_xml_test_utils.py
    
    PiperOrigin-RevId: 365140844
    
  - Googletest export
    
    Clarify explanation of mocking free functions
    
    PiperOrigin-RevId: 364943561
    
  - Googletest export
    
    Minor formatting updates
    
    PiperOrigin-RevId: 364935205
    
  - Googletest export
    
    Code style cleanup in docs
    
    PiperOrigin-RevId: 364907938
    
  - Googletest export
    
    Update advanced.md
    
    PiperOrigin-RevId: 364839958
    
  - Googletest export
    
    Update explanation of `EXPECT_EQ(NULL, ptr)` in FAQ
    
    PiperOrigin-RevId: 364626422
    
  - Googletest export
    
    Code style cleanups in cheat sheet
    
    PiperOrigin-RevId: 364465553
    
  - Googletest export
    
    Add CMake quickstart
    
    PiperOrigin-RevId: 364437779
    
  - Googletest export
    
    Add Bazel quickstart
    
    PiperOrigin-RevId: 364419540
    
  - Googletest export
    
    Print std::u8string, std::u16string, and std::u32string as string literals
    
    Previously, these types were printed as "{ U+123, U+456, U+789 }". However,
    printed output in that form is difficult to compare against any literals that
    might be defined in code. Instead, just treat these types like std::string
    and std::wstring, escaping non-ASCII characters with a hexadecimal escape
    sequence.
    
    The tests have also been updated to cover the new functionality: as a bonus,
    the tests now also pass with the MSVC toolchain.
    
    Internally, the code has been reorganized to primarily operate in terms of
    char32_t, under the assumption that char32_t will always be at least as big
    as wchar_t. While that assumption is currently true, perhaps it won't be in
    the future...
    
    PiperOrigin-RevId: 364033132
    
  - Merge pull request #3315 from zaucy:master
    
    PiperOrigin-RevId: 363176008
    
  - Update nicestrictnaggy gmock cook_book links
    
    An incorrect link is output to the user when these conditions are met.
  - Merge pull request #3291 from Be-ing:remove_zi_msvc
    
    PiperOrigin-RevId: 363063211
    
  - Googletest export
    
    gtest: Output a canned test suite for environment failures in XML/JSON
    
    This surfaces useful information about the environment failure in a structured form.
    
    As we can see from the updated test, previously unsurfaced information is now present.
    
    PiperOrigin-RevId: 362292322
    
  - Internal change
    
    PiperOrigin-RevId: 362216935
    
  - Googletest export
    
    Update CONTRIBUTING link in README
    
    PiperOrigin-RevId: 362141000
    
  - Googletest export
    
    Internal change
    
    PiperOrigin-RevId: 362040448
    
  - Use @platforms instead of @bazel_tools for windows constraint
    
  - Use Fetchcontent instead of ExternalProject
    
    Hi,
    
    instead of ExternalProject and a new file that is spawned in a new process, it's easier to just use FetchContent. cmake 3.14 should be old enough to be spread.
  - Googletest export
    
    Add missing period and use "that" in restrictive clause.
    
    PiperOrigin-RevId: 361941663
    
  - Googletest export
    
    Update READMEs and issue template
    
    PiperOrigin-RevId: 361931644
    
  - Googletest export
    
    Use monotonic time to measure test duration
    
    System time may be updated while a test is running. When this occurs a
    duration measured using system time may appear to move backwards, or
    jump far forwards.
    This change updates the duration measurement to use monotonic time
    instead. Timestamps for the test start still use system time.
    
    PiperOrigin-RevId: 361700881
    
  - Googletest export
    
    gtest.cc: Split out functions for printing `TestResult` objects
    
    This will make it possible to reuse this code for outputting the "ad_hoc" `TestResult` objects in structured form in XML/JSON.
    
    PiperOrigin-RevId: 361604860
    
  - Internal change
    
    PiperOrigin-RevId: 361213113
    
  - Merge pull request #3184 from N-Dekker:PrintTo-type_index-overload
    
    PiperOrigin-RevId: 361175466
    
  - Googletest export
    
    Add CI test scripts
    
    PiperOrigin-RevId: 360931988
    
  - Googletest export
    
    Format WORKSPACE and googlemock/test/BUILD.bazel using buildifier
    
    PiperOrigin-RevId: 360913861
    
  - Googletest export
    
    Fix enum names in a value-parameterized test example.
    
    PiperOrigin-RevId: 360559723
    
  - Googletest export
    
    Add Supported Platforms page to docs
    
    PiperOrigin-RevId: 360307129
    
  - Googletest export
    
    Update gtest doc link
    
    PiperOrigin-RevId: 359622286
    
  - Googletest export
    
    Update links in index.md
    
    PiperOrigin-RevId: 358956598
    
  - remove -Zi from MSVC compiler options
    
    This is incompatible with compiler caches such as sccache and
    clcache. If a project including Google Test specifies /Z7 instead,
    building fails with:
    
    sccache C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x64\cl.exe  /nologo /TP -D__SSE2__ -D__SSE__ -I..\lib\googletest-1.10.x\googlemock\include -I..\lib\googletest-1.10.x\googlemock -I..\lib\googletest-1.10.x\googletest\include -I..\lib\googletest-1.10.x\googletest /DWIN32 /D_WINDOWS /W4 /GR  /MD /Z7 /O2 /Ob1 /DNDEBUG -GS -W4 -WX -wd4251 -wd4275 -nologo -J -Zi -D_UNICODE -DUNICODE -DWIN32 -D_WIN32 -DSTRICT -DWIN32_LEAN_AND_MEAN -wd4702 -DGTEST_HAS_PTHREAD=0 -EHsc -D_HAS_EXCEPTIONS=1  /Gy /showIncludes /Folib\googletest-1.10.x\googlemock\CMakeFiles\gmock_main.dir\src\gmock-all.cc.obj /Fdbin\gmock_main.pdb /FS -c ..\lib\googletest-1.10.x\googlemock\src\gmock-all.cc
    FAILED: lib/googletest-1.10.x/googlemock/CMakeFiles/gmock_main.dir/src/gmock-all.cc.obj
    ..\lib\googletest-1.10.x\googletest\src\gtest-all.cc: fatal error C1041: cannot open program database 'D:\a\mixxx\mixxx\build\bin\gmock_main.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
    cl : Command line warning D9025 : overriding '/Z7' with '/Zi'
    
  - overload PrintTo for std::type_info and std::type_index
    
    Included the string returned by their `name()` member function with the output of `PrintTo`.
    
    Typical use case:
    
        std::unique_ptr<AbstractProduct> product = FactoryMethod();
        // Assert that the product is of type X:
        ASSERT_EQ(std::type_index{typeid(*product)},
                  std::type_index{typeid(ProductX)});
    
    Possible output in case of a test assert failure, now including the names of the compared type indices:
    
    > error: Expected equality of these values:
    >  std::type_index(typeid(*product))
    >    Which is: 8-byte object <D0-65 54-8C F6-7F 00-00> ("class ProductY")
    >  std::type_index(typeid(ProductX))
    >    Which is: 8-byte object <40-64 54-8C F6-7F 00-00> ("class ProductX")
    
    With help from Krystian Kuzniarek.
    
  - Googletest export
    
    Remove anchors from page titles in docs
    
    PiperOrigin-RevId: 358474917
    
  - Googletest export
    
    Add files for GitHub Pages
    
    PiperOrigin-RevId: 358289110
    
  - Googletest export
    
    Explicitly skip tests after fatal global environment setup errors
    
    Previously the tests were all skipped, but the resulting output claimed all
    tests passed.
    
    Before:
    ```
    [----------] Global test environment set-up.
    <failure message>
    [----------] Global test environment tear-down
    [==========] 1 test from 1 test suite ran. (83 ms total)
    [  PASSED  ] 1 test.
    [  FAILED  ] 0 tests, listed below:
    ```
    
    After:
    ```
    [==========] Running 1 test from 1 test suite.
    [----------] Global test environment set-up.
    <failure message>
    [----------] 1 test from SomeTest
    [ RUN      ] SomeTest.DoesFoo
    <...>: Skipped
    [  SKIPPED ] SomeTest.DoesFoo (0 ms)
    [----------] 1 test from SomeTest (0 ms total)
    
    [----------] Global test environment tear-down
    [==========] 1 test from 1 test suite ran. (68 ms total)
    [  PASSED  ] 0 tests.
    [  SKIPPED ] 1 test, listed below:
    [  SKIPPED ] SomeTest.DoesFoo
    [  FAILED  ] 0 tests, listed below:
    ```
    
    PiperOrigin-RevId: 358026389
    
  - Googletest export
    
    Explain how to wrap matchers.
    
    PiperOrigin-RevId: 357901293
    
  - Googletest export
    
    Update stale links to `gmock_cook_book.md`.
    
    I'm a new googletest user and found these links broken when reading the documentation.
    
    PiperOrigin-RevId: 357786392
    
  - Googletest export
    
    Update the custom name example to not use underscores.
    
    The NOTE a few blocks above specifically calls out that test names should not contain undersccores, so probably the example should not suggest using underscores.
    
    PiperOrigin-RevId: 357204578
    
  - Googletest export
    
    Add files for GitHub Pages
    
    PiperOrigin-RevId: 357096486
    
  - Googletest export
    
    Add issue templates
    
    PiperOrigin-RevId: 357075859
    
  - Googletest export
    
    Make include guards conform with https://google.github.io/styleguide/cppguide.html#The__define_Guard, attempt #2
    
    PiperOrigin-RevId: 357056902
    
  - Googletest export
    
    Internal change
    
    PiperOrigin-RevId: 356867746
    
  - Fix typo
  - CMake: Add namespaced ALIAS library
    
    Fixes #3125