Update git submodules
* Update platform/external/expat from branch 'master'
  to 4871ef19816cdfb503f12d1ba352e119b12f9f8a
  - Merge "Upgrade expat to R_2_4_9"
  - Upgrade expat to R_2_4_9
    
    Bug: http://b/247233670
    
    Test: Treehugger
    Change-Id: Ia34bdb2215a7effb231c26421d26bc3a2169510a
    
  - Merge pull request #644 from libexpat/issue-642-release-2-4-9
    
    Prepare release 2.4.9 (part of #642)
  - Set release date for version 2.4.9
    
  - Bump version to 2.4.9
    
  - Bump version info from 9:8:8 to 9:9:8
    
    See https://verbump.de/ for what these numbers do
    
  - Changes: Document #592 #593 #594 #614 #619 #627 #633 #635 #636 #637
    
  - Sync file headers
    
  - Resolve use of deprecated "fgrep" by "grep -F"
    
    Related:
    https://lists.gnu.org/archive/html/info-gnu/2022-09/msg00001.html
    
  - win32/build_expat_iss.bat: Add -DEXPAT_WARNINGS_AS_ERRORS=ON
    
  - Merge pull request #643 from libexpat/clang-15
    
    Upgrade Clang from 14 to 15
  - Actions: Upgrade Clang from 14 to 15
    
  - tests: Address Clang 15 warning -Wstrict-prototypes
    
    Symptom was:
    error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
    
  - Merge pull request #640 from libexpat/issue-629-heap-use-after-free
    
    [CVE-2022-40674] tests: Cover heap use-after-free issue in doContent (follow-up to #629)
  - Changes: Document heap use-after-free CVE-2022-40674
    
  - tests: Cover heap use-after-free issue in doContent
    
  - Merge pull request #641 from libexpat/issue-626-static-library-symbol-visibility
    
    Stop exporting API symbols when building a static library (fixes #626)
  - Stop exporting API symbols when building a static library
    
  - Merge pull request #629 from RMJ10/missing-store-raw
    
    Ensure raw tagnames are safe exiting internalEntityParser
  - Merge pull request #627 from libexpat/issue-597-cmake-migrate-set-cache-to-option
    
    CMake: Unify inconsistent use of set() and option() (related to #597)
  - cmake: Mark _EXPAT_M32 and EXPAT_*_POSTFIX as advanced
    
  - cmake: Unify set(var default CACHE type desc) and option(var desc default)
    
    .. into expat_shy_set(var default CACHE type desc).
    
    Note that this new macro is intended to be used for all future options.
    Also, because we are no longer using plain option(), wheter policy CMP0077
    is active in mode OLD or NEW is no longer of importance.
    Hence the code related to CMP0077 could could be dropped.
    
  - Merge pull request #632 from libexpat/github-actions-off-deprecated-ubuntu-18-04
    
    Get GitHub Actions CI off deprecated Ubuntu 18.04
  - Changes: Briefly document infra work
    
  - GitHub Actions: Pin remaining unpinned ubuntu-latest
    
  - GitHub Actions: Stop installing Clang when not used
    
  - GitHub Actions: Avoid Ubuntu 20.04 for coverage collection
    
    .. because its MinGW GCC 9.3.0 fails to create any .gcda files
    at test runtime (while that works just fine on 18.04 and 22.04).
    
  - coverage.sh|qa.sh: Fix copying of DLLs for Wine/MinGW for Ubuntu 22.04
    
    Ubuntu 22.04 no longer has libgcc_s_sjlj-1.dll but needs
    libgcc_s_dw2-1.dll now, instead.
    
  - GitHub Actions: Fix installation of 32bit Wine on Ubuntu 20.04
    
    Same approach as https://github.com/uriparser/uriparser/pull/144
    
  - GitHub Actions: Get off deprecated Ubuntu 18.04
    
  - cmake: Avoid error "windres: Command not found" with MinGW on Ubuntu 20.04
    
    Related:
    https://gitlab.kitware.com/cmake/cmake/-/issues/20500#note_720469
    
  - Merge pull request #636 from neheb/patch-1
    
    CMake: Drop leading whitespace from a #cmakedefine line in file expat_config.h.cmake to workaround issues with Meson
  - Merge pull request #637 from neheb/cl
    
    apply-clang-format.sh: Add support for BSD find
  - Merge pull request #638 from libexpat/fix-xmltest-log-sh-drop-more-wine-bug-output
    
    fix-xmltest-log.sh: Drop more Wine bug output
  - fix-xmltest-log.sh: Drop more Wine bug output
    
  - Merge pull request #635 from libexpat/coverage-sh-fix-name-collision
    
    coverage.sh: Fix name collision for -funsigned-char
  - remove leading whitespace from config file
    
    meson has a bug where #cmakedefine with leading whitespace is not transformed.
    
  - apply-clang-format: add support for BSD find
    
    Found with shellcheck:
    
    SC2185: Some finds don't have a default path. Specify '.' explicitly.
    
    Signed-off-by: Rosen Penev <rosenp@gmail.com>
    
  - Merge pull request #634 from libexpat/fix-mingw-compilation
    
    lib: Fix compilation for -D__USE_MINGW_ANSI_STDIO=0
  - coverage.sh: Fix name collision for -funsigned-char
    
  - lib: Fix compilation for -D__USE_MINGW_ANSI_STDIO=0
    
  - Merge pull request #633 from libexpat/coverage-sh-exclude-mingw-headers
    
    coverage.sh: Exclude MinGW headers
  - coverage.sh: Exclude MinGW headers (stdio.h and stdlib.h)
    
  - coverage.sh: Inline exclusion patterns (for upcoming change)
    
  - File expat/fuzz/.gitignore changed to not ignore already-committed source files (fixes #630) (#631)
    
    
  - Ensure raw tagnames are safe exiting internalEntityParser
    
    It is possible to concoct a situation in which parsing is
    suspended while substituting in an internal entity, so that
    XML_ResumeParser directly uses internalEntityProcessor as
    its processor.  If the subsequent parse includes some unclosed
    tags, this will return without calling storeRawNames to ensure
    that the raw versions of the tag names are stored in memory other
    than the parse buffer itself.  If the parse buffer is then changed
    or reallocated (for example if processing a file line by line),
    badness will ensue.
    
    This patch ensures storeRawNames is always called when needed
    after calling doContent.  The earlier call do doContent does
    not need the same protection; it only deals with entity
    substitution, which cannot leave unbalanced tags, and in any
    case the raw names will be pointing into the stored entity
    value not the parse buffer.
    
  - Merge pull request #625 from libexpat/autotools-sync-cmake-files
    
    Autotools: Get CMake templates back in sync with CMake of GitHub Actions image "ubuntu-20.04"
  - Changes: Document past Autotools Cmake template adjustments in more detail
    
  - autotools: Sync CMake templates with CMake 3.22
    
  - Merge pull request #624 from libexpat/issue-622-mingw-cmake-dll-filename
    
    CMake: Produce libexpat-1.dll with MinGW in line with GNU Autotools (fixes #622)
  - cmake: Produce libexpat-1.dll with MinGW in line with GNU Autotools
    
  - Merge pull request #621 from libexpat/issue-512-windows-render-def-files-from-template
    
    CMake: Render .def file from a template to fix linking (fixes #512) + apply .def file with MinGW
  - cmake: Apply .def file when linking with MinGW
    
  - cmake|windows: Render .def file from a template to fix linking
    
    .. with -DEXPAT_DTD=OFF and/or -DEXPAT_ATTR_INFO=ON .
    
  - Merge pull request #620 from libexpat/cmake-improve-documentation-on-variables
    
    CMake: Improve documentation on variables
  - Merge pull request #611 from neheb/def
    
    Fix .def files syntax for MinGW
  - Merge pull request #614 from Tieske/minor
    
    fix(docs) update XML_DTD symbol visibility
  - Changes: Document #608 and #620
    
  - readme: Get CMake variables documentation back in sync
    
  - cmake: Make all variable documentation start with a capital letter
    
  - cmake: Improve documentation of variables EXPAT_*_POSTFIX
    
  - cmake: Fix a CMAKE_*_POSTFIX leftover from pull request #608
    
  - Merge pull request #619 from libexpat/actions-get-off-deprecated-macos-10-15
    
    Actions: Get off deprecated macos-10.15
  - Merge pull request #608 from dfaure-kdab/master
    
    CMake: Set target properties *_POSTFIX instead of global vars CMAKE_*_POSTFIX
  - actions: Be explicit about macos-11
    
  - actions: Migrate from deprecated macos-10.15 to macos-11
    
  - Set target properties *_POSTFIX instead of global vars CMAKE_*_POSTFIX
    
    This fixes unwanted side effects when libexpat is used with FetchContent
    in another cmake-based project. Setting CMAKE_*_POSTFIX affects the
    whole project, while here we only want to define the postfix for libexpat
    itself.
    
  - fix(docs) update XML_DTD symbol visibility
    
  - expat: fix def files for MinGW
    
    MinGW expects a populated LIBRARY field. Alternatively it can just be
    removed.
    
    Signed-off-by: Rosen Penev <rosenp@gmail.com>
    
  - Merge pull request #610 from libexpat/address-cppcheck-2-8-1-warning
    
    lib: Address Cppcheck 2.8.1 warning / fix CI
  - lib: Address Cppcheck 2.8.1 warning
    
    expat/lib/xmlparse.c:4288:21: error: Uninitialized variable: &versionend [uninitvar]
              &version, &versionend, &encodingName, &newEncoding, &standalone)) {
                        ^
    
  - Merge pull request #609 from libexpat/issue-585-license-file
    
    Add /COPYING file + sync file headers (fixes #585)
  - COPYING: cp expat/COPYING ./
    
  - Sync file headers
    
  - .mailmap: Add Martin Ettl
    
  - Merge pull request #603 from libexpat/dependabot/github_actions/actions/upload-artifact-3.1.0
    
    Actions(deps): Bump actions/upload-artifact from 3.0.0 to 3.1.0
  - Actions(deps): Bump actions/upload-artifact from 3.0.0 to 3.1.0
    
    Bumps [actions/upload-artifact](https://github.com/actions/upload-artifact) from 3.0.0 to 3.1.0.
    - [Release notes](https://github.com/actions/upload-artifact/releases)
    - [Commits](https://github.com/actions/upload-artifact/compare/v3.0.0...v3.1.0)
    
    ---
    updated-dependencies:
    - dependency-name: actions/upload-artifact
      dependency-type: direct:production
      update-type: version-update:semver-minor
    ...
    
    Signed-off-by: dependabot[bot] <support@github.com>
  - Merge pull request #602 from libexpat/dependabot/github_actions/actions/checkout-3.0.2
    
    Actions(deps): Bump actions/checkout from 3.0.1 to 3.0.2
  - Actions(deps): Bump actions/checkout from 3.0.1 to 3.0.2
    
    Bumps [actions/checkout](https://github.com/actions/checkout) from 3.0.1 to 3.0.2.
    - [Release notes](https://github.com/actions/checkout/releases)
    - [Changelog](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
    - [Commits](https://github.com/actions/checkout/compare/v3.0.1...v3.0.2)
    
    ---
    updated-dependencies:
    - dependency-name: actions/checkout
      dependency-type: direct:production
      update-type: version-update:semver-patch
    ...
    
    Signed-off-by: dependabot[bot] <support@github.com>
  - [style] Added parentheses around macro arguments (#601)
    
    
  - Merge pull request #595 from orbitcowboy/master
    
    [style] Added parentheses around macro arguments
  - Merge pull request #599 from libexpat/issue-597-windows-tests-xml-static
    
    CMake: Add missing XML_STATIC to test runners and fuzzers on Windows (related to #597)
  - Merge pull request #600 from libexpat/dependabot/github_actions/actions/checkout-3.0.1
    
    Actions(deps): Bump actions/checkout from 3.0.0 to 3.0.1
  - Actions(deps): Bump actions/checkout from 3.0.0 to 3.0.1
    
    Bumps [actions/checkout](https://github.com/actions/checkout) from 3.0.0 to 3.0.1.
    - [Release notes](https://github.com/actions/checkout/releases)
    - [Changelog](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
    - [Commits](https://github.com/actions/checkout/compare/v3.0.0...v3.0.1)
    
    ---
    updated-dependencies:
    - dependency-name: actions/checkout
      dependency-type: direct:production
      update-type: version-update:semver-patch
    ...
    
    Signed-off-by: dependabot[bot] <support@github.com>
  - CMake: Add missing XML_STATIC to test runners and fuzzers on Windows
    
  - CMake: Add missing section comment for fuzzers
    
  - CMake: Extract loop to resolve runtests/runtestspp duplication
    
  - Merge pull request #598 from libexpat/appveyor-msvc2022
    
    AppVeyor: Add MSVC 2022
  - appveyor.yml: Add MSVC 2022
    
  - Merge pull request #596 from libexpat/sync-autotools-cmake-templates
    
    autotools: Sync expat.cmake to agree with CI
  - autotools: Sync expat.cmake to agree with CI
    
  - [STYLE] Added parentheses around macro argument
  - Merge pull request #594 from orbitcowboy/master
    
    Fixed variable mix-up in nsattcmp attribute handling
  - Fixed typo in nsattcmp attribute handling
  - Merge pull request #593 from orbitcowboy/master
    
    Assign LPVOID pointer with NULL before it's being used
  - Assign LPVOID pointer with NULL before it's being used
    
    This fixes https://github.com/libexpat/libexpat/issues/592