Update git submodules
* Update platform/external/rust/crates/bindgen from branch 'master'
  to e945fa8875dbcb08eacb8967f23fb27050a1f5af
  - Merge "Upgrade bindgen to 0.63.0"
  - Upgrade bindgen to 0.63.0
    
    Test: build/boot cuttlefish
    Change-Id: I44a22e13e11fef39caaafd66c4354b24c95a1f97
    
  - Temporarily use libclap_deprecated am: 256c6901a5 am: c83eb534c4 am: ff964683cf am: b8520ce7a3
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/crates/bindgen/+/2166366
    
    Change-Id: I31b2a41721b3b8019100c56b7595633241dca657
    Signed-off-by: Automerger Merge Worker <android-build-automerger-merge-worker@system.gserviceaccount.com>
    
  - Temporarily use libclap_deprecated am: 256c6901a5 am: c83eb534c4 am: ff964683cf
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/crates/bindgen/+/2166366
    
    Change-Id: I6c295a7122913e76b357c651b1118b61dbbd3efa
    Signed-off-by: Automerger Merge Worker <android-build-automerger-merge-worker@system.gserviceaccount.com>
    
  - Temporarily use libclap_deprecated am: 256c6901a5 am: c83eb534c4
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/crates/bindgen/+/2166366
    
    Change-Id: I03ce2302efaf3bfb979d9a5e25a160289d9b8f68
    Signed-off-by: Automerger Merge Worker <android-build-automerger-merge-worker@system.gserviceaccount.com>
    
  - Temporarily use libclap_deprecated am: 256c6901a5
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/crates/bindgen/+/2166366
    
    Change-Id: Ie524b538dfdc68642a3149681f9988e7abe34c36
    Signed-off-by: Automerger Merge Worker <android-build-automerger-merge-worker@system.gserviceaccount.com>
    
  - Merge "Update TEST_MAPPING" am: 8494b7e432 am: b79000f219 am: b1aeb475b3 am: 5a08693eb7
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/crates/bindgen/+/2125755
    
    Change-Id: I6dbee6b05a2466f6fab007eec26d444b8739c119
    Signed-off-by: Automerger Merge Worker <android-build-automerger-merge-worker@system.gserviceaccount.com>
    
  - Merge "Update TEST_MAPPING" am: 8494b7e432 am: b79000f219 am: b1aeb475b3
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/crates/bindgen/+/2125755
    
    Change-Id: I36b37a15c1663bf7f0d96b6c749f2383f4a3b24d
    Signed-off-by: Automerger Merge Worker <android-build-automerger-merge-worker@system.gserviceaccount.com>
    
  - Merge "Update TEST_MAPPING" am: 8494b7e432 am: b79000f219
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/crates/bindgen/+/2125755
    
    Change-Id: Ie096c4e88d273187c4464d107a173a2f5490c248
    Signed-off-by: Automerger Merge Worker <android-build-automerger-merge-worker@system.gserviceaccount.com>
    
  - Merge "Update TEST_MAPPING" am: 8494b7e432
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/crates/bindgen/+/2125755
    
    Change-Id: Ib463f6bff990ca6ca41b8a1daedc9efbb344302a
    Signed-off-by: Automerger Merge Worker <android-build-automerger-merge-worker@system.gserviceaccount.com>
    
  - Update TEST_MAPPING am: 9fb4cfdcc6 am: 694cbb9170 am: b5056ce14a am: 0bfd816273
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/crates/bindgen/+/2108424
    
    Change-Id: Idc26e60f9e47c7ca1747aacf9778fd77081f9f86
    Signed-off-by: Automerger Merge Worker <android-build-automerger-merge-worker@system.gserviceaccount.com>
    
  - Update TEST_MAPPING am: 9fb4cfdcc6 am: 694cbb9170 am: b5056ce14a
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/crates/bindgen/+/2108424
    
    Change-Id: I387df3b23ba3ded003d57079b6297ff390597dfc
    Signed-off-by: Automerger Merge Worker <android-build-automerger-merge-worker@system.gserviceaccount.com>
    
  - Update TEST_MAPPING am: 9fb4cfdcc6 am: 694cbb9170
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/crates/bindgen/+/2108424
    
    Change-Id: Id214c85dc1a9d4bacb7220c3d0bc1f0eb6d0c752
    Signed-off-by: Automerger Merge Worker <android-build-automerger-merge-worker@system.gserviceaccount.com>
    
  - Update bindgen to 0.59.2 am: 19fbac68e6 am: 22c064f569 am: 06227d3ba6
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/crates/bindgen/+/2005111
    
    Change-Id: Idebbfdaba156a78c76936407abf7f5c36c579d90
    
  - Merge "Refresh Android.bp, cargo2android.json, TEST_MAPPING." am: 245db42fda am: 0dff52646f am: a8ab0ad491 am: c4db92b8ab
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/crates/bindgen/+/1912184
    
    Change-Id: Ib6ff64ab44d66ec951a435b0c109d91859ef082b
    
  - Update TEST_MAPPING am: eb7c0b853d am: 03351d111e am: 7e23508e77 am: 1bad66f7d6 am: 5c459bca12
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/crates/bindgen/+/1813716
    
    Change-Id: I669fed2673cd5780136a24f283ee5da4550c3a75
    
  - Update TEST_MAPPING am: 7cdeb26b57 am: c8f9753ddc am: 8d49b7f0b0 am: e382d13e10 am: 6acffef17b
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/crates/bindgen/+/1806117
    
    Change-Id: Ie51100e8890457e29ead3aa962255dcf3911c938
    
  - Upgrade rust/crates/bindgen to 0.59.1 am: 4c81ebb91a am: 1209ecaae3 am: 04da28cf4b am: e061e77395 am: 0450274896
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/crates/bindgen/+/1791007
    
    Change-Id: I7efee45f9b4c8cc3379631b5d10e332dfa2d7ea2
    
  - Update vpnprofilestore_test to legacykeystore_test in TEST_MAPPING am: 2ed72dfeb7 am: 3f4d454426 am: 0d163dd906 am: 03308beb23
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/crates/bindgen/+/1756453
    
    Change-Id: Ie72138e8c88bef57daddc532e6e95926f5ae8872
    
  - Merge sc-mainline-prod
    
    Bug: 189946434
    Change-Id: I12b8eb6819bc97c326f7cc4d983f83b1280d21ab
    
  - Upgrade rust/crates/bindgen to 0.58.1 am: 64466033e1 am: cddef73ab2 am: 6bb386ebbc am: c1527f10f5 am: b23012aa40
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/crates/bindgen/+/1678110
    
    Change-Id: Iea5828f8cd22921cb092ea543609cedd6bc05705
    
  - Upgrade rust/crates/bindgen to 0.58.1 am: 64466033e1 am: cddef73ab2 am: 6bb386ebbc am: c1527f10f5
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/crates/bindgen/+/1678110
    
    Change-Id: I5b85dea4bf6b2847298717a534e7cf40eab75220
    
  - Upgrade rust/crates/bindgen to 0.58.1 am: 64466033e1 am: cddef73ab2 am: 6bb386ebbc am: c1527f10f5
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/crates/bindgen/+/1678110
    
    Change-Id: I9e8747da5c0813609f2b20ea77f8830bd691d734
    
  - Upgrade rust/crates/bindgen to 0.58.1 am: 64466033e1 am: cddef73ab2 am: 6bb386ebbc am: c1527f10f5
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/crates/bindgen/+/1678110
    
    Change-Id: I627b9044cb649828b1d3a3bead80f73c68e73c21
    
  - [automerger skipped] Mark ab/7061308 as merged in stage. am: 027339f782 -s ours am: e0da804fad -s ours am: 29e516251d -s ours
    
    am skip reason: Change-Id Ib05673188c977b60c66338796d0fd21a990939e3 with SHA-1 9e16877228 is in history
    
    Original change: undetermined
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Ie66a12934b66a73631ba3a15bc9faafd192a0d6b
    
  - [automerger skipped] Mark ab/7061308 as merged in stage. am: 027339f782 -s ours am: e0da804fad -s ours am: 29e516251d -s ours
    
    am skip reason: Change-Id Ib05673188c977b60c66338796d0fd21a990939e3 with SHA-1 9e16877228 is in history
    
    Original change: undetermined
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I7f3001b1911b54d304aec3ebde24abceecc7af0e
    
  - [LSC] Add LOCAL_LICENSE_KINDS to external/rust/crates/bindgen am: 3c37c623fd am: 515c33241d am: 341c74e7c9 am: 16e4a457bb
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/crates/bindgen/+/1588714
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: Iabe230061fb6f1ad9962483a061966868ded32ea
    
  - [LSC] Add LOCAL_LICENSE_KINDS to external/rust/crates/bindgen am: 3c37c623fd am: 515c33241d am: 341c74e7c9 am: 16e4a457bb
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/crates/bindgen/+/1588714
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I3dab897b36aac9d799e51c7a79e8af3fb3694552
    
  - Upgrade rust/crates/bindgen to 0.57.0 am: 1b7519d560 am: a73c2b1d71 am: c6074a8728 am: fe9744311d
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/crates/bindgen/+/1582524
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I8e1741e0eb9f2083fc1a1b3df5426399f214cca5
    
  - Upgrade rust/crates/bindgen to 0.57.0 am: 1b7519d560 am: a73c2b1d71 am: c6074a8728 am: fe9744311d
    
    Original change: https://android-review.googlesource.com/c/platform/external/rust/crates/bindgen/+/1582524
    
    MUST ONLY BE SUBMITTED BY AUTOMERGER
    
    Change-Id: I20a5d4929678745e7c06ebe0f6780cd3a75dd874
    

* Update platform/frameworks/native from branch 'master'
  to d431b2e03db1b2ba2fb192fea16b0b61a1ae7334
  - Merge "Use usize instead of c_long in Rust code"
  - Use usize instead of c_long in Rust code
    
    Needed to upgrade bindgen from 0.59.0 to 0.63.0. Resolves the
    following errors:
    
    error[E0308]: mismatched types
      --> frameworks/native/libs/binder/rust/src/parcel/parcelable.rs:91:22
       |
    91 |                 Some(serialize_element::<Self>),
       |                 ---- ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `usize`, found `u64
    `
       |                 |
       |                 arguments to this enum variant are incorrect
       |
       = note: expected fn pointer `unsafe extern "C" fn(_, _, usize) -> _`
                     found fn item `unsafe extern "C" fn(_, _, u64) -> _ {parcel::pa
    rcelable::serialize_element::<Self>}`
    note: tuple variant defined here
    
    error[E0308]: mismatched types
       --> frameworks/native/libs/binder/rust/src/parcel/parcelable.rs:136:22
        |
    136 |                 Some(deserialize_element::<Self>),
        |                 ---- ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `usize`, found `
    u64`
        |                 |
        |                 arguments to this enum variant are incorrect
        |
        = note: expected fn pointer `unsafe extern "C" fn(_, _, usize) -> _`
                      found fn item `unsafe extern "C" fn(_, _, u64) -> _ {parcel::p
    arcelable::deserialize_element::<Self>}`
    
    Test: Treehugger
    Change-Id: I019e17bd8770da0574b2397f72e717419aa537cd
    

* Update platform/system/security from branch 'master'
  to 26d4222e9296885cd1c3ebd47be668350c29d6da
  - Merge "Remove use of size_t in Rust code"
  - Remove use of size_t in Rust code
    
    Needed to upgrade bindgen from 0.59.0 to 0.63.0. Resolves the
    following errors:
    
    //#[path = "../../../src/options.rs"]
    //mod options;
    
    error[E0432]: unresolved import `keystore2_apc_compat_bindgen::size_t`
      --> system/security/keystore2/apc_compat/apc_compat.rs:22:82
       |
    22 |     abortUserConfirmation, closeUserConfirmationService, promptUserConfirmation, size_t,
       |
          ^^^^^^ no `size_t` in the root
    
    error[E0412]: cannot find type `size_t` in this scope
      --> system/security/keystore2/apc_compat/apc_compat.rs:79:23
       |
    79 |     tbs_message_size: size_t,
       |                       ^^^^^^ not found in this scope
    
    error[E0412]: cannot find type `size_t` in this scope
      --> system/security/keystore2/apc_compat/apc_compat.rs:81:30
       |
    81 |     confirmation_token_size: size_t,
       |                              ^^^^^^ not found in this scope
    
    error[E0412]: cannot find type `size_t` in this scope
       --> system/security/keystore2/apc_compat/apc_compat.rs:181:37
        |
    181 |                 extra_data.len() as size_t,
        |                                     ^^^^^^ not found in this scope
    
    Test: Treehugger
    Change-Id: I848f481627f3c14caa6252eee6b5dd40d2f58eed