Update git submodules
* Update platform/cts from branch 'master'
  to 7f9cb4927e246923a8f59f9f6ef28cdf9e2733ec
  - Merge changes I8657c38d,I94716a35
    
    * changes:
      CtsSystemApiAnnotationTestCases: Allow expected failures to be ignored
      Signature tests: catch and log NoClassDefFoundError
    
  - CtsSystemApiAnnotationTestCases: Allow expected failures to be ignored
    
    Adds support to allow a set of expected failures to be provided via the
    DynamicConfig mechanism and use that in the test to filter out expected
    failures.
    
    This change includes the following:
    * Adding support for DynamicConfig to the module, AndroidTest.xml,
      Android.mk changes and added DynamicConfig.xml file. The file will
      be automatically picked up by when building the test suite.
    * Added ExpectedFailuresFilter and test. The test required a little
      refactoring of the existing test.
    * Integrated ExpectedFailuresFilter into the AnnotationTest.java,
      populating it with information retrieved from the DynamicConfig.xml
      file.
    * Improving consistency of FailureType. Added EXTRA_CONSTRUCTOR, use
      EXTRA_INTERFACE to match how MISSING_INTERFACE is used.
    
    Usually, the above would be done as separate changes to simplify
    review but having a single change makes it easier for it to be
    cherry picked by partners.
    
    Bug: 206650495
    Test: atest --host signature-host-tests
    Change-Id: I8657c38d386e08f8d4b969a2e30ab10b2fa879bd
    
  - Signature tests: catch and log NoClassDefFoundError
    
    Avoids failing the tests if a NoClassDefFoundError is detected when
    attempting to retrieve a class or its constructors, methods or fields
    using reflection. Instead log the failure and continue.
    
    This should not make the tests any less rigorous or risk allowing
    access to implementation details of the platform as if the test cannot
    retrieve them using reflection then an app will be unable to do so
    either.
    
    Bug: 206650495
    Test: m CtsSystemApiAnnotationTestCases
    Change-Id: I94716a359aaa8c88429143130566ec4db13a7ad8