Update git submodules
* Update platform/bionic from branch 'master'
  to e75527347a3c68e7ecc976a67e30d08d28560c90
  - Merge "Fix foritfy test for clang update."
  - Fix foritfy test for clang update.
    
    When doing checkbuild for make_fortify_compile_test.mk:
    bionic/tests/clang_fortify_tests.cpp
    error: 'error' diagnostics seen but not expected:
      Line 171: 'mempcpy' will always overflow; destination buffer has size 8, but size argument is 9
    1 error generated.
    
    Bug: 149839606
    Test: run checkbuild.
    Change-Id: I97371600f6183b5cee8c2a6b976f5bf33e1f781d
    

* Update platform/build/soong from branch 'master'
  to 74d25e39f0e26857c867088b85e959bc86091c35
  - Merge "Switch to clang-r383902 (11.0.1)."
  - Switch to clang-r383902 (11.0.1).
    
    Also suppress some warnings/flags globally to pass compilation.
    
    Bug: 149839606
    Test: build aosp_arm64-userdebug.
    Change-Id: I0ed740e51b6b39c58842a58eabcf3cdf404e73fa
    

* Update platform/superproject from branch 'master'
  to c48c1009313bd9c9ee94461919e8dfca628b7de6
  - Update git submodules
    
    * Update bionic from branch 'master'
      to e75527347a3c68e7ecc976a67e30d08d28560c90
      - Merge "Fix foritfy test for clang update."
      - Fix foritfy test for clang update.
        
        When doing checkbuild for make_fortify_compile_test.mk:
        bionic/tests/clang_fortify_tests.cpp
        error: 'error' diagnostics seen but not expected:
          Line 171: 'mempcpy' will always overflow; destination buffer has size 8, but size argument is 9
        1 error generated.
        
        Bug: 149839606
        Test: run checkbuild.
        Change-Id: I97371600f6183b5cee8c2a6b976f5bf33e1f781d
        
    
    * Update build/soong from branch 'master'
      to 74d25e39f0e26857c867088b85e959bc86091c35
      - Merge "Switch to clang-r383902 (11.0.1)."
      - Switch to clang-r383902 (11.0.1).
        
        Also suppress some warnings/flags globally to pass compilation.
        
        Bug: 149839606
        Test: build aosp_arm64-userdebug.
        Change-Id: I0ed740e51b6b39c58842a58eabcf3cdf404e73fa