Update git submodules
* Update platform/external/selinux from branch 'master'
  to 1ad3304eae5e562aba64f256e5589d144d9cfadd
  - Merge remote-tracking branch 'aosp/upstream-master' into mymerge
    
    In particular, pulls in
    https://github.com/SELinuxProject/selinux/commit/3f99b14939ec616ef59f62887e2532cd89409a3e
    which is needed for b/118685852
    
    Followed the following steps:
      # In repo client
      cd external/selinux
      repo sync .
      repo start mymerge .
      git merge aosp/upstream-master --no-ff # resolve any conflicts
      repo upload .
    
    Bug: 118685852
    Test: Android compiles and no obvious problems.
    Change-Id: Ic8f1bb2b573a1491b733732653afd7dbe494c85f
    
  - libselinux: fix overly strict validation of file_contexts.bin
    
    load_mmap and regex_load_mmap (in the !USE_PCRE2 case) were
    incorrectly treating the absence of any fixed stems or study data
    as an error, rejecting valid file_contexts.bin files.  Remove
    the extraneous validation checks.
    
    Test:
    $ cat > file_contexts <<EOF
    (/.*)?                u:object_r:system_file:s0
    /lib                   u:object_r:system_dir:s0
    EOF
    $ sefcontext_compile file_contexts
    $ selabel_lookup -b file -k /lib -f file_contexts.bin
    
    Before:
    ERROR: selabel_open - Could not obtain handle.
    
    After:
    Default context: u:object_r:system_dir:s0
    
    Reported-by: Jiyong Park <jiyong@google.com>
    Signed-off-by: Stephen Smalley <sds@tycho.nsa.gov>
    
  - Fix snprintf truncated error
    
    Link: https://github.com/SELinuxProject/selinux/pull/106
    Signed-off-by: StidOfficial <stidofficiel@gmail.com>
    
  - mcstrans: remove unused getpeercon_raw() call
    
    There is a call to getpeercon_raw() in mcstransd, but nothing is done
    with the context. The purpose of process_request() is to translate a
    context and we would like that to succeed even if, for some reason,
    getpeercon_raw() fails.
    
    Signed-off-by: Yuli Khodorkovskiy <yuli@crunchydata.com>
    Signed-off-by: Joshua Brindle <joshua.brindle@crunchydata.com>
    
  - libsepol: add missing ibendport port validity check
    
    The kernel checks if the port is in the range 1-255 when loading an
    ibenportcon rule. Add the same check to libsepol.
    
    Fixes: 118c0cd1038e ("libsepol: Add ibendport ocontext handling")
    Signed-off-by: Ondrej Mosnacek <omosnace@redhat.com>
    
  - libsepol: fix endianity in ibpkey range checks
    
    We need to convert from little-endian before dong range checks on the
    ibpkey port numbers, otherwise we would be checking a wrong value on
    big-endian systems.
    
    Fixes: 9fbb3112769a ("libsepol: Add ibpkey ocontext handling")
    Signed-off-by: Ondrej Mosnacek <omosnace@redhat.com>
    

* Update platform/superproject from branch 'master'
  to 3f0fec66117864bd41c340852cd74891063a79fb
  - Update git submodules
    
    * Update external/selinux from branch 'master'
      to 1ad3304eae5e562aba64f256e5589d144d9cfadd
      - Merge remote-tracking branch 'aosp/upstream-master' into mymerge
        
        In particular, pulls in
        https://github.com/SELinuxProject/selinux/commit/3f99b14939ec616ef59f62887e2532cd89409a3e
        which is needed for b/118685852
        
        Followed the following steps:
          # In repo client
          cd external/selinux
          repo sync .
          repo start mymerge .
          git merge aosp/upstream-master --no-ff # resolve any conflicts
          repo upload .
        
        Bug: 118685852
        Test: Android compiles and no obvious problems.
        Change-Id: Ic8f1bb2b573a1491b733732653afd7dbe494c85f
        
      - libselinux: fix overly strict validation of file_contexts.bin
        
        load_mmap and regex_load_mmap (in the !USE_PCRE2 case) were
        incorrectly treating the absence of any fixed stems or study data
        as an error, rejecting valid file_contexts.bin files.  Remove
        the extraneous validation checks.
        
        Test:
        $ cat > file_contexts <<EOF
        (/.*)?                u:object_r:system_file:s0
        /lib                   u:object_r:system_dir:s0
        EOF
        $ sefcontext_compile file_contexts
        $ selabel_lookup -b file -k /lib -f file_contexts.bin
        
        Before:
        ERROR: selabel_open - Could not obtain handle.
        
        After:
        Default context: u:object_r:system_dir:s0
        
        Reported-by: Jiyong Park <jiyong@google.com>
        Signed-off-by: Stephen Smalley <sds@tycho.nsa.gov>
        
      - Fix snprintf truncated error
        
        Link: https://github.com/SELinuxProject/selinux/pull/106
        Signed-off-by: StidOfficial <stidofficiel@gmail.com>
        
      - mcstrans: remove unused getpeercon_raw() call
        
        There is a call to getpeercon_raw() in mcstransd, but nothing is done
        with the context. The purpose of process_request() is to translate a
        context and we would like that to succeed even if, for some reason,
        getpeercon_raw() fails.
        
        Signed-off-by: Yuli Khodorkovskiy <yuli@crunchydata.com>
        Signed-off-by: Joshua Brindle <joshua.brindle@crunchydata.com>
        
      - libsepol: add missing ibendport port validity check
        
        The kernel checks if the port is in the range 1-255 when loading an
        ibenportcon rule. Add the same check to libsepol.
        
        Fixes: 118c0cd1038e ("libsepol: Add ibendport ocontext handling")
        Signed-off-by: Ondrej Mosnacek <omosnace@redhat.com>
        
      - libsepol: fix endianity in ibpkey range checks
        
        We need to convert from little-endian before dong range checks on the
        ibpkey port numbers, otherwise we would be checking a wrong value on
        big-endian systems.
        
        Fixes: 9fbb3112769a ("libsepol: Add ibpkey ocontext handling")
        Signed-off-by: Ondrej Mosnacek <omosnace@redhat.com>