Update git submodules
* Update device/google/cuttlefish from branch 'master'
  to ac9e507a8c2e11dbe87fc4da4032abbc1762aa4c
  - Merge changes from topic "revert-1454075-2020-10-07-gki-update-SLQXEYZGME"
    
    * changes:
      Revert "Allow downstream devices to customize vendor modules set"
      Revert "load kernel, kernel modules from updated locations"
    
  - Revert "Allow downstream devices to customize vendor modules set"
    
    Revert "use new GKI kernel location"
    
    Revert "Update kernel to builds 6888926"
    
    Revert submission 1454075-2020-10-07-gki-update
    
    Reason for revert: Looks like this topic changes caused daily build broken, the error log as:
    
    error: +out/target/product/emulator_arm64/boot.img too large (34934784 > 33484800)
    
    I tried to revert this topic first and then feel free to revert revert it.
    
    Reverted Changes:
    Ie74ca26e8:use new GKI kernel location
    Ibff0d9638:Update kernel to builds 6889747
    I693476e82:Update kernel to builds 6888926
    I35d7f320c:Update kernel to builds 6888926
    Id221a7a30:Update kernel to builds 6888926
    I4421dbf67:remove kernel, kernel modules from cuttlefish_kern...
    I991f9a6af:Allow downstream devices to customize vendor modul...
    I598630e09:load kernel, kernel modules from updated locations...
    
    Bug: 170451791
    Change-Id: I2b5c33128cee1b29c9df401dc545606492b3ca28
    
  - Revert "load kernel, kernel modules from updated locations"
    
    Revert "use new GKI kernel location"
    
    Revert "Update kernel to builds 6888926"
    
    Revert submission 1454075-2020-10-07-gki-update
    
    Reason for revert: Looks like this topic changes caused daily build broken, the error log as:
    
    error: +out/target/product/emulator_arm64/boot.img too large (34934784 > 33484800)
    
    I tried to revert this topic first and then feel free to revert revert it.
    
    Reverted Changes:
    Ie74ca26e8:use new GKI kernel location
    Ibff0d9638:Update kernel to builds 6889747
    I693476e82:Update kernel to builds 6888926
    I35d7f320c:Update kernel to builds 6888926
    Id221a7a30:Update kernel to builds 6888926
    I4421dbf67:remove kernel, kernel modules from cuttlefish_kern...
    I991f9a6af:Allow downstream devices to customize vendor modul...
    I598630e09:load kernel, kernel modules from updated locations...
    
    Bug: 170451791
    Change-Id: Ib52e6cc40ec06b55f3f3c361be234f4130d1f1c5
    

* Update device/google/cuttlefish_kernel from branch 'master'
  to f034a42bfc811a2a6f15dab4c2971fa6d64ef66b
  - Revert "remove kernel, kernel modules from cuttlefish_kernel"
    
    Revert "Update kernel to builds 6888926"
    
    Revert "Update kernel to builds 6888926"
    
    Revert "Update kernel to builds 6889747"
    
    Revert "Allow downstream devices to customize vendor modules set"
    
    Revert "use new GKI kernel location"
    
    Revert "Update kernel to builds 6888926"
    
    Revert submission 1454075-2020-10-07-gki-update
    
    Reason for revert: Looks like this topic changes caused daily build broken, the error log as:
    
    error: +out/target/product/emulator_arm64/boot.img too large (34934784 > 33484800)
    
    I tried to revert this topic first and then feel free to revert revert it.
    
    Reverted Changes:
    Ie74ca26e8:use new GKI kernel location
    Ibff0d9638:Update kernel to builds 6889747
    I693476e82:Update kernel to builds 6888926
    I35d7f320c:Update kernel to builds 6888926
    Id221a7a30:Update kernel to builds 6888926
    I4421dbf67:remove kernel, kernel modules from cuttlefish_kern...
    I991f9a6af:Allow downstream devices to customize vendor modul...
    I598630e09:load kernel, kernel modules from updated locations...
    
    Bug: 170451791
    Change-Id: I4ce9656d9f756df5197bc7d173d35432878d4fae
    

* Update kernel/prebuilts/5.4/arm64 from branch 'master'
  to 1e95193a84abf0960b216366c1799e2fc54c1a5a
  - Revert "Update kernel to builds 6888926"
    
    Revert "Update kernel to builds 6888926"
    
    Revert "Update kernel to builds 6889747"
    
    Revert "Allow downstream devices to customize vendor modules set"
    
    Revert "use new GKI kernel location"
    
    Revert "Update kernel to builds 6888926"
    
    Revert submission 1454075-2020-10-07-gki-update
    
    Reason for revert: Looks like this topic changes caused daily build broken, the error log as:
    
    error: +out/target/product/emulator_arm64/boot.img too large (34934784 > 33484800)
    
    I tried to revert this topic first and then feel free to revert revert it.
    
    Reverted Changes:
    Ie74ca26e8:use new GKI kernel location
    Ibff0d9638:Update kernel to builds 6889747
    I693476e82:Update kernel to builds 6888926
    I35d7f320c:Update kernel to builds 6888926
    Id221a7a30:Update kernel to builds 6888926
    I4421dbf67:remove kernel, kernel modules from cuttlefish_kern...
    I991f9a6af:Allow downstream devices to customize vendor modul...
    I598630e09:load kernel, kernel modules from updated locations...
    
    Bug: 170451791
    Change-Id: I00b48f7c7ff2c3817aaa7245638c8cacf6812acb
    

* Update kernel/prebuilts/5.4/x86-64 from branch 'master'
  to e769c4971564a456f4904752f336bd3eafb17f5b
  - Revert "Update kernel to builds 6888926"
    
    Revert "Update kernel to builds 6889747"
    
    Revert "Allow downstream devices to customize vendor modules set"
    
    Revert "use new GKI kernel location"
    
    Revert "Update kernel to builds 6888926"
    
    Revert submission 1454075-2020-10-07-gki-update
    
    Reason for revert: Looks like this topic changes caused daily build broken, the error log as:
    
    error: +out/target/product/emulator_arm64/boot.img too large (34934784 > 33484800)
    
    I tried to revert this topic first and then feel free to revert revert it.
    
    Reverted Changes:
    Ie74ca26e8:use new GKI kernel location
    Ibff0d9638:Update kernel to builds 6889747
    I693476e82:Update kernel to builds 6888926
    I35d7f320c:Update kernel to builds 6888926
    Id221a7a30:Update kernel to builds 6888926
    I4421dbf67:remove kernel, kernel modules from cuttlefish_kern...
    I991f9a6af:Allow downstream devices to customize vendor modul...
    I598630e09:load kernel, kernel modules from updated locations...
    
    Bug: 170451791
    Change-Id: I85d9d824f2f6e76079232fa6c2bff00e787a5c83
    

* Update platform/build.git from branch 'master'
  to f07902e84fcef578e99215a0928a810cec182b3a
  - Merge "Revert "use new GKI kernel location""
  - Revert "use new GKI kernel location"
    
    Revert "Update kernel to builds 6888926"
    
    Revert submission 1454075-2020-10-07-gki-update
    
    Reason for revert: Looks like this topic changes caused daily build broken, the error log as:
    
    error: +out/target/product/emulator_arm64/boot.img too large (34934784 > 33484800)
    
    I tried to revert this topic first and then feel free to revert revert it.
    
    Reverted Changes:
    Ie74ca26e8:use new GKI kernel location
    Ibff0d9638:Update kernel to builds 6889747
    I693476e82:Update kernel to builds 6888926
    I35d7f320c:Update kernel to builds 6888926
    Id221a7a30:Update kernel to builds 6888926
    I4421dbf67:remove kernel, kernel modules from cuttlefish_kern...
    I991f9a6af:Allow downstream devices to customize vendor modul...
    I598630e09:load kernel, kernel modules from updated locations...
    
    Bug: 170451791
    Change-Id: I4d8f18a7c80eb92cb475c48e1dcf04ceabd08984
    

* Update platform/superproject from branch 'master'
  to d457a52818bce3b8de333576d09720d1f415120b
  - Update git submodules
    
    * Update build/make from branch 'master'
      to f07902e84fcef578e99215a0928a810cec182b3a
      - Merge "Revert "use new GKI kernel location""
      - Revert "use new GKI kernel location"
        
        Revert "Update kernel to builds 6888926"
        
        Revert submission 1454075-2020-10-07-gki-update
        
        Reason for revert: Looks like this topic changes caused daily build broken, the error log as:
        
        error: +out/target/product/emulator_arm64/boot.img too large (34934784 > 33484800)
        
        I tried to revert this topic first and then feel free to revert revert it.
        
        Reverted Changes:
        Ie74ca26e8:use new GKI kernel location
        Ibff0d9638:Update kernel to builds 6889747
        I693476e82:Update kernel to builds 6888926
        I35d7f320c:Update kernel to builds 6888926
        Id221a7a30:Update kernel to builds 6888926
        I4421dbf67:remove kernel, kernel modules from cuttlefish_kern...
        I991f9a6af:Allow downstream devices to customize vendor modul...
        I598630e09:load kernel, kernel modules from updated locations...
        
        Bug: 170451791
        Change-Id: I4d8f18a7c80eb92cb475c48e1dcf04ceabd08984
        
    
    * Update device/google/cuttlefish from branch 'master'
      to ac9e507a8c2e11dbe87fc4da4032abbc1762aa4c
      - Merge changes from topic "revert-1454075-2020-10-07-gki-update-SLQXEYZGME"
        
        * changes:
          Revert "Allow downstream devices to customize vendor modules set"
          Revert "load kernel, kernel modules from updated locations"
        
      - Revert "Allow downstream devices to customize vendor modules set"
        
        Revert "use new GKI kernel location"
        
        Revert "Update kernel to builds 6888926"
        
        Revert submission 1454075-2020-10-07-gki-update
        
        Reason for revert: Looks like this topic changes caused daily build broken, the error log as:
        
        error: +out/target/product/emulator_arm64/boot.img too large (34934784 > 33484800)
        
        I tried to revert this topic first and then feel free to revert revert it.
        
        Reverted Changes:
        Ie74ca26e8:use new GKI kernel location
        Ibff0d9638:Update kernel to builds 6889747
        I693476e82:Update kernel to builds 6888926
        I35d7f320c:Update kernel to builds 6888926
        Id221a7a30:Update kernel to builds 6888926
        I4421dbf67:remove kernel, kernel modules from cuttlefish_kern...
        I991f9a6af:Allow downstream devices to customize vendor modul...
        I598630e09:load kernel, kernel modules from updated locations...
        
        Bug: 170451791
        Change-Id: I2b5c33128cee1b29c9df401dc545606492b3ca28
        
      - Revert "load kernel, kernel modules from updated locations"
        
        Revert "use new GKI kernel location"
        
        Revert "Update kernel to builds 6888926"
        
        Revert submission 1454075-2020-10-07-gki-update
        
        Reason for revert: Looks like this topic changes caused daily build broken, the error log as:
        
        error: +out/target/product/emulator_arm64/boot.img too large (34934784 > 33484800)
        
        I tried to revert this topic first and then feel free to revert revert it.
        
        Reverted Changes:
        Ie74ca26e8:use new GKI kernel location
        Ibff0d9638:Update kernel to builds 6889747
        I693476e82:Update kernel to builds 6888926
        I35d7f320c:Update kernel to builds 6888926
        Id221a7a30:Update kernel to builds 6888926
        I4421dbf67:remove kernel, kernel modules from cuttlefish_kern...
        I991f9a6af:Allow downstream devices to customize vendor modul...
        I598630e09:load kernel, kernel modules from updated locations...
        
        Bug: 170451791
        Change-Id: Ib52e6cc40ec06b55f3f3c361be234f4130d1f1c5
        
    
    * Update device/google/cuttlefish_kernel from branch 'master'
      to f034a42bfc811a2a6f15dab4c2971fa6d64ef66b
      - Revert "remove kernel, kernel modules from cuttlefish_kernel"
        
        Revert "Update kernel to builds 6888926"
        
        Revert "Update kernel to builds 6888926"
        
        Revert "Update kernel to builds 6889747"
        
        Revert "Allow downstream devices to customize vendor modules set"
        
        Revert "use new GKI kernel location"
        
        Revert "Update kernel to builds 6888926"
        
        Revert submission 1454075-2020-10-07-gki-update
        
        Reason for revert: Looks like this topic changes caused daily build broken, the error log as:
        
        error: +out/target/product/emulator_arm64/boot.img too large (34934784 > 33484800)
        
        I tried to revert this topic first and then feel free to revert revert it.
        
        Reverted Changes:
        Ie74ca26e8:use new GKI kernel location
        Ibff0d9638:Update kernel to builds 6889747
        I693476e82:Update kernel to builds 6888926
        I35d7f320c:Update kernel to builds 6888926
        Id221a7a30:Update kernel to builds 6888926
        I4421dbf67:remove kernel, kernel modules from cuttlefish_kern...
        I991f9a6af:Allow downstream devices to customize vendor modul...
        I598630e09:load kernel, kernel modules from updated locations...
        
        Bug: 170451791
        Change-Id: I4ce9656d9f756df5197bc7d173d35432878d4fae
        
    
    * Update device/google/cuttlefish_prebuilts from branch 'master'
      to 0a6b8e6e4488c79b8ddd4c7a2e814fd50167035e
      - Merge "Revert "Update kernel to builds 6888926""
      - Revert "Update kernel to builds 6888926"
        
        Revert submission 1454075-2020-10-07-gki-update
        
        Reason for revert: Looks like this topic changes caused daily build broken, the error log as:
        
        error: +out/target/product/emulator_arm64/boot.img too large (34934784 > 33484800)
        
        I tried to revert this topic first and then feel free to revert revert it.
        
        Reverted Changes:
        Ie74ca26e8:use new GKI kernel location
        Ibff0d9638:Update kernel to builds 6889747
        I693476e82:Update kernel to builds 6888926
        I35d7f320c:Update kernel to builds 6888926
        Id221a7a30:Update kernel to builds 6888926
        I4421dbf67:remove kernel, kernel modules from cuttlefish_kern...
        I991f9a6af:Allow downstream devices to customize vendor modul...
        I598630e09:load kernel, kernel modules from updated locations...
        
        Bug: 170451791
        Change-Id: I855d43728d5b44153c33be37c8e20a889c5d2714
        
    
    * Update kernel/prebuilts/5.4/arm64 from branch 'master'
      to 1e95193a84abf0960b216366c1799e2fc54c1a5a
      - Revert "Update kernel to builds 6888926"
        
        Revert "Update kernel to builds 6888926"
        
        Revert "Update kernel to builds 6889747"
        
        Revert "Allow downstream devices to customize vendor modules set"
        
        Revert "use new GKI kernel location"
        
        Revert "Update kernel to builds 6888926"
        
        Revert submission 1454075-2020-10-07-gki-update
        
        Reason for revert: Looks like this topic changes caused daily build broken, the error log as:
        
        error: +out/target/product/emulator_arm64/boot.img too large (34934784 > 33484800)
        
        I tried to revert this topic first and then feel free to revert revert it.
        
        Reverted Changes:
        Ie74ca26e8:use new GKI kernel location
        Ibff0d9638:Update kernel to builds 6889747
        I693476e82:Update kernel to builds 6888926
        I35d7f320c:Update kernel to builds 6888926
        Id221a7a30:Update kernel to builds 6888926
        I4421dbf67:remove kernel, kernel modules from cuttlefish_kern...
        I991f9a6af:Allow downstream devices to customize vendor modul...
        I598630e09:load kernel, kernel modules from updated locations...
        
        Bug: 170451791
        Change-Id: I00b48f7c7ff2c3817aaa7245638c8cacf6812acb
        
    
    * Update kernel/prebuilts/5.4/x86_64 from branch 'master'
      to e769c4971564a456f4904752f336bd3eafb17f5b
      - Revert "Update kernel to builds 6888926"
        
        Revert "Update kernel to builds 6889747"
        
        Revert "Allow downstream devices to customize vendor modules set"
        
        Revert "use new GKI kernel location"
        
        Revert "Update kernel to builds 6888926"
        
        Revert submission 1454075-2020-10-07-gki-update
        
        Reason for revert: Looks like this topic changes caused daily build broken, the error log as:
        
        error: +out/target/product/emulator_arm64/boot.img too large (34934784 > 33484800)
        
        I tried to revert this topic first and then feel free to revert revert it.
        
        Reverted Changes:
        Ie74ca26e8:use new GKI kernel location
        Ibff0d9638:Update kernel to builds 6889747
        I693476e82:Update kernel to builds 6888926
        I35d7f320c:Update kernel to builds 6888926
        Id221a7a30:Update kernel to builds 6888926
        I4421dbf67:remove kernel, kernel modules from cuttlefish_kern...
        I991f9a6af:Allow downstream devices to customize vendor modul...
        I598630e09:load kernel, kernel modules from updated locations...
        
        Bug: 170451791
        Change-Id: I85d9d824f2f6e76079232fa6c2bff00e787a5c83
        
    
    * Update kernel/prebuilts/mainline/arm64 from branch 'master'
      to 7d6d04559925574c3c0336f558e77403786f5ab2
      - Revert "Update kernel to builds 6889747"
        
        Revert "Allow downstream devices to customize vendor modules set"
        
        Revert "use new GKI kernel location"
        
        Revert "Update kernel to builds 6888926"
        
        Revert submission 1454075-2020-10-07-gki-update
        
        Reason for revert: Looks like this topic changes caused daily build broken, the error log as:
        
        error: +out/target/product/emulator_arm64/boot.img too large (34934784 > 33484800)
        
        I tried to revert this topic first and then feel free to revert revert it.
        
        Reverted Changes:
        Ie74ca26e8:use new GKI kernel location
        Ibff0d9638:Update kernel to builds 6889747
        I693476e82:Update kernel to builds 6888926
        I35d7f320c:Update kernel to builds 6888926
        Id221a7a30:Update kernel to builds 6888926
        I4421dbf67:remove kernel, kernel modules from cuttlefish_kern...
        I991f9a6af:Allow downstream devices to customize vendor modul...
        I598630e09:load kernel, kernel modules from updated locations...
        
        Bug: 170451791
        Change-Id: I5cea51df5b76ce7f586372d9d1cc47e2bfaadf74