Update git submodules
* Update platform/external/jsoncpp from branch 'master'
  to 89fd0c7dd0a4d4195a8ecf8808d56e39351bfaa5
  - Merge "Add libjsoncpp_headers target"
  - Add libjsoncpp_headers target
    
    Test: build
    Bug: 139546461
    Change-Id: Id0fcb8c843be04f8d513dae7228cc40de303073d
    

* Update platform/superproject from branch 'master'
  to 6b245ee24b9b056d8ac4245f44300d7b0b5d357f
  - Update git submodules
    
    * Update external/jsoncpp from branch 'master'
      to 89fd0c7dd0a4d4195a8ecf8808d56e39351bfaa5
      - Merge "Add libjsoncpp_headers target"
      - Add libjsoncpp_headers target
        
        Test: build
        Bug: 139546461
        Change-Id: Id0fcb8c843be04f8d513dae7228cc40de303073d
        
    
    * Update system/core from branch 'master'
      to ebfd2a468b3070fbd6376428a84615829760beb1
      - Merge "Fix ODR violation"
      - Fix ODR violation
        
        host_init_verifier statically links libprocessgroup, which has shared
        dependency on libjsoncpp. Right now it also has shared dependency on
        libjsoncpp, resulting in ODR violation:
        
         ERROR: AddressSanitizer: odr-violation (0x7fce895f3220):
         [1] size=8 'Json::kNullRef' external/jsoncpp/src/lib_json/json_value.cpp:37:22
         [2] size=8 'Json::kNullRef' external/jsoncpp/src/lib_json/json_value.cpp:37:22
         These globals were registered at these points:
         [1]:
         #0 0x56276926ef0d (/usr/local/google/buildbot/src/android/master/out/host/linux-x86/bin/host_init_verifier+0xd1f0d)
         #1 0x7fce894ac1d9 (/lib64/ld-linux-x86-64.so.2+0x101d9)
        
         [2]:
         #0 0x56276926ef0d (/usr/local/google/buildbot/src/android/master/out/host/linux-x86/bin/host_init_verifier+0xd1f0d)
         #1 0x7fce894ac1d9 (/lib64/ld-linux-x86-64.so.2+0x101d9)
        
        Move host_init_verifier to libjsoncpp_headers to fix the ODR violation.
        
        Bug: 139546461
        Bug: 131328001
        Test: Run ASAN host_init_verifier
        Change-Id: I54a51138d61fff37f092ffaa0758817600a0af9d
        

* Update platform/system/core from branch 'master'
  to ebfd2a468b3070fbd6376428a84615829760beb1
  - Merge "Fix ODR violation"
  - Fix ODR violation
    
    host_init_verifier statically links libprocessgroup, which has shared
    dependency on libjsoncpp. Right now it also has shared dependency on
    libjsoncpp, resulting in ODR violation:
    
     ERROR: AddressSanitizer: odr-violation (0x7fce895f3220):
     [1] size=8 'Json::kNullRef' external/jsoncpp/src/lib_json/json_value.cpp:37:22
     [2] size=8 'Json::kNullRef' external/jsoncpp/src/lib_json/json_value.cpp:37:22
     These globals were registered at these points:
     [1]:
     #0 0x56276926ef0d (/usr/local/google/buildbot/src/android/master/out/host/linux-x86/bin/host_init_verifier+0xd1f0d)
     #1 0x7fce894ac1d9 (/lib64/ld-linux-x86-64.so.2+0x101d9)
    
     [2]:
     #0 0x56276926ef0d (/usr/local/google/buildbot/src/android/master/out/host/linux-x86/bin/host_init_verifier+0xd1f0d)
     #1 0x7fce894ac1d9 (/lib64/ld-linux-x86-64.so.2+0x101d9)
    
    Move host_init_verifier to libjsoncpp_headers to fix the ODR violation.
    
    Bug: 139546461
    Bug: 131328001
    Test: Run ASAN host_init_verifier
    Change-Id: I54a51138d61fff37f092ffaa0758817600a0af9d