Update git submodules
* Update platform/art from branch 'master'
  to 396198b6bd6635fff52091131ca5be94cfab1d74
  - Handle unresolved field type in compiler.
    
    Make behavior consistent with interpreter, by only resolving field types
    when the stored value is not null.
    
    Note that this differs from RI behavior which throws a
    NoClassDefFoundError when loading the BadField class.
    
    Bug: 79751666
    
    Test: 173-missing-field-type
    Change-Id: I1e584f3129fd651bee1c9635c90bc30e13190a90
    

* Update platform/superproject from branch 'master'
  to e9118fcf6503919103b43cc7dd5bac5876992a3e
  - Update git submodules
    
    * Update art from branch 'master'
      to 396198b6bd6635fff52091131ca5be94cfab1d74
      - Handle unresolved field type in compiler.
        
        Make behavior consistent with interpreter, by only resolving field types
        when the stored value is not null.
        
        Note that this differs from RI behavior which throws a
        NoClassDefFoundError when loading the BadField class.
        
        Bug: 79751666
        
        Test: 173-missing-field-type
        Change-Id: I1e584f3129fd651bee1c9635c90bc30e13190a90