Update git submodules
* Update platform/external/vogar from branch 'master'
  to f2a0039aa783b768d55af65d3f31a4ef3b86b711
  - Restore removeDexFilesForD8.
    
    This is a partial revert of:
    https://android-review.googlesource.com/c/platform/external/vogar/+/1928159
    
    From luci logs:
    Failed task: dex core-tests_intermediates ERROR
    vogar.commands.CommandFailedException: Command failed: d8 -JXms16M -JXmx1536M --min-api 10000 --output /tmp/vogar/e6b916f4-3df1-423b-9016-f9bcc89fba6f/core-tests_intermediates/core-tests_intermediates.dex.jar /b/swarming/w/ir/cache/art/out/target/common/obj/JAVA_LIBRARIES/core-tests_intermediates/classes.jar
      Error: com.android.tools.r8.internal.Lc: Cannot create android app from an archive '/b/swarming/w/ir/cache/art/out/target/common/obj/JAVA_LIBRARIES/core-tests_intermediates/classes.jar' containing both DEX and Java-bytecode content
      Compilation failed
      Exception in thread "main" java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
    
    Dex files are still present in archives and need to be removed.
    
    Test: run-libcore-tests.py
    Change-Id: Ic08c45b9e04d3ad3f2035a61924eb0e4228eb5f2