Update git submodules
* Update platform/superproject from branch 'master'
  to d5cf2e5fcaa258c572ea6aa367cae05cb9ad68b4
  - Update git submodules
    
    * Update system/tools/aidl from branch 'master'
      to 59e53e49b63d12d8d366e9ad035de9b98b7c7cb4
      - ShallowIntegralCopy: report user errors w/o crash
        
        Needs to check that ValueString returns non-empty string.
        Bug: 145066992
        Test: aidl_parser_fuzzer with:
            "enum F{s=2e8,z}"
        
        Needs to consider unsuccessful evaluate as user error not as AIDL_FATAL
        (also removed confusing print out of 'type' since in the case where it
        fails to evaluate, it may be something like 'binary expression').
        Fixes: 145011986
        Test: aidl_parser_fuzzer with:
            "enum i{Uecp,a333333=033-3.33333372928 ,ut,}"
        ERROR: a/path/Foo.aidl:1.35-38: Failed to parse expression as integer: 033-3.33333372928
        
        Change-Id: If76948afd96e7f975b6f834b59f9e29db7205cd0
        
      - Missing toString entry for const expressions.
        
        So, it aborted when printing info about float values. Also re-ordered
        this switch statement to be in the order that this enum is declared.
        
        Bug: 145066992
        Test: fuzzer w/ case "enum F{s=2e8,z}" makes more progress
        Change-Id: Iae2acb268b89438e1b06377243cc0b2d76ee164d
        

* Update platform/system/tools/aidl from branch 'master'
  to 59e53e49b63d12d8d366e9ad035de9b98b7c7cb4
  - ShallowIntegralCopy: report user errors w/o crash
    
    Needs to check that ValueString returns non-empty string.
    Bug: 145066992
    Test: aidl_parser_fuzzer with:
        "enum F{s=2e8,z}"
    
    Needs to consider unsuccessful evaluate as user error not as AIDL_FATAL
    (also removed confusing print out of 'type' since in the case where it
    fails to evaluate, it may be something like 'binary expression').
    Fixes: 145011986
    Test: aidl_parser_fuzzer with:
        "enum i{Uecp,a333333=033-3.33333372928 ,ut,}"
    ERROR: a/path/Foo.aidl:1.35-38: Failed to parse expression as integer: 033-3.33333372928
    
    Change-Id: If76948afd96e7f975b6f834b59f9e29db7205cd0
    
  - Missing toString entry for const expressions.
    
    So, it aborted when printing info about float values. Also re-ordered
    this switch statement to be in the order that this enum is declared.
    
    Bug: 145066992
    Test: fuzzer w/ case "enum F{s=2e8,z}" makes more progress
    Change-Id: Iae2acb268b89438e1b06377243cc0b2d76ee164d