Update git submodules
* Update platform/external/selinux from branch 'master'
  to cee4ffe06f8e3d979af00444da6c51c34acc05df
  - Merge remote-tracking branch 'aosp/upstream-master' into mymerge
    
    Followed the following steps:
    
      # In repo client
      cd external/selinux
      repo sync .
      repo start mymerge .
      git merge aosp/upstream-master --no-ff # resolve any conflicts
      repo upload .
    
    Test: Android compiles and no obvious problems.
    Change-Id: I526e8c09eb7cb7f73fe771fd1295bb406514589b
    
  - python/semanage: Stop rejecting aliases in semanage commands
    
    Resolves:
    
    \# semanage fcontext -a -t svirt_sandbox_file_t /pokus
    ValueError: Type svirt_sandbox_file_t is invalid, must be a file or device type
    \# semanage fcontext -d -t svirt_sandbox_file_t /pokus
    ValueError: File context for /pokus is not defined
    
    \# seinfo -tsvirt_sandbox_file_t -x
       TypeName container_file_t
       Aliases
          svirt_sandbox_file_t
          svirt_lxc_file_t
    
    Signed-off-by: Vit Mojzis <vmojzis@redhat.com>
    
  - python/sepolicy: Stop rejecting aliases in sepolicy commands
    
    Fix CheckDomain and CheckPortType classes to properly deal with aliases.
    
    Resolves:
       https://bugzilla.redhat.com/show_bug.cgi?id=1600009
    
    Signed-off-by: Vit Mojzis <vmojzis@redhat.com>
    
  - python/sepolicy: Fix "info" to search aliases as well
    
    Restore previous behaviour of "sepolicy.info()".
    
    Signed-off-by: Vit Mojzis <vmojzis@redhat.com>
    
  - README: Update the SELinux mailing list location
    
    Signed-off-by: Stephen Smalley <sds@tycho.nsa.gov>
    
  - libsepol: Add two new Xen initial SIDs
    
    Xen uses the initial SIDs domU and domDM in its toolstack, so it makes
    sense to add these to xen_sid_to_str[] in kernel_to_common.h
    
    Signed-off-by: James Carter <jwcart2@tycho.nsa.gov>
    
  - libsepol: Check that initial sid indexes are within the valid range
    
    When writing CIL from a policy module or when writing CIL or policy.conf
    from a kernel binary policy, check that the initial sid index is within
    the valid range of the selinux_sid_to_str[] array (or xen_sid_to_str[]
    array for a XEN policy). If it is not, then create a unique name
    ("UNKNOWN"+index) for the initial sid.
    
    Signed-off-by: James Carter <jwcart2@tycho.nsa.gov>
    
  - libsepol: Eliminate initial sid string definitions in module_to_cil.c
    
    Since the initial sid strings are defined in kernel_to_common.h,
    module_to_cil.c can use those and its initial sid string definitions
    can be removed.
    
    Signed-off-by: James Carter <jwcart2@tycho.nsa.gov>
    
  - libsepol: Rename kernel_to_common.c stack functions
    
    Want to make use of selinux_sid_to_str[] and xen_sid_to_str[] from
    kernel_to_common.h in module_to_cil.c, but stack functions with the
    same names exist in module_to_cil.c and kernel_to_common.c (with
    the function prototypes in kernel_to_common.h).
    
    Since the stack functions in kernel_to_common.c are less general and
    only work with strings, rename those functions from stack_* to
    strs_stack_*.
    
    Signed-off-by: James Carter <jwcart2@tycho.nsa.gov>
    
  - checkpolicy: Add option to sort ocontexts when creating a binary policy
    
    Add an option, specified by "-S" or "--sort", to sort the ocontexts
    before writing out the binary policy.
    
    Binary policies created by semanage and secilc are always sorted, so
    this option allows checkpolicy to be consistent with those. It has
    not been made the default to maintain backwards compatibility for
    anyone who might be depending on the unsorted behavior of checkpolicy.
    
    Signed-off-by: James Carter <jwcart2@tycho.nsa.gov>
    
  - libsepol: Create policydb_sort_ocontexts()
    
    Create the function called policydb_sort_ocontexts() that calls
    the internal function sort_ocontexts() to sort the ocontexts of
    a policydb.
    
    The function sort_ocontexts() is already used by
    sepol_kernel_policydb_to_conf() and sepol_kernel_policydb_to_cil()
    when converting a binary policy to cil or policy.conf format.
    
    Signed-off-by: James Carter <jwcart2@tycho.nsa.gov>
    
  - libsemanage: improve semanage_migrate_store import failure
    
    The selinux/semanage python module import error in semanage_migrate_store
    was misleading. Before, it would report that the selinux/semanage modules
    were not installed even though they were on the system.
    
    Now the import failure is only reported if the modules are not installed.
    Otherwise, a stack trace is printed for all other errors in the selinux/semanage
    python modules.
    
    Signed-off-by: Yuli Khodorkovskiy <yuli.khodorkovskiy@crunchydata.com>
    
  - restorecond: Do not ignore the -f option
    
    Since the default value of watch_file is set unconditionally *after* the
    command-line arguments have been parsed, the -f option is (and has
    always been) effectively ignored. Fix this by setting it before the
    parsing.
    
    Fixes: 48681bb49c03 ("policycoreutils: restorecond: make restorecond dbuss-able")
    Signed-off-by: Ondrej Mosnacek <omosnace@redhat.com>
    
  - python/sepolicy: Update to work with setools-4.2.0
    
    Change in internal setools API causes sepolicy to crash when processing
    AVRules.
    
        File "python/sepolicy/sepolicy/__init__.py", line 277, in _setools_rule_to_dict
            if isinstance(rule, setools.policyrep.terule.AVRule):
        AttributeError: module 'setools.policyrep' has no attribute 'terule'
    
    See https://github.com/SELinuxProject/setools/issues/8 for more details.
    
    Stop using internal setools API:
    
    - use AttributeError instead of setools specific exceptions
    - evaluate conditional expressions using conditional.evaluate() instead
    of qpol_symbol.is_enabled()
    
    Signed-off-by: Vit Mojzis <vmojzis@redhat.com>
    Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>
    

* Update platform/superproject from branch 'master'
  to 479f0060498f09991fd16cbf2c42c44ee4d3bbd6
  - Update git submodules
    
    * Update external/selinux from branch 'master'
      to cee4ffe06f8e3d979af00444da6c51c34acc05df
      - Merge remote-tracking branch 'aosp/upstream-master' into mymerge
        
        Followed the following steps:
        
          # In repo client
          cd external/selinux
          repo sync .
          repo start mymerge .
          git merge aosp/upstream-master --no-ff # resolve any conflicts
          repo upload .
        
        Test: Android compiles and no obvious problems.
        Change-Id: I526e8c09eb7cb7f73fe771fd1295bb406514589b
        
      - python/semanage: Stop rejecting aliases in semanage commands
        
        Resolves:
        
        \# semanage fcontext -a -t svirt_sandbox_file_t /pokus
        ValueError: Type svirt_sandbox_file_t is invalid, must be a file or device type
        \# semanage fcontext -d -t svirt_sandbox_file_t /pokus
        ValueError: File context for /pokus is not defined
        
        \# seinfo -tsvirt_sandbox_file_t -x
           TypeName container_file_t
           Aliases
              svirt_sandbox_file_t
              svirt_lxc_file_t
        
        Signed-off-by: Vit Mojzis <vmojzis@redhat.com>
        
      - python/sepolicy: Stop rejecting aliases in sepolicy commands
        
        Fix CheckDomain and CheckPortType classes to properly deal with aliases.
        
        Resolves:
           https://bugzilla.redhat.com/show_bug.cgi?id=1600009
        
        Signed-off-by: Vit Mojzis <vmojzis@redhat.com>
        
      - python/sepolicy: Fix "info" to search aliases as well
        
        Restore previous behaviour of "sepolicy.info()".
        
        Signed-off-by: Vit Mojzis <vmojzis@redhat.com>
        
      - README: Update the SELinux mailing list location
        
        Signed-off-by: Stephen Smalley <sds@tycho.nsa.gov>
        
      - libsepol: Add two new Xen initial SIDs
        
        Xen uses the initial SIDs domU and domDM in its toolstack, so it makes
        sense to add these to xen_sid_to_str[] in kernel_to_common.h
        
        Signed-off-by: James Carter <jwcart2@tycho.nsa.gov>
        
      - libsepol: Check that initial sid indexes are within the valid range
        
        When writing CIL from a policy module or when writing CIL or policy.conf
        from a kernel binary policy, check that the initial sid index is within
        the valid range of the selinux_sid_to_str[] array (or xen_sid_to_str[]
        array for a XEN policy). If it is not, then create a unique name
        ("UNKNOWN"+index) for the initial sid.
        
        Signed-off-by: James Carter <jwcart2@tycho.nsa.gov>
        
      - libsepol: Eliminate initial sid string definitions in module_to_cil.c
        
        Since the initial sid strings are defined in kernel_to_common.h,
        module_to_cil.c can use those and its initial sid string definitions
        can be removed.
        
        Signed-off-by: James Carter <jwcart2@tycho.nsa.gov>
        
      - libsepol: Rename kernel_to_common.c stack functions
        
        Want to make use of selinux_sid_to_str[] and xen_sid_to_str[] from
        kernel_to_common.h in module_to_cil.c, but stack functions with the
        same names exist in module_to_cil.c and kernel_to_common.c (with
        the function prototypes in kernel_to_common.h).
        
        Since the stack functions in kernel_to_common.c are less general and
        only work with strings, rename those functions from stack_* to
        strs_stack_*.
        
        Signed-off-by: James Carter <jwcart2@tycho.nsa.gov>
        
      - checkpolicy: Add option to sort ocontexts when creating a binary policy
        
        Add an option, specified by "-S" or "--sort", to sort the ocontexts
        before writing out the binary policy.
        
        Binary policies created by semanage and secilc are always sorted, so
        this option allows checkpolicy to be consistent with those. It has
        not been made the default to maintain backwards compatibility for
        anyone who might be depending on the unsorted behavior of checkpolicy.
        
        Signed-off-by: James Carter <jwcart2@tycho.nsa.gov>
        
      - libsepol: Create policydb_sort_ocontexts()
        
        Create the function called policydb_sort_ocontexts() that calls
        the internal function sort_ocontexts() to sort the ocontexts of
        a policydb.
        
        The function sort_ocontexts() is already used by
        sepol_kernel_policydb_to_conf() and sepol_kernel_policydb_to_cil()
        when converting a binary policy to cil or policy.conf format.
        
        Signed-off-by: James Carter <jwcart2@tycho.nsa.gov>
        
      - libsemanage: improve semanage_migrate_store import failure
        
        The selinux/semanage python module import error in semanage_migrate_store
        was misleading. Before, it would report that the selinux/semanage modules
        were not installed even though they were on the system.
        
        Now the import failure is only reported if the modules are not installed.
        Otherwise, a stack trace is printed for all other errors in the selinux/semanage
        python modules.
        
        Signed-off-by: Yuli Khodorkovskiy <yuli.khodorkovskiy@crunchydata.com>
        
      - restorecond: Do not ignore the -f option
        
        Since the default value of watch_file is set unconditionally *after* the
        command-line arguments have been parsed, the -f option is (and has
        always been) effectively ignored. Fix this by setting it before the
        parsing.
        
        Fixes: 48681bb49c03 ("policycoreutils: restorecond: make restorecond dbuss-able")
        Signed-off-by: Ondrej Mosnacek <omosnace@redhat.com>
        
      - python/sepolicy: Update to work with setools-4.2.0
        
        Change in internal setools API causes sepolicy to crash when processing
        AVRules.
        
            File "python/sepolicy/sepolicy/__init__.py", line 277, in _setools_rule_to_dict
                if isinstance(rule, setools.policyrep.terule.AVRule):
            AttributeError: module 'setools.policyrep' has no attribute 'terule'
        
        See https://github.com/SELinuxProject/setools/issues/8 for more details.
        
        Stop using internal setools API:
        
        - use AttributeError instead of setools specific exceptions
        - evaluate conditional expressions using conditional.evaluate() instead
        of qpol_symbol.is_enabled()
        
        Signed-off-by: Vit Mojzis <vmojzis@redhat.com>
        Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>