Update git submodules
* Update platform/build/soong from branch 'master'
  to 14584beec63d156360590c2871bbaad4974c38cb
  - Merge "Allowlist frameworks/hardware/interfaces/stats/aidl"
  - Allowlist frameworks/hardware/interfaces/stats/aidl
    
    This fixes current breakage on aosp-master-bazel on bp2build-incremental. aosp/2401793 addes android.frameworks.stats-V2-ndk to libtestvendoratoms but android.frameworks.stats aidl_interface is not allowlisted yet.
    
    However, `//frameworks/proto_logging/stats/stats_log_api_gen:libtestvendoratoms` is still not building because of another issue in genrule + proto.
    
    ```
    ERROR: out/soong/workspace/frameworks/proto_logging/stats/stats_log_api_gen/BUILD.bazel:87:8: Executing genrule //frameworks/proto_logging/stats/stats_log_api_gen:test_vendor_atoms.cpp failed: (Segmentation fault): bash failed: error executing command (from target //frameworks/proto_logging/stats/stats_log_api_gen:test_vendor_atoms.cpp) /bin/bash -c ... (remaining 1 argument skipped)i
    ```
    
    The fix to this is similar to aosp/2401794 and is fixed in aosp/2449265
    
    Test: presubmit
    Bug: 270131691
    Change-Id: I8bcc336d843ee4f0de44f377c828a9a4c959b0ec