Update git submodules
* Update platform/packages/modules/DnsResolver from branch 'master'
  to 9b879a6b28354518ec8b06914e90d982f79babc5
  - Merge "Fix tidy warnings for r399163 Clang update."
  - Fix tidy warnings for r399163 Clang update.
    
    Fix tidy warnings signed char -> int conversions.
    
    /disk/android_trees/aosp-master-plus-llvm/packages/modules/DnsResolver/res_comp.cpp:144:28: error: 'signed char' to 'int' conversion; consider casting to 'unsigned char' first. [cert-str34-c,-warnings-as-errors]
        int pch = PERIOD, ch = *dn++;
                               ^
    /disk/android_trees/aosp-master-plus-llvm/packages/modules/DnsResolver/res_comp.cpp:147:19: error: 'signed char' to 'int' conversion; consider casting to 'unsigned char' first. [cert-str34-c,-warnings-as-errors]
            int nch = *dn++;
                      ^
    /disk/android_trees/aosp-master-plus-llvm/packages/modules/DnsResolver/res_comp.cpp:168:18: error: 'signed char' to 'int' conversion; consider casting to 'unsigned char' first. [cert-str34-c,-warnings-as-errors]
        while ((ch = *dn++) != '\0')
                     ^
    
    Fix tidy warnings for unused result by casting to void.
    
    /disk/android_trees/aosp-master-plus-llvm/packages/modules/DnsResolver/tests/dns_responder/dns_tls_frontend.cpp:155:5: error: the value returned by this function should be used [bugprone-unused-return-value,-warnings-as-errors]
        connect(backend_socket_.get(), backend_ai_res->ai_addr, backend_ai_res->ai_addrlen);
        ^
    
    Bug: http://b/155835175
    Test: m
    
    Change-Id: Iada74f5c50a563012bfd26cee9088a3a72371f56
    
  - Merge "Make uid related tests compatible with Android Q" am: 05a0868b1f
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1381536
    
    Change-Id: I37e7b41b37b191445a684616bb4ebb4191b7dd60
    
  - Move RootTargetPreparer to the front of FilePusher for DnsResolver test xmls am: 957333d2a9
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1373696
    
    Change-Id: I29365164da301a0ffad7ffd8ed91931007c42bc9
    
  - Merge "Add VPN test for DnsResolver" am: 12fb6a1966
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1361616
    
    Change-Id: Ic03f2fe20fdcc64f01a27dcd8fee3c9bc98c67b0
    
  - Clean up gPrivateDnsConfiguration am: 6024824b2a
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1375918
    
    Change-Id: Icfdb066629e5488ec048c5e7610293489373bf8b
    
  - Merge "Enable mainline-presubmit for DnsResolver" am: 914656b6f4
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1373697
    
    Change-Id: I30d09bf989bbfe2dfc9c08cfd14408bcf37c5864
    
  - Fchown DNS query socket with AID_DNS when sdk version < 30 am: 6a9603a187
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1376317
    
    Change-Id: I39b493cd7b62bb20bf66bd90478e5d71615064a1
    
  - Update language to comply with Android's inclusive language guidance am: 96b09e2e84
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1375916
    
    Change-Id: I3c4e1fcfc7c05b4a2969f7d84c2e9f46188453e5
    
  - DnsResolver - improve aosp api level detection am: ebe06e8bab
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1366616
    
    Change-Id: Iea6a7829bd7aa0a946818bf07f272e2470f33809
    
  - DnsResolver - disable fchown() on Q am: fc9aa724a6
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1364661
    
    Change-Id: Iba24d98033c0c3c57b7c7e2bb8930eeaeb5aed47
    
  - DnsResolver - improve api level detection for aosp am: 701238f551
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1364656
    
    Change-Id: I210d3a4b33ecd6f56a161ff9789dd1e5ddf8519e
    
  - Support prioritizing DNS servers am: 61d1726705
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1243491
    
    Change-Id: I96359e44b18315f1235260026bb94bea92ef1310
    
  - Support multinetwork tests am: 6ce587d2c3
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1195355
    
    Change-Id: Ib0ba4f1763fd776db4f2d5720203a2b9b68b88a6
    
  - Fix private DNS not working due to getConnectCounter() stuck am: 568ed6c942
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1354544
    
    Change-Id: I82e479aa58329c48dc8455fb7ea380492b5c99e2
    
  - Add presubmit test for DNS resolver AIDL changes am: 159d3745e1
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1353343
    
    Change-Id: I003f8a502bc20dbbb04f1a6ac0fc62231290039a
    
  - Merge changes from topic "fchown" am: e816b9a3f7
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1343376
    
    Change-Id: Ief585975f48ab356cf879161d13773a7441a8ecc
    
  - Fix flaky tests due to onDnsEvent am: b8faac4252
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1344817
    
    Change-Id: I887012830441151ba9515aa419e4b24cd7ffe9d0
    
  - Merge "onDnsEvent check in resolv_integration_test" am: 8430b00027
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1343256
    
    Change-Id: Ib055cf7f63b625747482e4d0eb9c30db7813da6c
    
  - Merge "Rename "Westworld" to "Statsd"" am: 8d1de24afc
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1340497
    
    Change-Id: Ia6d14b65a5c44d059919dec85201ff9c170981b0
    
  - Allow only AID_ROOT to inject certificate am: 26dc2b0a7d
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1339796
    
    Change-Id: I0c0dd5e4fdfdb0b4d5c52931d700f401bc498fa6
    
  - Merge "Remove RESOLV_INJECT_CA_CERTIFICATE" am: 5b757efb3f
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1210063
    
    Change-Id: I4d262a44f2ac664e7df45d08de4e3692c914ac3c
    
  - Merge "Add GetResolverStats to cache unit test" am: 7d86afeb41
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1292816
    
    Change-Id: I3ee0dc7040e27bb31beb99b3d7a26468d633dcbd
    
  - libnetd_resolv, resolv_stress_test - switch to dnsresolver_aidl_interface-unstable-ndk_platform am: 3d8093622a
    
    Original change: https://android-review.googlesource.com/c/platform/packages/modules/DnsResolver/+/1323339
    
    Change-Id: Ie74a3ad31b9a6fe3d7cae58cb79a04aec1d92ecc
    

* Update platform/superproject from branch 'master'
  to d9b6a7eef8a0feada406262919b5251134717976
  - Update git submodules
    
    * Update packages/modules/DnsResolver from branch 'master'
      to 9b879a6b28354518ec8b06914e90d982f79babc5
      - Merge "Fix tidy warnings for r399163 Clang update."
      - Fix tidy warnings for r399163 Clang update.
        
        Fix tidy warnings signed char -> int conversions.
        
        /disk/android_trees/aosp-master-plus-llvm/packages/modules/DnsResolver/res_comp.cpp:144:28: error: 'signed char' to 'int' conversion; consider casting to 'unsigned char' first. [cert-str34-c,-warnings-as-errors]
            int pch = PERIOD, ch = *dn++;
                                   ^
        /disk/android_trees/aosp-master-plus-llvm/packages/modules/DnsResolver/res_comp.cpp:147:19: error: 'signed char' to 'int' conversion; consider casting to 'unsigned char' first. [cert-str34-c,-warnings-as-errors]
                int nch = *dn++;
                          ^
        /disk/android_trees/aosp-master-plus-llvm/packages/modules/DnsResolver/res_comp.cpp:168:18: error: 'signed char' to 'int' conversion; consider casting to 'unsigned char' first. [cert-str34-c,-warnings-as-errors]
            while ((ch = *dn++) != '\0')
                         ^
        
        Fix tidy warnings for unused result by casting to void.
        
        /disk/android_trees/aosp-master-plus-llvm/packages/modules/DnsResolver/tests/dns_responder/dns_tls_frontend.cpp:155:5: error: the value returned by this function should be used [bugprone-unused-return-value,-warnings-as-errors]
            connect(backend_socket_.get(), backend_ai_res->ai_addr, backend_ai_res->ai_addrlen);
            ^
        
        Bug: http://b/155835175
        Test: m
        
        Change-Id: Iada74f5c50a563012bfd26cee9088a3a72371f56