Update git submodules
* Update platform/superproject from branch 'master'
  to e2d9f2e2b65792a07042fc1558620a1052342511
  - Update git submodules
    
    * Update tools/tradefederation/core from branch 'master'
      to 36c8bc2e0ab114caf0e8a74c6c8b3b65de4c5a3a
      - Merge "Atest: fix NoneType of atest_unittest.py."
      - Atest: fix NoneType of atest_unittest.py.
        
        Running unit tests will seldom encounter flaky test failure:
          self.assertTrue(data_time)
          AssertionError: None is not true
        tempfile.mkdkdtemp() generates hashed filename which contains "_" so the
        previous parsing would be faulty when the string is YYYYMMDD_HHMM__<hash>
        
        Bug: 147202893
        
        Test: source build/envsetup.sh; lunch
          croot tools/tradefederation/core/atest
          ./run_atest_unittests.sh
          ./atest_run_unittests.py
        
        Change-Id: I02d15d79765d94882b67f86b0c733a02ae357284
        

* Update platform/tools/tradefederation.git from branch 'master'
  to 36c8bc2e0ab114caf0e8a74c6c8b3b65de4c5a3a
  - Merge "Atest: fix NoneType of atest_unittest.py."
  - Atest: fix NoneType of atest_unittest.py.
    
    Running unit tests will seldom encounter flaky test failure:
      self.assertTrue(data_time)
      AssertionError: None is not true
    tempfile.mkdkdtemp() generates hashed filename which contains "_" so the
    previous parsing would be faulty when the string is YYYYMMDD_HHMM__<hash>
    
    Bug: 147202893
    
    Test: source build/envsetup.sh; lunch
      croot tools/tradefederation/core/atest
      ./run_atest_unittests.sh
      ./atest_run_unittests.py
    
    Change-Id: I02d15d79765d94882b67f86b0c733a02ae357284