Update git submodules
* Update platform/external/toolchain-utils from branch 'master'
  to f5cc9231be5ecd6d0159b352dfb014926bfa77e6
  - Merging 15 commit(s) from Chromium's toolchain-utils
    
    Merged commit digest:
      028b14d toolchain-utils: Remove 'target' from distfiles path (for cleanup).
      bd1004a toolchain-utils: Fix hyphen/underscore issue for nightly tests.
      d5d49d2 afdo_metadata: Publish the new kernel profiles
      d796e2c default_remotes: fix a typo
      9d35abc llvm_tools: update upstream branch names to point to `main`
      369072a default_remotes: Update toolchain DUT names
      4a8085e compiler_wrapper: move llvm-next options to clang options
      2c27f0a llvm_tools: pass cl number as str to avoid type error
      2421372 afdo_metadata: Publish the new kernel profiles
      cb138b5 afdo_metadata: Publish the new kernel profiles
      8c34e96 crosperf: Fix BadChecksum failure on coral
      6da42e5 afdo_metadata: Publish the new kernel profiles
      84b5c8f compiler_wrapper: report parent processes' info in warnings tarballs
      49187a5 afdo_metadata: Publish the new kernel profiles
      602351c update_kernel_afdo: use gsutil.py instead of gsutil
    
    Change-Id: I6d94b7821404b85366f1f1c0b0f3fd8ecec8ded4
    
  - Mark ab/7061308 as merged in stage.
    
    Bug: 180401296
    Merged-In: I5950e7445c94969a7714d289da6babcd5a82de11
    Change-Id: I7f51135ba3d274f2f5a4c2cf011ee663b709aa86
    
  - toolchain-utils: Remove 'target' from distfiles path (for cleanup).
    
    'target' is no longer part of the path from distfiles to chrome-src,
    so this CL fixes the path inour cleanup script.
    
    BUG=None
    TEST=tested script by hand.
    
    Change-Id: I8a69b0d153a301b61c5176e44d1ad65dc8e467cd
    Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/toolchain-utils/+/2585652
    Auto-Submit: Caroline Tice <cmtice@chromium.org>
    Tested-by: Caroline Tice <cmtice@chromium.org>
    Commit-Queue: Manoj Gupta <manojgupta@chromium.org>
    Reviewed-by: Manoj Gupta <manojgupta@chromium.org>
    
  - toolchain-utils: Fix hyphen/underscore issue for nightly tests.
    
    The recipe builders use hyphens, while gsutil uses underscores.  We
    had a fix in place for this for veyron_minnie; this updates the fix for
    veyron_tiger.
    
    BUG=None
    TEST=None
    
    Change-Id: Ide32264e1cbbe29afc8ca2cd44e449b56f91a2c1
    Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/toolchain-utils/+/2585646
    Auto-Submit: Caroline Tice <cmtice@chromium.org>
    Reviewed-by: Manoj Gupta <manojgupta@chromium.org>
    Commit-Queue: Caroline Tice <cmtice@chromium.org>
    Tested-by: Caroline Tice <cmtice@chromium.org>
    
  - afdo_metadata: Publish the new kernel profiles
    
    Update chromeos-kernel-3_18 to R89-13638.0-1607337469
    Update chromeos-kernel-4_4 to R89-13638.0-1607337135
    Update chromeos-kernel-4_14 to R89-13638.0-1607337215
    Update chromeos-kernel-4_19 to R89-13638.0-1607337429
    
    BUG=None
    TEST=Verified in kernel-release-afdo-verify-orchestrator.
    
    Change-Id: I994ba9effc664cab904fccdbe0a207436ac2ea48
    Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/toolchain-utils/+/2580915
    Reviewed-by: Tiancong Wang <tcwang@google.com>
    Commit-Queue: Caroline Tice <cmtice@chromium.org>
    Tested-by: Caroline Tice <cmtice@chromium.org>
    
  - default_remotes: fix a typo
    
    Change "tigger" to "tiger". Also update a unit test.
    
    BUG=chromium:1156409
    
    TEST=None.
    
    Change-Id: I2dd394ccdfa79632e637cbefddf559e95296c8c1
    Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/toolchain-utils/+/2580398
    Reviewed-by: Tiancong Wang <tcwang@google.com>
    Tested-by: Jian Cai <jiancai@google.com>
    
  - llvm_tools: update upstream branch names to point to `main`
    
    LLVM recently renamed their `master` branch to `main` upstream. This
    changes our tooling to search for the latter name instead.
    
    BUG=None
    TEST=Unittests; ran `git llvm-rev --sha HEAD` in an up-to-date llvm
    repo.
    
    Change-Id: Icdc6dac48fda7697d18d0d77935e46670273bf84
    Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/toolchain-utils/+/2577643
    Reviewed-by: Manoj Gupta <manojgupta@chromium.org>
    Tested-by: George Burgess <gbiv@chromium.org>
    
  - default_remotes: Update toolchain DUT names
    
    Replace veyron_minnie with a newer model as it reaches end of life.
    
    BUG=b:170402899
    TEST=None
    
    Change-Id: I0caf06b84b465dcc88a3fdd9dc7d19f13fcd11b9
    Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/toolchain-utils/+/2574734
    Reviewed-by: Tiancong Wang <tcwang@google.com>
    Tested-by: Jian Cai <jiancai@google.com>
    
  - compiler_wrapper: move llvm-next options to clang options
    
    The new Clang version has a number of new warnings which we disable. This CL
    makes those apply to llvm (current) as well as llvm-next.
    
    BUG=None
    TEST=go test
    
    Change-Id: I1f4929580953003d21676e7e72af4577592fb217
    Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/toolchain-utils/+/2561725
    Reviewed-by: Manoj Gupta <manojgupta@chromium.org>
    Tested-by: Manoj Gupta <manojgupta@chromium.org>
    Commit-Queue: Manoj Gupta <manojgupta@chromium.org>
    
  - Mark ab/6881855 as merged am: 0b5abeb0d5
    
    Original change: https://googleplex-android-review.googlesource.com/c/platform/external/toolchain-utils/+/13112912
    
    Change-Id: I5950e7445c94969a7714d289da6babcd5a82de11
    
  - Mark ab/6881855 as merged
    
    Bug: 172690556
    Change-Id: Ia6891e0924374e831be2959d60de2423ec788880
    
  - llvm_tools: pass cl number as str to avoid type error
    
    llvm_bisection.py invokes the Gerrit CLI to abandon CLs created as part of the bisection. It passes a CL number to the command. Before this change, the CL number was passed as an int, which leads to the following error:
    
      Traceback (most recent call last):
        File "./auto_llvm_bisection.py", line 103, in main
          bisection_ret = llvm_bisection.main(args_output)
        File "/usr/local/google/home/inglorion/chromiumos/src/third_party/toolchain-utils/llvm_tools/llvm_bisection.py", line 364, in main
          subprocess.check_output([gerrit, 'abandon', build['cl']],
        File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/usr/lib/python3.8/subprocess.py", line 489, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.8/subprocess.py", line 1637, in _execute_child
          self.pid = _posixsubprocess.fork_exec(
      TypeError: expected str, bytes or os.PathLike object, not int
    
    With this change, we convert the value to an str first, avoiding the type error.
    
    BUG=chromium:1151325
    TEST=run auto_llvm_bisection.py
    
    Change-Id: I2b151c76757067f536712f69b14d6be549ee7c75
    Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/toolchain-utils/+/2551789
    Reviewed-by: Manoj Gupta <manojgupta@chromium.org>
    Reviewed-by: Jian Cai <jiancai@google.com>
    Tested-by: Bob Haarman <inglorion@chromium.org>
    
  - afdo_metadata: Publish the new kernel profiles
    
    Update chromeos-kernel-3_18 to R88-13577.0-1605522740
    Update chromeos-kernel-4_4  to R88-13577.0-1605523015
    Update chromeos-kernel-4_14 to R88-13577.0-1605522850
    Update chromeos-kernel-4_19 to R88-13577.0-1605522896
    
    BUG=None
    TEST=Verified in kernel-release-afdo-verify-orchestrator
    
    Change-Id: I75595037318c871b828f625b376000a6794ec65d
    Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/toolchain-utils/+/2542722
    Reviewed-by: Manoj Gupta <manojgupta@chromium.org>
    Commit-Queue: Tiancong Wang <tcwang@google.com>
    Tested-by: Tiancong Wang <tcwang@google.com>
    
  - afdo_metadata: Publish the new kernel profiles
    
    Update afdo cwp kernel profiles to R88-13577 version.
    
    BUG=None
    TEST=None
    
    Change-Id: I6acae2a8d6a47fa8f6d4a21d7b63ac75c5a0799b
    Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/toolchain-utils/+/2530409
    Reviewed-by: Tiancong Wang <tcwang@google.com>
    Tested-by: Manoj Gupta <manojgupta@chromium.org>
    
  - crosperf: Fix BadChecksum failure on coral
    
    Ignore "core id", "apicid", "initial apicid" fields from cpuinfo in
    machine checksum calculation. The values may differ on the same type of
    machines.
    
    Add more descriptive output for the BadChecksum error.
    Unittest is updated accordingly.
    
    BUG=chromium:1145386
    TEST=./run_tests.sh in crosperf.
    
    Change-Id: Ifcc91fb70f02c41d77787fbb665741bc130152c0
    Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/toolchain-utils/+/2523398
    Tested-by: Denis Nikitin <denik@chromium.org>
    Reviewed-by: Bob Haarman <inglorion@chromium.org>
    Commit-Queue: Denis Nikitin <denik@chromium.org>
    
  - afdo_metadata: Publish the new kernel profiles
    
    Update chromeos-kernel-3_18 to R88-13560.0-1604313218
    Update chromeos-kernel-4_4  to R88-13560.0-1604313145
    Update chromeos-kernel-4_14 to R88-13560.0-1604313396
    Update chromeos-kernel-4_19 to R88-13560.0-1604313185
    
    BUG=None
    TEST=Verified in kernel-release-afdo-verify-orchestrator
    
    Change-Id: I43d2604122c5af90ed7bdb47663bcf4c1b6a59aa
    Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/toolchain-utils/+/2523230
    Tested-by: Tiancong Wang <tcwang@google.com>
    Reviewed-by: Tiancong Wang <tcwang@google.com>
    Commit-Queue: Tiancong Wang <tcwang@google.com>
    
  - compiler_wrapper: report parent processes' info in warnings tarballs
    
    The bug I'm chasing down right now depends on environment variables, and
    could be due to a `make` invocation in one of N places. Having this
    context available to me is useful.
    
    It seriously pollutes the JSON we dump, but use of `jq` that I've put in
    the doc about this makes that a non-issue.
    
    BUG=None
    TEST=Ran on stress-ng. parent process info was dumped.
    
    Change-Id: Ib4d3b6c9887b4cf2a38472ef299c81af27e9a617
    Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/toolchain-utils/+/2481829
    Reviewed-by: Manoj Gupta <manojgupta@chromium.org>
    Tested-by: George Burgess <gbiv@chromium.org>
    
  - afdo_metadata: Publish the new kernel profiles
    
    Update chromeos-kernel-3_18 to R88-13531.0-1603099914
    Update chromeos-kernel-4_4  to R88-13531.0-1603100212
    Update chromeos-kernel-4_14 to R88-13505.11-1603100505
    Update chromeos-kernel-4_19 to R88-13531.0-1603100310
    
    BUG=None
    TEST=Verified in kernel-release-afdo-verify-orchestrator
    
    Change-Id: Ife0010abb801c80f1de503a88c36f342891ad0cf
    Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/toolchain-utils/+/2489892
    Reviewed-by: Manoj Gupta <manojgupta@chromium.org>
    Commit-Queue: Bob Haarman <inglorion@chromium.org>
    Tested-by: Bob Haarman <inglorion@chromium.org>
    
  - update_kernel_afdo: use gsutil.py instead of gsutil
    
    This changes update_kernel_afdo to call gsutil.py instead of
    gsutil (without the ".py"). Reason: the non-.py does not exist
    everywhere, whereas gsutil.py is part of depot_tools.
    
    BUG=None
    TEST=./afdo_tools/update_kernel_afdo
    
    Change-Id: I7c2192f5d4ef85852a4c5023edb29e9a092bbb8d
    Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/toolchain-utils/+/2490652
    Tested-by: Bob Haarman <inglorion@chromium.org>
    Reviewed-by: George Burgess <gbiv@chromium.org>
    Reviewed-by: Manoj Gupta <manojgupta@chromium.org>
    
  - Merging 84 commit(s) from Chromium's toolchain-utils am: 1e576757bc am: 12fcdf982e am: 76b8300539
    
    Original change: https://android-review.googlesource.com/c/platform/external/toolchain-utils/+/1469797
    
    Change-Id: I7d81870a25d8bc5516207e6d5fc751482f46efea
    
  - Merging 84 commit(s) from Chromium's toolchain-utils am: 1e576757bc am: 12fcdf982e
    
    Original change: https://android-review.googlesource.com/c/platform/external/toolchain-utils/+/1469797
    
    Change-Id: I2a31be48f21081cf60c64e4525ecffa425c12346
    
  - Merging 84 commit(s) from Chromium's toolchain-utils am: 1e576757bc
    
    Original change: https://android-review.googlesource.com/c/platform/external/toolchain-utils/+/1469797
    
    Change-Id: I9b1cd41e1cd7d67b963f80c582431b9516bf474f
    
  - Merging 2 commit(s) from Chromium's toolchain-utils am: b8e15db276 am: 06d9af65e4 am: 524e03e040 am: 740c99ffa8
    
    Original change: https://android-review.googlesource.com/c/platform/external/toolchain-utils/+/1343843
    
    Change-Id: I8a7c041ba7e3a814a428dc8725fd9286b93968b1
    
  - Symlink to android_llvm_next_flags.go in toolchain/llvm_android am: 0c0e1d6933 am: dc3fb12b0b am: af480e6a40 am: 401b7d7e50
    
    Original change: https://android-review.googlesource.com/c/platform/external/toolchain-utils/+/1340193
    
    Change-Id: I5d94b0c8a301f480080654185320245e48abf565
    
  - Merging 104 commit(s) from Chromium's toolchain-utils am: d808730430 am: dba8f92d04 am: 6df2365782 am: 164ad124cf
    
    Original change: https://android-review.googlesource.com/c/platform/external/toolchain-utils/+/1336029
    
    Change-Id: I12afd57711addaf3d10e0f4083cf135a5beea30d
    
  - Add METADATA to toolchain-utils: BSD+Apache2=NOTICE am: 6afd39284f am: 8ee1427ba8 am: 9f3a8343b2 am: 92f02322a8
    
    Change-Id: Ief4d99d00a2a7ab0dc5b264a6df28a4cb2fd0637
    
  - [automerger skipped] DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp into stag-aosp-master am: 5550639230 -s ours am: bef6d7497b am: 64136af531
    
    Change-Id: I98bfa8257cdd13048fa8c2479a36eb1201331056
    
  - Merging 9 commit(s) from Chromium's toolchain-utils am: 35b8ca1aa6 am: 3868531aa1 am: 9407fae111 am: 9311b02c20
    
    Change-Id: I29c38b1edd38aeba06d2341cd56e9049ac4acaf0
    
  - [automerger skipped] DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp@6304901 into stag-aosp-master am: 6e961ec81b -s ours am: 3af89f7913 am: 97f1cae011
    
    Change-Id: Id128d3394c1ce2de78719bcf8ebbfbc53041e799
    
  - Merging 7 commit(s) from Chromium's toolchain-utils am: c6166ac212 am: 003407a0e0 am: b060c18167 am: 1e8e9b4386
    
    Change-Id: I6a9562a43e2bdf94ce2ec336b2fd9193237046ae
    
  - Merging 11 commit(s) from Chromium's toolchain-utils am: d87896de8a am: d4e3d10615 am: 2560bcf333 am: 8031b78ce5
    
    Change-Id: I3d326cf81282e9ad068fbebc2e64a0ec7b72b8d3
    
  - Merging 13 commit(s) from Chromium's toolchain-utils am: 1c417d433e am: 73b35a2885 am: 7fdcb8e548 am: 6e4d049f45
    
    Change-Id: I32883f40bbb1fba5fc259c8482d388bfc77c3fc3