Update git submodules
* Update platform/system/core from branch 'master'
  to 57a935613c39fa8cd02d7dec5c68a992fbbccc4d
  - Merge "fastboot: Fix missing endian header in fastboot_driver.h to avoid header confusion"
  - fastboot: Fix missing endian header in fastboot_driver.h to avoid header confusion
    
    So fastboot_driver.h includes <android-base/logging.h>, but that
    file has a dependency on <android-base/endian.h>. So if
    fastboot_driver.h gets included somewhere before
    <android-base/endian.h>, it results in *very* opaque error
    message:
    
    system/core/fastboot/fastboot.cpp:1490:9: error: expected unqualified-id
            LOG(VERBOSE) << "Cannot optimize flashing super on non-AB device";
            ^
    system/libbase/include/android-base/logging.h:221:23: note: expanded from macro 'LOG'
                          ^
    system/libbase/include/android-base/logging.h:227:4: note: expanded from macro 'LOGGING_PREAMBLE'
      (WOULD_LOG(severity) &&                                                                  \
       ^
    system/libbase/include/android-base/logging.h:202:40: note: expanded from macro 'WOULD_LOG'
      (UNLIKELY(::android::base::ShouldLog(SEVERITY_LAMBDA(severity), _LOG_TAG_INTERNAL)) || \
                                           ^
    system/libbase/include/android-base/logging.h:174:26: note: expanded from macro 'SEVERITY_LAMBDA'
      using ::android::base::ERROR;               \
                             ^
    prebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8/x86_64-w64-mingw32/include/wingdi.h:75:15: note: expanded from macro 'ERROR'
                  ^
    
    This patch includes <android-base/endian.h> before
    <android-base/logging.h> to avoid this issue.
    
    Reported-by: Daniel Zheng <zhengdaniel@google.com>
    Signed-off-by: John Stultz <jstultz@google.com>
    Change-Id: I8752f2cdbef5b13901f0f4e8adfe60a21db785b6