Update git submodules
* Update platform/cts from branch 'master'
  to a3a89ab37801f885a0b789acc52bad71588f1325
  - Merge changes I05285811,I782f8a06,I7c5bf823,I7bb2a7e4
    
    * changes:
      Ensure location is enabled before getting SSID.
      Fix a regression in how required properties are collected.
      Fix Error Prone errors
      Reland "Pull service dumps to help debug test failures."
    
  - Ensure location is enabled before getting SSID.
    
    When location is disabled, Wi-Fi scan results and SSID are not available
    to apps.
    
    Fixes: 153850762
    Fixes: 153396893
    Test: atest hostsidetests/net/src/com/android/cts/net/HostsideRestrictBackgroundNetworkTests.java
    Change-Id: I05285811d7131e116d5e1d072137ed2cf9576d05
    Merged-In: I05285811d7131e116d5e1d072137ed2cf9576d05
    
  - Fix a regression in how required properties are collected.
    
    + Enable app standby mode before running the tests.
    
    Fixes: 147459100
    Fixes: 117169751
    Test: atest hostsidetests/net/src/com/android/cts/net/HostsideRestrictBackgroundNetworkTests.java
    Test: cts-tradefed run singleCommand cts-on-gsi --skip-device-info \
          --skip-preconditions -m CtsHostsideNetworkTests \
          -t com.android.cts.net.HostsideRestrictBackgroundNetworkTests
    
    Change-Id: I782f8a06922622d28f9a9d5c9f2afa2b12f8aa80
    Merged-In: I782f8a06922622d28f9a9d5c9f2afa2b12f8aa80
    
  - Fix Error Prone errors
    
    Soong wasn't including android_app or android_test sources in the
    javac-check target used for the Error Prone build, which allowed
    some Error Prone errors to get in.  Fix them so Error Prone can be
    re-enabled for these targets.
    
    Fixes:
    cts/hostsidetests/net/app/src/com/android/cts/net/hostside/RequiredPropertiesRule.java:61: error: [CollectionIncompatibleType] Argument '~requiredProperty.getValue()' should not be passed to this method; its type int is not compatible with its collection's type argument Property
    
    Bug: 146455923
    Test: m RUN_ERROR_PRONE=true javac-check
    Change-Id: I7c5bf823bf371902285ce3ee3929796fa40c653b
    Merged-In: I48b1ccb61c807d0b41a165298ef5981258d6656e
    
  - Reland "Pull service dumps to help debug test failures."
    
    + Convert tests to use Junit4
    + Add annotations to specify required conditions for the test to run.
    
    This reverts commit ac34967dba05fa78db298c5e500c387c3d2517e2.
    
    Bug: 137859686
    Change-Id: I7bb2a7e4b2dca3696761e7c030f3380b9226b676
    Merged-In: I93317c201a0ea06732e29154ab7e140735381f59
    

* Update platform/superproject from branch 'master'
  to 4b002344602d4f81a369893ee055ff697e930b0d
  - Update git submodules
    
    * Update cts from branch 'master'
      to a3a89ab37801f885a0b789acc52bad71588f1325
      - Merge changes I05285811,I782f8a06,I7c5bf823,I7bb2a7e4
        
        * changes:
          Ensure location is enabled before getting SSID.
          Fix a regression in how required properties are collected.
          Fix Error Prone errors
          Reland "Pull service dumps to help debug test failures."
        
      - Ensure location is enabled before getting SSID.
        
        When location is disabled, Wi-Fi scan results and SSID are not available
        to apps.
        
        Fixes: 153850762
        Fixes: 153396893
        Test: atest hostsidetests/net/src/com/android/cts/net/HostsideRestrictBackgroundNetworkTests.java
        Change-Id: I05285811d7131e116d5e1d072137ed2cf9576d05
        Merged-In: I05285811d7131e116d5e1d072137ed2cf9576d05
        
      - Fix a regression in how required properties are collected.
        
        + Enable app standby mode before running the tests.
        
        Fixes: 147459100
        Fixes: 117169751
        Test: atest hostsidetests/net/src/com/android/cts/net/HostsideRestrictBackgroundNetworkTests.java
        Test: cts-tradefed run singleCommand cts-on-gsi --skip-device-info \
              --skip-preconditions -m CtsHostsideNetworkTests \
              -t com.android.cts.net.HostsideRestrictBackgroundNetworkTests
        
        Change-Id: I782f8a06922622d28f9a9d5c9f2afa2b12f8aa80
        Merged-In: I782f8a06922622d28f9a9d5c9f2afa2b12f8aa80
        
      - Fix Error Prone errors
        
        Soong wasn't including android_app or android_test sources in the
        javac-check target used for the Error Prone build, which allowed
        some Error Prone errors to get in.  Fix them so Error Prone can be
        re-enabled for these targets.
        
        Fixes:
        cts/hostsidetests/net/app/src/com/android/cts/net/hostside/RequiredPropertiesRule.java:61: error: [CollectionIncompatibleType] Argument '~requiredProperty.getValue()' should not be passed to this method; its type int is not compatible with its collection's type argument Property
        
        Bug: 146455923
        Test: m RUN_ERROR_PRONE=true javac-check
        Change-Id: I7c5bf823bf371902285ce3ee3929796fa40c653b
        Merged-In: I48b1ccb61c807d0b41a165298ef5981258d6656e
        
      - Reland "Pull service dumps to help debug test failures."
        
        + Convert tests to use Junit4
        + Add annotations to specify required conditions for the test to run.
        
        This reverts commit ac34967dba05fa78db298c5e500c387c3d2517e2.
        
        Bug: 137859686
        Change-Id: I7bb2a7e4b2dca3696761e7c030f3380b9226b676
        Merged-In: I93317c201a0ea06732e29154ab7e140735381f59