Update git submodules
* Update platform/external/perfetto from branch 'master'
  to 658b80ff71e10b4b565c3fc88a633f9931c46e03
  - Merge changes I17004086,I72cc32fd,Ib2d3b7ce
    
    * changes:
      trace_processor: hackily allow empty callstacks in perf_sample table
      traced_perf: support counter-only mode (v0: just the timebase count)
      traced_perf: proto: initial counter-only mode (just the timebase count)
    
  - Merge "Remove check(...) to check_support(...) in traced_value.h"
  - Remove check(...) to check_support(...) in traced_value.h
    
    This is to avoid name collision with an existing macro in eureka repo,
    otherwise the following error will appear:
    
    /third_party/perfetto/include/perfetto/tracing/traced_value.h:371:53:
    error: too many arguments provided to function-like macro invocation
    static Yes& check(check_traced_value_support_t<V, int>);
    ^
    /usr/local/google/home/mosaic-role/workspace/eureka-internal/eureka/
    manifest/default.xml/master/external/opencflite/CoreFoundation/../
    include/AssertMacros.h:231:12: note: macro 'check' defined here
    ^
    
    Bug: b/180544354, b/180408157
    Test: CQ
    Change-Id: Ifaf3f7bb766e446ca04231d95db2ad1c6994f0e6
  - trace_processor: hackily allow empty callstacks in perf_sample table
    
    We're adding counter-only samples, which will be emitted as either a
    sample without a callsite_iid, or a callsite with zero frames (something
    that the rest of the parsing doesn't assume is possible).
    
    Relax the parser's assumption with a hacky fix (-1 is used elsewhere for
    invalid IDs according to Lalit). The proper fix is likely to break the
    inheritance of perf_sample table, and make the callsite id column
    optional.
    
    Bug: 180437026
    Change-Id: I17004086306aafeb01f09f5a9364671638041801
    
  - traced_perf: support counter-only mode (v0: just the timebase count)
    
    Even when doing stack sampling, we will now record the timebase count,
    as it should have negligible impact on the trace size.
    
    Note that I'm not being strictly backwards-compatible for existing
    configs, which always implied stack sampling. Now you have to set the
    |perf_event_config.callstack_sampling| proto field to get the sampling.
    I think it's fine since it only affects configs since this Monday's
    refactoring. Configs older than that had to set |all_cpus| to true to
    pass parsing, so I'm using that fact to keep legacy configs' behaviour.
    
    Bug: 180437026
    Change-Id: I72cc32fd31e5ce0f78df43ffaabe81d02e77f7d9
  - traced_perf: proto: initial counter-only mode (just the timebase count)
    
    Starting with a couple of enum values for demonstration purposes,
    adding more should be trivial once we agree on the proto and logic.
    
    Bug: 180437026
    Change-Id: Ib2d3b7ce5c3138221dfeb7f38447db32a00b68ae