Update git submodules
* Update platform/system/netd from branch 'master'
  to 6f528dd01fc5e80a6590ef729ed9302b11fa7fb6
  - [clang-tidy] Disable performance-no-int-to-ptr
    
    Bug: http://b/182416023
    
    This warning is added by new clang update (clang-r416183).
    
    packages/modules/DnsResolver/gethnamaddr.cpp:367:10: error: integer to
    pointer cast pessimizes optimization opportunities
    [performance-no-int-to-ptr,-warnings-as-errors]
        bp = (char*) ALIGN(bp);
    
    packages/modules/DnsResolver/sethostent.cpp:124:19: error: integer to
    pointer cast pessimizes optimization opportunities
    [performance-no-int-to-ptr,-warnings-as-errors]
                ptr = (char*) ALIGN(ptr);
    
    Test: Build with clang-r416183 and verify build.
    Change-Id: I6de904acabee1ddd8a9741f793458433a1bc0041