Update git submodules
* Update platform/external/google-benchmark from branch 'master'
  to 846b7549b6b43c6947f53b1e94968558d5a36830
  - Upgrade google-benchmark to dce3322a549650d18f50b5f1428a5942327ab6a5
    
    Test: make
    Change-Id: I07850ca99c79dd2225cb48821200a365b90e4d2c
    
  - Add support for z/OS XL compiler inline asm syntax (#1063)
    
    On s390 architecture, z/OS XL compiler uses HLASM inline assembly, which has different syntax and needs to be distinguished to avoid compilation error.
  - src/benchmark_register.h: add missing <limits> inclusion (#1060)
    
    Noticed missing header when was building llvm with gcc-11:
    
    ```
    llvm-project/llvm/utils/benchmark/src/benchmark_register.h:17:30:
      error: 'numeric_limits' is not a member of 'std'
       17 |   static const T kmax = std::numeric_limits<T>::max();
          |                              ^~~~~~~~~~~~~~
    ```
  - Add support for DragonFly BSD (#1058)
    
    Without this commit, compilation fails on DragonFly with the following message:
    
    ```
    /home/mneumann/Dev/benchmark.old/src/sysinfo.cc:446:2: error: #warning "HOST_NAME_MAX not defined. using 64" [-Werror=cpp]
    ^~~~~~~
    ```
    
    Also note that the sysctl is actually `hw.tsc_frequency` on DragonFly:
    
    ```
    $ sysctl hw.tsc_frequency
    hw.tsc_frequency: 3498984022
    ```
    
    Tested on:
    
    ```
    $ uname -a
    DragonFly box.localnet 5.9-DEVELOPMENT DragonFly v5.9.0.742.g4b29dd-DEVELOPMENT #5: Tue Aug 18 00:21:31 CEST 2020
    ```
  - Skip ab/6749736 in stage.
    
    Merged-In: If2054a6ce2b12935109bfbc119161225b31b8897
    Change-Id: Ifbc0a272d787d1fc3bb15238362215d15abb3a86
    
  - Add CycleTimer implementation for M68K architecture (#1050)
    
    As per discussions in here [1], LLVM is going to get backend support on
    Motorola 68000 series CPUs (a.k.a M68K or M680x0). So it's necessary to
    add CycleTimer implementation here, which is simply using `gettimeofday`
    same as MIPS. This fixes #1049
    
    [1] https://reviews.llvm.org/D88389
  - Include github workflows status in README
  - Add support for JSON dumps of benchmark diff reports. (#1042). Fixes #737.
    
    NOTE: This is a fresh-start of #738  pull-request which I messed up by re-editing the commiter email which I forgot to modify before pushing. Sorry for the inconvenience.
    
    This PR brings proposed solution for functionality described in #737 
    
    Fixes #737.
  - Fixed pkg-config on other than Ubuntu GNU/Linux distributions. (#1043)
    
    Signed-off-by: Vitaly Zaitsev <vitaly@easycoding.org>
  - Merge "Add libgoogle-benchmark-main module." am: fedc32dd69
    
    Original change: https://android-review.googlesource.com/c/platform/external/google-benchmark/+/1423810
    
    Change-Id: Ia9abc1b77f15276ba56e3f5efdcd8d893f7e6868
    
  - Bind benchmark builder to Python (#1040)
    
    * Fix setup.py and reformat
    
    * Bind benchmark
    
    * Add benchmark option to Python
    
    * Add Python examples for range, complexity, and thread
    
    * Remove invalid multithreading in Python
    
    * Bump Python bindings version to 0.2.0
    
    Co-authored-by: Dominic Hamon <dominichamon@users.noreply.github.com>
  - Upgrade google-benchmark to beb360d03e2a1a2673d9c2cf408c13b69fdb5627 am: daca24e319
    
    Original change: https://android-review.googlesource.com/c/platform/external/google-benchmark/+/1423976
    
    Change-Id: I28c21942d1723f191149aca609d9bdf1a62490b8
    
  - Add workflow to exercise bindings (#1041)
    
    * Initial version to try to run python bindings example
    
    * python indent issue in setup.py
    
    * better naming
  - Bind more State methods/attributes to Python (#1037)
    
    * Bind Counter to Python
    
    * Bind State methods to Python
    
    * Bind state.counters to Python
    
    * Import _benchmark.Counter
    
    * Add Python example of state usage
    
    Co-authored-by: Dominic Hamon <dominichamon@users.noreply.github.com>
  - Upgrade google-benchmark to 37177a84b7e8d33696ea1e1854513cb0de3b4dc3 am: 1c12faf75d am: cb290e283d am: f6d69ef8c8
    
    Original change: https://android-review.googlesource.com/c/platform/external/google-benchmark/+/1361218
    
    Change-Id: If2054a6ce2b12935109bfbc119161225b31b8897
    
  - Upgrade google-benchmark to d3ad0b9d11c190cb58de5fb17c3555def61fdc96 am: 98780c6c16 am: a089bf3939 am: eb98701d2c
    
    Change-Id: Ida0ce25fa33816f3ac122718a5a84a11e57236bc
    
  - Add license type: Apache2 is a NOTICE license am: a10ead10fe am: 2582e5e5b1 am: e8b2e4758b
    
    Change-Id: Ia1db015ce8d565337f872328aee8758f35dfd410
    
  - Upgrade google-benchmark to a77d5f70efaebe2b7e8c10134526a23a7ce7ef35 am: 6b289c9ae8 am: a96b50d8fb am: 09e7549561
    
    Change-Id: I136ea9a17d1bd4f520efce44d4b52d2df90bdf34
    
  - [automerger skipped] DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp into stag-aosp-master am: 536cb9595c -s ours am: 06ce0294ff
    
    Change-Id: Ia3d2677c369c7add76040d68bbed13cb66d7492d
    
  - Remove redundant NOTICE symbolic link. am: ad59c8bb0b am: 34ec1cc532 am: 07af29b403
    
    Change-Id: I7a88a81bf008fad1ef9ca5976dc30b87bb545d7c
    
  - [automerger skipped] DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp@6304901 into stag-aosp-master am: 5635cb4479 -s ours am: 62268e9aba
    
    Change-Id: Ib600025fe499f5a5000f5f6bf4975b7632cce2c3
    
  - Upgrade google-benchmark to 8e0b1913d4ea803dfeb2e55567208fcab6b1b6c7 am: 1eec37d671 am: 41ed5c22af am: bca58c1bae
    
    Change-Id: Ic5216a2d3df6defb5540c80f03d815a0cc144f17
    

* Update platform/superproject from branch 'master'
  to 831beab1e19156012fc7adb1514c920b37e2ecc7
  - Update git submodules
    
    * Update external/google-benchmark from branch 'master'
      to 846b7549b6b43c6947f53b1e94968558d5a36830
      - Upgrade google-benchmark to dce3322a549650d18f50b5f1428a5942327ab6a5
        
        Test: make
        Change-Id: I07850ca99c79dd2225cb48821200a365b90e4d2c
        
      - Add support for z/OS XL compiler inline asm syntax (#1063)
        
        On s390 architecture, z/OS XL compiler uses HLASM inline assembly, which has different syntax and needs to be distinguished to avoid compilation error.
      - src/benchmark_register.h: add missing <limits> inclusion (#1060)
        
        Noticed missing header when was building llvm with gcc-11:
        
        ```
        llvm-project/llvm/utils/benchmark/src/benchmark_register.h:17:30:
          error: 'numeric_limits' is not a member of 'std'
           17 |   static const T kmax = std::numeric_limits<T>::max();
              |                              ^~~~~~~~~~~~~~
        ```
      - Add support for DragonFly BSD (#1058)
        
        Without this commit, compilation fails on DragonFly with the following message:
        
        ```
        /home/mneumann/Dev/benchmark.old/src/sysinfo.cc:446:2: error: #warning "HOST_NAME_MAX not defined. using 64" [-Werror=cpp]
        ^~~~~~~
        ```
        
        Also note that the sysctl is actually `hw.tsc_frequency` on DragonFly:
        
        ```
        $ sysctl hw.tsc_frequency
        hw.tsc_frequency: 3498984022
        ```
        
        Tested on:
        
        ```
        $ uname -a
        DragonFly box.localnet 5.9-DEVELOPMENT DragonFly v5.9.0.742.g4b29dd-DEVELOPMENT #5: Tue Aug 18 00:21:31 CEST 2020
        ```
      - Add CycleTimer implementation for M68K architecture (#1050)
        
        As per discussions in here [1], LLVM is going to get backend support on
        Motorola 68000 series CPUs (a.k.a M68K or M680x0). So it's necessary to
        add CycleTimer implementation here, which is simply using `gettimeofday`
        same as MIPS. This fixes #1049
        
        [1] https://reviews.llvm.org/D88389
      - Include github workflows status in README
      - Add support for JSON dumps of benchmark diff reports. (#1042). Fixes #737.
        
        NOTE: This is a fresh-start of #738  pull-request which I messed up by re-editing the commiter email which I forgot to modify before pushing. Sorry for the inconvenience.
        
        This PR brings proposed solution for functionality described in #737 
        
        Fixes #737.
      - Fixed pkg-config on other than Ubuntu GNU/Linux distributions. (#1043)
        
        Signed-off-by: Vitaly Zaitsev <vitaly@easycoding.org>
      - Bind benchmark builder to Python (#1040)
        
        * Fix setup.py and reformat
        
        * Bind benchmark
        
        * Add benchmark option to Python
        
        * Add Python examples for range, complexity, and thread
        
        * Remove invalid multithreading in Python
        
        * Bump Python bindings version to 0.2.0
        
        Co-authored-by: Dominic Hamon <dominichamon@users.noreply.github.com>
      - Add workflow to exercise bindings (#1041)
        
        * Initial version to try to run python bindings example
        
        * python indent issue in setup.py
        
        * better naming
      - Bind more State methods/attributes to Python (#1037)
        
        * Bind Counter to Python
        
        * Bind State methods to Python
        
        * Bind state.counters to Python
        
        * Import _benchmark.Counter
        
        * Add Python example of state usage
        
        Co-authored-by: Dominic Hamon <dominichamon@users.noreply.github.com>