Update git submodules
* Update platform/build/blueprint from branch 'master'
  to 5b1a877f0a18a55cab0142e90155fdbb488ff9ca
  - Merge remote-tracking branch 'aosp/upstream' into master
    
    * aosp/upstream:
      Make proptools functions consistently take *struct types
      Add isStruct and isStructPtr helpers
      Fix null pointer dereference printing an expression.
    
    Test: m checkbuild
    Change-Id: I547f3cd5f286edd32efee60a7300c7eabe293e7b
    
  - Merge pull request #281 from colincross/proptools_consistency
    
    Proptools consistency
  - Make proptools functions consistently take *struct types
    
    The proptools functions took an inconsistent variety of
    struct and *struct types.  Some methods even took a struct
    but returned a *struct.  Make all the exported methods
    take a *struct, with internal helpers for the ones that need
    to take a struct.
    
    Test: proptools tests
    Change-Id: I60ce212606e96adcef66c531d57f69c39e1a1638
    
  - Add isStruct and isStructPtr helpers
    
    Test: proptools tests
    Change-Id: I7814b2138cd19b538a3a33036a15119e118d7644
    
  - Merge pull request #280 from asmundak/master
    
    Fix null pointer dereference printing an expression.
  - Fix null pointer dereference printing an expression.
    
    Parser.parseVariable method should always set the value of the variable
    it creates. Failure to do so may end up in the following:
    
    ```
    $ androidmk  <(printf "FOO:=(X)\nFOO:=bar\n")
    parse error:
    <input>:3:1: variable already set, previous assignment: FOO@<input>:1:5 = %!s(PANIC=String method: runtime error: invalid memory address or nil pointer dereference) (%!s(PANIC=String method: runtime error: invalid memory address or nil pointer dereference)) false
    ```
    
    The cause is that calling Parser.Parse to parse `FOO=abc` created
    a Variable instance with nil value, causing panic on print attempt.
    
    Test: m androidmk && androidmk  <(printf "FOO:=(X)\nFOO:=bar\n")
    (should print:
    ERROR:  parse error:
    <input>:3:1: variable already set, previous assignment: FOO@<input>:1:5 = X = Not Evaluated (X = Not Evaluated) false)
    
    Change-Id: I296d7984df6d8796e0075f9eb692b234f8c94f08
    

* Update platform/build/soong from branch 'master'
  to 0326e19b49b90bc1c161a4fca50c2838c2d940d5
  - Merge "Follow input changes to proptools.CloneEmptyProperties"
  - Follow input changes to proptools.CloneEmptyProperties
    
    Test: m checkbuild
    Change-Id: I1fd53d03722d134009f7ed663f05bd6dc5980dd1
    

* Update platform/superproject from branch 'master'
  to 6274cadf97ee52dfac89d1468fe7e42efe72e2e5
  - Update git submodules
    
    * Update build/blueprint from branch 'master'
      to 5b1a877f0a18a55cab0142e90155fdbb488ff9ca
      - Merge remote-tracking branch 'aosp/upstream' into master
        
        * aosp/upstream:
          Make proptools functions consistently take *struct types
          Add isStruct and isStructPtr helpers
          Fix null pointer dereference printing an expression.
        
        Test: m checkbuild
        Change-Id: I547f3cd5f286edd32efee60a7300c7eabe293e7b
        
      - Merge pull request #281 from colincross/proptools_consistency
        
        Proptools consistency
      - Make proptools functions consistently take *struct types
        
        The proptools functions took an inconsistent variety of
        struct and *struct types.  Some methods even took a struct
        but returned a *struct.  Make all the exported methods
        take a *struct, with internal helpers for the ones that need
        to take a struct.
        
        Test: proptools tests
        Change-Id: I60ce212606e96adcef66c531d57f69c39e1a1638
        
      - Add isStruct and isStructPtr helpers
        
        Test: proptools tests
        Change-Id: I7814b2138cd19b538a3a33036a15119e118d7644
        
      - Merge pull request #280 from asmundak/master
        
        Fix null pointer dereference printing an expression.
      - Fix null pointer dereference printing an expression.
        
        Parser.parseVariable method should always set the value of the variable
        it creates. Failure to do so may end up in the following:
        
        ```
        $ androidmk  <(printf "FOO:=(X)\nFOO:=bar\n")
        parse error:
        <input>:3:1: variable already set, previous assignment: FOO@<input>:1:5 = %!s(PANIC=String method: runtime error: invalid memory address or nil pointer dereference) (%!s(PANIC=String method: runtime error: invalid memory address or nil pointer dereference)) false
        ```
        
        The cause is that calling Parser.Parse to parse `FOO=abc` created
        a Variable instance with nil value, causing panic on print attempt.
        
        Test: m androidmk && androidmk  <(printf "FOO:=(X)\nFOO:=bar\n")
        (should print:
        ERROR:  parse error:
        <input>:3:1: variable already set, previous assignment: FOO@<input>:1:5 = X = Not Evaluated (X = Not Evaluated) false)
        
        Change-Id: I296d7984df6d8796e0075f9eb692b234f8c94f08
        
    
    * Update build/soong from branch 'master'
      to 0326e19b49b90bc1c161a4fca50c2838c2d940d5
      - Merge "Follow input changes to proptools.CloneEmptyProperties"
      - Follow input changes to proptools.CloneEmptyProperties
        
        Test: m checkbuild
        Change-Id: I1fd53d03722d134009f7ed663f05bd6dc5980dd1