Update git submodules
* Update platform/external/f2fs-tools from branch 'master'
  to 10e284242e6a522b53b7f17df50e882b111897c0
  - Android.bp: remove include_dir for e2fs libraries
    
    Signed-off-by: Jaegeuk Kim <jaegeuk@google.com>
    Change-Id: I3fa0d6db23584c5242c817e256049a978ec46b84
    
  - Fix dependencies on linux/blkzoned.h when using Bionic.
    
    Test: repo init -b master-art && repo sync
          banchan com.android.art && m
    Bug: 233898800
    Change-Id: Ia3f7128955234706f363b9a267e11e13242b26fc
    
  - Merge remote-tracking branch 'aosp/upstream-master' into aosp
    
    * aosp/upstream-master:
      Check fallthrough in mount.h for Mac
      avoid unnecessary function
      Fix dependencies on linux/blkzoned.h when using Bionic.
      Remove unnecessary config.h
      libzone: remove duplicate header
      Support zoned device if libc exists
    
    Bug: 233898800
    Bug: 233815888
    Signed-off-by: Jaegeuk Kim <jaegeuk@google.com>
    Change-Id: I41415f689155b22a06d023cf91d85dec0f725b65
    
  - Check fallthrough in mount.h for Mac
    
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/os/base.h:128:23: error: missing ')' after 'do'
                          ^~~~~~~~~~~
    external/f2fs-tools/include/f2fs_fs.h:81:24: note: expanded from macro 'fallthrough'
                        ~~ ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/os/base.h:128:22: note: to match this '('
    
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - avoid unnecessary function
    
    libf2fs.c:883:12: warning: unused function 'is_power_of_2' [-Wunused-function]
    
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - Fix dependencies on linux/blkzoned.h when using Bionic.
    
    This reverts commit adcec10b4dee ("Support zoned device if libc exists).
    
    Signed-off-by: Martin Stjernholm <mast@google.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@google.com>
    
  - Remove unnecessary config.h
    
    Instead, we should use <config.h> generated by configure.
    
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - libzone: remove duplicate header
    
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>
    
  - Support zoned device if libc exists
    
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>